### ISSUE TITLE
STRIDE

### ISSUE THREAD

**Issue by fufufanatic** [OWASP/ASVS#100]
Hi Andrew,

Great job with the ASVS thus far.

For Requirement 1.6 on Page 24, the D in STRIDE seems to denote "DISCLOSURE", but I believe it should actually denote "DENIAL OF SERVICE", which is missing as a threat.

Therefore:
Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, Elevation of Privilege (STRIDE).

**Comment by boos** [comment]
You are right, official source is here: https://msdn.microsoft.com/en-us/library/ee823878(v=cs.20).aspx

**Comment by vanderaj** [comment]
Fixed! :)
