### ISSUE TITLE
Drop all requirements that discuss salting

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1002]
ASVS should not be discussing salts at all.  All of the recommended password hashing algorithms salt for you.

https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html

So all references salts should go away in 2.4.X and 2.4.2 should be removed

**Comment by jmanico** [comment]
https://github.com/OWASP/ASVS/issues/1000

**Comment by jmanico** [comment]
This has been merged

**Comment by cmlh** [comment]
The merge should be performed by a different party to that of the requester.
