### ISSUE TITLE
Consider removing requirement for Content-Disposition: attachment; filename header

### ISSUE THREAD

**Issue by NeilMadden** [OWASP/ASVS#1004]
Requirement [14.4.2](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x22-V14-Config.md#v144-http-security-headers) says:

> Verify that all API responses contain a Content-Disposition: attachment; filename="api.json" header (or other appropriate filename for the content type).

It's not clear that this actually prevents any current attack, as RFD attacks are (I believe) prevented by all modern browsers. See also [this related issue](https://github.com/w3c/webappsec-post-spectre-webdev/issues/1) on the W3C Post-Spectre web development spec.

**Comment by elarlang** [comment]
I think this issue is duplicate: https://github.com/OWASP/ASVS/issues/721

**Comment by NeilMadden** [comment]
Quite possibly. I didn’t want to hijack that ticket.

**Comment by jmanico** [comment]
Neil, it's ok to keep the conversation here. You've given a very clear technical reason why the requirement is not helpful and I'm ready for a PR to remove it. If you PR I'll take care of it and handle the label. We're GTG on this.

**Comment by Bankde** [comment]
I'm ok with removing it.

**Comment by jmanico** [comment]
14.4.2 deleted
