### ISSUE TITLE
1.8.X new requirements

### ISSUE THREAD

**Issue by mgeramb** [OWASP/ASVS#1005]
In the EU in particular, the handling of personal data is strictly regulated (DSGVO). I know that with 1.8.2 everything should be fine. But maybe additional requirements makes it more clear.

e.g.:

- Provide functions to delete or anonymize old personal data
- Store only personal data which is required by your business process
- Verify the location (EU, USA, etc) where data is stored match the requirements of the local law

What is your opinion?

Best,
Michael

**Comment by elarlang** [comment]
Just mapping it here.

Current section [Sensitive Private Data](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x16-V8-Data-Protection.md#v83-sensitive-private-data) contains requirements like:
* 8.3.2 Verify that users have a method to remove their data on demand.
* 8.3.9 Verify that users have a method to export their data on demand.

One related issue: https://github.com/OWASP/ASVS/issues/883

**Comment by mgeramb** [comment]
@elarlang  You are right, but I see the first chapter more as guidlines for the architecture and design, while the chapter 8.X is more relevant for the developers. Maybe it makes sense to add some requirements to the architecture part as well.
At least, I can not find anything related to:

- Store only personal data which is required by your business process

**Comment by elarlang** [comment]
Like I wrote, I was just mapping those pieces here, because those belong to the same topic.

In big picture my vision is to move to solution (but I'm not deciding it :) ) where V1 describes architecture and business-logical decisions and other categories have requirements, where you can check are those really implemented. So, this vision is matching with your latest comment well.

To make other's life easier, @mgeramb , can you please provide quotes and references from regulations behind your proposals.

**Comment by mgeramb** [comment]
@elarlang  You mean like this: "Store only personal data which is required by your business process" -> see DSGVO Chapter II, Article 5, (c)"
[DSGVO Enlish](https://www.datenschutz-grundverordnung.eu/wp-content/uploads/2016/04/CONSIL_ST_5419_2016_INIT_EN_TXT.pdf)

**Comment by elarlang** [comment]
Yes, something which support those requirements. Those references are not pre-conditions, but the less conflicts are between different standards and regulations, the easier it is to work with them. And if there is difference, it should be argumented one.

**Comment by jmanico** [comment]
Ping. I think we should drop section 1.8 and merge 1.8.1 and 1.8.2 into section 8.1 and close this out!

**Comment by mgeramb** [comment]
I agree, thank you!
