### ISSUE TITLE
2.30 "proven secure authentication mechanism"

### ISSUE THREAD

**Issue by relaxnow** [OWASP/ASVS#101]
This requirement is very ambiguous and seems to call for 2FA, which seems overly strong for level 1 applications.

See:
http://lists.owasp.org/pipermail/owasp-application-security-verification-standard/2015-October/000897.html
http://lists.owasp.org/pipermail/owasp-application-security-verification-standard/2016-January/000943.html

**Comment by rietta** [comment]
I read that to mean uses good password hashing practices, such as bcrypt rather than unsalted sha1.

**Comment by vanderaj** [comment]
I have removed this item, as it IS too ambiguous, it is untestable, and it's more of a summary of all the other items for that level.
