### ISSUE TITLE
3.3.3 and 3.3.4 are very similar

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1011]
I see that 3.3.3 and 3.3.4 are very similar and clarity is likely needed to make these more sensible.

**Comment by jmanico** [comment]
Also, 3.5.1 overlaps with 3.3.3 and 3.3.4

**Comment by elarlang** [comment]
Helping out with copy-paste, current requirements:

* 3.3.3 Verify that the application gives the option to terminate all other active sessions after a successful password change (including change via password reset/recovery), and that this is effective across the application, federated login (if present), and any relying parties.
* 3.3.4 Verify that users are able to view and (having re-entered login credentials) log out of any or all currently active sessions and devices.
* 3.3.5 Verify that all pages that require authentication have easy and visible access to logout functionality.

**Comment by jsulinski** [comment]
I think the major difference is that 3.3.3 does not require the ability to view active sessions. In my experience, implementation of 3.3.3 is much more common than 3.3.4, and often touches different parts of a code base. I can see a case being made for keeping these separate. 

I agree that 3.5.1 can be rolled into the other two.

**Comment by jmanico** [comment]
I agree @jsulinski - I'm ok if we just dropped 3.5.1 and leave the other two as is.

**Comment by jmanico** [comment]
Yes please @jsulinski

**Comment by cmlh** [comment]
Should 3.5.1 be reworded to verify that Race Condition are not possible against the implementation of OAuth?

**Comment by jsulinski** [comment]
Okay will do!

**Comment by cmlh** [comment]
Has https://github.com/OWASP/ASVS/issues/1011#issuecomment-890269512 already been addressed too?

**Comment by jsulinski** [comment]
Hey @cmlh, I didn't address the comment.

3.5.1 previously read: 

> Verify the application allows users to revoke OAuth tokens that form trust relationships with linked applications.

This doesn't seem related to race conditions. Maybe suggest a new requirement in a new issue if you feel it wouldn't overlap with 1.11.3 and/or 11.1.6?

**Comment by jmanico** [comment]
I agree that 3.5.1 should be returned and was deleted in haste. Thanks for taking the time to explain. cc @elarlang

**Comment by elarlang** [comment]
PR #1128 restores both deleted requirements (3.3.4 and 3.5.1) for now.

If something need to be merged, you can go for it. If it is actually all good, we can just close the issue.
