### ISSUE TITLE
2.3.1 and 2.5.1 are duplicated

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1014]
This can be easily cleaned up

**Comment by elarlang** [comment]
V2.3 Authenticator Lifecycle
* 2.3.1 Verify system generated initial passwords or activation codes SHOULD be securely randomly generated, SHOULD be at least 6 characters long, and MAY contain letters and numbers, and expire after a short period of time. These initial secrets must not be permitted to become the long term password.

V2.5 Credential Recovery
* 2.5.1 Verify that if a system generated initial activation or recovery secret is being sent to the user, it is single-use, time-limited and random.

**Comment by jsulinski** [comment]
It might make sense to either remove the SHOULD/SHALL language or clarify the terms. I believe this is the only section of ASVS that uses the nomenclature, which is pulled for 800-63B.

Following is the definition in 800-63B:

> The terms “SHALL” and “SHALL NOT” indicate requirements to be followed strictly in order to conform to the publication and from which no deviation is permitted.
> 
> The terms “SHOULD” and “SHOULD NOT” indicate that among several possibilities one is recommended as particularly suitable, without mentioning or excluding others, or that a certain course of action is preferred but not necessarily required, or that (in the negative form) a certain possibility or course of action is discouraged but not prohibited.

A potential draft for removal:

V2.3 Authenticator Lifecycle

- 2.3.1 Verify system generated initial passwords or activation codes are securely randomly generated, at least 6 characters long, may contain letters and numbers, and expire after a short period of time. These initial secrets must not be permitted to become the long term password.

**Comment by jmanico** [comment]
Can we add to 2.3.1 that the secret should only be used once?

And can we drop 2.5.1?

**Comment by jsulinski** [comment]
Yes and yes, in my opinion. 

- 2.3.1 Verify system generated initial passwords or activation codes are securely randomly generated, at least 6 characters long, may contain letters and numbers, expire after a short period of time, **and are single-use**. These initial secrets must not be permitted to become the long term password.

**Comment by jmanico** [comment]
Care to submit a PR for this @jsulinski I think we are in agreement here
