### ISSUE TITLE
Clarification needed: what is the point for V5.3.2 (proposed remove)

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1017]
Current [V5.3.2](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x13-V5-Validation-Sanitization-Encoding.md#v53-output-encoding-and-injection-prevention)

> V5.3.2 Verify that output encoding preserves the user's chosen character set and locale, such that any Unicode character point is valid and safely handled.

What is the point for this requirement? Do display all characters correctly? Is it nowadays duplicate for [V14.4.1](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x22-V14-Config.md#v144-http-security-headers)?

> V14.4.1 Verify that every HTTP response contains a Content-Type header. text/*,&nbsp;/+xml and application/xml content types should also specify a safe character set (e.g., UTF-8, ISO-8859-1).

(for improving V14.4.1 there is already issue https://github.com/OWASP/ASVS/issues/788)

**Comment by jmanico** [comment]
I think 5.3.2 needs to go away, its to picky, output encoding libraries handle this fine

**Comment by elarlang** [comment]
Current proposal is to remove this requirement.

I leave this issue opened here for a while to get potential opposite arguments, why it should stay.

**Comment by jsulinski** [comment]
Agree with removal. There are very few CVEs referencing the CWE associated as well.
