### ISSUE TITLE
 2.22 "use a soft token, mobile push, or an offline recovery mechanism."

### ISSUE THREAD

**Issue by relaxnow** [OWASP/ASVS#102]
This seems very strong to require for level 1.

http://lists.owasp.org/pipermail/owasp-application-security-verification-standard/2016-January/000942.html

**Comment by relaxnow** [comment]
Suggest a rewording to:

From: "2.22 Verify that forgotten password and other recovery paths use a soft token, mobile push, or an offline recovery mechanism."
To: "2.22 Verify that forgotten password and other recovery paths are tied to a user's other assets no weaker than a sufficiently strong email link"

See discussion here: http://lists.owasp.org/pipermail/owasp-application-security-verification-standard/2016-January/000949.html

**Comment by vanderaj** [comment]
![image](https://cloud.githubusercontent.com/assets/5029993/16447836/bfff2f16-3dee-11e6-8cfb-38448097a711.png)

Fixed
