### ISSUE TITLE
Use of non-✓ for level

### ISSUE THREAD

**Issue by Sjord** [OWASP/ASVS#1022]
The ASVS level columns generally contain a ✓. There are some exceptions to this, listed below. I propose to make these columns contain ✓ or nothing, and not free-form text. This makes it easier to retrieve a list of requirements for a certain level, and makes it clear which levels every requirement applies to.

| **2.8.7** | Verify that biometric authenticators are limited to use only as secondary factors in conjunction with either something you have and something you know. | | o | ✓ | 308 | 5.2.3 |
| **2.8.8** | [ADDED] Ensure that generation of the time-based multi-factor OTP token is based on the server's system time and not the client's machine. | | o | ✓ | 367 | 5.1.4.2 / 5.1.5.2 |
| **3.3.2** | If authenticators permit users to remain logged in, verify that re-authentication occurs periodically both when actively used or after an idle period. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | 30 days | 12 hours or 30 minutes of inactivity, 2FA optional | 12 hours or 15 minutes of inactivity, with 2FA | 613 | 7.2 |
| **2.10.1** | Verify that intra-service secrets do not rely on unchanging credentials such as passwords, API keys or shared accounts with privileged access. | | OS assisted | HSM | 287 | 5.1.1.1 |
 None
| **2.10.2** | Verify that if passwords are required for service authentication, the service account used is not a default credential. (e.g. root/root or admin/admin are default in some services during installation). | | OS assisted | HSM | 255 | 5.1.1.1 |
| **2.10.3** | Verify that passwords are stored with sufficient protection to prevent offline recovery attacks, including local system access. | | OS assisted | HSM | 522 | 5.1.1.1 |
| **2.10.4** | Verify passwords, integrations with databases and third-party systems, seeds and internal secrets, and API keys are managed securely and not included in the source code or stored within source code repositories. Such storage SHOULD resist offline attacks. The use of a secure software key store (L1), hardware TPM, or an HSM (L3) is recommended for password storage. | | OS assisted | HSM | 798 | |

In 2.8.7 and 2.8.8, the level is "o". This means "Recommended, but not required", according to [this legend](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#legend). This is only used in two requirements, and the legend is specific to the authentication chapter. Furthermore, I think all requirements are recommended, so this doesn't add much information. I propose to remove the "o", and the legend chapter.

3.3.2 has requirements in the levels. I think this is an abuse of the level indicators. I propose to replace these all with ✓. At the start of the section there is already an explanation about the session timeouts.

2.10.2 - 2.10.4 have OS assisted / HSM in the levels, without an explanation anywhere. I propose to replace these with ✓. A description at the start of this section would be fitting.

Alternatively to L1, L2, L3 with ✓, we could make one "level" column with 1, 2, or 3. However, that would also need support from export scripts and other consumers that parse the current format.

**Comment by jmanico** [comment]
I agree 100% this is a good idea. We just need to capture the nuance in the requirement.

**Comment by Sjord** [comment]
> | **3.3.2** | If authenticators permit users to remain logged in, verify that re-authentication occurs periodically both when actively used or after an idle period. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | 30 days | 12 hours or 30 minutes of inactivity, 2FA optional | 12 hours or 15 minutes of inactivity, with 2FA | 613 | 7.2 |

So, for L1 the session can be valid for 30 days. I would say this is not pentestable. Testing this would take 30 days, and in my experience pentests last shorter than that. So this would become a L2 and L3 requirement. Agree?

In that case, we can put a maximum of 12 hours session duration in the requirement. We could also choose either 15 or 30 minutes of inactivity:

> Verify that sessions require reauthentication after at most 12 hours since the start of the session, or after at most 30 minutes of inactivity.

We could also make a requirement for each level:

> Verify that sessions require reauthentication after at most 12 hours since the start of the session, or after at most 30 minutes of inactivity. = L2
> Verify that sessions require reauthentication after at most 12 hours since the start of the session, or after at most 15 minutes of inactivity. = L3

Personally, I don't like that. I would say we allow at most 30 minutes in ASVS, and if people want to be NIST AAL3 compliant, they have to read the NIST spec.

Do we still need a requirement for L1?

**Comment by elarlang** [comment]
One completely different way to solve it:
* one requirement to V1.3 - verify that you have documented policy for session maximum lifetime and maximum inactivity time.
* second requirement for V3.3.2 - verify that the application follows policy for session maximum lifetime and maximum inactivity time.

Problematic part here is still, how to solve the levels issue - if think direction for different levels should be described in V1.3 requirement.

For level1 at the moment I can not see good solution - it must be covered, but I can not see at the moment, how it cam be automatically pentestable.

**Comment by Sjord** [comment]
I propose to change 3.3.2 to L2, L3, with the following requirement:

> Verify that sessions require reauthentication after at most 12 hours since the start of the session, or after at most 30 minutes of inactivity.

should we add "whichever comes first", to make clear that both apply?

I think the level 1 == pentestable is becoming more and more of a problem. Do we want to keep this? Did we already have an issue about this? 

> verify that you have documented policy
> verify that the application follows policy

I think ASVS has to say something about what reasonable values are for session timeout, and not totally leave it up to the developers.

**Comment by tghosth** [comment]
I think that the level columns are too messy anyway and I would prefer changing things so that is just a single column containing 1 2 or 3. That would be one of the last things we do though.

@elarlang what is the next action here?

**Comment by tghosth** [comment]
I am going to close this for now as it will be dealt with when the level column is simplified.
