### ISSUE TITLE
Don't collapse spaces in 2.1.1 and 2.1.3

### ISSUE THREAD

**Issue by Sjord** [OWASP/ASVS#1029]
Currently, we recommend/allow collapsing multiple spaces:

[ASVS](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#:~:text=2.1.1):
> 2.1.1. Verify that user set passwords are at least 8 characters in length (after multiple spaces are combined).
>
> 2.1.3 Verify that password truncation is not performed. However, consecutive multiple spaces may be replaced by a single space.

This originates from [NIST](https://pages.nist.gov/800-63-3/sp800-63b.html#a3-complexity:~:text=spaces%20themselves):
> Spaces themselves, however, add little to the complexity of passwords and may introduce usability issues (e.g., the undetected use of two spaces rather than one), so it may be beneficial to remove repeated spaces in typed passwords prior to verification.

I propose to remove this option. Passing the password directly to the hash function is better than doing custom post-processing on it first. I think entering multiple spaces is not very common. I don't think that spaces are special from any other character in this regard. NIST is not very clear on the advantages of collapsing spaces. I also don't agree that spaces add little to the complexity of passwords. A bug in the space collapsing function could remove part of the password, or result in denial-of-service when faced with long passwords.

So I propose:
> 2.1.1. Verify that user set passwords are at least 8 characters in length.
>
> 2.1.3 Verify that passwords are not truncated.

**Comment by elarlang** [comment]
Personally I agree with this proposal - the question is, how precisely ASVS should be aligned with NIST.

Alternative is - alert user when multiple spaces are used in UI side, then it's up to user's choice to use them or not.

**Comment by jmanico** [comment]
I agree as well. What a weird requirement.

That’s three of us. Can I get a PR please? :)

**Comment by jmanico** [comment]
Off topic: Elar and Sjoerd. Can we give you a title of ASVS lead contributor or similar to acknowledge your work here?

**Comment by Sjord** [comment]
I created a [PR](https://github.com/OWASP/ASVS/pull/1030). 

> Can we give you a title of ASVS lead contributor or similar to acknowledge your work here?

I don't care much about titles, but thank you for recognizing my contribution.

**Comment by elarlang** [comment]
@jmanico - any reason to not merge created PR?

**Comment by jmanico** [comment]
Merged
