### ISSUE TITLE
Symbols in tables in Word 2011 on Mac OS X (latest patch level)

### ISSUE THREAD

**Issue by rietta** [OWASP/ASVS#103]
Some of the tables appear to use a different character for the checkmarks that does not render in my copy of Word 2011 on Mac OS X. Not sure if it is an OS or Word thing since I seldom use Office.
![screen shot 2016-01-27 at 8 14 45 am](https://cloud.githubusercontent.com/assets/605406/12614462/26705cc4-c4ce-11e5-95a5-139b6ef7b075.png)

Other tables visually appear fine, such as:
![screen shot 2016-01-27 at 8 14 55 am](https://cloud.githubusercontent.com/assets/605406/12614497/5a09f374-c4ce-11e5-9b3c-f426e2ac9754.png)

**Comment by vanderaj** [comment]
Fixed. Thanks for that (Google Docs -> Word conversion issue).
