### ISSUE TITLE
v4.0.3 - Translate to Portuguese (pt-br)

### ISSUE THREAD

**Issue by edusantos33** [OWASP/ASVS#1033]
Hello everyone!

I'd like to start the translation ofthe ASVS project to Brazilian Portuguese, however I think that Portugal Portuguese is great too!
What I need to do?
Clone the project and start the translation using markdown and when finish it to do a PR, right?

**Comment by srjsoftware** [comment]
Hi, @edusantos33. I've translated 100% of L1 controls to Brazilian Portuguese (It needs a lot of revision). It's on my github page.

**Comment by elarlang** [comment]
Hi @edusantos33 and @srjsoftware - do you have some progress with translation and is in state worth sharing with others?

If you would like to start or update, it makes sense to use v4.0.3 as a base and translate markdown files. If you need any help with setup the workflow, please ask.

**Comment by srjsoftware** [comment]
Hi @elarlang I have a partial translation of 4.0.2 (only L1 controls and a few other parts). 
I've talked to @edusantos33 and we are going to use 4.0.3 from now on.

**Comment by tghosth** [comment]
Since we now have a proposed Portuguese translation, I am going to highlight this issue for that.

The original PR was #1475 and there was some back and forth between @elarlang and @cesarkohl to fix various points there. @cesarkohl addressed the issues and then I requested another PR because the currently PR changed various other things which I did not want to happen.

@cesarkohl opened this as #1534.

**Comment by tghosth** [comment]
#1534 was merged into a [temporary branch](https://github.com/OWASP/ASVS/tree/master-pt-translation).

@elarlang please can you perform any additional checks you want to do on this branch and I can then generate the outputs.

**Comment by cesarkohl** [comment]
@elarlang Please let me know if there's anything else I can do to finish the process.

It was worth a shot working on this translation, can't wait to see it merged! 😃

**Comment by elarlang** [comment]
Hi, @cesarkohl - all good from your side.

I rechecked the structure, made whitespace correction (and mistakes myself), then rechecked and found my mistakes (V4 content to V1), then validated and rechecked again and should be ok now.

Follow progress in #1535

**Comment by cesarkohl** [comment]
@elarlang Great, I read all commits. Thanks!
