### ISSUE TITLE
JWT Secure best practices

### ISSUE THREAD

**Issue by csfreak92** [OWASP/ASVS#1038]
Do we have a requirement for JWT secure best practices such as checking of algorithm (definitely should not be set to none), ensuring expiration of tokens, checking of issuer, etc? I keep looking for them but it seems the closest one we have was mentioned in #839 and it was pertaining to requirement 3.5.3 - `Verify that stateless session tokens make use of digital signatures to protect against tampering.` 

There is nothing specific for JWTs, so maybe this is a good idea for developers to have in mind as part of their secure coding checklist. I've seen applications using JWTs but tokens are not being used properly as with expiration, decoded claims contain information that can be modified and result to gaining admin access or cross-user access (IDORs), bypass authentication mechanisms, etc. If we have anything else, then maybe I was just mistaken in reading most of the ASVS requirements.

**Comment by csfreak92** [comment]
Placing this RFC here for reference: https://datatracker.ietf.org/doc/html/rfc8725

**Comment by jmanico** [comment]
839 is all we have and I would love to see more. Bring it on!

**Comment by jmanico** [comment]
Would you care to help us convert this to requirements?

**Comment by csfreak92** [comment]
Definitely! I will place it here as comments first before submitting a PR.

**Comment by cmlh** [comment]
Can [RFC8725](https://datatracker.ietf.org/doc/html/rfc8725) be forked from ASVS as JWT is specific to JSON (unless [RFC8725](https://datatracker.ietf.org/doc/html/rfc8725) can be made generic and therefore applicable to all technologies)?

**Comment by csfreak92** [comment]
Sounds like a great idea, let me draft it and place it here, thanks for pointing that out @cmlh!

**Comment by csfreak92** [comment]
Draft/Proposal for JWT secure best practices:  

`1) Verify expiration of JWTs are checked in the backend service (e.g. exp - expiration time and iat - issued before current time). `
`2) Verify that algorithm validation is being done by the backend service for the JWTs used and as such it should not accept "None" value in the algorithm section. `
`3) Verify proper validation of the JWT payload claims are done by the backend service (e.g. iss - valid issuer, sub - subject, aud - audience, etc). `
`4) Verify that signatures of JWTs are present in the claims to add more protection from tampering. (JWS-JSON Web Signature) `

@jmanico These are the most common and obvious ones I can think of about JWT security. There are more, but I would like to hear from the community about their thoughts which ones should be added to it. Sorry, it took me a while to draft this. For the numbering, let's talk about that later but I was thinking these requirements should go under `V3.5 Token-based Session Management` unless you have other ideas?

**Comment by jmanico** [comment]
This is a fantastic and needed addition. Let's PR please! :) cc @csfreak92
