### ISSUE TITLE
ASVS 2.02 Password echo text

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#104]
The text is not really clear when this is an issue. 

Verify all password fields do not echo the user’s password when it is entered

Should become

Verify all password fields do not echo the user’s credentials

**Comment by rietta** [comment]
This is an interesting point. But I think your guidance would be more confusing to developers than the specific guidance on passwords. What other credential do you imagine should be barred from being echoed as a whole?

**Comment by rietta** [comment]
And I could specifically make an argument that usability matters for password entry as well. Though a web app implementor may not run into it, I am appreciative as a user on a mobile interface to be able to see the password that I am entering when I know no one is surfing over my shoulder.  This is especially so with long passphrases that are prone for typos.

**Comment by vanderaj** [comment]
![image](https://cloud.githubusercontent.com/assets/5029993/16446733/532e85e4-3de9-11e6-9a02-17531a2f1369.png)

Fixed. There is a new entry about autocomplete and password managers.

**Comment by Bookerman** [comment]
In the "What Ever Happened To..." category:

In this Github repository the MS-Word .docx copies of ASVS 2015 v2.1 and the ASVS June 2015 v3.0.1 [sic] have this:
V2: Authentication Verification Requirements
Requirement 2.2 reads "Verify all password fields do not echo the user’s password when it is entered."
and
The ASVS June 2016 v3.0.1 has this:
V2: Authentication Verification Requirements
Requirement 2.2 reads "Verify that forms containing credentials are not filled in by the application. Pre-filling by the application implies that credentials are stored in plaintext or a reversible format, which is explicitly prohibited."

This is a significant difference. I can understand that it is accepted practice to be able to toggle show/hide password on mobile apps, effectively deprecating this requirement v2.2, but should it not have been deprecated out of hand for ASVS version 3, and a new V2.xx requirement assigned for this so as to avoid confusion? Also, it would be nice to have an explanation somewhere in the "What ever happened to..." appendix.
