### ISSUE TITLE
Proposal for 7.1.3

### ISSUE THREAD

**Issue by drwetter** [OWASP/ASVS#1040]
In [7.1.3](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x15-V7-Error-Logging.md#v71-log-content) I would rather suggest to split this point into auth related and other logging events. And if I may suggest I would also like to see auth related logging in Level 1 like (shortened):

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---:| :---: | :---: |
|*7.1.3*| Verify that the application logs security relevant events including successful and failed authentication events, access control failures | ✓ | ✓ | ✓ | 778 |
|*7.1.5*| Verify that the application logs security relevant events including deserialization failures and input validation failures |  | ✓ | ✓ | 778 |

CWE # probably is the same.

Reason: One is the enry/door to the whole thing (most of the time). I feel logging here should  have more relevance.

Let me know if I should submit a PR.

For 7.1.5. another suggestion would be to add file uploads (haven't found logging for those).

**Comment by elarlang** [comment]
I think this discussion is duplicate / should belong to #997

**Comment by drwetter** [comment]
@elarlang : you need to tell pls me what you expect from me as you assigned me : PR or continue discuss this in #997 ?

**Comment by elarlang** [comment]
I think we can keep related discussions in #997. Assignment was just for traceability.
