### ISSUE TITLE
Links in PDF that include a fragment are broken

### ISSUE THREAD

**Issue by avioli** [OWASP/ASVS#1043]
- [x] Please search the issues in case your question has been discussed before.
- [x] Make sure you are looking at the latest edits at: https://github.com/OWASP/ASVS/tree/master/4.0

As stated in the title of this issue - hyper-links in the PDF that include a fragment are broken, since the fragment prefix is rendered as `%23`, but should be `#`.

An example is [2.1.1] where C6 at the end of the Description is a hyperlink:

<img width="734" alt="An example showing a screenshot of the hyperlink as a tooltip" src="https://user-images.githubusercontent.com/524259/128649558-26c42181-d3c7-4d57-b6aa-d5d6714b0b09.png">

Clicking such a link opens the browser (Firefox in my case, but all handle it the same), showing a 404 - Not found page.

 - incorrect: [https://owasp.org/www-project-proactive-controls/%23div-numbering](https://owasp.org/www-project-proactive-controls/%23div-numbering)
 - correct: [https://owasp.org/www-project-proactive-controls/#div-numbering](https://owasp.org/www-project-proactive-controls/#div-numbering)

I wasn't able to find how the PDF files are generated to suggest any fixes, but my best guess is - manually from the docx file. This is a good place to note that the docx doesn't have this issue.

**Comment by lfservin** [comment]
In the pdf files generated with the makefile (check out the makefile branch), the problem is not there. Merging that branch into master would get rid of this problem.
![image](https://user-images.githubusercontent.com/1721414/129521149-d2e4803f-b033-46b9-a64b-8a66da4106c1.png)

**Comment by avioli** [comment]
Was this comment directed to somebody else? I don't see a `makefile` branch.

**Comment by ike** [comment]
@avioli -- perhaps it's the [`owasp-makefile`](https://github.com/lfservin/ASVS/tree/owasp-makefile) branch on @lfservin's fork?

**Comment by lfservin** [comment]
Yes, that is what I meant. I've made a pull request #815 and there the problem isn't present.
