### ISSUE TITLE
14.2.5 Verify that an inventory catalog is maintained of all third party libraries in use.

### ISSUE THREAD

**Issue by Sjord** [OWASP/ASVS#1066]
[ASVS/0x22-V14-Config.md at master · OWASP/ASVS](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x22-V14-Config.md#v142-dependency)

> 14.2.5 Verify that an inventory catalog is maintained of all third party libraries in use.

What is the goal of this? Isn't this just the package-lock.json in the project? What is this inventory catalog meant for? If the inventory catalog is maintained, but never used for anything, it doesn't really help.

**Comment by coderpatros** [comment]
> Isn't this just the package-lock.json in the project?

For a lot of ecosystems the package manifest is not necessarily what will be resolved and included in the build. Especially if the version in the manifest specifies a version constraint as opposed to a specific version.

There's also an ecosystem where the package lock file information is only enforced when restoring packages, not when resolving packages during the build.

**Comment by jmanico** [comment]
I really do not want to keep long term issues dangling. Can we please leave this closed for now since the original issue is resolved?

At the very least, if you want something new added let’s open a new issue and track these things discretely.

Is this acceptable?

**Comment by coderpatros** [comment]
> We'll also need to settle the following proposals too?

I probably wouldn't focus on specific formats (as much as I'd love a reference to CycloneDX). But rather what information is being included in the SBOM. It might make sense to just reference the V2 L1-3 requirements in SCVS https://owasp-scvs.gitbook.io/scvs/v2-software-bill-of-materials

**Comment by jmanico** [comment]
Patrick,

Would you care to give a PR a go for this? Or give us a suggestion as to 
the enhanced text for this requirement?
