### ISSUE TITLE
Add breached password references to section 2.1

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1071]
Resources to consider:

https://github.com/danielmiessler/SecLists/tree/master/Passwords

https://www.ncsc.gov.uk/blog-post/passwords-passwords-everywhere#:~:text=PwnedPasswordsTop100k.txt 

cc: @cmlh

**Comment by tghosth** [comment]
@jmanico the current requirement says (emphasis mine):

> Verify that passwords submitted during account registration or password changes are checked against a set of breached **username**/password pairs. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering))

**Comment by jmanico** [comment]
I am happy to move this to just "breached passwords" only.

**Comment by tghosth** [comment]
@jmanico opened PR #1234
