### ISSUE TITLE
Update 14.2.5 to reference SCVS V2 requirements

### ISSUE THREAD

**Issue by coderpatros** [OWASP/ASVS#1072]
[14.2.5](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x22-V14-Config.md#v142-dependency) has been updated to require an SBOM for all third party components. Without specifying what information should be captured in the SBOM.

I'd like to suggest that this requirement references [SCVS V2 L1-3 requirements](https://github.com/OWASP/Software-Component-Verification-Standard/blob/master/en/0x11-V2-Software_Bill_of_Materials.md). Although noting, in SCVS, a minimal SBOM is considered a foundational L1 requirement.

**Comment by jmanico** [comment]
This sounds like a good idea. What do you think the adjusted

**Comment by cmlh** [comment]
I'd prefer we integrate directly SCVS in its entirety into ASVS instead @coderpatros 

This would also be a great and similar example of integrating a fork discussed within https://github.com/OWASP/ASVS/issues/956 too @jmanico.

**Comment by coderpatros** [comment]
Will do. I just want to clarify scope.

Is this just to reference SCVS V2 SBOM requirements?

If so, the only issue I see is that ASVS and SCVS don't currently align on L1 requirements.

ASVS only requires an SBOM for L2. But, IMHO, knowing the 3rd party components in your software should be a L1 requirement. Noting that there is no prescribed format specified by SCVS. i.e. some ecosystems have package lock files that clearly define the _actual_ components used and can be used to meet this requirement.

**Comment by cmlh** [comment]
> ASVS only requires an SBOM for L2. But, IMHO, knowing the 3rd party components in your software should be a L1 requirement. Noting that there is no prescribed format specified by SCVS. i.e. some ecosystems have package lock files that clearly define the _actual_ components used and can be used to meet this requirement.

"_ASVS Level 1 is for low assurance levels, and is completely penetration testable_" to quote https://github.com/OWASP/ASVS/blob/master/4.0/en/0x03-Using-ASVS.md#application-security-verification-levels

Inspecting the SBOM would not be the norm during a penetration test at this point in time @coderpatros
