### ISSUE TITLE
Generated PDF Versions

### ISSUE THREAD

**Issue by ike** [OWASP/ASVS#1077]
The recent changes in #815 introduce two PDF versions. Is this correct? I have attached the two versions here for ease of reference. 

New version: [OWASP Application Security Verification Standard 4.x2.pdf](https://github.com/OWASP/ASVS/files/7355912/OWASP.Application.Security.Verification.Standard.4.x2.pdf)

Existing version: [OWASP Application Security Verification Standard 4.x.pdf](https://github.com/OWASP/ASVS/files/7355913/OWASP.Application.Security.Verification.Standard.4.x.pdf)

**Comment by jmanico** [comment]
Let’s go with Eisvogel!

**Comment by ike** [comment]
This would be closed by #1120

**Comment by lfservin** [comment]
@jmanico this issue has been closed. could you mark it as closed, please?
The discussion is now moved to #1120
