### ISSUE TITLE
Create 5.0 directory

### ISSUE THREAD

**Issue by ike** [OWASP/ASVS#1079]
A 5.0 directory should be created to hold new work, and 4.0 should reflect the state of the last release.

**Comment by elarlang** [comment]
I think we need Josh here, as he has been our git guru and vision guy.

**Comment by elarlang** [comment]
Well, all the commits and PR merges should be on hold till 5.0 is created, otherwise it will be proper mess :)

**Comment by ike** [comment]
100%, that would be a real snarl

**Comment by jmanico** [comment]
There are very few PR’s - I’m away from my computer today. Elar pleas go ahead and merge as you see fit! You have merge access, right?

**Comment by jmanico** [comment]
Why are you using a double negative?

**Comment by elarlang** [comment]
Agree with folder structure, I shared the same opinion in commenting related PR:
https://github.com/OWASP/ASVS/pull/1080#issuecomment-944966812

**Comment by elarlang** [comment]
Do I understand correctly that we drop current PR (#1080) and we go with plan like @tghosth [described](https://github.com/OWASP/ASVS/issues/1079#issuecomment-945552042)?

Otherwise I think we are a bit in _dead-lock_ situation. I would like to make fixes to labels, but then it makes extra work for every other step.

**Comment by jmanico** [comment]
I assume these three things were part of Josh's rollout to 4.03.

**Comment by ike** [comment]
> Do I understand correctly that we drop current PR (#1080) and we go with plan like @tghosth [described](https://github.com/OWASP/ASVS/issues/1079#issuecomment-945552042)?

This was my understanding, yes. This PR (#1080) will become either step 2 or step 3 of the plan.

**Comment by tghosth** [comment]
Hi @ike, did we not say that we would be keeping the file history when we moved to 5.0? It looks like that is not visible in GitHub...

![image](https://user-images.githubusercontent.com/13623828/152218351-f2bd9b68-114b-4fa6-870b-12d30b86da36.png)

**Comment by ike** [comment]
@tghosth -- yes, the history is still there, although Github does not show it. Using the `--follow` flag, you can see the history on your local copy. This is a feature that has been [asked for](https://github.com/github/feedback/discussions/3272) in Github for a [long time](https://github.com/isaacs/github/issues/900).

```
git log --follow <path>
```

**Comment by tghosth** [comment]
Thanks for the response on this @ike. Frustrating that Github doesn't support it 🤦‍♂️
