### ISSUE TITLE
duplicates: 1.5.2 and 5.5.3

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1084]
[V1.5.2](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x10-V1-Architecture.md#v15-input-and-output-architecture) Verify that serialization is not used when communicating with untrusted clients. If this is not possible, ensure that deserialization is performed safely, for example by only allowing a white-list of object types or not allowing the client to define the object type to deserialize to, in order to prevent deserialization attacks.
* Levels: 2, 3
* CWE: 502
* Previously related issue: https://github.com/OWASP/ASVS/issues/772 (assigning @tghosth @csfreak92 )

[V5.5.3](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x13-V5-Validation-Sanitization-Encoding.md#v55-deserialization-prevention) Verify that deserialization of untrusted data is avoided or is protected by filtering incoming deserialization data.
* Levels: 1, 2, 3
* CWE: 502

First recommendation is that we drop 1.5.2 and if needed, content update 5.5.3.

If 1.5.2 need to stay, then:

  * "Verify that serialization is not used" > "Verify that **deserialization** is not used" ?
  * replace _white-list_ with something like allow-list

**Comment by jmanico** [comment]
https://github.com/OWASP/ASVS/pull/1095
