### ISSUE TITLE
Need cleanup of 4.3.1 - suggest simplifying

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1086]
We already cover MFA elsewhere, this should really be about isolation admin interfaces or other topics.

4.3.1 | Verify administrative interfaces use appropriate multi-factor authentication to prevent unauthorized use.
-- | --

**Comment by cmlh** [comment]
I just did a search for "MFA" in the 4.0.2 PDF and it's not directly specified as a requirement @jmanico but is mentioned six (6) times in the 4.0.2 PDF

Should we just remove the the strikethrough text as "Verify administrative interfaces ~~use appropriate multi-factor authentication to~~ prevent unauthorized use." or something else?

**Comment by jmanico** [comment]
How about this? Nice and simple.

4.3.1 | Verify administrative interfaces are isolated from the main application in order to prevent unauthorized use.
-- | --

**Comment by jmanico** [comment]
After considering @starbuck3000 how about:

4.3.1 - Verify administrative interfaces only accept connections from trusted endpoints (e.g., admin workstation, bastion/jumphost, separate domain, intranet access only, etc).

**Comment by starbuck3000** [comment]
@jmanico : yes, looks all good to me. 

p.s. Just a little period (.) missing after the 'etc' :)

**Comment by jmanico** [comment]
Hey @elarlang is this ok with you?

4.3.1 - Verify administrative interfaces only accept connections from trusted endpoints (e.g., admin workstation, bastion/jumphost, separate domain, intranet access only, etc.).

**Comment by mgargiullo** [comment]
@jmanico  I liked your list of possible solutions with "accept connections from trusted endpoints" as one of the options.

**Comment by jmanico** [comment]
How about this one?

4.3.1 - Verify administrative interfaces only accept connections from trusted endpoints such as the use of a bastion or jump host, or by limiting access to only admin workstations, or by providing admin functionality on a separate domain from other users, or by only allowing admin access via an intranet.

**Comment by tghosth** [comment]
hi @jmanico, the suggestions says "providing admin functionality on a separate domain from other users" (assuming we are talking about a web domain like https://admin.example.com). Do you think that is an example of "only accept connections from trusted endpoints."? It feels like there is a mis-match between those two things...

**Comment by jmanico** [comment]
How about...

4.3.1 - Verify administrative interfaces are isolated from the main application and only accept connections from trusted endpoints. Examples include using a bastion or jump host, limiting access to only admin workstations, providing admin functionality on a separate domain from other users, or only allowing admin access via an intranet.

**Comment by tghosth** [comment]
@jmanico 

Minor modification to change "and" to "or":

> 4.3.1 Verify administrative interfaces are isolated from the main application **or** only accept connections from trusted endpoints. Examples include using a bastion or jump host, limiting access to only admin workstations, providing admin functionality on a separate domain from other users, or only allowing admin access via an intranet.

@cmlh:

I am not sure I understand what you mean.

**Comment by tghosth** [comment]
@jmanico do you agree with my minor change here: https://github.com/OWASP/ASVS/issues/1086#issuecomment-1195694482

**Comment by elarlang** [comment]
Reason for "keep the and" and do not use or. Even if you accept connections only from trusted endpoints then:
* in "XSS" situation those are on the same Origin and vulnerability most likely gives options to escalate to higher privileges functionality
* for accessing resources via API/DB/etc accounts it gives danger that "public web site" uses same level permissions as administrative part of the site. It is more secure to keep them separately with separate accounts and permissions for internal/external resources

"or only allowing admin access via an intranet" - limiting access only to intranet is takes down some likelihood, but on the other hand it is a bit in conflict with Zero Trust philosophy ([NIST Special Publication (SP) 800-207, Zero Trust Architecture](https://www.nccoe.nist.gov/projects/implementing-zero-trust-architecture)). ZTA does not say "do not use intranet", but just "don't relay on it"

**Comment by jmanico** [comment]
> Reason for "keep the and" and do not use or. Even if you accept connections only from trusted endpoints then:
> 
> * in "XSS" situation those are on the same Origin and vulnerability most likely gives options to escalate to higher privileges functionality
> * for accessing resources via API/DB/etc accounts it gives danger that "public web site" uses same level permissions as administrative part of the site. It is more secure to keep them separately with separate accounts and permissions for internal/external resources
> 
> "or only allowing admin access via an intranet" - limiting access only to intranet is takes down some likelihood, but on the other hand it is a bit in conflict with Zero Trust philosophy ([NIST Special Publication (SP) 800-207, Zero Trust Architecture](https://www.nccoe.nist.gov/projects/implementing-zero-trust-architecture)). ZTA does not say "do not use intranet", but just "don't relay on it"

This is a good argument, Elar. I'm personally ok with "and" or "or".  I prefer and. Or what you prefer. Either-or works for me.

**Comment by tghosth** [comment]
Ok I opened a PR with "and"

**Comment by elarlang** [comment]
I approved/merged PR, but ...

>  "Verify administrative interfaces are isolated from the main application ..."

I wonder is clear and actionable - like what mean "isolated from the main application"?

**Comment by tghosth** [comment]
Would you prefer something like:

> Verify that administrative interfaces are **logically separated** from the main application

That is still vague but it gives slightly more direction whilst still allowing flexibility.

**Comment by starbuck3000** [comment]
Reading this one year after my previous comment, I still suggest removing the isolation/separation part. 

Isolation (whatever it means) is an architecture/design pattern that can be implemented in response to a security requirement, it is not a security requirement by itself, unless we start telling the world how applications should be designed. 

It seems to me that this discussion arises from the ambiguity I often observe in security specifications on what constitutes unauthorized access to an administrative interface. If we compare this with a door lock: I cannot tell from our discussion whether we are trying make sure that a door lock cannot be bypassed/breached by intruders, or whether we are trying to prevent intruders from reaching the lock that holds access to the asset.

In the first case, there is no causation at all for isolation: a security control focused on ensuring that any interaction to an administrative interface undergoes proper access control (triple A, or authenticate / authorize / audit) is sufficient, isolation doesn't bring anything more.

If the second scenario is our concern, there is some causation for isolation. But "isolation" is only one of many possible design options: an architect could also choose to require a trusted IP origin, or to extend authentication to the client endpoint/device itself, to enforce hardware security key authentication, etc. "Isolation" is only one possible response to the threat we are trying to address. As such, I think it should not be part of the requirement but part of the possible answers to the requirement, i.e., listed as one of many possible answers.

I strongly believe that one of main ASVS's strengths resides in its agnostic approach to application design. It is rather through the evaluation of a design proposal that one should assert whether or not the proposal satisfies the ASVS requirement, whatever it looks like.

Consequently, my proposition: 
4.3.1 - Verify administrative interfaces can only be logically reached from trusted endpoints or locations. Examples include restricting access to authorized endpoints and/or networks (e.g., bastion or jump host, trusted admin workstation or endpoint, admin LAN, etc.).

First, this proposition acknowledges a design based on isolation, but also acknowledges other design proposals, which may satisfy the base requirement. Second, this proposition gets rid of the ambiguity behind "unauthorized access" (which is typically addressed through proper access control) by using the concept of "trusted" endpoints and networks.

**Comment by starbuck3000** [comment]
Thank you @tghosth for your review and improved version, all good for me!

**Comment by tghosth** [comment]
Opened #1407, @elarlang please review :)
