### ISSUE TITLE
Secure development environments

### ISSUE THREAD

**Issue by coderpatros** [OWASP/ASVS#1108]
Not sure this type of thing would be considered in scope or not.

But containerised, reproducible, ephemeral, development environments are now becoming more commonplace. i.e. Gitpod and GitHub Codespaces.

A see them as a natural next step after doing the same for build environments. i.e. the current requirements for V14.1 Build cover.

Any opinions on this?

**Comment by cmlh** [comment]
If I was still preforming https://www.cyber.gov.au/acsc/view-all-content/programs/australian-information-security-evaluation-program and therefore is what Mike Boberski based ASVS ToV on (i.e. Common Criteria) then I'd inspect https://github.com/OWASP/Software-Component-Verification-Standard in addition to https://github.com/OWASP/ASVS/blob/master/4.0/en/0x22-V14-Config.md#v142-dependency

I'll raise a separate issue to explore the differences between https://github.com/OWASP/Software-Component-Verification-Standard to that of https://github.com/OWASP/ASVS/blob/master/4.0/en/0x22-V14-Config.md#v142-dependency (if any) as the first step before a PR unless @coderpatros knows this already and therefore I'll support his Pull Request to list these requirements as L3 too.

**Comment by elarlang** [comment]
For ASVS scope discussion we have #1127 now.

**Comment by tghosth** [comment]
I think this is a good question which will really depend on the outcome of #1127

**Comment by tghosth** [comment]
In the meantime, @coderpatros what sort of requirements would you expect to see in relation to this?

**Comment by tghosth** [comment]
Note that I made another comment on https://github.com/OWASP/ASVS/issues/1127#issuecomment-1193352560

**Comment by elarlang** [comment]
Thank you for ideas and feedback, I'm closing this one.
