### ISSUE TITLE
Update bleeding edge labels for 5.0 release

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1122]
(just issue for references)

My own tasks, so you know that there is work in progress with those:

* [x] update labels in _bleeding edge_ compared to released v4.0.3 (at the moment those are compared to v4.0.2)
* [x] more detailed description of used labels and why we use labels

**Comment by jmanico** [comment]
I just renamed the title here for clarity, thank you for this. The label system ended up being super useful and I appreciate it.

**Comment by jmanico** [comment]
May I suggest that you remove your note on 4.04 or 4.1, I really would not like to suggest those in public.
