### ISSUE TITLE
Translate to Spanish

### ISSUE THREAD

**Issue by hansphp** [OWASP/ASVS#1129]
As of pr #911, we worked with @CarlosAllendes in the following adjustments to finally finish in a complete revision of version 4.0.3.

not to start from scratch and preserve the valuable work that was done. The starting point was the pr #911 through "Cherry Pick".

It was translated up to version 4.0.3 and the following revisions were made.

- Spanish language conventions
- Revised against Latin American conventions
- Proper use of anglicisms
- latin voice overs
- and some translations that its literal form sounds bad in Spanish.

Although everything is perfectible, we did the best we could trying to maintain the integrity of the idea to be transmitted.

Thanks

**Comment by elarlang** [comment]
Hi, thank you for translation!

Please give us some time to implement clear process for getting translation into ASVS. 
It includes some git branching instructions, markdown format validation etc.

**Comment by elarlang** [comment]
@hansphp - do you have experience and knowledge, who is using ASVS translations? I would like to be sure, that proposed new process fits their actual needs.

**Comment by hansphp** [comment]
Of course, @CarlosAllendes and I used the translation to train some development teams about the S-SDLC in Chile and 
 Mexico.

**Comment by hansphp** [comment]
Please, delete or discard the binary file "44.0/OWASP Application Security Verification Standard 4.0.2-es.pdf" that was passed with the changes but was not generated with the process or with the md files corresponding to 4.0.3.

Everything else is correct

**Comment by tghosth** [comment]
Merged in #1130
