### ISSUE TITLE
Update Project Web Pages on owasp.org

### ISSUE THREAD

**Issue by cmlh** [OWASP/ASVS#1133]
We need to update all the web page[s] on owasp.org as https://owasp.org/www-project-application-security-verification-standard/#div-acknowledgements hasn't been updated since v3 for example

Can this reoccurring task be added to the https://github.com/OWASP/ASVS/projects for each minor/major release please?

**Comment by elarlang** [comment]
This page and information was probably valid and needed when ASVS was not kept in github. Now everything is in github and I don't see the point to duplicate it there.

In my opinion we can keep only "main" page and if we need "news and events", then it would be nice to but this release history on that page as well.
