### ISSUE TITLE
2.5.3 "do not send plain-text password on password recovery" is covered by password hashing

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1134]
Requirement [2.5.3](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x11-V2-Authentication.md#v25-credential-recovery)

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---:| :---: | :---: | :---: |
| **2.5.3** | Verify password credential recovery does not reveal the current password in any way. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | ✓ | ✓ | ✓ | 640 | 5.1.1.2 |

If password is not stored in plain-text, it means hashing is used correctly like required by other requirement (2.4.1), then what 2.5.3 actually asks or how it can happen?

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---:| :---: | :---: | :---: |
| **2.4.1** | [MODIFIED] Verify that one of the following password hashing functions is used when storing passwords: argon2id, scrypt, bcrypt or PBKDF2. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 916 | 5.1.1.2 |

# Proposals

## v5.0
Delete current 2.5.3.

## v4.0.4

2.5.3 is level 1 and 2.4.1 is level 2, it would be breaking change (if do not consider it just an error). Can fix CWE to something more precise or just remove CWE.

**Comment by jmanico** [comment]
I agree with your proposal.

**Comment by maizuka** [comment]
Revealing of the current password also means that the app doesn't use secure way such as PSTN or time-based OTP in password recovery. I think it should be forbidden at level 1. Is my idea right that this is covered by other requirements such as [v5.0-2.2.2](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x11-V2-Authentication.md#v22-general-authenticator-security)?

**Comment by tghosth** [comment]
@elarlang do we state anywhere that passwords can only ever be stored in this way and can never be stored in any other way? Do we need to have a carve-out for passwords which need to be stored recoverably, e.g. for accessing 3rd party services? What do you think?

**Comment by tghosth** [comment]
> Your question opens actually another issue - make clear difference "user credential for application" and "external service authentication".

I raised this in #1277
