### ISSUE TITLE
12.3.1 Clarification

### ISSUE THREAD

**Issue by bretik** [OWASP/ASVS#1136]
> [12.3.1](https://github.com/OWASP/ASVS/blob/v4.0.3/4.0/en/0x20-V12-Files-Resources.md#v123-file-execution) Verify that user-submitted filename metadata is not used directly by system or framework filesystems and that a URL API is used to protect against path traversal.

From the requirement, it is not clear what exactly is meant by "URL API" and how do I use it to protect against path traversal. If I go with common Java check for path traversal, is `File` class the "URL API" here?

```
File file = new File(BASE_DIRECTORY, userInput);
if (file.getCanonicalPath().startsWith(BASE_DIRECTORY)) {
    // process file
}
```

Searching cheat sheets and Google for URL API references, I got nothing but [URL Web API](https://developer.mozilla.org/en-US/docs/Web/API/URL) - not sure how would I use that for path traversal protection (maybe in Node.js?).

**Comment by jmanico** [comment]
First remember that a Webservice is a type of API but an API is not necessarily a webservice. An API can refer to a set of functions in a library.

An example of a safe URL API is:

https://www.javadoc.io/doc/com.google.common.html.types/types/1.0.0/com/google/common/html/types/SafeUrl.html

**Comment by bretik** [comment]
OK, I understand the concept of API as "any application interface". To comply with this level 1 requirement, it is required that I use **URL API** to protect against path traversal in my application. I am trying to understand what exactly should I do, it is probably just problem with terminology. If you tell me, that it is common to refer to canonicalization functions as **"URL API"**, I am OK with that. If it is not about path canonicalization, I would be glad for some explanation/example what exactly this requirement covers.

Here is an example of what I understand under "path traversal protection" in the implementation phase:
> Inputs should be decoded and canonicalized to the application's current internal representation before being validated (CWE-180). Make sure that the application does not decode the same input twice (CWE-174). Such errors could be used to bypass allowlist validation schemes by introducing dangerous inputs after they have been checked.
Use a built-in path canonicalization function (such as realpath() in C) that produces the canonical version of the pathname, which effectively removes ".." sequences and symbolic links (CWE-23, CWE-59). This includes:
> - realpath() in C
> - getCanonicalPath() in Java
> - GetFullPath() in ASP.NET
> - realpath() or abs_path() in Perl
> - realpath() in PHP

_source: https://cwe.mitre.org/data/definitions/22.html_

**Comment by elarlang** [comment]
For v5.0 I have to-do for myself for all the requirements on this subcategory, there is not much to keep to be honest.

From ASVS v4.0.* point of view, the point for the requirement is simple: _Verify that application is not vulnerable to path traversal._ or _Verify that application has defense against path traversal._

In my opinion it does not matter how you build the defense (allow-list or sanitize), every part of the system must have this defense.

**Comment by bretik** [comment]
Thanks, I think we can close this. My aim was to make sure I understand the requirement and that I am not missing something with the "URL API" and I think I got that. Thanks for your answers.
