### ISSUE TITLE
Update Links regarding the New OWASP Top Ten

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1150]
The OWASP Top Ten 2021 is out, we need to update the existing OWASP links.

The new links should be:

- https://owasp.org/Top10/A01_2021-Broken_Access_Control/
- https://owasp.org/Top10/A02_2021-Cryptographic_Failures/
- https://owasp.org/Top10/A03_2021-Injection/
- https://owasp.org/Top10/A04_2021-Insecure_Design/
- https://owasp.org/Top10/A05_2021-Security_Misconfiguration/
- https://owasp.org/Top10/A06_2021-Vulnerable_and_Outdated_Components/
- https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/
- https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/
- https://owasp.org/Top10/A09_2021-Security_Logging_and_Monitoring_Failures/
- https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery_%28SSRF%29/

**Comment by tghosth** [comment]
Anyone fancy creating a PR for this :)

**Comment by securingdev** [comment]
Happy to help - didn't see `Contributing` guidance on the main repo's README file, but if someone can point me in the right direction I'm happy to update links 😊

**Comment by securingdev** [comment]
@jmanico @tghosth - which MD file(s) need updating? Happy to contribute here and get this updated.

**Comment by jmanico** [comment]
The current working directory for the 5.0 release is https://github.com/OWASP/ASVS/tree/master/5.0/en

Please submit any issues or PR's against that branch!

**Comment by tghosth** [comment]
@set-reminder 1 week look at this

**Comment by tghosth** [comment]
So I don't see links where this is actually an issue currently, I think maybe we want to revisit this when we have a full 5.0 draft so I will label it accordingly and leave it for now.

**Comment by tghosth** [comment]
I don't see any links to specific top 10 items for now so I am going to close this
