### ISSUE TITLE
https://mvsp.dev/ review

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1151]
Let's review this awesome project at https://mvsp.dev/ and see if we are missing anything before 5.0

**Comment by cmlh** [comment]
Any chance of creating a milestone to track  @jmanico https://mvsp.dev/ and https://github.com/OWASP/ASVS/issues/1039,  https://github.com/OWASP/ASVS/issues/317, [PA-DSS](https://github.com/OWASP/ASVS/issues/1127#issuecomment-968157979) and others?

**Comment by jmanico** [comment]
> Any chance of creating a milestone to track @jmanico https://mvsp.dev/ and #1039, #317, [PA-DSS](https://github.com/OWASP/ASVS/issues/1127#issuecomment-968157979) and others?

For sure Christian. For now, I flagged the issues you cited as 5.0 so at the very least address your comments before the 5.0 release. I'll also assign these issues to myself (and you) as well.

**Comment by tghosth** [comment]
@cmlh are #1360, #1361 and #1365 the only things that are missing from ASVS compared to MSVP? If so, can we close this original issue?

**Comment by tghosth** [comment]
@set-reminder 2 weeks decide what to do depending on response

**Comment by tghosth** [comment]
I am open to suggestions if you feel there are additional gaps

**Comment by tghosth** [comment]
#set-reminder 2 weeks decide what to do depending on response

**Comment by tghosth** [comment]
@cmlh are you going to go through and suggest items in msvp that do not exist in ASVS?

@set-reminder 4 weeks @tghosth to decide what to do if no response

**Comment by elarlang** [comment]
I think he did already.

https://github.com/OWASP/ASVS/issues?q=is%3Aissue+mvsp

**Comment by tghosth** [comment]
So I am leaving it open for now so let me know

**Comment by tghosth** [comment]
I have moved this to non-blocker and @cmlh is welcome to revisit this when he gets time

**Comment by jmanico** [comment]
I am closing this out since ASVS 5.0 is too busy as it is. Please open new individual issues for new requirements that we do not cover if you think we missed anything.
