### ISSUE TITLE
v4.0.3 - translation to simplified chinese 

### ISSUE THREAD

**Issue by hi-unc1e** [OWASP/ASVS#1152]
Hey, guys, I'm new here.

Recently I'm working on Application Security, targeting at taking SDLC into our dev-ops lifecycle.
As the local version of ASVS  is needed, I would like to translate ASVS to simplified chinese , you know, as a OWASP member.

But I have some questions: 
1）I am planing to contribute it in my fork，and push the translated commit to the PR，is that the expected step？
2）Which version should I commit to，is that `Stable Release 4.0.3` ？
3）What are the recommended steps of translation. I'm going to translate it at Google firstly, then correct those tiny difference manually. I dont know whether there's preferred method.

Anyway, ASVS really helped me a lot.

Yours,
Unc1e from China

**Comment by elarlang** [comment]
Hi,

1) yes, that's correct. Checkout the latest master and make your translation to 4.0/ folder. Later you going to PR this one back to master and from ASVS side we set it to v4.0.3 branch if needed.
2) correct, v4.0.3 is the latest stable release
3) no more specific steps to recommend. Please translate markdown files and keep the markdown file structure exactly like it is - then it's possible to use export tools as well (for JSON, and PDF outputs). Here, I'm not sure how much extra work we need to do to support Chinese language, but there is one way to find it out :)

If you have any technical question about the process, please ask.

**Comment by elarlang** [comment]
Translation is done and merged via https://github.com/OWASP/ASVS/pull/1178

Big thanks to @hi-unc1e !
