### ISSUE TITLE
How specific should we be about password storage?

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1159]
2.4.4 recommends bcrypt wf 10 (thats ok) but does not mention the 72 byte limit

**Comment by tghosth** [comment]
I think we are hitting a more specific problem here.

We want this standard to be both usable and accurate.

The section about password storage algorithms is getting more and more specific which I think is initially good for accuracy but more difficult for usability.

Also, if password storage guidelines change in the next 3 years, we are stuck with these guidelines in the standard until the next major release.

If we look at [V6 Cryptography](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x14-V6-Cryptography.md#v62-algorithms), we deliberately don't specific strong algorithms but rather we point to the cryptographic storage cheatsheet. I think we should be doing the same here and at this this point I would therefore recommend replacing the whole of section [V2.4](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x11-V2-Authentication.md#v24-credential-storage) with a single requirement that says:

> Verify that a secure, one-way algorithm is being used for password storage based on trusted recommendations such as those in the OWASP Password Storage Cheat Sheet.

Come at me :)

![ShrekComeAtMeGIF](https://user-images.githubusercontent.com/13623828/165463994-3a6428ac-bdb2-4426-87ca-8eaeb9e0b80f.gif)

**Comment by elarlang** [comment]
Some ideas/arguments with this singlie requirement - problem with referring to external standard/resource:
* there is need to another resource to understand, what the requirement means
* it makes ASVS living standard and may cause problem for pen-testing (but when I check that other standard it said like this and now it is like that)

Similar discussion for logging ahead.

**Comment by tghosth** [comment]
I don't see we have much choice here, I am pretty sure we mandate algorithm agility anyway don't we? If we don't, we should.

**Comment by jmanico** [comment]
I would like to add a note to 2.4.4 that the 72 byte limit must be addressed

**Comment by jmanico** [comment]
I disagree, I think we should be in parity with https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html

These values are very future-proof and will be solid recommendations for a decade as Moore's laws go.

We also see stable IETF standards here. https://datatracker.ietf.org/doc/html/draft-ietf-kitten-password-storage-07

Since the industry has stabilized on what is good password storage crypto and it's not an issue of flux, specific suggestions are appropriate.

If this was seriously in flux as it was years ago, that's a different matter, but we are very stable in these recommendations as an industry.

So instead of burning down all of 2.4.x I am asking for a simple change.


2.4.4 | Verify that if bcrypt is used, the work factor SHOULD be as large as verification server performance will allow, with a minimum of 10 and consideration for bcrypt's 72-byte limit. (C6) |   | ✓ | ✓ | 916 | 5.1.1.2
-- | -- | -- | -- | -- | -- | --


2.4.4	Verify that if bcrypt is used, the work factor SHOULD be as large as verification server performance will allow, with a minimum of 10. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering))		✓	✓	916	5.1.1.2

**Comment by tghosth** [comment]
@elarlang , @danielcuthbert what do you think?

**Comment by elarlang** [comment]
First - current requirement:

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.4.4** | Verify that if bcrypt is used, the work factor SHOULD be as large as verification server performance will allow, with a minimum of 10. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 916 | 5.1.1.2 |

I like to have clear requirements in the standard and no liquid dependency on external resource. So I prefer our current solution.

> Also, if password storage guidelines change in the next 3 years, we are stuck with these guidelines in the standard until the next major release.

Then we can change some of them as fix. If some used method turns to be vulnerable, then applications should not use it as "known vulnerable component" and/or we can mark some requirement as deprecated.

Instead of writing too abstract requirements, we should just release more often.

Back to this requirement (in current state):
_Verify that if bcrypt is used, the work factor SHOULD be ~~as large as verification server performance will allow, with a~~ minimum of 10._

I would get rid of this part of the requirement. How realistic is to test, how much server allows? Does it makes sense to use the maximum amount of server resources for that?

**Comment by tghosth** [comment]
So I suggest:

> Verify that if bcrypt is used, the work factor is a minimum of 10 and password size is limited to 50 or the password is pre-hashed due to with bcrypt's 72-byte limit. 

@jmanico

**Comment by Sjord** [comment]
> password size is limited to 50

The value of 50 doesn't make much sense to me. I would expect 72. And you would have to be clear that this is in bytes, not characters. And if the password is prefixed with a pepper, the length of the pepper (in bytes) should be subtracted.

The password should not be silently truncated, but denied. That is currently not clear from the language.

> or the password is pre-hashed

The [cheatsheet recommends against this](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#bcrypt).

> due to with

This seems like a typo.

According to 2.1.2 and 2.1.4, I should be able to use a password of 64 emojis. If bcrypt supports at most 72 bytes and prehashing is insecure, that basically means that bcrypt is out. So maybe we should reconsider recommending bcrypt.

I would word the current recommendation like this:

> Verify that if bcrypt is used, the work factor is a minimum of 10. Verify that passwords are denied when they would be truncated because of bcrypt's 72 byte limit.

**Comment by tghosth** [comment]
I agree with what you wrote @Sjord, so how about this:

> Verify that if bcrypt is used, the work factor is a minimum of 10 and password size is limited to 72-bytes due to with bcrypt's input limit. 

@jmanico?

**Comment by tghosth** [comment]
@set-reminder 1 week work on this

**Comment by tghosth** [comment]
Created #1452

**Comment by elarlang** [comment]
I think the change is not merged into repo now or got rollback via https://github.com/OWASP/ASVS/pull/1452/files/515e41e5072553bd448bd6ecd5c88fb2fc8ef4dd..8da184c1ade523d6c8375bb3c5ee47d3dc890bce

Please recheck @tghosth

**Comment by tghosth** [comment]
Amazing spot @elarlang! I opened #1502 to try again
