### ISSUE TITLE
Correlation of v3 to v4

### ISSUE THREAD

**Issue by cmlh** [OWASP/ASVS#1166]
_Hello everybody,_

_I wish you all a merry Christmas and a happy new year.._
_I am looking for a table which shows a mapping of ASVS V3 to ASVS V4 mappings or vice-versa._
_I couldn't find this information on the web. Previously, I used ASVS V3 in my project now I need to update it. For this modification, I_ _need to have exact mapping in full or partially at least._
_Whatever information you have would be beneficial._
_I do not think I can capture this information using Github logs._
_I am hoping to make this update in this holiday._

_I copied the contents of both versions in an excel and sorted in multiple ways. Unfortunately, not only the numbers are changed, although meaning still the same or similar (I could only check a small number of items) the wording was changed in both versions significantly. This makes it impossible to sort and check for similar items._

[Link to Screenshot Slack](https://owasp.slack.com/archives/C06MNF14M/p1640683999063200)

![image](https://user-images.githubusercontent.com/136826/147709024-23b5b33e-a31d-483e-bfbe-f30e508e6daf.png)

**Comment by elarlang** [comment]
no offical mapping, response in slack.

**Comment by cmlh** [comment]
[Link to Slack Screenshot](https://owasp.slack.com/archives/C06MNF14M/p1643742624903859)

![image](https://user-images.githubusercontent.com/136826/153208827-fa8ae877-6e08-42a9-a6ea-47e8c471b063.png)
