### ISSUE TITLE
new requirement for data process transaction / integrity

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1168]
I think we miss requirement to verify, that on data changes related data must be in transaction, if some step fails, you need to rollback previous step as well.

**Comment by danielcuthbert** [comment]
How would we do this? It would assume there is some state table to compare to, or is it even simpler than that?

**Comment by elarlang** [comment]
Let's say you make 3 SQL commands to insert data and 3rd one fails, then you must rollback 2 previous ones, otherwise it's incorrect integrity.

**Comment by elarlang** [comment]
2 ways how to look it:
* V11.1 business logic requirement - if some step is failing, need to cancel previous ones as well
* V8.1 data protection/integrity requirement

**Comment by tghosth** [comment]
I completely agree. I think we need to refer to the need for "atomic transaction" where either all steps succeed or all steps fail.

@elarlang do you think we need two requirements or is 1 sufficient?

**Comment by elarlang** [comment]
What would be the 2nd one?

**Comment by tghosth** [comment]
@elarlang  I mean do we need one in data protection and one in business logic or is one in business logic sufficient?

**Comment by elarlang** [comment]
Re-analyzing the situation - it think category "V8 Data protection" is more protecting already existing data (from leaking) and more confidentiality oriented. So the direction should be "V11 business logic" and data integrity - if one step fails, nothing goes in (everything is rolled back) to avoid partial data.

**Comment by tghosth** [comment]
Ok @elarlang, so how about:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **11.1.9** | [ADDED] Verify that "atomic transactions" are being used at the business logic level such that either a business logic operation succeeds in its entirety, or it is rolled back to the previous correct state. | | ✓ | ✓ | ? |

Do you have a CWE and what level do you suggest?

**Comment by elarlang** [comment]
I tried again to find suitable CWE but did not find. My logic says that this is co common and basic problem in software and it means there should be some CWE for that, but I can not hit correct words to find it.

Can we move forward with blank CWE?

**Comment by tghosth** [comment]
Opened #1727 to resolve this
