### ISSUE TITLE
Section 1.1 requirements should be level 1

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1180]
We wish to consider moving 1.1.3, 1.1.4 and 1.1.6 to level 1.

**Comment by elarlang** [comment]
requires change for level description, https://github.com/OWASP/ASVS/issues/1127#issuecomment-964341830

**Comment by tghosth** [comment]
These are not trivial to achieve and probably cannot be achieved for an application already underway. Whilst they are important, I think making them L1 would increase the barrier to entry too high.

**Comment by tghosth** [comment]
As such, @jmanico I would be inclined not to change these for now...
