### ISSUE TITLE
1.2.3 clarifying and expanding the AuthN provider requirements

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1181]
ASVS 1.2.3 from 4.0.3 branch is a tragic, confusing, overloaded requirement that needs to be carefully broken up or re-thought.

**Comment by tghosth** [comment]
So I don't actually hate this...

As at the bleeding edge, it is currently:

[1.2.3](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x10-V1-Architecture.md#v12-authentication-architecture)

> Verify that the application uses a single vetted authentication mechanism that is known to be secure, can be extended to include strong authentication, and has sufficient logging and monitoring to detect account abuse or breaches.

I would be tempted at this point to clarify it a little to say:

> Verify that the application uses a single authentication mechanism consistently. The mechanism should be well known/security tested, should support strong authentication, and should provide sufficient logging and monitoring functionality to detect account abuse or breaches.

Alternatively, it could be split:

> Verify that the application uses a single authentication mechanism consistently. 

> Verify that the application's authentication mechanism is well known and trusted or has undergone provable security testing.

> Verify that the application's authentication mechanism supports strong authentication

> Verify that the application's authentication mechanism provides sufficient logging and monitoring functionality to detect account abuse or breaches.

Thoughts?

**Comment by elarlang** [comment]
> ... that is known to be secure

> Verify that the application's authentication mechanism is well known and trusted or has undergone provable security testing.

We can also watch it as "one component" and it is covered by:
* _V14.2.1 Verify that all components are up to date, preferably using a dependency checker during build or compile time._
* _V14.2.4 Verify that third party components come from pre-defined, trusted and continually maintained repositories._

> can be extended to include strong authentication

> Verify that the application's authentication mechanism supports strong authentication

What would be the point for this? If it is supported, it comes out from V2 requirements. If the application does not need it - why there should be support for that?

> , and has sufficient logging and monitoring to detect account abuse or breaches

> Verify that the application's authentication mechanism provides sufficient logging and monitoring functionality to detect account abuse or breaches.

Logging part belongs to V7, breaches covered by 2.1.14 and 2.2.1:
* _V2.1.14 [ADDED, SPLIT FROM 2.1.7, LEVEL L1 > L3] Verify that passwords submitted during account registration or password changes are checked against a set of breached username/password pairs._
* _V2.2.1 Verify that anti-automation controls are effective at mitigating breached credential testing, brute force, and account lockout attacks. Such controls include blocking the most common breached passwords, soft lockouts, rate limiting, CAPTCHA, ever increasing delays between attempts, IP address restrictions, or risk-based restrictions such as location, first login on a device, recent attempts to unlock the account, or similar. More than 5 failed authentication attempts per hour for a single account should trigger some sort of reaction or alert._

So, this is the only part or requirement I would keep:

> Verify that the application uses a single authentication mechanism consistently.

**Comment by tghosth** [comment]
I disagree that 14.2.1 is relevant here.
I agree that 14.2.2 sort of covers this but I do feel like it might be worth mentioning specifically and also my new requirement is more stringent.

I think we will almost certainly mandate the use of strong authentication in some form in V2 so I think it makes sense to explicitly say that it must be supported by the architecture level mechanism.

2.1.14 and 2.2.1 are very specific and I think that the logging part is a pre-requisite to allow the V7 controls.

Overall, I think these new requirements are worth keeping because they provide clear upfront expectations. The whole point of this section is to provide the underpinnings for the detailed sections.

**Comment by jmanico** [comment]
Side note, 1.1.6 also talks about "use centralized..." controls. Lots of this idea is quite a few requirements.

**Comment by paul-williamson-swoop** [comment]
I just came across this via the CASA framework and the whole thing looks far too broad and ambiguous.  

"Verify that the application uses a single vetted authentication mechanism that is known to be secure, can be extended to include strong authentication and has sufficient logging and monitoring to detect account abuse or breaches."

'single vetted authentication mechanism' - What does this even mean?   What are you authenticating?  You would think authenticating user vs application procedure calls (RPC, API) should be different.

'known to be secure' - What does this mean?   How do you know something is secure?

'can be extended to include strong authentication' - Even more ambiguous  - what is 'strong authentication'?  Surely your application should always have authentication that satisfied the requirements so why do you need a requirement to extend?

'has sufficient logging and monitoring to detect account abuse or breaches' - so are we talking about user authentication or authentication in general?

IMO This whole thing needs to be broken down into detailed requirements, explained and referenced to the relevant source after being broken down.

**Comment by tghosth** [comment]
So I think this requirement makes some conceptual sense. However it is too vague to either implement or verify.

We already talk about a situation where there are multiple potential authentication mechanisms in [1.2.4](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x10-V1-Architecture.md#v12-authentication-architecture) (which arguably now contradicts requirement 1.2.3.

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.2.4** | [MODIFIED, SPLIT TO 2.2.11] Verify that, if the application includes multiple authentication pathways, these are all documented together with the security controls and authentication strength which should be consistently enforced across them. | | ✓ | ✓ | 306 |

I would now recommend deleting requirement 1.2.3.

@elarlang @jmanico thoughts?

**Comment by elarlang** [comment]
I agree the point for 1.2.3 is not clear and as I have analyzed here (https://github.com/OWASP/ASVS/issues/1181#issuecomment-1164076006) before, mostly covered somewhere else.

**Comment by tghosth** [comment]
Opened #2128
