### ISSUE TITLE
Migration of 2.5.1 to 2.3.1 rom v4 to v5

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1187]
2.3.1 in v5 states [MODIFIED, MERGED FROM 2.5.1]

2.5.1 in v4 states "..not sent in clear text..."

But 2.3.1 v5 does not at all address the clear text issue.

from Suvi @ Helsinki

**Comment by elarlang** [comment]
https://github.com/OWASP/ASVS/issues/1014
