### ISSUE TITLE
2.5.4 split it up

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1188]
The process of verifying a shared password for admin accounts - and the process of verifying default admin accounts - is very different and henceforth we should break this up like the Beatles.

**Comment by tghosth** [comment]
Just took a trip down memory lane to try and figure out why it was like that in the first place and why it has that NIST identifier.

Shared accounts seems to have been added to an existing requirement about spoofing here:
https://github.com/OWASP/ASVS/commit/c0f9c295ea57ecfba848cfbdca850034825117f1

It seems to have become shared or default here:
https://github.com/OWASP/ASVS/commit/6298456976626a1853f296f5c892f78c3b5379ec

I still don't know why it has that NIST reference.

CWE is very generic as well.

AND the section doesn't make sense to me anyway...

I actually think this is a good candidate for section V1 as it is a more pervasive thing across an application.

Currently we have:

[2.5.4](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x11-V2-Authentication.md#v25-credential-recovery):

> Verify shared or default accounts are not present (e.g. "root", "admin", or "sa").

I would propose adding the default aspect to [1.2](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x10-V1-Architecture.md#v12-authentication-architecture):

1.2.5 [MOVED AND SPLIT FROM 2.5.4] Verify that default user accounts are not present in the application or are disabled.

I am not actually sure if "shared accounts" should be included in the standard as it is not really related to how an application is built.

Thoughts?

**Comment by flo-blg** [comment]
> I am not actually sure if "shared accounts" should be included in the standard as it is not really related to how an application is built.

Hi guys, I totally agree with this. Maybe I misunderstand this requirement but if I get it right, how are we supposed to prevent users from being able to create an account using a generic email address such as "contact@mycompany.com" or "team@mycompany.com"?

**Comment by elarlang** [comment]
Another issue for the same requirement: https://github.com/OWASP/ASVS/issues/1395

**Comment by tghosth** [comment]
@set-reminder 5 weeks look at this

**Comment by tghosth** [comment]
Opened PR #1578

**Comment by elarlang** [comment]
Re-open for level validation.

@tghosth - was level change from Level 1 to Level 2 intended or it happened as a mistake?

https://github.com/OWASP/ASVS/pull/1578/files/82e25bc952c25be950a5542d578dc529a83383be

**Comment by tghosth** [comment]
I think this was a mistake made because originally I moved it to V1. I have restored it to L1 for now in #1645.
Thanks @elarlang !
