### ISSUE TITLE
3.6.1 and 3.6.2 seem complex without clear explanation

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1190]

**Comment by Sjord** [comment]
> 3.6.1 Verify that Relying Parties (RPs) specify the maximum authentication time to Credential Service Providers (CSPs) and that CSPs re-authenticate the user if they haven't used a session within that period.
> 3.6.2 Verify that Credential Service Providers (CSPs) inform Relying Parties (RPs) of the last authentication event, to allow RPs to determine if they need to re-authenticate the user.

These seem implementation details on how to implement session timeout (required in 3.3.2), when having authentication separate from the application. I think requiring session timeouts is sufficient, and specifying how that should be implemented between RPs and CSPs is not up to the ASVS.

**Comment by tghosth** [comment]
To be honest, having read [the relevant section of NIST](https://pages.nist.gov/800-63-3/sp800-63b.html#721-reauthentication-from-a-federation-or-assertion) and also read the requirements, I think these are ok. The point the NIST standard makes is that the CSP and RP will have different session mechanisms so a simple session timeout is not quite the right answer here.

Bottom line, I think these requirements are ok as they are at this point...

**Comment by Sjord** [comment]
I would prefer a requirement that says something like "session validity should be synchronized between servers", without getting into how this is implemented.

**Comment by tghosth** [comment]
> I would prefer a requirement that says something like "session validity should be synchronized between servers", without getting into how this is implemented.

That feels like it might end up a little oversimplified whilst not being specific enough to understand how to implement. Do you have a suggested wording @Sjord ?

**Comment by tghosth** [comment]
@Sjord any suggestion on this?

@set-reminder 3 weeks make a decision how to proceed if no response

**Comment by Sjord** [comment]
No, not other than what I said above. I think the requirements should specify application behaviour and not implementation.

**Comment by tghosth** [comment]
I just spent even more time trying to re-word these requirements and it is not easy. NIST is referring to a very specific case here and there seem to be some subtleties but it seems to be something like the following:

![image](https://user-images.githubusercontent.com/13623828/207367605-2c078ace-9632-4432-8200-0492766cd146.png)

I am not inclined to spend too much more time on this as these are level 3 requirements anyway. If you can think of a specific simplification suggestion then I am open to it but otherwise I think we need to move on :)

**Comment by tghosth** [comment]
So with no further improvement suggestions, I am going to close this for now. At least if someone searches the issues for these requirements they will hopefully find this thread :)

**Comment by tghosth** [comment]
Looks good to me

**Comment by jmanico** [comment]
So lets go to PR.

1) Modify 3.6.1 to Ryan's new text
2) Delete 3.6.2
3) Add a new doc requirement.

Enough of this "process" crap let's go right to PR, Ryan!

**Comment by ryarmst** [comment]
@tghosth See #2320. I created #2321 for the inevitable section text update.
