### ISSUE TITLE
update 1.14.6

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1192]
we do not want negative requirements

**Comment by elarlang** [comment]
No for drop. Wording can be improved, the point must stay.

**Comment by tghosth** [comment]
Current wording

[1.14.6](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x10-V1-Architecture.md#v114-configuration-architecture)

> Verify the application does not use unsupported, insecure, or deprecated client-side technologies such as NSAPI plugins, Flash, Shockwave, ActiveX, Silverlight, NACL, or client-side Java applets.

How about:

> Verify the application only uses client-side technologies which are still supported and considered secure. Examples of technologies which do not meet this requirement include NSAPI plugins, Flash, Shockwave, ActiveX, Silverlight, NACL, or client-side Java applets.

@jmanico

**Comment by jmanico** [comment]
There are plenty of secure client-side Java applications. They are not inherently insecure. I still oppose this very negative requirement, it's not helpful.

**Comment by elarlang** [comment]
With removing the requirement we kind of give go-ahead for flash, activex etc. This is also not the way to go.

**Comment by jmanico** [comment]
I disagree because it’s a slippery slope. Should we also ban old frameworks?

**Comment by elarlang** [comment]
Like I wrote, this is covered by 1.14.3 + 14.2.1 - if those old frameworks are not up to date or known to insecure, those are "banned".

**Comment by tghosth** [comment]
We should certainly ban old and unmaintained frameworks @jmanico. As such, I agree with @elarlang about relying on the other related requirements. @jmanico any other comments>

**Comment by tghosth** [comment]
So @elarlang are you suggesting that this requirement is covered by other requirements and can therefore just be removed?

**Comment by elarlang** [comment]
> So @elarlang are you suggesting that this requirement is covered by other requirements and can therefore just be removed?

No. "this is covered by 1.14.3 + 14.2.1" was answer to Jim's question:
> Should we also ban old frameworks?

I think the requirement should stay, like I said in https://github.com/OWASP/ASVS/issues/1192#issuecomment-1265042128

**Comment by tghosth** [comment]
Ah, ok. 

@jmanico Whilst it is possible to build secure client-side Java applications, it is not possible to build secure client-side Java **applets** as the [applet technology is deprecated](https://docs.oracle.com/javase/10/docs/api/java/applet/package-summary.html). The other examples mentioned are all deprecated technologies which are no longer considered secure.

As such, I propose the following wording. 

> Verify the application only uses client-side technologies which are still supported and considered secure. Examples of technologies which do not meet this requirement include NSAPI plugins, Flash, Shockwave, ActiveX, Silverlight, Google Native Client (NaCl), or client-side Java applets.

**Comment by tghosth** [comment]
@set-reminder 2 weeks @tghosth to open a PR if no further discussion or disagreement

**Comment by jmanico** [comment]
@tghosth I am ok with your earlier suggestion so we can resolve this.

_Verify the application only uses client-side technologies which are still supported and considered secure. Examples of technologies which do not meet this requirement include NSAPI plugins, Flash, Shockwave, ActiveX, Silverlight, NACL, or client-side Java applets._

**Comment by tghosth** [comment]
#1501 opened 
REMINDER NO LONGER RELEVANT
