### ISSUE TITLE
4.2.2 should likely be in the AuthN

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1193]
CSRF defense is typically associated with the session mechanism of an app, and is rarely tied to access control.

**Comment by elarlang** [comment]
title and description is not understandable.

**Comment by elarlang** [comment]
@jmanico - is the issue opened because current 4.2.2 is in wrong category or there is some other meaning?

**Comment by jmanico** [comment]
this is a duplicate of [422](https://github.com/OWASP/ASVS/issues/1193#:~:text=then%20related%20comment%3A-,%23795%20(comment),-Collaborator)
