### ISSUE TITLE
7.1.3 and 7.2.2 have overlap

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1196]
7.1.3 | [MODIFIED] Verify that the application logs security relevant events including successful and failed authentication events, access control failures, deserialization failures, input validation failures and incorrect HTTP requests (including requests with an unexpected HTTP verb). (C5, C7)
-- | --

7.2.2 | Verify that all access control decisions can be logged and all failed decisions are logged. This should include requests with relevant metadata needed for security investigations.
-- | --

**Comment by elarlang** [comment]
duplicate https://github.com/OWASP/ASVS/issues/997
