### ISSUE TITLE
Drop the "backwards compatibility" from 6.2.5

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1197]
6.2.5 | Verify that known insecure block modes (i.e. ECB, etc.), padding modes (i.e. PKCS#1 v1.5, etc.), ciphers with small block sizes (i.e. Triple-DES, Blowfish, etc.), and weak hashing algorithms (i.e. MD5, SHA1, etc.) are not used unless required for backward compatibility.
-- | --

**Comment by jmanico** [comment]
I agree with Jim here, bump.

**Comment by tghosth** [comment]
@set-reminder 1 week look at this

**Comment by tghosth** [comment]
I agree, if they need it for backwards compatibility then they will just have to be showing as non-compliant with this requirement until they have removed the reliance (e.g. decrypted and re-encrypted with better algo)

**Comment by tghosth** [comment]
PR #1456 opened
