### ISSUE TITLE
6.2.3 and 6.2.5 are semi duplicate

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1198]
6.2.3 | Verify that encryption initialization vector, cipher configuration, and block modes are configured securely using the latest advice.
-- | --

6.2.5 | Verify that known insecure block modes (i.e. ECB, etc.), padding modes (i.e. PKCS#1 v1.5, etc.), ciphers with small block sizes (i.e. Triple-DES, Blowfish, etc.), and weak hashing algorithms (i.e. MD5, SHA1, etc.) are not used unless required for backwards compatibility.
-- | --

**Comment by tghosth** [comment]
Well, this was a journey.

6.2.3 was introduced here:
https://github.com/OWASP/ASVS/commit/371b1610ec157bbb58016adc290d4cf34e64445b

6.2.5 was introduced based on this issue.
https://github.com/OWASP/ASVS/issues/537

Basically, I think 6.2.5 obsoletes 6.2.3 but I want to check whether we need to maintain the reference to IV and config from 6.2.3 somewhere. 

On my todo list..

**Comment by tghosth** [comment]
6.2.6 says:

> Verify that nonces, initialization vectors, and other single use numbers must not be used more than once with a given encryption key. The method of generation must be appropriate for the algorithm being used.

I think between this and 6.2.5, 6.2.3 is no longer relevant and can be simply deleted.

**Comment by jmanico** [comment]
I think it’s a good high level requirement (ASVS L3) to suggest using only one key per piece of data encrypted. It makes cryptanalysis much much more difficult.

Reference : https://code.cash.app/app-layer-encryption

Note how cash app has one key per piece of data, it’s remarkable and significantly adds to the long term security of their crypto system.

**Comment by tghosth** [comment]
> I think it’s a good high level requirement (ASVS L3) to suggest using only one key per piece of data encrypted. It makes cryptanalysis much much more difficult.
> 
> Reference : https://code.cash.app/app-layer-encryption
>
> Note how cash app has one key per piece of data, it’s remarkable and significantly adds to the long term security of their crypto system.

@jmanico I moved this discussion to #1464
