### ISSUE TITLE
The 7.2 Title talks about "remote monitoring system" but no requirements in this section addresses it

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1199]
V7.2 Log Processing
Timely logging is critical for audit events, triage, and escalation. Ensure that the application's logs are clear and can be easily monitored and analyzed either locally or log shipped to a remote monitoring system.

**Comment by elarlang** [comment]
I would say it's also duplicate to https://github.com/OWASP/ASVS/issues/997#issuecomment-841846770
