### ISSUE TITLE
It is unclear why there are “Skipped/Missing” verification requirements

### ISSUE THREAD

**Issue by defern** [OWASP/ASVS#12]
It is unclear why there are “Skipped/Missing” verification requirements

It is unclear if the missing requirements were forgotten or have been removed. 

It may help reader and user of ASVS to have either a generic paragraph stating why there are some missing or include the line and say something like “No longer relevant” or “Deleted from this version of ASVS”  

The entire V6 verification is is not included any more.

The following verification requirements are missing or have been removed:
2.3
2.10
2.11
3.9
4.6
4.7
4.8
5.9
7.4
8.12
11.1

**Comment by vanderaj** [comment]
This is like the #1 FAQ that I get, so we are going to fix it. 

We will add them back, and note when they were retired, moved, etc, in a new "Since" column.
