### ISSUE TITLE
10.1.1 asks for basic SAST but is l3 should this be l1?

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1200]
10.1.1 | Verify that a code analysis tool is in use that can detect potentially malicious code, such as time functions, unsafe file operations and network connections.
-- | --

**Comment by mascotter** [comment]
Taking into account development world moving more and more into DevOps and highlighting automation (also security-wise) I find it incomprehensible that a SAST tool is a requirement only for L3 i.e. "the most critical applications" as per definition in the ASVS.

If the penetration testable approach needs to be maintained for L1, how about putting the requirement 10.1.1 mandatory beginning from L2?

**Comment by jmanico** [comment]
Absolutely I agree this should be a level 1 or 2 requirement. Good catch.

**Comment by vdbaan** [comment]
I would make this a L2 requirement. L1 claims to be completely penetration testable and I would say that this requirement asks for attestation instead.

**Comment by vdbaan** [comment]
I like to hear that the ASVS is moving to risk levels.

If that is the case I would recommend it for Level 1 Even a SAST that is not tuned optimally will provide insight. Perhaps add that the findings of SAST should be blocking from Level 2 onwards.

**Comment by jmanico** [comment]
I agree that using SAST should be a requirement at the most basic levels of ASVS. +1

**Comment by vdbaan** [comment]
I would like to clarify that the purpose of SAST for Level 1 is awareness, especially if the tool is not tuned for the application. 
For higher levels the tool needs to be tuned to reduce FP as those findings are more of a hindrance than help raise awareness.

**Comment by Sjord** [comment]
I agree that everyone should run SAST to detect security bugs. But is that what this requirement says?

> that can detect potentially malicious code

Not security bugs, but actively malicious code.

**Comment by vdbaan** [comment]
This item has been removed as per#1507, the issue can be closed
