### ISSUE TITLE
11.1.1 and 11.1.2 and 11.1.7 all have significant overlap

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1202]
11.1.1 | Verify that the application will only process business logic flows for the same user in sequential step order and without skipping steps. | ✓ | ✓ | ✓ | 841
-- | -- | -- | -- | -- | --
11.1.2 | Verify that the application will only process business logic flows with all steps being processed in realistic human time, i.e. transactions are not submitted too quickly.

11.1.7 | Verify that the application monitors for unusual events or activity from a business logic perspective. For example, attempts to perform actions out of order or actions which a normal user would never attempt. (C9)
-- | --

**Comment by elarlang** [comment]
No overlap here.
* 11.1.1 - business logic requirement - check that you can not do steps outside of the flow
* 11.1.2 - anti-automation requirement - check, that some data flows are not automated (massive read/write/delete)
* 11.1.7 - monitoring and logging requirement, belongs to category V7

**Comment by elarlang** [comment]
Should be solved with #1211 + #1272
