### ISSUE TITLE
11.1.3 and 11.1.5 have significant overlap

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1203]
11.1.3 | Verify the application has appropriate limits for specific business actions or transactions which are correctly enforced on a per user basis. | ✓ | ✓ | ✓ | 770
-- | -- | -- | -- | -- | --

11.1.5 | Verify the application has business logic limits or validation to protect against likely business risks or threats, identified using threat modeling or similar methodologies. | ✓ | ✓ | ✓ | 841
-- | -- | -- | -- | -- | --

**Comment by elarlang** [comment]
* 11.1.3 - limits for user
* 11.1.5 - limits for application

**Comment by tghosth** [comment]
@elarlang do you think you could expand on how you see the difference between these as it is not super clear to me.

Also, we should consider the following requirements:


| # | Description |
| :---: | :--- |
| [8.1.4](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x16-V8-Data-Protection.md#v81-general-data-protection) | Verify the application can detect and alert on abnormal numbers of requests, such as by IP, user, total per hour or day, or whatever makes sense for the application.|
| [11.2.2](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x19-V11-BusLogic.md#v112-anti-automation) | [MOVED FROM 11.1.4] Verify that the application has  anti-automation controls to protect against excessive calls such as mass  data exfiltration, business logic requests, file uploads or denial of  service attacks.|

It feels like there is a lot of overlap here which I think we need to figure out how to resolve.

**Comment by elarlang** [comment]
8.1.4 (see also https://github.com/OWASP/ASVS/issues/1272) and 11.2.2 are anti-automation requirements, 11.1.3 and 11.1.5 are business logic limits.

Example of limits:
* 11.1.3 user can put to shopping cart only X amount of items to avoid "bron" and "keep under bron" all items
* 11.1.5 all users combined can not allocate more items to shopping cart than the shop has

**Comment by tghosth** [comment]
So it feels like this could be combined as follows:

> Verify the application has appropriate business logic limits or validation (at both a user level and at an overall level) for specific business actions or transactions. These should be designed to protect against likely business risks or threats, identified using threat modelling or similar methodologies.

What do you think @elarlang

**Comment by elarlang** [comment]
It's more question - do we want to keep separate requirements for separate test-cases (per user and per application), or we merge them to one requirement. From reporting point of view, I like them separately, as those are separate problems.

**Comment by tghosth** [comment]
But do you think the implementation would be completely separate. I would assume the implementation would be the same with some sort of configuration difference between absolute limits and per user limits... I accept that the tests cases are slightly different but the overall concept is the same.

**Comment by elarlang** [comment]
I think it do not require any rework (this is basically only issue with v11 label) and can be sorted out. If there is will to merge them (https://github.com/OWASP/ASVS/issues/1203#issuecomment-1195734719), we can. If there is not, we can just close the issue.

**Comment by tghosth** [comment]
Ok so I take your point about different test cases so I can see an argument to keep them separate, with some minor modifications:


| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **11.1.3** | [MODIFIED] Verify that the application has appropriate limits **defined on a per user basis** for specific business actions or transactions. | ✓ | ✓ | ✓ | 770 |
| **11.1.5** | [MODIFIED] Verify that the application has **globally defined** business logic limits or validation to protect against likely business risks or threats, identified using threat modeling or similar methodologies. | ✓ | ✓ | ✓ | 841 |

However, can you suggest better CWEs for these @elarlang ?

**Comment by elarlang** [comment]
Those are not specific "one certain problem" requirements and for this kind of stuff it's hard to find match from CWE. If we don't find good ones, maybe it's just better to leave those not set.

**Comment by tghosth** [comment]
Agree, let's go without CWE for now
