### ISSUE TITLE
12.5.3 grammatical error

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1206]
12.5.3 | [MODIFIED, MOVED FROM 12.3.4] Verify that the application validates or ignores user-submitted filenames, including in a JSON, JSONP, or URL parameter. The response Content-Type header and Content-Disposition header should be fixed to the file and securely handled by the application instead of the user.
-- | --

**Comment by tghosth** [comment]
@set-reminder 3 weeks look at this

**Comment by tghosth** [comment]
Based on https://github.com/w3c/webappsec-post-spectre-webdev/commit/f1728a156b2f6e79f81ad195d69497cb48927e2a and https://github.com/w3c/webappsec-post-spectre-webdev/issues/1 and #1004 and #721 and #1008, I don't think Reflected File Download is a relevant attack any more.

As such, I want to streamline this requirement to be more specific.

**Comment by tghosth** [comment]
Created #1458

**Comment by elarlang** [comment]
From proposal https://github.com/OWASP/ASVS/pull/1458/commits/02573ddb5ccddfd1f91c7e8f5368021c0a0f376b

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **12.5.3** | [MODIFIED, SPLIT FROM 12.3.4] Verify that the application validates or ignores user-submitted filenames, including in a JSON, JSONP, or URL parameter and specifies a filename in the Content-Disposition header in the response. | ✓ | ✓ | ✓ | 641 |
| **12.5.4** | [MODIFIED, SPLIT FROM 12.3.4] Verify that the Content-Type header is set to the appropriate type for the file being downloaded. | ✓ | ✓ | ✓ | 430 |

I think proposed 12.5.4 is duplicating current 14.4.1:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **14.4.1** | Verify that every HTTP response contains a Content-Type header. Also specify a safe character set (e.g., UTF-8, ISO-8859-1) if the content types are text/*, /+xml and application/xml. Content must match with the provided Content-Type header. | ✓ | ✓ | ✓ | 173 |

And actually, how relevant the `Content-Type` header value is for downloaded file? Downloaded file is opened in local operation system based on file extension I guess.

Current 12.5.3 potentially overlaps a bit with https://github.com/OWASP/ASVS/issues/1390

**Comment by tghosth** [comment]
#1390 should maybe be a new requirement in 12.5.x

Having read [this](https://stackoverflow.com/questions/20508788/do-i-need-content-type-application-octet-stream-for-file-download) I am still undecided about what the content type should be.

I am however inclined to skip 12.5.4 and rely on 14.4.1 which I agree kinda already covers it.

What do you think?
