### ISSUE TITLE
Discussion: V11.1.* - divide business logic requirements to "business logic" and "anti-automation" requirements

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1211]
Yes, there could be at the moment only 4 and 2 requirements to subcategories, but for me it makes sense to separate them.

Note: I kept current requirement numbers on purpose

Proposal:

## Business logic

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **11.1.1** | Verify that the application will only process business logic flows for the same user in sequential step order and without skipping steps. | ✓ | ✓ | ✓ | 841 |
| **11.1.3** | Verify the application has appropriate limits for specific business actions or transactions which are correctly enforced on a per user basis. | ✓ | ✓ | ✓ | 770 |
| **11.1.5** | Verify the application has business logic limits or validation to protect against likely business risks or threats, identified using threat modeling or similar methodologies. | ✓ | ✓ | ✓ | 841 |
| **11.1.6** | Verify that the application does not suffer from "Time Of Check to Time Of Use" (TOCTOU) issues or other race conditions for sensitive operations. | | ✓ | ✓ | 367 |

## Anti-automation

Goal: to stop massive data breaches, data modifications etc

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **11.1.2** | Verify that the application will only process business logic flows with all steps being processed in realistic human time, i.e. transactions are not submitted too quickly. | ✓ | ✓ | ✓ | 799 |
| **11.1.4** | Verify that the application has anti-automation controls to protect against excessive calls such as mass data exfiltration, business logic requests, file uploads or denial of service attacks. | ✓ | ✓ | ✓ | 770 |

## Remove requirements 11.1.7 and 11.1.8 from business logic category.

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **11.1.7** | Verify that the application monitors for unusual events or activity from a business logic perspective. For example, attempts to perform actions out of order or actions which a normal user would never attempt. ([C9](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 754 |
| **11.1.8** | Verify that the application has configurable alerting when automated attacks or unusual activity is detected. | | ✓ | ✓ | 390 |

Those requirements are logging and monitoring requirements and should be covered in those categories or merged to some requirements which are already there.

Also those are quite close to current 8.1.4 (but we can watch 8.1.4 as duplicate of 11.1.2 + 11.1.4 as well):

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **8.1.4** | Verify the application can detect and alert on abnormal numbers of requests, such as by IP, user, total per hour or day, or whatever makes sense for the application. | | ✓ | ✓ | 770 |

**Comment by mgargiullo** [comment]
This makes a lot of sense.

**Comment by danielcuthbert** [comment]
this actually really does. it makes it cleaner

**Comment by tghosth** [comment]
Makes perfect sense, @elarlang do you want to open a PR?

**Comment by tghosth** [comment]
Merged
