### ISSUE TITLE
Inconsistent use of "Verify that"

### ISSUE THREAD

**Issue by relaxnow** [OWASP/ASVS#122]
Most requirements are prefaced by "Verify that" except these: 2.33, 5.15, 5.16, 5.22, 5.23, 7.12, 8.13, 10.13, 16.9, 19.1, 19.2, 19.3, 19.4

Since this is the "verification standard" I would propose that these words are removed everywhere for additional brevity.

(Note that this issue is very minor and bikesheddy)

**Comment by vanderaj** [comment]
Fixed in 3.1 milestone. Also this was a good selector for all the not-quite-right findings. Thank you for your submission!
