### ISSUE TITLE
V9 rework needed

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1220]
I have ready V9 and I think it needs some rework.

Overall I think it is trying to distinguish between external facing services and service to service comms and also trying to distinguish between TLS and other encryption mechanisms.

I have started by trying to make this differentiation clearer but I am keen to get other feedback from people.

**Comment by tghosth** [comment]
Ok so what everything in V9 has in common which is not the case for the 4 requirements you specified is that the server-side configuration would almost certainly be outside of the application code/config but rather at the server or service hosting level. 

if you can think of other comms related items that fall into that bucket then we can look at them but I think the other items you have pointed out are application code/config related so belong wherever they currently are.

**Comment by elarlang** [comment]
> I think the other items you have pointed out are application code/config related so belong wherever they currently are.

That's the problem, that they are not - CSRF is not authorization problem and does not belong to V4. Those 4 belong together to one (sub)category, but it does not mean it must be V9. That's why I asked, how do we define the category name "Communication".

**Comment by elarlang** [comment]
If current V9 is purely for configuration, should it be part of V14 then?

**Comment by tghosth** [comment]
But it is a special kind of configuration which is a little outside of the regular application domain and it is also an important topic which is why I think it merits its own section. I agree that things are getting a little murky now but I think it makes enough sense where it is.

**Comment by elarlang** [comment]
Then I stand for this:
> If to keep it only for communication encryption, then maybe it makes sense to make title more precise as well.

https://github.com/OWASP/ASVS/issues/1220#issuecomment-1035200681

**Comment by tghosth** [comment]
Can we say "Communication Protection"?

**Comment by tghosth** [comment]
> Can we say "Communication Protection"?
@elarlang what do you think?

**Comment by tghosth** [comment]
Ok so "Communication Encryption"? @elarlang

**Comment by elarlang** [comment]
Seems good

**Comment by tghosth** [comment]
Created #1342 @elarlang
