### ISSUE TITLE
remove 1.1.1 as out of scope

### ISSUE THREAD

**Issue by suvikaartinen** [OWASP/ASVS#1226]
[1.1.1] Verify the use of a secure software development lifecycle that addresses security in all stages of development. 
(https://github.com/OWASP/ASVS/blob/master/5.0/en/0x10-V1-Architecture.md#v11-secure-software-development-lifecycle)

This is a very vague requirement. Secure software development lifecycle approaches vary and some of them might not be as comprehensive as others. Using ASVS could be already considered fulfilling this requirement, but on the end there is certified SDL process.  One approach could be to split this on different levels:
* L1: Some SDL activities. e.g. usage of checklists and code reviews
* L2: Covers design, implementation, verification and operations
* L3: Based on standards such as 62443

**Comment by elarlang** [comment]
See:
* https://github.com/OWASP/ASVS/issues/1108
* https://github.com/OWASP/ASVS/issues/1127

**Comment by tghosth** [comment]
@set-reminder 3 weeks @tghosth look at this

**Comment by tghosth** [comment]
I think this requirement should be dropped entirely as not being in line with the standard as a whole.

There seems to be support for this based on #1460 and #1461 and @jmanico's often repeated opinion seems to be:

> I think all of these non-technical requirements should go away. Too abstract.

@elarlang what do you think? Should I open a PR :)

**Comment by elarlang** [comment]
In general those will be removed, I just want to check one-by-one, that maybe those actually contain something useful for documentation or implementation requirements.

"Use something during developing" is out of scope - so this one goes away.
