### ISSUE TITLE
What do you think to add a column for verifications title?

### ISSUE THREAD

**Issue by toufik-airane** [OWASP/ASVS#1228]
**Context**
I've been working to implement security controls in an application design stage.

Like many companies, we use Atlassian Jira to produce user stories and technical tasks. There is a basic feature on Jira where you can link issues to display relating or blocking issues. I actually try to leverage this functionality to integrate security controls in malicious user stories, themselves integrated into user stories as blocking ones.

Basically, the workflow looks like this:

```mermaid
flowchart LR
A[User Story] -->|is blocked by| B[Malicious User Story] -->|is blocked by| C[Security Controls]
```

And visually speaking, it looks like this:

![Screenshot 2022-02-16 at 20 17 50](https://user-images.githubusercontent.com/5610269/154340878-a098d2f4-065f-408d-883b-60740ff230a2.png)
_Note the linked issue below the description of the main report. It eases the brain to industrialize security reviews._

**Proposal**

A Jira issue requires a title to be created, without a title you can't create an issue, so in my situation a security control. I had to improvisate and choose a title for each verification. I wonder if it could be useful to state that a verification point should be a title and a description, and not only a description. In the current case, it misses the opportunity to standardize the integration of security controls in issue tracking systems.

**So what do you think to add a column for verifications title?**

**Comment by elarlang** [comment]
Hi, Toufik!

First - I don't think we need to present verification requirement texts in different wordings. It's quite complicated to get only this one version precise :)

Second - maybe I'm not into this "user-stories" topic enough, but I don't get it - what extra value it gives in pentest context?

If I write some finding to pen-test report, I need to describe it from many roles perspective - risk for en end user, risk for an application owner, opportunities for an attacker. So it's not one-to-one relation for my brain to cover and limit it to only for one option per requirement.

Requirements are quite abstract and cover quite wide range of situations. I'm not sure it is possible to cover that.

But. This is only my opinion.

If you want to develop it further, please fork the ASVS and add "extra-layer" for "Jira integration" for that. There have been some initiatives for user-stories previously as well, see https://github.com/OWASP/ASVS/issues/813. If you are doing the same thing, maybe you can co-operate etc.

Any thoughts, feedback?

**Comment by tghosth** [comment]
This sounds to me like a type of mapping where we want to map a title to a requirement. Our general direction would be to keep mappings separate from the main standard as otherwise the main standard gets a bit messy.

**Comment by toufik-airane** [comment]
Dear @elarlang, @tghosth,

To resume the idea is to add a title to verification controls to make them handlable by any Jira-like issue tracker to coordinate security-by-design efforts. The improvement should help the work for application security engineers.

But I don't want to add friction to the ASVS project progression. This issue helps me to survey the value of this idea.

On my side, I've already written a title for each verification control. I will probably push them in a fork.

Thank you for your attention.
Regards.

**Comment by avasiljeva** [comment]
This topic is interesting. I definitely see the value in the work you did, @toufik-airane. Creating a pre-defined library of Jira tickets to be able to include 'security controls' related work into the project backlog from the start - I'd love to have it. Please share the fork in case you manage to push your adjustments.

**Comment by toufik-airane** [comment]
Thanks for your interest. Give me some time, I will definitely share these titles.
