### ISSUE TITLE
V1 - new documentation requirements

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1231]
I collect here requirements for documentation - those are pre-conditon to be able to make pentest.

Later or at the end those will be (probably) requirements in V1 category

* logs
  * https://github.com/OWASP/ASVS/issues/892
* sensitive data
  * https://github.com/OWASP/ASVS/issues/1064
* business logic limits
* used components (SBOM)
* external resources (for allow-listing outgoing connections, defense/lowering impact for SSRF for example)
  * https://github.com/OWASP/ASVS/issues/993
* browser version check
  * https://github.com/OWASP/ASVS/issues/959
* file upload
  * https://github.com/OWASP/ASVS/issues/1604

**Comment by tghosth** [comment]
@set-reminder 5 weeks @tghosth to look at this

**Comment by elarlang** [comment]
I'll close this issue, as it was a temporary solution to collect information for the "need for documentation requirements". For now, we know we need them and those are implemented or will be implemented.
