### ISSUE TITLE
Admin password change issue

### ISSUE THREAD

**Issue by csfreak92** [OWASP/ASVS#1239]
I have seen some web applications (mostly) that allow `administrator/superadmin` users to change passwords of any user in their system. Some of them probably have a business case for it that when the admin triggers a change password request, this sends an email to the user and he/she will have to update his/her own password. In some weird cases I've seen admins can change and pick the passwords for any user of their system including other admins. This is not a great idea even if the person doing the change is a trusted party. Ideally, all users must change and manage their passwords. 

I know this is a very common sense and elementary idea, but other applications are still doing this including some of the big enterprises which surprised me that they have not been implementing password changes properly in this regard. We don't have anything in the standard that calls this out, probably because as I said this is common sense, though maybe we should start calling this out to send the message that it should not be implemented like that. I would like to suggest adding a requirement to ASVS for this under `V4.3 Other Access Control Considerations` as I see it fits well there.

**Comment by tghosth** [comment]
Do you think this is already covered by [2.3.1](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x11-V2-Authentication.md#v23-authenticator-lifecycle) or [2.5.6](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x11-V2-Authentication.md#v25-credential-recovery)?

**Comment by csfreak92** [comment]
Ideally, people should have picked that up using those two controls but some may have weird cases where the initial password generation is random, but later on an admin can still login to the user management feature of the system and just change someone else's password. I know it sounds quite funny and not great but that's what I've observed in testing web apps.

**Comment by tghosth** [comment]
so maybe you need to add a note forbidding that kinda thing in 2.5.6

**Comment by elarlang** [comment]
We don't need new requirement for that, 2.5.6 covers it. 2.3.1 may have some note to cover password reset scenario as well.

**Comment by csfreak92** [comment]
So just a note under 2.5 section that says admins should not be able to change other user's passwords? Although section 2.5 talks about `Credential Recovery` requirements and technically it is not recovery as the admin just changed it. Would that be the right section?

**Comment by tghosth** [comment]
If you think it is not clear from those two requirements then you could suggest a modification to them to make it clearer.

**Comment by tghosth** [comment]
Thanks for the PR, unfortunately I think that any clarification should be within the requirement itself. I know we have the notes around the requirements but to be honest I don't know how many people really use them and I think it is important that the requirements are clear. If I close the current PR, can you try something which is within the requirements themselves. Sorry :(

**Comment by csfreak92** [comment]
Ah, gotcha @tghosth although we are talking about two requirements here as mentioned it was `2.3.1` and `2.5.6`. I think it will look silly having both of them with the redundant note, so maybe I'll just select the one that seems the best for this case that I raised up. Also, I am totally wondering about the same thing, not sure how many people really read the notes around the requirements at all. :) No worries, I will create a new PR for that one.

**Comment by tghosth** [comment]
Ok... I apologies in advance that I don't think we are there yet...

I had a look a the PR. This requirement is now getting a bit large and painful... I am also questioning whether this is best in 2.3 or 2.5.

I think maybe we need another requirement to be added to either 2.3 or 2.5 which just says.

> Verify that no one other than the user (including system administrators) can choose the value of a user's password.

What do you think? If you agree, can you modify the PR...?

**Comment by csfreak92** [comment]
No worries @tghosth, I share the same opinion that making `2.3.1` large is painful to read and implement. In my experience with clients and even developers, if it is a multi-line requirement, oftentimes the first line would only be taken care of and the rest is omitted or lost and never implemented as a control. 

Let me see what I can do with adding a requirement to either one of sections 2.3.x or 2.5.x. Will update the PR shortly.

**Comment by tghosth** [comment]
Thanks :)

**Comment by tghosth** [comment]
Merged the PR following further changes
