### ISSUE TITLE
[Clarification/For Discussion] 1.14.4 - "build and verify the secure deployment of the application"

### ISSUE THREAD

**Issue by blincoln-bf** [OWASP/ASVS#1245]
[1.14.4](https://github.com/OWASP/ASVS/tree/master/5.0) refers to "the secure deployment of the application". It doesn't refer to a CWE. It's unclear to me (and several other people I discussed this with) what is being required here. For context, here is the full text as it stands today:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.14.4** | Verify that the build pipeline contains a build step to automatically build and verify the secure deployment of the application, particularly if the application infrastructure is software defined, such as cloud environment build scripts. | | ✓ | ✓ | |

Here are a few alternative phrasings I can think of depending on what the intent is. I don't know that you need something quite this wordy, just trying to get across the different interpretations I see.

"Verify that the build pipeline contains steps to automatically build and deploy the application in a test environment, then automatically test that the deployment meets security requirements defined in the build pipeline. If the application infrastructure is software defined (such as cloud environment build scripts), verify that the automated build and deploy step creates an ephemeral instance of the infrastructure and deploys the application into that ephemeral instance, and that the automated security validation includes infrastructure-level tests."

"Verify that the build pipeline contains steps to validate the integrity of the source code, such as checking cryptographic signatures on code commits.  If the application infrastructure is software defined (such as cloud environment build scripts), verify that the same tests are applied to the infrastructure code."

"Verify that the build pipeline contains a step to generate metadata that can be used to cryptographically validate the integrity of the application, and a step that performs the cryptographic validation to ensure that it is successful.  If the application infrastructure is software defined (such as cloud environment build scripts), verify that the build pipeline generates and validates the integrity metadata for the infrastructure components as well."

i.e. is it more like "build and deploy the application, then validate that the deployed application is secure [in some way]", "build the application using secured source code", "build the application deployment package, then validate the security aspects of the deployment package itself", or something else?

If it's the second one, [CWE-494](https://cwe.mitre.org/data/definitions/494.html) could be referenced. I didn't find a good CWE match for the other two cases.

**Comment by tghosth** [comment]
This ties into the whole #1315 thing

**Comment by tghosth** [comment]
@set-reminder 3 weeks @tghosth look at this

**Comment by tghosth** [comment]
I think this is less about code security and more about configuration security.

In https://github.com/OWASP/ASVS/issues/1271#issuecomment-1360918374 I have suggested an update to a related requirement [14.1.5](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x22-V14-Config.md#v141-build-and-deploy) which talks about secure environment configuration.

To me, the question is whether this requirement 1.14.4 is practically speaking a duplicate of [14.1.3](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x22-V14-Config.md#v141-build-and-deploy) or whether they sound different enough in the context of my suggestion for 14.1.5.

14.1.3 reads:
> [MODIFIED] Verify that configuration hardening is performed on all 3rd party products, libraries, frameworks and services as per their individual recommendations.

My suggestion for 14.1.5 is [here](https://github.com/OWASP/ASVS/issues/1271).

**Comment by tghosth** [comment]
@set-reminder 4 weeks @tghosth to look at this

Probably need to dig through the history and decide on the question above:

> To me, the question is whether this requirement 1.14.4 is practically speaking a duplicate of [14.1.3](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x22-V14-Config.md#v141-build-and-deploy) or whether they sound different enough in the context of my suggestion for 14.1.5.

**Comment by elarlang** [comment]
2 notes:
* build pipelines are questioned to be in the scope
* it the requirement and/or it's modification stays, it is implementation requirement and should be moved to "V14.1 Build and Deploy"

**Comment by tghosth** [comment]
Having thought long and hard and since our discussion about the scope of build pipelines, I am inclined to delete this as I think it is not in scope and not well defined.

**Comment by jmanico** [comment]
I am inclined to delete this as well

**Comment by tghosth** [comment]
Opened #1662 to resolve this.
