### ISSUE TITLE
14.4.6 Need to always require Referrer-Policy?

### ISSUE THREAD

**Issue by maizuka** [OWASP/ASVS#1262]
[14.4.6](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x22-V14-Config.md#v144-http-security-headers) require Referrer-Policy in response headers.

> Verify that a suitable Referrer-Policy header is included to avoid exposing sensitive information in the URL through the Referer header to untrusted parties.

However, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy), the default policies in modern browsers are set to `strict-origin-when-cross-origin`, which doesn't leak the URL path across origins. Internet Explorer doesn't support this header. So the default without the header is not problem.

On the other hand, customizing by the header might bring some failure.

My suggestion is that we check the policy in the header if exists, but the absence is ok.

> Verify that the specified policy in the Referrer-Policy header does not cause the browser to send URL paths for cross-origin requests through the Referer header to avoid exposing sensitive information in the URL.

**Comment by elarlang** [comment]
You expect, that all users are using modern and up-to-date browsers. It's a bit too optimistic.

Point to set this header is to not hope for browser's default settings, but to say clearly, how to handle it.

I can not see improvement from proposal - given wording expects that the header exists.

**Comment by maizuka** [comment]
I agree that it should support wide range of browser environments. But there is limit somewhere.

There doesn't seem to have a clear guide for the range. Because X-XSS-Protection was removed in v4 ([commit](https://github.com/OWASP/ASVS/commit/751cdbce263ee3214e9783a33d10026d10d2c92c)), defense-in-depth seems to be cut off for some situation such as IE. My idea is based on the hypothesis.

I see this requirement as one of the defense-in-depths since URL should not have sensitive information as [13.1.3](https://github.com/OWASP/ASVS/blob/a0b99845684d4836928a7ac5df195e2cd5c72351/5.0/en/0x21-V13-API.md#v131-generic-web-service-security).

I found that the default has been implemented in a few years, so it is okay if it should support to that versions. For example, Firefox changed it at release on Mar 2020. This page has details.
https://caniuse.com/referrer-policy

**Comment by jmanico** [comment]
Enabling the XSS Browser Auditor is very dangerous because it adds XSS where none existed before. I suggest X-Xss-Protection be set to 0. This is why the browsers have removed it.

Here is some research that illustrates this. https://infosecwriteups.com/xss-auditor-the-protector-of-unprotected-f900a5e15b7b

Also, no one should be using Internet Explorer. It's an end of life browser with bad security.

**Comment by elarlang** [comment]
X-XSS-Protection did not provide protection and was removed from browsers for that reason. It was a mistake and It's not good thing for comparing.

I analyzed referrers from one of my web sites, and there were still many Full-URL Referer sendings. Clear reality is, that is not time yet to remove this requirement.

"Old browser" problem should be covered with this issue:
https://github.com/OWASP/ASVS/issues/959

**Comment by maizuka** [comment]
Thank you for information. I understand the reason about X-XSS-Protection correctly. The discussion #959 looks interesting and I will subscribe.

Elar's result is critical in this issue. Could you tell me one of the conditions where full URLs are sent?
Finally, I think this issue should be closed. Thanks a lot.

**Comment by maizuka** [comment]
> Could you tell me one of the conditions where full URLs are sent?

I misunderstood. The analysis is from the server logs so I have no question about it.
