### ISSUE TITLE
How many failed attempts?

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1264]
How many failed login attempts should trigger an account lockout or similar?

A new intelligent student of mine asked this and I'd like ASVS to address this.

:)

**Comment by elarlang** [comment]
We have opened issue for searching answer for that question: https://github.com/OWASP/ASVS/issues/906

closing as duplicate

**Comment by jmanico** [comment]
Perfect can you close this out for me? I’m on the run…
