### ISSUE TITLE
Drift prevention / tamper protection

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1271]
> 14.1.5  Verify that authorized administrators can verify the integrity of all security-relevant configurations to detect tampering.

[Live version](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x22-V14-Config.md#v141-build-and-deploy)
[Point in time version](https://github.com/OWASP/ASVS/blob/cda75733b1f8740a64db1a6241bd48e402dbb6e3/5.0/en/0x22-V14-Config.md#v141-build-and-deploy)

We currently have this mechanism as an L3 control. 

Is this the same as [drift prevention](https://blog.aquasec.com/cloud-native-security-drift-prevention)? Should we be clearer about this?

**Comment by jmanico** [comment]
Meh, this seems really esoteric, I'd like to drop 14.1.5

**Comment by tghosth** [comment]
So drift prevention is important for things like infrastructure as code where you are expecting the environment config, my main question would be whether this is not really application code which is more of the focus of ASVS but more like some sort of grey area around application infrastructure...

**Comment by yosignals** [comment]
security configuration attestation is what we’re looking for here, ‘verify an administrator can verify’ forgive me ! Is a bit word soupy, - perhaps 4 (appropriate) eyes on changes is enough ? Day to day

**Comment by tghosth** [comment]
I am inclined to agree to remove as I think that the [ephemerality](https://pipelinedriven.org/article/ephemeral-environment-why-what-how-and-where) concept discussed in #1315 is more actionable. What do you think @wet-certitude?

**Comment by tghosth** [comment]
Any further comments @wet-certitude?

@set-reminder 2 weeks @tghosth decide what to do if no response

**Comment by tghosth** [comment]
So the ephemerality reference in #1315 is more about the build environment rather than the deployed environment itself.

I would therefore suggest the following more specific control:
> 14.1.5 Verify that deployed environments are short lived and frequently redeployed to a "known good" but updated state. Alternatively, long lived environments should use some form of "drift prevention" to ensure that deployed configurations are not changed to an insecure state.

I think this is easier to understand. Whilst it is difficult to enforce, it is L3 so that is kinda expected.
