### ISSUE TITLE
"Clear-Site-Data" HTTP response header

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1273]
Should we mandate the use of the  ["Clear-Site-Data" HTTP response header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data)?

[Browser support](https://caniuse.com/?search=clear-site-data) seems to be reasonable.

I can imagine that clearing all cookies on an origin might be undesirable but clearing the other items on logout seems more reasonable.

I would see this as a level 2 or 3 control.

What do people think?

**Comment by elarlang** [comment]
A bit too early maybe? https://caniuse.com/mdn-http_headers_clear-site-data_cache

**Comment by tghosth** [comment]
Yeah but compare to: https://caniuse.com/mdn-http_headers_clear-site-data_storage

**Comment by tghosth** [comment]
Good question, IMHO this is less relevant for 8.2.2 but I guess this is a way of achieving 8.2.3. However, that now raises the question of whether it should be in chapter 8 or in the chapter with the other HTTP security headers (is that 14?) 

What do you think?

**Comment by elarlang** [comment]
I see it as one technique to achieve V8.2.3 and I would not change it.

This `Clear-Site-Data` header is not webserver configuration topic - you don't "hardcode" this header to webserver, but need to send it on logout situation from program code (correct?). It's similar to Set-Cookie header.

**Comment by tghosth** [comment]
So maybe we should add it as an example to the 8.2.3 requirement rather than requiring it explicitly?

**Comment by elarlang** [comment]
It provides one technical solution, but I can see also negative part of (only) using this.

Let's say user was authenticated to some application and then lost internet connection - in this situation, client-side (browser) should be able to cleanup all the things itself.

**Comment by tghosth** [comment]
So maybe we need to specify that as well:

> V8.2.3 Verify that authenticated data is cleared from client storage, such as the browser DOM, after the client or session is terminated. The "Clear-Site-Data header" may be able to help with this but the client-side should also be able to perform this clear up if the server connection is lost.

**Comment by elarlang** [comment]
Ok, hard work, you got it in ;)

**Comment by jmanico** [comment]
I do not think we should mandate it, 8.2.3 says "may" which I think is enough for now. Not browsers support this yet.
