### ISSUE TITLE
Normalize the use of "risk based", "high value" etc

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#129]
In the ASVS, we use L1 ... L2 ... L3 to indicate risk, but I think in L2 there is scope for risk based inclusion, such that:

* Verify that OPTIONAL THING EXISTS, where the application or its data has been assessed as high risk or this is a business requirement. 

We should make something like this the standard way we express an optional but desirable goal. There are heaps of these requirements throughout. I want to give assessors a way to exclude looking for something if it's not that important, but they are doing a L2 assessment. 

For example:

2.25	Verify that high value applications can be configured to disallow the use of a configurable number of previous passwords.

becomes

2.25 Verify that the application is configured to disallow the use of a configurable number of previous passwords, where the application or its data has been assessed as high risk or this is a business requirement. 

Thoughts?

**Comment by vanderaj** [comment]
Pls comment @danielcuthbert

**Comment by jmanico** [comment]
I really don't like this for some reason. It makes the requirements WAY WAY to messy. I'm suggest we keep requirements as concise as possible. I politely vote thumbs down and find another way to add this attribution if necessary.
