### ISSUE TITLE
I think the requirement 12.2.1 should be more explicit

### ISSUE THREAD

**Issue by hansphp** [OWASP/ASVS#1291]
Hello,
I think the requirement 12.2.1 should be more explicit.
I have noticed that many developers confuse content integrity with file signature.
I suggest the following [https://github.com/hansphp/ASVS/commit/d1b32f2c60dab790e12f048e177b8bd4390e54da](https://github.com/hansphp/ASVS/commit/d1b32f2c60dab790e12f048e177b8bd4390e54da)

I request a hearing for PR.

**Comment by elarlang** [comment]
Current requirement:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **12.2.1** | Verify that files obtained from untrusted sources are validated to be of expected type based on the file's content. | | ✓ | ✓ | 434 |

Point for the requirement: if you are waiting image files, then user can not upload any other formats.

Can you explain - how your recommendation improve the requirement or what exact problem it solves?

**Comment by RafaelGreen1** [comment]
Hi,
I think that @hansphp meant to say that the heading above the table doesn't match the table's content.
The heading is: **V12.2 File Integrity**
Thanks,
Rafael,

**Comment by elarlang** [comment]
Agree with that word, for me it's basically input validation issue here.

**Comment by hansphp** [comment]
Of course, Need to be more explicit for these cases:

Suppose we have this file:
![image](https://user-images.githubusercontent.com/6464707/174214244-c6b247d2-e0ce-40a7-bd4d-f411e33361dd.png)

Under specific configuration conditions it could be executed:
![image](https://user-images.githubusercontent.com/6464707/174214379-2f2952c7-cee6-4e60-bfab-523727cb7e0e.png)

The above file complies with being of the correct extension, of the correct file type, but does not comply with the overall integrity of the file.

This is what this point is about and most file input validations are only restricted to validating extension and file type.

There are other more complex attacks such as PHP Wrapping, where a breach like this would allow LFI to be carried out.

**Comment by elarlang** [comment]
Ok, thank you for feedback.

For me the requirement text is covering this scenario clearly: "Verify that files obtained from untrusted sources **are validated** to be of expected type **based on the file's content**."

If we could start listing "for image files, check image size, for pdf check something else" - then we give examples, but the point for the requirement stays like it is at the moment.

Personally I would like to get rid of the phrase "untrusted".

**Comment by tghosth** [comment]
Hi @hansphp, I think I understand your point. To me it is about trying to be more sophisticated in how we verify that the file is really what it says it is.

What do you think about the following?

12.2.1:

> Verify that files obtained from untrusted sources are validated to be of expected type based on the file's content. **Ideally this should be more sophisticated than just checking the initial "magic bytes" of the file**.

**Comment by SoftwareSinner** [comment]
This one has me scratching my head at times when reading it. 


"Verify that files obtained from untrusted sources are validated to be of expected type based on the file's content."

I think maybe wording it as "Verify that files obtained from untrusted sources are validated to be of expected type or extension" 

??

**Comment by elarlang** [comment]
I don't think we go in an improvement direction at the moment.

If someone says to me "do it a more sophisticated way", it does not say to me, what I actually need to do now.

> ... or extension
This is exactly the reason why this requirement exists - do not rely on the file extension.

The point for this requirement - the file actual content must be what you expect on the application side and a user can not upload javascript, php or whatever other files saying, that this is image by extension or by content-type.

First - how far we can go with that requirement? We have polyglot files - by every meaning correct image by content, but it can be still valid javascript or php file. But this part is more important how those files are accessed or served later.

If the application uses user-uploaded file name later on serving the file - it's important to have additional check, that for uploaded file - file content and file extension are matching. From serving the file perspective, it's covered by requirement V14.4.1:

> Verify that every HTTP response contains a Content-Type header. Also specify a safe character set (e.g., UTF-8, ISO-8859-1) if the content types are text/*, /+xml and application/xml. **Content must match with the provided Content-Type header.**

The same applies, when serving the file, user-provided content-type value is used.

We can put this to the requirement, like be sure that file extension, content-type (mime-type) and file actual content are matching each other. But.. if the application just uses file content and it is in expected/allowed list then it does not matter what was the file extension or mime-type on file upload.

**Comment by tghosth** [comment]
@elarlang I agree that how a file is served later is important but as you say we have a requirement to cover that.

I also think that there is value in enforcing controls around files when they are received. I take your point about the fact that it is not so actionable.

12.2.1:

Verify that files obtained from untrusted sources are validated to be of expected type based on the file's content, **including but not limited to checking the initial "magic bytes" of the file**.

Do you think this is clearer that we would like them to do more without making too much of a judgement? Clearly we cannot give more details to satisfy every case.

**Comment by elarlang** [comment]
What is the actual problem we are solving here?

Initial proposal for improvement was phrase:
_"Not just checking the file signature. For example, an image file should have properties such as width and height."_

And now we are close to opposite phrase:
_including but not limited to checking the initial "magic bytes" of the file._

I don't mind to have the last proposal, but I don't mind also to keep the requirement like it is. If you give an example as "magic bytes", I think in practice it will be taken as the main test-case here and at the end it works exactly opposite direction against first proposal.

**Comment by tghosth** [comment]
I think the aim is to clarify what we mean but file content. If that ends up just being "magic bytes" then I think that is ok as it clarifies the sort of direction we are looking for.

**Comment by elarlang** [comment]
Ok, let's go with last proposal (_Verify that files obtained from untrusted sources are validated to be of expected type based on the file's content, including but not limited to checking the initial "magic bytes" of the file._).

Like I mentioned, personally I would like to get rid of the phrase "untrusted" - from the application side, everything should be handled as untrusted.

My proposal (we can use also "all files" instead of "files"):
_Verify that files are validated to be of expected type based on the file's content, including but not limited to checking the initial "magic bytes" of the file._

**Comment by tghosth** [comment]
I understand dropping "untrusted sources" but I think we still need to be specific so how about:

_Verify that files **being processed by the application** are validated to be of expected type based on the file's content, including but not limited to checking the initial "magic bytes" of the file._

**Comment by tghosth** [comment]
Hey @elarlang 
I understand dropping "untrusted sources" but I think we still need to be specific so how about:

_Verify that files **being processed by the application** are validated to be of expected type based on the file's content, including but not limited to checking the initial "magic bytes" of the file._

**Comment by elarlang** [comment]
"being processed by the application" in also unnecessary limitation. For (business logic) integrity, the application must validate files also in case, when the application does not process them but only serving them for (for example backoffice) users.

**Comment by tghosth** [comment]
We need a way to be clear about the sort of files we are talking about here. We aren't just talking about every file involved in the application like code files. How do we specify this?

**Comment by Sjord** [comment]
> For example, an image file should have properties such as width and height.

[PHP docs disagree](https://www.php.net/manual/en/function.getimagesize.php):

> Do not use getimagesize() to check that a given file is a valid image. Use a purpose-built solution such as the [Fileinfo](https://www.php.net/manual/en/book.fileinfo.php) extension instead.

And Fileinfo looks at the magic bytes.

> Verify that files obtained from untrusted sources are validated to be of expected type based on the file's content.

I think this is fine. For me "untrusted sources" means user input. We could say as much to make it clearer, but I think it's fine.

Checking the file's content only goes so far. I think checking magic bytes is fine. Actually validating whether something is an image can be pretty hard to do securely, especially if the validating image processor is different than the destination image processor. Furthermore, it is possible to put malicious code in valid images and documents, so this does not protect against `<?php` tags in your uploads.

**Comment by tghosth** [comment]
@elarlang what would you add to this requirement to give an example so as to make it clearer? I am not sure what you are suggesting

> Verify that files **being processed by the application** are validated to be of expected type based on the file's content, including but not limited to checking the initial "magic bytes" of the file.

**Comment by ImanSharaf** [comment]
I would suggest this check: _Verify that files obtained from untrusted sources are validated to be of expected type based on the file's content, using methods such as checking file extensions, validating file magic numbers, and verifying MIME types._

**Comment by securitydave** [comment]
As suggested in my closed issue https://github.com/OWASP/ASVS/issues/1623, we should have a requirement like the following. This is in agreement with some of above comments.

12.2.x (new) Verify that user-submitted filename extension matches content type.
CWE-646

**Comment by elarlang** [comment]
Related to previous comments:

  * https://github.com/OWASP/ASVS/issues/1291#issuecomment-1212102771
  * https://github.com/OWASP/ASVS/issues/1291#issuecomment-1212113067
  * https://github.com/OWASP/ASVS/issues/1291#issuecomment-1245747794

> Verify that contents of files being processed by the application are validated

If I read the requirement, for me it does not cover scenario "application allows users to upload files and later serves them" (without processing them on the server side). We can call accepting and later serving a file also processing, but there is assumption (which is mother of all ...) that everyone interpret it that way.

I don't have any wordsmithing proposals, just pointing out the problem.

**Comment by tghosth** [comment]
So how about the following @elarlang:


| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **12.2.1** | [MODIFIED] Verify that contents of files being accepted by the application are validated to match the expected type and that the file has the correct file extension, including but not limited to checking the initial "magic bytes" of the file. | | ✓ | ✓ | 434 |

**Comment by securitydave** [comment]
I suggest the following reshuffle of the sentence:
Verify that the contents of each file being accepted by the application are validated to match the expected type, including but not limited to checking the initial "magic bytes" of the file, and that the file has the correct file extension.

**Comment by tghosth** [comment]
> I suggest the following reshuffle of the sentence: Verify that the contents of each file being accepted by the application are validated to match the expected type, including but not limited to checking the initial "magic bytes" of the file, and that the file has the correct file extension.

So I worded this quite deliberately @securitydave  but maybe it needs to be clearer.

To my mind the following process needs to take place.

1) Have an expectation for the file types to be accepted.
2) Verify that the file extension matches that expectation (although this can be spoofed)
3) If 2 is successful, verify that the contents of the file matches the expected type from 2), including but not limited to checking magic bytes.

So what do you think about:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **12.2.1** | [MODIFIED] Verify that when the application is **accepting** a file, it checks that the file extension of the file matches an expected type and it validates that the contents of the file match that type, including but not limited to checking the initial "magic bytes". | | ✓ | ✓ | 434 |

**Comment by securitydave** [comment]
Yes, looks good to me.

**Comment by tghosth** [comment]
Opened #1681 to resolve this.

**Comment by tghosth** [comment]
In PR #1681, @elarlang said:

> > _it checks that the file extension of the file matches an expected type_

> instead of "expected type" maybe we should mention "allowed list of file extensions"? File extension and type is just not intuitive to put together,

So how about this @elarlang ?

> [MODIFIED] Verify that when the application is accepting a file, it checks that the file extension of the file matches an expected **file extension** and that it validates that the contents of the file match the **type represented by that extension**, including but not limited to checking the initial "magic bytes".

**Comment by elarlang** [comment]
I'm ok with this one, but there is some potential to make it easier.

What always matters, is file content.

File extension matters only when a file is served to the user (mostly as an attachment) and the file name from the user is used.
File content-type matters only when a file is served in-line and content-type from the user is used.
And also, in practice, content-type just duplicates the file extension.

When the application processes the file content (eg import, convert images, convert to pdf etc), it only requires correct content - file extension and content-type does not matter.

So, in practice, we don't need to check always everything like the current requirement says but I don't know how to make it easier and to be still clear and understandable.

**Comment by jmanico** [comment]
> When the application processes the file content (eg import, convert images, convert to pdf etc), it only requires correct content - file extension and content-type does not matter.

I disagree. File content and file extension need to match for a legit file.

**Comment by tghosth** [comment]
It might not matter but I think Jim's point is that it may be suspicious if a file is provided without an extension so maybe that would be considered a warning sign.

**Comment by jmanico** [comment]
There are files that claim to be a .gif that are really a script file 
that can be run as a shell script. In this case - a common attack - the 
file extension matches the magic bytes of the file, but the contents are 
not a valid .gif and do not match the file type.

Any time contents do not match the file type, that file should be discarded.

- Jim

**Comment by jmanico** [comment]
> It might not matter but I think Jim's point is that it may be suspicious if a file is provided without an extension so maybe that would be considered a warning sign.

My intention is an uploaded multi-part form, the file name extension must match the magic bytes and the file contents. They must all be congruent for a valid file upload.

**Comment by jmanico** [comment]
ASVS is also to help *developers* build more secure applications if you do not understand from an attackers perspective. 

There is no good reason to accept a file upload when the file extension, is one exists, does not match the file magic bytes and content. It’s a (very basic) part of file upload input validation.

It’s also helps detect malicious content if other controls like anti virus, which is faulty, misses a bad file.

**Comment by elarlang** [comment]
> It’s a (very basic) part of file upload input validation. It’s also helps detect malicious content if other controls like anti virus, which is faulty, misses a bad file.

I agree with that part - from functionality perspective it does not make sense .... 

> ASVS is also to help *developers* build more secure applications if you do not understand from an attackers perspective. There is no good reason to accept a file upload when the file extension, is one exists, does not match the file magic bytes and content. 

But, ASVS stands for Application *Security Verification* Standard and we should not have requirements like "Verify that your code makes sense even if there is no risk in that situation". Malicious content and virus checks are different topic from that requirement perspective.

**Comment by jmanico** [comment]
What is wrong with verifying that the file extension, magic bytes and 
content all match? What is that a bad control to verify? Is this 
something that you struggle to test for? Is it to hard for you as a 
pentester?Message ID: ***@***.***>

**Comment by elarlang** [comment]
I wrote my concern here: https://github.com/OWASP/ASVS/issues/1291#issuecomment-1634549994

> What I don't like here is exactly this - basically false negative reports - "in ASVS there is a requirement for that but it does not contain any risk in reality".

What I don't like here that service or product owners, who are ordering pen-testing/security assesment/however you call it service and they will have "noise" there: "you have huge problem because the application accepts valid content x with file extension Y". But the application does not user the file extension and "incorrect value" does not cause any security risk in practice.

So. This is my concern and this is what I don't like at the moment. At the same time I don't know how to improve it with keeping it still short and understandable. And also, with black-box pen-testing is not maybe detectable, do application uses file extension (or content-type) from user or not.


Like I wrote in the beginning of this extra-discussion round:

> I'm ok with this one, but there is some potential to make it easier.

So, I accept the PR and let's see what the future brings with this one.

**Comment by tghosth** [comment]
@elarlang ok so I have updated the PR, if you are comfortable enough with it, please merge it.

**Comment by elarlang** [comment]
If we want to develop the requirement further, then - there is "that" 5 times in the requirement.

**Comment by jmanico** [comment]
What is wrong with **that**?

**Comment by elarlang** [comment]
Nothing, just a bit repetitive. Pointed out as potential for improvement, not as a party stopper.

**Comment by jmanico** [comment]
Ok, that's cool, Elar.

**Comment by jmanico** [comment]
May I suggest :

12.2.1 | [MODIFIED] Verify that the application verifies the file extension matches an expected type when accepting a file. Additionally, validate that the file's contents correspond to that type. This includes checking the initial 'magic bytes', performing PDF or image validation (using image re-writing), or using specific file validation libraries to validate the file  contents.  |   | ✓ | ✓ | 434
-- | -- | -- | -- | -- | --

**Comment by jmanico** [comment]
Actually we do need a grammar change

12.2.1 | [MODIFIED] Verify that when the application is accepting a file, it checks that the file extension of the file matches an expected file extension and that it validates that the contents of the file match the type represented by that extension, including but not limited to checking the initial "magic bytes". |   | ✓ | ✓ | 434
-- | -- | -- | -- | -- | --

**Comment by jmanico** [comment]
Change suggestion with less "That"

12.2.1 [MODIFIED] Verify that when the application accepts a file, it checks if the file extension matches an expected file extension and validates that the contents correspond to the type represented by the extension. This includes, but is not limited to, checking the initial 'magic bytes'. ✓ ✓ 434

**Comment by jmanico** [comment]
Any may I also suggest:

12.2.1 [MODIFIED] Verify that when the application accepts a file, it checks if the file extension matches an expected file extension and validates that the contents correspond to the type represented by the extension. This includes, but is not limited to, checking the initial 'magic bytes', performing image re-writing, and using specialized libraries for file content validation. ✓ ✓ 434

**Comment by tghosth** [comment]
Looks good, want to open a PR @jmanico

**Comment by jmanico** [comment]
PR is in, @tghosth https://github.com/OWASP/ASVS/pull/2009
