### ISSUE TITLE
new requirement - one application per hostname (and remove current 3.4.5)

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1299]
Initial discussion on requirement 3.4.5 in issue #978 . But I would solve it a bit different way and it deserves separate issue, as it is quite big change.

Problems to solve: if one application is compromised, it should not affect others. Even those are separated on the filesystem or hosting, host, origin or domain name will be the keyword here.

If the application uses cookies
* we need to have one application per host/origin and `__Host-` prefix used for session cookies
* OR we need to have one application per eTLD (effective Top Level Domain)

If the appication do not use cookies
* we need to have separation for SOP (Same Origin Policy)

If this idea develops as new requirement, it drops current 3.4.5.

**Comment by Sjord** [comment]
> we need to have one application per host/origin

This should be "host", not origin. Specifically, it should not be allowed to run different applications on different ports. Applications running on different TCP ports would have different origins, but the `__Host-` prefix does not protect cookies on different ports from interfering.

> we need to have one application per eTLD (effective Top Level Domain)

While this makes sense in respect to cookies, it makes phishing much easier. Checking whether the domain name is legit is easier for online.microsoft.com than for microsoftonline.com.

I would propose to have a requirement saying "every application must run on its own (sub)domain", and not make distinction between cookies or not, and not mention cookie prefixes as it's already a requirement.

**Comment by elarlang** [comment]
> Applications running on different TCP ports would have different origins

technically possible, never seen in practice for public websites. It is used for internal API's, probably we need to exclude this somehow in the requirement?

> we need to have one application per eTLD (effective Top Level Domain)

this was given as an alternative. If there is just one application per domain, we don't have a lot of other problems and therefore the need to solve them. But I agree, it's easier to leave this option completely out

> every application must run on its own (sub)domain

I think host**name** is correct to user here instead of domain or subdomain

**Comment by tghosth** [comment]
@elarlang 
Does this requirement boil down to something like:

> Verify that multiple, separate applications are not hosted on the same hostname.

**Comment by elarlang** [comment]
For me, yes. I'm a bit concerned, is it clear enough. Like how to define, what is an application? If there is "public site", "self service" and "back office" - are those part of the same application or are those separate applications.

**Comment by tghosth** [comment]
Maybe the answer is applications with separate session mechanisms should be on different origins?

If I understand correctly, the problem is that XSS on 1 app will affect apps 2 and 3 on the same origin which use cookies, even if the cookies/session mechanisms of app 2 and app 3 are different to each other and/or app 1. Is that correct?

By that logic, the requirement would be:
> Verify that multiple, separate applications with different session mechanisms are not hosted on the same hostname.

What do you think @elarlang ?

**Comment by elarlang** [comment]
Session mechanism does not matter, if many applications are hosted on the same origin - in XSS situation you can force/automate victim browser to do actions in any case.

**Comment by Sjord** [comment]
> Verify that multiple, separate applications are not hosted on the same hostname.

I would say it the other way around:

> Verify that a hostname hosts only a single application.

I think this should be a level 1 requirement. Should it go under 3.4? Or perhaps in chapter 14? I couldn't find a specific CWE, but [CWE - CWE-668: Exposure of Resource to Wrong Sphere (4.8)](https://cwe.mitre.org/data/definitions/668.html) seems applicable.

**Comment by elarlang** [comment]
For category - personally I would like to have separate (sub)category for all SOP, CORS, CSRF related requirements.

**Comment by tghosth** [comment]
> What I think @tghosth was trying to say is that https://example.com/a and https://example.com/b are different applications, if the session cookie used for authentication differs between these pages. Pages that use the same authentication method are of the same application and can run on the same host.

Yes that is what I meant, if they have the same session mechanism then they can be on the same origin. On the other hand, maybe the point here is to reduce co-location of applications in general regardless of session mechanism so maybe:

> Verify that separate applications are not hosted on the same hostname to reduce the blast radius of origin based attacks.


What do we think?

**Comment by elarlang** [comment]
Ok to move on with requirement text.

With category we need to wait the outcome from #1230

**Comment by Sjord** [comment]
I think a requirement could be sufficiently clear without explicitly defining what an application is. I think it's sufficiently clear for most people what an application is, but defining it exactly in a one-sentence requirement can be pretty hard.

I can see some exceptions to this. For example, a website without authentication which hosts multiple JavaScript games could be fine.

> blast radius

I would prefer something less metaphorical.

> are not hosted

I would prefer a positive recommendation instead of a negative one.

**Comment by tghosth** [comment]
@Sjord good points, how about:

`Verify that separate applications are hosted on different hostnames to reduce the risk of origin based attacks which impact every application on the same hostname`

**Comment by tghosth** [comment]
I still think it is important to include a reason. How about:

`Verify that separate applications are hosted on different hostnames so as to benefit from the protections provided by the "same origin policy".`

**Comment by elarlang** [comment]
> I still think it is important to include a reason. How about:
> 
> `Verify that separate applications are hosted on different hostnames so as to benefit from the protections provided by the "same origin policy".`

It fits JavaScript-related problems, but does not fit with cookie-related problems - there is the keyword hostname. See 
https://github.com/OWASP/ASVS/issues/1299#issuecomment-1167183581

**Comment by tghosth** [comment]
Ok, so how about:

`Verify that separate applications are hosted on different hostnames so as to benefit from the protections provided by the "same origin policy" and the hostname restrictions on cookies.`

**Comment by elarlang** [comment]
Current proposal:
* Category: waits outcome from #1230 
* Requirement: _Verify that separate applications are hosted on different hostnames so as to benefit from the protections provided by the "same origin policy" and the hostname restrictions on cookies._
* Level 1
* [CWE-668: Exposure of Resource to Wrong Sphere (4.8)](https://cwe.mitre.org/data/definitions/668.html)

**Comment by elarlang** [comment]
I added "Big decision" label - as this potential new requirement will affect a lot of applications and architecture decisions.

**Comment by tghosth** [comment]
hi @jmanico 

Do you think the following requirement change is appropriate and sensible? It is quite sweeping but seems to add a lot of value against attacks which can cross application boundaries.

Old requirement:

## V3.4 Cookie-based Session Management

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **3.4.5** | [GRAMMAR] Verify that if the application is published under a domain name with other applications that set or use session cookies that might disclose the session cookies, it sets the path attribute in cookie-based session tokens using the most precise path possible. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | ✓ | ✓ | ✓ | 16 | 7.1.1 |

New requirement (might change it to be in a different section)

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **3.4.5** | [MODIFIED] Verify that separate applications are hosted on different hostnames so as to benefit from the protections provided by the "same origin policy" and the hostname restrictions on cookies. | ✓ | ✓ | ✓ | 16 | 7.1.1 |

**Comment by jmanico** [comment]
I’m not sure I fully understand this one, so I’ll remain neutral.On Jul 10, 2023, at 10:29 PM, Josh Grossman ***@***.***> wrote:﻿
hi @jmanico
Do you think the following requirement change is appropriate and sensible? It is quite sweeping but seems to add a lot of value against attacks which can cross application boundaries.
Old requirement:
V3.4 Cookie-based Session Management



#
Description
L1
L2
L3
CWE
NIST §




3.4.5
[GRAMMAR] Verify that if the application is published under a domain name with other applications that set or use session cookies that might disclose the session cookies, it sets the path attribute in cookie-based session tokens using the most precise path possible. (C6)
✓
✓
✓
16
7.1.1



New requirement (might change it to be in a different section)



#
Description
L1
L2
L3
CWE
NIST §




3.4.5
[MODIFIED] Verify that separate applications are hosted on different hostnames so as to benefit from the protections provided by the "same origin policy" and the hostname restrictions on cookies.
✓
✓
✓
16
7.1.1

**Comment by tghosth** [comment]
@jmanico basically we are forcing companies to only ever host a single application on a single hostname. For example, if a company had two applications with different login/session mechanisms, they could not host them on:

* https://www.example.com/app1
* https://www.example.com/app2 
 
but rather they would have to do something like:

* https://app1.example.com/ 
* https://app1.example.com/

To me this sounds reasonable but quite strict/drastic which is why I wanted to get your thoughts as well

**Comment by jmanico** [comment]
This seems reasonable to me. Origin isolation is important!

**Comment by tghosth** [comment]
ok @elarlang, what do you think about #1701?

**Comment by elarlang** [comment]
There are quite many problems - V1 is not anymore v4.0.* style architecture category, but more documentation and decision category. This new requirement is something what you need to check from the implementation, so it does not belong there.

Additionally, it's not anymore session specific requirement, as it's also related same-origin isolation for javascript execution.

Also, it's not a modification of the current 3.4.5, but it deprecates it.

As temporary solution, we can just add new requirement to V3.4 (3.4.7) with label `ADDED` and delete 3.4.5 (I'll think about suitable label).

**Comment by elarlang** [comment]
Or, let's just create a new category "Client-Side" or with a better title and start adding related requirements there. https://github.com/OWASP/ASVS/issues/1299#issuecomment-1297487978

Related to https://github.com/OWASP/ASVS/issues/1230

**Comment by jmanico** [comment]
Great idea, Elar.

**Comment by tghosth** [comment]
So this feels like an architecture level requirement, there is an implementation but the requirement is at the very heart of the application is built (and it would be hard to retro fit this back onto an existing application.) That is why I moved it to V1. Do you disagree?

**Comment by elarlang** [comment]
Yes, I disagree. V1 it's logical for v4.0.3 but not for v5.0 - for v5.0 V1 is "documentation requirements".

It is architecture requirement, like proposed here 10 months ago: https://github.com/OWASP/ASVS/issues/1230#issuecomment-1287381350

New category "Client-Side" (or Browser side) and subcategory "Architecture".

**Comment by tghosth** [comment]
Do you remember where we defined V1 for v5.0?

**Comment by elarlang** [comment]
https://github.com/OWASP/ASVS/issues/1063

**Comment by tghosth** [comment]
Assuming it doesn't go in V1, what is the argument for putting it in client side? Because the protection is implemented at the client side?

**Comment by elarlang** [comment]
It's mostly Same-Origin or Same-Site policy, it's all for client side configuration and defense against client-side attacks.

**Comment by tghosth** [comment]
Ok so I am comfortable for this to go into the client side section so now we just need a client side section :)

**Comment by tghosth** [comment]
This was the latest recommended text:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **X.X.X** | [MODIFIED, MOVED FROM 3.4.5] Verify that separate applications are hosted on different hostnames so as to benefit from the protections provided by the "same origin policy" and the hostname restrictions on cookies. | ✓ | ✓ | ✓ | 16 |

**Comment by elarlang** [comment]
Just to note here - it will be with tag `ADDED` (see https://github.com/OWASP/ASVS/issues/1299#issuecomment-1654005638)

and CWE-16 is general category which CWE itself recommend to not link.

**Comment by tghosth** [comment]
@elarlang did you add this to your browser requirements draft?

**Comment by elarlang** [comment]
Yes, this is the cornerstone for all that:
https://github.com/elarlang/ASVS/blob/asvs-1230-attacks-via-browser/5.0/en/0x50-V50-attacks-via-browser.md#v501-site-isolation-architecture

**Comment by elarlang** [comment]
Prep for PR...
> Verify that separate applications are hosted on different hostnames so as to benefit from the protections provided by the "same origin policy" and the hostname restrictions on cookies.

One may read as it is all for cookies...

> Verify that separate applications are hosted on different hostnames so as to benefit from the protections provided by (the "same origin policy" and the hostname restrictions) on cookies.

But how to improve that? When using SOP definition from [MDN](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy), the idea should be something like:

> Verify that separate applications are hosted on different hostnames so as to benefit from the **restrictions** provided by the "**same-origin** policy" **how document or script loaded by one origin can interact with a resource from another origin** and the hostname restrictions on cookies.

Note: "same origin policy" will be changed to "same-origin policy".

**Comment by tghosth** [comment]
Suggested final wording for V50:

> Verify that separate applications are hosted on different hostnames so as to benefit from the restrictions provided by the "same-origin policy" including how documents or scripts loaded by one origin can interact with resources from another origin and hostname restrictions on cookies.

**Comment by elarlang** [comment]
The requirement is now merged to the new "Web Frontend Security" category, via https://github.com/OWASP/ASVS/commit/fb0113371191592787feeeecbc722973db903bfc

## V50.1 Site Isolation Architecture

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **50.1.1** | [ADDED, DEPRECATES 3.4.5] Verify that separate applications are hosted on different hostnames to benefit from the restrictions provided by the "same-origin policy" including how documents or scripts loaded by one origin can interact with resources from another origin and hostname restrictions on cookies. | ✓ | ✓ | ✓ | 668 |
