### ISSUE TITLE
 Adhere security.txt "Conanical" Field to RFC 9116

### ISSUE THREAD

**Issue by cmlh** [OWASP/ASVS#1306]
[V1 Architecture, Design and Threat Modeling V11 Secure Software Development Lifecycle Requirement 1.1.8](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x10-V1-Architecture.md#v11-secure-software-development-lifecycle) states "_[ADDED] Verify availability of a publicly available security.txt file at the root or .well-known directory of the application that clearly defines a link or e-mail address for people to contact owners about security issues._".

The "Canonical" field indicates the canonical URI[s] where the `security.txt` file is located.

Therefore I propose create a new requirement based on the text from [Section "Canonical" 2.5.2. of RFC 9116](https://www.rfc-editor.org/rfc/rfc9116.html#name-canonical)

**Comment by elarlang** [comment]
cover all with one issue and one requirement, see https://github.com/OWASP/ASVS/issues/1305#issuecomment-1166449877
