### ISSUE TITLE
Sign security.txt for RFC 9116 Adherence

### ISSUE THREAD

**Issue by cmlh** [OWASP/ASVS#1307]
[V1 Architecture, Design and Threat Modeling V11 Secure Software Development Lifecycle Requirement 1.1.8](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x10-V1-Architecture.md#v11-secure-software-development-lifecycle) states "_[ADDED] Verify availability of a publicly available security.txt file at the root or .well-known directory of the application that clearly defines a link or e-mail address for people to contact owners about security issues._".

I propose to create two new requirements related to [1.1.8](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x10-V1-Architecture.md#v11-secure-software-development-lifecycle):
- [ ] An OpenPGP Public Key is used to sign `security.txt` as specified by [Section 2.3. "Digital Signature" of RFC 9116](https://www.rfc-editor.org/rfc/rfc9116.html#name-digital-signature)
- [ ] Verify the OpenPGP Digital Signature of `security.txt`

**Comment by elarlang** [comment]
cover all with one issue and one requirement, see https://github.com/OWASP/ASVS/issues/1305#issuecomment-1166449877
