### ISSUE TITLE
Integration of RFC 9116 with Requirement 1.1.8 security.txt

### ISSUE THREAD

**Issue by cmlh** [OWASP/ASVS#1308]
@elarlang

As instructed within https://github.com/OWASP/ASVS/issues/1305#issuecomment-1166449877 below is the draft text for PR with reference to the child GitHub issue and relevant section of RFC 9116 "_A File Format to Aid in Security Vulnerability Disclosure_":

| [V1 Architecture, Design and Threat Modeling V11 Secure Software Development Lifecycle Requirement 1.1.8](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x10-V1-Architecture.md#v11-secure-software-development-lifecycle) | [MODIFIED] Verify availability of a publicly available security.txt file at the root or `.well-known` directory of the application that clearly defines a link or e-mail address for people to contact owners about security issues. | | ✓ | | 1059 |
| #1305 | [SPLIT] Verify that requesting the security.txt file at the root redirects to the `.well-known` directory i.e. Section 5.6. "Multi-User Environments" of RFC 9116 | | | ✓ | 1059 |
| #1305 | [SPLIT] Verify availability of a publicly available security.txt file at `.well-known` directory of the application that clearly defines a link or e-mail address for people to contact owners about security issues i.e. Section 3. "Location of the security.txt" File of RFC 9116 | | | ✓ | 1059 |
| #1306 | [SPLIT] Verify the URI for security.txt file is specified within the `Cananicol` Field i.e. Section "Canonical" 2.5.2. of RFC 9116 | | | ✓ | 1059 |
| #1307 | [SPLIT] Verify an OpenPGP Public Key is used to sign security.txt i.e.  Section 2.3. "Digital Signature" of RFC 9116 | | | ✓ | 1059 |
| #1307 | {SPLIT] Verify the OpenPGP Digital Signature of security.txt i.e.  Section 2.3. "Digital Signature" of RFC 9116 | | | ✓ | 1059 |

**Comment by elarlang** [comment]
as instructed?

* _**we will not create more than one requirement on the topic**_ - and you going to propose 6 here
* _If you have improvement proposals, with arguments, why it is important_ - the most important thing - can you provide **your interpretation** what kind of security problem it solves?
* _then **combine them to one issue** and to one requirement_ - you already had #1305 on the topic.

Please write your clear **and argumented** proposal to #1305 to cover all security.txt related proposals.
