### ISSUE TITLE
Non-pentestable items in Level 1

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#131]
oelnaggar04@gmail.com reports:

1.1 - Is not pen-testable as a pen-tester would not necessarily detect all components and libraries you link with or use

5.1 - The runtime environment may contain back-end components that are only reachable in certain scenarios and aren't really reachable via a penetration test.  Even if they are reachable, a pen-tester may not be able to verify a finding

5.3 - No way to know if these are logged or not via a pentest

7.7 - Is not testable as this section pertains to cryptography at rest

8.10 - Is not testable as the pen-tester will not have access to these logs

20.2 - I think this would be difficult to pentest without reverse engineering which would be difficult if debugging interfaces are disabled

**Comment by ossie-git** [comment]
Adding myself for follow-up

**Comment by jmanico** [comment]
So @vanderaj can we just move these items to level 2? Not sure how to handle.

**Comment by tghosth** [comment]
This issue came up from a different direction in [#350](https://github.com/OWASP/ASVS/issues/350#issuecomment-453808135).

**Comment by mgargiullo** [comment]
Why does a Level 1 assessment have to be completable via grey-box testing?
 
If you're scope of work only covers grey-box testing, then test as a Level 0 and note what was assessment and what wasn't (and why).

**Comment by jmanico** [comment]
This is a dupe, closing out
