### ISSUE TITLE
8.3.1 and 13.1.3 about data in URLs/query string seem to be duplicated

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1313]
Can anyone see why we should not merge these two requirements?

| # | Description |
| :---: | :--- |
| [8.3.1](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x16-V8-Data-Protection.md#v83-sensitive-private-data) | Verify that sensitive data is sent to the server in the HTTP message body or headers, and that query string parameters from any HTTP verb do not contain sensitive data. |
| [13.1.3](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x21-V13-API.md#v131-generic-web-service-security) | Verify API URLs do not expose sensitive information, such as the API key, session tokens etc. |

**Comment by elarlang** [comment]
Yes, duplicate.
https://github.com/OWASP/ASVS/issues/934#issuecomment-967275084

**Comment by jmanico** [comment]
I suggest a merger of the two for clarity.

Verify that sensitive data is sent to the server in the HTTP message body or headers and that any part of the URL does not expose sensitive information, such as the API key, session tokens, etc.

**Comment by tghosth** [comment]
Just to confuse matters, we also have 3.1.1. Is this not also a duplicate @jmanico / @elarlang ?

| # | Description |
| :---: | :--- |
| [3.1.1](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x12-V3-Session-management.md#v31-fundamental-session-management-security) | Verify that the application never reveals session tokens in URL parameters. |

**Comment by elarlang** [comment]
In case we don't want to put session tokens and api tokens to special hilight, we can get rid of 13.1.3 and 3.1.1.

I opened this discussion some time ago in another issue:
* https://github.com/OWASP/ASVS/issues/696#issuecomment-626231907
* https://github.com/OWASP/ASVS/issues/696#issuecomment-798953776

**Comment by tghosth** [comment]
Created 1330 to resolve this

**Comment by elarlang** [comment]
I approved PR, but it makes sense to work with comments by Sjord:
https://github.com/OWASP/ASVS/pull/1330#issuecomment-1214131403

**Comment by elarlang** [comment]
Reopen for confirming - do we want to take comments from Sjord into account?
https://github.com/OWASP/ASVS/pull/1330#issuecomment-1214131403

Current modified requirement:
_Verify that sensitive data is only sent to the server in the HTTP message body or headers and that the URL/query string do not contain sensitive information, such as an API key, session token, etc._

His proposal:
_Verify that sensitive data is only sent to the server in the HTTP message body or headers and that the URL and query string do not contain sensitive information, such as an API key or session token._

I prefer his proposal.

**Comment by tghosth** [comment]
I saw that you wanted him to put his points in another issue but maybe I mis-read. I agree with the PR and have merged it.
