### ISSUE TITLE
Extending ch.14.1 towards Ephemerality requirement (ASVS5)

### ISSUE THREAD

**Issue by moshe-apiiro** [OWASP/ASVS#1315]
Current Chapter 14 tackles Build and Deploy systems, specifically describing in 14.1.1:
> Verify that the application build and deployment processes are performed in a secure and repeatable way, such as CI / CD automation, automated configuration management, and automated deployment scripts.
as a requirement for L2 or above.

As supply chain attacks have been occurring/detected more over last few years now, there is a requirement which I think is not reflected by the current wording and usually being encapsulated by the word ‘[ephemerality](https://pipelinedriven.org/article/ephemeral-environment-why-what-how-and-where)’.

The concern there is that reusing any part of the system which is not ephemeral leads to attacks targeting this mechanism while residing as persistent threats on CI/CD systems.

To better cover this requirement, we can either re-word 14.1.1 to reflect this notion or create a new section, targeted at L3, to emphasize the riskier applications’ concern and dictate ephemeral build systems explicitly.

Personally, I tend towards the latter, but I can imagine the alternative being more elegant to some, especially if you see ephemerality fitting to a L2 requirement.

I would love to have your feedback on the matter

**Comment by moshe-apiiro** [comment]
@cmlh thanks for the input, care to elucidate on how you see verification in a point in time will satisfy the requirement?

**Comment by moshe-apiiro** [comment]
for the first point - ephemerality is usually seen as a stricter rule than permanent hosts, hence I can't seem to fit the Level 1 requirement you are proposing
also, as for the second point you suggested modifying 14.1.1 - isn't it contradicting L1?

I might be overcomplicating it or tangled in my own terminologies here, though, so excuse me if I'm missing a crucial point in what you are conveying

**Comment by moshe-apiiro** [comment]
Ephemeral CI agents are perceived as a more mature pipeline as they are more resilient to supply chain attacks (lowers the attack surface and virtually nullifies persistency attacks on those agents/hosts).
Do you see it otherwise or under a different prism as less mature CI pipeline?

**Comment by moshe-apiiro** [comment]
We should get an alignment on the topic and settle on the main ideas, then let's proliferate to other projects as well.

@cmlh I find your statement peculiar, can you share more about why ephemeral systems are less secure approach for build systems? the statement seems to contradict other standards as well, at least as far as I understand your statement for now.

**Comment by tghosth** [comment]
hi @moshe-apiiro,

Whilst I agree that something like this would seem to be a sensible level 3 requirement, I am a little concerned that we are potentially duplicating ground covered by both [OWASP SCVS](https://owasp-scvs.gitbook.io) and also [SLSA](https://github.com/slsa-framework/slsa).

@jmanico @elarlang @danielcuthbert, what are your thoughts on build environment controls? Do you think we should be explicitly including this (as we did in 4.x) or do you think we should be leaving it to other standards? I note that [SLSA](https://github.com/slsa-framework/slsa) still appears to be in a pre-release state and  [OWASP SCVS](https://owasp-scvs.gitbook.io) was last updated 1.5 years ago.

**Comment by tghosth** [comment]
@elarlang @jmanico , Daniel has said that build environment controls should stay in v5 of ASVS, what do you think?

**Comment by jmanico** [comment]
That works for me....

**Comment by jmanico** [comment]
Build controls seems more like architedcture and infrastructure, something I think we want to push off to a different standard. Also, I do not (at all) need special build controls to be secure, it's nice but not necessary.

**Comment by tghosth** [comment]
Tricky one. Daniel says yes and Jim says no

@elarlang what do you think?

**Comment by tghosth** [comment]
@elarlang any thoughts on this?

**Comment by tghosth** [comment]
@set-reminder 2 days look at this

**Comment by tghosth** [comment]
@coderpatros I think it would be hard to be sure of this without the ephemeral aspect of the build process.

**Comment by tghosth** [comment]
@set-reminder 3 weeks @tghosth to check progress on this issue

**Comment by moshe-apiiro** [comment]
@tghosth please review attached PR suggestion, per our resolution - written as a L3 requirement set at 14.1.8.
