### ISSUE TITLE
Terminology / Grammar

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#132]
oelnaggar04@gmail.com reports:

On page 8, I think you want to replace "version 3.0" with "version 3.1" and "ASVS 3.0" with "ASVS 3.1” (the first instance only I think)

Page 20 has to be updated to include the IoT section

1.6 "covers off risks" - this phrase is un-usual and I haven't seen it before.  I looked it up and found 50 references only on Google, most of them related to ASVS. "covers risks" I think would be preferable

1.11: platform -> platforms

2.22: "is known weak" -> "is known to be weak"

4.16: Authorization is spelled authorization in some parts of the document and authorisation in other parts.  There are also similar issues with modelling vs. modeling

9.8: "where logging of accesses is required".  Accesses is valid but sounds strange.  I think just access is fine

**Comment by ossie-git** [comment]
Adding myself for follow-up

**Comment by mastacheata** [comment]
That reference to 1.6 sounds like it was translated word by word from German ;)
Except for the Authori{z|s}ation part, which I didn't verify, all of these are gone in the current draft of 4.0
