### ISSUE TITLE
Include UUID v6, v7, v8

### ISSUE THREAD

**Issue by Sjord** [OWASP/ASVS#1323]
ASVS 6.3.2 says

> Verify that random GUIDs are created using the GUID v4 algorithm

IETF is working on [proposing new UUID versions](https://datatracker.ietf.org/doc/html/draft-peabody-dispatch-new-uuid-format), which may also be acceptable. We should evaluate these and consider allowing them in this ASVS requirement.

**Comment by tghosth** [comment]
It looks to me like v6, v7 and v8 are not designed to be fully random like v4 is so I don't think we would allow them. What do you think?

**Comment by Sjord** [comment]
UUID v4 contains 122 bits of randomness. UUID v7 contains 74 bits of randomness and a timestamp in milliseconds of 48 bits. That's less random, but still firmly in the territory of unguessable within reasonable times. It could be acceptable in some cases. Of course, it's easier and safer to only allow UUID v4. But if some application is using UUID v7 for an identifier, I wouldn't call it vulnerable in any way.

**Comment by tghosth** [comment]
I don't think it is just a question of guessability but also information disclosure. It looks like it is clear from a UUIDv7 when the UUID was generated.

**Comment by Sjord** [comment]
I hadn't considered that. Let's keep with UUID v4 for now.
