### ISSUE TITLE
V3.4.3 - CWE clarification

### ISSUE THREAD

**Issue by tadeuszwachowski** [OWASP/ASVS#1326]
requirement 3.4.3
"Verify that cookie-based session tokens utilize the 'SameSite' attribute to limit exposure to cross-site request forgery attacks."

CWE-16 is mapped to that control, however a better-suiting one is present: **CWE-1275: Sensitive Cookie with Improper SameSite Attribute** (https://cwe.mitre.org/data/definitions/1275.html)

Proposal - change CWE ID from 16 to 1275

**Comment by tadeuszwachowski** [comment]
Created PR https://github.com/OWASP/ASVS/pull/1328/commits/44a2c07bf9968f396429ecb97fbb77761d1f6d0d

**Comment by elarlang** [comment]
Merged, closed, thank you :)
