### ISSUE TITLE
V2 comments / additions

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#133]
V2: Authentication verification requirements
I think that some of the requirements are too stringent for L1 applications such as:

2.20 - anti-automation
2.27 - P@ssw0rd is an example of a commonly used password.  It's a bad password but forcing the application to check for a list of the most common X passwords from SecLists that meet complexity rules but are poor passwords is I think too stringent for L1 applications (most enterprises don’t even do this for their AD credentials).  As far as I know, Facebook are one of the few web sites that actually do this (buy cracked password lists and add them to a blacklist of passwords)

2.18 - If an application allows self-registration, then it is very difficult to block against username name enumeration.

2.22 - I don't think that mentioning that pointing out that "e-mail or SMS" is "known to be weak" is useful as this can cause unnecessary discussions about what types of threats we are trying to block against.  An average attacker would have to compromise an email gateway or ISP infrastructure to intercept most emails.  Similarly, attackers intercepting SMSes aren't your average day attackers.  Instead, stating that other mechanisms are preferable I think is better.  Also, the mention of the use of a "random value" in an email I think can be better updated to state that random values used in emails should meet the same requirements as those used for session IDs (highlighted in 3.11)

2.29 - I think this should be L2 as well as L2 applications handling PII, healthcare information and other important data.

Possible addition: There was no mention that an application should not lock an account until the user verifies the forgotten password request (you can kind of link it to 2.20 but it's not a straightforward link and someone using 2.20 would likely not look at this scenario)

**Comment by kravietz** [comment]
Authentication 2.2 ("Verify that the application does not automatically fill in credentials – either as hidden fields, URL arguments, Ajax requests, or in forms, as this implies plain text, reversible...") is a bit of oversimplification of a quite complex topic.

First, it can be interpreted as a ban for password managers - if you have a website with login form, the browser filling-in credentials can be interpreted as an "application". 

Second, applications may use different kinds of credentials - for example, user login credentials as well as API keys used to access various 3rd party web services which may be stored in the database.

There's a whole NIST SP 800-63 that discusses in details what should be authenticated, where, when and how, including federated authentication schemes.

**Comment by danielcuthbert** [comment]
agree with all of Andrew's comments, one i think we need to add (and think more about is)

Possible addition: There was no mention that an application should not lock an account until the user verifies the forgotten password request (you can kind of link it to 2.20 but it's not a straightforward link and someone using 2.20 would likely not look at this scenario)
