### ISSUE TITLE
V3: Session management verification requirements comments / enhancements

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#134]
3.7 - Does not cover the scenario where a user can browse a site and add things to their shopping cart before optionally logging in.  I think it should be updated to cover this scenario.

3.12 - I think updating this to include specifying the sub-domain as well (not just the path) as using a subdomain for L2 and L3 applications would cover the scenarios where you have cross-domain attacks due to running multiple less secure applications under sub-domains and having your critical application on the parent domain.

3.16 - Although a limit is set here and a user can access an active session list in 3.17, there is no mention of alerting the user of a login from a new machine (kind of like what Gmail does).  I think that this should be added to L3 applications.

**Comment by kravietz** [comment]
3.12 - should we also mention SameSite?

**Comment by eoftedal** [comment]
Should 3.16-3.18 be L2?

**Comment by ossie-git** [comment]
Adding myself for follow-up
