### ISSUE TITLE
Clarify 2.2.9 (and also 2.2.4?)

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1340]
Based on discussion in #1060, @maizuka made a change to 2.2.4 and 2.2.9 (in #1062).

These now look like this:

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.2.4** | [MODIFIED, SPLIT TO 2.2.9] Verify that a hardware-based authenticator and an authenticator that provides verifier impersonation resistance against phishing attacks are used, such as a multi-factor cryptographic hardware, or a combination of a single-factor cryptographic hardware and an OTP device. | | | ✓ | 308 | 5.2.5 |
| **2.2.9** | [ADDED, SPLIT FROM 2.2.4] Verify that multi-factor authentication is required, that is, the application uses either a multi-factor authenticator or a combination of single-factor authenticators. | | ✓ | ✓ | 308 | 4.2.1 |

I like the simplicity of 2.2.9 but I think 2.2.4 is still a little bit clunky. The reason for that seems to be that the NIST guidance is not exactly straightforward but I think the examples we provide are a little confusing.

Also, @RafaelGreen1 suggested in #1287 that we should explicitly mention WebAuthn. 

I think we should reword and simplify 2.2.4 to be:

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.2.4** | [MODIFIED, SPLIT TO 2.2.9] Verify that a hardware-based authenticator and an authenticator that provides verifier impersonation resistance against phishing attacks **(such as WebAuthn)** are used. | | | ✓ | 308 | **4.3.1** |

@jmanico what do you think?

**Comment by tghosth** [comment]
Hi @jmanico,

I think this the reason that I suggested the following wording (which explicitly requires phishing resistance) for the requirement:

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.2.4** | [MODIFIED, SPLIT TO 2.2.9] Verify that a hardware-based authenticator and an authenticator that provides verifier impersonation resistance against phishing attacks **(such as WebAuthn)** are used. | | | ✓ | 308 | 4.3.1 |

Is this updated wording ok?

**Comment by jmanico** [comment]
Yes!On Jul 10, 2023, at 10:08 PM, Josh Grossman ***@***.***> wrote:﻿
Hi @jmanico,
I think this the reason that I suggested the following wording (which explicitly requires phishing resistance) for the requirement:



#
Description
L1
L2
L3
CWE
NIST §




2.2.4
[MODIFIED, SPLIT TO 2.2.9] Verify that a hardware-based authenticator and an authenticator that provides verifier impersonation resistance against phishing attacks (such as WebAuthn) are used.


✓
308
4.3.1



Is this updated wording ok?

**Comment by jmanico** [comment]
> Hi @jmanico,
> 
> I think this the reason that I suggested the following wording (which explicitly requires phishing resistance) for the requirement:
> 
> #	Description	L1	L2	L3	CWE	[NIST §](https://pages.nist.gov/800-63-3/sp800-63b.html)
> **2.2.4**	[MODIFIED, SPLIT TO 2.2.9] Verify that a hardware-based authenticator and an authenticator that provides verifier impersonation resistance against phishing attacks **(such as WebAuthn)** are used.			✓	308	4.3.1
> Is this updated wording ok?

BIG YES
