### ISSUE TITLE
FIPS 140-2 is superseded by FIPS 140-3

### ISSUE THREAD

**Issue by AtlasHackert** [OWASP/ASVS#1344]
In V6's references, FIPS 140-2 is mentioned. However, FIPS 140-2 is superseded by FIPS 140-3. See for example:
https://www.federalregister.gov/documents/2019/05/01/2019-08817/announcing-issuance-of-federal-information-processing-standard-fips-140-3-security-requirements-for
> FIPS 140-3 supercedes FIPS 140-2.

However, FIPS 140-3 is vastly different in set-up than FIPS 140-2, so I'm not sure there's a "quick fix", and I'm not a FIPS-expert.

**Comment by tghosth** [comment]
So I don't think we rely on FIPS, we just mention it so I have just updated how we refer to it in #1373

**Comment by elarlang** [comment]
changes merged, closing. reopen if needed.
