### ISSUE TITLE
True Pseudo-random Number Generation (PRNG)?

### ISSUE THREAD

**Issue by AtlasHackert** [OWASP/ASVS#1345]
V6.3's intro text mentions "True Pseudo-random Number Generation (PRNG)". I don't know what those are, and my favourite search engine seems to primarily find the ASVS using this term.
Is something like "Cryptographically strong Pseudo-random Number Generation (PRNG)" meant instead? Or "True Random Number Generation (TRNG)"?

**Comment by tghosth** [comment]
I agree that this should be something like [CSPRNG](https://en.wikipedia.org/wiki/Cryptographically_secure_pseudorandom_number_generator)

Could you open a PR to fix this?

**Comment by tghosth** [comment]
Closed with #1377
