### ISSUE TITLE
3.4.5 sentence grammar

### ISSUE THREAD

**Issue by AtlasHackert** [OWASP/ASVS#1347]
There's a sentence that doesn't read properly in [3.4.5](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x12-V3-Session-management.md#v34-cookie-based-session-management)

It currently goes:
> Verify that if X is published, set Y.

but it clearly should be:
> Verify that if X is published, it sets Y.

(or perhaps:)
> Verify that if X is published, Y is set.

**Comment by tghosth** [comment]
Merged :)
