### ISSUE TITLE
Out of band verifier expiration less than 10 minutes is fine too.

### ISSUE THREAD

**Issue by AtlasHackert** [OWASP/ASVS#1349]
The current wording of [2.7.2](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x11-V2-Authentication.md#v27-out-of-band-verifier) basically demands an exact 10 minutes expiration time for out of band verifiers, but sooner is fine too, and may even be better/safer and thus preferred under certain circumstances.

**Comment by tghosth** [comment]
What do you think about:

Verify that the out of band verifier expires out of band authentication requests, codes, or tokens **within** 10 minutes?

**Comment by AtlasHackert** [comment]
Sounds good to me! Shall I make a new pull request?

**Comment by elarlang** [comment]
> Sounds good to me! Shall I make a new pull request?

Yes, please.

And in general - if something requires discussion, it makes sense to open PR after getting agreement in issue.

**Comment by AtlasHackert** [comment]
PR created. And sorry, in the future, I'll only create one after reaching consensus.

**Comment by elarlang** [comment]
Merged, closed. Thank you!
