### ISSUE TITLE
V4: Access control verification requirements comments / enhancements

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#135]
4.11 - I think this should be applicable to L2 as well.  In fact, without a centralized mechanism, it is hard to comply with the rest of the requirements in this section.

4.13 - This requirement does not specify if anti-CSRF should be applied for all transactions or just sensitive ones

4.16 - From your training material, it appears that this basically means not to rely on parameters to perform authorization decisions.  If so, I think this can be reworded to more clearly be understood as the current description is somewhat cryptic.

**Comment by ossie-git** [comment]
Adding myself for follow-up
