### ISSUE TITLE
V5: Malicious input handling verification requirements comments/enhancements

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#136]
5.6 - I think that this should be L2 as well as ad-hoc input validation is probably not recommended for L2 applications

5.10 - This does not cover scenarios where users can submit column names for sorting or ORDER BYs.  I think this can be expanded to include these cases as well as SQL injection will still be possible unless these are accounted for

**Comment by kravietz** [comment]
5.10 has been compressed to a point where it's no longer formally correct. "prepared statements or query parameterization" only make sense when implementing raw SQL queries in specific programming languages and environments. They don't make any sense in context of NoSQL. OSQL is not really a query language, but a command-line client for MS SQL. 

Proposed wording for 5.10:

*Verify that database queries (e.g. SQL, HQL, ORM, NoSQL, XPath, LDAP) are protected from respective injection attacks.*

This might be expanded by the following sentence for SQL specifically:

*SQL query implementation must separate query language syntax from query parameters and enforce parameter typing (e.g. using bind variables, prepared statements, query parametrization). SQL stored procedures must never include untrusted input as part of the query e.g. in a WHERE statement.*

**Comment by ossie-git** [comment]
Adding myself for follow-up
