### ISSUE TITLE
Support "1.2 Customer testing" from MVSP

### ISSUE THREAD

**Issue by cmlh** [OWASP/ASVS#1360]
["1.2 Customer testing" of MVSP](https://github.com/vendorsec/mvsp/blame/master/packages/mvsp/mvsp.en.asciidoc#L24) is reproduced below:

`1.2 Customer testing`
`* On request, enable your customers or their delegates to test the security of your application`
`* Test on a non-production environment if it closely resembles the production environment in functionality`
`* Ensure non-production environments do not contain production data`

Should we include this in the next major release of ASVS and/or be governed upstream by [CREST OVS](https://www.crest-approved.org/membership/crest-ovs-programme/) instead?

The parent of this issue is #1151.

**Comment by danielcuthbert** [comment]
I'm not a fan if I'm honest. Firstly, what anyone does with the standard is their choice, we are not governed by anyone let alone CREST. Telling people to allow testing of their product goes over what I feel is useful

**Comment by tghosth** [comment]
@set-reminder 5 weeks @tghosth to look at this

**Comment by elarlang** [comment]
As we move with scope more towards "strictly only application", then mentioned customer testing things are out of scope.

Josh can recheck, recommendation to close it.

**Comment by tghosth** [comment]
Agree with @danielcuthbert and @elarlang that I think this item is out of scope.
