### ISSUE TITLE
Support "1.7 Incident handling" from MVSP

### ISSUE THREAD

**Issue by cmlh** [OWASP/ASVS#1361]
["1.7 Incident handling" of MVSP](https://github.com/vendorsec/mvsp/blame/master/packages/mvsp/mvsp.en.asciidoc#L43) is reproduced below (space characters are not supported by Markdown):

`1.7 Incident handling`
` * Notify your customers about a breach without undue delay, no later than 72 hours upon discovery`
` * Include the following information in the notification:`
` 1. Relevant point of contact`
` 2. Preliminary technical analysis of the breach`
` 3. Remediation plan with reasonable timelines`

Should we add support for ["1.7 Incident handling" of MVSP](https://github.com/vendorsec/mvsp/blame/master/packages/mvsp/mvsp.en.asciidoc#L43) by expanding
[0x15 V7 Error Logging v7.3 Log Protection](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x15-V7-Error-Logging.md#v73-log-protection) or creating new ASVS Requirement[s]?

The parent of this issue is #1151.

**Comment by elarlang** [comment]
ASVS goal is to verify, that you are able to detect incidents and you have enough security related information to investigate an incident. Incident handling process or procedure itself is out ot ASVS scope.

**Comment by tghosth** [comment]
I am going to reopen this as it has come up in a different context as well..

**Comment by tghosth** [comment]
@set-reminder 4 weeks @tghosth to look at this

**Comment by tghosth** [comment]
I'm going to close again for now, we seem to be focusing ASVS pretty specifically on the building an application securely whereas this is more of a process/activity related to operating an application...
