### ISSUE TITLE
Support Offsite Backups Mandated by MSVP "2.8 Backup and Disaster recovery"

### ISSUE THREAD

**Issue by cmlh** [OWASP/ASVS#1365]
["2.8 Backup and Disaster recovery" of MVSP](https://github.com/vendorsec/mvsp/blame/master/packages/mvsp/mvsp.en.asciidoc#LL104) mandates `Securely back up all data to a different location than where the application is running`

[V8.1 General Data Protection](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x16-V8-Data-Protection.md#v81-general-data-protection) does not list this as a Requirement.

Should we include [this](https://github.com/vendorsec/mvsp/blame/master/packages/mvsp/mvsp.en.asciidoc#LL104) as a new Requirement in the next release of ASVS?

The parent of this issue is #1151.

**Comment by elarlang** [comment]
> Securely back up all data to a different location than where the application is running

Related requirements and related opened issue: https://github.com/OWASP/ASVS/issues/1462

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **8.1.5** | Verify that regular backups of important data are performed and that test restoration of data is performed. | | | ✓ | 19 |
| **8.1.6** | Verify that backups are stored securely to prevent data from being stolen or corrupted. | | | ✓ | 19 |

**Comment by tghosth** [comment]
There seems to be widespread support in #1462 for reducing or removing these requirements so I don't think we are going to add more requirements around this.
