### ISSUE TITLE
Mandate CREST OVS (OWASP Verification Standard)

### ISSUE THREAD

**Issue by cmlh** [OWASP/ASVS#1366]
Mandate that only [CREST OVS (OWASP Verification Standard) service providers](https://www.crest-approved.org/membership/crest-ovs-programme/) can perform ASVS within [Guidance for Certifying Organizations](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x04-Assessment_and_Certification.md#guidance-for-certifying-organizations)

**Comment by elarlang** [comment]
I have said that before but I repeat - for every opened issue, please explain WHY you have opened them, what is your clear proposal and what kind of problem those going to solve.

For this issue - the proposal is rhetorical and just out of curiosity from my side, what could be your the explanation for the reason.

**Comment by vdbaan** [comment]
I disagree with this setting this mandate as it adds no value.
They currently require in their accreditation process that the company is a penetration testing company. Unfortunately, experience has shown that a pentester is not the same type of person than somebody that has a development background that can do these types of verifications.

**Comment by jmanico** [comment]
Crest will be just one certification body, I am politely closing this.
