### ISSUE TITLE
6.2.6 incorrectly implies that an initialization vector should only be used once per key

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1378]
The most recent language in 6.2.6 implies that only one IV should be used per key. Just to be clear we really should state that an IV should be used once per key/data-element pair, not just once per key. That's way, way too aggressive.

From https://github.com/OWASP/ASVS/blob/master/5.0/en/0x14-V6-Cryptography.md

6.2.6 | Verify that nonces, initialization vectors, and other single use numbers must not be used more than once with a given encryption key. The method of generation must be appropriate for the algorithm being used. |   | ✓ | ✓ | 326
-- | -- | -- | -- | -- | --

**Comment by tghosth** [comment]
@set-reminder 4 weeks @tghosth to look at this

**Comment by tghosth** [comment]
So @jmanico would you suggest:

> [MODIFIED] Verify that nonces, initialization vectors, and other single use numbers **are not be used for more than one encryption key/data-element pair**. The method of generation must be appropriate for the algorithm being used.

**Comment by tghosth** [comment]
Opened #1489, @jmanico please review :)
