### ISSUE TITLE
8.1.3 seems like nonsense

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1381]
8.1.3 makes absolutely no sense

From: https://github.com/OWASP/ASVS/blob/master/5.0/en/0x16-V8-Data-Protection.md

8.1.3 | [GRAMMAR] Verify the application minimizes the number of parameters in a request, such as hidden fields, Ajax variables, cookies, and header values. |   | ✓ | ✓ | 233
-- | -- | -- | -- | -- | --

**Comment by elarlang** [comment]
The sense for example - instead of keeping already submitted data on the service side, some app carries entire package in hidden fields / in some JSON object etc.

It is problematic also with some restful stuff, where entire datasets are sent back and forward when only few items are needed.

**Comment by jmanico** [comment]
> The sense for example - instead of keeping already submitted data on the service side, some app carries entire package in hidden fields / in some JSON object etc.
> 
> It is problematic also with some restful stuff, where entire datasets are sent back and forward when only few items are needed.

Server vs client-side data is a different issue covered elsewhere. I do not think the field number really matters. This, IMO, needs to be clarified or just removed. We have bigger issues to focus on.

**Comment by elarlang** [comment]
From the "data protection" category perspective this requirement is at least in wrong place. We can minimize unnecessary bandwidth from client to server with that, but it's not a data protection issue.

**Comment by jmanico** [comment]
And having many parameters vs JSON is actually SAFER since you do not need to utilize a server-side JSON parser.

I again assert this requirement is nonsense. Many apps require lots of parameters for good reason.

I do see EXTRA parameters the app does not need as a good intrusion detection point. But many parameters is just how some apps work, and that does not add a security risk in an of itself.

**Comment by jsulinski** [comment]
I agree, this requirement is too vague to be useful.

**Comment by tghosth** [comment]
Do we have any idea what the original rationale was here? Can we see from blame or previous issues?

**Comment by jsulinski** [comment]
Doesn't seem to exist in ASVS [1.0](https://github.com/OWASP/ASVS/blob/master/1.0/asvs-webapp-release-2009-en.pdf).
Exists in ASVS [2.0](https://github.com/OWASP/ASVS/blob/master/2.0/OWASPApplicationSecurityVerificationStandard3.0.pdf) as 9.7.
Exists in ASVS [3.0.1](https://github.com/OWASP/ASVS/blob/master/3.0.1/OWASP%20Application%20Security%20Verification%20Standard%203.0.1.pdf) as 9.7.
[Renumbered from 9.1.3 to 8.1.3](https://github.com/OWASP/ASVS/commit/99f80b6ffe4276b5bedc7427d4f94b415554eb14) in 2019.
[Some previous discussion](https://github.com/OWASP/ASVS/issues/934) in 2021.

**Comment by jsulinski** [comment]
It looks like ASVS 2.0 predates [git repo usage](https://github.com/OWASP/ASVS/commits/master?after=36dedf2326c034afddb5b4f65ab0570f7271c5a7+1720&branch=master&qualified_name=refs%2Fheads%2Fmaster). 

Anyone know where changes were discussed before git?
