### ISSUE TITLE
Discuss MTLS for internal services

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1382]
I think we need to get more aggressive on suggesting the use mTLS intra-service for level 3.

Please note mTLS - Mutual TLS.
Somewhere here.
https://github.com/OWASP/ASVS/blob/master/5.0/en/0x17-V9-Communications.md in 9.3

**Comment by csfreak92** [comment]
+1 on this, I totally agree we should suggest mTLS. We usually see this in security and architecture reviews that most setups do not have mTLS for intra-service communications.

**Comment by tghosth** [comment]
@csfreak92 do you fancy drafting some wording?

**Comment by csfreak92** [comment]
Hi @tghosth, I can give it a shot. Please assign to me this issue. Also, are we just suggesting this for Level 3? Wouldn't it make more sense for Level 2 requirement as well?

**Comment by tghosth** [comment]
Lets start with L3 as it is not super trivial. Assigned to you
