### ISSUE TITLE
Section 10 seems more mobile than web

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1383]
From: https://github.com/OWASP/ASVS/blob/master/5.0/en/0x18-V10-Malicious.md

All of section v10 seems way more mobile than web and should be discarded.

The first item of 10 is already submitted as a problematic issue here https://github.com/OWASP/ASVS/issues/1200

...and the rest of 10 seems very mobile-specific and should possibly be revisited.

**Comment by danielcuthbert** [comment]
I've never liked this sentence

"Does not have back doors, Easter eggs, salami attacks, rootkits, or unauthorized code that can be controlled by an attacker"
As someone who's written many a backdoor/malicious code, it's not exactly obvious and this is ambiguous at best.

**Comment by ImanSharaf** [comment]
@jmanico Could you please let us know which items are specific to mobile apps and not web apps?

**Comment by elarlang** [comment]
I think this issues does not have any precise "problem to solve" or "proposal" in it, so I close it out.

V10 needs re-build, the starting point is probably: https://github.com/OWASP/ASVS/issues/1468
