### ISSUE TITLE
5.3.5 is dead wrong and this may impact the fate of the planet

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1385]
PHP dropped its manual escaping functions years ago because - they do not work.
This requirement needs to go away!

https://www.php.net/manual/en/function.mysql-real-escape-string.php

**Comment by elarlang** [comment]
Requirement itself, PR for removing it on the way
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **5.3.5** | Verify that where parameterized or safer mechanisms are not present, context-specific output encoding is used to protect against injection attacks, such as the use of SQL escaping to protect against SQL injection. ([C3, C4](https://owasp.org/www-project-proactive-controls/#div-numbering)) | ✓ | ✓ | ✓ | 89 |
