### ISSUE TITLE
3.2.1 / 3.3.3 Does not require terminating current session or renewing session id

### ISSUE THREAD

**Issue by jsulinski** [OWASP/ASVS#1386]
[3.3.3](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x12-V3-Session-management.md#v33-session-termination)

"Verify that the application gives the option to terminate all **other** active sessions after a successful password change (including change via password reset/recovery), and that this is effective across the application, federated login (if present), and any relying parties."

When a user changes their password to regain control of an account in the case of compromise, they likely expect that all sessions will be terminated or renewed, such that an attacker would not be able to persist access to the current session. 

I think either the word "other" should be removed here or language should be added similar to the [Session Management Cheatsheet](https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#renew-the-session-id-after-any-privilege-level-change).

**Comment by elarlang** [comment]
I interpret, that if user has active session and changes password, we don't need to log out user from this current active session and that's why there is "all other".

Just in case, a bit related requirement:
| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **3.7.1** | [MODIFIED] Verify the application requires re-authentication or secondary factor verification before allowing any sensitive transactions or account modifications. | ✓ | ✓ | ✓ | 306 | |

**Comment by jsulinski** [comment]
Yes, that is the way it is currently written. However, some best practices suggest that the current session be expired and/or the session id renewed. Otherwise, there is no way to block access to attackers in the case of account compromise. 

3.7.1 refers to re-authentication **before** sensitive transactions/account modifications. 3.3.3 refers to **after**.

**Comment by elarlang** [comment]
Got it.

One option is to cover it in another requirement:
| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **3.2.1** | Verify the application generates a new session token on user authentication. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | ✓ | ✓ | ✓ | 384 | 7.1 |

Something like: for password change you need to re-authenticate (3.7.1), which means your all other sessions are terminated (3.3.3) and your current session id/token is regenerated (3.2.1).

**Comment by jsulinski** [comment]
Awesome, thanks for the advice! I'd love to get more input on best practices here and/or do some more research before drafting a PR. 

I couldn't find any references in NIST 800-63. The [Session Management Cheatsheet](https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#renew-the-session-id-after-any-privilege-level-change) says "The most common scenario where the session ID regeneration is mandatory is during the authentication process, as the privilege level of the user changes from the unauthenticated (or anonymous) state to the authenticated state though in some cases still not yet the authorized state. Common scenarios to consider include; password changes [...]"

This is technically fulfilled by either expiring all sessions or regenerating the session ID, as both will inevitably result in a new session ID. The mention of unauthenticated state also makes it sound like this passage only relates to password reset requests, rather than password changes.

I don't think I've encountered any applications in the wild that only regenerate the session ID, but some do expire all sessions. 

The Devise library does neither, but it does expire all old sessions if you're using server-side sessions (not sure if this is the case for the default cookie-based sessions). 

Anyone familiar with other best practices or implementations around this topic?

**Comment by elarlang** [comment]
My proposal could to extend 3.2.1 with "including re-authentication, and terminate previous session token".

With regenerate session token there are sometimes mistakes like - instead of create "new one, destroy previous one" is used "create new token, copy content from previous (but old one stays valid as well)"

**Comment by jmanico** [comment]
Good idea Elar, I like it.

**Comment by elarlang** [comment]
I would like to get help to wordsmith it to correct english, @jsulinski @jmanico

**Comment by elarlang** [comment]
Some more comments.

> The specific sensitive action that I'm concerned about is when a user utilizes an existing session to change their password.

With session takeover, when an attacker wants to change password for victim account, he/she need to know current valid password. Related requirement:
_V2.1.6 Verify that password change functionality requires the user's current and new password._

If victim's account credentials are leaked, then there is hope only for MFA. Related requirements:
* _V2.2.9 [ADDED, SPLIT FROM 2.2.4] Verify that multi-factor authentication is required, that is, the application uses either a multi-factor authenticator or a combination of single-factor authenticators._
* _V2.2.10 [ADDED, SPLIT FROM 2.2.3] Verify that users are notified of suspicious authentication attempts. Suspicious authentication attempts may include successful or unsuccessful authentication from an unusual location or client, partially successful authentication with only one of multiple factors, successful or unsuccessful authentication after a long period of inactivity or successful authentication after several unsuccessful attempts._

Before closing the issue, I'm going to implement my own proposal, as it fixes 2 problems.

**Comment by jsulinski** [comment]
> With session takeover, when an attacker wants to change password for victim account, he/she need to know current valid password.

Understood. My concern is not that the attacker will change the password, but that the existing session the attacker is using will remain active after the user changes their password in an attempt to recover their account. For example, in the case of MITM that has been resolved or if the user leaves their account logged in on a public computer.

However, if the user can see and terminate previous sessions through a feature in the application then this is probably fine.

**Comment by jsulinski** [comment]
> Verify the application generates a new session token on user authentication. 

> including re-authentication, and terminate previous session token

If you combine these two, you get:

"Verify the application generates a new session token on user authentication, including re-authentication, and terminate previous session token."

While this is an improvement for security, the user experience is going to be pretty poor, especially for applications that utilize separate sessions for mobile or desktop applications. 

It might also be prudent to investigate whether many popular auth libraries support this functionality, as it will be a heavy lift getting the recommendation implemented otherwise. The one I know off-hand is that Devise does not support this without modifications.

**Comment by elarlang** [comment]
"terminate previous session token" should cover here only current active session.

All other sessions are up to user choice with requirement 3.3.3:
_V3.3.3 [LEVEL L2 > L1] Verify that the application gives the option to terminate all other active sessions after a successful password change (including change via password reset/recovery), and that this is effective across the application, federated login (if present), and any relying parties._

**Comment by jsulinski** [comment]
Ah, then how about:

"Verify the application generates a new session token on user authentication, including re-authentication, and terminates the current session token."

**Comment by elarlang** [comment]
@jsulinski - my change is merged. Is here something else to clarify / improve / solve from your side or we can close this issue?
