### ISSUE TITLE
Clear separate requirement for making sure that application gets actual user IP (move V1.14.7 away from V1)

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1389]
The main goal is, that logs must contain actual user IP, not some firewall, load-balancer, proxy etc IP.

and the other part of it, that users should not be able to fake their IP addresses using X-Forwarded-For or similar request headers.

To what category to put this requirement - I'm not sure. Most important it is for logs as it is the corner-stone for every investigation.

**Comment by jsulinski** [comment]
Also important for effective IP-based rate limiting.

**Comment by jsulinski** [comment]
8.1.x might be a good place for this.

**Comment by elarlang** [comment]
8.1 is valid when we like to protect the client ip from leaking (covered it as sensitive data anyway).

I think first choice should be current 14.5, as it is delivered via HTTP request header and in general is configuration issue.

**Comment by elarlang** [comment]
But with requirement text, in valid and correct English, I need help :)

**Comment by jsulinski** [comment]
Good call, I agree that 14.5 is a solid place for this. Perhaps:

```
14.5.6 "Verify that headers containing user IP addresses, such as X-Forwarded-For and X-Real-IP, include the true end-user IP" 
```
Could also consider adding rationale: "to prevent spoofing in logs and rate limits."

**Comment by elarlang** [comment]
Final pieces:
* Level - proposal for level 1, 2, 3 - IP is the main corner-stone for investigations, if you don't have this data, there is nothing to investigate.
* CWE - [CWE-348](https://cwe.mitre.org/data/definitions/348.html): Use of Less Trusted Source

**Comment by elarlang** [comment]
Analyzing this proposal text and maybe it needs still some finetuning - what if headers contain the faked IP, but application just ignores them? The point is - application should use only trusted one.

I throw some pieces here / potential points to cover (at the moment overlapped in wording):
* Verify that application uses only user's real IP
* accross all applicaiton components (load balanceres, firewalls, apis, application, etc)
* which is not spoofed by headers like X-Forwarded-For or X-Real-IP
* to provide data integrity related to user IP like to prevent spoofing in logs, rate limits

**Comment by jsulinski** [comment]
> what if headers contain the faked IP, but application just ignores them? The point is - application should use only trusted one.
> 
> I throw some pieces here / potential points to cover (at the moment overlapped in wording):
> 
>     * Verify that application uses only user's real IP
> 
>     * accross all applicaiton components (load balanceres, firewalls, apis, application, etc)

The last point would be difficult to achieve on some cloud vendors/devices, for example: Google Cloud Load Balancers [1]. 

Aside from this point, the wording could be:

"Verify that the application is able to discern and utilizes the user's true, non-spoofed IP address from a header, for example X-Forwarded-For or X-Real-IP, and that rate limiting and logging use this true IP."

[1] https://cloud.google.com/load-balancing/docs/https#x-forwarded-for_header

**Comment by elarlang** [comment]
Thank you for brainstorming. Part of making requirement texts good, is to "attacking" them.

_Verify that the application is able to discern and utilizes the user's true, non-spoofed IP address from a header, for example X-Forwarded-For or X-Real-IP, and that rate limiting and logging use this true IP._

IP can come also from environment variable like REMOTE_ADDR, it's not always read from header.

Is this the material we can improve?
_Verify that application uses only user's real IP which is not spoofed by headers like X-Forwarded-For or X-Real-IP to provide data integrity related to user IP like to prevent spoofing in logs, rate limits_

**Comment by jmanico** [comment]
Well said. And IP addresses are not just sensitive data, they are also 
GDPR/Privacy protected data.

**Comment by jsulinski** [comment]
Here's another draft:

Verify that the application is able to discern and utilizes the user's true IP address to provide data integrity and that rate limiting and logging use this true IP.

**Comment by tghosth** [comment]
> Verify that the application is able to discern and utilizes the user's true IP address to provide data integrity and that rate limiting and logging use this true IP.

@elarlang what do you think about this suggestion from @jsulinski?

**Comment by elarlang** [comment]
This issue is in a way related to https://github.com/OWASP/ASVS/issues/1697

Need to think should we merge them or not. Those are like 2 sides of the same problem.

**Comment by jsulinski** [comment]
These two issues can likely be merged as this one is part of #1697 with a bit more detail. I'm not sure that detail is necessary, so could probably drop this one and accept #1697 (after adding X-Real-IP).

**Comment by elarlang** [comment]
It makes sense to keep them separately. One (#1697) is for avoiding end-users to manipulate or override expected headers and other is just being sure one of the most important piece of information for investigations - IP - is the correct one, not some waf, or proxy IP. In some cases they overlap, but at the moment it seems good for me to keep them separately.

**Comment by jsulinski** [comment]
Good point and agreed.

**Comment by elarlang** [comment]
From @jsulinski 

> Verify that the application is able to discern and utilizes the user's true IP address to provide data integrity and that rate limiting and logging use this true IP.

Previously I left it on hold as there was something to improve in my opinion - "now it is fixed" as I don't remember, what it was :) So I think we can put this requirement in and if needed, improve it later.

**Comment by elarlang** [comment]
IP spoofing vector is / will be covered now via #1697, so this requirement focus should be to avoid misconfiguration on the application side. Which rises questions like:
* category?
* cwe?
* level?

**Comment by tghosth** [comment]
> Verify that the application is able to discern and utilizes the user's true IP address to provide data integrity and that rate limiting and logging use this true IP.

What do you mean by "data integrity" in this case @jsulinski? Do you think you could be more specific?

**Comment by jsulinski** [comment]
> What do you mean by "data integrity" in this case @jsulinski? Do you think you could be more specific?

This seems superfluous and was from previous copy that I was editing. 

Perhaps:

Verify that the application is able to discern and utilizes the user's true IP address to provide for sensitive functions, including rate limiting, logging, and/or as an aspect of authentication. 

CWE: 348
Category: 14.4 or 10.3
Level: 2

**Comment by jsulinski** [comment]
I added the part about authentication because IP is sometimes used in the decision to require additional authentication factors (along with other information).

**Comment by elarlang** [comment]
> I added the part about authentication because IP is sometimes used in the decision to require additional authentication factors (along with other information) but this can be removed if the requirement is becoming too unclear or unfocused.

Yes, I would skip this authentication part - if authentication is limited by IP, probably they use actual IP. But geolocation or whatever can be topic.

Category - actually I don't know where it fits. In big picture V14 configuration seems to be correct place.
* 14.4 are response headers for browser, so this does not seems to be correct. 14.5 is better, but this part is covered via #1697 .
* 10.3 - V10 in general wait rebuild and proper cleanup.

**Comment by tghosth** [comment]
@elarlang what do you think about chapter 11.2 ("Anti-automation" within "Business Logic") as this new requirement mostly seems to be related to this.

**Comment by elarlang** [comment]
V11.2 uses it. So do entire logging V7 and whatever uses IP as input data.

By v4.0.3 logic suitable category is V1.14, but it requires cleanup itself. As temporary solution do just get the requirement in, we can use this maybe.

**Comment by tghosth** [comment]
I disagree that this is server configuration because it is the application itself that needs a clear way of doing this. 

I think I would still support being in the business logic section as it is kinda a business logic thing

**Comment by elarlang** [comment]
Ack, I agree that it is not (only) server configuration question.

**Comment by elarlang** [comment]
Reopen for moving the requirement away from V1.14

**Comment by tghosth** [comment]
I think I am less opinionated about this right now, I think it could be considered to be V7 logging or V11 business logic so maybe V14 is a good compromise. Any further thoughts @elarlang ?

**Comment by tghosth** [comment]
Hmm, not sure about that, this doesn't feel that simple as it probably involves various components including program code, might also involve configuration of front end devices such as waf or proxy or cloud component or something. That's why I like v14 as more general than just code or v7 as less code connected

**Comment by elarlang** [comment]
See my previous comment https://github.com/OWASP/ASVS/issues/1389#issuecomment-1267983986 and your own comment here https://github.com/OWASP/ASVS/issues/1389#issuecomment-1739288017.

In case there are WAF or whatever component in place to "mess" with the IP address, it's the application's decision to use the correct one - that is why the requirement exists.

For "do not mess with IP address" we have:
> V13.6.4 Verify that any HTTP headers used by the application and defined by intermediary devices like load balancers or proxies, such as X-Real-IP and X-Forwarded-*, cannot be overridden by the end-user.

(for other topic discussion, V13.6.4 may suit to configuratino better)

**Comment by tghosth** [comment]
OK having discussed with Elar, ultimately the buck stops with the program code to be able to correctly interpret this so I would support this going into V10.

@elarlang please PR it in
