### ISSUE TITLE
V9: Data protection verification requirements comments / enhancements

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#139]
9.1 - According to your training slide, all modern browser do not honor "autocomplete" and this requirement should be skipped as it requires replacing the submit button with a Javascript action.  So should this be removed altogether or just modified so that it is only applicable for L3?

9.2 - Considering the rest of the requirements deal with sensitive data, why isn't the identification of sensitive data an L1 and L2 requirement as well?  I would suggest splitting it into its own requirement (the identification of sensitive information) and having an explicit policy on how you will deal with it as an L2 requirement as L2 also deals with PII, etc.

9.6 - I think this should be an L2 requirement as well single you have regulated data at this level as well

9.8 - 4.14 specifies that you have an L2/L3 control to control scraping.  So why is this an L3 requirement and not an L2 requirement?

**Comment by ossie-git** [comment]
Adding myself for follow-up
