### ISSUE TITLE
2.1.8 password strength meter requirement

### ISSUE THREAD

**Issue by wet-certitude** [OWASP/ASVS#1398]
I am currently checking the ASVS compliance of an online service. This service uses a third-party authentication provider. This authentication provider does not provide a password strength meter. 

Since this is required by stipulation 2.1.8, there is a clear disagreement with ASVS.

I believe a password strength meter is a great idea and should be recommended for implementations, though I think it excludes a ton of applications from compliance with even Level 1 (AFAIK Google, Facebook).

What is the reasoning for making this a hard requirement?

**Comment by elarlang** [comment]
Current requirement:
| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.1.8** | Verify that a password strength meter is provided to help users set a stronger password. | ✓ | ✓ | ✓ | 521 | 5.1.1.2 |

We have had this discussion previously:
* https://github.com/OWASP/ASVS/issues/420
* https://github.com/OWASP/ASVS/issues/622
* https://github.com/OWASP/ASVS/issues/683

**Comment by elarlang** [comment]
Basically, the requirement (still) exist in the ASVS because of @jmanico comment here: https://github.com/OWASP/ASVS/issues/420#issuecomment-463732929

3.5 years passed, we are moving to MFA direction - Jim, do still have opinion that this requirement is must have and hard requirement or we can kick it off?

**Comment by jmanico** [comment]
I think a password meter is super important, even if IdP's do not support them. Maybe this requirement will help them do so....

**Comment by elarlang** [comment]
As we have had this discussion many times, arguments are the same. I can call it as duplicate and close.

**Comment by wet-certitude** [comment]
So you are saying that these services are currently not ASVS L1 compliant:

* Google
* Facebook
* Wikipedia
* LinkedIn

Any service that does not comply with ASVS L1 is therefore in good company.

Yes, of course it is useful, and yes, every service _should_ have it, though we also have to ask: Is this requirement important enough that not complying means non-compliance with ASVS? AS**V**S is, after all, a _verification_ and not a _recommendation_ standard.

**Comment by elarlang** [comment]
As I'm one of those who would like to see the requirement walk away, I actually reopen the issue for collection wider feedback.

**Comment by tghosth** [comment]
We are trying to streamline as much as possible. NIST has this as a "SHOULD" rather than a "MUST". I agree this is a nice to have but I think that having it in as a "pass/fail" requirement seems incorrect. I am in favour of removing.

@danielcuthbert what do you think?

**Comment by danielcuthbert** [comment]
Not overly keen to have it as a pass/fail and do accept that having a meter is good but not an 'if you don't, it's a fail' approach.

**Comment by elarlang** [comment]
I conclude it a "removal" and make PR.

For the record - password meter is nice to have feature, but not a "you have an security hole if you don't have it". This is also what NIST says, you SHOULD have it, not MUST have it.

Password meter in general is usability feedback which is most likely is not duplicated on the trusted service layer side. The point is - if an application want to be sure users are using strong passwords (to take down application owner risks, not only enduser risks), then those rules must be on the trusted service layer side, and those are covered with other requirements, like current (2.1.1, 2.1.4, 2.1.7).

Also, important one, we are moving towards MFA direction.
