### ISSUE TITLE
2.1.3 password truncation

### ISSUE THREAD

**Issue by wet-certitude** [OWASP/ASVS#1399]
Should password truncation (e.g. after 100 characters) be a hard fail? I know that some (well-established) online services behave like this.

**Comment by elarlang** [comment]
Current requirement:
| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.1.3** | [MODIFIED] Verify that passwords are not truncated. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | ✓ | ✓ | ✓ | 521 | 5.1.1.2 |

100 characters password is more than enough, but principle to automatically truncate user's password without letting user know, it's problem. Application should not accept this password or use pre-hash for that.

See also: https://github.com/OWASP/ASVS/issues/1029

**Comment by elarlang** [comment]
Do you have any further questions and/or proposals or we can close this?

**Comment by wet-certitude** [comment]
Would a warning that a password is about to be truncated be acceptable (for the case that truncation happens at >= 70 chars or so)?

I want to make sure exactly what ASVS's position is before raising the issue with the IdP. If truncation is a no-go and a hard fail according to _even_ ASVS L1, this should be considered a major security issue.

**Comment by elarlang** [comment]
**As a pentester** I have a question, what is this true-or-false behavior? I write and describe risks and recommendations for my/our clients and this is not "you passed" vs "not passed" the test.

Can you prove with practical attack, that there is practical difference is the password truncated at 70 or at 100 or not truncated at all? From attacking perspective I would say, it is not party-stopper, but auto-truncating user-input without letting user know about it is not technically correct way to do it.

For that in pentest reports should be risk level - and if the finding is without proof how you can misuse it as an attack, the level is "info" (means "there is space for improvement")

**As a ASVS co-lead** - if we read how the requirement is written it says "No password truncation allowed".

**Comment by elarlang** [comment]
The world is not that boolean. Context and common sense matters.

If `Content-Security-Policy` header is missing and there is no other problem in the tested application, what is the risk? As this missing header do not provide any extra attacking scenario, you skip it? It's a second layer of defense.

> If truncation is a no-go and a hard fail according to even ASVS L1, this should be considered a major security issue.

Truncation is an issue. Is it major issue or minor issue, you should analyze with risk level. All is said in https://github.com/OWASP/ASVS/issues/1399#issuecomment-1280557323 and https://github.com/OWASP/ASVS/issues/1399#issuecomment-1289051865.
