### ISSUE TITLE
Appendix B - Page 46 – OWASP Testing Guide Link Should be Consistent

### ISSUE THREAD

**Issue by defern** [OWASP/ASVS#14]
Appendix B - Page 46 – OWASP Testing Guide Link Should be Consistent

May consider changing the URL from http://www.owasp.org/index.php/Testing_Guide to https://www.owasp.org/index.php/OWASP_Testing_Project to be more direct

It would also then match the same link on page 44

**Comment by vanderaj** [comment]
Fixed thank you :)
