### ISSUE TITLE
14.1.5 config tampering detection

### ISSUE THREAD

**Issue by wet-certitude** [OWASP/ASVS#1400]
14.1.5 stipulates that admins should be able to verify the integrity of security-relevant configurations to detect tampering.

I have no clue what that would look like in practice. Could that be a script that SSHs into all machines and verifies the hashes of config files? Assuming the machine was compromised this would be of limited use since an attacker could use a rootkit to make the hash appear to be valid (e.g. replace the sha256sum binary).

Can you give guidance what that would look like in practice? Where would the references (e.g. reference hashes) need to be stored - on the same machine does not make sense? When tampering is considered, shouldn't much rather binaries/scripts instead of configs be validated?

**Comment by elarlang** [comment]
Current requirement:
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **14.1.5** | Verify that authorized administrators can verify the integrity of all security-relevant configurations to detect tampering. | | | ✓ | |

**Comment by tghosth** [comment]
Does the info in #1271 provide any clarification for you? I agree that the wording could potentially be better

**Comment by wet-certitude** [comment]
I'll continue discussion in #1271 as I think it's pretty similar.
