### ISSUE TITLE
13.1.5 - is correct HTTP status code is worth separate requirement or can be merged to 13.2.5?

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1401]
Related requirements:
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **13.1.5** | Verify that requests containing unexpected or missing content types are rejected with appropriate headers (HTTP response status 406 Unacceptable or 415 Unsupported Media Type). | | ✓ | ✓ | 434 |
| **13.2.5** | Verify that REST services explicitly check the incoming Content-Type to be the expected one, such as application/xml or application/json. | | ✓ | ✓ | 436 |

CWE values are questionable for both:
* [CWE-434](https://cwe.mitre.org/data/definitions/434.html) - Unrestricted Upload of File with Dangerous Type
  * Description: _The software allows the attacker to upload or transfer files of dangerous types that can be automatically processed within the product's environment._
* [CWE-436](https://cwe.mitre.org/data/definitions/436.html) - CWE-436: Interpretation Conflict
  * Description: _Product A handles inputs or steps differently than Product B, which causes A to perform incorrect actions based on its perception of B's state._

Is 13.1.5 solving some actual security issue or it is more "handle things correctly"? If yes, is it worth separate requirement or can be part of 13.2.5?

**Comment by tghosth** [comment]
I suggest deleting 13.1.5. I don't see any major security benefit which it brings nor has that ever been clarified in an issue or from the history of the requirement.

@elarlang @jmanico @danielcuthbert do you agree?

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **13.1.5** | Verify that requests containing unexpected or missing content types are rejected with appropriate headers (HTTP response status 406 Unacceptable or 415 Unsupported Media Type). | | ✓ | ✓ | 434 |

**Comment by jmanico** [comment]
I suggest deleting 13.1.5

**Comment by elarlang** [comment]
As I don't like labels just "DELETED" for version mapping, then in this case (or like with deleted 2.1.8, 2.1.12 and some more) - what is the reason? "NO IMPACT"? "NOT ENOUGH IMPACT"?

**Comment by tghosth** [comment]
Opened a PR
REMINDER NO LONGER RELEVANT

**Comment by tghosth** [comment]
I wrote DELETED, INSUFFICIENT IMPACT. Is that not ok?
