### ISSUE TITLE
6.3.1 and 6.3.2 refer to "CSPRNG's" differently

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1403]
These two requirements should be more consisitent in how they talk about CSPRNG's

6.3.1 | Verify that all random numbers, random file names, random GUIDs, and random strings are generated using the cryptographic module's approved cryptographically secure random number generator when these random values are intended to be not guessable by an attacker. |   | ✓ | ✓ | 338
-- | -- | -- | -- | -- | --
6.3.2 | Verify that random GUIDs are created using the GUID v4 algorithm, and a Cryptographically-secure Pseudo-random Number Generator (CSPRNG). GUIDs created using other pseudo-random number generators may be predictable.

**Comment by elarlang** [comment]
@tghosth - can you sync the terms? I think we can use label `GRAMMAR` here.

**Comment by tghosth** [comment]
Weird, I was sure this came up elsewhere, I will take a look

@set-reminder 4 weeks @tghosth to look at this

**Comment by tghosth** [comment]
Should also consider whether there is duplication between these requirements.
