### ISSUE TITLE
Incorrect CWE allocation

### ISSUE THREAD

**Issue by vdbaan** [OWASP/ASVS#1409]
Within [chapter 8](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x16-V8-Data-Protection.md)

You have the two following requirements:

8.3.3 | L1 | Data Protection | Sensitive Private Data | Verify that users are provided clear language regarding collection and use of supplied personal information and that users have provided opt-in consent for the use of that data before it is used in any way.
-- | -- | -- | -- | --
8.3.8 | L2,L3 | Data Protection | Sensitive Private Data | Verify that sensitive personal information is subject to data retention classification, such that old or out of date data is deleted automatically, on a schedule, or as the situation requires.

This is all mapped to CWE 285 which has the following text and Title.

CWE-285: Improper Authorization: The software does not perform or incorrectly performs an authorization check when an actor attempts to access a resource or perform an action.

The CWE does not match the language regarding data protection, content, or retention.

**Comment by tghosth** [comment]
@elarlang is there no CWE that would match in this case?

**Comment by tghosth** [comment]
@vdbaan do you think [CWE-359 - "Exposure of Private Personal Information to an Unauthorized Actor"](https://cwe.mitre.org/data/definitions/359.html) is close enough?

**Comment by elarlang** [comment]
CWE-359 is more like pointing to authorization problem, but this is not (directly) the case here.

**Comment by vdbaan** [comment]
The CWE does not relate to the requirements.
The requirements to me are about customer control over their own data (think GDPR).
The CWE reads to me about exposure of any users sensitive data, slightly different angle.
