### ISSUE TITLE
V11: HTTP security configuration verification requirements comments/enhancements

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#141]
The section start says that a control objective is that "the application server is suitably hardened from a default configuration" yet none of the requirements address application server hardening (removing default content, disabling demo applications, patch updates, etc.).  They are all related to HTTP header security.  The actual server hardening is in V19

**Comment by ossie-git** [comment]
Adding myself for follow-up

**Comment by danielcuthbert** [comment]
Agreed and reworded. Added "The application server contains HTTP response headers that help provide a layer of security to help users mitigate certain types of attacks and vulnerabilities."
