### ISSUE TITLE
V16: Files and resources verification requirements comments / enhancements

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#142]
I found no mention of DoS type attacks (uploading very big files or a lot of very small files).  The only mention of this was in 18.4 which is specific to Web services.  I think this should be added.

16.5 CORS was mentioned here but just accepting untrusted data was mentioned.  I don’t think that there was anywhere in the standard where it mentioned securing CORS only to trusted domains.

16.7 - I think this can be expanded to also allow access to certain extensions so backup files, temporary files, etc are not accessible.  Or this can be added to V19

16.8 - I think this can be expanded to cover scenarios where malicious HTML can be uploaded to then used to execute XSS attacks as in this case, the browser’s client would execute it (not the application)

**Comment by ossie-git** [comment]
Adding myself for follow-up

**Comment by danielcuthbert** [comment]
Worry a little about the interpretation of these, they are good additions but a bit too open for my liking. We should also add here about 3rd-party CSS and others, especially in light of the recent supply-chain attacks.

**Comment by tghosth** [comment]
Opened #377 to address these points, @danielcuthbert please can you see if you think this covers them all off.
