### ISSUE TITLE
2.7.1 and 2.2.2 seem to be inconsistent (or duplicates)

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1420]
2.7.1 | Verify that clear text out of band (NIST "restricted") authenticators, such as SMS or PSTN, are not offered by default, and stronger alternatives such as push notifications are offered first.
-- | --

2.2.2 | [MODIFIED] Verify that weak authenticators (such as out-of-band authentication using VOIP or email) are not used as authentication methods. Verify that restricted authenticators (those using PSTN to deliver OTPs via phone or SMS) are offered only when alternate stronger methods are also offered and when the service provides information on their security risks to users.
-- | --

**Comment by tghosth** [comment]
There is some NIST subtlety here that needs to be addressed. I will take this.

@set-reminder 5 weeks to look at this

**Comment by belalena** [comment]
Can I add a question here about level. Both requirements are L1. Does it mean it concerns Single factor authentication as well as Second factor? Could you please correct me if I'm wrong with following statements:

1. If the app requires only one factor and it is password - both requirements are met?
2. If the app allows login with some TOTP from Authentication App (such as google auth app OR Microsoft auth app) - the requirements are met?
3. If the app allows login with SMS only - the requirement is NOT met
4. If the app requires MFA , first factor is password, second is auth app TOTP  OR SMS - the requirement is met
5. If the app requires MFA , first factor is password, second is only SMS  - the requirement is NOT met

**Comment by tghosth** [comment]
Yes I think this needs to be revisited once #1394 is finalized.

**Comment by tghosth** [comment]
I think that #1394 clarified this so I am going to close for now
