### ISSUE TITLE
2.8.7 needs the grammar police to get involved

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1421]
Grammar problem?

2.8.7 | [LEVEL L2 > L3] Verify that biometric authenticators are limited to use only as secondary factors in conjunction with **either** something you have **and** something you know.
-- | --

**Comment by csfreak92** [comment]
Sounds like it should be `Verify that biometric authenticators are limited to` **be used only as a secondary factor** `in conjunction with either something you have and something you know.` Not sure if `secondary factor` should be plural. I'll leave it to the grammar police. :)

**Comment by tghosth** [comment]
@set-reminder 4 weeks @tghosth to look at this

**Comment by tghosth** [comment]
REMINDER NO LONGER RELEVANT

@jmanico please review #1490

**Comment by jmanico** [comment]
May I suggest this fix:Verify that biometric authenticators are only used as secondary factors together with either something you have or something you knowThe last or is the change--Jim ***@***.*** Coding Education+1 (808) 652-3805On Jan 1, 2023, at 1:20 PM, Josh Grossman ***@***.***> wrote:﻿
REMINDER NO LONGER RELEVANT
@jmanico please review #1490
