### ISSUE TITLE
discussion: configuration (for example integration) in user interface

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1437]
Situation: often (based on my experience as pentester) there is functionality in user interface for administrators for changing some API url, secrets, configurations etc.

Problem to solve: if an attacker gains access as administrator (use your imagination how, one XSS or session takeover is enough), then it should not affect / escalate to change application configuration.

A bit related to current requirement 2.10.4 (see below), but not directly - 2.10.4 focus is credentials only, but users should not be able to change to source addresses as well - this is also the way how to read credentials, because if you can change some integration source address to your controlled address, you can read the password sent by the application.

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.10.4** | Verify passwords, integrations with databases and third-party systems, seeds and internal secrets, and API keys are managed securely and not included in the source code or stored within source code repositories. Such storage SHOULD resist offline attacks. The use of a secure software key store (L1), hardware TPM, or an HSM (L3) is recommended for password storage. | | ✓ | ✓ | 798 | |

**Comment by Sjord** [comment]
Perhaps 3.7.1 is relevant for this?

> Verify the application requires re-authentication or secondary factor verification before allowing any sensitive transactions or account modifications.

**Comment by elarlang** [comment]
I think it's not - it could require re-authentication for every change admins make. Additionally, then it could require every time admins want to see sensitive configuration/integration details.

**Comment by Sjord** [comment]
What solution do you propose? That important configuration can not be modified at all from within the application?

**Comment by elarlang** [comment]
Yes.

Examples: database connection configuration, authentication service connection configuration.

**Comment by tghosth** [comment]
I am a little nervous that this would be hard to enforce. Do we have a better definition of "important configuration" that we could use in a theoretical new requirement @elarlang ?

**Comment by elarlang** [comment]
> I am a little nervous that this would be hard to enforce. Do we have a better definition of "important configuration" that we could use in a theoretical new requirement @elarlang ?

Maybe you can provide some example, why? Some blog RSS feed import? It's usually "SSRF with cronjob" :)

If we take requirement 2.10.4

> Verify passwords, integrations with databases and third-party systems, seeds and internal secrets, and API keys are managed securely and not included in the source code or stored within source code repositories. 

We can interpret that is should not be ok to show database or user-authentication integration (openid, oauth, whatever sso solution service) password as plain-text to the output (target for XSS, cache, session takeover, account takeover). It should be stored safe against offline attacks but most likely is often stored as somewhere as plain-text.

Integration source address (e. g. sso host, database server) should not be changed to whatever value, as an impact for previously mentioned vectors, it may cause denial of service attack or give man-in-the-middle or proxied-communication possibility.

Current 12.6.1 says:
> Verify that the web or application server is configured with an allow list of resources or systems to which the server can send requests or load data/files from.

It also means, to allow application communicate to some new address, it may require some other configuration changes.

**Comment by tghosth** [comment]
I get your overall concept but I am struggling to come up with a solid requirement/s.

I think 2.10.4 is saying something specific and is valid related to secret management and the ability to keep them confidential and rotate them.

> We can interpret that is should not be ok to show database or user-authentication integration (openid, oauth, whatever sso solution service) password as plain-text to the output (target for XSS, cache, session takeover, account takeover). It should be stored safe against offline attacks but most likely is often stored as somewhere as plain-text.

So this is a problem I have seen in multiple places and I would interpret this as a requirement like

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **8.x.x** | Verify that if the application's provides configuration screens to set sensitive data in the application such as integration secrets or passwords, these configuration items are "write-only" to prevent an attacker with access to the configuration page from overwriting them. | | ✓ | ✓ | |

> Integration source address (e. g. sso host, database server) should not be changed to whatever value, as an impact for previously mentioned vectors, it may cause denial of service attack or give man-in-the-middle or proxied-communication possibility.

I can understand the concept here but I just don't know how best to define what should not be configurable in this context...

**Comment by tghosth** [comment]
Ping @elarlang :0

**Comment by elarlang** [comment]
If it is possible to override the configuration from the web interface, it means you can just kill the service (if ruining some connection parameters).

**Comment by tghosth** [comment]
Again, I understand the concept of why this is dangerous and have seen this in the wild, I am just trying to come up with a more solid requirement. Is it as simple as saying something like:

> Verify that there are extra controls for modifying passwords and connection parameters for integrations with databases and third-party systems if the application allows this within its administration interface.

What do you think?

**Comment by elarlang** [comment]
What would be those "extra controls"? Proposed requirement is better solution than to not have the requirement at all. But...

I think with that direction we fall to requirement like "make sure that user has permission to see and modify connection parameters", like we had here: https://github.com/OWASP/ASVS/issues/1524#issuecomment-1576895079

My proposed "extra control" is to not have them in the user-interface to take down escalation for XSS, session takeover or account takeover.

Problematic part (something which I/we need to define) is that "what is allowed to change via admin web interface and what is not".

**Comment by tghosth** [comment]
I don't think we can outlaw them all together.

Extra controls make me think about step-up authentication/multi-person review or something and then that makes me think that maybe we need something like requirement [4.3.3](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x12-V4-Access-Control.md#v43-other-access-control-considerations) for sensitive/dangerous operations like these.

> [GRAMMAR] Verify the application has additional authorization (such as step up or adaptive authentication) for lower value systems, or alternatively segregation of duties for high value applications to enforce anti-fraud controls as per the risk of application and past fraud.

What do you think?

**Comment by elarlang** [comment]
In general it sounds reasonable to take town session hijacking vector, but I'm not really sure that multi-person review is suitable solution for setting credentials via web ui.

**Comment by tghosth** [comment]
>  but I'm not really sure that multi-person review is suitable solution for setting credentials via web ui.

**Comment by elarlang** [comment]
Connection string is just part of credentials, think about

`Fred has tried to change database connection password to Y, do you approve?`

**Comment by tghosth** [comment]
I don't 100% agree, especially as the connection URL specifically would also be a sensitive change but that isn't important right now, the important thing is do you consider the multi-person review and other mitigating controls like that to be the correct direction here?

**Comment by elarlang** [comment]
Multiuser preview can be acceptable solution, but not preferred one.

**Comment by elarlang** [comment]
Yes, maybe just the "if condition" in front?

Does not feel correct, but the idea is:

> Verify that if the application allows modifying passwords or connection parameters for integrations with databases and third-party systems within its administration interface there are extra controls (such as re-authentication or multi-user approval).

**Comment by tghosth** [comment]
How about:

> Verify that, if the application allows changing highly sensitive configurations around passwords or connection parameters for integrations with databases and third-party systems, they are protected by extra controls (such as re-authentication or multi-user approval).

**Comment by elarlang** [comment]
Looks good :) Let's wait some feedback

**Comment by elarlang** [comment]
Did we actually reach to 4.3.3 now? 4.3.3 is more abstract and actually I can not translate it to action myself.

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **4.3.3** | [GRAMMAR] Verify the application has additional authorization (such as step up or adaptive authentication) for lower value systems, or alternatively segregation of duties for high value applications to enforce anti-fraud controls as per the risk of application and past fraud. | | ✓ | ✓ | 732 |
| proposed | Verify that, if the application allows changing highly sensitive configurations around passwords or connection parameters for integrations with databases and third-party systems, they are protected by extra controls (such as re-authentication or multi-user approval). | ? | ? | ? | ? |

**Comment by tghosth** [comment]
Basically yes. In #1045 and #1496 it was made clear that 4.3.3 needs to be fixed so I think we need to make it include your requirements as well as discussed in this issue.

The question is, do you consider this to be an access control issue or a business logic issue? i.e. which chapter should it go in @elarlang ?

**Comment by tghosth** [comment]
Ok I want to replace 4.3.3 with this requirement and I want to create a new anti-fraud requirement in the business logic section which is worded slightly differently.

I would suggest the following changes:


| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **4.3.3** | [MODIFIED, SPLIT TO 11.1.10] Verify that, if the application allows changing highly sensitive configurations around passwords or connection parameters for integrations with databases and third-party systems, they are protected by extra controls (such as re-authentication or multi-user approval). | | ✓ | ✓ | 732 |
| **11.1.10** | [ADDED, SPLIT FROM 4.3.3] Verify the application has additional authorization requirements (such as step up or adaptive authentication), segregation of duties to enforce anti-fraud controls. | | ✓ | ✓ | 732 |

What do you think @elarlang

**Comment by elarlang** [comment]
* I think we should have agreed guide-line how to use "such as" - using commas or brackets
* anti-fraud - is it clear enough term or is it too abstract and requires some examples to be listed?

**Comment by tghosth** [comment]
> I think we should have agreed guide-line how to use "such as" - using commas or brackets

Not sure if we need solid guidelines but I agree that it is interesting in this case. In the first requirement I think the brackets are extraneous and unnecessary. In the second requirement I think they are useful because they create a subsection in the middle of an existing list.

> anti-fraud - is it clear enough term or is it too abstract and requires some examples to be listed?

~~I think it is relatively clear but it does open some additional questions.~~ Actually I think that whole second requirement is not great and opens other questions about anti-fraud so let's discuss.

Current suggestion for reference:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **4.3.3** | [MODIFIED, SPLIT TO 11.1.10] Verify that, if the application allows changing highly sensitive configurations around passwords or connection parameters for integrations with databases and third-party systems, they are protected by extra controls such as re-authentication or multi-user approval. | | ✓ | ✓ | 732 |
| **11.1.10** | [ADDED, SPLIT FROM 4.3.3] Verify that the application uses additional authentication requirements (such as step up or adaptive authentication) or segregation of duties to enforce anti-fraud controls. | | ✓ | ✓ | 732 |

**Comment by tghosth** [comment]
Need to check what is going on with 3.7.1

**Comment by tghosth** [comment]
anti-fraud seems too abstract and also not clear it is in scope for ASVS

Potentially need to check if business logic chapter considers workflows or other functionality restrictions to enforce business logic controls, 

Aside from this, we need to find a way to effectively merge the new requirement with 4.3.3 to cover the problem we are trying to solve, i.e. some additional authentication when performing highly sensitive operations.

**Comment by tghosth** [comment]
Ok, 3.7.1 was handled here: https://github.com/OWASP/ASVS/issues/1523

To be honest I think we can just replace 4.3.3 with this requirement 

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **4.3.3** | [MODIFIED] Verify that, if the application allows changing highly sensitive configurations around passwords or connection parameters for integrations with databases and third-party systems, they are protected by extra controls (such as re-authentication or multi-user approval). | | ✓ | ✓ | 732 |

I think that anti-fraud is just too nebulous and not in scope

@elarlang what do you think about this modification?

**Comment by tghosth** [comment]
Actually, I just opened a PR because you seemed to agree with this change above
#1846

**Comment by jmanico** [comment]
4.3.3 [MODIFIED] Verify that, if the application allows changing highly sensitive configurations around passwords or connection parameters for integrations with databases and third-party systems, they are protected by extra controls such as re-authentication or multi-user approval. ✓ ✓ 732

This is a rather complex requirement that I think can be removed.

**Comment by elarlang** [comment]
> This is a rather complex requirement that I think can be removed.

**Comment by tghosth** [comment]
I agree that is is complicated but we did have a long discussion about it and the requirement is solving a real problem. Open to suggestions on simplification

**Comment by jmanico** [comment]
After reading the thread carefully, I think 4.3.3 covers this issue well and I am closing this issue,
