### ISSUE TITLE
3.5.3 and 3.5.5 are duplicates?

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1439]
## V3.5 Token-based Session Management

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **3.5.3** | [MODIFIED, LEVEL L2 > L1] Verify that stateless session tokens make use of digital signatures to protect against tampering. | ✓ | ✓ | ✓ | 345 | |
| **3.5.5** | [ADDED] Verify that the signature of a stateless token is being checked before processing it further. | ✓ | ✓ | ✓ | 347 | |

What is the actual difference between those requirements? If there are no meaningful differences, one of them should be removed.

* CWE-345: Insufficient Verification of Data Authenticity
* CWE-347: Improper Verification of Cryptographic Signature

**Comment by tghosth** [comment]
I suggest:

> Verify that stateless session tokens make use of digital signatures to protect against tampering and this is checked before processing it further.

**Comment by tghosth** [comment]
Keep CWE 345

**Comment by tghosth** [comment]
Will also need to renumber

**Comment by tghosth** [comment]
@set-reminder 3 weeks @tghosth to address

**Comment by tghosth** [comment]
Created PR
