### ISSUE TITLE
Merge edits/comments to V20 

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#144]
Thanks for the guidance on how to find the doc on github. I am new github user, so I kind of winged it as far as getting my file uploaded by forking a branch, cloning and then adding my file there. Hopefully this has not caused any trouble.

The link is below
https://github.com/GitMadjid/Madjid_editsTo3.1

Comments are only on v.20 which is on IOT devices which has been most my focus last year or so. Will follow up with web server side hopefully in the next month or so.

Attaching the file the old fashion way here too, since I am not sure if I did it right.

**Comment by vanderaj** [comment]
@GitMajid - I don't know if this has been dealt with. Can you please let us know?

**Comment by danielcuthbert** [comment]
There's actually a lot wrong with this section, some of the requirements would just not make sense in most cases. For example:

| **20.4** | Verify that on-chip debugging interfaces such as JTAG or SWD are disabled or that available protection mechanism is enabled and configured appropriately. | ✓ | ✓ | ✓ | 4.0 |

Yes, the manufacturer could have removed the pins, or hidden them, you can go down the spec sheets route. if they aren't available, you've got logic analysers or the epic JTAGulator. Finally, if the manufacturer was truly trying to stop anyone accessing them, you'd resort to soldering. 

What I'm getting at is that the above is hard and adds cost to already very price-sensitive devices and engineering. It just wont happen and i question the value of such advice and its effectiveness. 

Having been involved in designing and building such devices over the past year, many requirements here make no sense and are impractical. 

We need to revisit the IoT section before we finalise 4.0.

**Comment by danielcuthbert** [comment]
closing this one as there will be a bigger discussion based on this and other thoughts around IoT
