### ISSUE TITLE
14.3.3 - exclude js libraries (or client-side components in general) from the requirement, as those expose their version one way or another.

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1441]
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **14.3.3** | Verify that the HTTP headers or any part of the HTTP response do not expose detailed version information of system components. | ✓ | ✓ | ✓ | 200 |

Exposing version info is helping attacker in enumeration phase and it makes sense to not advertise your versions and components.

As it's is not realistic to hide client-side components (javascript libraries) and their versions, I recommend to exclude them from the requirement. Otherwise it can cause noise in "pentest" reports.

An example: jQuery exposing it's version in HTTP response. If some application includes it from CDN, it usually contains precise version already from file name. And even if the version info is removed from comments, it's still in the javascript code and accessible with `$().jquery`.

And if you manually removed all version info from components, then you can still check code from repository and compare, which version is it.

So it's not correct to recommend to hide component version info from HTTP response, it's just not realistic.

For reporting old versions in use we have separate requirement 14.2.1:
_V14.2.1 Verify that all components are up to date, preferably using a dependency checker during build or compile time._

**Comment by tghosth** [comment]
@set-reminder 3 weeks @tghosth to open PR with this:

> Verify that the HTTP headers or any part of the HTTP response do not expose detailed version information of **server-side** components.

**Comment by tghosth** [comment]
Created #1516
