### ISSUE TITLE
1.9.1, 1.9.2 - check duplicates and/or merge to V9 requirements

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1443]
## V1.9 Communications Architecture

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.9.1** | Verify the application encrypts communications between components, particularly when these components are in different containers, systems, sites, or cloud providers. ([C3](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 319 |
| **1.9.2** | Verify that application components verify the authenticity of each side in a communication link to prevent person-in-the-middle attacks. For example, application components should validate TLS certificates and chains. | | ✓ | ✓ | 295 |

Are those requirements actually already covered by requirements in [V9](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x17-V9-Communications.md) category?

Proposal: if not, move and/or merge missing points to V9 requirements.

**Comment by tghosth** [comment]
@set-reminder 3 weeks @tghosth to think about this

**Comment by tghosth** [comment]
I think 1.9.1 is entirely duplicated by [9.1.1](https://appsecg.host/9.1), [9.2.2](https://appsecg.host/9.2) and [9.3.1](https://appsecg.host/9.3).

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **9.1.1** | [MODIFIED] Verify that TLS is used for all connectivity between the client and external facing, HTTP-based services, and does not fall back to insecure or unencrypted communications. ([C8](https://owasp.org/www-project-proactive-controls/#div-numbering)) | ✓ | ✓ | ✓ | 319 |
| **9.2.2** | Verify that encrypted communications such as TLS is used for all inbound and outbound connections, including for management ports, monitoring, authentication, API, or web service calls, database, cloud, serverless, mainframe, external, and partner connections. The server must not fall back to insecure or unencrypted protocols. | | ✓ | ✓ | 319 |
| **9.3.1** | [ADDED] Verify that TLS or another appropriate transport encryption mechanism used for all connectivity between internal, HTTP-based services, and does not fall back to insecure or unencrypted communications. | | ✓ | ✓ | 319 |

For 1.9.2, I think this is covered by [9.2.3](https://appsecg.host/9.3) and [9.3.2](https://appsecg.host/9.3)

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **9.2.3** | Verify that all encrypted connections to external systems that involve sensitive information or functions are authenticated. | | ✓ | ✓ | 287 |
| **9.3.2** | [MODIFIED, MOVED FROM 9.2.1] Verify that TLS connections between internal services use trusted certificates. Where internally generated or self-signed certificates are used, the consuming service must be configured to only trust specific internal CAs and specific self-signed certificates. All others should be rejected. | | ✓ | ✓ | 295 |

However, in 9.3.2 I would be tempted to change "**Verify that TLS connections between internal services use trusted certificates.**" to "**Verify that TLS connections between internal services use trusted certificates and that these are validated by the calling service.**"

What are people's thoughts on this?

**Comment by elarlang** [comment]
> I would therefore consider either deleting 1.9.1 or changing it to a documentation requirement.

What is the goal for documentation requirement?

Otherwise I think we can move forward with proposed solutions.

**Comment by jmanico** [comment]
Side note: If we do move 1.9.2 I think it also needs significant modification per https://github.com/OWASP/ASVS/issues/1548

**Comment by jmanico** [comment]
Suggestion on 1.9.1 here: https://github.com/OWASP/ASVS/issues/1547

**Comment by tghosth** [comment]
I think this is best handled alongside the larger V1 rewrite so moving to rework / v1.
