### ISSUE TITLE
14.4.1 should be 3 requirements

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1459]
I think 14.4.1 should be 3 requirements:
* All have content type
* Specify safe encoding
* Actual content type must match header

It currently is this:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **14.4.1** | Verify that every HTTP response contains a Content-Type header. Also specify a safe character set (e.g., UTF-8, ISO-8859-1) if the content types are text/*, /+xml and application/xml. Content must match with the provided Content-Type header. | ✓ | ✓ | ✓ | 173 |

**Comment by elarlang** [comment]
Just for linking previous issues on the topic:
* https://github.com/OWASP/ASVS/issues/788
* https://github.com/OWASP/ASVS/issues/900

**Comment by jmanico** [comment]
I suggest two: one requiring a safe content type and a second that goes over the text issue..

**Comment by elarlang** [comment]
from test-case perspective I would use 2 requirements but a bit differently than Jim proposed:
* Verify that every HTTP response contains a Content-Type header. Also specify a safe character set (e.g., UTF-8, ISO-8859-1) if the content types are text/*, /+xml and application/xml.
* Verify that served content match with the provided Content-Type header.
  * do we need to limit it to "when served inline" == "not served as attachment"?

**Comment by tghosth** [comment]
Ok so neither of you think that just having a content type header on each request should be it's own requirement?

**Comment by elarlang** [comment]
Actually, I like this requirement like it is.

If we have separate requirement "just have a content-type header" in response. What is the point?

Do you verify that it is ok and satisfied requirement, when the value or charset does not make any sense or it does not match with actual content?

I think it's one validation, can not watch each item separately.

**Comment by tghosth** [comment]
I have taken this opportunity to revisit the information about content types in 14.4.1.

* @jason-invision pointed to [RFC-2046](https://tools.ietf.org/html/rfc2046#section-4.1.2) in [this comment](https://github.com/OWASP/ASVS/issues/710#issuecomment-584793932) to come up with the `text/*`, `*/*+xml` and `application/xml` types 
* @elarlang did some good analysis [in this issue](https://github.com/OWASP/ASVS/issues/788) to clarify the types required,
* `text/*` is clearly indicated in the original [RFC-2046](https://tools.ietf.org/html/rfc2046#section-4.1.2).
* `*/xml` is "strongly recommended" by  [RFC-2376](https://datatracker.ietf.org/doc/html/rfc2376#section-3.1).
* `*/*+xml` there are loads of these but seems like charset is needed for them.

Going back to the original requirement, I think two requirements is right but I would do them different to @elarlang 

> Verify that every HTTP response contains a Content-Type header which matches the actual content of the response.

> Verify that if a response specifies a Content-Type of "text/\*", "\*/\*+xml" and "\*/xml", it also specifies a safe character set (e.g., UTF-8, ISO-8859-1) with the charset parameter.

@elarlang @jmanico what do you think?

**Comment by elarlang** [comment]
I still prefer this as one requirement (https://github.com/OWASP/ASVS/issues/1459#issuecomment-1359324019), can live with separate ones.

**Comment by tghosth** [comment]
Opened #1728 to resolve
