### ISSUE TITLE
proposal: remove 1.1.3 as out of scope

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1460]
Current requirement 1.1.3

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.1.3** | [GRAMMAR] Verify that all user stories and features contain functional security constraints, such as "As a user, I should be able to view and edit my profile. I should not be able to view or edit anyone else's profile". | | ✓ | ✓ | 1110 |

It does not have clear impact for running application security. Developers can implement code incorrectly with having the documentation and testers need to test it correctly without having the documentation.

Proposal: remove, out of scope.

**Comment by jmanico** [comment]
I agree these non technical requirements are out of scope and should be removed.
