### ISSUE TITLE
proposal: remove or update 1.1.7

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1461]
Current requirement 1.1.7:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.1.7** | Verify availability of a secure coding checklist, security requirements, guideline, or policy to all developers and testers. | | ✓ | ✓ | 637 |

Maybe some parts of this requirement are useful - but how one can test this requirement (available for developers and testers)?

We can only verify that those exists. The point should be: Verify that security standard and policy are defined for the application.

This is pre-condition for actual testing.

We don't actually need secure coding checklist and guideline - for sure those are useful but it does not mean that developers follow them and the application is less secure without them.

**Comment by jmanico** [comment]
I think all of these non-technical requirements should go away. Too abstract.

**Comment by elarlang** [comment]
Some of them contain valid point as pre-condition for actual developing and security testing, like this one:
_Verify that security standard and policy are defined for the application._

The point is - before deleting one, we should check do we need some part of it as pre-condition.

**Comment by tghosth** [comment]
I think the requirement is too general, I think we need to specify in our "documentation" requirements what is actually needed for specific types of security control.

**Comment by tghosth** [comment]
The forking should be for de-scoping or refining requirements according to the organization's specific situation. It should not involve changing the requirements but rather be an accelerator to make it easier and more accurate to use across an organization.

The assessment of an application should still be performed using the **out-of-the-box version of the standard** although it could refer to the forked version being used for specific clarifications.

As such, I want to avoid generic/"hard to assess" requirements.

**Comment by elarlang** [comment]
ok, agree with that. The requirement as is will be removed.
