### ISSUE TITLE
One key per piece of data encrypted

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1464]
@jmanico wrote in #1198:

> I think it’s a good high level requirement (ASVS L3) to suggest using only one key per piece of data encrypted. It makes cryptanalysis much much more difficult.
> 
> Reference : https://code.cash.app/app-layer-encryption
>
> Note how cash app has one key per piece of data, it’s remarkable and significantly adds to the long term security of their crypto system.

**Comment by jmanico** [comment]
The change made works for me. Its merged.
