### ISSUE TITLE
1.7.2 - securely transmitting logs to external system - point, scope and category

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1466]
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.7.2** | Verify that logs are securely transmitted to a preferably remote system for analysis, detection, alerting, and escalation. ([C9](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | |

category - if to keep this requirement, we should move it to V7.3 Log Protection

point - the point seems to be that logs are handled outside of the application. If logs are kept in scope with the application, is the application not valid for ASVS?

What we actually need to verify here? That they are securely transmitted? How? From that perspective seems a bit questionable - is it the ASVS scope.

**Comment by jmanico** [comment]
This feels more infrastructure to me and less AppSec- I’d like devs to do security logging - and we can verify that.

**Comment by tghosth** [comment]
I see no problem with verifying that application logs are transmitted securely and transmitted to a remote system. Maybe we need to specify that these are application logs. I agree that this is implementation and not documentation/architecture.

**Comment by elarlang** [comment]
From V1 clean-up point of view, let's move 1.7.2 to V7.3 (as V7.3.5) and let's have scope and requirement text to be solved later.

In general - how do you verify that those are securely transmitted? What is securely transmitted?

**Comment by tghosth** [comment]
TLS, not messing up certificates...

**Comment by tghosth** [comment]
@set-reminder 3 weeks @tghosth to create a PR to move it
