### ISSUE TITLE
proposal: delete 12.3.5 as duplicate of 5.3.8

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1472]
Related requirements:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **5.3.8** | Verify that the application protects against OS command injection and that operating system calls use parameterized OS queries or use contextual command line output encoding. ([C4](https://owasp.org/www-project-proactive-controls/#div-numbering)) | ✓ | ✓ | ✓ | 78 |
| **12.3.5** | Verify that untrusted file metadata is not used directly with system API or libraries, to protect against OS command injection. | ✓ | ✓ | ✓ | 78 |

Proposal: delete 12.3.5 as duplicate of 5.3.8

**Comment by jmanico** [comment]
Agreed

**Comment by elarlang** [comment]
@tghosth - do you think anything from 12.3.5 need to be covered in 5.3.8 or we just delete 12.3.5?

**Comment by tghosth** [comment]
Opened #1718 to resolve this
