### ISSUE TITLE
2.6.3 is redundant and does not add anything to 2.6.2

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1476]
Current 2.6.3:

> Verify that lookup secrets are resistant to offline attacks, such as predictable values. | | ✓ | ✓ | 310 | 5.1.2.2 |

Current 2.6.2:

> [MODIFIED] Verify that lookup secrets have sufficient randomness (112 bits of entropy), or if less than 112 bits of entropy, are hashed with an approved password storage hashing algorithm.

2.6.2 proposed in #1218 and #1449:

> [MODIFIED] Verify that lookup secrets with 112 bits of entropy or more (typically 19 random alphanumeric characters or 34 random digits is sufficient) are hashed with an approved password storage hashing algorithm. If the secret has less than 112 bits of entropy, a 32bit random salt should be incorporated.

What I said in the title. The point of the "approved password storage hashing algorithm" is to make the secret resistant to offline attack. As such, this extra requirement adds nothing.

I would propose just deleting 2.6.3.

**Comment by tghosth** [comment]
@elarlang what do you think?

**Comment by elarlang** [comment]
[CWE-310](https://cwe.mitre.org/data/definitions/310.html) points to "Cryptographic Issues" which does not seem to be correct.

In general - 2.6.2 says how you need to store it, 2.6.3 says what value they can have.

With the proposal/modification of 2.6.2 you solve the "reistant to offline attacks" part - but what if the code is `0000`? I think 2.6.3 should cover that part - that this code can not be simple stupid and also not guessable with online attacks. Like with classical passwords we have different rules how you need to store the password and what kind of value password can (not) have.

**Comment by tghosth** [comment]
So it currently says:

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.6.3** | Verify that lookup secrets are resistant to offline attacks, such as predictable values. | | ✓ | ✓ | 310 | 5.1.2.2 |

I would propose changing it to:

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.6.3** | Verify that lookup secrets are generated using a Cryptographically Secure Pseudorandom Number Generator (CSPRNG) to avoid predictable values. | | ✓ | ✓ | 310 | 5.1.2.2 |


What do you think @elarlang ?

**Comment by elarlang** [comment]
Yes, better.

(... and the `MODIFIED` label for PR)

**Comment by tghosth** [comment]
Doh

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.6.3** | [MODIFIED] Verify that lookup secrets are generated using a Cryptographically Secure Pseudorandom Number Generator (CSPRNG) to avoid predictable values. | | ✓ | ✓ | 310 | 5.1.2.2 |

@set-reminder 4 weeks @tghosth to open a PR hopefully after #1449 has merged

**Comment by maizuka** [comment]
Should we limit the generator to CSPRNG? There are generators that are enforced but not specified as CSPRNG, such as SecureRandom in Java. The attack to randomness of lookup secrets needs too many samples  for attackers to obtain, so I suggest softer specification such as "using secure generators".

**Comment by tghosth** [comment]
Is SecureRandom not considered a CSPRNG. My understanding is that it is, no?

**Comment by maizuka** [comment]
I'm sorry. The SecureRandom is CSPRNG and very wrong example. I might be confused to another language but please ignore that because it came from my unreliable knowledge.
I will add comment here if I will find any issue with right information.

**Comment by jmanico** [comment]
> I'm sorry. The SecureRandom is CSPRNG and very wrong example.

The docs say:

public class SecureRandom
extends [Random](https://docs.oracle.com/javase/8/docs/api/java/util/Random.html)
This class provides a cryptographically strong random number generator (RNG).
A cryptographically strong random number minimally complies with the statistical random number generator tests specified in [FIPS 140-2, Security Requirements for Cryptographic Modules](http://csrc.nist.gov/cryptval/140-2.htm), section 4.9.1. Additionally, SecureRandom must produce non-deterministic output. Therefore any seed material passed to a SecureRandom object must be unpredictable, and all SecureRandom output sequences must be cryptographically strong, as described in [RFC 1750: Randomness Recommendations for Security](http://www.ietf.org/rfc/rfc1750.txt).
