### ISSUE TITLE
3.2.4 needs to be more specific

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1478]
Current wording of [3.2.4](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x12-V3-Session-management.md#v32-session-binding):

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **3.2.4** | Verify that session tokens are generated using approved cryptographic algorithms. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 331 | 7.1 |

This doesn't really make sense in the context nor does it really match what [NIST](https://pages.nist.gov/800-63-3/sp800-63b.html#71-session-bindings) says.

I would recommend changing to:

> [MODIFIED] Verify that opaque session tokens are generated using a secure random function.

The CWE should also be changed from [CWE-331: Insufficient Entropy](https://cwe.mitre.org/data/definitions/331.html) to [CWE-330: Use of Insufficiently Random Values](https://cwe.mitre.org/data/definitions/330.html).

Any objections?

The use of "opaque" session tokens should distinguish between this and something like a JWT.

 [3.2.2](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x12-V3-Session-management.md#v32-session-binding) should also be clarified to mention opaque.
 
 | # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **3.2.2** | [MODIFIED] Verify that session tokens possess at least 128 bits of entropy. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | ✓ | ✓ | ✓ | 331 | 7.1 |

Suggested:
> [MODIFIED] Verify that **opaque** session tokens possess at least 128 bits of entropy.

@set-reminder 2 weeks @tghosth open PR if no opposition.

**Comment by elarlang** [comment]
Ok for me. I guess CWE change for 3.2.2 as well?

**Comment by tghosth** [comment]
CWE for 3.2.2 is actually fine. I changed 3.2.4 though. Opened PR #1517
