### ISSUE TITLE
Remove glossary section from V2 to App A

### ISSUE THREAD

**Issue by JoergBruenner** [OWASP/ASVS#1479]
Hi,

I wonder if we could move the glossary of terms in "V2 Authentication" to Appendix A.
One could read this more fluently: I guess noone expect a glossary in the middle of the
standard. Even it's the only chapter we do so.

See you
Jörg Brünner

**Comment by elarlang** [comment]
When requirements are reorganized, all the text part will be reviewed.

**Comment by elarlang** [comment]
I link here related discussion https://github.com/OWASP/ASVS/discussions/1574

**Comment by ryarmst** [comment]
A note for later when this is reviewed; to the extent it is possible, it may be helpful to organize the glossary by chapter.

**Comment by JoergBruenner** [comment]
I wouldn't do that: You may have to repeat too much.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Ryan Armstrong ***@***.***> Datum: 21.09.24  15:57  (GMT+01:00) An: OWASP/ASVS ***@***.***> Cc: JoergBruenner ***@***.***>, Author ***@***.***> Betreff: Re: [OWASP/ASVS] Remove glossary section from V2 to App A (Issue
  #1479) 
A note for later when this is reviewed; to the extent it is possible, it may be helpful to organize the glossary by chapter.

**Comment by ryarmst** [comment]
I think there ought to be some way for users of the ASVS to easily identify the meaning behind relevant terminology used in each chapter without reading the glossary from top to bottom, but perhaps that is not shared.

**Comment by tghosth** [comment]
> I think there ought to be some way for users of the ASVS to easily identify the meaning behind relevant terminology used in each chapter without reading the glossary from top to bottom (or somehow knowing when a specific term has a corresponding definition they can search for), but perhaps that is not shared.

So I think having a glossary that is not ordered alphabetically would be a little tricky. Obviously the glossary can also be searched. I am however open to suggestions in what we could.

One option is to have multiple copies of the glossary which are ordered differently and generated using a script. We would still need a clear definition of the different orders though.

**Comment by tghosth** [comment]
I have moved most of it.

I have left two items because they are very specific to the NIST style terminology and I need to fix them alongside the rest of the chapter.
