### ISSUE TITLE
5.3.11 is not practically testable

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1484]
This requirement was moved here as it was considered to be implementation specific.

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **5.3.11** | [MOVED FROM 1.5.4] Verify that output encoding occurs close to or by the interpreter for which it is intended. ([C4](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 116 |

I am not sure I agree with that but in any case it is not clear to me how this would be tested.

Do we think we need to return this to V1 and convert it into some sort of documentation requirement? Otherwise, I think we may have to eliminate it and leave it as a standard assumption for the correct implementation of any output encoding/sanitization.

**Comment by elarlang** [comment]
(Bad) Example: data is converted for HTML output and stored to database and then it's "safe" to display it to the HTML. The problem is, if you need to display the same data in JavaScript or any other format, you have data in incorrect encoding and not in original way - may also cause integrity problem.

What we expect - data is stored as it came from the source/user and it is converted for every component just before or by the component which uses the data.

**Comment by elarlang** [comment]
Another example - data is converted for HTML in user browser when user is using some WYSIWYG kind of thing, user submits HTML encoded data...

**Comment by tghosth** [comment]
I understand the concept behind it but it is not really a requirement that itself can be specifically tested without separately looking at the implementation of all output encoding, I think maybe this should just be a factor within an existing output encoding requirement like 5.3.3.

Do you disagree @elarlang ?

**Comment by elarlang** [comment]
Yes, I disagree. It's not only output problem.

If the data from user modified to some encoding it means that it's already ruining the integrity.

I have used this requirement for pen-test reports often enough to say it's clearly valid and needed.

Maybe we can look to this problem from another angle with more clear statement (I don't have any problems with current one), but the it should exists in ASVS.

**Comment by tghosth** [comment]
So what if we did something like this:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **5.3.3** | Verify that context-aware, preferably automated - or at worst, manual - output escaping protects against reflected, stored, and DOM based XSS **and that this is done close to or by the interpreter for which it is intended**. ([C4](https://owasp.org/www-project-proactive-controls/#div-numbering)) | ✓ | ✓ | ✓ | 79 |

**Comment by elarlang** [comment]
In practice it's mostly happening (or I have detected) with converted too early for HTML/XML. The same problem may happen with any other component/document - SQL, JavaScript, OS command, LDAP, ...

From that I would say current requirement needs "escaping" to be covered additionally to output encoding. Also, current requirement maybe needs "as a last step before executed by interpreter". Otherwise we may have situation when something is first encoded or escaped, but then comes value max length truncation, sanitization etc.

**Comment by tghosth** [comment]
@elarlang I accept the "as a last step before executed by interpreter" point but I still don't see 5.3.11 as a separate, practically testable requirement. It still seems to be part of the general output encoding/escaping requirements.

How can we make this requirement practically testable? Right now it sounds like we are expecting the tester to review all encoding/escaping code to look where it is being done...

**Comment by elarlang** [comment]
Meanwhile I'm more and more convinced that we need this as separate requirement.

It may require code review, but it may come out other ways. If encoding or escaping is done before max-length or truncation.

And maybe we need matching requirement like "Verify that decoding is done once and as first step e. g. decoding is not done after input validation or sanitization."

**Comment by elarlang** [comment]
> I accept the "as a last step before executed by interpreter" point but I still don't see 5.3.11 as a separate, practically testable requirement. **It still seems to be part of the general output encoding/escaping requirements.**

We need it as separate requirement - for each separate technology requirement we say "do the correct thing" and with this requirement (current 5.3.11) we say "do it in correct place" / "do things in correct order", otherwise it may loose it's effect.

Escaping things should be covered by #1589

Decoding part should be covered by #1590

For current 5.3.11 we should "inject" the idea "as a last step before executed by interpreter"

**Comment by elarlang** [comment]
ping @tghosth

**Comment by tghosth** [comment]
So this feels like something to consider alongside the rest of the issues in this chapter... marking for rework,

**Comment by tghosth** [comment]
We need to create an Validation and Sanitization Architecture section which contains this item and also #1590

Suggested updated wording for this item:

> [MODIFIED, MOVED FROM 1.5.4] Verify that output encoding is designed throughout the application to occur close to or by the interpreter for which it is intended. ([C4](https://owasp.org/www-project-proactive-controls/#div-numbering))

**Comment by tghosth** [comment]
@elarlang

**Comment by jmanico** [comment]
Like it, Josh

**Comment by elarlang** [comment]
> Verify that output encoding and escaping are designed throughout the application to occur close to or by the interpreter for which it is intended.

* I added "escaping"
* is "to occur close to or by the interpreter" clear enough?
  * compare with "as a last step before executed by interpreter"
* should we make clear the intention of the requirement: "data must be stored in the "original" state, not as encoded for some specific encoding (e.g. HTML encoding)?

ping @tghosth @jmanico

**Comment by tghosth** [comment]
> Verify that the application performs output encoding and escaping either as a final step before being used by the interpreter for which it is intended or by the interpreter itself.

This is a good final wording.

> should we make clear the intention of the requirement: "data must be stored in the "original" state, not as encoded for some specific encoding (e.g. HTML encoding)?

@elarlang to add this to the intro to the section.

**Comment by elarlang** [comment]
> should we make clear the intention of the requirement: "data must be stored in the "original" state, not as encoded for some specific encoding (e.g. HTML encoding)?

I need help with wording for this one.

**Comment by elarlang** [comment]
Note that I also made the requirement Level 1.

**Comment by csfreak92** [comment]
> > should we make clear the intention of the requirement: "data must be stored in the "original" state, not as encoded for some specific encoding (e.g. HTML encoding)?
> 
> I need help with wording for this one.

Is the purpose of that one to prevent double encoding issues? 

If yes, then how about "Whenever data is being stored, ensure that it is stored in its original state and not in an encoded state (e.g. HTML encoding) to prevent double encoding issues"

**Comment by tghosth** [comment]
> > > should we make clear the intention of the requirement: "data must be stored in the "original" state, not as encoded for some specific encoding (e.g. HTML encoding)?
> > 
> > 
> > I need help with wording for this one.
> 
> Is the purpose of that one to prevent double encoding issues?
> 
> If yes, then how about "Whenever data is being stored, ensure that it is stored in its original state and not in an encoded state (e.g. HTML encoding) to prevent double encoding issues"

I like this and I added a paragraph along these lines to the intro section @csfreak92 @elarlang 
.

**Comment by tghosth** [comment]
> Note that I also made the requirement Level 1.

I think we should keep this L2. In an ideal world it would be the basis of all other requirements but practically speaking I think we have to accept that it probably wouldn't be covered in a basic verification, especially black box.

**Comment by elarlang** [comment]
> > Note that I also made the requirement Level 1.
> 
> I think we should keep this L2. In an ideal world it would be the basis of all other requirements but practically speaking I think we have to accept that it probably wouldn't be covered in a basic verification, especially black box.

At the time when we don't have level's defined, it's pointless to discuss it. So I re-changed it
https://github.com/OWASP/ASVS/commit/b251c3774695fcf3af69571e32cc2ae4525e056c

**Comment by tghosth** [comment]
Note this requirement subsequently became 5.6.2 instead of 5.6.3 as something else got moved.
