### ISSUE TITLE
Rationale behind 14.5.2

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1487]
I would like to dig into the rationale/history behind this requirement as it is not super clear to me.

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **[14.5.2](https://appsecg.host/14.5)** | Verify that the supplied Origin header is not used for authentication or access control decisions, as the Origin header can easily be changed by an attacker. | ✓ | ✓ | ✓ | [346](https://cwe.mitre.org/data/definitions/346.html) |

**Comment by elarlang** [comment]
First, I think there is some confusion between authentication and authorization. For me it's hard to understand, how you can authenticate based on `Origin` header, so I _assume_ that it actually points to authorization.

And based on that, I think requirement 14.2.5 is covered by current 4.1.1:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **4.1.1** | [MODIFIED] Verify that the application enforces access control rules at a trusted service layer **and doesn't rely on controls which an untrusted user could manipulate** such as client-side JavaScript. | ✓ | ✓ | ✓ | 602 |


CWE-346 points to Origin Validation Error - with description: _The software does not properly verify that the source of data or communication is valid._

Based on this it's not server-side authentication or authorization check, but just client-side communication. We have this covered by:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **14.5.3** | [MODIFIED, SPLIT TO 14.4.8] Verify that the Origin header is validated against a defined list of allowed origins to match the desired Cross-Origin Resource Sharing (CORS) policy. | ✓ | ✓ | ✓ | 346 |

14.5.2 and 14.5.3 both have CWE-346, for requirement 14.5.2 it is clearly incorrect - defense against server-side attack vs client-side side attack.

My proposal: delete 14.5.2 as duplicate of 4.1.1.

**Comment by tghosth** [comment]
Is this a very literal interpretation of https://cwe.mitre.org/data/definitions/346.html?

Seems to have originated in 3.1 with basically the same text.

In summary, I agree with @elarlang's suggestion to delete  14.5.2

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **[14.5.2](https://appsecg.host/14.5)** | Verify that the supplied Origin header is not used for authentication or access control decisions, as the Origin header can easily be changed by an attacker. | ✓ | ✓ | ✓ | [346](https://cwe.mitre.org/data/definitions/346.html) |

@jmanico what do you think?

**Comment by tghosth** [comment]
I'd like to wait for a comment from @jmanico before committing the PR

**Comment by jmanico** [comment]
I agree that deleting requirement 14.5.2 is good since it seems to duplicate 4.1.1
