### ISSUE TITLE
9.1 retire

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#149]
9.1 contains text around autocomplete, which the browsers no longer support. Once that's removed, the remaining text is identical in nature to 9.4, which has better guidance. So it's time for 9.1 to be retired.

**Comment by kozmic** [comment]
@vanderaj Browsers do still support autocomplete attribute on input elements (even though Chrome sometimes won't let you turn it of in some cases).

Can be tested here: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_autocomplete
(note that most security aware end users turn this browser feature off, but it's on by default)

**Comment by jmanico** [comment]
I agree it's still a risk but one that I think we can afford to drop from ASVS. Twitter chimed in as well and a few serious experts from other companies and tools agreed. https://twitter.com/manicode/status/1024733278467579904

**Comment by jmanico** [comment]
Just to explain more: There are only two ways to harvest autocomplete data maliciously. One is local access to the browser/machine. That's not in our threat model for the most part. Second, if you find a browser bug then XSS/JavaScript can harvest autocomplete data.

In the past, autocomplete data could be harvested from XSS CROSS DOMAIN and that is crazy. Today, JavaScript does not give you access to autocomplete data so those vectors are gone. You would need to find an unknown browser bug to harvest autocomplete data from JavaScript. 

Hence, 9.1 is going away in ASVS 4.0.
