### ISSUE TITLE
Resetting password by changing email/phone number.

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1496]
Do we currently have a requirement to prevent the scenario where an attacker with temporary access to a session can change an email address or phone number to one which is attacker controlled and then use that to change the user's password via the forgot password functionality?

@elarlang ?

**Comment by elarlang** [comment]
| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **3.7.1** | [MODIFIED] Verify the application requires re-authentication or secondary factor verification before allowing any sensitive transactions or account modifications. | ✓ | ✓ | ✓ | 306 | |

**Comment by jmanico** [comment]
This looks well covered @tghosth - close this out?

**Comment by vdbaan** [comment]
I agree with Jim that this seems to cover it

**Comment by tghosth** [comment]
So 2.2.3 is too late IMHO, this needs to be a preventative control.

3.7.1 has problems and I have raised this in #1523 so I don't think we can rely on this specifically but maybe a different version of it put elsewhere.

4.3.3 actually seems more like what I was thinking of but not exactly.

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **4.3.3** | Verify the application has additional authorization (such as step up or adaptive authentication) for lower value systems, and / or segregation of duties for high value applications to enforce anti-fraud controls as per the risk of application and past fraud. | | ✓ | ✓ | 732 |

I am thinking of something more like [GitHub's "sudo mode"](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/sudo-mode).

I would suggest something similar to 3.7.1 but more focused and I would be tempted to consider this a V2 authentication issue rather than V3 session management..

> Verify that the application requires re-authentication or secondary verification before allowing highly sensitive transactions or modifications to account authentication settings.

**Comment by elarlang** [comment]
Is suggestion meant to be new requirement on update to current 3.7.1?

> I would suggest something similar to 3.7.1 but more focused and I would be tempted to consider this a V2 authentication issue rather than V3 session management..

Without any extra problems with authentication or authorization - 3.7.1 can happen only when user's session is taken over and it's defense against escalation from session takeover to account takeover.

So 3.7.1 requires that user re-authenticates (V2) to be sure, that in case of session takeover (V3) user is legit and authorized (V4) to do this sensitive action. From this I would say, it's more authorization requirement.

**Comment by tghosth** [comment]
So in ASVS version 2.0 there were two controls which mentioned this sort of step up authentication.

### version 2.0 

| ID | Section | Description
| :---: | :---: | :--- |
| **V2.26** | Authentication | Verify re-authentication, step up or adaptive authentication, SMS or other two   factor authentication, or transaction signing is required before any application-specific sensitive operations are permitted as per the risk profile of the application. |
| **V15.9** | Business Logic | Verify the application has additional authorization (such as step up or adaptive authentication) for lower value systems, and / or segregation of duties for high value applications to enforce anti-fraud controls as per the risk of application and past fraud. |

It looks like 2.26 got carried into version 3.0 as 2.26 except it is talking about "high value transactions" rather than "sensitive operations".

It looks like 15.9 got carried into version 3.0 in the "Access Control" chapter as 4.15 

### version 3.0 

| ID | Section | Description
| :---: | :---: | :--- |
| **V2.26** | Authentication | Verify that risk based re-authentication, two factor or transaction signing is in place for high value transactions. |
| **V4.15** | Access Control | Verify the application has additional authorization (such as step up or adaptive authentication) for lower value systems, and / or segregation of duties for high value applications to enforce anti-fraud controls as per the risk of application and past fraud.. |


It looks like 2.26 got carried into 4.0 as 3.7.1 and 4.15 got carried into 4.0 as 4.3.3.

### version 4.0 

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **3.7.1** | [MODIFIED] Verify the application requires re-authentication or secondary factor verification before allowing any sensitive transactions or account modifications. | ✓ | ✓ | ✓ | 306 | |
| **4.3.3** | Verify the application has additional authorization (such as step up or adaptive authentication) for lower value systems, and / or segregation of duties for high value applications to enforce anti-fraud controls as per the risk of application and past fraud. | | ✓ | ✓ | 732 |


I guess my proposal in this issue is to re-work part of 3.7.1 to be in V2 and more focussed around the original meaning for which I propose:

> Verify that the application requires re-authentication or secondary verification before allowing highly sensitive transactions or modifications to account authentication settings.

In #1523 I also say that there are session management aspects there that we should ensure are captured earlier in V3.

As for the current 4.3.3, I think this needs to be returned to business logic and have more thought applied to it as noted in #1045

**Comment by tghosth** [comment]
I have created a PR to try and address the wording clarification here. I am going to continue the discussion on which section it should be in at #1523
