### ISSUE TITLE
Appendix B - Page 46 - OWASP Top 10 Guide Link Should be Consistent

### ISSUE THREAD

**Issue by defern** [OWASP/ASVS#15]
Appendix B - Page 46 - OWASP Top 10 Guide Link Should be Consistent

OWASP Top Ten Project - http://www.owasp.org/index.php/Top_10  this is different from the same on page 44

http://www.owasp.org/index.php/Top10

But it looks like the same page

Additionally should the Mobile top 10 be included since there is a big mobile section, V17?
https://www.owasp.org/index.php/Projects/OWASP_Mobile_Security_Project_-_Top_Ten_Mobile_Risks

**Comment by vanderaj** [comment]
Fixed, thank you :)
