### ISSUE TITLE
The usage of "SHOULD"

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1505]
I understand that some requirement got quite clearly ported from NIST, where special keywords are written with capital letters. In ASVS requirements we don't use this style and should use the same style through the document.

There are some "leftovers" with capital SHOULD (didn't find any MAY, MUST or SHALL anymore).

```
grep -r "SHOULD" .
```

or

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.4.3** | [MODIFIED] Verify that if PBKDF2 is used, the iteration count **SHOULD** be as large as verification server performance will allow, with a minimum of 720,000 iterations with PBKDF2-HMAC-SHA1, a minimum of 310,000 iterations using PBKDF2-HMAC-SHA256, or with a minimum of 120,000 iterations with PBKDF2-HMAC-SHA512. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 916 | 5.1.1.2 |
| **2.4.6** | [ADDED] Verify that if argon2id is used, the configuration **SHOULD** be as strong as verification server performance will allow, with a minimum configuration of 15 MiB of memory, an iteration count of 2, and 1 degree of parallelism. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 916 | 5.1.1.2 |
| **2.4.7** | [ADDED] Verify that if scrypt is used, the configuration **SHOULD** be as strong as verification server performance will allow, with a minimum CPU/memory cost parameter of (2^16), a minimum block size of 8 (1024 bytes), and a parallelization parameter of 1. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 916 | 5.1.1.2 |
| **2.10.4** | Verify passwords, integrations with databases and third-party systems, seeds and internal secrets, and API keys are managed securely and not included in the source code or stored within source code repositories. Such storage **SHOULD** resist offline attacks. The use of a secure software key store (L1), hardware TPM, or an HSM (L3) is recommended for password storage. | | ✓ | ✓ | 798 | |

Proposal - use lowercase "should".

**Comment by elarlang** [comment]
@tghosth @jmanico @danielcuthbert - any disagreement or I go for PR?

**Comment by jmanico** [comment]
Love it, go PR

**Comment by danielcuthbert** [comment]
I like this @elarlang GO GO GO  ;)

**Comment by elarlang** [comment]
> I like this @elarlang GO GO GO ;)

Nowhere to GO, PR is/was waiting already
