### ISSUE TITLE
Section 5.14 should be split in to two.

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#151]
Section 5.14:
Verify that the application is not susceptible to common XML attacks, such as XPath query tampering, XML External Entity attacks, and XML injection attacks.

This should be split into two:

1. Test the application for XPath query tampering and XML injection attacks; and  
2. XML External Entity attacks

XXE vulnerability is uniquely different to the other two. 

Potentially, XPath and XML injection could be split as well, since XML Injection is a generic 'catch-all' condition. Or it could be removed and simplified, if there is nothing concrete to test there, since XXE and XPath tampering will cover most of it.

**Comment by jmanico** [comment]
Agreed full. This issue will be closed and re-opened as https://github.com/OWASP/ASVS/issues/220 and https://github.com/OWASP/ASVS/issues/222
