### ISSUE TITLE
Ambiguous requirement (section 2.1) 

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#152]
_Verify all pages and resources by default require authentication except those specifically intended to be public (Principle of complete mediation)._

Each control should be self contained. Where is "Principle of complete mediation" defined? I think this needs simplification.

**Comment by danielcuthbert** [comment]
agreed and this has been simplified in 3.1 to

Verify all pages and resources are protected by server-side authentication, except those specifically intended to be public.
