### ISSUE TITLE
Are 2.3.2  intended to be L2?

### ISSUE THREAD

**Issue by belalena** [OWASP/ASVS#1520]
[2.3.2]https://github.com/OWASP/ASVS/blob/master/5.0/en/0x11-V2-Authentication.md#v23-authenticator-lifecycle
Verify that enrollment and use of user-provided authentication devices are supported, such as a U2F or FIDO tokens.

In [#1013](https://github.com/OWASP/ASVS/issues/1013) 2.2.7. was deleted as it duplicated 2.3.2. But it was L3 and 2.3.2 is L2. Should it be changed to L3 only?

**Comment by tghosth** [comment]
I think further discussion is needed on that issue. I personally do think that at this point we should consider this an L2 requirement.
