### ISSUE TITLE
3.5.2 doesn't seem like it is in context

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1522]
3.5.2 sounds more like it should either:

1. Be in section [2.10](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x11-V2-Authentication.md#v210-service-authentication) where we discuss intra-service authentication 
2. It should be made more generic to be clear that this is a general guideline that temporary session tokens should be used after authentication and never a static identifier. 

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **[3.5.2](https://appsecg.host/3.5)** | [GRAMMAR] Verify that the application uses session tokens rather than static API secrets and keys, except with legacy implementations. | | ✓ | ✓ | 798 | |

History:

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **[3.5.2](https://github.com/OWASP/ASVS/blame/af06e16ed3612ed0da80b677bf3be04234a1d31c/4.0/en/0x12-V3-Session-management.md#L62)** | Verify the application uses session tokens rather than static API secrets and keys, except with legacy implementations. |  | ✓ | ✓ | - | 798 | tbd |
| **[3.5.2](https://github.com/OWASP/ASVS/blame/54629299a244ab712d44cc440800dbd7e8141f00/4.0/en/0x12-V3-Session-management.md#L61)** | Verify that single factor, static API secrets and keys are not used, except with legacy implementations. |  | ✓ | ✓ | - | 798 | tbd |
| **[3.3.1](https://github.com/OWASP/ASVS/blame/c0f9c295ea57ecfba848cfbdca850034825117f1/4.0/en/0x12-V3-Session-management.md)** | Verify single factor unchanging API secrets and keys are not used, except with legacy implementations. |  | ✓ | ✓ | 1.0 |

**Comment by jmanico** [comment]
I would just say:

_Verify that the application uses framework-specific session tokens or cryptographically signed  JSON Web Tokens for session management. Static API secrets and keys should be avoided._

**Comment by elarlang** [comment]
Probably we need to start from the question: what problem it addresses?

From the text I don't read it as machine-to-machine communication specific.

As a quick-fix I would get rid of phrase ", except with legacy implementations".

**Comment by Sjord** [comment]
It seems this section is for applications that authenticate with OpenID connect and supply a JWT to the user, instead of a random session cookie. I am not sure how "static API secrets and keys" can be an alternative to that, so in this context this requirement doesn't make sense to me.

For intra-service authentication, static API secrets and keys seem acceptable to me.

**Comment by tghosth** [comment]
Some more details:

History:

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **[3.5.2](https://github.com/OWASP/ASVS/blame/af06e16ed3612ed0da80b677bf3be04234a1d31c/4.0/en/0x12-V3-Session-management.md#L62)** | Verify the application uses session tokens rather than static API secrets and keys, except with legacy implementations. |  | ✓ | ✓ | - | 798 | tbd |
| **[3.5.2](https://github.com/OWASP/ASVS/blame/54629299a244ab712d44cc440800dbd7e8141f00/4.0/en/0x12-V3-Session-management.md#L61)** | Verify that single factor, static API secrets and keys are not used, except with legacy implementations. |  | ✓ | ✓ | - | 798 | tbd |
| **[3.3.1](https://github.com/OWASP/ASVS/blame/c0f9c295ea57ecfba848cfbdca850034825117f1/4.0/en/0x12-V3-Session-management.md)** | Verify single factor unchanging API secrets and keys are not used, except with legacy implementations. |  | ✓ | ✓ | 1.0 |

See also [2.10.1](https://github.com/OWASP/ASVS/blame/master/5.0/en/0x11-V2-Authentication.md#v210-service-authentication):

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.10.1** | Verify that intra-service secrets do not rely on unchanging credentials such as passwords, API keys or shared accounts with privileged access. | | ✓ | ✓ | 287 | |
| **[2.10.1](https://github.com/OWASP/ASVS/blame/90958ab0737f4a37e586d9fdc767ed47de107714/4.0/en/0x11-V2-Authentication.md)** | Verify that intra-service secrets do not rely on unchanging credentials such as passwords, API keys or shared accounts with privileged access. | | OS assisted | HSM | 287 | 5.1.1.1 |
| **[2.10.1](https://github.com/OWASP/ASVS/blame/57a0724d896408654e755f0a0d387e0d19ae3279/4.0/en/0x11-V2-Authentication.md)** | Verify that intra-service secrets do not rely on unchanging passwords, such as API keys or shared accounts with privileged access. |  | OS assisted | HSM | 287 | 5.1.1.1 |
| **[2.10.1](https://github.com/OWASP/ASVS/blame/49d63c54537dc02c154a7ff99101cea2525c59b3/4.0/en/0x11-V2-Authentication.md)** | Verify that integration secrets do not rely on unchanging passwords, such as API keys or shared privileged accounts. |  | OS assisted | HSM | 287 | 5.1.1.1 |
| **[2.11.1](https://github.com/OWASP/ASVS/blame/4bdb7500839b9ca88c2165c1cafa69a2ff7bf16d/4.0/en/0x11-V2-Authentication.md)** | Verify that integration secrets do not rely on unchanging passwords, such as API keys or shared privileged accounts. | Software | OS assisted | HSM | 5.1.1.1 |
| **[2.11.1](https://github.com/OWASP/ASVS/blame/ff6ae74f7f411bfb43af5bc9c25e7929a1ea05dc/4.0/en/0x11-V2-Authentication.md)** | Integration secrets SHOULD NOT rely on unchanging passwords, such as API keys or shared privileged accounts. | Software | OS assisted | HSM | 5.1.1.1 |
| **[2.11.1](https://github.com/OWASP/ASVS/blame/72640d48efacdb2902eba5494b9d50a3e733cac2/4.0/en/0x11-V2-Authentication.md)** | Integration secrets SHOULD NOT rely on unchanging passwords, such as API keys or shared privileged accounts. If passwords are required, the credential should not be a default account and stored with sufficient protection to prevent offline recovery attacks, including local system access. | Software | OS assisted | HSM | 5.1.1.1 |
| [2.11.1](https://github.com/OWASP/ASVS/blame/9ace43e4e8b9b980e3d526cfda5b1bbd8a09e46e/4.0/en/0x11-V2-Authentication.md) | Integration secrets SHOULD NOT rely on unchanging passwords, such as API keys or shared privileged accounts. If passwords are required, the credential should not be a default account, and stored with sufficient protection to prevent offline recovery attacks, including local system access. | Software | OS assisted | HSM | 5.1.1.1 |
| **[2.21](https://github.com/OWASP/ASVS/blame/134fc631f173d0abd1da60ec9937fc1a866d1baa/4.0/en/0x11-V2-Authentication.md)** | Integration secrets SHOULD NOT rely on unchanging memorized secrets, such as API keys or shared privileged accounts. If memorized secrets are required, the credential should not be a default account, and stored with sufficient protection to prevent offline recovery attacks, including local system access. | Software | OS assisted | HSM | 5.1.1.1 |
| **[2.21](https://github.com/OWASP/ASVS/blame/c6e18819a32160932b94ad5e9715a667ea1818db/4.0/en/0x11-V2-Authentication.md#L65)** | Integration  secrets SHOULD NOT rely on unchanging memorized secrets, such as API keys or shared privileged accounts. If memorized secrets are required, the credential should not be a default account, and stored with sufficient protection to prevent offline recovery attacks, including local system access. | Software | OS assisted | HSM | 5.1.1.1 |
| **[2.21](https://github.com/OWASP/ASVS/blame/e5a2e56993c560c51a16d4c93b05d557530cab2b/4.0/en/0x11-V2-Authentication.md#L34)** | Integration memorized secrets SHOULD NOT rely on unchanging memorized secrets, such as API keys or shared privileged accounts. If memorized secrets are required, the credential should not be a default account, and stored with sufficient protection to prevent offline recovery attacks, including local system access. | Software | OS assisted | HSM | 4.0 | 5.1.1.1 |

From [Andrew's deck](https://appsecg.host/asvsdeck#86): 
![image](https://github.com/OWASP/ASVS/assets/13623828/36d5d756-e160-4913-b1ce-a72640f38004)


From [Andrew's deck](https://appsecg.host/asvsdeck#102): 
![image](https://github.com/OWASP/ASVS/assets/13623828/dea84195-262e-422e-947a-27a89ed52211)

**Comment by tghosth** [comment]
There has been discussion of 2.10.1 at #1032

**Comment by tghosth** [comment]
> 3.5.2 sounds more like it should either:
> 
> 1. Be in section [2.10](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x11-V2-Authentication.md#v210-service-authentication) where we discuss intra-service authentication 
> 2. It should be made more generic to be clear that this is a general guideline that temporary session tokens should be used after authentication and never a static identifier. 

I am leaning towards option 2 here. 2.10.1 seems like it is going to change slightly anyway. The [history of 3.5.2](https://github.com/OWASP/ASVS/issues/1522#issuecomment-1559058887) is a bit weird but I think the idea is partially covered by 2.10.1 and the rest is kind of a generic basis for session management.

**Comment by elarlang** [comment]
After reading it again, I still have the same question: what problem it solves?

**Comment by tghosth** [comment]
I think the problem it solves is that we don't have a basic level requirement which says, use session tokens not fixed values which I think is why Jim came up with:

> Verify that the application uses framework-specific session tokens or cryptographically signed JSON Web Tokens for session management. Static API secrets and keys should be avoided.

**Comment by elarlang** [comment]
Is the context here machine-to-machine integrations or it covers all "usual" end-users with their browsers as well? If it is machine to machine, How it's different from current 2.10.1?

At the moment the requirement is in "Token based session management", but I can not read this category out from the requirement text.

What is "framework-specific" session token?

**Comment by tghosth** [comment]
> Is the context here machine-to-machine integrations or it covers all "usual" end-users with their browsers as well? If it is machine to machine, How it's different from current 2.10.1?

I think we are talking about usual end users here and that service to service is something else handled in 2.10.1.

> What is "framework-specific" session token?

This is a good question and I think actually we should be more consistent with the wording we are using in 3.2 so I would propose the following:

## V3.1 Fundamental Session Management Security

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **3.1.3** | [ADDED] Verify that the application uses opaque or cryptographically signed tokens for session management. Static API secrets and keys should be avoided. | ✓ | ✓ | ✓ | | |

**Comment by tghosth** [comment]
@elarlang do you approve this wording?

**Comment by elarlang** [comment]
We already have those requirements:
| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **3.2.2** | [MODIFIED] Verify that opaque session tokens possess at least 128 bits of entropy. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | ✓ | ✓ | ✓ | 331 | 7.1 |
| **3.2.4** | [MODIFIED] Verify that opaque session tokens are generated using a secure random function. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 330 | 7.1 |
| **3.5.2** | [GRAMMAR] Verify that the application uses session tokens rather than static API secrets and keys, except with legacy implementations. | | ✓ | ✓ | 798 | |

Why we need proposed 3.1.3? Feels like some overlapping.

**Comment by tghosth** [comment]
Ah yeah, I think it is intended to replace 3.5.2 with a generic requirement for the need for session management so it should be this:

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **3.1.3** | [MOVED FROM 3.5.2, MODIFIED] Verify that the application uses opaque or cryptographically signed tokens for session management. Static API secrets and keys should be avoided. | ✓ | ✓ | ✓ | | |

@elarlang

**Comment by elarlang** [comment]
Maybe some duplication with "session tokens"
_Verify that the application uses opaque **session tokens** or cryptographically signed tokens for session management. Static API secrets and keys should be avoided._

Otherwise (I personally) may read it like:
_Verify that the application uses ( opaque OR cryptographically ) signed tokens for session management. Static API secrets and keys should be avoided._

... and it rises the question - why we need to sign opaque tokens,

**Comment by tghosth** [comment]
Fair point, how about this @elarlang:


| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **3.1.3** | [MOVED FROM 3.5.2, MODIFIED] Verify that the application uses either **cryptographically signed or opaque tokens** for session management. Static API secrets and keys should be avoided. | ✓ | ✓ | ✓ | | |

**Comment by elarlang** [comment]
ok with text. no CWE?

**Comment by tghosth** [comment]
I cannot find a good CWE match so I would rather just get this in for now.

**Comment by tghosth** [comment]
Although actually 3.5.2 originally had CWE-798 which is not ideal but it is something.

**Comment by tghosth** [comment]
Opened #1743 to resolve

**Comment by craig-shony** [comment]
Sorry to rehash this, but I think the original concern was that "Static API secrets and keys should be avoided." would get interpreted as almost a stand alone statement. I think this is a valid concern as while reading this, though I did eventually lean toward "this only applies to client-side sessions", there was some thought of whether or not ASVS was wanting me to ditch static API secrets m2m.

**Comment by tghosth** [comment]
@elarlang what do you think>

**Comment by Sjord** [comment]
> ASVS was wanting me to ditch static API secrets m2m.

There is more discussion about this in [2.10.1 Verify that intra-service secrets do not rely on unchanging credentials such as passwords, API keys · Issue #1032 · OWASP/ASVS](https://github.com/OWASP/ASVS/issues/1032).

**Comment by tghosth** [comment]
@set-reminder 10 minutes Josh to look at this one

**Comment by tghosth** [comment]
Hi @craig-shony, I agree with @Sjord that the best place to discuss this would be in #1032 where I think we are already deep into this discussion :)

If you don't agree, tag me with some reasoning and I can reopen this
