### ISSUE TITLE
Don't see the point of 4.1.2

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1524]
This requirement seems to have come through entirely unchanged from at least ASVS 3.1 if not earlier.

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **4.1.2** | Verify that all user and data attributes and policy information used by access controls cannot be manipulated by end users unless specifically authorized. | ✓ | ✓ | ✓ | 639 |

My guess here is that it is refering to ensuring that data used to make access control decisions cannot be manipulated by an unauthorized user. 

My thoughts:
a) I don't see a way of making this specifically actionable
b) I think it should be included in the general access control point. Maybe as a bullet point in wider Access Control documentation which should be in V1 anyway.

As such, I think it should be merged into another requirement.

(this would need to be part of #1352)

The CWE is IDOR so not super related either

**Comment by Sjord** [comment]
> My guess here is that it is refering to ensuring that data used to make access control decisions cannot be manipulated by an unauthorized user.


I agree, I think I used this once or twice for a vulnerability where there is an IP allowlist, and the IP address can be spoofed with a X-Forwarded-For request header. So in that case, information used by access controls could be manipulated.

A simpler variant would be setting 'isAdmin=1' somewhere, and gaining administrator privileges.

> I don't see a way of making this specifically actionable

I agree. "cannot be manipulated" is pretty non-specific. Perhaps saying that user input should not be used in security decisions is already more specific.

**Comment by Sjord** [comment]
4.1.1 also says that access control shouldn't rely on user input:

> 4.1.1 Verify that the application enforces access control rules at a trusted service layer and doesn't rely on controls which an untrusted user could manipulate such as client-side JavaScript.

**Comment by elarlang** [comment]
If no one can figure out what is the point of the requirement, it's safe to just remove it.

**Comment by tghosth** [comment]
> Can this be traced back with `git blame` or not?

As I said above "This requirement seems to have come through entirely unchanged from at least ASVS 3.1 if not earlier." This means it predates git blame @cmlh

**Comment by tghosth** [comment]
I found this other explanation elsewhere but I still think it does not add anything useful so have proposed deletion in #1646

![image](https://github.com/OWASP/ASVS/assets/13623828/786de1bc-dbb8-4a12-aeea-26c4405fe913)

**Comment by jmanico** [comment]
I think this is a critical requirement for access control architects and designers. I like it.

**Comment by elarlang** [comment]
@jmanico - It's.. I don't know what if issue is opened forever and you found it useful 8min after it got deleted :)

To bring it back, can you please provide please provide arguments why it's useful and what problem it solves (and what is not already covered by other requirements)?

**Comment by jmanico** [comment]
You’re welcome Elar.

Developers often need to build complicated access control by themselves for big enterprise systems. Several of these systems that I built for large banks, etc, required extensive live policy editing capability. And one of our most critical requirements was thst access control policy metadata needed to be tightly controlled.

So while this may not seem like a big requirement for testers, it’s a critical one for architects of access control systems.

**Comment by tghosth** [comment]
@jmanico 

I just don't understand what it adds. To me it says, make sure that only people who are authorized can edit access control configurations.

To me that is the same as saying to make sure that only people who are authorized can edit any data. 

Are you able to articulate what the difference here is and how this should be tested differently from general authorization in the application?

**Comment by jmanico** [comment]
Yes, I would review systems that provide customizable access control solutions and make sure that only admin's or similar can edit access control policy data.

This is a very specific and important requirement for SaaS. This is *loosely* covered by other requirements.

However, we already have a very weak access control set of requirements and this will help provide guidance to those building more extensive access control layers from scratch, which is becoming the norm.

**Comment by tghosth** [comment]
So @jmanico would you say something like:

> **4.1.2** If this application provides a customizable access control solution, verify that only administrators or other specifically authorized users can edit access control policy data.

**Comment by jmanico** [comment]
Not all policy data comes from custom solutions, plenty of add-ons, frameworks like cancan and similar also have this requirement. It’s a core part of ABAC like solutions.

**Comment by tghosth** [comment]
I'm going to punt this to the rework stage as I am not sure what to do with it for now.

**Comment by tghosth** [comment]
@jmanico is there any way you could rephrase it as I am not really sure I understand it...

(I have raised #1694 to revert the deletion for now)

**Comment by jmanico** [comment]
Perhaps:

Verify that end users cannot manipulate access control policy information used in access controls (such as a user's role, or the access control level of a certain feature), unless granted explicit authorization to do so.

**Comment by elarlang** [comment]
> Perhaps:
> 
> Verify that end users cannot manipulate access control policy information used in access controls (such as a user's role, or the access control level of a certain feature), unless granted explicit authorization to do so.

This rises same questions like Josh wrote here: https://github.com/OWASP/ASVS/issues/1524#issuecomment-1576895079

**Comment by jmanico** [comment]
The requirement addresses a critical aspect of application security: access control. Specifically, it targets the integrity of access control metadata, like user roles, permissions, or feature-level access settings. We want to ensure that end users can't tinker with these settings unless explicitly allowed.

So, here's the requirement, expanded and with a bit more technical meat on the bones:

"Verify that end users are restricted from altering, injecting, or manipulating any form of access control policy information, such as user roles, permissions, and feature access levels, unless they are explicitly authorized to make such changes. Implement strict server-side validation and access checks to guard against unauthorized modification of critical access control data. Employ cryptographic controls where necessary to secure the integrity of access control metadata in transit and at rest."

#ThankYouChatGPT

**Comment by elarlang** [comment]
I still think the original comment is valid: https://github.com/OWASP/ASVS/issues/1524#issuecomment-1576895079

**Comment by jmanico** [comment]
I have very deep expertise in this area. I have built many access control systems for large banks and similar ones. This is a significant problem and I please ask you @tghosth and @elarlang to reconsider based on my significant experience as an enterprise developer who has built many access control systems for large companies. Please. I often trust you in areas I am not an expert in, and I ask you to trust me when it comes to this one.

**Comment by tghosth** [comment]
Ok so maybe rewording like his:

> Verify that specific controls exist to prevent end users making changes to access control policy information, such as user roles, permissions, and feature access levels, unless they are explicitly authorized to do so.

What do you think @jmanico ?

**Comment by jmanico** [comment]
Small change for grammar:

_Verify that specific controls exist to prevent end users **from** making changes to access control policy information, such as user roles, permissions, and feature access levels, unless they are explicitly authorized to do so._

**Comment by tghosth** [comment]
Ok so I opened #1713 with that clarification
