### ISSUE TITLE
What is the practical difference between 14.1.1 and 14.1.4

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1527]
### History of 14.1.1

| # | Description | L1 | L2 | L3 | CWE |
| --- | --- | --- | --- | -- | -- |
| **14.1.1** | **Verify that the application build and deployment processes are performed in a secure and repeatable way, such as CI / CD automation, automated configuration management, and automated deployment scripts.** | | ✓ | ✓ | |
| **19.5** | Verify that the application build and deployment processes are performed in a secure and repeatable way, such as CI / CD automation and automated configuration management.  |  | ✓ | ✓ |  |

### History of 14.1.4

| # | Description | L1 | L2 | L3 | CWE |
| --- | --- | --- | --- | -- | -- |
| **14.1.4** | **Verify that the application, configuration, and all dependencies can be re-deployed using automated deployment scripts, built from a documented and tested runbook in a reasonable time, or restored from backups in a timely fashion.** | | ✓ | ✓ | |
| **[14.5.2](https://github.com/OWASP/ASVS/blame/ee289296aab67ca7ba31eb1d3efe85b547de36db/4.0/en/0x22-V14-Config.md)** | Verify that either the system can be automatically re-deployed using software-defined deployment scripts or that regular backups of all configuration files and other custom components are performed and that the application can be restored to a functional state. | | ✓ | ✓ | |
| **[14.5.2](https://github.com/OWASP/ASVS/commit/408c62560d08045e49693ead1f31b6ea7dd56717)** | Verify that regular backups of all configuration files and other custom components are performed and that the application can be restored to a previous working state from that backup. | | ✓ | ✓ | tbd |
| **[19.5.4](https://github.com/OWASP/ASVS/commit/55302d35c7a5e318f090fddaf276b51d7130ce6d)** | Verify that regular backups of all customer data, configuration files and other custom components are performed and that the application can be restored to a previous working state from that backup. | ✓ | ✓ | ✓ |  |  |

(19.5.4 originally added in #363)

### My comments

Looks like the 14.1.4 requirement was originally about backups and then modified to also talk about scripts later. 

In #1462 we established that backups are out of scope for ASVS.

I do not believe that there is anything in 14.1.4 which is not covered by 14.1.1 so I would support simply **deleting** 14.1.4.

Any objections/thoughts?

**Comment by tghosth** [comment]
@elarlang @jmanico @danielcuthbert what do you think?

**Comment by tghosth** [comment]
@moshe-apiiro I know you spent a while looking at this section so I would welcome your opinion as well

**Comment by elarlang** [comment]
Add to the mix 1.14.4:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.14.4** | Verify that the build pipeline contains a build step to automatically build and verify the secure deployment of the application, particularly if the application infrastructure is software defined, such as cloud environment build scripts. | | ✓ | ✓ | |


In a way related:
https://github.com/OWASP/ASVS/issues/1405

**Comment by tghosth** [comment]
1.14.4 is relevant, #1405 I believe is something else

**Comment by moshe-apiiro** [comment]
The nuance I see here is that 14.1.1 has both **build and deployments** stated and 14.1.4 has its focus on **deployment alone**. Given that - there is a need for both but maybe we can distinguish the two phases better if that makes more sense. wdys @tghosth ?

**Comment by moshe-apiiro** [comment]
On second thought, maybe too obvious to note but I think worth mentioning is the fact that one can be seen as 'having an automated process' and the other is more regarding a documented runbook and its practical testing of one, but maybe it should be pronounced better.

**Comment by elarlang** [comment]
Secure build pipeline is really important, but...

from ASVS perspective - ASVS is Application Security Verification Standard. Now the question is - is build pipeline part of the application or just a tool, to create/build the application. In other words - this is scope question and deployment or pipeline requirements are not that clearly in the scope of ASVS.

**Comment by tghosth** [comment]
> 1.14.4 is relevant...

#1245 proposes to delete 1.14.4



14.1.4 originates in backups which is considered out of scope for ASVS as per #1462.

As such, I think this strengthens my opinion that we should **delete** 14.1.4.

@jmanico @elarlang any other opinions?

**Comment by jmanico** [comment]
I agree build pipeline is out of scope, for this ASVS, but I vote for a DevOpsASVS some day :)

**Comment by tghosth** [comment]
Ok great, I opened #1648 to address this.
