### ISSUE TITLE
14.5.1 blocking unused HTTP methods

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1528]
14.5.1 currently reads as follows:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **14.5.1** | [MODIFIED] Verify that the application server only accepts HTTP methods (including OPTIONS during preflight requests) in use by the application or by the API. | ✓ | ✓ | ✓ | 749 |

It went through a bunch of iterations but the original was like this (i.e. pretty similar):

| # | Description | L1 | L2 | L3 | Since |
| --- | --- | --- | --- | -- | -- |
| **11.1** | Verify that the application server accepts the HTTP methods in use by the application or API, including pre-flight OPTIONS. | ✓ | ✓ | ✓ | 1.0 |

How important is this requirement? It seems to be annoying to implement and not really impactful. I would suggest either making this L3 or deleting it.

Any thoughts @jmanico @danielcuthbert @elarlang

**Comment by elarlang** [comment]
Is it better when we use "application" instead of "application server"? The point is - application should not execute functionality with GET method HTTP request when it's meant to be executed only with POST method HTTP request.

**Comment by tghosth** [comment]
@jmanico would like your thoughts as well though so I will mark as draft for now.

**Comment by jmanico** [comment]
Apps are so fuzzy and distributed these days I like application better than application server! Just my 2 cents but I think either way is ok.

**Comment by tghosth** [comment]
@jmanico the proposal is to **delete** the requirement as low impact. It currently reads:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **14.5.1** | [MODIFIED] Verify that the application server only accepts HTTP methods (including OPTIONS during preflight requests) in use by the application or by the API. | ✓ | ✓ | ✓ | 749 |


Note that we already have a separate requirement:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **[14.5.5](https://appsecg.host/14.5)** | [MODIFIED, MOVED FROM 13.2.1] Verify that HTTP requests using the HEAD, OPTIONS, TRACE or GET verb do not modify any backend data structure or perform any state-changing actions. These requests are safe methods and should therefore not have any side effects. | ✓ | ✓ | ✓ | 650 |

**Comment by jmanico** [comment]
I am ok to leave 14.5.1 in after another review. It's meaningful.

**Comment by tghosth** [comment]
@elarlang I don't think TRACE is really important enough anymore to worry about, what do you think?

**Comment by elarlang** [comment]
> @elarlang I don't think TRACE is really important enough anymore to worry about, what do you think?

maybe you think only XST vector? From browsers you can not do TRACE methods request and this vector is gone.

As unintended security disclosure, HTTP request with TRACE method may leak extra headers added by WAF, load balancer or some other component before application and from HTTP response with TRACE method request you can read it out. So I think it's still valid and should be covered.

**Comment by tghosth** [comment]
@elarlang ok I am prepared to accept that, are you ok with the updated wording in #1628 ?

**Comment by elarlang** [comment]
Maybe it make sense to mention the TRACE method like it was in v3.0.1? Then it makes the requirement more clear I think.

Unnecessary space before dot as well.

**Comment by tghosth** [comment]
Ok so how about now?
