### ISSUE TITLE
Section 2.8 can be simplified

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#153]
Current: 
_Verify all account identity authentication functions (such as update profile, forgot password, disabled / lost token, help desk or IVR) that might regain access to the account are at least as resistant to attack as the primary authentication mechanism._

Suggested:
Verify all identity functions (e.g. forgot password, change password, change email, manage 2FA token, etc.) have the security controls, as the primary authentication mechanism (e.g. login form).

**Comment by danielcuthbert** [comment]
amended and simplified in 3.1
