### ISSUE TITLE
Is 1.14.2 relevant to a web standard

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1530]
### History

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---:| :---: | :---: |
| **1.14.2** | **Verify that binary signatures, trusted connections, and verified endpoints are used to deploy binaries to remote devices.** | | ✓ | ✓ | 494 |
| **[1.14.3](https://github.com/OWASP/ASVS/blame/b262352f7e0857677274ca1e35c8d74c29102c34/4.0/en/0x10-V1-Architecture.md)** | Verify that if deploying binaries to untrusted devices makes use of binary signatures, trusted connections, and verified endpoints. | | ✓ | ✓ | 494 |
| **[1.14.2](https://github.com/OWASP/ASVS/blame/9f229df4e92f0976d6dac30a5610d132a763c64f/4.0/en/0x10-V1-Architecture.md#L106)** | Verify that deploying binaries to untrusted devices makes use of binary signatures, trusted connections, and verified endpoints. | | ✓ | ✓ | 494 |
| **[1.19.2](https://github.com/OWASP/ASVS/blame/89ee514bdd4d95c41393f3b3146482078577a5cb/4.0/en/0x10-V1-Architecture.md#L99)** | Verify that if binaries are delivered to untrusted devices, ensure that an secure automatic updating mechanism is present in the architecture which ensures that only signed binaries are downloaded from trusted sites over a secure connection. | | ✓ | ✓ | tbd | 
| **[1.10](https://github.com/OWASP/ASVS/blame/9a1742826751cad4a21d0725801c912e546f5cfb/4.0/en/0x10-V1-Architecture.md#L97)** | Verify that if binaries are delivered to untrusted devices, ensure that an secure automatic updating mechanism is present in the architecture that ensures only signed binaries are downloaded from trusted sites over a secure connection. | | ✓ | ✓ | tbd |

Looks like 1.10 was added here as part of a larger re-write: https://github.com/OWASP/ASVS/commit/2e5616340ef2c9eb8c8895721f944398850508b9

### Background to non-web requirements

In previous discussion of what is in scope for ASVS in #803:

> I still think we need to drop desktop requirement and move those to MASVS where they are more appropriate.

@jmanico wrote [here](https://github.com/OWASP/ASVS/issues/803#issuecomment-797765489).

> I agree with this stance. If we are talking about Electron-based apps (JavaScript) then we could support it but then it becomes a slippery slope. I can't see this working out the way many would like it to

@danielcuthbert wrote [just below that](https://github.com/OWASP/ASVS/issues/803#issuecomment-800089269).

### Proposal

This requirement has been through a journey but it feels like it is not very relevant to web apps. It sounds very connected to desktop apps and therefore not in scope.

I propose deleting the requirement.

**Comment by elarlang** [comment]
For me it seems out of scope also from "application" vs "deploy process" perspective.
