### ISSUE TITLE
1.14.5 needs to be rewritten

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1531]
### History

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---:| :---: | :---: |
| **1.14.5** | Verify that application deployments adequately sandbox, containerize and/or isolate at the network level to delay and deter attackers from attacking other applications, especially when they are performing sensitive or dangerous actions such as deserialization. ([C5](https://www.owasp.org/index.php/OWASP_Proactive_Controls#tab=Formal_Numbering)) | | ✓ | ✓ | 265 |
| **1.19.5** | Verify that application deployments are adequately sandboxed, containerized and/or isolated at the network level to delay and deter attackers from attacking other applications, especially when they are performing sensitive or dangerous actions such as deserialization. | ✓ | ✓ | ✓ | 265 | tbd |
| **19.1.2** | Verify application deployments are adequately sandboxed, containerized and/or isolated at the network level to delay and deter attackers from attacking other applications, especially when they are performing sensitive or dangerous actions such as deserialization. | ✓ | ✓ | ✓ | 265 | tbd |
| **19.1.2** | Verify application deployments are adequately sandboxed, containerized or isolated to delay and deter attackers from attacking other applications. | ✓ | ✓ | ✓ | 265 |

(original item came from ASVS 3.0)

### Proposal

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---:| :---: | :---: |
| **1.14.5** | [MODIFIED, LEVEL L2 > L3] Verify that the application architecture uses techniques such as sandboxing, containerization or network level isolation to delay and deter attackers from attacking other parts of the application, especially when the application is performing sensitive or dangerous actions such as deserialization. ([C5](https://www.owasp.org/index.php/OWASP_Proactive_Controls#tab=Formal_Numbering)) | | | ✓ | 265 |

**Comment by tghosth** [comment]
Moving this to rework because it is going to depend on the plan for V1

**Comment by tghosth** [comment]
@elarlang what do you think about this? I could move it to V14 although it does not quite fit...

**Comment by elarlang** [comment]
We have also other architecture decisions towards how to organize or use/place components safely, although those are dependency related:
* 14.2.6
* 14.2.7
* 14.2.8

One option is to create one chapter to V10 (need to rename and redescrribe the V10 for that)

**Comment by tghosth** [comment]
So 1.14.5 is not just about 3rd party components but general dangerous stuff and general segmentation.

It would seem to be a true architecture requirement but I am not sure whether it is specific enough to really be enforceable. It is also a little abstracted from the code which is why I prefer V14 to V10.
