### ISSUE TITLE
General wording - requesting prove of the negative

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#154]
Most control are written in a way, where they are asking the security reviewer to prove the negative.

For example:    
_Verify that the application is not susceptible to LDAP Injection, or that security controls prevent LDAP Injection._

It cannot be verified that the application is not vulnerable to something. It can only be stated that the application has been tested for... Not that it has no vulnerabilities. 

Suggested change to something similar to:
Verify that the application has been tested for LDAP Injection vulnerabilities, or that specific security controls to prevent LDAP Injection have been implemented.

This is a common issue across all controls.

**Comment by vanderaj** [comment]
This is an enhancement that we need to apply to all controls, so I'm going to make this is into an "Enhancement" and re-write the title a little.

**Comment by jmanico** [comment]
This is largely the case for the current work. If we see issues that are NOT based please re-open an issue on that item (or fix!)

**Comment by jmanico** [comment]
I made several changes removing "nots" here a5b57af

**Comment by jmanico** [comment]
more note removal a8f6467

**Comment by jmanico** [comment]
more not removal
