### ISSUE TITLE
1.1.4 and 1.1.5 are just threat modeling 

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1541]
It looks to me that 1.1.4 and 1.1.5 and not necessary and can be deleted. We already cover threat modeling in 1.1.2

1.1.2 | Verify the use of threat modeling for every design change or sprint planning to identify threats, plan for countermeasures, facilitate appropriate risk responses, and guide security testing. |   | ✓ | ✓ | 1053
-- | -- | -- | -- | -- | --

And here is the current status of 1.1.4 and 1.1.5

1.1.4 | Verify documentation and justification of all the application's trust boundaries, components, and significant data flows. |   | ✓ | ✓ | 1059
-- | -- | -- | -- | -- | --
1.1.5 | Verify definition and security analysis of the application's high-level architecture and all connected remote services. (C1) |   | ✓ | ✓ | 1059

1.1.4	Verify documentation and justification of all the application's trust boundaries, components, and significant data flows.		✓	✓	1059
1.1.5	Verify definition and security analysis of the application's high-level architecture and all connected remote services. ([C1](https://owasp.org/www-project-proactive-controls/#div-numbering))		✓	✓	1059

**Comment by tghosth** [comment]
Dropping this into the V1 rework bucket

**Comment by elarlang** [comment]
I think 1.1.2 is just TM process and will be removed (or modified) by #1227.

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.1.4** | Verify documentation and justification of all the application's trust boundaries, components, and significant data flows. | | ✓ | ✓ | 1059 |
| **1.1.5** | Verify definition and security analysis of the application's high-level architecture and all connected remote services. ([C1](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 1059 |

[CWE-1059](https://cwe.mitre.org/data/definitions/1059.html) for both is "CWE-1059: Insufficient Technical Documentation"

So the goal here should be: to analyze, are those mentioned and previously required documentation required as pre-conditions for implementing and testing some other section or requirement in ASVS.

If not, we can just delete the requirement as out of scope.

If it is, then we can modify it to be more clear of the expected outcome and move to a more precise section.

Personally, I can not find any good and quick match for 1.1.4.

For 1.1.5 "for connected remote services" I have proposed to have a separate documentation requirement in #1541. Maybe we can handle those together. "application's high-level architecture" part probably is also required...

**Comment by tghosth** [comment]
Recommend merging to:

> Verify that an architecture document exists which demonstrates the application's components, trust boundary assumptions, significant data flows, and remote 3rd party services which it relies upon.

**Comment by jmanico** [comment]
Bump, lets delete these 💪

**Comment by tghosth** [comment]
Opened #1862 to resolve

**Comment by tghosth** [comment]
Changed my mind becaue we also have

**Comment by tghosth** [comment]
This is why the "rework" category exists so that we can consider a chapter as a whole rather than making a change and then discovering we need to make another change 🙃

**Comment by elarlang** [comment]
> Verify that an architecture document exists which demonstrates the application's components, trust boundary assumptions, significant data flows, and remote 3rd party services which it relies upon.

In practice, it is something you need to do, but for ASVS - what is the expected outcome for this requirement for the verification? For me it is not clear, what I should do with this requirement as a pen-tester.

**Comment by csfreak92** [comment]
> > Verify that an architecture document exists which demonstrates the application's components, trust boundary assumptions, significant data flows, and remote 3rd party services which it relies upon.
> 
> In practice, it is something you need to do, but for ASVS - what is the expected outcome for this requirement for the verification? For me it is not clear, what I should do with this requirement as a pen-tester.

While I agree with Elar's point mostly, I do think the usual solution is either a security architecture document or in many cases an application diagram that clearly shows the different components would suffice to verify this.

**Comment by elarlang** [comment]
1.1.5 part "Verify definition ~~and security analysis of the application's high-level architecture and~~ all connected remote services.	" can be documentation requirement for V13 API and Web Service or also for V14 Configuration.

**Comment by elarlang** [comment]
ping @tghosth , please re-check the issue and what is your vision or idea with this now. I think we have a bit more clear scope and understanding, what kind of requirements we want to the ASVS.

The "need for external communications" documentation requirement should be viewed separately via #993, so mainly we should analyze, what we need from 1.1.4 and the first part of 1.1.5 as already pointed out in https://github.com/OWASP/ASVS/issues/1541#issuecomment-1843182931

**Comment by tghosth** [comment]
1.1.5 is being handled elsewhere, I don't think that 1.1.4 satisfies the "without it your app is insecure" test.

**Comment by elarlang** [comment]
So the proposal is to delete 1.1.4 as out of scope, pure documentation requirement without a clear security decision to provide as a pre-condition for other requirements.

**Comment by jmanico** [comment]
I agree on deleting 1.1.4 per the OP.
