### ISSUE TITLE
Expand 1.6.3

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1544]
With the upcoming quantum computing horizon coming up (2030) i think it's REALLY important for developers to achieve "cryptographic agility". So perhaps augment the current 1.6.3:

1.6.3 | Verify that all keys and passwords are replaceable and are part of a well-defined process to re-encrypt sensitive data. |   | ✓ | ✓ | 320
-- | -- | -- | -- | -- | --

...to include even more...

1.6.3 | Verify that all keys, passwords, cryptographic algorithms, key/secret vaults and other cryptographic components are replaceable and are part of a well-defined process to re-encrypt sensitive data. |   | ✓ | ✓ | 320
-- | -- | -- | -- | -- | --

#cryptographicAgility

**Comment by tghosth** [comment]
We talk about this elsewhere in the standard. I agree with the concept but we need to investigate whether we need to do deduplication. I'll add this to my todo list...

**Comment by danielcuthbert** [comment]
Added in 5.0 under V6.9 Post-Quantum Cryptography (PQC) and more specifically

6.9.2 	[ADDED] Verify that cryptographic systems are designed to allow for seamless upgrades to post-quantum cryptography, enabling the transition once PQC standards are fully established.

I don't feel we need this in 1.6.3 too so my approach would be to keep it as 6.9.2 and remove it from 1.6.3
