### ISSUE TITLE
1.6.4 grammar police strikes again

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1545]
1.6.4 is still using bad grammar

1.6.4 | [GRAMMAR] Verify that the architecture treats client-side secrets - such as symmetric keys, passwords, or API tokens - as insecure and never uses them to protect or access sensitive data.
-- | --

possible fix (drop the dashes please):

1.6.4 | [GRAMMAR] Verify that the architecture treats client-side secrets such as symmetric keys, passwords, or API tokens as insecure and never uses them to protect or access sensitive data.
-- | --

**Comment by tghosth** [comment]
@jmanico what do you think about:

1.6.4 | [GRAMMAR] Verify that the architecture treats client-side secrets, (such as symmetric keys, passwords, or API tokens,) as insecure and never uses them to protect or access sensitive data.
-- | --

**Comment by elarlang** [comment]
Can you give an example, where this mistake can happen or how it is important?

**Comment by jmanico** [comment]
I am not debating the validity of the requirement, I am concerned that this existing requirement has bad grammar. That's it! If you want to discuss the details I suggest you open a new issue.

**Comment by tghosth** [comment]
Opened a PR to fix grammar
