### ISSUE TITLE
1.5.1 and 1.8.1 overlap

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1546]
It looks to me that 1.5.1 and 1.8.1 overlap in terms in "policy compliance" a little. Looks odd to me.

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.5.1** | Verify that input and output requirements clearly define how to handle and process data based on type, content, and applicable laws, regulations, and other policy compliance. | | ✓ | ✓ | 1029 |
| **1.8.1** | [MODIFIED, MERGED FROM 8.3.4, LEVEL L2 > L1] Verify that all sensitive data created and processed by the application has been identified and classified into protection levels, and ensure that a policy is in place on how to deal with sensitive data. | ✓ | ✓ | ✓ | 213 |

**Comment by tghosth** [comment]
Looks like this will be handled in #1552 so I am going to close this for now,.

**Comment by elarlang** [comment]
I re-open the issue to handle overlapping parts separately.

I propose we leave 1.8.1 as it is and remove the policy and sensitive information part from 1.5.1 (as it should only address that the content is in the expected format).

Both requirements may need some additional modifications, but let's handle those case by case.

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.5.1** | [MODIFIED, LEVEL L2 > L1] Verify that input and output requirements clearly define how to handle and process data based on type and content. | ✓ | ✓ | ✓ | 1029 |

**Comment by tghosth** [comment]
Makes sense to me although I am not sure what output requirements are...

**Comment by elarlang** [comment]
> Makes sense to me although I am not sure what output requirements are...

What comes to my mind is, "Should the data be displayed as text or as HTML content", should URL, email address, and phone number be displayed as text or as link?

As you did not understand it and we may interpret it differently, it indicates that it must be changed and clarified. If we can not solve it immediately, I prefer to get this change in and we can finetune the requirement in another issue.

**Comment by tghosth** [comment]
Ok so open a PR
