### ISSUE TITLE
Change level of 1.9.1 to level 1

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1547]
Always using TLS is straight-forward these days and insecure comms should never me allowed. Suggest changing this:

1.9.1 | Verify the application encrypts communications between components, particularly when these components are in different containers, systems, sites, or cloud providers. (C3) |   | ✓ | ✓ | 319
-- | -- | -- | -- | -- | --

to this:

1.9.1 | Verify the application encrypts communications between components, particularly when these components are in different containers, systems, sites, or cloud providers. (C3) | ✓ | ✓ | ✓ | 319
-- | -- | -- | -- | -- | --

**Comment by elarlang** [comment]
probably it makes sense to handle proposals in #1443

**Comment by tghosth** [comment]
Agree, let's close this and centralize in #1443
