### ISSUE TITLE
1.9.2 seems overly agressive

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1548]
1.9.2 seems to endorse mTLS everywhere, this seems overly aggressive.

1.9.2 | Verify that application components verify the authenticity of each side in a communication link to prevent person-in-the-middle attacks. For example, application components should validate TLS certificates and chains. |   | ✓ | ✓ | 295
-- | -- | -- | -- | -- | --

**Comment by elarlang** [comment]
probably it makes sense to handle proposals in #1443

**Comment by tghosth** [comment]
Agree, let's close this and centralize in #1443
