### ISSUE TITLE
1.12.2 Grammar police is back

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1549]
dashes mid sentence is not proper english, plus other fixes.

So change:

1.12.2 | [MODIFIED] Verify that user-uploaded files - if required to be displayed or downloaded from the application - are served by either octet stream downloads, or from an unrelated domain, such as a cloud file storage bucket. |   | ✓ | ✓ | 646
-- | -- | -- | -- | -- | --

to

1.12.2 | [MODIFIED] Verify that user-uploaded files, if required to be displayed or downloaded from the application, are served by either octet-stream downloads or an unrelated domain, such as a cloud file storage bucket. |   | ✓ | ✓ | 646
-- | -- | -- | -- | -- | --

**Comment by elarlang** [comment]
please move discussion and proposal to already opened issue for the requirement: https://github.com/OWASP/ASVS/issues/1406
