### ISSUE TITLE
2.13 - ambiguous requirements "sufficient work factor"

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#155]
_Verify that account passwords are one way hashed with a salt, and there is **sufficient work factor to defeat brute force and password hash recovery attacks**._ 

**sufficient work factor** is too broad to be included in 'standard' (i.e. asv**S**). I suggest adding concrete requirement, like how many cycles would be expected, to make brute forcing impractical while limiting denial of service vulnerability on authentication or user registration function. 

Perhaps sacrifice user enumeration vulnerability in place for strong passwords, i.e. ask for username first, before verifying (hashing) the password.  Google Gmail signup and many others are now adopting this approach.

**Comment by danielcuthbert** [comment]
agree and this has been resolved in 3.0.1
