### ISSUE TITLE
1.13 looks empty!

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1550]
v1.13 looks empty and no one is discussing it. Do we want to work on this for 5.0?

**Comment by elarlang** [comment]
Entire V1 is under re-structure and cleanup - https://github.com/OWASP/ASVS/issues/1063

If you have proposals, what kind of documentation requirements it must contain, then let us know. Otherwise I think the issue does not point to any precise problem and can be closed as duplicate of 1063.
