### ISSUE TITLE
Change suggestion for V5 "Control Objective" first paragraph ext

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1551]
suggested fix:

The most common web application security weakness is the failure to properly validate input before directly using it without any output encoding, query parameterization, or other output handling defense. This weakness leads to almost all of the significant vulnerabilities in web applications, such as Cross-Site Scripting (XSS), SQL injection, OS command injection, template injection, log injection, LDAP injection, and more.

**Comment by elarlang** [comment]
I would like to have clear message, that input validation is not for defense against XSS, SQL injection etc. Input validation is just for (business logic) data integrity. How the data is handled later, is not input validation responsibility.

**Comment by jmanico** [comment]
> I would like to have clear message, that input validation is not for defense against XSS, SQL injection etc. Input validation is just for (business logic) data integrity. How the data is handled later, is not input validation responsibility.

That is not true. You need output validation as a core defense for untrusted URL's.

Like in react:

<a href={userURLinput}>CLICK ME</a>

is solved with URL validation in react, not encoding. Angular has this validation defense built in.

**Comment by mgargiullo** [comment]
@elarlang  I'm not sure if I'm coming into this late, but...
 I agree that client-side input validation is not a security function. What are you calling server-side "How the data is handled later"?
 
If we agree that the server-side should always assume that incoming data is dirty or potentially poisoned... if the server validates that the data supplied by the user for a SQL query should be an integer (and we validate that it is), I'd call that input validation. It doesn't replace using the database driver's parameter functionality to ensure dynamic queries are safe, but it is validating that the incoming data is sane.

**Comment by elarlang** [comment]
Agree with URL and binding examples, my point was or should be more precisely addressed towards dynamic document building, like HTML, JavaScript and SQL injection. And this is common mistake - output layer is built in knowledge, that "only good" things came into database, and then business rules changed... and no one knows where the defense is missing.

**Comment by jmanico** [comment]
I hear you Elar. Building a good UI that is XSS resistant is super hard and requires:

1) Contextual output encoding *for data you want to display exactly as the user typed it in*
2) Contextual output validation *user driven URL's*
3) Contextual output sanitization *for user driven HTML*
4) Cookie security like HTTPOnly *stop cookie theft*
5) Build templates safely *dont use user input server side to construct templates*

And a lot more. It's WAY more than output encoding. You need a mix of output validation, output encoding and output sanitization to really build secure UI's (and more).

**Comment by tghosth** [comment]
I think this is a terminology question primarily, 

@jmanico would you maybe accept:

The most common web application security weakness is ~the failure to properly validate input before directly~ using **untrusted content in an unsafe context** ~it~ without any output encoding, query parameterization, or other output handling defense. This weakness leads to almost all of the significant vulnerabilities in web applications, such as Cross-Site Scripting (XSS), SQL injection, OS command injection, template injection, log injection, LDAP injection, and more.

**Comment by jmanico** [comment]
Much better Josh, I like the change
