### ISSUE TITLE
5.1.6 needs added clarity

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1553]
Suggest change:

5.1.6 | [MOVED FROM 1.5.3, LEVEL L2 > L1] Verify that input validation is enforced on a trusted service layer. (C5) | ✓ | ✓ | ✓ | 602
-- | -- | -- | -- | -- | --

to:

5.1.6 | [MOVED FROM 1.5.3, LEVEL L2 > L1] Verify that input validation is enforced on a trusted service layer. Avoid client-side validation, which can be easily bypassed. (C5) | ✓ | ✓ | ✓ | 602
-- | -- | -- | -- | -- | --

**Comment by elarlang** [comment]
Recommendation sends wrong signal, like client-side validation is bad. It is not bad, just from security point of view, you can not rely on that.

**Comment by jmanico** [comment]
How about:

5.1.6 | [MOVED FROM 1.5.3, LEVEL L2 > L1] Verify that input validation is enforced on a trusted service layer.  Client-side validation, while still useful for other purposes, which can be easily bypassed from a security perspective. (C5) | ✓ | ✓ | ✓ | 602
-- | -- | -- | -- | -- | --

**Comment by mgargiullo** [comment]
May I suggest a slight rewrite for clarity:

"Client-side validation, while still useful for other purposes, which can be easily bypassed from a security perspective. 
to
"While useful, client-side validation can be easily bypassed and thus is not a security treatment."

**Comment by elarlang** [comment]
Mor food for brain.

We hade similary discussion (https://github.com/OWASP/ASVS/issues/1031#issuecomment-965569058) for access control requirement 4.1.1:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **4.1.1** | [MODIFIED] Verify that the application enforces access control rules at a trusted service layer and doesn't rely on controls which an untrusted user could manipulate such as client-side JavaScript. | ✓ | ✓ | ✓ | 602 |


Also, we have logging requirement which kind of expects, that all input validation is done on the client side, other wise you have a lot of noise to log on the trusted service layer. If input validation is done in client side, then you have only 2 cases to log as input validation error:
  * validations on the client-side and server-side are out of sync (bug)
  * someone is trying to manipulate input validation or making HTTP request without expected user-interface (browser) - potential attacking attempt

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **7.1.3** | [MODIFIED] Verify that the application logs security relevant events including successful and failed authentication events, access control failures, deserialization failures, input validation failures and incorrect HTTP requests (including requests with an unexpected HTTP verb). ([C5, C7](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 778 |

**Comment by elarlang** [comment]
ping @jmanico @tghosth

**Comment by jmanico** [comment]
I like it Elar. Small change suggestion:

Verify that input validation is enforced at a trusted server-side layer. While client-side validation improves usability, security must not rely solely on it.

**Comment by tghosth** [comment]
Minor change:

(We wanted to move away from the "server-side" expression).

> Verify that the application is designed to enforce input validation at a trusted service layer. While client-side validation improves usability, security must not rely on it.

This should be added to the new section described here: https://github.com/OWASP/ASVS/issues/1484#issuecomment-1933966658

Should also add an entry to recommendations:

> Client-side input validation should be enforced along with the validation at a trusted service layer as this provides a good opportunity to discover when someone has bypassed client-side controls in an attempt to attack the application.

**Comment by tghosth** [comment]
@elarlang to create the PR

**Comment by tghosth** [comment]
> Should also add an entry to recommendations:
> 
> > Client-side input validation should be enforced along with the validation at a trusted service layer as this provides a good opportunity to discover when someone has bypassed client-side controls in an attempt to attack the application.

I have done this with: https://github.com/OWASP/ASVS/pull/1871/commits/6b92836740d2238ffc113ba6bdd90febe5d25227
