### ISSUE TITLE
Missing CSS Injection in ASVS (split from 5.3.1)

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#1558]
I have recently noticed that ASVS does not include a check for CSS Injection, which is a common vulnerability that can have a significant impact on web application security.

CSS Injection is a type of injection attack that targets the Cascading Style Sheets (CSS) of a web application, where an attacker can inject malicious code into the CSS files that are used to style the application. This can result in various attacks, such as cross-site scripting (XSS), data exfiltration, and other types of attacks.

Considering the potential impact of this vulnerability, I believe that it should be included in ASVS to ensure that web applications are thoroughly tested for security. I would like to suggest adding a new item to ASVS for CSS Injection, with relevant testing requirements and verification procedures.

The testing requirements for this section could include verifying that input validation and sanitization are performed on user input that is used to generate CSS, that the content security policy (CSP) is implemented correctly to limit the sources of external CSS sources.

**Comment by elarlang** [comment]
We actually have it covered in 5.3.1:
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **5.3.1** | [MODIFIED] Verify that output encoding is relevant for the interpreter and context required. For example, use encoders specifically for HTML values, HTML attributes, JavaScript, **CSS**, URL parameters, HTTP headers, SMTP, and others as the context requires, especially from untrusted inputs (e.g. names with Unicode or apostrophes, such as ねこ or O'Hara). ([C4](https://owasp.org/www-project-proactive-controls/#div-numbering)) | ✓ | ✓ | ✓ | 116 |

It was added recently via https://github.com/OWASP/ASVS/issues/1286 but now I think, it's not in correct (sub)category (5.3) - defense against CSS injection is most likely allow-listed input validation (category 5.1) or sanitization (category 5.2).

**Comment by tghosth** [comment]
@ImanSharaf do you agree with @elarlang ?

**Comment by ImanSharaf** [comment]
I agree with your observation that the current placement of the CSS Injection check may not be in the most suitable (sub)category. As you suggested, it would be more fitting under either allow-listed input validation (category 5.1) or sanitization (category 5.2), as these categories focus on addressing potential injection vulnerabilities.

**Comment by elarlang** [comment]
Technical note: as CSS was not part of the 5.3.1 in latest release and is added to the bleeding edge, then as a separate requirement it must get label `[ADDED]` (not split from 5.3.1)

**Comment by elarlang** [comment]
From @jmanico via https://github.com/OWASP/ASVS/issues/1589#issuecomment-1497956789
> Note: CSS encoding is a thing, it's a native JS function. CSS.escape for example.

https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape

**Comment by tghosth** [comment]
Yeah I think we will need to decide whether we need to a separate requirement per sink type or whether we can have a giant combined requirement like this.

**Comment by elarlang** [comment]
With requirement per language/syntax we can be more precise with every requirement. I prefer this way.

Compare with cookie setup - one requirement for each parameter, and then we have "entire world" described in 5.3.1

**Comment by jmanico** [comment]
How about:

_Verify that untrusted input added to dynamically-generated CSS is properly escaped or sanitized to prevent CSS Injection attacks._

**Comment by jmanico** [comment]
> As it contains both, escaping and sanitizing, it's hard to decide category for it. Also, maybe we can do the requirement without "untrusted" input, as actually every input needs escaping to keep the functionality working.

I think that is a good idea. More specifically, both escaping and VALIDATION. I would never sanitize content that goes into CSS as a dynamic variable. I would only sanitize of the content was a chunk of CSS that a user authored as input.

**Comment by elarlang** [comment]
We actually have CSS sanitization covered via 5.2.8...

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **5.2.8** | Verify that the application sanitizes, disables, or sandboxes user-supplied scriptable or expression template language content, such as Markdown, CSS or XSL stylesheets, BBCode, or similar. | ✓ | ✓ | ✓ | 94 |

**Comment by tghosth** [comment]
Good spot @elarlang, this is tagged as needs rework because it needs to be tackled alongside the rest of the chapter

**Comment by jmanico** [comment]
I think the wwayas CSS is referenced in 5.3.1 and 5.2.8 is more than enough to address CSS injection and I think we can close this issue cc @elarlang and @tghosth

**Comment by tghosth** [comment]
I think we have consensus to just close this for now as CSS is mentioned elsewhere.
