### ISSUE TITLE
2.16 - rephrase, hard to read, invalid assumptions 

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#156]
_Verify that credentials are transported using a suitable encrypted link and that all pages/functions that require a user to enter credentials are done so using an encrypted link._

"are done so" is a little out of place here, as is "suitable". 

Perhaps:
Verify that all application data is transmitted over an encrypted channel (e.g. TLS). 

If this is covered elsewhere, then the entire control 2.16 is redundant. 

Justification for 'all', rather than specifics (e.g. credentials, pages, functions):
It is unknown what is and is not sensitive. Taking a black list approach (defining what we/the author  thinks should be encrypted) is too narrow. Encrypt everything.

**Comment by danielcuthbert** [comment]
I agree, times have changed and have amended to reflect that in 3.1
