### ISSUE TITLE
Add Web Cache Deception Attack Verification to ASVS

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#1560]
I believe the current version of ASVS does not include an item that addresses the vulnerability of web cache deception attacks. These attacks have been successfully carried out against many online services, including PayPal ([$3k bounty was paid to the researcher](http://omergil.blogspot.com/2017/02/web-cache-deception-attack.html)) and others. Also, I believe 8.2.1 check doesn't fully cover this, as the main issue is that the web app serves a dynamic page as a static page that doesn't exist.
Web cache deception attacks are a type of attack where a server caches pages with personal data in a way that makes them available to unauthenticated users. An attacker can trick a user into accessing a link pointing to a non-existent resource, and the server will then create a cache for the URL section up until the non-existent resource. This cached page can include user details, such as account balance, transaction data, email address, and the last four digits of the user's debit/credit card, among others.

The impact of such an attack could be severe, as it allows attackers to gain access to personal data without any authentication or authorization. A potential check could be like this: Verify the application doesn't serve a non-existent resource.

**Comment by elarlang** [comment]
> Also, I believe 8.2.1 check doesn't fully cover this, as the main issue is that the web app serves a dynamic page as a static page that doesn't exist.

8.2 is client-side cache

I think the issue is covered by 8.1.1

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **8.1.1** | [MODIFIED, MERGED FROM 8.1.2] Verify that the application prevents sensitive data from being cached in server components such as load balancers and application caches or ensures that the data is securely purged after use. | | ✓ | ✓ | 524 |

**Comment by ImanSharaf** [comment]
I believe if testers look at this item they might miss the cache deception attack vector and they only check load balancers [settings] and app caches for any sensitive data that is cached and we need to explicitly mention the cache deception attack in this item.

**Comment by tghosth** [comment]
Hi @ImanSharaf, what specific mechanisms, requirements should we be adding to prevent this? We need to provide guidance that a developer can use to ensure that the attack is not possible in the application

**Comment by ImanSharaf** [comment]
Hi @tghosth, I believe we should validate requested resources: `Ensure that the application only serves resources that actually exist and are intended to be served.` for the reference please check [this](https://book.hacktricks.xyz/pentesting-web/cache-deception#cache-deception) one.

**Comment by elarlang** [comment]
In dynamic world "existing resource" is dynamic thing.

The problem is not what is served from the server, but what is cached in cache server. In those cases, cache server makes assumption based on request file extension, but should be based on content-type from the application server.

**Comment by tghosth** [comment]
OK, let's call in the big guns.

Hey @omer-cider, any thoughts how we can best include a defence against web cache deception in ASVS 5.0? :)

**Comment by ImanSharaf** [comment]
Latest interesting Web Cache Deception incident: Someone has found a critical account takeover on ChatGPT using Web Cache Deception https://twitter.com/naglinagli/status/1639343866313601024?s=20

**Comment by tghosth** [comment]
Found this in @omer-cider's original whitepaper: 

> **MITIGATIONS**
> 1. Configure the cache mechanism to cache files only if their HTTP caching headers allow.
> 2. Store all static files in a designated directory and cache only that directory.
> 3. If the cache component provides the option, configure it to cache files by their content type.
> 4. Configure the web server so that for pages such as http://www.example.com/home.php/nonexistent.css, the web server does not return the content of home.php with the triggering URL; instead, the server should return a 404 or 302 response.

I am thinking of two requirements. @ImanSharaf @elarlang what do you think:

1:
> Verify that caching mechanisms are configured to only cache static files and only those which have the correct content type to prevent Web Cache Deception attacks. 

2:
> Verify that the web server returns a 404 or 302 response when an non-existent file is accessed rather than returning a different, valid file to prevent Web Cache Deception attacks.

**Comment by elarlang** [comment]
> Verify that caching mechanisms are configured to only cache static files

This one sends wrong signal. It's allowed to cache dynamic content as well with checking the modification.

> Verify that the web server returns a 404 or 302 response when an non-existent ...

The problem with `/some.php/other.css` is that part after last `/` can be translated to "query string" which means it actually does not cause 404 or any other error, but load balancer still may see "css file" there and caches it.

Like I wrote here https://github.com/OWASP/ASVS/issues/1560#issuecomment-1474972810:

> The problem is not what is served from the server, but what is cached in cache server. In those cases, cache server makes assumption based on request file extension, but should be based on content-type from the application server.

Maybe this direction: Verify that caching decisions (todo: where?) are following caching headers from the application and decision are made based on content-type (not based on file extension) to prevent Web Cache Deception attacks.

By concept it can be part of 8.1.1, but it may get too long.

**Comment by tghosth** [comment]
> > Verify that caching mechanisms are configured to only cache static files
> 
> This one sends wrong signal. It's allowed to cache dynamic content as well with checking the modification.

So how about:

**_Verify that caching mechanisms are configured to only cache files which have the correct content type and which do not contain sensitive, dynamic content to prevent Web Cache Deception attacks._**
 
> > Verify that the web server returns a 404 or 302 response when an non-existent ...
> 
> The problem with `/some.php/other.css` is that part after last `/` can be translated to "query string" which means it actually does not cause 404 or any other error, but load balancer still may see "css file" there and caches it.
> 
> Like I wrote here [#1560 (comment)](https://github.com/OWASP/ASVS/issues/1560#issuecomment-1474972810):

> > The problem is not what is served from the server, but what is cached in cache server. In those cases, cache server makes assumption based on request file extension, but should be based on content-type from the application server.


So Cider's 4th recommendation is:

> 4. Configure the web server so that for pages such as http://www.example.com/home.php/nonexistent.css, the web server does not return the content of home.php with the triggering URL; instead, the server should return a 404 or 302 response.

My understanding is that this behaviour leads to a situation where the server is returning content with a content type and extension which looks to the caching server to be something it should be caching. As such, this is specifically a web server configuration and not a caching server configuration.

**Comment by elarlang** [comment]
I would change "files" to "responses"

_Verify that caching mechanisms are configured to only cache **responses** which have the correct content type and which do not contain sensitive, dynamic content to prevent Web Cache Deception attacks._

"responses" can be more precise as well, like "HTTP responses from the application"

**Comment by tghosth** [comment]
Ok so I think that makes sense @elarlang.

As such, I would propose the following additions:


## V14.7 Web Server Configuration

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **14.7.1** | [ADDED] Verify that caching mechanisms are configured to only cache responses which have the correct content type and which do not contain sensitive, dynamic content to prevent Web Cache Deception attacks. | | ✓ | ✓ | 444 |
| **14.7.2** | [ADDED] Verify that the web server returns a 404 or 302 response when an non-existent file is accessed rather than returning a different, valid file to prevent Web Cache Deception attacks. | | ✓ | ✓ | 444 |

**Comment by elarlang** [comment]
* I think proposed 14.7.2 can be part of 14.7.1 as an exclusion
* "web server configuration" as category for separate cache server is confusing, I think proposed requirement(s) should be in the same category with current requirement 8.1.1 (it can be moved)

**Comment by tghosth** [comment]
OK so @elarlang how about:

## V8.1 General Data Protection

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **8.1.7** | Verify that caching mechanisms are configured to only cache responses which have the correct content type and do not contain sensitive, dynamic content. The web server should return a 404 or 302 response when an non-existent file is accessed rather than returning a different, valid file. This should prevent Web Cache Deception attacks.. | | ✓ | ✓ | 444 |

**Comment by elarlang** [comment]
Let's go with that. We can finetune it always later if needed.

**Comment by jmanico** [comment]
I like this as well, nice work everyone.
