### ISSUE TITLE
Add a Category for CI/CD Security Risks in ASVS

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#1566]
I am writing to suggest the addition of a new category for CI/CD security risks in the ASVS (Application Security Verification Standard). Currently, the ASVS does not explicitly cover security risks related to CI/CD pipelines, which are becoming increasingly important in modern software development.

As more organizations adopt continuous integration and delivery (CI/CD) practices, it is essential that the ASVS includes guidance on how to verify the security of these pipelines. CI/CD pipelines are often used to automate the deployment of software, which means that vulnerabilities in these pipelines can lead to the rapid deployment of insecure code.

A dedicated category for CI/CD security risks in the ASVS would provide developers and security professionals with clear guidance on how to identify and mitigate these risks. This would help to improve the overall security of software systems and reduce the likelihood of successful attacks.
Therefore, I would like to request that the ASVS Development Team consider adding a new category for CI/CD security risks in a future release of the standard. 
There are are some items that are related to  CI / CD pipeline in the subsection 14.1 such as `Verify that the application build and deployment processes are performed in
a `**secure**` and repeatable way, such as CI / CD automation, automated
configuration management, and automated deployment scripts.`
But I believe that having its own category would be a valuable addition to the ASVS and would help to ensure that it remains relevant and useful for modern software development practices.
We can get inspired by OWASP Top 10 CI/CD Security Risks framework to create related ASVS issues.
![image](https://user-images.githubusercontent.com/78227895/222478683-eba8bd41-94f5-49a0-8131-d112c0c972f9.png)

**Comment by elarlang** [comment]
In my opinion entire CI/CD topic is out of scope for ASVS. See https://github.com/OWASP/ASVS/issues/1527#issuecomment-1417190647

**Comment by ImanSharaf** [comment]
Thank you for your response. While I appreciate your opinion, I respectfully disagree that the CI/CD topic is completely out of scope for ASVS.

CI/CD practices have become an integral part of modern software development, and vulnerabilities in these pipelines can have serious security implications. As such, it is essential that the ASVS provides guidance on how to verify the security of these pipelines.

Furthermore, the ASVS already includes categories that relate to software development practices. Adding a new category for CI/CD security risks would be in line with the ASVS's focus on providing comprehensive coverage of application security.

I understand that the inclusion of a new category requires careful consideration and evaluation by the ASVS development team. However, I strongly believe that the benefits of including a category for CI/CD security risks would far outweigh the effort required to develop it.

Thank you for your consideration.

**Comment by elarlang** [comment]
I repeat myself here - I say, build pipeline is important to achieve security but also I say, it's not clearly in the ASVS scope. It should have it's own standard as it's quite clearly separate topic. ASVS verifyes the result of it (build piplelines), not that much how it is achieved.

If we going to include build pipelines, then where is the limit - what items from development and build process we include and what not?

We already got rid of many requirements which were not clearly in the scope, including backup process - as this is something which not the responsibility for the application. The same with build pipeline, it's not in the scope or responsibility of the application.

So, those are my opinions and those are not standing for _the only truth in the world_. The more opinions and arguments we get, the better result we will have.

**Comment by ImanSharaf** [comment]
These are my recommendations for the Insufficient Flow Control Mechanisms subcategory. If the ASVS team chooses not to include a CI/CD security category, I will establish a new OWASP project dedicated to CI/CD Verification Standards. @jmanico @elarlang

- Verify that branch protection rules are configured on branches hosting code used in production and other sensitive systems, with no exclusions for user accounts or branches without a valid reason.
- Verify that auto-merge rules are limited in usage, thoroughly reviewed, and not bypassable. Ensure auto-merge rules do not import third-party code without proper scrutiny.Verify that user accounts with permission to push unreviewed code to a repository are restricted from triggering deployment pipelines connected to the repository.
- Verify that production build and deployment pipelines require additional approval or review before being triggered by any account.
- Verify that artifacts are only allowed to flow through the pipeline if created by a pre-approved CI service account. Ensure secondary review and approval is required for artifacts uploaded by other accounts.Verify that drifts and inconsistencies between code running in production and its CI/CD origin are detected and prevented. Implement mechanisms to modify any resource containing a drift.
- Verify that the CI/CD pipeline implements a multi-step approval process for deploying code and artifacts to sensitive environments, including production.Verify that pipeline flow control mechanisms are in place to detect and prevent unauthorized changes to application code or infrastructure in production environments.
- Verify that access to the SCM, CI, and artifact repository systems is restricted to authorized users and applications with the principle of least privilege applied.Verify that all changes to production code and infrastructure undergo a strict set of reviews and approvals, including peer review, security review, and change management approval.
- Verify that the CI/CD pipeline has an audit log to track and monitor all actions performed, including code pushes, pipeline triggers, and artifact deployments.
- Verify that continuous monitoring and alerting mechanisms are in place to detect suspicious activity in the CI/CD pipeline and trigger appropriate incident response procedures.

**Comment by elarlang** [comment]
Personally I would like to see this as separate project.

Those requirements for me are out of ASVS scope. And again I think it's important to state - I think those are important, the question is just scoping.

I labeled the issue with "Leaders decision", so let's wait feedback from others as well.

**Comment by ImanSharaf** [comment]
It is a good idea to seek input from other team members and leaders to ensure that the scope of the project remains focused and relevant. By labeling the issue with "Leaders decision," you've made it clear that you're open to feedback and looking for consensus from others. Ultimately, the decision will depend on the team's collective agreement on the project's scope and I would like to hear from them too. Thanks.

**Comment by danielcuthbert** [comment]
Firstly I agree with the points raised here, there needs to be more eyes on pipeline integrity and security and what is proposed is 100% solid. I'm with @elarlang here in that I think this is more ideal as a separate project, and indeed an important one at that, but I don't see it easily fitting into the ASVS

**Comment by jmanico** [comment]
> Firstly I agree with the points raised here, there needs to be more eyes on pipeline integrity and security and what is proposed is 100% solid. I'm with @elarlang here in that I think this is more ideal as a separate project, and indeed an important one at that, but I don't see it easily fitting into the ASVS

+1 Daniel and Elar. I like the DASVS (DevOps ASVS) (for CI/CD rules) as a separate project.

**Comment by tghosth** [comment]
Closing for now
