### ISSUE TITLE
2.4.3 PBKDF2 iterations value should be changed from 100,000 to 600,000 in alignment with OWASP Password Storage Cheat Sheet

### ISSUE THREAD

**Issue by markonweb** [OWASP/ASVS#1567]

**Comment by markonweb** [comment]
Proposal to change 2.4.3 (line 98) PBKDF2 iterations value from 100,000 to 600,000 in alignment with the OWASP Password Storage Cheat Sheet https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html

**Comment by elarlang** [comment]
What is the argumentation behind the value "600,000"? Other than it is in the cheat sheet.

**Comment by markonweb** [comment]
Good question. The cheat sheet recommendation points to https://tobtu.com/minimum-password-settings/ , a page on a site owned by Steve "sc00bz" Thomas. Also on the site, is a link his Blackhat 2022 presentation https://tobtu.com/files/blackhat2022.pdf  
Sides 18-20 are about PBKDF2 including a minimum strength recommendation of "Such that an attacker gets <10 KH/s/GPU" with a footnote (17) that links to an ArsTechnica article about the 2015 LastPass breach https://arstechnica.com/?p=685505 ... I haven't seen what led to the 600,000 iteration recommendation.
fwiw, the cheat sheet iteration recommendation carried into the wikipedia entry for pbkdf2 as an "OWASP recommendation" https://en.wikipedia.org/wiki/PBKDF2
RFC 2898 (Sept 2000) isn't prescriptive except that it recommends a min of 1000 iterations. https://www.rfc-editor.org/rfc/rfc2898#section-4
RFC 8018 (Jan 2017) obseletes RFC 2898 but restates the same numbers and section 4.2 references NIST SP 800-132 as the source. Min of 1000 iterations https://www.rfc-editor.org/info/rfc8018
CWE 916 isn't prescriptive in terms of iterations https://cwe.mitre.org/data/definitions/916.html
NIST SP 800-132 (Dec 2010) isn't prescriptive either, but also recommends a min of 1000 iterations in section 5.2. https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-132.pdf
Note - NIST just closed a public comment period on SP 800-132 (so there will likely be changes) https://content.govdelivery.com/accounts/USNIST/bulletins/3414e52
NIST SP 800-63B (Jun 2017) states "For PBKDF2, the cost factor is an iteration count: the more times the PBKDF2 function is iterated, the longer it takes to compute the password hash. Therefore, the iteration count SHOULD be as large as verification server performance will allow, typically at least 10,000 iterations." https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63b.pdf
So... as far as NIST or IETF are concerned, I was only able to find a high water mark minimum iteration recommendation of 10,000. Password vault companies and Microsoft's default iteration count for asp.net cite 100,000 or higher but I haven't found a source indicating why they selected their respective numbers.
Do you know what the source was for the ASVS recommendation of 100,000?
I found a closed issue related to this topic where the alignment of ASVS with the cheat sheet was discussed https://github.com/OWASP/ASVS/issues/1003 . Based on a comment in the thread, it appears that the two were brought into alignment at some point in 2021. There are also comments in the thread related to standing by the number of iterations based on work with the hashcat team. Lastly, someone mentioned a concern related to breaking support for older hardware (and they referenced the NIST minimum iteration count of 1000). No math or sources were shared related to the current 100,000 value.  I'm guessing that it will probably be best to wait for NIST to release an updated version of SP 800-132 unless someone can share the math behind their recommendations.

**Comment by elarlang** [comment]
Ok, I though I already saw something like that and we actually have the same proposal in other issue: #1508

**Comment by tghosth** [comment]
This is useful context but I am going to close this issue as handled by #1508
