### ISSUE TITLE
2.17 - too broad and may be misinterpreted 

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#157]
_Verify that the forgotten password function and other recovery paths do not reveal the current password and that the new password is not sent in clear text to the user._

**"new password is not sent in clear text to the user"**

This does not assist with sending one time password reset link, which is typically sent over SMTP in the clear. 

I think this needs to be a little more explicit.

**Comment by danielcuthbert** [comment]
agreed amended in 3.1
