### ISSUE TITLE
Missing ASVS verification item for preventing loop bound injection attacks

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#1570]
The current version of the Application Security Verification Standard (ASVS) does not include a specific verification item for preventing loop bound injection attacks, which is a security vulnerability that can occur in code that uses loops to iterate over data and can cause a DoS. Therefore, it is recommended to add a new verification item to help ensure that developers take appropriate steps to prevent this type of vulnerability.
Please check this [reference](https://codeql.github.com/codeql-query-help/javascript/js-loop-bound-injection/) to see sample vulnerable codes (the attacker can modify the length property without inserting any items into the object).

A sample check could be this one:
_Verify that input validation is performed for all loop conditions to prevent loop bound injection attacks._

**Comment by elarlang** [comment]
The name "loop bound injection" is confusing for me.

The actual context is basically just input validation, and if it's not done, then as an impact in some context it may cause "running out of resources". "Loop" means it actually never ends, but based on description, it's not the case here.

Now there is question, do we want to have separate requirement to say - Verify that your input validation rules are matching with available resources.

Similar requirements already exists in business logic and file handling area:
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **11.1.3** | Verify the application has appropriate limits for specific business actions or transactions which are correctly enforced on a per user basis. | ✓ | ✓ | ✓ | 770 |
| **11.1.5** | Verify the application has business logic limits or validation to protect against likely business risks or threats, identified using threat modeling or similar methodologies. | ✓ | ✓ | ✓ | 841 |
| **12.1.1** | [MODIFIED] Verify that the application will only accept files of a size which it can process without causing a loss of performance or denial of service attack. | ✓ | ✓ | ✓ | 400 |
| **12.1.3** | Verify that a file size quota and maximum number of files per user is enforced to ensure that a single user cannot fill up the storage with too many files, or excessively large files. | | ✓ | ✓ | 770 |

**Comment by elarlang** [comment]
In a way related: https://github.com/OWASP/ASVS/issues/934
(if someone can ask too many rows/too big response to the output, that server can not produce it - running out of memory)

**Comment by ImanSharaf** [comment]
There is a difference between loop bound injection and #934. In JavaScript, the `length` property of an array is mutable, which means that an attacker can modify it without actually inserting that many items in the array. This is often how loop bound injection attacks are carried out in JavaScript applications.

For example, consider the following code:
```
var arr = [1, 2, 3];
for (var i = 0; i < arr.length; i++) {
    console.log(arr[i]);
}
```
In this code, the loop iterates over the items in the `arr` array, and the loop condition is based on the value of `arr.length`. An attacker can modify the `length` property of the array without actually changing the contents of the array itself, by using the `Object.defineProperty()` function. Here's an example:
```
var arr = [1, 2, 3];
Object.defineProperty(arr, 'length', {value: 1000000});
for (var i = 0; i < arr.length; i++) {
    console.log(arr[i]);
}
```
In this modified code, the attacker has set the length property of the `arr` array to a very large value using `Object.defineProperty()`. This causes the loop to iterate many times, potentially causing a denial-of-service attack or other security issue.

To prevent this type of attack, input validation should be performed on the value of `arr.length` before using it in a loop condition. This can help to ensure that the loop does not consume excessive resources or cause other security issues.

**Comment by elarlang** [comment]
Well, "attacker can modify" .. how? What is the precondition that an attacker can do that?

**Comment by ImanSharaf** [comment]
Please check the following [code](https://codeql.github.com/codeql-query-help/javascript/js-loop-bound-injection/). The server listens for POST requests to the `/foo` endpoint and expects to receive a JSON object in the request body. Here, the attacker can modify the `length` property.
```
var express = require('express');
var app = express();

app.post("/foo", (req, res) => {
    var obj = req.body;

    var ret = [];

    // Potential DoS if obj.length is large.
    for (var i = 0; i < obj.length; i++) {
        ret.push(obj[i]);
    }
});
```

**Comment by elarlang** [comment]
I checked it before I wrote my first comment. I still think it's input validation question with different potential outcome as impact.

For JSON and for this example we need to meet the requirement 13.2.2 first:
_13.2.2 | Verify that JSON schema validation is in place and verified before accepting input._

At same time I'm opened to point-of-views, how it is not (only) an input validation question.

**Comment by elarlang** [comment]
> Also, there are many ASVS items that can be grouped into one ASVS item under the name of input validation (all injection related attaks) but we have not done that (which is good).

A bit offtopic, but - against injection attack you need mostly encoding, then sanitization, then input validation.

> The point here is to make the tester aware of this attack vector.

Yes, awareness is good. The question - is ASVS the correct project to achieve it (if the reason is only awareness)?

And back to the beginning: can you provide an example - how _loop bound injection_ can happen if input validation (including JSON schema validation) is done correctly?

Where I want to reach is - if it's not a separate and independent problem, then I'm not sure it's worth separate and independent requirement. Note: I'm not sure does not mean I'm against that.

**Comment by jmanico** [comment]
Actually you do •not• need encoding, injection or sanitization for the most severe form of injection. You need query parameterization to stop SQL injection.This is why injection is a lot more difficult to fix than most people think because each individual type of injection has a very different formula for how it needs to be fixed.On Mar 9, 2023, at 12:21 AM, Elar Lang ***@***.***> wrote:﻿

Also, there are many ASVS items that can be grouped into one ASVS item under the name of input validation (all injection related attaks) but we have not done that (which is good).

A bit offtopic, but - against injection attack you need mostly encoding, then sanitization, then input validation.

The point here is to make the tester aware of this attack vector.

Yes, awareness is good. The question - is ASVS the correct project to achieve it (if the reason is only awareness)?
And back to the beginning: can you provide an example - how loop bound injection can happen if input validation (including JSON schema validation) is done correctly?
Where I want to reach is - if it's not a separate and independent problem, then I'm not sure it's worth separate and independent requirement. Note: I'm not sure does not mean I'm against that.

**Comment by ImanSharaf** [comment]
If the developer uses maxItems in the JSON Schema to set a bound we can prevent this attack, should we rephrase the ASVS item to mention this too?

**Comment by tghosth** [comment]
I think the control flow thing here is the key point. I would propose an addition to V5.1 Input Validation:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **5.1.7** | [ADDED] Verify that untrusted input which can affect control flow (such as the number of iterations in a loop) is carefully validated against expectations. | | ✓ | ✓ | |

**Comment by tghosth** [comment]
@ImanSharaf @elarlang comments?

**Comment by elarlang** [comment]
Can you clarify, what is the risk or attack vector to solve with this?

**Comment by tghosth** [comment]
This is the attack vector which concerns me:
https://github.com/OWASP/ASVS/issues/1570#issuecomment-1458679446 @elarlang

**Comment by tghosth** [comment]
@set-reminder 7 days @tghosth Is this different to input validation? The size of the loop should be a business expectation kind of, no?

**Comment by tghosth** [comment]
Ok so following further discussion with @elarlang, I think maybe we need to include this as a business expectation which input validation is checking for so my thought is to try and include it in 5.1.3. I therefore propose the following:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **5.1.3** | [MODIFIED] Verify that all input is validated using positive validation, against an allowed list of values, patterns or ranges to enforce business or functional expectations for that input. | ✓ | ✓ | ✓ | 20 |

@ImanSharaf do you think this is sufficient.

@elarlang any further thoughts

**Comment by tghosth** [comment]
I would also suggest adding a clarification to the surrounding text.

**Comment by tghosth** [comment]
@elarlang was ok with this.

@ImanSharaf any final requests before I do a PR?

**Comment by ImanSharaf** [comment]
I am good.

**Comment by tghosth** [comment]
Opened #1570

Still need to do the surrounding text update

**Comment by tghosth** [comment]
Surrounding text updated in #2026
