### ISSUE TITLE
Protection against Cross-Site WebSocket Hijacking (CSWSH) attacks

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#1575]
What do you think about modifying "13.5.2 Verify that, during the initial HTTP WebSocket handshake, the Origin header is checked against an allow list of authorized origins.". This is the modified version:

[MODIFIED] 13.5.2 Verify that the application enforces a combination of Origin header validation and authentication checks to protect against cross-site WebSocket hijacking (CSWSH) attacks.

**Comment by elarlang** [comment]
What do you mean by "authentication checks"? How it is different from just authentication?

Is it protection against cross-site or cross-origin websocket hijacking?

**Comment by tghosth** [comment]
@ImanSharaf does [13.5.6](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x21-V13-API.md#v135-websocket) not cover authentication? Not sure if this extra addition is necessary?

> [ADDED] Verify that authentication is done before opening the WebSocket connection if only authenticated users should be able to use WebSockets.

**Comment by tghosth** [comment]
> @ImanSharaf does [13.5.6](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x21-V13-API.md#v135-websocket) not cover authentication? Not sure if this extra addition is necessary?
> 
> > [ADDED] Verify that authentication is done before opening the WebSocket connection if only authenticated users should be able to use WebSockets.

@ImanSharaf what do you think?

**Comment by elarlang** [comment]
> [ADDED] Verify that authentication is done before opening the WebSocket connection if only authenticated users should be able to use WebSockets.

I don't get the need for this requirement, and by this wording it sounds like current 4.1.3:

> V4.1.3 Verify that the principle of least privilege exists - users should only be able to access functions, data files, URLs, controllers, services, and other resources, for which they possess specific authorization. This implies protection against spoofing and elevation of privilege.

**Comment by jmanico** [comment]
This is a rule for Authentication. All websockets should require an active token or similar. Since this, at least was, relatively new tech, many developers have their website endpoints missing authentication, which is why this requirement is suggesting it.

This is to stop a third-party from opening up a Web socket to your site and using it without authentication.

This is likely covered in other areas…

**Comment by ImanSharaf** [comment]
> rify that authentication is done before opening the WebSocket connection if only authenticated users should be able to use WebSockets.

It is good!

**Comment by maizuka** [comment]
Question: Is it safe without Origin header checked, if the authentication is checked over cookie session or it is by HTTP authentications (Basic, Digest)?

**Comment by tghosth** [comment]
Ok I think section 13.5 handles Iman's original question so I am going to close this for now. If anyone has other questions, please open a separate issue.
