### ISSUE TITLE
2.22 - opinionated/contradictory control, contradicts ASVS L1 

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#158]
_Verify that forgotten password and other recovery paths use a TOTP or other soft token, mobile push, or other offline recovery mechanism. Use of a random value in an e-mail or SMS should be a last resort and is known weak._

This control covers ASVS Level 1, 2, 3.

Low risk/low value applications (e.g. ASVS L1), in my opinion,  are not required to have this level of security, from ROI and cost point of view. This is why ASVS has three levels of security. TOTP holds no ROI on low value applications for most companies. Control should be adjusted to cover L2 and L3. L1 should be abandoned for TOTP.  

Also, SMS has been deprecated by NIST. It should be reflected in ASVS too. 

N.B.
L2 and L3 should also call out B2B and API communications, typically not via UI that may be missed in 2FA implementation (i.e. should have compensating controls, where 2FA is not practical for API and B2B authentication).

**Comment by danielcuthbert** [comment]
agree 100%

Verify that forgotten password and other recovery paths use a TOTP or other soft token, mobile push, or other offline recovery mechanism. The use of SMS has been deprecated by NIST and should not be used.
