### ISSUE TITLE
2.24 - simplify wording

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#159]
_Verify that if shared knowledge based questions (also known as "secret questions") are required, the questions do not violate privacy laws and are sufficiently strong to protect accounts from malicious recovery._ 

Simplify:
Verify that if secret questions are required, the questions do not violate privacy laws and are sufficiently strong to protect accounts from malicious recovery. 

"_shared knowledge based questions_" - redundant wordage, no need to over complicate.

**Comment by danielcuthbert** [comment]
good catch and rephrasing, this is much better. added to 3.1
