### ISSUE TITLE
What does 4.3.1 mean by "administrative interfaces"

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1591]
Further to #1086, I wonder whether this is clear enough.

Specifically, What is an "administrative interfaces"? Are we only talking about super admins, are we talking about every individual tenant organizational admin? In my mind, we are talking about the most highly privileged users but do we need to make this clearer?

**Comment by elarlang** [comment]
One clear option (but not limited to): changing the application functionality (an example: installing new modules)

Potentially related issues:
* https://github.com/OWASP/ASVS/issues/1437
* https://github.com/OWASP/ASVS/issues/1438

**Comment by jmanico** [comment]
An admin interface is for admins only, so admin functionality is split from the typical user functionality.

Most every large website on the planet has a set of admin features, and most developers on the planet understand the difference. I politely do not think we need to clarify this. We should assume at least some basic developer knowledge.

**Comment by elarlang** [comment]
How I have looked to it so far - if "random user from the internet" can not register to the application / user-list is managed by a company or organization / limiting access to the admin/backoffice/... interface takes down likelihood component for the risk rating, then I use this requirement.

In short - I can live with the requirement as it is right now. When going to change it with intent to make it more clear, we need to avoid making it so limited that it rules out some current usage scenarios.
