### ISSUE TITLE
Modify 3.3.3 to include invalidation of user session upon change or removal of any authentication factor

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#1592]
Current 3.3.3 is this: 
_Verify that the application gives the option to terminate all other active sessions after a successful password change (including change via password reset/recovery), and that this is effective across the application, federated login (if present), and any relying parties._

However, I would like to suggest modifying this item to be more inclusive of other authentication factors, not just password changes.

Suggested Modification:
_Verify that the application gives the option to terminate all other active sessions after a successful change or removal of any authentication factor (including change via password reset/recovery, MFA settings update, etc.), and that this is effective across the application, federated login (if present), and any relying parties._

**Comment by elarlang** [comment]
Current situation:
| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **3.3.3** | [LEVEL L2 > L1] Verify that the application gives the option to terminate all other active sessions after a successful password change (including change via password reset/recovery), and that this is effective across the application, federated login (if present), and any relying parties. | ✓ | ✓ | ✓ | 613 | |

Proposal:
| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **3.3.3** | [MODIFIED, LEVEL L2 > L1] Verify that the application gives the option to terminate all other active sessions after a successful **change or removal of any authentication factor** (including change via password reset/recovery, **MFA settings update**, etc.), and that this is effective across the application, federated login (if present), and any relying parties. | ✓ | ✓ | ✓ | 613 | |

In general I like the proposal.

I would like to get rid of the "etc", as it does not give any content or meaning.

My concern is that we made it to Level 1 requirement and now talk about MFA in the requirement.

Also, as we already touching this requirement, I would like to get rid of "/" from reset/recovery (see https://github.com/OWASP/ASVS/issues/1491)

Updated proposal:
| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **3.3.3** | [MODIFIED, LEVEL L2 > L1] Verify that the application gives the option to terminate all other active sessions after a successful **change or removal of any authentication factor** (including change via password **reset or recovery, MFA settings update**), and that this is effective across the application, federated login (if present), and any relying parties. | ✓ | ✓ | ✓ | 613 | |

... but I still feel that it should be more flexible and to be sure that it does not give feelings "MFA must be there"

**Comment by csfreak92** [comment]
I like that latest updated proposal, makes the requirement easier and clearer to understand. 

A minor tweak if you wish to give it flexibility and not give the feeling that "MFA must be there", then maybe you could add in the phrase **"MFA settings update, if present"**. That should clear out any confusion in my opinion.

**Comment by csfreak92** [comment]
Although, a quick interjection as I would like to ask, why are we saying _"the application gives the option to terminate all other active sessions..."_? Are we not supposed to terminate all active sessions (and it should not just be an option) whenever a scenario of password reset or recovery happens?

**Comment by elarlang** [comment]
Requirement in ASVS v4.0
* _V3.3.3 Verify that the application **terminates all other active sessions** after a successful password change, and that this is effective across the application, federated login (if present), and any relying parties._

Requirement in ASVS v4.0.3
* _V3.3.3 Verify that the application **gives the option to terminate all other active sessions** after a successful password change (including change via password reset/recovery), and that this is effective across the application, federated login (if present), and any relying parties._

Change is made by @tghosth via https://github.com/OWASP/ASVS/commit/5a4baa115ae04e96af7120cfca7b7542f1a7812d and related issue is https://github.com/OWASP/ASVS/issues/734

Reason behind the change is here: https://github.com/OWASP/ASVS/issues/734#issuecomment-612671562

Do we still agree with the change @tghosth @jmanico ? Is it also aligned with NIST?

**Comment by tghosth** [comment]
> Is it also aligned with NIST?

So I don't think this requirement ever had a NIST mapping so I am not too concerned about this.

> Change is made by @tghosth via https://github.com/OWASP/ASVS/commit/5a4baa115ae04e96af7120cfca7b7542f1a7812d and related issue is https://github.com/OWASP/ASVS/issues/734

This is such a good spot @elarlang 😄 

@csfreak92 it is a good question but I think we leave it as @jmanico requested, as long as the application gives the option then that is what is important.

I have opened #1682 to address this
