### ISSUE TITLE
Suggestion to remove 7.4.2

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1596]
I suggest that 7.4.2 is not a completely security-related issue. Lots of apps do not use exception handling well yet do not have major security problems. 

7.4.2 | Verify that exception handling (or a functional equivalent) is used across the codebase to account for expected and unexpected error conditions. (C10) |   | ✓ | ✓ | 544
-- | -- | -- | -- | -- | --

I do what to keep 7.4.3, that seems more than enough to cover this issue.

7.4.3 | Verify that a "last resort" error handler is defined which will catch all unhandled exceptions. (C10) |   | ✓ | ✓ | 431
-- | -- | -- | -- | -- | --

**Comment by elarlang** [comment]
Last time (https://github.com/OWASP/ASVS/issues/1379) you "disappeared" from the conversation, maybe it makes to reopen the old issue and close this one.

**Comment by jmanico** [comment]
Agreed for some reason when I searched on this issue the old discussion did not appear. We can delete this PR and focus on the old discussion.
