### ISSUE TITLE
Add ASVS requirements for GraphQL SDL and constraint directives

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#1597]
As GraphQL is becoming a popular choice for developing APIs, I believe it is important to include specific guidance on using Schema Definition Language (SDL) and constraint directives for input validation. This would help developers ensure that their GraphQL APIs are designed and implemented securely.

Using SDL allows for a strongly typed and human-readable schema definition, making it easy for developers to understand and maintain their API structure. Additionally, incorporating validation constraints directly within the schema can improve the clarity and maintainability of the validation rules.

Here's a sample schema using SDL and constraint directives for input validation:

```graphql
input SignUpInput {
  email: String! @constraint(format: "email", maxLength: 255)
  password: String! @constraint(maxLength: 255)
  firstName: String! @constraint(pattern: "^[0-9a-zA-Z]*$", maxLength: 255)
  lastName: String! @constraint(pattern: "^[0-9a-zA-Z]*$", maxLength: 255)
}

type Mutation {
  signUp(input: SignUpInput!)
}
```
Suggested check:

_13.4.4 Ensure that Schema Definition Language (SDL) is used to define the GraphQL schema, and constraint directives are applied for input validation_

**Comment by tghosth** [comment]
So this is an interesting idea, however I am not sure the "constraint" directive is widely supported.

It looks like it exists in an npm library but not really anywhere else. https://www.npmjs.com/package/graphql-constraint-directive

As such, I am not sure we can mandate this. What do you think?

**Comment by tghosth** [comment]
I am going to close this due to insufficient library support
