### ISSUE TITLE
Appendix B page 44 – May want to write out Abbreviations for HTML and LDAP

### ISSUE THREAD

**Issue by defern** [OWASP/ASVS#16]
Appendix B page 44 – May want to write out Abbreviations for HTML and LDAP

HTML – The main markup language for the creation of web pages and other information displayed in a web browser. 

Write out HTML as HyperText Markup Language (HTML)

LDAP – An application protocol for accessing and maintaining distributed directory information services over a network. 

Write out LDAP as Lightweight Directory Access Protocol (LDAP)

**Comment by vanderaj** [comment]
Fixed. Thank you :)
