### ISSUE TITLE
2.26 - confusing control, rephrase

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#160]
_Verify that risk based re-authentication, two factor or transaction signing is in place for high value transactions._ 

This is redundant (2FA is already covered). 
If this is referring to re-authentication on sensitive operations, then this is what needs to be said. 

E.g.
Verify that sensitive operations (e.g. change password, change email address, add new biller, etc.) require re-authentication (e.g. password or 2FA token). 

Perhaps call out, that this is in addition to CSRF, not instead.

**Comment by danielcuthbert** [comment]
agreed and amended in 3.1
