### ISSUE TITLE
link to https version of URL if available (5.1.5)

### ISSUE THREAD

**Issue by securitydave** [OWASP/ASVS#1603]
5.3.x (additional requirement) or 5.x.1 (new section)
Verify that hyperlinks in the application’s pages always provide the TLS version (https:) of a URL if it is available. Relying on redirect gives an opportunity for man-in-the-middle attacks.

**Comment by elarlang** [comment]
For me it's covered by:
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **9.1.1** | [MODIFIED] Verify that TLS is used for all connectivity between the client and external facing, HTTP-based services, and does not fall back to insecure or unencrypted communications. ([C8](https://owasp.org/www-project-proactive-controls/#div-numbering)) | ✓ | ✓ | ✓ | 319 |
| **14.4.5** | [MODIFIED] Verify that a Strict-Transport-Security header is included on all responses and for all subdomains, such as Strict-Transport-Security: max-age=31536000; includeSubdomains. | ✓ | ✓ | ✓ | 523 |

**Comment by elarlang** [comment]
@securitydave - do you think proposed requirement or attacking scenario is covered by 9.1.1 and/or 14.4.5?

**Comment by securitydave** [comment]
No, I'm talking about links within the pages of the application which are http: to external sites when the linked-to URL could have been https:. Even though you require TLS to access your own site's pages, you are needlessly exposing your uses by having them click an http: link.

**Comment by elarlang** [comment]
This case is covered by 
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **5.1.5** | Verify that URL redirects and forwards only allow destinations which appear on an allow list, or show a warning when redirecting to potentially untrusted content. | ✓ | ✓ | ✓ | 601 |

I don't support the solution that the application goes and checks is URL available via HTTPS as it open SSRF vector.

**Comment by elarlang** [comment]
@securitydave - is the situation described in the issue covered by current requirement 5.1.5?

**Comment by securitydave** [comment]
Elar, thank you for your great care! The ASVS is so great because of people like you.
> I don't support the solution that the application goes and checks is URL available via HTTPS as it open SSRF vector.
I agree. Not automated check by the app.

My thought is that when testing a web app, we would document a finding for any occurrence of a link to http: if that page supports https: thus avoiding the user experiencing redirect to https:. A code change would be needed to fix.

5.1.5 is similar, but is related to user input. My concern here is regarding links coded into the page. In a real-world case, this occurred in marketing-like links in footer of page template.

**Comment by elarlang** [comment]
I don't read 5.1.5 to be limited to "user input", it's in general redirecting to untrusted content.

I don't think we need new separate requirement for cover that.

What we can consider is to mention, what means "untrusted" in 5.1.5. From the issue - should we mention, "http" protocol there as untrusted.

Also, maybe we should split 5.1.5 to 2 separate requirements - one is dealing with redirections (usually via Location header, does not need extra action from user) and another showing links where going to the external page needs action (click) from the user.

**Comment by securitydave** [comment]
Your latest comment covers the issue I raised.
"showing links where going to the external page needs action (click) from the user"

**Comment by tghosth** [comment]
History for [5.1.5](https://appsecg.host/5.1):

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **5.1.5** | Verify that URL redirects and forwards only allow destinations which appear on an allow list, or show a warning when redirecting to potentially untrusted content. | ✓ | ✓ | ✓ | 601 |
| **5.1.5** | Verify that URL redirects and forwards only allow list destinations, or show a warning when redirecting to potentially untrusted content. | ✓ | ✓ | ✓ | 601 |
| **5.1.5** | Verify that URL redirects and forwards only allow whitelisted destinations, or show a warning when redirecting to potentially untrusted content. | ✓ | ✓ | ✓ | 601 |

Before this it basically dates back to 2.0 of ASVS.

> I don't read 5.1.5 to be limited to "user input", it's in general redirecting to untrusted content.

With respect @elarlang, I think that (rightly or wrongly) this would be interpreted as limited to user input.

> Also, maybe we should split 5.1.5 to 2 separate requirements - one is .... and another showing links where going to the external page needs action (click) from the user.

So my understanding is that @elarlang you are thinking more about this sort of warning when a user clicks a potentially untrusted link, correct?

![image](https://github.com/OWASP/ASVS/assets/13623828/1e949dda-cc82-48a2-a4b4-7086e1cb028a)

My understanding of what @securitydave is saying is that we should have a requirement that mandates that links written into an app should always be in https where possible. If that is the case, I have a few questions for @securitydave :

1) Are we talking about links provided by an untrusted user or are we talking about links manually added by the application developer 
2) Are we expecting an automated solution to address this (e.g. scans for links and upgrades them if possible) or is this more like manual guidance for developers/content writers?

**Comment by elarlang** [comment]
"user input"

> With respect @elarlang, I think that (rightly or wrongly) this would be interpreted as limited to user input.

It is limited to first part of the requirement (_Verify that URL redirects and forwards only allow destinations which appear on an allow list_) but it is not limited to second part (_or show a warning when redirecting to potentially untrusted content._).

If application has link (which is not end-user-input) and sends user away to another page, it makes sense to notice user that he/she is now leaving the app and will be on another app (to avoid confusions).

and this is exactly the reason I see the point to split the requirement like I wrote in https://github.com/OWASP/ASVS/issues/1603#issuecomment-1498546225:

> Also, maybe we should split 5.1.5 to 2 separate requirements - one is dealing with redirections (usually via Location header, does not need extra action from user) and another showing links where going to the external page needs action (click) from the user.


"Warning topic"

> So my understanding is that @elarlang you are thinking more about this sort of warning when a user clicks a potentially untrusted link, correct?

yes.

**Comment by securitydave** [comment]
@tghosth,

> 1. Are we talking about links provided by an untrusted user or are we talking about links manually added by the application developer

Links manually added by the application developer is what I had in mind.

> 2. Are we expecting an automated solution to address this (e.g. scans for links and upgrades them if possible) or is this more like manual guidance for developers/content writers?

Guidance for developers/content writers. Perhaps violations can be found by an automated test.

**Comment by tghosth** [comment]
Ok so as I see it, we have two suggested actions here:

1) @securitydave is suggesting a requirement mandating that all URLs included in an application (by the application develoeprs) are specifically HTTPs and not HTTP. If I am pen testing an application, I would not expect to see any requests to HTTP endpoints, only HTTPS.

2) @elarlang is suggesting splitting requirement 5.1.5 to specifically mandate warning users when they are being passed to an external, untrusted link. Similar to my screenshot in [my comment above](https://github.com/OWASP/ASVS/issues/1603#issuecomment-1592573725).

**Comment by elarlang** [comment]
Yes, split 5.1.5 and add separate (or merge to something if possible) "redirects only to https, if it is available".

**Comment by tghosth** [comment]
Ok so @elarlang I have tried to clarify these requirements but I think we will need to iterate on them a bit....

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **5.1.5** | [MODIFIED, SPLIT TO 5.1.7] Verify that the application will only redirect the user to a different URL directly from an application URL where the destination appears on an allow list. | ✓ | ✓ | ✓ | 601 |
| **5.1.7** | [ADDED, SPLIT FROM 5.1.5] Verify that the application shows a warning when redirecting to URL destinations which are not within the control of the application, even if this is a result of manually clicking on a link to that URL. | | ✓ | ✓ | 601 |

**Comment by EnigmaRosa** [comment]
I feel  like the new/edited requirements still don't address the original issue surrounding redirecting only to HTTPS.

**Comment by elarlang** [comment]
like @tghosth said himself, I think those new requirements need some work also, but I have not figure out yet how to improve them.

**Comment by elarlang** [comment]
@tghosth - I think we don't have covered this

From: https://github.com/OWASP/ASVS/issues/1603#issuecomment-1497625275

> My thought is that when testing a web app, we would document a finding for any occurrence of a link to http: if that page supports https: thus avoiding the user experiencing redirect to https:. A code change would be needed to fix.

**Comment by tghosth** [comment]
> @tghosth - I think we don't have covered this
> 
> From: [#1603 (comment)](https://github.com/OWASP/ASVS/issues/1603#issuecomment-1497625275)
> 
> > My thought is that when testing a web app, we would document a finding for any occurrence of a link to http: if that page supports https: thus avoiding the user experiencing redirect to https:. A code change would be needed to fix.

@elarlang do you not think that is covered by 9.1.1?

**Comment by elarlang** [comment]
> @elarlang do you not think that is covered by 9.1.1?

No, 9.1.1 covers that only https can be used when you come to the application.

Pointed out issue describing, that https should be used (when available), when you navigate or application navigates you away to another application.

**Comment by tghosth** [comment]
> > @elarlang do you not think that is covered by 9.1.1?
> 
> No, 9.1.1 covers that only https can be used when you come to the application.
> 
> Pointed out issue describing, that https should be used (when available), when you navigate or application navigates you away to another application.

So then I think we need to clarify 9.1.1 rather than creating a new issue

**Comment by tghosth** [comment]
@elarlang to work on this one

**Comment by elarlang** [comment]
Requirements to cover:

## original issue - use https instaed of http scheme for links, if https is available

Original issue - link to an external page must use the `https:` protocol (instead of the `http:`), if it is available

It is not and can not be covered by 9.1.1, see https://github.com/OWASP/ASVS/issues/1603#issuecomment-1775036949

The idea here should be:

> Verify that, if the application content, which is not end-user input, provides a URL or link, then it uses https schema instead of http schema if the https schema is available for the URL.

My concern here is - that developers may build "auto-validation" for validating the URL or "check if there https available for the URL" and it creates an SSRF vulnerability.


## split current 5.1.5

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **5.1.5** | Verify that URL redirects and forwards only allow destinations which appear on an allow list, or show a warning when redirecting to potentially untrusted content. | ✓ | ✓ | ✓ | 601 |


### redirect to allow-listed URL's

Current 5.1.5:

> _Verify that URL redirects and forwards only allow destinations which appear on an allow list_

Current proposal: https://github.com/OWASP/ASVS/issues/1603#issuecomment-1724909988

> _Verify that the application will only redirect the user to a different URL directly from an application URL where the destination appears on an allow list._

The context here is "auto-redirect". Appears in "allow-list" sounds like a fixed list of URLs, but we can also validate against patterns.

Requires more finetuning, but the direction:

Proposal: _Verify that the application can auto-redirect the user only to validated allow-listed destinations._


### Show warning when navigating away

Current 5.1.5

> Verify that URL redirects and forwards /../ show a warning when redirecting to potentially untrusted content.

Current proposal: https://github.com/OWASP/ASVS/issues/1603#issuecomment-1724909988

> Verify that the application shows a warning when redirecting to URL destinations which are not within the control of the application, even if this is a result of manually clicking on a link to that URL.

Is it reasonable to require it from EVERY link or URL? Or how to define the reason to warn the user, is it:

  * hey, you are going to **navitate away** from the application, do you want to continue?
  * hey, you are going to "non-trusted" content, do you want to continue?

For example, the content of Google is not under the application control, but should we show warning for navigating to Google? What risk we mitigate when we warn user before navitaging to Google?

I think it requires some clarification, why exactly we need to warn users.

**Comment by elarlang** [comment]
ping @tghosth

**Comment by tghosth** [comment]
Proposal 1:

I would suggest (L1/2):

> Verify that the application will only auto-redirect the user to URL destinations outside of the application's control which are validated and on an allow-list.

I would suggest (L3):

> Verify that the application shows a warning when manually redirecting to URL destinations outside of the application's control, even if this is a result of manually clicking on a link to that URL.

What do you think? @elarlang

**Comment by elarlang** [comment]
The question is more about the requirements.  I'm ok with the proposed levels like the levels are described at the moment, but as the topic of the defining levels is opened, there is no point in discussing this.

**Comment by tghosth** [comment]
Are you ok with the proposed text?

**Comment by elarlang** [comment]
Ok, it as a bit non-untuitive to follow comment. So, in total we are covering 3 requirements here. I modified my comment above (https://github.com/OWASP/ASVS/issues/1603#issuecomment-1962891615) to point out clearly "requirement 1", "requirement 2", "requirement 3".

... or should I split to 3 different issues...

### requirement 1:

Latest proposal:
> Verify that, if the application content, which is not end-user input, provides a URL or link, then it uses https schema instead of http schema if the https schema is available for the URL.

There were no comments for this one.

### requirement 2:

Previous proposal:
> Verify that the application will only auto-redirect the user to URL destinations outside of the application's control which are validated and on an allow-list.

Proposal from Josh:
> Verify that the application will only redirect the user to a different URL directly from an application URL where the destination appears on an allow list.

I think the auto-redirect is important message here - you can redirect user to wherever, but then you need to show the warning. Without the auto-redirect, we can merge it to requirement 3.


### requirement 3:

Previous proposal:
> Verify that the application shows a warning when redirecting to URL destinations which are not within the control of the application, even if this is a result of manually clicking on a link to that URL.

Proposal from Josh:
> Verify that the application shows a warning when manually redirecting to URL destinations outside of the application's control, even if this is a result of manually clicking on a link to that URL.

"manually redirecting" is confusing here for me.

Not the proposal for the requirement, but just an attempt to cover some points:
> Verify, that if the application provides a functionality that navigates user away from the application control to not previously allow listed URL (Origin), then it show warning to to user with options to navigate away or not.

**Comment by tghosth** [comment]
### Requirement 1

I still feel like his is a little too niche.

### Requirement 2:

Updated proposal:

> Verify that the application will only **automatically** redirect the user to a different URL directly from an application URL where the destination appears on an allow list.

### Requirement 3:

Updated proposal:

> Verify that the application shows a notification when the user is being redirected to a URL outside of the application's control, with an option to cancel the navigation.


### Location

Requirements 2 and 3 are split from 5.1.5 and should get moved to the new v50 section.

**Comment by elarlang** [comment]
> Verify that the application will only automatically redirect the user to a different URL directly from an application URL where the destination appears on an allow list.

I'm analyzing it a bit more - this one does not fit V50, as it is a problem also without a browser. It can be an important weakness combined with SSRF and follow-redirection for bypassing some (logical) outgoing connection limitations.

**Comment by tghosth** [comment]
Hmm, ok so I think just make a decision about the section, I don't want to get bogged down on this

**Comment by elarlang** [comment]
I opened PR (#1898 ) to solve two requirements from the discussion here.

@securitydave - at the moment we don't address the original requirement or problem statement from the opened issue. Although I agree that technically it could improve the security, in practice it is a bit too niche for ASVS.

If you feel, that it is really important and widespread problem enough, we can consider covering it in the recommendations section.
