### ISSUE TITLE
business requirements should specify allowed file types to upload

### ISSUE THREAD

**Issue by securitydave** [OWASP/ASVS#1604]
12.1.x (additional requirement)
Verify that the application only allows upload of whitelisted file types determined by business requirement. (Each allowed file type should be specified by mime/content type and associated file extension. The allowed file types must be specified in each instance of a file upload feature in the application.)

**Comment by elarlang** [comment]
I though I had opened issue for that, but did not find it. May it just did it in my head :)

Anyway, it's documentation requirement - to be able to implement and / or verify that users are allowed to upload only allowed files, you need to have first documented, what are allowed.

Belongs to list #1231

**Comment by elarlang** [comment]
By current logic, requirement to category 1.12.

**Comment by securitydave** [comment]
Yes, first thing I ask when looking at file upload is what file types are allowed. If not specified, then this is for the product owner/business owner to do. Then the feature should be implemented accordingly.

**Comment by elarlang** [comment]
We need to look here separately 2 requirements:

  * implementation requirement (current 12.2.1)
  * documentation requirement - need to add

Documentation requirement(s) should carry points:

  * for each file upload functionality / form / file category there must be documentation of allowed file types (for 12.2.1)
  * analyzed that application is able to process allowed file with provided type (extension), size (including unpacked size) and define size limits when needed (for 12.1.1, 12.1.2)

Maybe something else?

Related/mentioned requirements:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **12.1.1** | [MODIFIED] Verify that the application will only accept files of a size which it can process without causing a loss of performance or denial of service attack. | ✓ | ✓ | ✓ | 400 |
| **12.1.2** | Verify that the application checks compressed files (e.g. zip, gz, docx, odt) against maximum allowed uncompressed size and against maximum number of files before uncompressing the file. | | ✓ | ✓ | 409 |
| **12.2.1** | Verify that files obtained from untrusted sources are validated to be of expected type based on the file's content. | | ✓ | ✓ | 434 |

To improve the requirement 12.2.1 there is opened issue: https://github.com/OWASP/ASVS/issues/1291

**Comment by elarlang** [comment]
@tghosth - I think I need wording help here for proposal. base information is ready (in my opinion).

**Comment by tghosth** [comment]
Fair one but I have marked this as "major rework" as I think we will need to consider it in the overall v12 rewrite. Is that ok?

**Comment by elarlang** [comment]
Note, that I added to the description (https://github.com/OWASP/ASVS/issues/1604#issuecomment-1570884021): accepted files (size, content) is safe for end-users to download and process them

**Comment by jmanico** [comment]
This thread has gotten out of hand and I want to address the OP and close this out.

The original posted asked about "Verify that the application only allows upload of whitelisted file" which is already covered in detail in the current 12.2.1

12.2.1 | [MODIFIED] Verify that when the application accepts a file, it checks if the file extension matches an expected file extension and validates that the contents correspond to the type represented by the extension. This includes, but is not limited to, checking the initial 'magic bytes', performing image re-writing, and using specialized libraries for file content validation. |   | ✓ | ✓ | 434
-- | -- | -- | -- | -- | --

I would ilke to close this out and have folks open a new comment if they want to address issues other than the request from the OP.

**Comment by elarlang** [comment]
The problem with 12.2.1 it is implementation requirement without documentation requirement (that is proposed to add with this issue) - close 100% of cases, when I ask the question from the client who ordered pen-test, what kind of files you expected to be allowed to be uploaded, they don't know the answer. And as they don't know, most likely it also allows them to upload files that they don't need causing a wider attack surface. So the documentation requirement is a must.

Points to cover are written here https://github.com/OWASP/ASVS/issues/1604#issuecomment-1570884021, need help with wordsmithing the requirement.

**Comment by jmanico** [comment]
So I like 12.2.1. For documentation, how about we add one very similar but more brief like:

12.2.1 | [MODIFIED] Verify that application documentation checks if the uploaded file extension matches an expected file extension or file types. |   | ✓ | ✓ | 434
-- | -- | -- | -- | -- | --

**Comment by tghosth** [comment]
@elarlang what do you think about my suggestion: https://github.com/OWASP/ASVS/issues/1604#issuecomment-2336774938

**Comment by elarlang** [comment]
> Verify that the application documentation defines the file types which are permitted for upload, the file extension/s expected for each type, the maximum size (including unpacked size) and how to ensure that files are safe for end-users to download and process them.

* Should it be conditional, "if the application allows uploading files" - or is it a clear common sense and no need that noise into the requirement?
* Should the requirement be oriented "per functionality", "or per form" / "per controller" - for example, from an admin interface, that is also part of the same application it is allowed to upload different set of files than from public web page

**Comment by tghosth** [comment]
> Here is a suggestion that considers Elar's comments.
> 
> _Verify that, if the application allows uploading files, the documentation defines the permitted file types, expected file extensions, and maximum size (including unpacked size) for each upload feature. Additionally, ensure that the documentation specifies how files are made safe for end-users to download and process._

I like this.

@elarlang what do you think?

**Comment by jmanico** [comment]
There may be different upload features in the same application with different upload rules....

**Comment by tghosth** [comment]
Yeah Elar included this in the requirement :)
![image](https://github.com/user-attachments/assets/d8d42620-9c1c-46fb-8e5d-565b25fb9a22)

**Comment by jmanico** [comment]
Gotchya. Thanks Josh and Elar!
