### ISSUE TITLE
2.23 - expand explanation 

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#161]
_Verify that administrative interfaces are not accessible to untrusted parties._

Expanded:
Verify that administrative interfaces are not accessible to untrusted parties. This includes login forms to administrative interfaces (e.g. IP level controls to admin login forms).

**Comment by danielcuthbert** [comment]
now numbered 2.32 in 3.1 and agree but amended slightly

Verify that access to administrative interfaces are strictly controlled and not accessible to untrusted parties.
