### ISSUE TITLE
Insert NIST "Guidelines for Media Sanitization" within IoT Appendix

### ISSUE THREAD

**Issue by cmlh** [OWASP/ASVS#1611]
["1.8 Data handling" of MVSP](https://github.com/vendorsec/mvsp/blame/master/packages/mvsp/mvsp.en.asciidoc#L50) mandates `Ensure media sanitization processes based on NIST SP 800-88 or equivalent are implemented`

The parent of all MVSP issues is #1151.

[Appendix C: Internet of Things Verification Requirement C25](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x93-Appendix-C_IoT.md#security-verification-requirements) states "Verify that the device wipes firmware and sensitive data upon detection of tampering or receipt of invalid message._".

Therefore, modify [Appendix C: Internet of Things Verification Requirement C25](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x93-Appendix-C_IoT.md#security-verification-requirements) to cite [NIST Special Publication (SP) 800-88, Revision 1, Guidelines for Media Sanitization](https://www.nist.gov/privacy-framework/nist-sp-800-88)

**Comment by mgargiullo** [comment]
I wish the ISVS hadn't stalled

**Comment by tghosth** [comment]
Closing as I don't think we will be modifying IoT section

**Comment by tghosth** [comment]
The IoT section was more as a convenience to anyone who wants to go and create a more detailed standard and I am not convinced we will include it in 5.0 anyway

**Comment by tghosth** [comment]
I have opened #1688 to track whether we deprecate this or not.
