### ISSUE TITLE
Seeking clarification in 2.6.2 that this is server side

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1614]
Suggest a change to specify this is server side, from:

2.6.2 | [MODIFIED] Verify that lookup secrets with less than 112 bits of entropy (19 random alphanumeric characters or 34 random digits) are hashed with an approved password storage hashing algorithm which incorporates a 32 bit random salt. If the secret has 112 bits of entropy or more, a standard hash function can be used. |   | ✓ | ✓ | 330 | 5.1.2.2
-- | -- | -- | -- | -- | -- | --

... to perhaps ...

2.6.2 | [MODIFIED] Verify that lookup secrets stored on your server with less than 112 bits of entropy (19 random alphanumeric characters or 34 random digits) are hashed with an approved password storage hashing algorithm that incorporates a 32-bit random salt. A standard hash function can be used if the secret has 112 bits of entropy or more. |   | ✓ | ✓ | 330 | 5.1.2.2
-- | -- | -- | -- | -- | -- | --

**Comment by tghosth** [comment]
Requirement history:

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.6.2** | [MODIFIED] Verify that lookup secrets with less than 112 bits of entropy (19 random alphanumeric characters or 34 random digits) are hashed with an approved password storage hashing algorithm which incorporates a 32 bit random salt. If the secret has 112 bits of entropy or more, a standard hash function can be used. | | ✓ | ✓ | 330 | 5.1.2.2 |
| **2.6.2** | [MODIFIED] Verify that lookup secrets with 112 bits of entropy or more (typically 19 random alphanumeric characters or 34 random digits is sufficient) are hashed with an approved password storage hashing algorithm. If the secret has less than 112 bits of entropy, a 32bit random salt should be incorporated. | | ✓ | ✓ | 330 | 5.1.2.2 |
| **2.6.2** | [MODIFIED] Verify that lookup secrets have sufficient randomness (112 bits of entropy), or if less than 112 bits of entropy, are hashed with an approved password storage hashing algorithm. | | ✓ | ✓ | 330 | 5.1.2.2 |
| **2.6.2** | Verify that lookup secrets have sufficient randomness (112 bits of entropy), or if less than 112 bits of entropy, are hashed with an approved password storage hashing algorithm. | | ✓ | ✓ | 330 | 5.1.2.2 |
| **2.6.2** | Verify that lookup secrets have sufficient randomness (112 bits of entropy), or if less than 112 bits of entropy, salted with a unique and random 32-bit salt and hashed with an approved one-way hash. | | ✓ | ✓ | 330 | 5.1.2.2 |

**Comment by jmanico** [comment]
I’d much rather just suggest Argon2id. We do not have to talk about salting, the algorithms of the day for password storage already do this (bcrypt, Argon2id, PBKDF2).

I’m not sure we need to actually suggest bit sizes and similar. It would be way easier for developers if we just pointed to the work of the password storage cheatsheet.


Forgive me if I’m out of context with this suggestion.

**Comment by tghosth** [comment]
@jmanico so this section is talking about "lookup secrets" as opposed to regular passwords.

Lookup secrets are defined by NIST as:

> ...pre-generated lists of secret codes, similar to Transaction Authorization Numbers (TAN), social media recovery codes, or a grid containing a set of random values. These are distributed securely to users. These lookup codes are used once, and once all used, the lookup secret list is discarded. This type of authenticator is considered "something you have".

This requirement is specifically worded in accordance with NIST .

Your original suggestion was (main change bolded):

> [MODIFIED] Verify that lookup secrets stored **on your server** with less than 112 bits of entropy (19 random alphanumeric characters or 34 random digits) are hashed with an approved password storage hashing algorithm that incorporates a 32-bit random salt. A standard hash function can be used if the secret has 112 bits of entropy or more.

I proposed a very similar change:

> [MODIFIED] Verify that lookup secrets stored **at the back-end** with less than 112 bits of entropy (19 random alphanumeric characters or 34 random digits) are hashed with an approved password storage hashing algorithm that incorporates a 32-bit random salt. A standard hash function can be used if the secret has 112 bits of entropy or more.

Are you comfortable with my suggestion?

**Comment by jmanico** [comment]
Yes, way better.
