### ISSUE TITLE
2.33 - redundant control 

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#162]
_Browser autocomplete, and integration with password managers are permitted unless prohibited by risk based policy._

Read as: 
You are allowed to do this, unless you are not allowed to do this? What if you shouldn't do this, but policy doesn't exist?

This is already covered by another autocomplete control.

**Comment by danielcuthbert** [comment]
rewritten to "Verify that the application is compatible with browser based and third party password managers, unless prohibited by risk based policy"
