### ISSUE TITLE
Resource exhaustion, improper closing of resources.

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1620]
Do we have an ASVS item that covers [CWE-404](https://cwe.mitre.org/data/definitions/404.html)? Should we have one?

**Comment by elarlang** [comment]
To make it more clear, can you provide an example?

**Comment by elarlang** [comment]
But based on title, for reporting it I would look to V11 category:
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **11.1.3** | Verify the application has appropriate limits for specific business actions or transactions which are correctly enforced on a per user basis. | ✓ | ✓ | ✓ | 770 |
| **11.1.5** | Verify the application has business logic limits or validation to protect against likely business risks or threats, identified using threat modeling or similar methodologies. | ✓ | ✓ | ✓ | 841 |

Based on CWE description, we don't have really 1:1 match for the issue.

**Comment by jmanico** [comment]
This looks like “don’t forget to close database connections” and the risk here is DOS

I’m inclined to drop this requirement, this kind of mistake will not last long and it’s only loosely a security issue.

**Comment by elarlang** [comment]
Maybe we should look at it (additionally) as business logic requirement - like you can not bron some goods forever from some shop or some places in cinema (like you don't buy them yourself but don't allow to buy anyone else as well).

In a way it is covered by requirements like:
* V11.1.3 Verify the application has appropriate limits for specific business actions or transactions which are correctly enforced on a per user basis.
* V11.1.5 Verify the application has business logic limits or validation to protect against likely business risks or threats, identified using threat modeling or similar methodologies.

**Comment by tghosth** [comment]
> For the requirement there should be also clear - what and how it should be tested. From current wording I don't get it.
> 
> Maybe the proposed requirement should give some examples to make it more understandable? Database connections, temporary files, ...

Yeah basically this

> Maybe we should look at it (additionally) as business logic requirement - like you can not bron some goods forever from some shop or some places in cinema (like you don't buy them yourself but don't allow to buy anyone else as well).
> 
> In a way it is covered by requirements like:
> 
>     * V11.1.3 Verify the application has appropriate limits for specific business actions or transactions which are correctly enforced on a per user basis.
> 
>     * V11.1.5 Verify the application has business logic limits or validation to protect against likely business risks or threats, identified using threat modeling or similar methodologies.

I don't agree with this, it is a technical issue rather than a business logic problem.

I can see that @jmanico doesn't love the idea. What do you think @elarlang ?

**Comment by elarlang** [comment]
Maybe I'm a bit lost here. If we just say that application should close the connections, then I agree with Jim (Jim, mark to the calendar!) as this problem can not exists too long time.

Another point of view is - resources should have an timeout when they are dead or other part does not respond etc. Otherwise it's easy to use this kind of issues as Denial of Service attacks.

**Comment by tghosth** [comment]
> Another point of view is - resources should have an timeout when they are dead or other part does not respond etc. Otherwise it's easy to use this kind of issues as Denial of Service attacks.

So yeah this is kind of the point. It is a little niche but potentially still problematic

**Comment by jmanico** [comment]
> Maybe I'm a bit lost here. If we just say that application should close the connections, then I agree with Jim (Jim, mark to the calendar!) as this problem can not exists too long time.
> 
> Another point of view is - resources should have an timeout when they are dead or other part does not respond etc. Otherwise it's easy to use this kind of issues as Denial of Service attacks.

Elar AGREED WITH ME??????? Mercury is in retrograde?

**Comment by elarlang** [comment]
In a way it's separate topic, but also related with this one.

To one pen-test case I reported, that for every resource or external connection, there must be analyzed and documented expected behaviour - how application need to behave if some resource (e.g. some external API) is not available.

It is related with opened issue as if resource is not available, there is possibility that all connection start waiting some timeout, which can be too long (example 30sec or 5min) and it gives quite easy vector for denial of service.

So additionally, documentation must contain - what is the timeout for each service (default timeout) or request (if some requires extra solution) and an application should monitor "slow responses" (which also requires definition, what is "slow").

**Comment by tghosth** [comment]
> In a way it's separate topic, but also related with this one - to one pen-test case I reported, that for every resource or external connection, there must be analyzed and documented expected behaviour - how application need to behave if some resource (e.g. some external API) is not available.
> 
> It is related with opened issue as if resource is not available, there is possibility that all connection start waiting some timeout, which can be too long (example 30sec or 5min) and it gives quite easy vector for denial of service.
> 
> So additionally, documentation must contain - what is the timeout for each service (default timeout) or request (if some requires extra solution) and an application should monitor "slow responses" (which also requires definition, what is "slow").

I think this is a separate topic and would suggest needs a separate issue

**Comment by tghosth** [comment]
> So I think that 11.1.3 is related to business resources whereas I am talking about raw infrastructure resources so I think a requirement related to CWE-404 should be in section V12 which talks about "File and **Resources**".
> 
> I would propose something like:
> 
> | # | Description | L1 | L2 | L3 | CWE |
> | :---: | :--- | :---: | :---: | :---: | :---: |
> | **12.x.x** | Verify that the application proactively releases system resources, **such as database connections, open files, etc**, when it finishes using them to prevent resource exhaustion. | | ✓ | ✓ | 404 |
> 

Seeing as how we continued discussing this, @elarlang, do you prefer this enhancement to my suggestion from https://github.com/OWASP/ASVS/issues/1620#issuecomment-1576824292 ?

**Comment by tghosth** [comment]
So I think the CWE has a reasonably good description:
https://cwe.mitre.org/data/definitions/404.html

How do you attack it? If you find a function that uses a resource but doesn't close it properly (such as a database connection), you can keep using it until it can no longer open any connections and the app then breaks.

How do you test it? Might be tricky in a pen test but it is L2 so you can also ask or review code.

**Comment by elarlang** [comment]
> If you find a function that uses a resource but doesn't close it properly (such as a database connection), you can keep using it until it can no longer open any connections and the app then breaks.

I don't find it realistic and widespread problem with good-case scenario when application just don't close the connection. With database example, usually the connection pool is just few hundreds, if an application do not close them, it's dead really soon.

Have you seen this problem in practice? What is reason to propose the requirement (exatly for "just leaves connection opened")?

I can not see the reason to have requirement just for that, but I can see the reason to address (with the main focus) too long time-outs which is usable for attack scenario you described.

**Comment by tghosth** [comment]
Calling in the WG :)

**Comment by elarlang** [comment]
To get answers to those questions could help WG as well
> Have you seen this problem in practice? What is reason to propose the requirement (exatly for "just leaves connection opened")?

**Comment by jmanico** [comment]
Resource exhaustion in Java typically refers to scenarios where a Java program runs out of crucial resources, such as memory or threads, which can lead to performance problems or even application crashes. Here's an example of resource exhaustion related to memory:

**Java Heap Space Exhaustion**:

In Java, memory is allocated from the heap to store objects and data. If your program consumes more memory than is available in the heap, you'll encounter a `java.lang.OutOfMemoryError`. This can happen for various reasons, including:

1. **Memory Leaks**: If your program has memory leaks, meaning it retains references to objects that are no longer needed, it will gradually consume more and more memory until it exhausts the heap.

   ```java
   List<String> list = new ArrayList<>();
   while (true) {
       list.add("This is a memory leak example.");
   }
   ```

2. **Large Data Sets**: If your program loads and processes large data sets without releasing memory appropriately, it can lead to heap space exhaustion.

   ```java
   byte[] data = new byte[1000000000]; // Attempting to allocate a large array
   ```

3. **Concurrency Issues**: In multi-threaded applications, if there are issues with thread management, such as creating too many threads or not properly managing thread lifecycles, it can lead to excessive memory consumption.

   ```java
   for (int i = 0; i < 1000; i++) {
       new Thread(() -> {
           // Some resource-intensive task
       }).start();
   }
   ```

To avoid these types of resource exhaustion, it's essential to properly manage memory, close resources when they are no longer needed, and carefully design your application to handle concurrency if it involves multiple threads. Monitoring tools and profiling can help identify memory-related issues early in the development process.

**Comment by elarlang** [comment]
@jmanico  - how your new comment (copy-paste from ChatGPT?) is aligned with your previous one: https://github.com/OWASP/ASVS/issues/1620#issuecomment-1577210486

@tghosth - is Jim's new comment anyhow related with problems which you try to address with your proposal?

**Comment by csfreak92** [comment]
I'm also a little lost. Which is the main problem we are tackling in this issue? Is it about the resource exhaustion issue? If that's the case, it merits adding **closing of threads** as an important item in @tghosth's original proposed version such as: 

> **12.x.x**	Verify that the application proactively releases system resources, **such as database connections, open files, threads, etc**, when it finishes using them to prevent resource exhaustion.		✓	✓	404

+1 with you all. I am inclined to add this requirement as well. I just added the threads thing to Josh's proposed requirement.

**Comment by tghosth** [comment]
I think Jim's text is similar but not exactly the same. I agree with @csfreak92's addition as it is certainly another resource.

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **12.x.x** | 	Verify that the application proactively releases system resources, such as database connections, open files, threads, etc, when it finishes using them to prevent resource exhaustion. | | ✓ | ✓ | 404 |

Let's see if anyone else provides their thoughts.

**Comment by elarlang** [comment]
When searching CWE for other issues, then maybe more suitable here?

CWE-404: Improper Resource Shutdown or Release
The product does not release or incorrectly releases a resource before it is made available for re-use.
When a resource is created or allocated, the developer is responsible for properly releasing the resource as well as accounting for all potential paths of expiration or invalidation, such as a set period of time or revocation.

CWE-772: Missing Release of Resource after Effective Lifetime
The product does not release a resource after its effective lifetime has ended, i.e., after the resource is no longer needed.
When a resource is not released after use, it can allow attackers to cause a denial of service by causing the allocation of resources without triggering their release. Frequently-affected resources include memory, CPU, disk space, power or battery, etc.

**Comment by elarlang** [comment]
I was just pointing it out when found similar one. But now looking at it, maybe it makes sense to cover CWE-772 as part of proposed requirement as well?

**Comment by tghosth** [comment]
> I was just pointing it out when found similar one. But now looking at it, maybe it makes sense to cover CWE-772 as part of proposed requirement as well?

What would you add to the current text that is not already there?

**Comment by elarlang** [comment]
I created new issue instead: https://github.com/OWASP/ASVS/issues/1778

**Comment by tghosth** [comment]
So do you think we can merge #1777?

**Comment by elarlang** [comment]
In general yes, but it would be good when we can get #1778 into to requirement list as well then it's better to ask feedback. otherwise it contains already known missing requirement (in my opinion).

**Comment by elarlang** [comment]
Also, I don't think V12 is best place for those requirement. Maybe we need to create something completely new, maybe we can merge it to current V10. We had similar discussion (https://github.com/OWASP/ASVS/issues/1324#issuecomment-1207414877) to move 12.6.1 away from V12 to V14.

We can change/improve category later, it's important to get feedback to requirements.
