### ISSUE TITLE
Uploaded file extension should match content type

### ISSUE THREAD

**Issue by securitydave** [OWASP/ASVS#1623]
We should have a requirement like:

12.2.x (new)	Verify that user-submitted filename extension matches content type.
CWE-646

Also, the extension and content type must be allowed as per https://github.com/OWASP/ASVS/issues/1604.

**Comment by elarlang** [comment]
I think this issue is duplicate of https://github.com/OWASP/ASVS/issues/1291

**Comment by elarlang** [comment]
@securitydave - I close it as duplicate of #1291. Please add your proposals there.
