### ISSUE TITLE
6.2.4's most important use case is quantum computers

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1630]
Quantum computers will break a lot of modern crypto, so I suggest we change:

6.2.4 | Verify that random number, encryption or hashing algorithms, key lengths, rounds, ciphers or modes, can be reconfigured, upgraded, or swapped at any time, to protect against cryptographic breaks. (C8) |   | ✓ | ✓ | 326
-- | -- | -- | -- | -- | --

to:

6.2.4	Verify that random number, encryption or hashing algorithms, key lengths, rounds, ciphers or modes, can be reconfigured, upgraded, or swapped at any time, to protect against cryptographic breaks and the future of quantum computing. ([C8](https://owasp.org/www-project-proactive-controls/#div-numbering))		✓	✓	326

**Comment by elarlang** [comment]
Can we have some argumentation behind that as well? I have heard the same sentence over 15+ years already.

**Comment by elarlang** [comment]
I prefer we don't try to predict future and we address the topic when we know exactly what is the threat then and what must be done to mitigate it.

**Comment by tghosth** [comment]
Quantum was also mentioned in #1411. I am going to keep this as a reminder for the rework activity.

**Comment by tghosth** [comment]
Ok I think #1411 is going to become the primary issue for reworking V6 so I am going to close this issue if that is ok with you @jmanico

**Comment by jmanico** [comment]
Sounds good Daniel.
