### ISSUE TITLE
8.1.4 does not suggest a practical solution or method

### ISSUE THREAD

**Issue by endergzr** [OWASP/ASVS#1639]
8.1.4 in "V8.1 General Data Protection" is not practicle. I see that many institutions send their application logs to a solution such as SIEM/SOAR or they are using WAF to detect, alarm and take an action. 

8.1.4 | Verify the application can detect and alert on abnormal numbers of requests, such as by IP, user, total per hour or day, or whatever makes sense for the application. |   | ✓ | ✓ | 770
-- | -- | -- | -- | -- | --

Instead of this standard, I suggest that this subject can be examined in more detail under the title of "Secure Log Forwarding" in a different field such as 8.4.x(new). NIST 800-92 (Guide to Computer Security Log Management) can be used as a guide. We can use 800-92, 2.1.3 "Applications" section. I would like to open this issue for discussion and contribute if you allow.

**Comment by elarlang** [comment]
> I would like to open this issue for discussion and contribute if you allow.

You already did :)

We have related issue opened for 8.1.4 https://github.com/OWASP/ASVS/issues/1272

Do you want to open some new topic or proposal or you can put your input to the already opened issue?

**Comment by endergzr** [comment]
I can input to the already opened issue, thank you.
