### ISSUE TITLE
3.3 - out dated control 

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#165]
_Verify that sessions timeout after a specified period of inactivity._

This is somewhat outdated and unrealistic with modern technologies and marketing requirements. Especially for social media and communication applications. A user may ask, well if it's good enough for Facebook, then why? 

Sessions timeout after a specified period of inactivity should be shifted to ASVS Level 3 only. Other applications should have compensating controls.

**Comment by danielcuthbert** [comment]
agreed and amended in 3.1
