### ISSUE TITLE
3.4 - outdated control

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#166]
Similar to 3.3. 

_"Verify that sessions timeout after an administratively-configurable maximum time period regardless of activity (an absolute timeout)."_

This is somewhat outdated and unrealistic with modern technologies and marketing requirements. Especially for social media and communication applications. A user may ask, well if it's good enough for Facebook, then why?

Hard sessions timeout should be shifted to ASVS Level 3 only. Other applications should have compensating controls.

**Comment by danielcuthbert** [comment]
Totally agree, this is no longer best practice. moving to a level 3 control only.
