### ISSUE TITLE
8.2.1 - mention or require cache-control no-store

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1674]
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **8.2.1** | Verify the application sets sufficient anti-caching headers so that sensitive data is not cached in modern browsers. | ✓ | ✓ | ✓ | 525 |

Is there any actual alternative for `Cache-Control: no-store`?

If there is not, I recommend to at least mention this as an example.

The problem to solve: I see often `Cache-Control: no-cache`, but interpretation of the value `no-cache` can be misleading here.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#no-cache

> Note that no-cache does not mean "don't cache". no-cache allows caches to store a response but requires them to revalidate it before reuse. If the sense of "don't cache" that you want is actually "don't store", then no-store is the directive to use.

`no-store` should be used when response contains sensitive data.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#no-store

> The no-store response directive indicates that any caches of any kind (private or shared) should not store this response.

**Comment by elarlang** [comment]
... and like usual - 0 arguments. What is the reason to have requirement for `no-cache` in ASVS?

**Comment by elarlang** [comment]
... and can you explain me, how `no-cache` value in `Cache-Control` HTTP response header prevents CSRF attack?

**Comment by elarlang** [comment]
Your comments are technically incompetent.

Do you actually understand that `no-cache` does not disallow caching which is quoted in the issue and which is the main point of the issue?

**Comment by elarlang** [comment]
No. My comment is valid.

Additionally you should understand the difference between cache for middleware (which you are referring) and the cache configuration for browser (which is the issue here).

**Comment by elarlang** [comment]
> no-cache prevents CSRF by forcing the web browser to revalidate the Synchronizer Token with the web server before sending the POST request.

And you don't dare here to explain, how and why this `no-cache` actually works in this process? I _assume_ (which is in general bad thing to do) that there is extra HTTP request to achieve fresh tokens before data-changing request (in your example HTTP request with POST method). But it's not possible to read it out from your line - how browser is revalidating it.

Setting `no-cache` is not defence against CSRF. If you cache tokens, you may cause new vector to do it or just break functionality (because client sends invalid tokens), but it's not defense against CSRF. You are just copy-pasting lines from ASP NET manual without understanding the context (middleware vs browser cache).

**Comment by elarlang** [comment]
Change my opinion on what?

The topic here is - client-side cache and sensitive data. Which means you are not allowed to store any cache on the client side and if you don't have any cache on the client side, validating it is not the case.

Just stop digging your hole deeper.

**Comment by tghosth** [comment]
As far as I can tell, the CSRF point here is very niche and probably not worth having its own requirement.

@elarlang, I found [this blog on caching](https://grayduck.mn/2021/09/13/cache-control-recommendations/) which would seem to indicate that a more complex config is needed to fully eliminate caching.

**Comment by tghosth** [comment]
So what do you think about:

> [MODIFIED] Verify the application sets sufficient anti-caching headers (including but not limited to Cache-Control: no-store) so that sensitive data is not cached in modern browsers.

@elarlang

**Comment by elarlang** [comment]
I also think that the part `including but not limited to` is not needed in the requirement.

But this no-cache vs csrf topic is non-stop facepalm here. Just stop it.

**Comment by tghosth** [comment]
So @elarlang you also prefer:

> [MODIFIED] Verify the application sets sufficient anti-caching headers (i.e. Cache-Control: no-store) so that sensitive data is not cached in modern browsers.

**Comment by elarlang** [comment]
It will be in memory or DOM anyway, can not take away that.
