### ISSUE TITLE
3.10 - spelling and potentially splitting control into separate vulnerbailities

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#168]
Verify that only session ids generated by the application framework are recognized as active by the application.

'IDs', not "ids".
"recognised" not 'recognized', Straya! 

Perhaps this could be broken into separate controls, like: 

- Session Hijacking
- Session ID Recycling 
- Session Fixation. 

...after all, this is what this control is summarising.

**Comment by ordinaehs** [comment]
On top of that, I propose at least changing the wording to "are recognized as valid" instead of "active".
