### ISSUE TITLE
Deprecate the IoT appendix

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1688]
Nothing has really happened with this during 4.x. Do we still want to include it? If not, we should remove it and include an explanation in the ASVS introduction. (see previous discussion on #1611).

**Comment by elarlang** [comment]
it's clearly out of scope and I can not see any reason, why some other project need be as appendix in ASVS. Also I don't think we need this explanation in introduction, it is enough to point it out in some "changes overview from v4 to v5" document.

**Comment by ImanSharaf** [comment]
I don't believe that we need this anymore.

**Comment by tghosth** [comment]
Ok, we will delete it as part of the draft preparation stage (we arent there yet :) )

**Comment by elarlang** [comment]
I think we don't need to wait the "draft preparation" for deleting it.

_Bleeding edge_ should carry all new changes for getting feedback. IoT appendinx is not something what we want to get into v5.0 so why should keep it there now (for giving others signal, that we will keep it there)?

If needed, reference to IoT project can be added to [appendix B](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x91-Appendix-B_References.md).

**Comment by tghosth** [comment]
Fair point, can you open a PR?
