### ISSUE TITLE
Suggest to Add CWE-615: Inclusion of Sensitive Information in Source Code Comments in V8 Data Protection

### ISSUE THREAD

**Issue by Rado0z** [OWASP/ASVS#1695]
I would like to suggest adding the CWE-615: Inclusion of Sensitive Information in Source Code Comments in V8 Data Protection

## V8.3 Sensitive Private Data

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---:| :---: | :---: |
| **8.3.9** | Information, such as secret keys or passwords, is not stored or commented on within the source code. |   |   | ✓ | 615 |

**Comment by elarlang** [comment]
First, sensitive data must be classified and divided into protection layers. It is covered by:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.8.1** | [MODIFIED, MERGED FROM 8.3.4, LEVEL L2 > L1] Verify that all sensitive data created and processed by the application has been identified and classified into protection levels, and ensure that a policy is in place on how to deal with sensitive data. | ✓ | ✓ | ✓ | 213 |

And I think the proposed requirement itself is covered by current 2.10.4.

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.10.4** | [GRAMMAR] Verify passwords, integrations with databases and third-party systems, seeds and internal secrets, and API keys are managed securely and not included in the source code or stored within source code repositories. Such storage should resist offline attacks. The use of a secure software key store (L1), hardware TPM, or an HSM (L3) is recommended for password storage. | | ✓ | ✓ | 798 | |

Do you agree it's covered and we can close it as duplicate or do you have any extra proposals or recommendations?

**Comment by Rado0z** [comment]
Yeah, I totally agree with 2.10.4 because this test is all about the L2/L3 approach. So you can close it as a duplicate, and I'm really sorry for overlooking that requirement.
