### ISSUE TITLE
new requirement: end-user should not be able to give and/or manipulate headers which an application expects/uses from load balancers or proxies

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1697]
Problem to solve: if an application uses HTTP request headers (like X-Forwarded-* headers) from load balancers, proxies etc, then it should be clear that those headers are not given by end user.

Fits to category: V14.5 HTTP Request Header Validation

**Comment by tghosth** [comment]
Something like: 

> Verify that http headers which the application relies upon for business logic or security decisions such as X-Forwarded-* cannot be manipulated/controlled by the end-user.

What do you think @elarlang ?

**Comment by elarlang** [comment]
Can we use something like...

> Verify that HTTP headers, which are set by middleware like proxy of load balancers, and application relies upon ...

End-users can manipulate those headers anyway, the point is, that this middle-layer should clean up headers with the same name.

**Comment by tghosth** [comment]
Are there any other security sensitive headers that you want to consider here or only those related to the original IP?

**Comment by jsulinski** [comment]
Not just IP, there are:

- `X-Forwarded-For`
- `X-Forwarded-Host`
- `X-Forwarded-Proto`

Rails has historically struggled with these in certain configurations. 

Perhaps something like:
 
> Verify that HTTP headers defined by intermediary devices, such as X-Forwarded-*, that the application relies upon cannot be overridden by the end-user.

**Comment by elarlang** [comment]
I was thinking about it more and those (#1389) need to be separate requirements.

`and/or` to `and` in @jsulinski proposal and it's good for me.

**Comment by elarlang** [comment]
Requirement:
_Verify that HTTP headers defined by intermediary devices, such as X-Real-IP and X-Forwarded-*, that the application relies upon cannot be overridden by the end-user._

Other pieces/proposals:
* Category V14.5 HTTP Request Header Validation
* Level: 2
* CWE proposal [CWE-345](https://cwe.mitre.org/data/definitions/345.html)

**Comment by tghosth** [comment]
My modification:

> Verify that if the application relies upon HTTP headers such as X-Real-IP and X-Forwarded-*, which are defined by intermediary devices like load balancers or proxies, that these cannot be overridden by the end-user.

**Comment by elarlang** [comment]
One more thing - "relies upon" ... maybe just "uses"?

**Comment by jsulinski** [comment]
Sounds good to me! Here's another version if you prefer, that resolves the awkwardness of 'which/that these':

> Verify that any HTTP headers used by the application and defined by intermediary devices like load balancers or proxies, such as X-Real-IP and X-Forwarded-*, cannot be overridden by the end-user.

**Comment by elarlang** [comment]
I updated PR based on that (https://github.com/OWASP/ASVS/pull/1720/commits/097e6faf141d3d8554e16f18647f5aac72f6336b)

**Comment by tghosth** [comment]
@elarlang what do you think about [CWE-346](https://cwe.mitre.org/data/definitions/346.html) instead of CWE-[345](https://cwe.mitre.org/data/definitions/345.html)?

**Comment by elarlang** [comment]
Both are ok, but what is the key difference?
* 345 The product does not sufficiently verify the origin or authenticity of data, in a way that causes it to accept invalid data.
* 346 The product does not properly verify that the source of data or communication is valid.

From https://github.com/OWASP/ASVS/issues/1481 point of view, it does not matter too much anyway.
