### ISSUE TITLE
Page 15 Scope of verification Misspelling Be should be By

### ISSUE THREAD

**Issue by defern** [OWASP/ASVS#17]
Page 15 Scope of verification Misspelling Be should be By

Be default, ASVS assumes that the scope of the verification includes all code that was developed or modified in order to create the application or release.  

Should be:

By default, ASVS assumes that the scope of the verification includes all code that was developed or modified in order to create the application or release.

**Comment by vanderaj** [comment]
Fixed. Thank you :)
