### ISSUE TITLE
Make fails with a docker image error.

### ISSUE THREAD

**Issue by rewtd** [OWASP/ASVS#1707]
make fails to build:

➜  ASVS git:(master) ✗ make 
docker run --rm --user : -v "`pwd`/5.0:/data" -v "`pwd`/docker:/scripts" -e "TARGET=5.0" -e "FORMATS=" ghcr.io/asvs/documentbuilder
Unable to find image 'ghcr.io/asvs/documentbuilder:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/asvs/documentbuilder/manifests/latest": denied.
See 'docker run --help'.
make: *** [5.0] Error 125

potentially fixed by PR 1704 https://github.com/OWASP/ASVS/pull/1704 ?

**Comment by danielcuthbert** [comment]
thanks @rewtd, looking into this now

**Comment by tghosth** [comment]
@ike has committed a fix which will hopefully help with this. We are supposed to have a backup method but it is not currently working for me so I am investigating.

Thanks,

**Comment by tghosth** [comment]
@rewtd the old mechanism [described in the wiki](https://github.com/OWASP/ASVS/wiki/Building-the-ASVS) should work for now until we get the container mechanism fixed.

**Comment by rewtd** [comment]
Thanks @tghosth I'll give that a try.

**Comment by ike** [comment]
@rewtd if you create a [Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens) with **read access to packages**, you can download the docker image from here: https://github.com/OWASP/ASVS/pkgs/container/asvs%2Fdocumentbuilder

E.g.: 

```
$ echo <TOKEN> | docker login ghcr.io -u ike --password-stdin
$ docker pull ghcr.io/owasp/asvs/documentbuilder:latest
```

Alternatively, you can build the docker image yourself on your own machine, and then tag it:

```
$ docker build ./docker --tag ghcr.io/owasp/asvs/documentbuilder:latest
```

Hope that helps.

**Comment by ike** [comment]
@tghosth should we make the docker image public? Then it would automatically download for anyone who hadn't built it on their machine. There's a description of the process at the bottom of [this blog post](https://dev.to/willvelida/pushing-container-images-to-github-container-registry-with-github-actions-1m6b)

**Comment by tghosth** [comment]
Looks like I cannot, this means that people cannot build locally or that they have to build the image locally manually?
![image](https://github.com/OWASP/ASVS/assets/13623828/d0bf74e8-c641-4921-b4b2-13dce20fe579)

**Comment by ike** [comment]
@tghosth it means they'd have to build locally and can't download the image from the ASVS repo.

**Comment by tghosth** [comment]
Ok does the script build the container locally?
