### ISSUE TITLE
14.3.2 unintended security disclosures

### ISSUE THREAD

**Issue by Sjord** [OWASP/ASVS#1708]
https://github.com/OWASP/ASVS/blob/master/5.0/en/0x22-V14-Config.md

>  14.3.2 Verify that web or application server and application framework debug modes are disabled in production to eliminate debug features, developer consoles, and unintended security disclosures.

I think "security disclosures" is not really a thing. I get what is meant by this, but I don't think this is proper English.

**Comment by jmanico** [comment]
“Security disclosures” is like a security oracle, revealing info that weakens security - like an error code that reveals the encryption type or similar.

**Comment by jmanico** [comment]
How about:

"14.3.2 Ensure that debug modes for both the web/application server and the application framework are disabled in production environments to prevent exposure of debug features, developer consoles, and unintended sensitive information leakage."

Is that better?

**Comment by elarlang** [comment]
One more version:
Verify that debug modes are disabled in production environments for every component to prevent exposure of debug features, developer consoles, and unintended information leakage.

**Comment by tghosth** [comment]
> One more version: Verify that debug modes are disabled in production environments for every component to prevent exposure of debug features, developer consoles, and unintended information leakage.

I like this. @jmanico @Sjord what do you think?

**Comment by jmanico** [comment]
Developers consoles < Developer console output

**Comment by elarlang** [comment]
actually, what is "developer console"? how it's different from "debug feature"? So maybe we can just skip it.

Verify that debug modes are disabled in production environments for every component to prevent exposure of debug features and unintended information leakage.

**Comment by tghosth** [comment]
I would agree that developer console is effectively a debug feature and also developer console output would probably be unintended information leakage so I would be comfortable with @elarlang's wording:

> Verify that debug modes are disabled in production environments for every component to prevent exposure of debug features and unintended information leakage.

@jmanico @Sjord any further thoughts?

**Comment by elarlang** [comment]
As the issue was mainly against phrase "security disclosure", I reopen it for category title:
V14.3 Unintended Security Disclosure

Proposal to change it to:
V14.3 Unintended Information Leakage
