### ISSUE TITLE
3.12 - rephrase, spelling and potential pattern change

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#171]
_Verify that session ids stored in cookies have their path set to an appropriately restrictive value for the application, and authentication session tokens additionally set the “HttpOnly” and “secure” attributes_

Suggested
Verify that session IDs stored in cookies are scoped using the 'path' attribute; and have the 'HttpOnly' and 'Secure' cookie flags enabled.

N.B.
This may be impossible for API based apps, perhaps a link to design pattern or shift ID to HTTP header is a better approach.

**Comment by danielcuthbert** [comment]
agreed, amended.
