### ISSUE TITLE
9.4.1 (previously 9.1.2) - out of scope?

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1723]
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **9.4.1** | [MOVED FROM 9.1.2] Verify using up to date TLS testing tools that only strong cipher suites are enabled, with the strongest cipher suites set as preferred. | ✓ | ✓ | ✓ | 326 |
| **9.4.2** | [MOVED FROM 9.1.3] Verify that only the latest recommended versions of the TLS protocol are enabled, such as TLS 1.2 and TLS 1.3. The latest version of the TLS protocol should be the preferred option. | ✓ | ✓ | ✓ | 326 |

What is the point for 9.4.1? To say "use correct tools for testing 9.4.2"? If so, then I think it should be deleted as out of scope.

**Comment by jmanico** [comment]
Since there is no other "strong cipher" requirement, how about we change 9.4.1 to: 

9.4.1 | [MOVED FROM 9.1.2] Verify that only the latest recommended cipher suites are enabled, with the strongest cipher suites set as preferred. | ✓ | ✓ | ✓ | 326
-- | -- | -- | -- | -- | --

**Comment by tghosth** [comment]
Agree with Jim that protocols and ciphers are different, I opened #1725 to resolve
