### ISSUE TITLE
7.1.2 Isn't Pentestable/L1

### ISSUE THREAD

**Issue by cmlh** [OWASP/ASVS#1726]
As raised by @kwwall within https://owasp.slack.com/archives/C06MNF14M/p1694628426409349

Remove L1 from 7.1.2, reproduced below, as it is not possible to produce an artefact during a pentest/DAST.

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **7.1.2** | Verify that the application does not log other sensitive data as defined under local privacy laws or relevant security policy. ([C9](https://owasp.org/www-project-proactive-controls/#div-numbering)) | ✓ | ✓ | ✓ | 532 |

**Comment by elarlang** [comment]
In the same thread it is written, that there is no point to open new issues on the topic, as we have one already opened and antire V7 waits reorg.

Sorry for #nofilter, but you are just causing noise and wasting every volunteer time here.
