### ISSUE TITLE
4.4 - complexity for the sake of complexity, rephrase

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#174]
_Verify that access to sensitive records is protected, such that only authorized objects or data is accessible to each user (for example, protect against users tampering with a parameter to see or alter another user's account)._

Why not just say: 
Make sure that the application is tested against Insecure Direct Object Reference vulnerabilities?

This is a standard, not a 101, ASVS audience either assumed to know or can research what  Insecure Direct Object Reference is on OWASP vulnerability reference pages.

**Comment by vanderaj** [comment]
Serg, I've updated it to be a lot clearer and inline with OWASP Top 10 A3 (sensitive data exposure) and A5 (Access Control). Please review and re-open, but I think this is a lot clearer for you.
