### ISSUE TITLE
Is the new 14.2.7 clear enough?

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1746]
14.2.7 was added [in this PR](https://github.com/OWASP/ASVS/pull/908/files).

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **14.2.7** | [ADDED] Verify that third party components are sourced separately from internally owned and developed applications. | ✓ | ✓ | ✓ | 441 |

It is followed by the following note:

> Note: Certain languages and package managers, have ecosystems that require the identification of packages using multiple factors (e.g groupId and artifactId). This would allow the build process to more specifically identify a resource. In other cases, package managers operate by the order of repositories or mirrors included. Consult your package managers to specifically indicate search order.

Do we think this requirement is clear enough or could it be made clearer?

Any thoughts @joubin?

**Comment by ImanSharaf** [comment]
@tghosth is it here to avoid dependency confusion?

**Comment by elarlang** [comment]
Original issue: https://github.com/OWASP/ASVS/issues/899 - why not to re-open the issue for clarification?

I'm not sure the chosen CWE suits here - [CWE-441](https://cwe.mitre.org/data/definitions/441.html) Unintended Proxy or Intermediary ('Confused Deputy')

**Comment by tghosth** [comment]
Fair one @elarlang, I will close this and move discussion back to #899
