### ISSUE TITLE
Consideration of Appropriate Cryptoperiods as per NIST Guidelines

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#1750]
In light of enhancing ASVS cryptographic key management practices, it's advisable to consider aligning our cryptoperiods with the recommendations provided by the National Institute of Standards and Technology (NIST). [NIST 800-57](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-57pt1r4.pdf) suggests a maximum cryptoperiod of 1 to 3 years for private keys associated with certificates. This issue aims to initiate discussions and subsequent actions towards reviewing and possibly amending current ASVS key management practices in line with NIST guidelines.

![image](https://github.com/OWASP/ASVS/assets/78227895/4052a6cc-cb39-4167-ab1f-f535e00ea2e0)

**Comment by jmanico** [comment]
I think this is too long. I suggest "no long-term keys" for any reason.

**Comment by tghosth** [comment]
We currently have this requirement:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.6.1** | Verify that there is an explicit policy for management of cryptographic keys and that a cryptographic key lifecycle follows a key management standard such as NIST SP 800-57. | | ✓ | ✓ | 320 |

I would be quite hesitant to start trying to mandate too many details of this directly...

**Comment by ImanSharaf** [comment]
Should we explicitly mention "maximum cryptoperiod of 1 to 3 years for private keys"?

**Comment by tghosth** [comment]
> Should we explicitly mention "maximum cryptoperiod of 1 to 3 years for private keys"?

But if we say that, do we not need to also mandate a whole bunch of other requirements?

**Comment by tghosth** [comment]
@ImanSharaf waiting for a response here

**Comment by tghosth** [comment]
@ImanSharaf :)

**Comment by ImanSharaf** [comment]
Sorry for delay. We can close this one.
