### ISSUE TITLE
2.1.9 seems wrong

### ISSUE THREAD

**Issue by oEscal** [OWASP/ASVS#1753]
Is [2.1.9](https://github.com/OWASP/ASVS/blob/154aebdcc4a119b479d96b36aed22087c13df9e2/5.0/en/0x11-V2-Authentication.md?plain=1#L41C56-L41C56) right? Shouldn't passwords be required to have mixed character sets (https://cwe.mitre.org/data/definitions/521.html)?

**Comment by elarlang** [comment]
Seems, that CWE is outdated on the topic.

A lot of authentication and session management requirements in ASVS are based on NIST research, including password requirements.

The table contains also NIST column and refers to 5.1.1.2.

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.1.9** | Verify that there are no password composition rules limiting the type of characters permitted. There should be no requirement for upper or lower case or numbers or special characters. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | ✓ | ✓ | ✓ | 521 | 5.1.1.2 |

... and there is written:
_Verifiers SHOULD NOT impose other composition rules (e.g., requiring mixtures of different character types or prohibiting consecutively repeated characters) for memorized secrets. Verifiers SHOULD NOT require memorized secrets to be changed arbitrarily (e.g., periodically). However, verifiers SHALL force a change if there is evidence of compromise of the authenticator._

For correction, maybe we need to get rid of the CWE value from the requirement. Title and short description are kind of valid, but section "Phase: Architecture and Design" is in conflict with NIST research.

**Comment by jmanico** [comment]
No, this requirement was removed in the recent NIST 800-63b standard. They added things like blocking common passwords and stopping credential, stuffing, and other controls that are more effective.

**Comment by ataseren** [comment]
Hello, can you tell me why imposing composition rules for passwords is a bad thing? I read the related part on NIST800-63B but couldn't understand it.

**Comment by jmanico** [comment]
There are many reasons but one is that complexity rules do not defend against modern attacks.

Attackers do not manually guess passwords (which is what complexity rules try to prevent) they use powerful brute-force and dictionary attacks using common or breached passwords.

**Comment by ataseren** [comment]
Just to verify it, a completely random password with such rules would be effective for defense. But with these rules, created passwords are usually consist of meaningful words and numbers. Therefore, these rules become obsolete, right?

**Comment by jmanico** [comment]
Exactly!

**Comment by ataseren** [comment]
Just wanted to satisfy my curiosity. Thanks a lot!
