### ISSUE TITLE
proposal: new requirement - no extra logs than allowed in inventory

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1759]
Spin-off from: https://github.com/OWASP/ASVS/issues/892#issuecomment-808788466

Problem to solve: there are security logs, which need to exists, but often developers "forget" debug logs on and those logs contain a lot of sensitive information, are not sanitized (cleaned from sensitive information) and quite soon those log contain too much data which is outside of application authorization flow.

edit 2023-12-22: updated proposal is here: https://github.com/OWASP/ASVS/issues/1759#issuecomment-1867417889

Proposal:
* Requirement: Verify that the application does not log anything extra then described in log inventory.
  * need to improve: to be clear - no extra log files, not just events to already existing log files
* Level: 2
* CWE-779 Logging of Excessive Data

Category waits outcome from https://github.com/OWASP/ASVS/issues/1444 it should belong to the same category, where goes current "to not log sensitive data". We don't need to wait for V7 restruct, we can put the requirement in and move around later, if needed.

**Comment by EnigmaRosa** [comment]
I think this could be addressed by modifying the language in the existing 7.1.X requirements to specify that _only_ security events should be logged. Or, if we don't want to impose such limitations, I would at least think that 7.1.2 - that the application doesn't log other sensitive data - covers the sensitive part. 
On a related note, should we perhaps edit the language of 7.1.1 and 7.1.2 to include log sanitization, or is that implied?

**Comment by elarlang** [comment]
Maybe my proposal is not clear here - I did not mean writing anything non-related to already existing security events log (I need to recheck that this problem is covered somehow), but more addressing the problem - that sometimes application log information to some other file/source, often those are "I forgot them to be enabled" debug logs. Most likely this kind of debug log contain not sanitized sensitive data (which we have covered via current 7.1.2, but even if those could be sanitized by some miracle, then creating alternative and extra log somewhere is still problematic.

For "related note" we have many related issues opened and I would not like to search different discussions from another related issues later:
https://github.com/OWASP/ASVS/issues?q=is%3Aissue+is%3Aopen+v7

If the problem is not covered, it makes sense to open new issue. Otherwise pointed out problems may be lost when the main issue topic is solved and issue is closed.

General logs reorg issue is this: https://github.com/OWASP/ASVS/issues/1444

**Comment by EnigmaRosa** [comment]
> Maybe my proposal is not clear here - I did not mean writing anything non-related to already existing security events log (I need to recheck that this problem is covered somehow), but more addressing the problem - that sometimes application log information to some other file/source, often those are "I forgot them to be enabled" debug logs. 

Ah, I see. I think there needs to be some clarifying language such that readers understand that this is not referring to events log.

**Comment by elarlang** [comment]
> Ah, I see. I think there needs to be some clarifying language such that readers understand that this is not referring to events log.

Yes, thank you for feedback, it was good validation that it can be interpreted differently.

**Comment by csfreak92** [comment]
Hi @elarlang, I am probably reading it wrong so let me ask to clarify. Are you proposing a requirement to:

* Prevent logging of excessive information (which I think is covered by 7.1.1 and 7.1.2), or
* Require that verify debugging logs are not enabled in production?, or
* Prevent excessive logging of data that is not declared in a log inventory documentation? 

I can help with the wordsmithing, but sorry I am just a bit confused what we are trying to achieve here in this issue. Thanks!

**Comment by elarlang** [comment]
Prevent excessive logging to **log files** that are not declared in a log inventory documentation, and it also covers the "accidental debug logs" part.

note: 7.1.1 and 7.1.2 do not prevent logging excessive information, but sensitive information.

**Comment by csfreak92** [comment]
I agree with preventing excessive logging of information to the log files that are not declared in the log inventory documentation and to cover the accidental debug logs as well. 

I am a little unclear with this part though... 

> note: 7.1.1 and 7.1.2 do not prevent logging excessive information, but sensitive information. 

Can you provide some examples of excessive information that gets accidentally logged if let's say debugging was enabled in production? To me, excessive information usually are sensitive information as well such as IP address, PII, card payment details, session tokens, healthcare data, financial data, social security data, etc. I feel that I am missing something else? If you could provide an example that would help and I could start with some wordsmithing from it. :)

**Comment by elarlang** [comment]
I'm not a native speaker, so I may interpret it somehow differently, but this is my understanding in the context:
* Excessive - covers in general "too much" information which is mostly unnecessary - does not give any value, just noise. It makes it harder to search from logs.
* Sensitive information - some piece of data which is declared and documented to be sensitive (see 1.8.1). Those may be logged in hashed form.

**Comment by elarlang** [comment]
I update my proposal:
* Verify that the application logs information only to files and services documented in the log inventory.
* CWE: - (initially proposed CWE leads to different problem)

**Comment by tghosth** [comment]
> Verify that the application only stores/broadcasts logs to the files and services which are documented in the log inventory.

Do you think that is clearer?

**Comment by elarlang** [comment]
Instead of `/`, should we use "or" or "and"?

**Comment by jmanico** [comment]
Nobody gets hacked because of bad log management. I’d like to suggest that we reduce the blogging requirements and just focus on developers, creating security logs for security events, so choose detection as possible.

Elar, I know this is a bit off-topic. It’s completely OK to dismiss this comment. Forgive me for giving you a comment out of context.

**Comment by elarlang** [comment]
Why I think the requirement is important:
* an application logs something extra, which is not intended to happen in a public environment - classical example, some debug log
* log files collect a lot of information over a long period of time and access control is not under the application control anymore
* extra bonus - when the log file is in the public folder and accessible with a direct HTTP request

**Comment by jmanico** [comment]
Your argument is solid. I am convinced.

He reminds me of the IEEE logging passwords in a public file. Oops.

https://it.slashdot.org/story/12/09/25/1356211/data-breach-reveals-100k-ieeeorg-members-plaintext-passwords
