### ISSUE TITLE
proposal/discussion: validation rules for files inside archive if the application unpack it or has business logic limit for other files

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1770]
If an application allows users to upload archive files (such as zip) and then unpack files from zip to the application, then application should validate each file separately inside the archive according to file validation rules.

Or in more general - if an application allows to upload files including archives, then if business logic rules exists for uploaded files, those should also apply to the files inside the archive.

... but an application may just allow users to upload zip files by business logic rules and other users to download them.

So - do we need requirement for that?

**Comment by elarlang** [comment]
Maybe it is solvable via https://github.com/OWASP/ASVS/issues/1604

**Comment by tghosth** [comment]
You know what I am going to say.... 🙃

**Comment by jmanico** [comment]
Another problem is that you cannot figure out the unpacked size of the zip without walking the file structure and counting. I typically unzip files for file upload in a quota limited directory and if it fails, drop it. I worry mostly about disk flooding attacks when it comes to zip.

And I totally agree that each file inside a zip needs to also go through a file validation/malware scanning/etc process like any other uploaded individual file.

**Comment by jmanico** [comment]
So how about this.

Let's make a new section 12.8 that is exclusively for archive (zip, etc) file handling.  We can move these two into it:

12.1.2 | Verify that the application checks compressed files (e.g. zip, gz, docx, odt) against maximum allowed uncompressed size and against maximum number of files before uncompressing the file. |   | ✓ | ✓ | 409
-- | -- | -- | -- | -- | --

12.3.7 | [ADDED] Verify that server-side file processing such as file decompression ignores user-provided path information to prevent vulnerabilities such as zip slip. | ✓ | ✓ | ✓ | 23
-- | -- | -- | -- | -- | --

... and add a third that Elar suggested above:

_Verify that if an application allows users to upload archive files (e.g., zip files) and then unpacks files from these archives within the application, the application must individually validate each file within the archive according to established file validation rules._

**Comment by jmanico** [comment]
Another option is to modify 12.2.1, suggested by @tghosth 

12.2.1 | [MODIFIED] Verify that when the application accepts a file, it checks if the file extension matches an expected file extension and validates that the contents correspond to the type represented by the extension. This includes, but is not limited to, checking the initial 'magic bytes', performing image re-writing, and using specialized libraries for file content validation. **_This validation should also apply to uploaded files or uploaded contents of an archive file, such as a zip._** | | ✓ | ✓ | 434

**Comment by tghosth** [comment]
12.2.1 | [MODIFIED] Verify that when the application accepts a file, either on its own or within an archive such as zip, it checks if the file extension matches an expected file extension and validates that the contents correspond to the type represented by the extension. This includes, but is not limited to, checking the initial 'magic bytes', performing image re-writing, and using specialized libraries for file content validation. | | ✓ | ✓ | 434
-- | -- | -- | -- | -- | --

**Comment by tghosth** [comment]
I think this is a good compromise which hits the original goal of the issue without getting too prescriptive or complicated
