### ISSUE TITLE
2.4.1 should be required for L1

### ISSUE THREAD

**Issue by appills** [OWASP/ASVS#1773]
[2.4.1](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x11-V2-Authentication.md#user-content-v24-credential-storage)

 [Application Security Verification Levels](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x03-Using-ASVS.md#application-security-verification-levels):
 > ASVS Level 1 is for low assurance levels, and is completely penetration testable.
 
 > Level 1 is the only level that is completely penetration testable using humans. All others require access to documentation, source code, configuration, and the people involved in the development process.

Insecure password storage or insecure credential handling can be tested by a human in at least one method, such as detecting non-timing-safe string comparisons. Secure password hashing is surely testable as a human from a black box and can be inferred to some extent based on response timing.

[Using ASVS for Level 1 states](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x03-Using-ASVS.md#level-1---first-steps-automated-or-whole-of-portfolio-view):
> An application achieves ASVS Level 1 if it adequately defends against application security vulnerabilities that are easy to discover, and included in the OWASP Top 10 and other similar checklists.

And insecure password hashing, storage, and non-timing-safe string comparisons surely fall under [A02 Cryptographic Failures](https://owasp.org/Top10/A02_2021-Cryptographic_Failures/)

**Comment by elarlang** [comment]
So you copy-paste selective texts from around documents, but not the one which is written to the mentioned section? :)

https://github.com/OWASP/ASVS/blob/master/5.0/en/0x11-V2-Authentication.md#v24-credential-storage

> This section cannot be penetration tested, so controls are not marked as L1. However, this section is of vital importance to the security of credentials if they are stolen, so if forking the ASVS for an architecture or coding guideline or source code review checklist, please place these controls back to L1 in your private version.

So at the moment I see it as duplicate of https://github.com/OWASP/ASVS/issues/1495

**Comment by appills** [comment]
> So you copy-paste selective texts from around documents, but not the one which is written to the mentioned section? :)

Hehe good point, I should've copied the text from the section (& probably read that it states to "Verify", which of course there's probably someone out there doing 100k md5's and that might be timing-indistinguishable) 

@Sjord brings up a valid point in that #1495 thread:
> For me, the levels relate to the security requirements of your application. If you are building a nuclear missile launch system, you would comply to L3. If you are building a tic-tac-toe website, you would comply to L1.

I'll continue my separate thought over there, thank you!

**Comment by elarlang** [comment]
I don't close it at the moment, just marked it as "level question". If we can declare the levels on one nice day, we need to recheck those issues as well.

**Comment by jmanico** [comment]
We made major changes to password storage in v6, please re-open this if you think I'm closing it prematurely,
