### ISSUE TITLE
4.11 - this makes no sense, what so ever

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#178]
_Verify that there is a centralized mechanism (including libraries that call external authorization services) for protecting access to each type of protected resource._

No idea what this means. Ran it past 3 other people - no idea. 

If this is referring to something like 'make use of centralised and vetted artefact repository', then this is what needs to be said.

**Comment by jmanico** [comment]
We would like to see access control rules and verification to be in a centralized service or library. This is opposed to the common practice of just hard coding role checks all over your code which makes verification difficult.
