### ISSUE TITLE
Proposal: End-to-End Access Control Tests

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#1782]
Upon review of the current ASVS Category 4 requirements focused on access control, I have identified a gap in the verification items regarding continuous testing and validation of access control mechanisms. There is no explicit requirement that states the need for automated testing to ensure that access controls are not only correctly designed but also reliably enforced across all application components under various scenarios.
Automated end-to-end access control tests are crucial for validating the security of user roles and ensuring that the principle of least privilege is adhered to throughout the application. This proposed requirement would help organizations enforce a more rigorous and automated approach to access control testing, reducing the risk of unauthorized access due to access control flaws.

4.X.X **Verify that the application includes a series of automated end-to-end access control tests that validate the effectiveness of the access controls implemented, including but not limited to, unauthorized access attempts with no auth token and with different roles' tokens, to ensure proper authorization enforcement. These tests should be integrated into the continuous integration/continuous deployment (CI/CD) pipeline to ensure regular and consistent evaluation of the access control mechanisms.**

**Comment by elarlang** [comment]
For me it's out of scope so many ways.

* proposed requirement is not actually access control issue (V4.X.X)
* testing fits to test-environment, you should not do it in production. we don't write rules how someone should test their stuff
* most of CI/CD requirements we remove as out of scope - for ASVS we care more about the end product, not that much how it is produced (pretty much the same comment like given here https://github.com/OWASP/ASVS/issues/1566#issuecomment-1452465066)
* test-code and also test-data should not be present in production

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **14.1.7** | [ADDED] Verify that production environment does not include test code. | | ✓ | ✓ | 489 |

**Comment by csfreak92** [comment]
@ImanSharaf, should we really have a testing requirement about automated testing? I think that is also part of the question whether to add CI/CD stuff or not. While it could be a good idea, I think @elarlang mentioned it to be out of scope which I agree as well since some of the old CI/CD related requirements were deleted in the other issues.

**Comment by tghosth** [comment]
So this is out of scope for the ASVS.

However, I wonder whether it would be a useful addition to the surrounding text in chapter V4? 

@ImanSharaf, do you want to take a look and see where you think it might fit in?

**Comment by ImanSharaf** [comment]
Thanks. I will work on this.

**Comment by elarlang** [comment]
> So this is out of scope for the ASVS.
> 
> However, I wonder whether it would be a useful addition to the surrounding text in chapter V4?
> 
> @ImanSharaf, do you want to take a look and see where you think it might fit in?

@tghosth - one of the goals to roadmap was to reduce texts as much as possible, I think current direction is not aligned with that idea:
https://github.com/OWASP/ASVS/wiki/Roadmap-to-version-5.0#streamlined-document

**Comment by tghosth** [comment]
> > So this is out of scope for the ASVS.
> > However, I wonder whether it would be a useful addition to the surrounding text in chapter V4?
> > @ImanSharaf, do you want to take a look and see where you think it might fit in?
> 
> @tghosth - one of the goals to roadmap was to reduce texts as much as possible, I think current direction is not aligned with that idea: https://github.com/OWASP/ASVS/wiki/Roadmap-to-version-5.0#streamlined-document

I agree but I think useful pointers and ideas are still worth while

**Comment by ImanSharaf** [comment]
@tghosth what do you think about adding this paragraph to the introduction section of chapter 4? 

In addition to the high-level requirements, it is essential to verify that the application incorporates a robust series of automated end-to-end access control tests. These tests should be designed to validate the effectiveness of the access controls under various scenarios. This ensures that the access controls are not only correctly designed but also consistently and reliably enforced across all application components. Integrating these tests into the continuous integration/continuous deployment (CI/CD) pipeline will enable regular and thorough evaluation of the access control mechanisms, thereby reinforcing the principle of least privilege and significantly reducing the risk of unauthorized access due to access control flaws

**Comment by tghosth** [comment]
I would shorten to this and add it to the start of V4:

_Access control deficiencies are unlikely to be discovered using generic automated testing tools. Verifying the requirements in this section will either require manual or manual assisted testing or alternatively a robust series of automated end-to-end access control tests which validate the effectiveness of the access controls under various scenarios. Integrating these tests into the continuous integration/continuous deployment (CI/CD) pipeline will make it easier to validate these requirements on an ongoing basis._

Any other thoughts @ImanSharaf @elarlang?

**Comment by elarlang** [comment]
I'm ok with the content. I'm also ok without having it to keep the document short.

**Comment by tghosth** [comment]
Opened #1881

**Comment by ImanSharaf** [comment]
> I would shorten to this and add it to the start of V4:
> 
> _Access control deficiencies are unlikely to be discovered using generic automated testing tools. Verifying the requirements in this section will either require manual or manual assisted testing or alternatively a robust series of automated end-to-end access control tests which validate the effectiveness of the access controls under various scenarios. Integrating these tests into the continuous integration/continuous deployment (CI/CD) pipeline will make it easier to validate these requirements on an ongoing basis._
> 
> Any other thoughts @ImanSharaf @elarlang?

It works for me.
