### ISSUE TITLE
Proposal for Inclusion of Continuous Fuzzing Practices in CD Pipelines within ASVS

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#1783]
This proposal advocates for the inclusion of continuous fuzzing practices (I don't mean DAST), particularly coverage-based fuzzing, within Continuous Deployment (CD) pipelines in the ASVS.

Fuzzing, especially automated fuzzing in CD pipelines, has proven instrumental in identifying and resolving security vulnerabilities that may not be detected by other testing methods. For example I found this bug in Python's pickle module ([Issue 41288](https://bugs.python.org/issue41288)), and I used the AFL fuzzer to find this in a few hours and this bug could lead to denial-of-service (DoS). 

This demonstrates the necessity for coverage-based fuzzing to be part of the standard security testing toolkit in modern development pipelines.

**Comment by elarlang** [comment]
I don't see it to me in scope. Pretty much the same comment like I gave here - https://github.com/OWASP/ASVS/issues/1782#issuecomment-1803215686

**Comment by ImanSharaf** [comment]
How it comes that it is out of scope? 
[This is](https://github.com/mrash/afl-cve) just a very small portion of CVEs that AFL(++) found in different libraries and software.

**Comment by ImanSharaf** [comment]
Also, we have an ASVS item, 1.14.3, that is similar to the mentioned issue.

1.14.3. Verify that the build pipeline warns of out-of-date or insecure components and takes appropriate actions.

**Comment by elarlang** [comment]
> Also, we have an ASVS item, 1.14.3, that is similar to the mentioned issue.
> 
> 1.14.3. Verify that the build pipeline warns of out-of-date or insecure components and takes appropriate actions.

And we have agreement to delete it for that exact reason.
https://github.com/OWASP/ASVS/issues/1405#issuecomment-1751675278

**Comment by ImanSharaf** [comment]
What about 14.2.1?

**Comment by elarlang** [comment]
> What about 14.2.1?

Discussion about 14.2.1 in held in the same previously linked issue: https://github.com/OWASP/ASVS/issues/1405

**Comment by ImanSharaf** [comment]
I believe we should not change it and we should not remove "using a runtime or code level dependency scan". What is your opinion? @tghosth

**Comment by elarlang** [comment]
Please move discussion on 14.2.1 to mentioned issue.

**Comment by tghosth** [comment]
> I believe we should not change it and we should not remove "using a runtime or code level dependency scan". What is your opinion? @tghosth

I agree with @elarlang and this is something that has been covered elsewhere although I admit I can't find a good reference.

Basically, in ASVS our scope is the application itself, not the processes around secure development or other security scanners.

We recently had a discussion about where the border is and you can see my response in https://github.com/OWASP/ASVS/issues/1526#issuecomment-1801232706

ASVS 4.x did not strictly hold to this line and this is something we are working on

**Comment by tghosth** [comment]
I am going to respectfully close this for now.
