### ISSUE TITLE
Proposal: Add Trusted Types API to Mitigate XSS Vulnerabilities

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#1787]
### Issue Description
I'd like to propose the inclusion of the Trusted Types API in the OWASP Application Security Verification Standard (ASVS). Given the increasing prevalence of Cross-Site Scripting (XSS) attacks, integrating the Trusted Types API could provide a robust defense-in-depth strategy.

### Proposed Change
Trusted Types API, an emerging standard, offers a powerful mechanism to prevent DOM-based XSS. It ensures that DOM manipulation uses known-safe values, preventing the injection of untrusted data. Its integration into ASVS would encourage developers and security professionals to adopt this modern and effective approach against XSS.

### Justification
- **Security Enhancement**: Trusted Types API specifically targets one of the most common and impactful security vulnerabilities, XSS.
- **Modern Practices**: As web applications evolve, incorporating modern security practices like Trusted Types API keeps the ASVS relevant and effective.
- **Developer Awareness**: Including this in the ASVS raises awareness among developers and organizations about this powerful security feature.

I believe that the addition of the Trusted Types API to the ASVS will significantly contribute to more secure web applications. Looking forward to the community's thoughts and feedback on this proposal.

Thank you for considering this feature request.

**Comment by tghosth** [comment]
Ok, so my big problem with trusted types is that it is quite complicated to implement (especially retroactively) and it is only supported by Chromium and Opera but not Firefox and Safari.
https://caniuse.com/trusted-types

Santizer API seems like a more widely adopted process but it is still at the discussion stage (https://wicg.github.io/sanitizer-api/) and things are changing so much that Chromium has actually removed support from it until the API becomes more stable.
https://caniuse.com/?search=sanitizer

 It is also solving a slightly different problem to trusted types.

In conclusion, I think that disappointingly these mechanisms are not mature enough to include in ASVS.

@jmanico what do you think?

**Comment by jmanico** [comment]
I'm torn on this. Developers will mostly benefit from this being built 
into frameworks. But it's also a very high end defense that is quite 
powerful.

I tend to say yes, but can accept a no. I worry ASVS is getting too bulky.

**Comment by elarlang** [comment]
So, yes it is useful, but...

First the thing what @tghosth already pointed out, that it lacks browser support at the moment.

Second - can / do we need to require it? The point is, you can write your code secure against so-called DOM XSS without using it.

Feels more something to be recommended, not required. Happy to change my mind with arguments why it should be required.

**Comment by ImanSharaf** [comment]
@tghosth I believe that ASVS could still play a pivotal role in advocating for future-ready security measures. While Trusted Types and Sanitizer API are not widely adopted yet, their potential in enhancing web application security is considerable.

### Suggested Approach
- **Future Guidance**: Perhaps ASVS could include a section on emerging security technologies like Trusted Types and Sanitizer API. This would not be a requirement but rather guidance for the future, helping organizations prepare for and gradually adopt these technologies as they mature and gain wider support.
- **Awareness and Advocacy**: By mentioning these technologies, ASVS can raise awareness and potentially influence broader adoption and faster maturity, as organizations and developers start considering and experimenting with these APIs.
- **Differentiation of Standards**: Clearly differentiate between current best practices and emerging technologies. This ensures that the ASVS remains practical and relevant, while also being forward-looking.

**Comment by elarlang** [comment]
For me it feels cheat sheet material.

As this discussion and quite different point of view what and why is ASVS is relatively frequent lately, we need to write it out somewhere.

**Comment by tghosth** [comment]
I like the concept but I agree with Elar that this is out of scope for ASVS.

However, I think this might actually be a valid use of a top 10 project, the OWASP Top 10 emerging application security mechanisms or something. I don't usually like top 10s but since this is specifically for awareness, it might be a good fit :)
