### ISSUE TITLE
1.7.1 - do we need to require common logging format?

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1796]
Requirement 1.7.1:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.7.1** | Verify that a common logging format and approach is used across the system. ([C9](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 1009 |

I think this requirement is a bit old-school or strict and all logs must follow the same format. Nowadays it's more important that the tools for watching and monitoring can take this log in. Common format is definitely helpful, but is it something we should require? If log-reading tools can read different formats, I can not see the risk to mitigate here.

edit: The requirement itself is needed to be sure that all logs are correlatable for the log reader in use. As it is implementation requirement, it should be moved to 7.1. Also CWE value points to CWE category (and it's incorrect usage of CWE)

Thoughts?

**Comment by jmanico** [comment]
> Seems like a good point. Maybe a common logging format is preventing log injection issues? Just thinking of possible cases why this was required.

A common logging format is different than the encoding needed to stop log injection.

**Comment by elarlang** [comment]
> Seems like a good point. Maybe a common logging format is preventing log injection issues? Just thinking of possible cases why this was required.

Like Jim said, log injection is a different topic and it is covered by 7.3.1:
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **7.3.1** | Verify that all logging components appropriately encode data to prevent log injection. ([C9](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 117 |

Common logging format is helpful for log readers for log correlation - if you watch/import 2 different log sources/files, you can align the same type of information. Nowadays there are every kind of log readers available that provides "adapters" - so that is why I opened the issue - do we actually need to **require** it?

**Comment by tghosth** [comment]
Sounds like a basic but important requirement to me

**Comment by elarlang** [comment]
To be clear, I don't want to remove it. I think it requires an exception for log readers which can work as adapters and read different formats.

Something like:
_Verify that logs are readable and correlatable for the used log reader, preferably by using a common logging format._
