### ISSUE TITLE
Bring all access control requirements inline with NIST 800-63

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#180]
_Verify the application has additional authorization (such as step up or adaptive authentication) for lower value systems, and / or segregation of duties for high value applications to enforce anti-fraud controls as per the risk of application and past fraud._

This is just an aggregate control, covering IDOR, control 4.14 and many others. Can be removed.

Potentially, could be isolated to L3 and suggest behaviour analysis and fraud prevention services. Or merged into 4.14

**Comment by vanderaj** [comment]
We need to bring this into line with NIST 800-63's access control requirements. I'll keep this around until we've fully decomposed all of its requirements (it's very dense).

**Comment by jmanico** [comment]
Hey @vanderaj do you will want to do this for 4.0? That is a pretty big challenge.

**Comment by jmanico** [comment]
removed 4.3.3 and closing - issue 362 discusses the NIST issue
