### ISSUE TITLE
14.4 section (HTTP Security Headers) rename / find better category-section for "content-type" requirements.

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1808]
After browser-related requirements are moved away, there will be only 2 requirements left behind (as those are not that browser-specific and are required for other clients as well)

## V14.4 HTTP Security Headers

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **14.4.1** | [MODIFIED, SPLIT TO 14.4.8] Verify that every HTTP response contains a Content-Type header which matches the actual content of the response. | ✓ | ✓ | ✓ | 173 |
| **14.4.8** | [ADDED, SPLIT FROM 14.4.1] Verify that if a response specifies a Content-Type of "text/\*", "\*/\*+xml" and "\*/xml", it also specifies a safe character set (e.g., UTF-8, ISO-8859-1) with the charset parameter. | ✓ | ✓ | ✓ | 173 |

Now - the section title is misleading. Also think those requirements should not belong to the Configuration category.

**Comment by elarlang** [comment]
The change is done now: https://github.com/OWASP/ASVS/blob/master/5.0/en/0x22-V14-Config.md#v144-http-security-headers

Note: the initial idea was to move those (14.4.1 and 14.4.8) requirements to the section "Unintended Content Interpretation": https://github.com/OWASP/ASVS/blob/master/5.0/en/0x50-V50-Web-Frontend-Security.md#v505-unintended-content-interpretation

**Comment by tghosth** [comment]
Ok so I feel like these should not strictly belong to the browser category because they could be relevant to other apps which pull resources via HTTP.

**Comment by meghanjacquot** [comment]
Following up on this - I think it is ok to only have two for 14.4 unless the above two that you mentioned @elarlang should go into a different section. 

In regards to a name, maybe Content-type configuration?

**Comment by randomstuff** [comment]
> [ADDED, SPLIT FROM 14.4.1] Verify that if a response specifies a Content-Type of "text/*", "*/*+xml" and "*/xml", it also specifies a safe character set (e.g., UTF-8, ISO-8859-1) with the charset parameter.

Does this means, we have to specify a charset (especially XML where there is an alternate way to detect the encoding)? Is this a good idea to have this requirement? Does this really prevent any attack?

Nitpicks: Does this conflicts with text/dns (RFC4027) or text/vtt which do not define a charset parameter?

>  a safe character set

What is a safe character set? (and why is ISO-8859-1 safe?)

Nitpick: actually this is a character *encoding* :).

**Comment by elarlang** [comment]
@randomstuff  - how those requirements are developed, please read issues:
* https://github.com/OWASP/ASVS/issues/900
* https://github.com/OWASP/ASVS/issues/788

If you have suggestions for improvement, probably it makes sense to re-open one of those issues and keep this issue for structure - chapter title.

**Comment by elarlang** [comment]
As stated in the issue (https://github.com/OWASP/ASVS/issues/1808#issue-2044227823):

> Now - the section title is misleading. Also think those requirements should not belong to the Configuration category.

it is not about renaming the section title, mentioned requirements are not belonging to Configuration by their principle. Yes, there is option to configure web server default response, but it is just one edge-case - the point is to provide HTTP response with correct information.

If it does not fit to "V50 Web Frontend Security", then maybe we should move to V13, as this is a web service topic.

So, my proposal is to move it to V13.

Any alternatives? ping @tghosth

**Comment by elarlang** [comment]
Additionally, if we move it away, it should go together with "V14.5 HTTP Request Header Validation" and maybe also "V14.6 HTTP/2"

**Comment by tghosth** [comment]
Having discussed with @elarlang, I agree that it would make sense to move [V14.4, V14.5 and V14.6](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x22-V14-Config.md#v144-http-security-headers) to V13 as they are more about HTTP requests/responses then specifically about configuration.

Suggestion would be:

V14.4 HTTP Security Headers > V13.1 Generic Web Service Security
V14.5 HTTP Request Header Validation > V13.6 HTTP Request Header Validation
V14.6 HTTP/2 > V13.7 HTTP/2

@meghanjacquot what do you think about this?

**Comment by meghanjacquot** [comment]
I think that makes a lot of sense and removes these types of things that are much more focused on web services and keeps them altogether. I am in full support.
