### ISSUE TITLE
proposal: new requirement for disallowing search engines to crawl and index the content

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1810]
Category/Section: V14.3 Unintended Information Leakage

An application can do some extra steps to prevent search engines and crawlers from indexing the page. 

Points - if the site is not meant to be public, it can be said in robots.txt that it does not index at all.

Some components may want to hint crawlers, it should be disallowed as well (if not intended to do so):
https://developers.cloudflare.com/cache/advanced-configuration/crawler-hints/

**Comment by tghosth** [comment]
I think the underlying issue is an authorization problem and this more like defense in depth.

Not sure if this should be an L3 requirement or a recommendation (#1801).

**Comment by elarlang** [comment]
I agree that underlying problem is an authorization problem and it is 2nd layer of defense. It's a bit the same with Content-Security-Policy and so-called XSS, or limiting outgoing destination from the server and SSRF.

Some more ideas - if I watch it from return on investment point of view, it makes sense to require it - it does not require too much effort to implement, but it gives extra layer of defense (yes, only for "good search engines").

Why it makes sense - if there is authorization problem and some sensitive content is indexed, it is impossible or really complicated get it out from search engine cache.

I'm also ok if it ends up as a recommendation or we just close the issue :)

**Comment by jmanico** [comment]
> Re: [OWASP/ASVS] proposal: new requirement for disallowing search engines to crawl and index the content (Issue #1810)

I think this is a very bad control, and should be dismissed from ASVS. Search engines typically only crawl public data and public data is unfortunately public and malicious search engines will always collect it.

The way to protect sensitive data is behind authentication and authorization. And even then, if public registration is available, malicious search engines regardless of your headers can create accounts and scrape that content.

**Comment by elarlang** [comment]
Just a tiny clarification - it's all true, robots.txt or some extra headers are only effective for "good search engines", but the application or part of it (like Cloudflare) does not send hints to malicious search engines by default.

**Comment by jmanico** [comment]
Good point, Elar. 

I still think that these defenses are ineffective controls for any kind of public data or any kind of data that’s behind systems that allows public registration. 

The way that I’ve stopped adversaries in the past what did detect the rate at which they’re crawling my data. IP address analysis sometimes helps. 

Put in general this kind of control makes me a bit nervous because it tends to provide the fall sense of security.

**Comment by elarlang** [comment]
It is pretty much the same like:
_V14.3.4 [ADDED, SPLIT FROM 4.3.2] Verify that directory browsing is disabled unless deliberately desired._

It does not solve any authorization or architecture problems, but as 2nd layer of defense, it does not help attackers to deliver successful attacks faster by providing too much information, and it's easy to disable it.

Yes, it's not something critical, but it makes sense to do it.

**Comment by jmanico** [comment]
I agree this is a good requirement that makes automated attacks a lot more difficult.

**Comment by tghosth** [comment]
Ok so I think this should go in the recommendations section as I think it is a nice bonus but I don't think I would want explicitly mandate it.

**Comment by elarlang** [comment]
@tghosth - please do the wording and add it to recommendations.
