### ISSUE TITLE
2.2.2 and 2.7.1 are duplicates

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1811]
2.2.2 | [MODIFIED, SPLIT TO 2.2.12] Verify that restricted authenticators (those using PSTN to deliver OTPs via phone or SMS) are offered only when alternate stronger methods are also offered and when the service provides information on their security risks to users.
-- | --

2.7.1 | Verify that clear text out of band (NIST "restricted") authenticators, such as SMS or PSTN, are not offered by default, and stronger alternatives such as push notifications are offered first.
-- | --

Suggest deleting 2.7.1

**Comment by elarlang** [comment]
@tghosth - do you agree, that 2.7.1 is duplicate of 2.2.2 and can be deleted?

**Comment by tghosth** [comment]
This is another weird NIST artefact, I think we consider this in the V2 rework but it seems likely we will need to do something drastic with this chapter.

**Comment by tghosth** [comment]
Opened #2242 to resolve this clear duplication
