### ISSUE TITLE
Inclusion of Cypher Injection Prevention for Neo4j in ASVS 5.3.4

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#1824]
The current version of the ASVS under item 5.3.4 addresses the importance of protecting against database injection attacks in various database query languages (SQL, HQL, ORM, NoSQL). However, there is no mention of Cypher Injection attacks, particularly in the context of Neo4j databases.

Neo4j is widely used for graph database applications, and like SQL and NoSQL databases, it is also susceptible to injection attacks through its query language, Cypher. It would be beneficial for ASVS to acknowledge and provide guidelines on preventing Cypher Injection attacks.

### Recommended Change

 **Current 5.3.4** | Verify that data selection or database queries (e.g. SQL, HQL, ORM, NoSQL) use parameterized queries, ORMs, entity frameworks, or are otherwise protected from database injection attacks. ([C3](https://owasp.org/www-project-proactive-controls/#div-numbering)) | ✓ | ✓ | ✓ | 89 |

**Updated 5.3.4** | Verify that data selection or database queries (e.g. SQL, HQL, ORM, NoSQL, **Cypher**) use parameterized queries, ORMs, entity frameworks, or are otherwise protected from database injection attacks. ([C3](https://owasp.org/www-project-proactive-controls/#div-numbering)) | ✓ | ✓ | ✓ | 89 |

**Comment by elarlang** [comment]
For me the case is covered, "e.g." lists just examples, not "only for those" and Cypher fits there without mentioning it.

If to do something with the requirement, then first, let's remove ORM (what "language" is this?)

**Comment by tghosth** [comment]
Shout out to my friend @noypearl who did a great talk on this https://www.youtube.com/watch?v=SIqKo7xiPVA
