### ISSUE TITLE
[ASVS 5.0] Fix typos, punctuation, grammar, and standardize spelling to US English

### ISSUE THREAD

**Issue by streichsbaer** [OWASP/ASVS#1827]
The ASVS 5.0 documentation contains several typos, grammatical errors, punctuation inconsistencies, and instances of mixed US/British English spellings. To enhance the document's clarity and maintain a consistent standard of non-technical quality, it is recommended that these issues be addressed.

**Comment by elarlang** [comment]
Hi @streichsbaer and thank you for the effort.

Some side-note for working with document texts - at the moment we mostly work with requirements and "plain-text" part of the document is mostly just carried over (not removed) from v4.0.3, so there is "danger" that some work will be lost (but now it is done anyway). The same comment you can see here: https://github.com/OWASP/ASVS/issues/1132#issuecomment-966857324

I also added some tracking-changes tags to some requirements with my own commit and I'll leave the issue for @tghosth to process further.

**Comment by streichsbaer** [comment]
Thanks, @elarlang. Duly noted.

I just went for it in the hope that it's helpful. I'm also happy to incorporate any changes that you and @tghosth are proposing to get it merged.

**Comment by tghosth** [comment]
As Elar says, some of these texts may be removed but we'll see. In the meantime, I had a quick look through and it seems ok. I made some minor changes but otherwise I am just going to merge.

Would definitely be interested in getting some of your feedback in the issues as well @streichsbaer :)
