### ISSUE TITLE
5.6 - correction, centralised, not single

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#183]
_Verify that a single input validation control is used by the application for each type of data that is accepted._

Should read: 
Verify that a centralised input validation control library is used by the application.

**Comment by jmanico** [comment]
I went with...

| **5.6** | Verify that a centralized input validation control mechanism is used by the application. | ✓ | ✓ | ✓ | 1.0 |

cause it might be a framework feature or language feature as opposed to a separate lib
