### ISSUE TITLE
5.10 - needs simplification

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#184]
_Verify that all SQL queries, HQL, OSQL, NOSQL and stored procedures, calling of stored procedures are protected by the use of prepared statements or query parameterization, and thus not susceptible to SQL injection_

Test the application for SQL (including NOSQL) Injection vulnerabilities. And confirm that all database operation are protected by the use of ORM; or prepared statements; or parameterised queries.

**Comment by jmanico** [comment]
I went with

| **5.10** | Verify that all database queries are protected by the use of parameterized queries or proper ORM usage to avoid SQL injection. | ✓ | ✓ | ✓ | 2.0 |

and committed to master
