### ISSUE TITLE
5.16 - simplify and remove literal examples (potential false sense of security coverage)

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#185]
_If the application framework allows automatic mass parameter assignment (also called automatic variable binding) from the inbound request to a model, verify that security sensitive fields such as “a ccountBalance ”, “r ole ” or “p assword ” are protected from malicious automatic binding._

Suggested:
Test the application for mass parameter assignment (AKA automatic variable binding) vulnerabilities.

**There is no need to provide literal examples. If literal examples are provided, they will be used as the only test vectors.**

**Comment by ordinaehs** [comment]
Sergicles has already done this (or I have an older copy?), but at least the double usage of "verify" should be fixed by removing the "Verify that" at the start.

**Comment by jmanico** [comment]
Change to the following and committed to master.

| **5.16** | Verify that the application does not contain mass parameter assignment (AKA automatic variable binding) vulnerabilities. |  | ✓ | ✓ | 3.1 |
