### ISSUE TITLE
Warnings on github actions

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1851]
The actions run page gives a [list of warnings in the annotations section](https://github.com/OWASP/ASVS/actions/runs/7693711663):
![image](https://github.com/OWASP/ASVS/assets/13623828/d63a99ad-5cc5-44b5-97e6-eafe7fea8147)

Are you able to upgrade the actions to address those @ike?

**Comment by ike** [comment]
Yep!

**Comment by tghosth** [comment]
Thanks @ike, almost all those warnings have gone but it does seem like there might be an issue with the container build now:
https://github.com/OWASP/ASVS/actions/runs/7775191097
https://github.com/OWASP/ASVS/actions/runs/7775199991

**Comment by ike** [comment]
@tghosth that's really odd. On a re-run it works properly. I'll dig in to that failing install script and see if we can make it try again -- I'm assuming some kind of network failure. I'll make a new issue for it.
