### ISSUE TITLE
1.2.2 "User Account" is troubling

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1858]
I suggest we change "user accounts" to "service accounts" based on the context of this requirement.

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.2.2** | [MODIFIED] Verify that communications between back-end application components, including APIs, middleware and data layers, are authenticated and use individual user accounts. ([C3](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 306 |

**Comment by elarlang** [comment]
As it is implementation requirement, it should be moved away from V1 category.

**Comment by elarlang** [comment]
But what exact attack scenario or weakness does the requirement address?

Not all services require authentication.

What is accepted authentication? Basic auth vs some application logic for auth vs certificate...

ping @tghosth

**Comment by tghosth** [comment]
We have a separate and similar discussion going on about this in #1032, I am going to move the comments there and close this for now.
