### ISSUE TITLE
5.22 - potentially interpreted as incorrect advice

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#186]
_Make sure untrusted HTML from WYSIWYG editors or similar are properly sanitized with an HTML sanitizer and handle it appropriately according to the input validation task and encoding task._

Point of WYSIWYG is to render marked-up output.  Encoding may be viewed as incorrect. 

Suggest to simplify: 
Make sure that all untrusted HTML input from WYSIWYG editors or similar is properly sanitized with an HTML sanitizer library.

**Comment by jmanico** [comment]
Excellent change. Added "or framework feature" and committed to master

| **5.22** | Verify that all untrusted HTML input from WYSIWYG editors or similar is properly sanitized with an HTML sanitizer library or framework feature.  | ✓ | ✓ | ✓ | 3.0 |
