### ISSUE TITLE
13.5.3 rate limiting should apply to all APIs

### ISSUE THREAD

**Issue by craig-shony** [OWASP/ASVS#1864]
Rate limiting should be a general control for APIs (move to 13.1). [1.14.8](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x10-V1-Architecture.md#v114-configuration-architecture) is a control regarding correctly identifying IP addresses for rate limiting, but I think there should be a specific API rate limiting control.

**Comment by elarlang** [comment]
Is this covered by those?
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **11.2.1** | [MOVED FROM 11.1.2] Verify that the application will only process business logic flows with all steps being processed in realistic human time, i.e. transactions are not submitted too quickly. | ✓ | ✓ | ✓ | 799 |
| **11.2.2** | [MODIFIED, MOVED FROM 11.1.4] Verify that the application has anti-automation controls to protect against excessive calls to application functionality which could result in mass data exfiltration, junk data creation, resource quota exhaustion, rate limit breaches, out-of-band communication flooding, denial of service, overuse of an expensive resource, etc. | ✓ | ✓ | ✓ | 770 |

**Comment by craig-shony** [comment]
That likely covers it, so then the question is why does this requirement exist?

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **13.5.3** | [ADDED] Verify that rate limiting is in place for WebSocket messages. | ✓ | ✓ | ✓ | 770 |

Is WebSockets a different category from application functionality?

**Comment by elarlang** [comment]
That is a good and valid question, for my taste there are many duplicated requirements in the WebSocket section and the entire section needs some additional work (it is new for v5.0).

**Comment by craig-shony** [comment]
Additionally, is business logic the best category for rate limiting given the description:
_Business logic security must be designed into the system to protect against likely external threats - it cannot be added using web application firewalls or secure communications._
While I think rate limiting should be designed beyond just flipping a switch in the WAF, you can start with the WAF a basic L1. Then a more carefully architected rate limiting approach would be a higher level of security.

**Comment by elarlang** [comment]
Section title is "Anti-automation", category title is "Business logic" and for me it is ok - how many request you allow per time-unit is a business logic decision.

**Comment by elarlang** [comment]
@craig-shony - do you have any further questions or recommendations on the topic or we can close this issue?

**Comment by craig-shony** [comment]
I do still hold the opinion that rate limiting is a critical control for API security, but if my case to move it isn't strong enough, I can close.

**Comment by elarlang** [comment]
It is critical for API security and I have reported it basically to every pen-test case and I use requirement 11.1.4 for that. So I think the problem "rate limiting for API" is covered in the ASVS, we just don't duplicate all the requirements to the API section e.g. you can not take the API section and only test requirements from there.

Based on the current information, I close this issue. If there are other concerns or recommendations, we can always reopen this or create a new issue.
