### ISSUE TITLE
client should not send longer request headers than server can accept

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1867]
spin-off from https://github.com/OWASP/ASVS/issues/1739#issuecomment-1816882008

Problem to solve: if a user controls input that is sent to the server via request header (token) value, it must be validated or sanitized to not be longer than the "max header field size" allowed by server configuration, usually it is 8kB.

Classical functionality: cookies, authorization headers (including access_token JWT's)

If an attacker controls the value and can set it to the client browser, this client will have error 413 or 400 as a response for each request and can not use the service.

**Comment by tghosth** [comment]
This is input validation or sanitization of content going into an HTTP request, it is basically an expansion of https://github.com/OWASP/ASVS/issues/1739#issuecomment-1816882008 where instead of a cookie we are talking about any header entry, correct?

**Comment by elarlang** [comment]
> This is input validation or sanitization of content going into an HTTP request, it is basically an expansion of [#1739 (comment)](https://github.com/OWASP/ASVS/issues/1739#issuecomment-1816882008) where instead of a cookie we are talking about any header entry, correct?

yes, the same problem is for every HTTP **request** header (field) which contains user-controlled input

**Comment by jmanico** [comment]
Please note this is more of a Webserver issue than an application issue. For example, Apache has a default 8k limit for the total size of the request header. NGINX is 4K.

**Comment by elarlang** [comment]
Statement in the issue:
> Problem to solve: if a user controls input that is sent to the server via request header (token) value, it must be validated or sanitized to not be longer than the "max header field size" allowed by server configuration, usually it is 8kB.

Comment from @jmanico 
> Please note this is more of a Webserver issue than an application issue. For example, Apache has a default 8k limit for the total size of the request header. NGINX is 4K.

So, yes it is a webserver configuration question, but at the same time, the application needs to take this limit into account, and do not build longer values than it (a web server) can handle.

**Comment by tghosth** [comment]
Ok can you prepare a requirement text for this @elarlang ?

**Comment by elarlang** [comment]
Not ready yet to propose requirement text, just pieces to take into account:
* situation: if user input is sent to the server automatically by the browser
* problem: if automatically sent content length is larger than the server accepts (examples `Cookie`, `Authorization`, or any custom header that is always sent automatically by the frontend)
* outcome (issue to avoid): then it can cause a client-based denial of service attack - the browser automatically sends too long value and the server always responds with an error

**Comment by tghosth** [comment]
> Verify that the application must validate that user-controlled input in HTTP request headers does not exceed the server's maximum header field size limit (e.g., 8kB for Apache, 4kB for NGINX) to prevent client-based denial of service attacks.

Not sure this solves the problem Elar mentioned here: https://github.com/OWASP/ASVS/issues/1867#issuecomment-1959040703

@elarlang didn't we discuss another requirement related to ensuring a request doesn't get too large, e.g. via cookies?

**Comment by tghosth** [comment]
@elarlang where do you think we go with this?

**Comment by elarlang** [comment]
Although I have seen it often enough to make the issue, I feel that the level of details is a bit edge-case for ASVS.

In a way it is covered by validation and sanitization requirements, but without pointing out the problem itself.

In case we want to have the requirement, we can finetune the wording proposed by Jim https://github.com/OWASP/ASVS/issues/1867#issuecomment-2152451602.

**Comment by tghosth** [comment]
I do think it is covered in other requirements although maybe only indirectly.

Do you think it would be useful to either mention in the intro text for 5.1 or within the body of [5.1.3](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x13-V5-Validation-Sanitization-Encoding.md#v51-input-validation) @elarlang ?

**Comment by tghosth** [comment]
@elarlang to work more on this

**Comment by elarlang** [comment]
To just solve this, we can go further with:
> Verify that the application must validate that user-controlled input in HTTP request headers does not exceed the server's maximum header field size limit (e.g., 8kB for Apache, 4kB for NGINX) to prevent client-based denial of service attacks.

Maybe with 2 changes:
* "Verify that the application must validate that" > "Verify that the application validates that"
* "(e.g., 8kB for Apache, 4kB for NGINX)" > "(usually 4kB or 8kB)"

**Comment by jmanico** [comment]
I like this direction, Elar.

**Comment by elarlang** [comment]
Current proposal (note also changed "request headers" to "request header fields"):
> Verify that the application validates that user-controlled input in HTTP request header fields does not exceed the server's maximum header field size limit (usually 4kB or 8kB) to prevent client-based denial of service attacks.

Section 5.1, level 1.

**Comment by tghosth** [comment]
> Current proposal (note also changed "request headers" to "request header fields"):
> 
> > Verify that the application validates that user-controlled input in HTTP request header fields does not exceed the server's maximum header field size limit (usually 4kB or 8kB) to prevent client-based denial of service attacks.
> 
> Section 5.1, level 1.

PR it in please :)

**Comment by tghosth** [comment]
If you have a good reference link to add somewhere I think that would also be good

**Comment by elarlang** [comment]
> If you have a good reference link to add somewhere I think that would also be good

Nope, but entire world can reference to me here :)

**Comment by elarlang** [comment]
PR made (#2108). I used since level 2 and without a CWE.

Note for the future - if to make few steps make and invent really abstract requirement, it can be merged with 
> Verify that untrusted input is validated for length before being included in a cookie (including as part of a JWT) and that the cookie name and value length combined are not over 4096 bytes.

Both are a bit too detailed requirements in their niche.
