### ISSUE TITLE
new V5 section for architecture requirements

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1868]
## Title

[Proposed](https://github.com/OWASP/ASVS/issues/1484#issuecomment-1933966658) title by @tghosth : Validation and Sanitization Architecture

Preferred title by @elarlang (to re-use current 1.5): Input and Output (processing?) Architecture

## Chapter text

With syntax-specific requirements we say "do the correct thing" and here are the requirements to say "do it in correct order" and in "correct place".

```
<!--
The requirement belongs here if it is:

  * input validation, sanitization or encoding architecture
  * input validation, sanitization or encoding processing (order)

The requirement does not belong here, if it is:

  * syntax specific or clear input validation, sanitization or encoding requirement

reorg: move it to 1st chapter in the paragraph
-->
```

## Requirements

At the moment is the plan to create or move to this section:
* https://github.com/OWASP/ASVS/issues/1553
* https://github.com/OWASP/ASVS/issues/1484
* https://github.com/OWASP/ASVS/issues/1590

**Comment by tghosth** [comment]
Apologies but I don't think "Input and Output (processing?) Architecture" is a good heading, I would prefer my original proposal.

@elarlang can you open a PR for this.

**Comment by elarlang** [comment]
> @elarlang can you open a PR for this.

At the moment I think I'll do it when I have agreements in related issues.
