### ISSUE TITLE
Something amiss in requirement description for v5.0-50.5.3

### ISSUE THREAD

**Issue by kwwall** [OWASP/ASVS#1873]
There is a seemingly incomplete dangling phrase in the requirements description for v5.0-50.5.3 at https://github.com/OWASP/ASVS/blob/master/5.0/en/0x50-V50-Web-Frontend-Security.md?plain=1#L52 that states:

`For example when an API or other resource is loaded directly.`

It seems as though something is missing here or that perhaps it was intended to be a phrase part of the previous sentence.

**Comment by elarlang** [comment]
If you take this phrase out of context, it is not clear. But if you watch it with the context "_Verify that to prevent browsers from rendering content or functionality in HTTP responses in an incorrect context_" it makes it more clear?

Anyway, if you had a question or confusion, it is likely that also someone else may have. Do you have a proposal for improvements?

**Comment by elarlang** [comment]
Requirement was created via https://github.com/OWASP/ASVS/issues/1009

**Comment by kwwall** [comment]
@elarlang - I guess this "create an issue to try to be helpful" experience should be filed under the "no good deed will go unpunished" folder. 🤣  In reality, I was only looking at v5.0-50.5.3 to see if I could get a clarification of v4.0-3-14.4.2 and ended up here when I noticed the note in v5.0-14.4.2 that it had moved to 50.5.3.

Anyhow, I already have my feet in too many other puddles right now, so I prefer _not_ to create a PR for this. I think that what was causing my confusion is that it wasn't obvious what that statement was meant to be associated with, so it seemed to be just floating out there as an independent thought.

That said, how about just rewriting it something like this instead?

Verify that to prevent browsers from rendering content or functionality in HTTP responses in an incorrect context (e.g., when an API or other resource is loaded directly), and that appropriate security controls are in place (e.g. not serving the content unless headers indicate it is the correct context, Content-Security-Policy: sandbox, Content-Disposition: attachment, etc).

**Comment by elarlang** [comment]
> no good deed will go unpunished

This is how ASVS works, it's all volunteer-based and if no-one have any good will, nothing gets better.

No problem, I use your wording and I'll create a PR. Thank you for pointing the "not that clear thing out" and for your recommendation! In general, our update process is written here: https://github.com/OWASP/ASVS/blob/master/CONTRIBUTING.md

I understand that you work through the entire document, so it is wasted time from the ASVS perspective do not have any feedback and recommendations as a side-effect :)
