### ISSUE TITLE
clarifying 5.1.3

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1878]
Spin-off from https://github.com/OWASP/ASVS/issues/1552#issuecomment-1497203051 to solve 5.1.3 separtely.

Current 5.1.3:
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **5.1.3** | [MODIFIED] Verify that all input (HTML form fields, REST requests, URL parameters, HTTP headers, cookies, batch files, RSS feeds, etc) is validated using positive validation (allow lists). Where HTML markup must be accepted for input, refer to requirement 5.2.1. ([C5](https://owasp.org/www-project-proactive-controls/#div-numbering)) | ✓ | ✓ | ✓ | 20 |

The point for the 5.1.3 is agreed here https://github.com/OWASP/ASVS/issues/1552#issuecomment-1497203051

> 5.1.3 everything must be validated using positive validation (allow lists) == do not use disallow/block-lists

So it must ONLY focussing on allow-list vs deny-list

The parts I don't like in this requirement:

  * listing "all potential input sources" - if it is really needed, this should be covered in the chapter text and not duplicated to every requirement. Listing them is also misleading and makes it feel like a duplicate of 5.1.4 (which was also the original reason why the source issue was opened)
  * _Where HTML markup must be accepted for input, refer to requirement 5.2.1._ part, which was added via https://github.com/OWASP/ASVS/issues/1250 and I did not like it back then as well.

As we now have new section under "V5.6 Validation and Sanitization Architecture", maybe we can combine validation and sanitization points to one architecture requirement:

> Verify that input validation and sanitization are using allow-lists, and are not using deny- or blocklists.

**Comment by danielcuthbert** [comment]
There's a lot to discuss here but in essence, I agree with your thoughts around moving it into an architecture requirement (because fundamentally it is right, you have to know what you expect and what is known good before you design the feature/function)

I'd see 5.1.3 reading something like

`Verify that all input is validated using positive validation (allow lists).`

I'm not a fan of specifically calling out HTML here, that is 100% sanitisation and doesn't belong in this and should be elsewhere

**Comment by tghosth** [comment]
I agree with @danielcuthbert and but I would expand this requirement slightly as we are seeing it was an architectural requirement.

`Verify that the application is architected with a centralized input validation capability based on the documented rules which uses positive validation (allow lists).`

**Comment by elarlang** [comment]
Oh please no.
* centralized - it is a completely different requirement and removes focus away from the goal
* documentation in implementation requirement, it must be covered in 1.5.3

The only point it should carry is the allow-list vs deny-list validation.

**Comment by jmanico** [comment]
I like it. Very nice Elar.

**Comment by tghosth** [comment]
> Thinking more about it, I think the word "list" is a bit misleading here - it kind of suggests to have a list of accepted values, but in reality, it also means patterns.
> 
> My proposal: _Verify that all input is validated using positive validation, using an allowed list of values or patterns._
> 
> Also, we need to change the [CWE-20](https://cwe.mitre.org/data/definitions/20.html) "Improper Input Validation" as it's a class/folder and _Vulnerability Mapping: DISCOURAGED_

ok I can accept the wording @elarlang 

I wouldn't bother with a CWE for now.

Are we moving this to 5.6?

**Comment by tghosth** [comment]
Ok so I think we leave it where it is for now

**Comment by tghosth** [comment]
@elarlang I added some info to the explanatory text at the beginning. What do you think?
