### ISSUE TITLE
7.9 - out of scope 

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#188]
_Verify that there is an explicit policy for how cryptographic keys are managed (e.g., generated, distributed, revoked, and expired). Verify that this key lifecycle is properly enforced._

This is much, much broader than ASVS. It's a reasonable ask, but it's not in scope for ASVS.

**Comment by vanderaj** [comment]
I agree - it's too policy / operational, and not developer or tester testable. My suggestion to resolve this. We have V7.14, which asks for keys to be replaceable. Are we missing anything from that control that this one might have covered? Expiry dates stored, warnings for up and coming expiry? What would help ops teams manage the expiry of key materials?

**Comment by vanderaj** [comment]
I'm going to delete the item, and create a new issue for 7.14 as per the above.
