### ISSUE TITLE
V9 rework - 9.2.5 has insufficient value

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1890]
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **9.2.5** | Verify that backend TLS connection failures are logged. | | | ✓ | 544 |

I don't think this requirement is super impactful and I don't think it needs it's own requirement.

We mention this in #1444 but I still don't think it is worthwhile.

I am looking for strong reasons to keep this in but otherwise I am going to remove it.

See work in progress here:
https://github.com/OWASP/ASVS/blob/refresh_v9/5.0/en/0x17-V9-Communications.md#v92-general-service-to-service-communication-security

**Comment by elarlang** [comment]
In a way it's just one security event to log is related to https://github.com/OWASP/ASVS/issues/1795

Personally I think the requirement is reasonable level 3 requirement.

**Comment by jmanico** [comment]
One of the main features of Istio which is state of the art for mutual TLS management for microsservice, is an audit log that will show successes and failures. This is one of the primary ways that we see failures in back end microservices meshes.

But ASVS has a lot of requirements and I'm OK with this either being deleted or used as a level three requirement.

**Comment by tghosth** [comment]
> In a way it's just one security event to log is related to #1795
> 
> Personally I think the requirement is reasonable level 3 requirement.

So I suggest we open an issue to decide if we put this in V7 and remove it from V9 for now. WDYT @elarlang ?

**Comment by elarlang** [comment]
I agree to move it to V7.2 section. Please change CWE to 778.

Do you want to handle it with V9 rework branch or I open separate PR?

**Comment by tghosth** [comment]
I did it in the rework file
