### ISSUE TITLE
Page 14 – I am not sure I agree with having a 3.1 and 3.2 when this is the only Level that even mentions this. 

### ISSUE THREAD

**Issue by defern** [OWASP/ASVS#19]
Page 14 – I am not sure I agree with having a 3.1 and 3.2 when this is the only Level that even mentions this. 

While each level has a variety of sub levels we need to group organizations in “bands” that best fit their maturity.

Could these 4 things be out into a level 3 item or do they really represent a level 4?

**Comment by vanderaj** [comment]
3.1 has been revised to allow custom session managers, but requires them to be solid. 
3.2. is a vital security control to all levels. Users expect logout to be effective if they click it. 
3.3. is how 99.9% of all web apps do it today. It's not a level 3 item.
