### ISSUE TITLE
7.12 - partially redundant control 

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#190]
_Personally Identifiable Information should be stored encrypted at rest and ensure that communication goes via protected channels._

_communication goes via protected channels._ - duplicate, already covered.

Suggested:
Personally Identifiable Information should be stored encrypted at rest.

**Comment by jmanico** [comment]
Nice fix. I took a swing and this and checked "Verify that Personally Identifiable Information (PII) and other sensitive data is stored encrypted while at rest." into 3.1

**Comment by vanderaj** [comment]
Agreed. This is fixed.
