### ISSUE TITLE
7.2.3 (v4.0.3-7.1.3) - wording improvement

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1900]
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **7.2.3** | [MODIFIED, MOVED FROM 7.1.3] Verify that the application logs security relevant events including deserialization failures, input validation failures and incorrect HTTP requests (including requests with an unexpected HTTP verb). | | ✓ | ✓ | 778 |

Proposal: improve the wording to cover all decisions, which are made by the application to not accept user input.

Problems to solve:

  * "input validation failures" - this sounds more like a situation when the program code fails when validating user input, but should be the event when user input gets rejected by the application
  * to be sure it covers file upload situation (#1622)
  * to be sure it covers situations if JWT was not accepted

**Comment by elarlang** [comment]
> Verify that the application logs attempts to bypass security controls.

This part ("security controls") is a bit maybe too abstract. The goal for this requirement should be to address input validation (as unexpected structure for the input), but in current wording it also covers access control and anything else.

> ... which are defined at both the client-side and a trusted service layer such as file upload controls or input validation.

The second part of the proposal is confusing. The message itself is (probably) good - you need to validate the input on the client side and then again on the server side

With current wording, it sounds like it is limited to detect only situations, where client-side validation exists, but it is bypassed. Is this the goal?

**Comment by tghosth** [comment]
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **7.2.3** | [MODIFIED, MOVED FROM 7.1.3] Verify that the application logs attempts to bypass security controls as defined in the relevant design documentation. | | ✓ | ✓ | 778 |

 We should make sure that the new [1.7.3](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x10-V1-Architecture.md#v17-errors-logging-and-auditing-architecture) sufficiently covers this.

~~which are defined at both the client-side and a trusted service layer such as file upload controls or input validation.~~

Add some intro text about the idea of the section and trying to abstract out. Don't eliminate 7.2.1 and 7.2.2 immediately.

**Comment by tghosth** [comment]
Created #1944 to resolve this.

Additional events added to the logging cheatsheet here: https://github.com/OWASP/CheatSheetSeries/pull/1394

**Comment by elarlang** [comment]
I think the requirement should be understandable out of context. I think it makes sense to list some examples there.

The chapter intro text should carry message like: "Every application has its own needs and it is not possible to list all security events as requirements. The list must be analyzed and built through the analysis phase for the application."

**Comment by tghosth** [comment]
> The chapter intro text should carry message like: "Every application has its own needs and it is not possible to list all security events as requirements. The list must be analyzed and built through the analysis phase for the application."

Agree

How about the following

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **7.2.3** | [MODIFIED, MOVED FROM 7.1.3] Verify that the application logs attempts to bypass the security controls defined in the design documentation such as input validation. | | ✓ | ✓ | 778 |

**Comment by elarlang** [comment]
Ok, let's go with that.
