### ISSUE TITLE
Proposal to remove serverless references

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1910]
There was discussion in #483 about adding items specific to serverless functions and a small addition was made here: https://github.com/OWASP/ASVS/commit/c466ce918e401fac90e5e59baf97860e7155387c

The relevant projects appear inactive and not to contain issues that would be in scope for ASVS which are specific to serverless/cloud native apps:
* https://owasp.org/www-project-cloud-native-application-security-top-10/
* https://owasp.org/www-project-serverless-top-10/

I am therefore proposing to remove these specific references in ASVS

**Comment by tghosth** [comment]
Accidentally merged. If anyone has strong opinions we can revisit but I don't think this is controversial.

**Comment by elarlang** [comment]
ok for me.

**Comment by tghosth** [comment]
@set-reminder 1 week @tghosth to close if no further comments
