### ISSUE TITLE
8.2 - confusing and potentially wrong/redundant 

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#192]
_Verify that error handling logic in security controls denies access by default._

Error handling logic is not the same as 'authorisation' or 'authentication' logic, who's job it is to deny access by default. Not sure what errors have to do with anything here. 

This is covered elsewhere in ASVS.

**Comment by jmanico** [comment]
Dropping this per earlier conversation via checkin 7f15ddb510df670943ec7600b1cee1ef1a860460
