### ISSUE TITLE
proposal: move 1.14.6 to V50 (Web Frontend Security)

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1920]
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.14.6** | [MODIFIED] Verify the application only uses client-side technologies which are still supported and considered secure. Examples of technologies which do not meet this requirement include NSAPI plugins, Flash, Shockwave, ActiveX, Silverlight, NACL, or client-side Java applets. | | ✓ | ✓ | 477 |

Proposal to move it to:
https://github.com/OWASP/ASVS/blob/master/5.0/en/0x50-V50-Web-Frontend-Security.md#v507-other-browser-security-considerations

**Comment by elarlang** [comment]
One week of silence. I made PR to celebrate that.

**Comment by jmanico** [comment]
Merged!
