### ISSUE TITLE
2.3.1 and 2.5.1 tags are misleading

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1927]
v4.0.3-2.5.1 is this:

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---:| :---: | :---: | :---: |
| **2.5.1** | Verify that a system generated initial activation or recovery secret is not sent in clear text to the user. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | ✓ | ✓ | ✓ | 640 | 5.1.1.2 |

This requirement has gone through some stuff over the last few years but my understanding is that the tagging should reflect a change from v4.0.3 to v5.

The bleeding edge current tagging is:

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.3.1** | [MODIFIED, MERGED FROM 2.5.1] Verify system generated initial passwords or activation codes are securely randomly generated, at least 6 characters long, may contain letters and numbers, expire after a short period of time, and are single-use. These initial secrets must not be permitted to become the long term password. | ✓ | ✓ | ✓ | 330 | 5.1.1.2 / A.3 |
| **2.5.1** | [DELETED, MERGED TO 2.3.1] | | | | | |

However, I think that this has gotten confused as the requirement has evolved and the actual tagging should be as follows based on [this issue](https://github.com/OWASP/ASVS/pull/650#issuecomment-514540750).

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.3.1** | **[MODIFIED]** Verify system generated initial passwords or activation codes are securely randomly generated, at least 6 characters long, may contain letters and numbers, expire after a short period of time, and are single-use. These initial secrets must not be permitted to become the long term password. | ✓ | ✓ | ✓ | 330 | 5.1.1.2 / A.3 |
| **2.5.1** | **[DELETED, INCORRECT]** | | | | | |

Opinions @elarlang ?

**Comment by elarlang** [comment]
I don't have any strong opinions on this.

Related issue https://github.com/OWASP/ASVS/issues/1014 and PR https://github.com/OWASP/ASVS/pull/1041 and merge commit https://github.com/OWASP/ASVS/pull/1041/commits/89986cee587f1495ce23dd3ee9cc71f2464d18e3.

**Comment by tghosth** [comment]
Ok I opened a PR because I think this is clear cut, whatever happened afterwards is not relevant to the tagging :)
