### ISSUE TITLE
Essential Controls

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#193]
Construct a list of the Top Essential Controls, with a bit of a discussion of why this is an issue, and what to do about it in the front area.

**Comment by Sergicles** [comment]
Actually, I was going to do this later today, just after I finish adding my notes... Where can I share?

**Comment by vanderaj** [comment]
How did it go? vanderaj@owasp.org would be good, also a pull request would also work. 

My current thoughts is to re-define L1 as "Core" or "Essential" by objectively including them only if they are rated high (CVSSv3 7.0 - 8.9) or critical (CVSSv3 9.0-10.0). 

Thoughts?

**Comment by jmanico** [comment]
The first category is implied to be essential; closing this for now
