### ISSUE TITLE
8.7 - Literal examples, simplify

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#194]
_Verify that the application does not log sensitive data as defined under local privacy laws or regulations, organizational sensitive data as defined by a risk assessment, or sensitive authentication data that could assist an attacker, including user’s session identifiers, passwords, hashes, or API tokens._

Verify that the application does not log sensitive data, as defined under local privacy laws or  organizational security policy.

**Comment by vanderaj** [comment]
Serg - I've simplified this, but I've also included the a few of the things devs have previously asked us to include without referring to a privacy policy or risk assessment. It should be testable without unless it's a huge topic.
