### ISSUE TITLE
2.3.4 does not seem like registration

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1940]
The following likely needs to be recategorized

2.3.4 | [ADDED] System administrators should not be able to change or choose any user's password, but rather only be able to initiate the password reset process for the user. | ✓ | ✓ | ✓ | 620
-- | -- | -- | -- | -- | --

**Comment by elarlang** [comment]
It is "V2.3 Authenticator Lifecycle", not the registration section.  However, the requirement can be in most of the V2 sections.

But if you would like to re-organize requirements to sections, then the entire V2.1 requires some work :)

**Comment by csfreak92** [comment]
+1 on Elar :)

**Comment by tghosth** [comment]
Yeah I agree but I think we need to finish with the requirements and then figure out the new sections.

**Comment by jmanico** [comment]
Ok to let this go
