### ISSUE TITLE
Minor V7 changes

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1948]
* [x] 7.1.2 merge into 7.1.1
* [x] 7.1.4 make clear in intro that other sources are needed
* [x] 7.1.7 fix english
* [x] 7.2.1/7.2.2 clarify wording
* [x] 7.3.1 make sure it is not duplicated in V5.
* [x] Review all chapter wording

**Comment by tghosth** [comment]
@elarlang I'd appreciate your input on the logging rework

**Comment by elarlang** [comment]
I have reviewed all related commits separately already. If we think that something needs improvement again, then we can make it happen.
