### ISSUE TITLE
8.8 - simplify

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#195]
_Verify that all non-printable symbols and field separators are properly encoded in log entries, to prevent log injection._

Test the application for log injection vulnerabilities.

**Comment by vanderaj** [comment]
I've made it easier to understand, but ASVS should have the positive ("what to do") and which will prevent the negative ("what to test"). We will be carefully reviewing each control using that standard as we get closer to the end. Let me know if we don't satisfy it elsewhere.
