### ISSUE TITLE
8.9 - partially redundant 

### ISSUE THREAD

**Issue by Sergicles** [OWASP/ASVS#196]
_Verify that log fields from trusted and untrusted sources are distinguishable in log entries._

Trust is defined by a 'trust boundary'. That is, an abstract concept, that may shift over time. There should be no differentiation between trusted and untrusted sources. Validation is global and centralised. One log source should not be any less or more secure than the other, in terms of validation.

May as well remove this control, or state that all log sources need to be validated.

**Comment by vanderaj** [comment]
8.9 has been removed.
