### ISSUE TITLE
Make 2.1.14 easier and more simplified

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1977]
I would like to suggest that we change:

2.1.14 | [ADDED, SPLIT FROM 2.1.7, LEVEL L1 > L3] Verify that passwords submitted during account registration or password changes are checked against a set of breached username and password pairs. |   |   | ✓ |   | 5.1.1.2
-- | -- | -- | -- | -- | -- | --

... to ...

2.1.14 | [ADDED, SPLIT FROM 2.1.7, LEVEL L1 > L3] Verify that passwords submitted during account registration or password changes are checked against a set of breached passwords. |   |   | ✓ |   | 5.1.1.2
-- | -- | -- | -- | -- | -- | --

Hey @tghosth I know we talked about this in the past, I'm with you on this.

**Comment by ImanSharaf** [comment]
Can we change password to secret? For example, assume we have a crypto exchange that works with Interac to transfer money and the users should provide Q&As to receive the money on the other end, should we check those answers against  breached databases too?

**Comment by jmanico** [comment]
I think that would be a different requirement. Credential stuffing is mostly specific to passwords, I think. If you are using security questions for security (which NIST recommends against) then there will be duplication.

**Comment by randomstuff** [comment]
For what it's worth, [NIST SP800 63b](https://pages.nist.gov/800-63-3/sp800-63b.html), talks about [Memorized Secrets](https://pages.nist.gov/800-63-3/sp800-63b.html#sec5):

> A Memorized Secret authenticator — commonly referred to as a password or, if numeric, a PIN — is a secret value intended to be chosen and memorized by the user.

**Comment by jmanico** [comment]
@randomstuff, I think this comment from NIST is good, but the requirement above is specific to passwords.

Credential stuffing involves the use of previously breached passwords, and we want to disallow users from using passwords that have been exposed in breaches. However, when it comes to other secrets like security questions or PIN codes, we need to allow users to use a PIN code or security questions that may have been breached, as the list of possible values for these factors is much smaller than for passwords.

Does this make sense? Any counterarguments are very welcome!

**Comment by tghosth** [comment]
Credential stuffing involves the use of both usernames and passwords.

The current requirement came out of a long discussion which is summarised here:
https://github.com/OWASP/ASVS/issues/841#issuecomment-884058667

I believe the intention of this requirement was to make it more focused by only focusing on known breached passwords, **for that particular user**.

The problem with that is that you would need to find a data source for that information which is not trivially available and this is why it was L3.

The alternative is to say that supplied passwords should be checked against all known breached passwords. That is a much larger data source to check against but the data source is easier to obtain, e.g. from [Pwned Passwords](https://haveibeenpwned.com/Passwords).

@jmanico can you confirm which approach you are advocating?

**Comment by jmanico** [comment]
Josh,

I have admitted changed my mind here after talking to Troy Hunt. I think checking against *all* breached passwords is the best path.

**Comment by tghosth** [comment]
So in that case please open a PR as I think that it is a more straightforward requirement.
