### ISSUE TITLE
Implement Requirement for Anomalous Behavior Detection 

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#1979]
During the course of application operations, it is crucial to identify and respond to anomalous behavior that could indicate security threats or system malfunctions. Currently, the ASVS does not explicitly cover the need for implementing codes designed to detect such behaviors.

Requirement: `The application must incorporate a system to detect and alert on anomalous behaviors. This system should monitor user activities and system operations, utilizing models or rules to differentiate between normal and abnormal behaviors, and promptly notify designated persons through real-time alerts.`

**Comment by tghosth** [comment]
We have something like this in business logic I think, can you take a look?

**Comment by jmanico** [comment]
Yea see https://github.com/OWASP/ASVS/blob/master/5.0/en/0x19-V11-BusLogic.md

We already have 11.6.1. Is this good enough for you, @ImanSharaf ?

_11.6.1 Verify the application has a capability to detect and respond to anomalous activity within its business logic, including the ability to alert administrators when such activity occurs._

**Comment by jmanico** [comment]
Are we ok to close this issue?

**Comment by ImanSharaf** [comment]
Awesome!
