### ISSUE TITLE
5.3.4 should also mention stored procedures.

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1993]
[5.3.4](https://appsecg.host/5.3):

> [MODIFIED] Verify that data selection or database queries (e.g. SQL, HQL, NoSQL, Cypher) use parameterized queries, ORMs, entity frameworks, or are otherwise protected from database injection attacks.

Suggested modification:

> [MODIFIED] Verify that data selection or database queries (e.g. SQL, HQL, NoSQL, Cypher) use parameterized queries, ORMs, entity frameworks, or are otherwise protected from database injection attacks. **This should also be considered when writing stored procedures.**

**Comment by jmanico** [comment]
A few notes:
1) I like this change re: stored procedures
2) Can we somehow add the term "SQL Injection" in here? It's a very popular term. This is just an ask, not necessary.

**Comment by tghosth** [comment]
Opened #1999 to resolve
