### ISSUE TITLE
ASVS Assessment Checklist 3.0.1 includes removed requirement 2.30

### ISSUE THREAD

**Issue by cxzzero** [OWASP/ASVS#201]
Just to notice that the [ASVS Assessment Checklist 3.0.1](https://github.com/OWASP/ASVS/blob/master/3.0.1/OWASP%20Application%20Security%20Verification%20Standard%20Checklist%203.0.1.xlsx) has the requirement 2.30 which was removed.

Regards,
Juan

**Comment by jmanico** [comment]
Done! c64c9995b3348584de18db0353e2b2bf50c1ec5b
