### ISSUE TITLE
Set Account Lockout ASVS Levels 1-3 Aligned to NIST, PCI-DSS, CIS et al

### ISSUE THREAD

**Issue by cmlh** [OWASP/ASVS#2011]
[ASVS Requirement 2.2.1 states "... More than 5 failed authentication attempts per hour for a single account should trigger some sort of reaction or alert. ..."](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x11-V2-Authentication.md#v22-general-authenticator-security)

To expand on @TheDauntless comment within https://github.com/OWASP/ASVS/issues/906#issuecomment-782739441 I'd like the ASVS Levels to align within PCI-DSS and CIS.

[NIST Special Publication 800-63B](https://pages.nist.gov/800-63-3/sp800-63b.html#sec5) sets the limit to <100 as reproduced below:

![image](https://github.com/user-attachments/assets/dcca5190-ff31-43e8-a236-ec6025507436)

[PCI-DSS 4.0.1](https://docs-prv.pcisecuritystandards.org/PCI%20DSS/Standard/PCI-DSS-v4_0_1.pdf) sets the limit to 10 as reproduced below:

![image](https://github.com/user-attachments/assets/cd787ddd-83fe-4366-8cc8-e980ab21c5a0)

[CIS](https://www.cisecurity.org/insights/blog/cis-password-policy-guide-passphrases-monitoring-and-more) sets the limit to 5 as reproduced below as provided by @TheDauntless:

![image](https://github.com/user-attachments/assets/fa636158-30d0-404d-8fc8-d26fd4a5a7c7)

Can we set the limits to <=100, 10, 5 for ASVS Level 1, 2, 3 respectively?

[All other issues referencing "lockout"](https://github.com/OWASP/ASVS/issues?q=is%3Aissue+lockout)

**Comment by elarlang** [comment]
Here are two things mixed - the issue title asks to align "account lockout limits" but the content points to rate limiting and account lockout, and those are in conflict with each other (NIST vs PCI)

The direction should be do NOT use lockouts.

We have separate issues to handle those:
* #1763 - for rate limiting
* #2134 - for (no) lockouts

Closing this as duplicate.
