### ISSUE TITLE
Insert Burp Sequencer Test Cases for Randomness

### ISSUE THREAD

**Issue by cmlh** [OWASP/ASVS#2024]
Can we please insert the @PortSwigger [Burp Sequencer randomness tests](https://portswigger.net/burp/documentation/desktop/tools/sequencer/results/tests) into  [ASVS Requirement V63 Random Values](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x14-V6-Cryptography.md#v63-random-values)?

[All other issues referencing "random"](https://github.com/OWASP/ASVS/issues?q=is%3Aissue+random)

**Comment by tghosth** [comment]
I'd rather not mention proprietary tools and this also would only work where a lot of values can be easily generated which won't always be the case.
