### ISSUE TITLE
2.1 - Merge with 2.4

### ISSUE THREAD

**Issue by TheDauntless** [OWASP/ASVS#203]
> 2.1 - Verify all pages and resources by default require authentication except those specifically intended to be public.

> 2.4 - Verify all authentication controls are enforced on the server side.

2.1 is useless without 2.4. If authentication is done client side, it shouldn't even count as proper authentication. The "by default" is also weird, as it is followed by "the only exception".

So merge:
> 2.1 Verify all pages and resources are protected by server-side authentication, except those specifically intended to be public.

**Comment by danielcuthbert** [comment]
merged and removed 2.4 in 3.1
