### ISSUE TITLE
Add new v5 item on Deserialization

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#204]
Need this for ASVS 3.1

**Comment by vanderaj** [comment]
@jmanico This is likely to end up in V5, and possibly in V1 (don't send serialized objects to untrusted clients), so allocating it to you

**Comment by jmanico** [comment]
This has been committed to master https://github.com/OWASP/ASVS/commit/4c8d9cd52661519207082af71294b9ff82a6dacc
