### ISSUE TITLE
V6 points to wrong requirement 5.16

### ISSUE THREAD

**Issue by eoftedal** [OWASP/ASVS#206]
From V6

> This section was incorporated into V5 in Application Security Verification Standard 2.0.
> ASVS requirement 5.16 addresses contextual output encoding to help prevent Cross Site
> Scripting. 

However 5.16 is:

> If the application framework allows automatic mass
> parameter assignment (also called automatic variable binding)
> from the inbound request to a model, verify that security
> sensitive fields such as “accountBalance”, “role” or
> “password” are protected from malicious automatic binding

Looks like 5.15, 5.22, 5.23 are better fits.

**Comment by jmanico** [comment]
Hey @vanderaj I do not see this text anymore in the .MD files. Is section 6 fully gone now?

**Comment by jmanico** [comment]
This is resolved for 3.0.1 only via these commits to master. https://github.com/OWASP/ASVS/commit/14aa0be9a6fd8060e8f7d2041ed8d5aad9c93704 and https://github.com/OWASP/ASVS/commit/04fd0cf77979a777ffe11af21db3889593ca9702
