### ISSUE TITLE
Move all documentation requirements out of v1 and into their respective sections when possible

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#2067]
I feel its a bad design to have access control requirements in v1. I feel they belong in v12 so v12 is complete. I suggest we do this for all documentation requirements **_when we can_** so each section is as complete as possible in and of itself. I do not like the idea of having to hop to several different sections to get requirements for one category.

**Comment by elarlang** [comment]
I don't think we need another opened issue for that, as I responded (https://github.com/OWASP/ASVS/issues/2065#issuecomment-2331341039) just 15min ago in another issue

> What we going to do with current V1 content is up to separate discussion #1063 / #1831

**Comment by jmanico** [comment]
Fair enough, you can close this out.
