### ISSUE TITLE
V51 OAuth client CSRF protection for token request

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#2068]
At the moment we have requirement:

| # | Description | L1 | L2 | L3 |
| :---: | :--- | :---: | :---: | :---: |
| **51.1.1** | [ADDED] Verify that the Authorization Server supports CSRF protection either using the mechanism provided by PKCE, the "nonce" parameter or the "state" parameter. | ✓ | ✓ | ✓ |

In reality, CSRF protection should be on the OAuth Client side to avoid triggering token request. So the requirement should be on the OAuth Client section and I don't think we need current requirement.

Direction should be something like this (wordsmithing needed):
> Verify that the OAuth Client has protection against CSRF attacks for triggering token requests using PKCE functionality or checking the state parameter that was sent in the authorization request.

**Comment by jmanico** [comment]
PKCE based CSRF protection requires that the authorization server supports PKCE. It's the final step in the authorization flow where the **_authorization server verifies the code challenge_** from the client against the code verifier sent during the token request.

**Comment by elarlang** [comment]
That is all true, but...

We don't need to verify from a security perspective, what is **supported** but we need to verify, that **defense is in place**. For example, let's say the Authorization Server supports PKCE or sends the `state` value correctly back to the client, but if the client does not use it, it does not matter. We are not testing the functionality for the Authorization Server but we are testing, is there a defense against certain attacks or vulnerabilities.

**Comment by elarlang** [comment]
Also note, that PKCE flow itself will be covered by other requirements and should not be duplicated into this one. https://github.com/OWASP/ASVS/issues/2041

**Comment by jmanico** [comment]
> That is all true, but...
> 
> We don't need to verify from a security perspective, what is **supported** but we need to verify, that **defense is in place**. For example, let's say the Authorization Server supports PKCE or sends the `state` value correctly back to the client, but if the client does not use it, it does not matter. We are not testing the functionality for the Authorization Server but we are testing, is there a defense against certain attacks or vulnerabilities.

That makes total sense, gotchya.

**Comment by elarlang** [comment]
ping @randomstuff @TobiasAhnoff - any (dis)agreements or feedback? (Including checking the wording)

**Comment by randomstuff** [comment]
@elarlang, Look good to me.

Nitpick, I am wondering if a wording such as « [ADDED] Verify that the Authorization Server supports CSRF protection. This can for example be achieved using the mechanism provided by PKCE, the "nonce" parameter or the "state" parameter. » would not be better (following [this argument](https://github.com/OWASP/ASVS/issues/2041#issuecomment-2349842644)).

**Comment by randomstuff** [comment]
> [ADDED] Verify that the Authorization Server supports CSRF protection either using the mechanism provided by PKCE, the "nonce" parameter or the "state" parameter.

Nitpick, it is probably clear but would be worth mentioning that we are talking about CSRF protection of the client `redirect_uri` for the authorization code flow here?

**Comment by elarlang** [comment]
@randomstuff - I think you analyzed current requirement that I referenced, not the requirement I proposed:
> Verify that the OAuth Client has protection against CSRF attacks for triggering token requests using PKCE functionality or checking the state parameter that was sent in the authorization request.

**Comment by randomstuff** [comment]
@elarlang, Oh yes :)

**Comment by tghosth** [comment]
> 
> > Verify that the OAuth Client has protection against CSRF attacks for triggering token requests using PKCE functionality or checking the state parameter that was sent in the authorization request.

LTGM

**Comment by elarlang** [comment]
Requirement added to **V51.2 OAuth Client**

| # | Description | L1 | L2 | L3 |
| :---: | :--- | :---: | :---: | :---: |
| **51.2.5** | [ADDED] Verify that, if the code flow is used, the OAuth Client has protection against CSRF attacks which trigger token requests, either by using PKCE functionality or checking the state parameter that was sent in the authorization request. | ✓ | ✓ | ✓ |
