### ISSUE TITLE
Overlap V2.7 and V2.33.

### ISSUE THREAD

**Issue by ordinaehs** [OWASP/ASVS#208]
There appears to be some overlap between V2.7 and the new V2.33, to the extent that V2.33 could be said to be fully contained in V2.7. I would suggest the removal of the the mention of "password managers" from V2.7, so that V2.7 focuses purely on the password fields themselves, and V2.33 on the password manager support.

**Comment by jmanico** [comment]
Thank you for this excellent and simple fix to ASVS. The change has been made and will appear in ASVS 3.1.
