### ISSUE TITLE
deduplicate or merge 14.6.2 and 1.14.7

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#2082]
We have 2 quite similar requirements:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **14.6.2** | [ADDED] Verify that communications between back-end application components, including APIs, middleware and data layers, are performed with the least necessary privileges. | | ✓ | ✓ | 272 |
| **1.14.7** | [MODIFIED, MOVED FROM 1.2.1] Verify the use of unique or special low-privilege operating system accounts for all back-end application components, services, and servers. | | ✓ | ✓ | 250 |

We may say that the points are:
* 14.6.2 "least necessary privileges" on every layer
  * CWE-272: Least Privilege Violation
* 1.14.7 "unique and low privilege accounts in OS"
  * CWE-250: Execution with Unnecessary Privileges

Is there any good reason to keep them separately or those can be merged?

~~In which section to store it/those, is discussed in #2072~~

**Comment by tghosth** [comment]
I would suggest merge

**Comment by elarlang** [comment]
If you are able to come up with the text, then the label is: `[MODIFIED, MOVED FROM 1.2.1]`

I think we can carry the section choice also to this issue, the question is:
* to move/keep the requirement in V14.6
* or to create a "service authorization" (or something similar) section to V4 to be with the same style as authentication (V2.10 service authentication)

**Comment by tghosth** [comment]
My suggested merged wording:

> Verify that communications between back-end application components, including local or operating system services, APIs, middleware and data layers, are performed with accounts assigned the least necessary privileges.

I am a little torn on where it should go. My feeling at the moment (as I said here https://github.com/OWASP/ASVS/issues/2072#issuecomment-2357570281) is that for communication between services that is outside our standard authentication/session management mechanism we should move it all to configuration as that we have less control over the specifics but rather it becomes a config question.

**Comment by elarlang** [comment]
> ... are performed with accounts assigned the least necessary privileges.

can we also ask the account to be unique or dedicated / not shared?

**Comment by tghosth** [comment]
> > ... are performed with accounts assigned the least necessary privileges.
> 
> can we also ask the account to be unique or dedicated / not shared?

I think we'll leave that for 2.10.1.

@set-reminder @tghosth now to open a PR

Should be moved and modified rather than added

**Comment by tghosth** [comment]
Opened #2094
