### ISSUE TITLE
Appendix A page 38-41 – Inconsistent Capitalization in the Suggested ASVS Level Description 

### ISSUE THREAD

**Issue by defern** [OWASP/ASVS#21]
Appendix A page 38-41 – Inconsistent Capitalization in the Suggested ASVS Level Description 

Wording in the Suggested Level All start with a small character except for the ones in Retail, Food, Hospitality

For Example:
Level 1: all Internet-accessible applications.

Level 2: Suitable for business applications, product catalogue information, internal corporate information, and applications with limited user information (e.g. contact information).  Applications with small or moderate amounts of payment data or checkout functionality.

**Comment by vanderaj** [comment]
Resolved in latest draft. Thank you. :)
