### ISSUE TITLE
My name as a contributor/reviewer

### ISSUE THREAD

**Issue by ordinaehs** [OWASP/ASVS#210]
I noticed I am named as a contributor/reviewer for version 3.1. First of all, thanks! :)

But let's not use my nickname. You can use the company-name "Ordina", or my personal name "Dr Daniël Geerts" instead.

**Comment by danielcuthbert** [comment]
Pleasure. it's been great to have your help. Noted and added.

**Comment by vanderaj** [comment]
Daniel's name was left off 4.0. Need to fix!
