### ISSUE TITLE
V17: Mobile Verification Requirements

### ISSUE THREAD

**Issue by danielcuthbert** [OWASP/ASVS#212]
With the Mobile ASVS effort in full swing, I wonder if it's not time to retire this and link to MASVS?

**Comment by jmanico** [comment]
I agree 100%. I suggest we drop the entire mobile section and point to the Mobile ASVS instead. So ASVS really becomes about web apps and web services.

**Comment by jmanico** [comment]
I talked to the MASVS team and they are on board with this move.

**Comment by jmanico** [comment]
Mobile requirements have all gone away per this commit. https://github.com/OWASP/ASVS/commit/942642af38118ea9b2b1ec5562f5245698b98e0c
