### ISSUE TITLE
Contributor guidelines

### ISSUE THREAD

**Issue by stuartgunter** [OWASP/ASVS#213]
Contributor guidelines

I would love to help with this project, but I'm finding it difficult knowing where I can be of most use. Most issues appear to be assigned already, so I don't want to step on anyone's toes (or waste time on tasks that are already in progress). I thought of creating a `CONTRIBUTING` file - similar to [zaproxy](https://github.com/zaproxy/zaproxy/blob/develop/CONTRIBUTING.md) - but I didn't know enough about how the project leads want others to contribute, how issues are managed / assigned, etc.

It would be great to have some guidelines / instructions on how we can help out. I'm happy to help with this, but would need some direction from existing committers / project leads.

**Comment by danielcuthbert** [comment]
hey @stuartgunter 

Glad to have the offer of help. Easiest way right now is to look at any of the open issues for the 4.0 branch and grab one that appeals. Just because they are assigned doesn't mean you can't be forceful ;) 

Thanks in advance
