### ISSUE TITLE
2.10.4 and 6.4.1 seem like duplicates

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#2130]
We currently have the following requirements:

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.10.4** | [GRAMMAR] Verify passwords, integrations with databases and third-party systems, seeds and internal secrets, and API keys are managed securely and not included in the source code or stored within source code repositories. Such storage should resist offline attacks. The use of a secure software key store (L1), hardware TPM, or an HSM (L3) is recommended for password storage. | | ✓ | ✓ | 798 | |

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **6.4.1** | [MODIFIED] Verify that a secrets management solution such as a key vault is used to securely create, store, control access to and destroy back-end secrets such as service account or 3rd party application credentials. | | ✓ | ✓ | 798 |
| **6.4.2** | [MODIFIED] Verify that key material is not exposed to the application (neither the front-end nor the back-end) but instead uses an isolated security module like a vault for cryptographic operations. | | ✓ | ✓ | 320 |

(6.4.2 included for information although I don't think it is a duplicate.)

I think 2.10.4 and 6.4.1 are duplicates.

We also need to think in the context of whether section 2.10 should move to the config chapter.

**Comment by elarlang** [comment]
2.10.4 provides the problem statement and 6.4.1 a way how to solve the problem. In case  6.4.1 is the one and only way to solve 2.10.4, those can be merged.

At the moment both requirements have a clear focus, and both should be carried to the merged requirement.

My worry at the moment is - is the Cryptography paragraph your default idea to look for the requirement handling the "hardcoded credentials" or secret management in general?

**Comment by meghanjacquot** [comment]
> We currently have the following requirements:
> 
> #	Description	L1	L2	L3	CWE	[NIST §](https://pages.nist.gov/800-63-3/sp800-63b.html)
> **2.10.4**	[GRAMMAR] Verify passwords, integrations with databases and third-party systems, seeds and internal secrets, and API keys are managed securely and not included in the source code or stored within source code repositories. Such storage should resist offline attacks. The use of a secure software key store (L1), hardware TPM, or an HSM (L3) is recommended for password storage.		✓	✓	798	
> #	Description	L1	L2	L3	CWE
> **6.4.1**	[MODIFIED] Verify that a secrets management solution such as a key vault is used to securely create, store, control access to and destroy back-end secrets such as service account or 3rd party application credentials.		✓	✓	798
> **6.4.2**	[MODIFIED] Verify that key material is not exposed to the application (neither the front-end nor the back-end) but instead uses an isolated security module like a vault for cryptographic operations.		✓	✓	320
> (6.4.2 included for information although I don't think it is a duplicate.)
> 
> I think 2.10.4 and 6.4.1 are duplicates.

I think that they have overlap, but not that they are complete duplicates. Depending upon which part is emphasized I think it makes more sense to keep the merge in chapter 2 or if other parts are emphasized it could make sense to move it to chapter 6. 

If the emphasis is on the secret management from 2.10.4 then I think it makes sense to move it to 6.10.X. If the emphasis is on how services authenticate then it should stay in 2.10.X. I lean more towards merging language and moving it 6.10.X. 

This could be an example of merged language, "Verify that a secrets management solution such as a key vault is used to securely create, store, control access to, and destroy back-end secrets, such as service accounts or 3rd party application credentials. Verify that no secrets are included in the source doe or stored within source code repositories. Possible solutions could include the following: the use of a secure software key store (L1), hardware TPM (L2), or an HSM (L3).

> 

> We also need to think in the context of whether section 2.10 should move to the config chapter.

I don't think 2.10 should move to the configuration chapter. The items in 2.10 all heavily relate to authentication. For example, from 2.10.1 "Authentication should use individual service accounts,...", and from 2.10.2 "Verify that if a credential has to be used for service authentication,...".

**Comment by elarlang** [comment]
> I don't think 2.10 should move to the configuration chapter. The items in 2.10 all heavily relate to authentication. For example, from 2.10.1 "Authentication should use individual service accounts,...", and from 2.10.2 "Verify that if a credential has to be used for service authentication,...".

The rest of V2 is about the user authentication into/for the application, V2.10 is about authentication between services and therefore does not really match with the rest of the paragraph.

**Comment by meghanjacquot** [comment]
> > I don't think 2.10 should move to the configuration chapter. The items in 2.10 all heavily relate to authentication. For example, from 2.10.1 "Authentication should use individual service accounts,...", and from 2.10.2 "Verify that if a credential has to be used for service authentication,...".
> 
> The rest of V2 is about the user authentication into/for the application, V2.10 is about authentication between services and therefore does not really match with the rest of the paragraph.

But isn't that ok that different sections relate to different aspects of auth? 

For example, the intro V2 states "Authentication is the process of establishing or confirming the authenticity of an individual or device. It involves verifying claims made by a person or about a device, ensuring resistance to impersonation, and preventing the recovery or interception of passwords." 

So auth with service seems like it would fit into the V2 section?

**Comment by meghanjacquot** [comment]
Ahh, that's helpful additional information, thanks Elar. 

If we're ignoring the intro text, and considering V2 to be more focused on Auth regarding users, then I agree that it would make sense to associate these with V14.

Maybe we can agree upon language regarding 2.10.4 and 6.4.1 and then I can open up a new issue for moving parts of V2 to V14. 

So thoughts on this as merged language, @elarlang @jmanico @tghosth :

"Verify that a secrets management solution such as a key vault is used to securely create, store, control access to, and destroy back-end secrets, such as service accounts or 3rd party application credentials. Verify that no secrets are included in the source doe or stored within source code repositories. Possible solutions could include the following: the use of a secure software key store (L1), hardware TPM (L2), or an HSM (L3)."

**Comment by tghosth** [comment]
Apologies for the delay:

I think overall your merge proposal makes sense. I don't like how prescriptive the final sentence was historically and I also think that distinguishing between an HSM and TPM was a bit weird. I think the key thing is that we want a hardware backed mechanism although I think that should be L3 only.

"_Verify that a secrets management solution such as a key vault is used to securely create, store, control access to, and destroy back-end secrets, such as service accounts or 3rd party application credentials. Secrets must not be included in the source code or stored within source code repositories. For a L3 application, this should involved a hardware-backed solution such as an HSM._"

@elarlang what are your thoughts on this wording?

**Comment by elarlang** [comment]
I like the list from 2.10.4 that carries attention to widespread mistakes:
>  Verify passwords, integrations with databases and third-party systems, seeds and internal secrets, and API keys ...

I think the current abstract "service accounts or 3rd party application credentials" does not cover all that.

---

> Secrets must not be included in the source code or stored within source code repositories.

I think "stored within source code repositories" is just a duplicate for the 1st part here.

I have seen too many times, that 3rd party integration secrets are stored as plain-text to a database and managed via user-interface.

**Comment by tghosth** [comment]
Ok so updated suggestion, what do you think of my CI/CD addition @elarlang @meghanjacquot ?

"_Verify that a secrets management solution such as a key vault is used to securely create, store, control access to, and destroy back-end secrets, such as passwords, integrations with databases and third-party systems, seeds and internal secrets, and API keys. Secrets must not be included in source code **or as CI/CD variables**. For a L3 application, this should involved a hardware-backed solution such as an HSM._"

**Comment by elarlang** [comment]
> or as CI/CD variables

as CI/CD itself is not in the scope, I think we need to change the perspective for that part

> or not received as environment variables from CI/CD

---

> I have seen too many times, that 3rd party integration secrets are stored as plain-text to a database and managed via user-interface. So I would like to get special attention for this one.

Makes the requirement long but I think it should be mentioned somehow.

**Comment by tghosth** [comment]
I propose:

"Verify that a secrets management solution such as a key vault is used to securely create, store, control access to, and destroy back-end secrets, such as passwords, integrations with databases and third-party systems, seeds and internal secrets, and API keys. Secrets must not be included in source code **or be received as CI/CD variables**. For a L3 application, this should involved a hardware-backed solution such as an HSM."

> I have seen too many times, that 3rd party integration secrets are stored as plain-text to a database and managed via user-interface. So I would like to get special attention for this one.

Did we not have a whole other requirement about this?

**Comment by elarlang** [comment]
> Did we not have a whole other requirement about this?

Not really. Probably you meant current 4.3.3 with that, but it's focus is to take down escalation from UI or from authorization point of view, not from secure storage point of view.

> V4.3.3 Verify that, if the application allows changing highly sensitive configurations around passwords or connection parameters for integrations with databases and third-party systems, they are protected by extra controls such as re-authentication or multi-user approval.

At the same time, based on 2.10.4 / 6.4.1 there should be no such functionality like password change for 3rd party integration in UI, but the point for V4.3.3 stays.

**Comment by tghosth** [comment]
> Makes the requirement long but I think it should be mentioned somehow.

Ok so how would you update the requirement I proposed here: https://github.com/OWASP/ASVS/issues/2130#issuecomment-2439871335

**Comment by elarlang** [comment]
It does not cover it clearly but let's go with that.

**Comment by tghosth** [comment]
Opened #2130 @elarlang

**Comment by tghosth** [comment]
My thought is to handle the merge for now and then hold off on a decision about a move to V14

**Comment by meghanjacquot** [comment]
I think that handling the merge for now sounds good. We're close to having all issues with tagging for V14 closed and then could do a general publish of the chapter for public comment with awareness that more things might continue to change.

**Comment by elarlang** [comment]
Offtopic note, but my proposal is, that we don't ask feedback from wide audience for paragraphs separately, as those may not give full picture and can not be taken out of context. Also, those are not finished from re-organizing the chapters and requirement point of view.

We can always ask feedback for targeted chapters and requirement from targeted audience, but for wider publish and noise I prefer to wait for RC1.

**Comment by tghosth** [comment]
Reopening this.

Following a discussion with Elar, I think we need to be moving secrets management to v14 as it is more of a config problem and not a cryptography problem.

**Comment by jmanico** [comment]
I think this is very reasonable.

**Comment by tghosth** [comment]
This is on my todo list but is waiting for #2376
