### ISSUE TITLE
split from 2.2.1 - disallow account lockout

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#2134]
Spin-off from https://github.com/OWASP/ASVS/issues/1763#issuecomment-2401626104

As current 2.2.1 requires work, and should have a clear anti-automation goal, it makes sense to separate the lockout part from this.

First question is - do we need this requirement? What NIST says about it? How it can fire back?

In practice - I have seen "enough times" solutions that via some web application authentication form you can lock out an entire organization or company user base with incorrect credentials.

Idea [proposal](https://github.com/OWASP/ASVS/issues/1763#issuecomment-2402435457) from @tghosth
> Verify that malicious users cannot lock out legitimate users and admins through excessive incorrect login attempts?

This serves to goal to explain the idea, but should be written as positive requirement.

**Comment by elarlang** [comment]
> What NIST says about it?

For my surprise, NIST kind of agrees to "no lockout" direction, but not requiring it. 

[3.2.2 Rate Limiting (Throttling) ](https://pages.nist.gov/800-63-4/sp800-63b.html#throttle)

> Additional techniques MAY be used to reduce the likelihood that an attacker will lock the legitimate claimant out due to rate limiting. These include:
> * Requiring the claimant to complete a bot-detection and mitigation challenge before attempting authentication
> * Requiring the claimant to wait after a failed attempt for a period of time that increases as the subscriber account approaches its maximum allowance for consecutive failed attempts (e.g., 30 seconds up to an hour)
> * Accepting only authentication requests from IP addresses from which the subscriber has been successfully authenticated before
> * Leveraging other risk-based or adaptive authentication techniques to identify user behavior that falls within or outside typical norms (e.g., the use of the claimant’s IP address, geolocation, timing of request patterns, or browser metadata)

**Comment by tghosth** [comment]
So do you still want a separate requirement here? if so, what is your proposed wording @elarlang ?

**Comment by tghosth** [comment]
Discussing with Elar:

Proposed update:

"_Verify that application documentation defines how controls such as rate limiting, anti-automation, and adaptive response, are used to defend against attacks such as credential stuffing and password brute force. The documentation should make clear how these controls are configured and prevent malicious account lockout._"

Opening a PR...
