### ISSUE TITLE
V1.11.3 and V11.1.6 - merge tactou requirements

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#2138]
Current requirements:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.11.3** | Verify that all high-value business logic flows, including authentication, session management and access control are thread safe and resistant to time-of-check and time-of-use race conditions. | | | ✓ | 367 |
| **11.1.6** | [MODIFIED] Verify that the application uses synchronization and locking mechanisms for sensitive operations in order to keep internal data consistent, maintain user state, and prevent race conditions, such as 'time of check to time of use (TOCTOU)' vulnerabilities. | | ✓ | ✓ | 367 |

If there is something unique in V1.11.3 that is not covered by V11.1.6, those should be merged into V11.1.6. Otherwise V1.11.3 should be deleted as duplicate of V11.1.6.

**Comment by elarlang** [comment]
ping @tghosth

**Comment by jmanico** [comment]
I agree with @elarlang that these should be merged into one. My suggestion to preserve all of these ideas:

_Verify that all high-value business logic flows, including authentication, session management, and access control, are thread-safe, resistant to time-of-check and time-of-use (TOCTOU) race conditions, and utilize synchronization and locking mechanisms for sensitive operations to maintain internal data consistency and user state._

**Comment by tghosth** [comment]
Minor modification:

> _Verify that all high-value business logic flows, **as well as** authentication, session management, and access control, are thread-safe, resistant to time-of-check and time-of-use (TOCTOU) race conditions, and utilize synchronization and locking mechanisms for sensitive operations to maintain internal data consistency and user state._

**Comment by tghosth** [comment]
I would say L2, maybe even L3.

**Comment by tghosth** [comment]
@elarlang thoughts?

**Comment by elarlang** [comment]
It carries the ideas from previous ones, L2 as it was (11.1.6) before. There is potential to be improved, but let's solve the merge problem here.
