### ISSUE TITLE
4.1.1 belongs in V4.2

### ISSUE THREAD

**Issue by EnigmaRosa** [OWASP/ASVS#2143]
4.1.1 addresses the implementation of the access control system:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **4.1.1** | [MODIFIED] Verify that the application enforces access control rules at a trusted service layer and doesn't rely on controls which an untrusted user could manipulate such as client-side JavaScript. | ✓ | ✓ | ✓ | 602 |

However, it is under section V4.1 - Access Control Design, which I believe is not the appropriate location. 

This may change depending on what we do with #2139

**Comment by elarlang** [comment]
This requirement belongs to access control design - if some one designed it to be on the not trusted service layer, such as client-side javascript code, it's an architecture issue.

**Comment by jmanico** [comment]
Agree with @elarlang here.

**Comment by EnigmaRosa** [comment]
Okay, I'm good with closing. Sorry
