### ISSUE TITLE
Consider Adding RASP for Runtime Attack Prevention

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#2144]
Runtime Application Self-Protection (RASP) is a security technology that is embedded into an application to detect and prevent real-time attacks by analyzing application behavior and context.

Do we need to add the following requirement to the ASVS?

* Verify that the application implements RASP techniques to detect and prevent runtime attacks, such as code injection or unexpected behavior modifications.

**Comment by jmanico** [comment]
I strongly vote no for this. I do not think we need to address specific tool categories for this need, but would rather us address the defense requirements if needed.

**Comment by elarlang** [comment]
I can not see it as "the one and only thing to use without your application is not secure" thing to require.

It makes sense to check, what are the principles the RASP covers and check, do we have matching requirements for each one of them.

**Comment by ImanSharaf** [comment]
We can close this if we are not into adding this one.

**Comment by elarlang** [comment]
It is a bit in style like "every application needs to use WAF", but it's not very informative. In the ASVS requirements we need to focus on the attack vectors that need to be mitigated, not on the abstract solutions without clearly understanding, why we need this solution.

If there is no intent to analyze the reasoning behind RASP, then yes, we can close this issue.
