### ISSUE TITLE
Is 1.4.4 a useful and verifiable requirement.

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#2147]
[1.4.4](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x10-V1-Architecture.md#v14-access-control-documentation):

> Verify the application uses a single and well-vetted access control mechanism for accessing protected data and resources. All requests must pass through this single mechanism to avoid copy and paste or insecure alternative paths.

Does this pass the "without this requirement, the app is insecure" test? In it's current form it feels closer to a design principle than a requirement as discussed in #1434

**Comment by elarlang** [comment]
For me it is material for a recommendation.

**Comment by jmanico** [comment]
I can actually think of reasons why an app would need different access control methods. So I agree this is a recommendation at best.

**Comment by elarlang** [comment]
So the proposal is to move it to recommendation.

**Comment by tghosth** [comment]
Opened #2163
