### ISSUE TITLE
18.6 does not make much sense for backend Web/REST services

### ISSUE THREAD

**Issue by eoftedal** [OWASP/ASVS#219]
Should we really advocate using session-based auth over other authentication mechanisms.

For Web Services using WS-Security with x509 is pretty common and it doesn't really match this requirement.

**Comment by kozmic** [comment]
+1
or using OAuth/OpenIDConnect, which is not session-based

**Comment by jmanico** [comment]
I agree. Would you care to make a exact change suggestion to this item? I'm happy to change it for version 3.1,

**Comment by jmanico** [comment]
18.6 is flat out wrong so I'm just deleting it. If you would like to suggest additional items for 18.x just add a new ticket with this suggestion and we'll get on it for 3.1

**Comment by jmanico** [comment]
The delete is co
