### ISSUE TITLE
V4 principles coverage

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#2195]
From issue to issue we discussions, is some "requirement" in the scope of ASVS or not.

First - please do not point to any section text as an "argument", as those are deprecated and just carried from v4.0.3.

And second, please get familiar with the agreed scope and expectations for requirements.

The goal of ASVS is not to educate developers, it is to provide verifiable security requirements. Many existing and proposed requirements do not match these criteria.

At the same time, I agree that it is good to get developer's attention to those principles - so I propose to cover it with a section in the paragraph.

Direction:

---

There are many principles to follow to make a good, maintainable, and secure authorization solution. Principles are an important way of thinking but are often too abstract for a verifiable security requirement in practice. From a security testing perspective, all principles are covered by technical security requirements, but when developing software or its architecture, the following principles should kept in mind:

  * Least privilege exists - todo: short explanation
  * Deny by default - todo: short explanation

**Comment by jmanico** [comment]
> The goal of ASVS is not to educate developers...

This is simply not true. The docs have stated for years that ASVS is for both security professionals and developers well before you joined the project and I ask you to stop asserting otherwise.

However, your wish to focus on verifiable requirements is reasonable and I support it.

**Comment by elarlang** [comment]
> This is simply not true. The docs have stated for years that ASVS is for both security professionals and developers well before you joined the project and I ask you to stop asserting otherwise.

Did I say it is not for developers or I said "The goal of ASVS is not to educate developers"? To make it more precise - the main goal for ASVS is to provide security verification requirements, investigating ASVS is educative by nature and comes as a side-effect.

> I ask you to stop asserting otherwise

In return, I ask you to read _precisely_ what I have said and not apply sentences to me what I did not say. The recommendation is not limited to this issue.

**Comment by jmanico** [comment]
That is fair. I may have misunderstood what you said and overall I agree with where you are coming from.

**Comment by jmanico** [comment]
This is being addressed in https://github.com/OWASP/ASVS/issues/2196 so I'm closing it out
