### ISSUE TITLE
Page 46 – Appendix C – May Want to Include the Actual MITRE Page Title 

### ISSUE THREAD

**Issue by defern** [OWASP/ASVS#22]
Page 46 – Appendix C – May Want to Include the Actual MITRE Page Title 

MITRE - Common Weakness Enumeration – Vulnerability Trends, http://cwe.mitre.org/documents/vuln-trends.html 

May want to remove the “,” and the actual page Title is “Vulnerability Type Distributions in CVE“

This and PCI Security Standards Council are the only ones that say why the site is useful

**Comment by vanderaj** [comment]
Resolved.
