### ISSUE TITLE
Is 8.3.7 duplicated in V6

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#2208]
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **[8.3.7](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x16-V8-Data-Protection.md#v83-sensitive-private-data)** | Verify that sensitive or private information that is required to be encrypted, is encrypted using approved algorithms that provide both confidentiality and integrity. | | ✓ | ✓ | 327 |

Seems like this might be duplicated in V6 but we need to wait and see what the updated V6 looks like first.

**Comment by elarlang** [comment]
I think we don't have any problem to solve here, as duplicates are in V6 that are not belonging there. It is duplicate of #1658.
