### ISSUE TITLE
Merge V11 (Http Security) and V19 Configuration?

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#221]
I think we have a great deal of overlap here, and a lot of the advice in V11 needs to be kept in sync with configuration. Could we best merge these two items into say V19? 

Thoughts @danielcuthbert @jmanico @eoftedal ?

**Comment by jmanico** [comment]
All of V11 was deprecated already in v3.. I'm confused!

**Comment by jmanico** [comment]
I think these can all be moved like so.

- 11.1 : Looks like an access control item
- 11.2: Looks like a general item for HTTP, not sure this fits into config. This is really to stop XSS so I suggest renaming v5 and putting it there.
- 11.3 Drop this or move to API v18 section
- 11.4 I would add this to the UI security section, v5
- 11.5: move to v9? data protection?
- 11.6: split this into two items, one for XSS issues and another for API's
- 11.7 + 11.8: These are again XSS issues, so rename v5 and move there?

**Comment by jmanico** [comment]
V11 is now gone and merged into V19. 940440b
