### ISSUE TITLE
V6 - Discuss forward secrecy

### ISSUE THREAD

**Issue by randomstuff** [OWASP/ASVS#2215]
Some requirement(s) should require the usage of forward secrecy whenever it makes sense.

see https://github.com/OWASP/ASVS/pull/2212#issuecomment-2451664978

Possible impact:

* Key exchange (ephemeral DH vs. RSA and static DH)
* mTLS client authentication using static client DH keypair (is it still relevant?)
* TLS session resumption (with TLS before 1.3)

**Comment by randomstuff** [comment]
>  Both RSA and DHE do support PFS 

Can you clarify (or provide reference) when you say that RSA supports PFS? Maybe we are not talking about the same thing?

**Comment by randomstuff** [comment]
Proposed generic requirement:

> 9.2.X Verify than for all communications using an encrypted protocols (TLS, SSH) the communication provides forward secrecy with respect to the long term private keys when communicating with modern clients. Non-forward secret communication might still be supported only for compatibility with old client which do not support it and if such compatibility is required.

This generic requirement could be specialized into more specific requirement about TLS (?). Proposed requirement about forward secrecy with respect to the client private key

> 9.4.X Verify than for all communications using TLS provides forward secrecy with respect to server private key when communicating with modern clients. Key exchanges such as RSA transport, static diffie-hellman, static ECDH (for TLS 1.2) must not be used.

Is 9.4.X with existing requirement such as 9.4.1? ("latest recommended cipher suites")

Some questions/comments:

* I would consider a requirement about forward secrecy with respect to the client private key in TLS (i.e. rsa_fixed_dh, dss_fixed_dh). I don't know if this has been used in practice and I don't believe this has been used much anyway.
* I'm not including requirements about forward secrecy with TLS PSK as this is quite niche (outside of TLS 1.3 session resumption).
* Before TLS 1.3 and when using TLS 1.3 with psk_ke, there is no forward secrecy with respect to the session secret. This might need to be mitigated. More generally, there are considerations wrt TLS sessions secrets which might need to be included.

**Comment by ImanSharaf** [comment]
Should we enforce the use of ephemeral key exchange methods, such as ephemeral Diffie-Hellman (DHE) or Elliptic Curve Diffie-Hellman (ECDHE)?
It can ensure that session keys are unique per session, preserving forward secrecy. In contrast, static key exchanges, like RSA or static Diffie-Hellman, do not provide forward secrecy and are therefore less secure.

**Comment by randomstuff** [comment]
@ImanSharaf, I think the requirement should focus on the goal which is to provide forward secrecy. In practice, this is typically achieved using DHE but could be achieved using other schemes (triple diffie hellman, some RSA based scheme, etc.).

**Comment by randomstuff** [comment]
See #2252

**Comment by tghosth** [comment]
@randomstuff what are the next steps on this issue?

**Comment by randomstuff** [comment]
Proposition:

> 9.2.X Verify that communications using in-transit encryption (for example using TLS, SSH, IPsec, QUIC), the encryption protocol provides forward secrecy. This can be achieved using an ephemeral Diffie-Hellman key exchange.

Somewhat more verbose (but possibly more precise) wording:

> 9.2.X Verify than for all communications using in-transit encryption (for example using TLS, SSH, IPsec, QUIC), the communication cannot be decrypted with any persistent secret (forward secrecy). This can be achieved using an ephemeral Diffie-Hellman key exchange.

Question: Any need for an exception for compatibility with old legacy external clients? ("[…] when communicating with up-to date clients […] Communication with external legacy clients which do not support forward secrecy can be used if such compatibility is required.")

Question: Add some hints about suitable TLS ciphersuites in appendix?

Question: Do we need to discuss about the impact of session resumption with respect to forward secrecy?

**Comment by tghosth** [comment]
My questions:

- Does offering TLS 1.3 mean that an app automatically complies with this requirement?
- If not, can the dev choose specific cipher suites to comply with this requirement?
- If not, what do they need to do?
- What does someone need to do if they also offer TLS 1.2?


> Question: Add some hints about suitable TLS ciphersuites in appendix?

Open to suggestions but that would be a separate issue on the appendix. I don't think it is critical.

> Question: Do we need to discuss about the impact of session resumption with respect to forward secrecy?

Does it alter the requirement?

**Comment by tghosth** [comment]
@randomstuff

**Comment by randomstuff** [comment]
> > Question: Do we need to discuss about the impact of session resumption with respect to forward secrecy?
> 
> Does it alter the requirement?

Short answer: It's complicated. I'd say we can include the requirement as is. Id needed, we can talk about session resumption in another issue.

Long answer below:

Possibly, somewhat.

Explanation: The secrets stored by the TLS server for session resumption can typically be used to break the encryption of the resumed TLS session. If these are persisted (and [replicated in order to allow the session to work on different instances of the TLS termination server](https://timtaubert.de/blog/2014/11/the-sad-state-of-server-side-tls-session-resumption-implementations/#:~:text=Session%20Resumption%20with%20multiple%20servers)), this may compromise forward secrecy.

See for reference : https://timtaubert.de/blog/2014/11/the-sad-state-of-server-side-tls-session-resumption-implementations/

Note: This is [fixed in TLS 1.3](https://timtaubert.de/blog/2017/02/the-future-of-session-resumption/) when if a Diffie-Hellman key exchange is done as part of the session resumption (`psk_dhe_ke`).

So for this proposed requirement:

> 9.2.X Verify than for all communications using in-transit encryption (for example using TLS, SSH, IPsec, QUIC), the communication cannot be decrypted with **any persistent secret** (forward secrecy). This can be achieved using an ephemeral Diffie-Hellman key exchange.

could be interpreted as implying that session secrets must be not persisted.

**Comment by tghosth** [comment]
Ok so how about my other questions @randomstuff :


* Does offering TLS 1.3 mean that an app automatically complies with this requirement?
* If not, can the dev choose specific cipher suites to comply with this requirement?
* If not, what do they need to do?
* What does someone need to do if they also offer TLS 1.2?

**Comment by randomstuff** [comment]
[Mozilla SSL server configuration](https://ssl-config.mozilla.org/) has three modes:

* modern → TLS 1.3 only, forward secret only
* intermediate → intermediate → support for TLS 1.2 with DHE and ECDHE only (foward secret ciphersuites only)
* old ("Compatible with a number of very old clients, and should be used only as a last resort")  → enables legacy ciphersuite which don't support forward secrecy.

So the question is. Can we require the usage of an "intermediate or higher" level (→ option  1)?

If I look at several servers:

* [https://www.google.com](https://www.ssllabs.com/ssltest/analyze.html?d=www.google.com&s=142.250.189.4&hideResults=on&ignoreMismatch=on) still allows legacy ciphersuites
* [https://github.com](https://www.ssllabs.com/ssltest/analyze.html?d=github.com&hideResults=on) still allows legacy  ciphersuites
* All apps I have configured recently follow the intermediate configuration and therefore only support forward secrecy. I have not had any recent complaints/brokeness about this.

**Comment by tghosth** [comment]
So I would suggest the following:

[9.4.1](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x17-V9-Communications.md#v94-general-tls-security-guidance)
_[MODIFIED, MOVED FROM 9.1.2] Verify that only the latest recommended cipher suites are enabled, with the strongest cipher suites set as preferred. For L3 applications, only cipher suites which support forward secrecy should supported._

**Comment by randomstuff** [comment]
> [MODIFIED, MOVED FROM 9.1.2] Verify that only the latest recommended cipher suites are enabled, with the strongest cipher suites set as preferred.

"latest recommended cipher suites are enabled" is somewhat vague but maybe that's the point.

Moreover, this wording seems to be (implicitly) about TLS ("ciphersuites") but we might want it to apply to other protocols as well.

> For L3 applications, only cipher suites which support forward secrecy should supported.

Is the "should" instead of "must" intentional here? Not that I am against saying "should" here.

I'd want to focus more on forward-secrecy as an explicit goal.

**Comment by tghosth** [comment]
> "latest recommended cipher suites are enabled" is somewhat vague but maybe that's the point.

Yes as this guidance changes.

> Moreover, this wording seems to be (implicitly) about TLS ("ciphersuites") but we might want it to apply to other protocols as well.

Seems like TLS is probably the vast majority of cases so I prefer to include it there.

> Is the "should" instead of "must" intentional here? Not that I am against saying "should" here.

Agree it should be a little clearer:

[9.4.1](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x17-V9-Communications.md#v94-general-tls-security-guidance)
_[MODIFIED, MOVED FROM 9.1.2] Verify that only the latest recommended cipher suites are enabled, with the strongest cipher suites set as preferred. L3 applications must only support cipher suites which provide forward secrecy._

**Comment by randomstuff** [comment]
> Seems like TLS is probably the vast majority of cases so I prefer to include it there.

Wouldn't it make sense to have (also) general requirement about this?

**Comment by randomstuff** [comment]
(Discussion)

The forward secrecy requirement could apply to these web-compatible flows as well (which are not completely niche):

- WebRTC /AV streams (which use SRTP)
- WebRTC data streams (which use **D**TLS)

More generally some of the transport security requirements might apply to WebRTC. There is not so much we can do about for browser-to-browser communications but for browser-to-server WebRTC, it might be relevant.

**Comment by tghosth** [comment]
> Wouldn't it make sense to have (also) general requirement about this?

In theory but I see the other examples as a lot more niche and I'd rather focus on the main relevant example.

For WebRTC, we have a guy who did those requirements so maybe open a separate issue and I will ping him :)

**Comment by tghosth** [comment]
opened #2439 to resolve
