### ISSUE TITLE
Proposal to Remove ASVS Requirement 10.3.1

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#2226]
This requirement primarily applies to desktop applications with auto-update features, which is outside the primary scope of ASVS. Its applicability to web applications is limited to niche cases, making it less relevant to ASVS's focus on broadly applicable security standards for web applications. Also, we have mentioned this here too: https://github.com/OWASP/ASVS/issues/663#issuecomment-955805650

**Comment by tghosth** [comment]
Requirement:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **[10.3.1](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x18-V10-Coding.md#v103-application-integrity)** | Verify that if the application has a client or server auto-update feature, updates should be obtained over secure channels and digitally signed. The update code must validate the digital signature of the update before installing or executing the update. | ✓ | ✓ | ✓ | 16 |

I think web apps can still have an auto update feature making this requirement still relevant.

@elarlang @ryarmst @danielcuthbert @tobias

**Comment by randomstuff** [comment]
Debian traditionally does *not* use (by default) a secure channel but only digital signatures and (AFAIU) some timestamps in the signature in order to limit denial of update attacks. Would such a scheme be OK?

Do we need to explicitly mention that any auto-updated plugins are also covered?

**Comment by randomstuff** [comment]
> I think web apps can still have an auto update feature making this requirement still relevant.

Yes, many PHP-based apps for example have auto-updates and plugin registries.

**Comment by randomstuff** [comment]
> Do we need to explicitly mention that any auto-updated plugins are also covered?

(Note: this might include applications which would download/update executable deep-learning models.)

**Comment by ImanSharaf** [comment]
Yesterday, we had a presentation where we discussed that we shouldn't target niche applications and write requirements for them. Also, machine learning models can be downloaded or updated, but they are not essentially executable code (out of scope for ASVS).

**Comment by tghosth** [comment]
@ryarmst what do you think about this?

**Comment by tghosth** [comment]
I don't think it is too niche and it is also a potentially dangerous piece of functionality, I would simplify it slightly to:

**Comment by ryarmst** [comment]
I would like to restate my opinion regarding secure channels with another example from V3 (section text):

> TLS or another secure transport channel is mandatory for session management. 

I feel like these are redundancies that appear littered throughout ASVS and are covered under [9.2.2](https://github.com/ryarmst/ASVS/blob/ryarmst-2102/5.0/en/0x17-V9-Communications.md#v92-general-service-to-service-communication-security).

**Comment by tghosth** [comment]
> I would like to restate my opinion regarding secure channels with another example from V3 (section text):
> 
> > TLS or another secure transport channel is mandatory for session management.
> 
> I feel like these are redundancies that appear littered throughout ASVS and are covered under [9.2.2](https://github.com/ryarmst/ASVS/blob/ryarmst-2102/5.0/en/0x17-V9-Communications.md#v92-general-service-to-service-communication-security).

Sold, opened a PR
