### ISSUE TITLE
proposal from #2212 -  V6.5 Secret Management

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#2232]
Current requirement:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **6.4.1** | [MODIFIED, MERGED FROM 2.10.4] Verify that a secrets management solution such as a key vault is used to securely create, store, control access to, and destroy back-end secrets, such as passwords, integrations with databases and third-party systems, seeds and internal secrets, and API keys. Secrets must not be included in source code or be received as CI/CD variables. For a L3 application, this should involved a hardware-backed solution such as an HSM. | | ✓ | ✓ | 798 |
| **6.4.2** | [MODIFIED] Verify that key material is not exposed to the application (neither the front-end nor the back-end) but instead uses an isolated security module like a vault for cryptographic operations. | | ✓ | ✓ | 320 |

Proposal in PR #2212

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **6.4.1** | A secrets management solution, such as a key vault, must be used to securely create, store, and control access to secrets (e.g., credentials, service accounts). |     |  ✓  |  ✓  | 798 |
| **6.4.2** | Key material must not be exposed to the application and should be stored and managed within an isolated security module.                                         |     |  ✓  |  ✓  | 320 |
| **6.4.3** | Verify that cryptographic keys and secrets be managed using approved key management systems with proper auditing and access controls.                |     |  ✓  |  ✓  | 320 |
| **6.4.4** | Verify that a function exists for the secure destruction of secrets, ensuring that secrets are irrecoverable when no longer needed.                              |     |  ✓  |  ✓  | 320 |

Nothing from the proposal is added yet - need to analyze, are those covered already or not.

**Comment by danielcuthbert** [comment]
I prefer #2212's offering here, 6.4.2 should be clarified better but overal this I feel offers more value than the current requirement.

**Comment by randomstuff** [comment]
> Key material must not be exposed to the application and should be stored and managed within an isolated security module.

Does/can this apply to crypto happening on the (web) client-side?

**Comment by tghosth** [comment]
This seems to have been handled so I am closing
