### ISSUE TITLE
2.1.4 has insufficient impact

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#2239]
| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.1.4** | Verify that any printable Unicode character, including language neutral characters such as spaces and Emojis are permitted in passwords. | ✓ | ✓ | ✓ | 521 | 5.1.1.2 |

Your application is not less secure without this, I recommend deleting.

@jmanico @elarlang @danielcuthbert @cronchie @ImanSharaf @ryarmst @TobiasAhnoff

**Comment by jmanico** [comment]
There are 95 printable ASCII characters. There are over 65,536 or so printable unicode characters. Unicode allows for much stronger passwords. But I agree it's not absolutely necessary for secure software.

**Comment by tghosth** [comment]
It is considered "SHOULD" in NIST's latest draft so I would prefer to remove:
https://pages.nist.gov/800-63-4/sp800-63b.html#passwordver

**Comment by danielcuthbert** [comment]
I'd support deleting this as yeah, impact is minimal
