### ISSUE TITLE
Do composition rules, rotation and history actively make your app insecure?

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#2240]
| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.1.9** | Verify that there are no password composition rules limiting the type of characters permitted. There should be no requirement for upper or lower case or numbers or special characters. | ✓ | ✓ | ✓ | 521 | 5.1.1.2 |
| **2.1.10** | [MODIFIED, SPLIT TO 2.1.13, LEVEL L1 > L2] Verify that the application does not require periodic credential rotation. | | ✓ | ✓ | | 5.1.1.2 |
| **2.1.13** | [ADDED, SPLIT FROM 2.1.10, LEVEL L1 > L2] Verify that the application does not keep a password history. | | ✓ | ✓ | | 5.1.1.2 |

These are kind of a negative requirements.
I am also not sure they actively make your app insecure.
Would it be better that we are just silent on composition rules and rotation?

My proposal is to delete as insufficient impact.

@jmanico @elarlang @danielcuthbert @cronchie @ImanSharaf @ryarmst @TobiasAhnoff

**Comment by tghosth** [comment]
Note that NIST considers these "SHOULD" not "SHALL/MUST" I don't think that is automatic grounds for deletion but...

**Comment by tghosth** [comment]
We have this text as well in 2.3 that could maybe be moved to 2.1 if we remove these:

Note: Passwords are not to have a maximum lifetime or be subject to password rotation. Passwords should be checked for being breached, not regularly replaced.

**Comment by ImanSharaf** [comment]
Strict rules can frustrate users, causing them to use one passwords across multiple platforms. Forcing users to change passwords regularly can lead to minor, predictable changes. Storing password history increases the amount of sensitive data that could be exposed in a breach. Omitting these points may lead organizations to assume that such practices are acceptable or even recommended.

**Comment by tghosth** [comment]
History doesn't seem to have any basis in NIST so I think I would take it out altogether:
https://github.com/OWASP/ASVS/commit/6298456976626a1853f296f5c892f78c3b5379ec#diff-0c2b5e7455e2813c723b067180f2b89432476e3fffc7e5d1e69b8da70e3efec4L92

**Comment by tghosth** [comment]
I don't see a way of making the composition requirement positive and I am not convinced it is essential
