### ISSUE TITLE
Proposal to delete 2.2.5 as duplicate

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#2241]
We talk about mutual TLS in [9.9.3](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x17-V9-Communications.md#v93-https-communication-between-internal-services). I don't think we need it separately in [2.2.5](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x11-V2-Authentication.md#v22-general-authenticator-security).

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **9.3.3** | [ADDED] Verify that mutual TLS (mTLS) is used by services communicating internally within a system or "intra-service communications" to ensure all the involved parties at each end of a network connection are who they claim to be. | | | ✓ | 295 |

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.2.5** | Verify that where a Credential Service Provider (CSP) and the application verifying authentication are separated, mutually authenticated TLS is in place between the two endpoints. | | | ✓ | 319 | 5.2.6 |

I propose considering 9.3.3 to be a moved and modified version of 2.2.5

**Comment by tghosth** [comment]
@jmanico @elarlang @danielcuthbert @cronchie @ImanSharaf @ryarmst @TobiasAhnoff

**Comment by jmanico** [comment]
Agree 2.2.5 should be deleted
