### ISSUE TITLE
V6 Cryptography - AES and ChaCha20

### ISSUE THREAD

**Issue by danielcuthbert** [OWASP/ASVS#2245]
V6.5 Cipher Algorithms

<img width="945" alt="Screenshot 2024-11-05 at 14 19 36" src="https://github.com/user-attachments/assets/7390e643-1a63-48d4-b585-ddcc71914af6">

**Comment by unprovable** [comment]
Yes, it probably should.

**Comment by unprovable** [comment]
https://github.com/Santandersecurityresearch/ASVS-Standard/commit/407ce190d6579efb2500025f11ea663f1ccafd00

**Comment by danielcuthbert** [comment]
Fixed with https://github.com/OWASP/ASVS/commit/856684d0e8f026234f2b0e7afc31b6c8d75ee84e
