### ISSUE TITLE
V6 Cryptography - GUIDS and UUIDS

### ISSUE THREAD

**Issue by danielcuthbert** [OWASP/ASVS#2248]
6.3.2 	[MODIFIED] Verify that GUIDs are created with an implementation of the GUID v4 algorithm which utilizes a cryptographically-secure pseudo-random number generator (CSPRNG). GUIDs created using other algorithm versions or using insufficiently secure pseudo-random number generators may be predictable.

<img width="946" alt="Screenshot 2024-11-05 at 14 20 02" src="https://github.com/user-attachments/assets/e990b026-1abe-4278-8862-30bff29e90cd">

**Comment by unprovable** [comment]
Should be V4 or V7 (not just v4).

**Comment by unprovable** [comment]
Also, going to remove excessive hyphens.

**Comment by unprovable** [comment]
https://github.com/Santandersecurityresearch/ASVS-Standard/commit/bc5d718ba50570200c5518c0f9dd1a5eb6d5ec42

**Comment by danielcuthbert** [comment]
Fixed with https://github.com/OWASP/ASVS/commit/856684d0e8f026234f2b0e7afc31b6c8d75ee84e
