### ISSUE TITLE
V6 Cryptography - /dev/urandom 

### ISSUE THREAD

**Issue by danielcuthbert** [OWASP/ASVS#2249]
<img width="935" alt="Screenshot 2024-11-05 at 14 20 10" src="https://github.com/user-attachments/assets/be92502e-eedd-4e4a-963b-2fa7c6dd2433">

Approved RNG Methods and Algorithms

**Comment by danielcuthbert** [comment]
I'm not 100% sure I'm happy with the recommendation of using getrandom() when even the GNU website states

> 
Most applications should use getentropy. The getrandom function is intended for low-level applications which need additional control over blocking behavior. 

My concern with both is that they can fail for a number of reasons. 

On /dev/urandom, I often consult the bible on this https://www.thomas-huehn.com/myths-about-urandom/ which now states that 

> 
Good news: the separation between /dev/urandom and /dev/random is practically gone. 

So I wonder if we just include /dev/random & /dev/urandom or just keep it as /dev/random?

**Comment by danielcuthbert** [comment]
I've added this into the new Appendix for cryptography

**Comment by randomstuff** [comment]
> I'm not 100% sure I'm happy with the recommendation of using getrandom() when even the GNU website states
> 
> > Most applications should use getentropy. The getrandom function is intended for low-level applications which need additional control over blocking behavior.

Well if `getentropy` calls `getrandom` this is till a usage of `getrandom` :) The same way that if you use `whateverlib_get_random()` which relies of `/dev/random` you are OK.

> My concern with both is that they can fail for a number of reasons.

Well [`getrandom`](https://man7.org/linux/man-pages/man2/getrandom.2.html), the Linux system call uses the same kernel mechanism as `/dev/random` and `/dev/urandom`. `getrandom` is a (relatively new](https://kernelnewbies.org/Linux_3.17#More_secure_generation_of_random_numbers_with_the_getrandom.28.29_syscall) (2014 :smile:) system call intended to be a [better/safer](https://lwn.net/Articles/606141/) alternative to using `/dev/[u]random`:

* it does not allocate file descriptors;
* it works even if a strict system call filter preventing any access to the file system is applied to the process;
* it works even if no `/dev/` is mounted in the chroot/file system namespace of the process.

**Comment by jmanico** [comment]
gerrandom() can be used in blocking mode (good for cryptograpic purposes) or non-blocking mode (not as safe).

Blocking: getrandom(buffer, sizeof(buffer), 0);
Non-Blocking: getrandom(buffer, sizeof(buffer), GRND_NONBLOCK);
