### ISSUE TITLE
1.4 - formulation to vague

### ISSUE THREAD

**Issue by tjherzog** [OWASP/ASVS#225]
"Data considered sensitive in the context of the application is clearly identified." is to vague. 
Why not just state: "The data protection requirements concerning confidentiality, integrity, authenticity and availability are identified." 
It's the basis for an informed assessment of the residual risks in case of implementaition errors.

**Comment by jmanico** [comment]
This issue does not seem to exist in 4.0. Can you please reopen and point to a specific file in https://github.com/OWASP/ASVS/tree/master/4.0/en if the issue still exists? Thank you.
