### ISSUE TITLE
V6 Cryptography - PQC

### ISSUE THREAD

**Issue by danielcuthbert** [OWASP/ASVS#2251]
<img width="934" alt="Screenshot 2024-11-05 at 14 20 24" src="https://github.com/user-attachments/assets/13a838d4-7c92-4907-9e7c-eb4a2e095d16">

6.9.1 	[ADDED] Verify that Quantum-Safe Algorithms, or quantum-resistant algorithms, such as lattice-based, hash-based, code-based, or multivariate cryptographic schemes, as replacements for vulnerable classical algorithms like RSA and ECC, are used. 		✓ 	✓ 	798
6.9.2 	[ADDED] Verify that cryptographic systems are designed to allow for seamless upgrades to post-quantum cryptography, enabling the transition once PQC standards are fully established. 		✓ 	✓ 	798
6.9.3 	[ADDED] Regularly monitor advancements in the field of post-quantum cryptography and align with emerging industry standards to remain prepared for quantum threats.

**Comment by danielcuthbert** [comment]
No, this should say use them if you want to be post-quantum secure. I'm not sure, at this stage, how we could amend the text to make that clearer. Should we specifically mention ML-KEM/ML-DSA or maybe even reference NSCS's piece https://www.ncsc.gov.uk/whitepaper/next-steps-preparing-for-post-quantum-cryptography?

**Comment by tghosth** [comment]
Opened a PR for this
