### ISSUE TITLE
V3 - 3.1.3 - Wording update to correspond to new definitions

### ISSUE THREAD

**Issue by ryarmst** [OWASP/ASVS#2253]
Based on recent changes to terminology (see #2100), I propose the following update. Emphasis added just to highlight change. 

Original:

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **3.1.3** | [MODIFIED, MOVED FROM 3.5.2, LEVEL L2 > L1] Verify that the application uses either **cryptographically signed** or **opaque tokens** for session management. Static API secrets and keys should be avoided. | ✓ | ✓ | ✓ | 798 | 7.1 |

Updated:

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **3.1.3** | [MODIFIED, MOVED FROM 3.5.2, LEVEL L2 > L1] Verify that the application uses either **cryptographically secured** or **random session tokens** for session management. Static API secrets and keys should be avoided.  | ✓ | ✓ | ✓ | 798 | 7.1 |

**Comment by elarlang** [comment]
ping @randomstuff

**Comment by randomstuff** [comment]
@jmanico:

>  Verify that the application uses cryptographically secured tokens for session management. Static API secrets and keys should be avoided.

I understand we are talking about session tracking and therefore it. We want to use random session tokens and avoid cryptographically secured tokens?

**Comment by ryarmst** [comment]
@jmanico Looking again at the present [Glossary](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x90-Appendix-A_Glossary.md), if we rely on the definitions of Cryptographically Secured Token and Random Session Token, I think it makes sense to reference both as acceptable options. Alternatively, we abandon the terminology and specific options for this requirement and instead state the security properties we hope to achieve (for example, tokens used should not be *guessable*).

**Comment by ryarmst** [comment]
@jmanico Regarding your last comment, I think this is probably preferable, but not necessary to achieve desired security properties nor common.

**Comment by randomstuff** [comment]
> Even if you use a random session id it should be in a abstraction like a reference token that is signed or mac'ed to session id tamper requests are not possible.

Is it really necessary to sign or MAC the random token? If so, do we explicitly have this requirement?

Is it enough to use a random token and only store a secure hash of the random token in database? One benefit is that we don't have to manage (rotate, encrypt, etc.) a secret to MAC/sign the token.

**Comment by ryarmst** [comment]
@randomstuff 
> Is it enough to use a random token and only store a secure hash of the random token in database?

I would guess this is the most common implementation in practice, no (perhaps not the "secure hash" part)? @jmanico I believe we have defined "random session token" to coincide with how "reference token" is broadly used - it is a random identifier that is mapped to a non-random user identifier server-side. While it may be preferable as a defense in depth mechanism to use an additional signature/MAC with a reference token, is it appropriate as a requirement? Is an update for terminology required?

The intent of this requirement is essentially to set the scope of allowable session token types (session tracking, as per @randomstuff). Further requirements specify the security features that should be required for different types of tokens, so that aspect can be ignored here. I might argue that "cryptographically secured" is inclusive of tokens that are not "self-encoded" but still signed/MAC'ed.

**Comment by ryarmst** [comment]
Discussed with @jmanico and am going to conclude with a PR for the original proposal.
