### ISSUE TITLE
JWT spec review how many things we have (not) covered

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#2261]
List of all security requirements from JWT spec with mapping what is covered and what is not.

**Comment by elarlang** [comment]
Tobias made the review, current summary, and idea from that is:
* most of the security considerations from JWT are V6 topics and should be covered there
* some requirements are general enough and overlap with the current "stateless token" chapter well
* not enough content to make a separate JWT section, and it would be unaligned with other technologies which rising a question - why there is no separate section for technology X

**Comment by TobiasAhnoff** [comment]
Suggestions on how to address this has been added in #1917 (and issues related to that), so I think this can be closed.
