### ISSUE TITLE
Suggestion to Include Service Mesh for Microservice Architectures in Requirement 9.3.3 on mTLS for Intra-Service Communications

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#2266]
Requirement 9.3.3 of ASVS currently states:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **9.3.3** | [ADDED] Verify that mutual TLS (mTLS) is used by services communicating internally within a system or "intra-service communications" to ensure all the involved parties at each end of a network connection are who they claim to be. | | | ✓ | 295 |

While this requirement is essential for securing internal communications, I believe it would be valuable to include a note or recommendation for users managing microservice architectures. In such architectures, managing mTLS certificates manually can be complex, time-consuming, and error-prone. For this reason, adopting a service mesh (such as Istio, Linkerd, or Consul) is often a more scalable and manageable approach for handling mTLS in dynamic microservice environments.

Include guidance or a recommendation in 9.3.3 suggesting that, in microservice architectures, using a service mesh could simplify mTLS management by automating certificate issuance, rotation, and revocation. This would also reduce the risk of configuration errors in a manually managed system, improving both security and operational efficiency.
@jmanico @tghosth @elarlang

**Comment by jmanico** [comment]
I am a big fan of this direction

**Comment by tghosth** [comment]
@ImanSharaf can you dig up the issue which led to this new requirement so we can see if there was a reason we specifically said mtls?

**Comment by tghosth** [comment]
So overall I don't think we should be prescriptive and say "you must use service mesh" but we can mention it is an option (as well as other options).

Do you want to prepare some suggested wording @ImanSharaf ?

**Comment by ImanSharaf** [comment]
@tghosth Do you like it?
_Verify that mutual TLS (mTLS) is used for intra-service communications, with the option of using a service mesh in microservice architectures to simplify certificate management and enhance security._

**Comment by randomstuff** [comment]
What about requiring "mutual node authentication based on public-key cryptography for example mTLS"?

For example, it might make sense in some contexts to internally use Oauth2.0 based flows with DPoP for intra-service communications instead of mTLS?

**Comment by tghosth** [comment]
@randomstuff how would you merge that into what Iman wrote?

**Comment by randomstuff** [comment]
Would something somewhat like this work?

> Verify that services communicating internally within a system or "intra-service communications" ensure that all the involved parties at each end of a network connection are who they claim to using strong authentication methods such as mTLS. For microservice architectures, consider the option of using a service mesh to simplify certificate management and enhance security.

By "strong authentication", what I mean here is:

* based on public-keys
* resistant to reaply attacks

i.e. mTLS or things like short-lived assertions bound to the target server (such as [DPoP proofs](https://datatracker.ietf.org/doc/html/rfc9449#name-dpop-proof-jwt-syntax)).

**Comment by tghosth** [comment]
> Would something somewhat like this work?
> 
> > Verify that services communicating internally within a system or "intra-service communications" ensure that all the involved parties at each end of a network connection are who they claim to using strong authentication methods such as mTLS. For microservice architectures, consider the option of using a service mesh to simplify certificate management and enhance security.
> 
> By "strong authentication", what I mean here is:
> 
>     * based on public-keys
> 
>     * resistant to reaply attacks
> 
> 
> i.e. mTLS or things like short-lived assertions bound to the target server (such as [DPoP proofs](https://datatracker.ietf.org/doc/html/rfc9449#name-dpop-proof-jwt-syntax)).

@ImanSharaf what do you think about this?

**Comment by jmanico** [comment]
My suggestion:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **9.3.3** | [MODIFIED, MOVED FROM 2.2.5] Verify that services communicating internally within a system (intra-service communications) use strong authentication to ensure that each endpoint is verified. Strong authentication methods, such as mTLS, should be employed to ensure identity, using public-key infrastructure and mechanisms that are resistant to replay attacks. For microservice architectures, consider using a service mesh to simplify certificate management and enhance security. | | | ✓ | 295 |

**Comment by ImanSharaf** [comment]
It works for me
