### ISSUE TITLE
Consider Signed Exchanges for Content Integrity

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#2267]
Signed Exchanges (SXG) help secure content by enabling cryptographic signing, ensuring that content served via third parties (e.g., CDNs) remains unaltered. This approach protects users from man-in-the-middle (MITM) attacks and guarantees they receive content exactly as intended by the origin server.

**Benefits:**

- Content Authenticity: Guarantees content is unmodified and from a trusted source.
- Improved Security: Reduces tampering risks during delivery.

**Implementation:**

- Enable SXG for cacheable content and static assets.
- Rotate cryptographic keys regularly and ensure SXG compatibility with third-party CDNs.

**Recommendation:** 
_Ensure Signed Exchanges (SXG) are implemented securely to maintain content integrity and authenticity during third-party delivery._

**Comment by danielcuthbert** [comment]
I love the idea in principle but would like to see how we tie this into V6 from a cryptographic perspective too

**Comment by tghosth** [comment]
Should this be another option in this requirement:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **[50.6.1](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x50-V50-Web-Frontend-Security.md#v506-external-resource-integrity)** | [MODIFIED, MOVED FROM 14.2.3] Verify that if client-side assets, such as JavaScript libraries, CSS or web fonts, are hosted externally on a Content Delivery Network (CDN) or external provider, Subresource Integrity (SRI) is used to validate the integrity of the asset. | ✓ | ✓ | ✓ | 829 |

**Comment by tghosth** [comment]
See discussion here:
https://twitter.com/dcuthbert/status/1854079241425502496

**Comment by ImanSharaf** [comment]
@jmanico What is your opinion?

**Comment by jmanico** [comment]
Signed exchanges only works in Chromium browsers.

https://caniuse.com/?search=Signed%20Exchanges

I'd suggest we just focus on SRI, which works in every browser.

https://caniuse.com/?search=sri

**Comment by ImanSharaf** [comment]
Then we can close it.
