### ISSUE TITLE
Remove 2.8.5 notification on multi-factor OTP

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#2268]
I think this is insufficient impact and should be deleted in NIST it is a MAY. 

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.8.5** | Verify that if a time-based multi-factor OTP token is re-used during the validity period, it is logged and rejected with secure notifications being sent to the holder of the device. | | ✓ | ✓ | 287 | 5.1.5.2 |

See:
https://pages.nist.gov/800-63-4/sp800-63b.html#multi-factor-otp-verifiers

**Comment by jmanico** [comment]
Agreed, Josh
