### ISSUE TITLE
clarify 11.2.1 and 11.2.2

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#2269]
@ImanSharaf suggests these are both the same and we need to clarify the difference more.

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **11.2.1** | [MOVED FROM 11.1.2] Verify that the application will only process business logic flows with all steps being processed in realistic human time, i.e. transactions are not submitted too quickly. | ✓ | ✓ | ✓ | 799 |
| **11.2.2** | [MODIFIED, MOVED FROM 11.1.4] Verify that the application has anti-automation controls to protect against excessive calls to application functionality which could result in mass data exfiltration, junk data creation, resource quota exhaustion, rate limit breaches, out-of-band communication flooding, denial of service, overuse of an expensive resource, etc. | ✓ | ✓ | ✓ | 770 |

**Comment by tghosth** [comment]
Please take a look at the previous discussion here:
https://github.com/OWASP/ASVS/issues?q=11.1.2+OR+11.1.4+

**Comment by elarlang** [comment]
11.2.1 - going through UI to fill big forms, defense is applied to the application

11.2.2 - automatically messing with API or services directly, dense most likely can be applied to WAF or network level

**Comment by ImanSharaf** [comment]
Nowadays, many people use form fillers, and we should allow them to do so. Additionally, by implementing the requirement in 11.2.2, 'Verify that the application has anti-automation controls,' 11.2.1 would also be covered. If 11.2.1 fails, then 11.2.2 should fail as well. Therefore, I believe we should merge these two requirements and remove 11.2.1.

**Comment by tghosth** [comment]
@danielcuthbert @cronchie @ryarmst @TobiasAhnoff @randomstuff can we get more opinions on this please

**Comment by randomstuff** [comment]
Yes agree with @ImanSharaf on this. I would remove 11.2.1.

> [MODIFIED, MOVED FROM 11.1.4] Verify that the application has anti-automation controls to protect against excessive calls to application functionality which could result in mass data exfiltration, junk data creation, resource quota exhaustion, rate limit breaches, out-of-band communication flooding, denial of service, overuse of an expensive resource, etc.

Nitpick/musing: I agree with the content of the requirement but I am conflicted on the term "anti-automation" here. There are legitimate cases for automation by legitimate users.

**Comment by cronchie** [comment]
11.2.1 is trying to require **throttling**, but does not word it as such. I recommend rephrasing to call out the concept explicitly. How about:

`Verify that throttling is assessed and implemented where needed, especially for business logic flows that may be susceptible to high-frequency submissions or that interact with rate-limited resources, ensuring transactions are processed at realistic human speeds.`

And then 11.2.2 can focus on the separate concept of setting a rate limit per-operation, like:

`Verify that each operation has a defined rate limit and an explicit designation for whether it should be automatable, with limits tailored to prevent excessive calls that could result in data exfiltration, junk data creation, resource exhaustion, rate limit breaches, denial of service, or overuse of high-cost resources.`

@randomstuff @ImanSharaf

**Comment by randomstuff** [comment]
@cronchie, Reading your comment, I'm not very clear about:

* throttling vs rate limiting.
* your first proposed requirement and the second one

All in all, I am not sure I know what to propose here.

> junk data

"junk" seems quite familiar. Maybe "garbage data"?

**Comment by jmanico** [comment]
I agree to keep both, here is a minor cleanup.

# | Description | L1 | L2 | L3 | CWE
-- | -- | -- | -- | -- | --
11.2.1 | Verify that business logic processes require realistic human timing, preventing excessively rapid transaction submissions. | ✓ | ✓ | ✓ | 799
11.2.2 | Verify that anti-automation controls are in place to protect against excessive calls to application functions that could lead to data exfiltration, junk data creation, quota exhaustion, rate limit breaches, denial of service, or overuse of costly resources. | ✓ | ✓ | ✓ | 770
