### ISSUE TITLE
Usable security as a architectural requirement?

### ISSUE THREAD

**Issue by tjherzog** [OWASP/ASVS#227]
The main enemy of security is to (not only) my opinion is poor usability. This should also be condidered in the design of an application.

**Comment by vanderaj** [comment]
This is being incorporated into V2. Are you asking for it to be in V1 Architecture as well?

**Comment by jmanico** [comment]
Please reopen with more specific enhancement suggestions. We like your idea - but just need more specific suggestions to act on it.
