### ISSUE TITLE
V3 Move 3.8.2 to 3.7.2

### ISSUE THREAD

**Issue by ryarmst** [OWASP/ASVS#2271]
In combination with proposed changes to V3.7 (see #2270), this proposal is to move 3.8.3 to 3.7.2 as this requirement is best understood as a mechanism to allow users to defend themselves from hijacked active sessions. 

For reference:

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **3.8.3** | [MODIFIED, MOVED FROM 3.3.4] Verify that users are able to view and (having re-entered login credentials) terminate any or all currently active sessions. | | ✓ | ✓ | 613 | 7.1 |

**Comment by elarlang** [comment]
I proposed it, but at the same time it's not a clear call:
* from session termination point of view it belongs to V3.8
* from calling account sensitive action point of view it belongs to V3.7

ping @tghosth - as you reorganized this part previously.

**Comment by tghosth** [comment]
https://github.com/OWASP/ASVS/issues/2270#issuecomment-2458963006

**Comment by ryarmst** [comment]
In combination with #2270, PR coming.

**Comment by ryarmst** [comment]
@tghosth please see #2304
