### ISSUE TITLE
V3 Update 3.2.2 and consider moving to V3.1

### ISSUE THREAD

**Issue by ryarmst** [OWASP/ASVS#2273]
Proposal (ping @jmanico):

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **3.2.2** | [MODIFIED, MERGED FROM 3.2.4] Verify that if random tokens are used to represent user sessions, they are unique and generated using a cryptographically secure pseudo-random number generator (CSPRNG) and possess at least 128 bits of entropy. | ✓ | ✓ | ✓ | | |

I think it will also make sense to move up into V3.1.

**Comment by randomstuff** [comment]
See discussion from https://github.com/OWASP/ASVS/issues/2253#issuecomment-2458046371

> > Even if you use a random session id it should be in a abstraction like a reference token that is signed or mac'ed to session id tamper requests are not possible.
>
> Is it really necessary to sign or MAC the random token? If so, do we explicitly have this requirement?
> 
> Is it enough to use a random token and only store a secure hash of the random token in database? One benefit is that we don't have to manage (rotate, encrypt, etc.) a secret to MAC/sign the token.

**Comment by jmanico** [comment]
This is an option, it's called a "reference token" with a signature so session id tampering is not possible. It greatly reduces the likelihood of session hijacking.

**Comment by ryarmst** [comment]
I think this requirement should apply strictly to random tokens that are used to track user sessions as this is a common pattern.

**Comment by ryarmst** [comment]
See resolution to #2253 regarding discussion above. Going to propose with PR.

**Comment by ryarmst** [comment]
@tghosth please see #2301 and help ensure tags are correct.

**Comment by tghosth** [comment]
@ryarmst please submit another PR which updates the tag on 3.2.4 as it has now been merged to 3.1.4, not 3.2.2

**Comment by jmanico** [comment]
I merged this, I'll hold off and let you and Elar merge most.

**Comment by ryarmst** [comment]
@tghosth see #2303
