### ISSUE TITLE
2.2 - The intention of the last sentence is not clear to me.

### ISSUE THREAD

**Issue by tjherzog** [OWASP/ASVS#228]
Maybe it is only because i am not a natove speaker:-), but I havn't got the  clue from "Random time limited nonces are acceptable as stand ins, such as to protect change password forms or forgot password forms."

**Comment by m8urnett** [comment]
I think that a more concise way to word this might be:

_Verify that the application never automatically fills in or saves a user's plaintext credentials–either as hidden or visible form fields, query parameters, cookie values, or HTTP headers._ 

I don't think it is necessary to explain why (this isn't done with other items) and I don't think it's really necessary to say that cryptographic nonces are allowed.
