### ISSUE TITLE
V4 Move 4.1.5 to V7.4 as "Fail Open" prevention

### ISSUE THREAD

**Issue by ryarmst** [OWASP/ASVS#2282]
The current 4.1.5 is about preventing fail open conditions, which are more broad than access control issues alone:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **4.1.5** | [GRAMMAR] Verify that access controls fail securely by denying access, including when an exception occurs. | ✓ | ✓ | ✓ | 285 |

Suggestion: move to V7.4 and generalize. Proposed:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **7.4.5** | [GRAMMAR] Verify that the application fails gracefully and securely, including when an exception occurs, preventing fail open conditions.

Question: does this conflict with existing V7.4 requirements like 7.4.3? @cronchie 

OR consider merging to 7.4.3 (though I think this may require some additional refinement):

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **7.4.3** | Verify that a "last resort" error handler is defined which will catch all unhandled exceptions prior to the execution of business logic, preventing fail open conditions. | | ✓ | ✓ | 431 |

**Comment by jmanico** [comment]
I think this is a good call. cc @elarlang @tghosth

**Comment by tghosth** [comment]
If we don't have another fail secure requirement then I think this makes sense

**Comment by cronchie** [comment]
Ship it!

**Comment by ryarmst** [comment]
@tghosth #2294
