### ISSUE TITLE
Add Support for Post-Quantum Cryptography Algorithm Agility

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#2293]
Currently, most applications lacks the necessary flexibility to efficiently upgrade or replace cryptographic algorithms in response to emerging quantum computing threats. 

Proposed requirement:
_Verify that the cryptographic architecture supports algorithm agility, allowing for rapid switching or upgrading of cryptographic algorithms in response to advancements in PQC._

**Comment by jmanico** [comment]
I suggest:

_Verify that the cryptographic architecture supports cryptographic agility, allowing for rapid switching or upgrading of cryptographic algorithms and keys as well as re-encrypting or resigning data in response to advancements in post-quantum computing._

**Comment by danielcuthbert** [comment]
We have this already:

6.9 Post-Quantum Cryptography (PQC)

The need to future-proof cryptographic systems in preparation for the eventual rise of quantum computing is critical. Post-Quantum Cryptography (PQC) focuses on developing cryptographic systems that are resistant to quantum attacks, which could break current encryption methods such as RSA and ECC.

# | Description | L1 | L2 | L3 | CWE
-- | -- | -- | -- | -- | --
6.9.1 | [ADDED] Verify that Quantum-Safe Algorithms, or  quantum-resistant algorithms, such as lattice-based, hash-based,  code-based, or multivariate cryptographic schemes, as replacements for  vulnerable classical algorithms like RSA and ECC, are used. |   | ✓ | ✓ | 798
6.9.2 | [ADDED] Verify that cryptographic systems are designed  to allow for seamless upgrades to post-quantum cryptography, enabling  the transition once PQC standards are fully established. |   | ✓ | ✓ | 798
6.9.3 | [ADDED] Regularly monitor advancements in the field of  post-quantum cryptography and align with emerging industry standards to  remain prepared for quantum threats. |   | ✓ | ✓ | 798

I'm toying with the idea of specifying the algorithms directly, such as 

Verify that Quantum-Safe Algorithms like lattice-based cryptosystems (e.g., ML-KEM), hash-based cryptosystems (e.g., Kyber)......

but it is in V6 already so do we need the additional crypto agility one or could we use 6.9.2 with some tweaks or does that work as it is?

**Comment by ImanSharaf** [comment]
I am pro specifying the algorithms directly. What do you think about suggesting to have hybrid cryptographic solutions by combining classical algorithms with quantum-resistant algorithms to ensure security during the transition period to full PQC adoption?

**Comment by JaimeGomezGarciaSan** [comment]
Until recently nobody dared to create a concrete definition of crypto-agility, AFAIK. Some weeks ago, the FSISAC PQC WG published[ a paper on the topic](https://www.fsisac.com/pqc-crypto-agility). We had a lengthy discussion to break the trend of talking about crypto-agility without defining it. I would suggest to back that definition by reusing it.

The definition is:
"Cryptographic Agility is a measure of an organization’s ability to adapt cryptographic solutions or algorithms (including their 
parameters and keys) quickly and efficiently in response to developments in cryptanalysis, emerging threats, technological 
advances, and/or vulnerabilities. 
It is also a design principle for implementing, updating, replacing, running, and adapting cryptography and related business processes and policies with no significant architectural changes, minimal disruption to business operations, and short transition time."

It took us a long time a lengthy discussions to agree on that definition. And I think it is good, with a nice mix of tech detail and business needs.

I also like the way this discussion is addressed in [DORA](https://www.esma.europa.eu/sites/default/files/2024-01/JC_2023_86_-_Final_report_on_draft_RTS_on_ICT_Risk_Management_Framework_and_on_simplified_ICT_Risk_Management_Framework.pdf). Art.7.3:
"Financial entities shall include in the policy on encryption and cryptographic controls
criteria to select cryptographic techniques and use practices taking into account leading
practices and standards, as defined in Article 2, point (1), of Regulation (EU) No 1025/2012,
and the classification of relevant ICT assets established according to Article 8(1) of Regulation
(EU) 2022/2554. Where the financial entity cannot adhere to the leading practices or use the
most reliable techniques, it shall adopt mitigation and monitoring measures to ensure resiliency
against cyber threats."
Art.7.4:
"Financial entities shall include in the policy on encryption and cryptographic controls
provisions to, where necessary, on the basis of developments in cryptanalysis, update or change
the cryptographic technology to ensure they remain resilient against cyber threats and
considering the information resources referred to in Article 10(2), point (a). Where the financial
entity cannot update or change the cryptographic technology, it shall adopt mitigation and
monitoring measures to ensure they remain resilient against cyber threats."

I like to avoid mentioning the word quantum too much when discussing the need for crypto-agility and to use modern standards. Eventually, one day we will not speak about PQC, but about current standards. And there may be different threats to algorithms that are not only quantum. So, I love the way DORA and FSISAC make it general.

So, I would suggest these articles or something similar:

- "Verify that cryptographic techniques and use practices take into account leading practices and standards, considering the  forseeable challenges they may face during the lifespan of their use cases, in particular the threat posed by quantum computers"
- "Verify that  cryptographic techniques and use practices can adapt quickly and efficiently in response to developments in cryptanalysis, emerging threats, technological advances, and/or vulnerabilities."
- "Verify that the cryptographic designs put a focus on implementing, updating, replacing, running, and adapting cryptography and related business processes and policies with no significant architectural changes, minimal disruption to business operations, and short transition time."

**Comment by ImanSharaf** [comment]
@tghosth

**Comment by tghosth** [comment]
> I am pro specifying the algorithms directly. What do you think about suggesting to have hybrid cryptographic solutions by combining classical algorithms with quantum-resistant algorithms to ensure security during the transition period to full PQC adoption?

Want to add something to 6.2.4 on this hybrid topic but waiting for #2306 to be merged.

**Comment by tghosth** [comment]
> > I am pro specifying the algorithms directly. What do you think about suggesting to have hybrid cryptographic solutions by combining classical algorithms with quantum-resistant algorithms to ensure security during the transition period to full PQC adoption?
> 
> Want to add something to 6.2.4 on this hybrid topic but waiting for #2306 to be merged.

I had another look at this and I think I would rather not get prescriptive to this level
