### ISSUE TITLE
V6 Verify that (TLS) certificates are validated

### ISSUE THREAD

**Issue by randomstuff** [OWASP/ASVS#2309]
I don't think there is a requirement which explicitly says that TLS certificates (and more generally any public-keys) are verified, not disabled.

We have these requirements on this topic:

> 9.1.4 [ADDED] Verify that external facing services use publically trusted TLS certificates.
>
> 9.3.2 [MODIFIED, MOVED FROM 9.2.1] Verify that TLS connections between internal services use trusted certificates. Where internally generated or self-signed certificates are used, the consuming service must be configured to only trust specific internal CAs and specific self-signed certificates. All others should be rejected.

Something like:

> Verify that the TLS client validates that the server public key is valid for the target TLS server before finalizing the TLS handshake. TLS server certificate verification must not be disabled by code or by configuration unless some other verification mechanism is implemented.
>
> Verify that, when TLS client authentication is used, the application verifies that the public key is valid for the user identity. If this verification is disabled at the TLS termination point, the required information must be propagated to the application which must do the verification.

Context (and things I am trying to prevent here):

* In my experience there is a saddeningly high prevalence of "TLS validation fails? Let's just disable TLS validation in code (as recommended in some random StackOverflow answer".
* Another thing I've seen too many times is « ssl_verify_client optional_no_ca; » where the application just blindly trusts the client identity (issuer) found in the certificate. (This is NOT safe at all as you can just self-sign your own certificate to assume any identity you wish).

Some additional considerations:

* This could apply to other uses of certificates.
* In some cases ([OAuth mTLS-bound access tokens](https://www.rfc-editor.org/rfc/rfc8705.html)), it is actually OK (and the intended usage) to use self-signed client certificates (but there is some additional mechanism which makes it possible to verify the binding of the certificate TLS public key in the intended usage context). The formulation of the requirements should allow this kind of usage.

**Comment by tghosth** [comment]
> Something like:
> 
> > Verify that the TLS client validates that the server public key is valid for the target TLS server before finalizing the TLS handshake. TLS server certificate verification must not be disabled by code or by configuration unless some other verification mechanism is implemented.
> > Verify that, when TLS client authentication is used, the application verifies that the public key is valid for the user identity. If this verification is disabled at the TLS termination point, the required information must be propagated to the application which must do the verification.

I agree but I'd like to keep it very simple, something like:

> Verify that TLS clients validate certificates received before communicating with a TLS server.

What do you think @randomstuff ?

**Comment by tghosth** [comment]
If you agree, open a PR @randomstuff

**Comment by randomstuff** [comment]
OK will do.

**Comment by ryarmst** [comment]
Yoink. @tghosth @randomstuff please see #2357. Dropped in V9.2.

**Comment by randomstuff** [comment]
Good to me but I think we would need a second requirement for the other direction mTLS (but it should be slightly different). Something like:

> Verify that TLS servers validate certificates received from TLS clients (mTLS) before relying of them for client authentication.

**Comment by tghosth** [comment]
Please open a

**Comment by ryarmst** [comment]
Is the application responsible for cert validation when using mTLS?

**Comment by randomstuff** [comment]
… and this is one reason why the wording:

 > Verify that TLS servers validate certificates received before communicating with a TLS client.

may not always be completely accurate.

It is OK (and somewhat usual) for the TLS server to accept communicating with a client using an invalid TLS certificate if the server rejects the (application layer/) HTTP request (or possibly ignore the client identity when processing the HTTP request).

***

Moreover when using DPoP, it is OK for the authorization server or the resource server to accept any self-signed certificate but only use the associated public-key for:

* binding the client public key to the issued access token (AS);
* verifying the binding between the client public key and the received access token (RS).

**Comment by tghosth** [comment]
So what is the proposal here @randomstuff

**Comment by randomstuff** [comment]
What about:

> Verify that TLS servers validate that mTLS client certificates are trusted before using the certificate identity for authentication or authorization.

or maybe

> Verify that the application validates that mTLS client certificates are trusted before using the certificate identity for authentication or authorization.

**Comment by jmanico** [comment]
I like the second

**Comment by tghosth** [comment]
Can we not just add a note about validation to 9.3.3 @randomstuff?

**Comment by randomstuff** [comment]
@tghosth, 9.3.3 is about  services communicating internally within a system. This proposed requirement would apply to external services or even for authenticating end-users. I would think these are different in scope.

**Comment by tghosth** [comment]
> @tghosth, 9.3.3 is about services communicating internally within a system. This proposed requirement would apply to external services or even for authenticating end-users. I would think these are different in scope.

Ok I think that is a fair point, so how does this fit into V9? I am also open to suggestions for restructuring V9. @randomstuff

**Comment by randomstuff** [comment]
Validation of server certificate trust:

> 9.2.6 [ADDED] Verify that TLS clients validate certificates received before communicating with a TLS server.

is currently in 9.2  (General Service to Service Communication Security). This is probably OK. Would it make sense to move it into 9.4 (General TLS Security Guidance)?

***

Validation of client certificate trust:

> Verify that the application validates that mTLS client certificates are trusted before using the certificate identity for authentication or authorization.

This could go into into 9.4 (General TLS Security Guidance)? It might go into V2 Authentication as well but this would be weird (it can apply to user authentication but is often going to be more about client/service authentication).

***

>  I am also open to suggestions for restructuring V9

This would probably be the topic of another issue but some considerations:

* some requirement could be generalized to other secure protocols (eg. in my field SSH/SFTP is sometimes used for data transfer between systems) and the client/server identity validation apply equally there;
* a "general secure communication recommendations" section, might be useful for discussing for example forward secrecy.

**Comment by tghosth** [comment]
> Validation of server certificate trust:
> 
> > 9.2.6 [ADDED] Verify that TLS clients validate certificates received before communicating with a TLS server.
> 
> is currently in 9.2 (General Service to Service Communication Security). This is probably OK. Would it make sense to move it into 9.4 (General TLS Security Guidance)?

Sure

---

> Validation of client certificate trust:
> 
> > Verify that the application validates that mTLS client certificates are trusted before using the certificate identity for authentication or authorization.
> 
> This could go into into 9.4 (General TLS Security Guidance)? It might go into V2 Authentication as well but this would be weird (it can apply to user authentication but is often going to be more about client/service authentication).

I think this makes sense

---

> > I am also open to suggestions for restructuring V9
> 
> This would probably be the topic of another issue but some considerations:
> 
>     * some requirement could be generalized to other secure protocols (eg. in my field SSH/SFTP is sometimes used for data transfer between systems) and the client/server identity validation apply equally there;
> 
>     * a "general secure communication recommendations" section, might be useful for discussing for example forward secrecy.

If you have some straightforward suggested moves then I am comfortable with that. Otherwise, please just open a PR with the simple changes discussed here.
