### ISSUE TITLE
2.17 - add "temporary" 

### ISSUE THREAD

**Issue by tjherzog** [OWASP/ASVS#231]
i.e. "A temporary one time password reset link should be used instead."

A further suggestion: For high protection requirements  (e.g. online banking) the one time password should be transported via an independent sidechannel (e.g. SMS).

**Comment by vanderaj** [comment]
"Verify memorized secret credential recovery, does not reveal the current memorized secret and that a system generated new memorized secret is not sent in clear text to the user. Lookup codes or a random, time limited one time reset link should be used instead."
