### ISSUE TITLE
Generalize 9.4.4 (about certificate in productions vs non-production environments)

### ISSUE THREAD

**Issue by randomstuff** [OWASP/ASVS#2312]
Currently 9.4.4 is:

> 9.4.4 	[ADDED] Verify that if TLS wildcard certificates are used, wildcard certificates from a non-production environment are not valid for a production environment.

This actually applies for non-wildcard certificates as well (certificate with multiple SANS 'www.example.com' and 'preproduction.example.com').

Proposition:

>  9.4.4 	Verify that TLS server certificates from a non-production environment are not valid for a production environment (for example when using wildcard certificates).

**Comment by jmanico** [comment]
We typically do not want to deal with requirements that deal with dev vs production and I'd like to close this out. Please re-open if you think otherwise,

**Comment by randomstuff** [comment]
@jmanico, it would make sense to remove 9.4.4 then.

**Comment by jmanico** [comment]
Noted. Issue re-opened

**Comment by tghosth** [comment]
Yeah that is a good point, this requirement was brought in in: https://github.com/OWASP/ASVS/pull/1223/files

I actually agree removing this.

What do you think?

@jmanico @elarlang @danielcuthbert @cronchie @ImanSharaf @ryarmst @TobiasAhnoff @randomstuff

**Comment by ImanSharaf** [comment]
I agree removing this too. We can bring more examples, such as dev and prod API keys.

**Comment by cronchie** [comment]
On the one hand, I agree that distinguishing prod vs non-prod is more of a process thing and thus out of scope.
On the other hand, if it were rephrased to:

`Verify that TLS server certificates are only valid for one environment (subdomain perhaps?)`

I could see it staying in here. Though, that might be overly prescriptive and then also out of scope. I don't feel strongly about this either way though!

**Comment by ryarmst** [comment]
Agree with removal.
