### ISSUE TITLE
Add requirement about using different secrets/keys in production and preproduction environment

### ISSUE THREAD

**Issue by randomstuff** [OWASP/ASVS#2313]
Should we add requirements about using different secrets/keys in production and preproduction environments (and, in some cases, in different production environments):

* TLS private keys in production environments should not be found in the preproduction environments (see #2312).
* If a secret is used to protect (MAC/sign) tokens (such as session tokens) it must not be the same in production and preproduction environments (for the record, I have already seen this one in the wild).

**Comment by elarlang** [comment]
I consider this to be out of scope. It requires to have access to both requirements and it's more about process.

**Comment by elarlang** [comment]
Discussed with Josh and we consider this as a deployment issue and out of scope.
