### ISSUE TITLE
Expand the Cryptography Appendix for MAC, signatures, key derivation functions

### ISSUE THREAD

**Issue by randomstuff** [OWASP/ASVS#2314]
The [crypto appendix](https://github.com/OWASP/ASVS/pull/2306/files) currently provides guidance around suitable algorithms for:

* ciphers
* random generation
* symmetric ciphers
* key wrapping
* key exchange and DH groups
* secure hash functions
* password hashing

The following things are not covered:

* MAC
* digital signatures
* key derivation functions

Should this appendix be expanded to cover these (and relevant requirements be included as well)?

**Comment by danielcuthbert** [comment]
Morning, spent last night adding this into a patch https://github.com/OWASP/ASVS/blob/dc_v6_patch3/5.0/en/0x97-Appendix-V_Cryptography.md

Does this match what you had in mind @randomstuff

**Comment by randomstuff** [comment]
In the KDF, we might want to add the [PRF](https://datatracker.ietf.org/doc/html/rfc5246#section-5) used in TLS 1.2 (for compatibility with TLS 1.2).

**Comment by danielcuthbert** [comment]
added in https://github.com/OWASP/ASVS/pull/2371
