### ISSUE TITLE
V3 - Update section text for V3.6 and/or corresponding security decision

### ISSUE THREAD

**Issue by ryarmst** [OWASP/ASVS#2321]
See #1190. Previous note to consider for section text update: 

> For an updated reference, consider the second public draft of [NIST 800-63C-4](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63C-4.2pd.pdf).

**Comment by tghosth** [comment]
Hi @ryarmst, what is the current action here?

**Comment by ryarmst** [comment]
Since #2442 is now open and V1 content has been merged with V3, I think it makes sense to close this issue and continue there.
