### ISSUE TITLE
Do we still want to include regulatory requirements in V8.3?

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#2330]
We currently have the following requirements which relate to regulatory requirements rather than specific security requirements.

We previously discussed his in #1918 where the concensus was to make many of these level 3 to reflect the fact that they are not really security requirements.

However, now that we have clarified the ASVS scope, my proposal is to move these to the recommendations section as I am not sure they pass the test of "your application is insecure without these requirements".

What do other people think?

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **8.3.2** | [MODIFIED, SPLIT TO 8.3.9, LEVEL L1 > L3] Verify that users have a method to remove their data on demand. | | | ✓ | |
| **8.3.3** | [MODIFIED, LEVEL L1 > L3] Verify that the application provides guidance regarding how it collects and uses of personal data and that users have to provide opt-in consent for this use. | | | ✓ | |
| **8.3.8** | Verify that sensitive personal information is subject to data retention classification, such that old or out of date data is deleted automatically, on a schedule, or as the situation requires. | | ✓ | ✓ | |
| **8.3.9** | [ADDED, SPLIT FROM 8.3.2] Verify that users have a method to export their data on demand. | | | ✓ | |
| **8.3.10** | [ADDED] Verify that sensitive information is removed from the metadata of user-submitted files unless storage is consented to by the user. | ✓ | ✓ | ✓ | 212 |
| **8.3.11** | [MODIFIED, MOVED FROM 10.2.2, LEVEL L2 > L1] Verify that the application does not ask for unnecessary or excessive permissions to privacy related features or sensors, such as cameras, microphones, or location. | ✓ | ✓ | ✓ | 272 |

@jmanico @elarlang @danielcuthbert @cronchie @ImanSharaf @ryarmst @TobiasAhnoff @randomstuff

**Comment by cronchie** [comment]
I think we can merge a lot of these into requiring:
- a data retention lifecycle, which implicitly covers some of these requirements like exporting and removing data.
- a data classification process, which is arguably more of a process question and should belong in SAMM instead

**Comment by ryarmst** [comment]
I am fine with purging regulatory requirements, especially as these could vary significantly jurisdiction, industry, and so on.

**Comment by randomstuff** [comment]
I'm quite OK with removing most of them but maybe 8.3.11 should be kept? Is it not a security requirement? (cf. `Permissions-Policy`)

**Comment by tghosth** [comment]
> ...maybe 8.3.11 should be kept? Is it not a security requirement? (cf. `Permissions-Policy`)

I don't see it is as a security vulnerability, if the app intentionally asks for extra permissions then that is just how it works. What it asks for is a design and privacy question.

**Comment by randomstuff** [comment]
I don't know, I'm arguing a bit but don't have a strong opinion on this.

**Comment by elarlang** [comment]
> V8.3.2 Verify that users have a method to remove their data on demand.

Out.

Pure policy.

---

> V8.3.3 Verify that the application provides guidance regarding how it collects and uses of personal data and that users have to provide opt-in consent for this use.

Out.

Just providing guidance is policy. Do not collect more information about the user than it is required by the application is a thing and subject to analyzis. I would say it is covered by 1.8.1 + 1.8.2.

---

> V8.3.8 Verify that sensitive personal information is subject to data retention classification, such that old or out of date data is deleted automatically, on a schedule, or as the situation requires.

A bit the same story with the 8.3.3, but it can stay as implementation requirement for Level 3

---

> V8.3.9 Verify that users have a method to export their data on demand.

Out.

Pure policy.

---

> V8.3.10 Verify that sensitive information is removed from the metadata of user-submitted files unless storage is consented to by the user.

Added it myself, not coming from policy.

Need to recheck level, probably level 3. Although it is easy to implement, so it can be also level 2.

---

> V8.3.11 Verify that the application does not ask for unnecessary or excessive permissions to privacy related features or sensors, such as cameras, microphones, or location.

Requirement needs improvement, but is not a policy and it is in.

Previously it was in V10 that application should not contain malicious code that asks unnecessary privileges.

It is not a V4 topic, as it is not an authorization verification issue.

Level must be rechecked, as for everything.

Wording is also negative...

**Comment by tghosth** [comment]
I opened PR #2349 to resolve most of this and I split the 8.3.11 discussion to #2350.
