### ISSUE TITLE
v4 documentation cleanup

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#2331]
I suggest we change v4 documentation requirements to more directly reflect the existing requirements.

1. Verify that the documentation specifies the application enforces function-level access control, restricting access only to consumers with explicit permissions.
2. Verify that the documentation details data-specific access restrictions to consumers with explicit permissions for each data item, mitigating risks such as insecure direct object references (IDOR) and broken object level authorization (BOLA).
3. Verify that the documentation defines field-level access controls, allowing access only to authorized consumers for specific fields to prevent broken object property level authorization (BOPLA).

**Comment by tghosth** [comment]
So [this section](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x12-V4-Access-Control.md#v14-access-control-documentation) (ignoring deleted/moved reqs) looks like this right now:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.4.6** | [ADDED] Verify that the application documentation defines controls that incorporate changes to a consumers environmental and contextual attributes (such as time of day, location, IP address, or device) to make security decisions, including those pertaining to authentication and authorization. These changes should be detected both when the consumer tries to start a new session or during an existing session. | | | ✓ | |
| **1.4.7** | [ADDED] Verify that access control documentation defines the rules for access control decision-making, specifying consumer and subject attributes, resource attributes, and relevant environmental factors involved in the process. | ✓ | ✓ | ✓ | |

**Comment by tghosth** [comment]
I am not sure I want all 3 of those new documentation requirements, especially if we have the implementation requirements already defined. 

Instead, could you check to see whether 1.4.7 sufficient covers the key points of the new requirements you suggested and if not suggest what could be added? @jmanico

**Comment by jmanico** [comment]
Suggestion 1:

4.1.8 Verify that documentation defines adaptive security controls that respond to environmental and contextual attribute changes for authentication and authorization decisions during both new and ongoing sessions.

**Comment by jmanico** [comment]
And I think we want to expand 1.4.7 as follows:=

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
1.4.7 | [ADDED] Verify that access control documentation defines explicit rules for restricting function-level, data-specific, and field-level access based on consumer permissions, specifying relevant consumer and resource attributes, as well as environmental factors involved in decision-making. | ✓ | ✓ | ✓
-- | -- | -- | -- | --
