### ISSUE TITLE
2.22 - I have several issues with this point

### ISSUE THREAD

**Issue by tjherzog** [OWASP/ASVS#234]
First of all: please write out TOTP (in the glossary). I had to google it too:-)

I see a bit of a contradiction to 2.17 because there we allow using email for sending a reset link. Also I do not agree completely to NIST regarding SMS. I know it has some severe security weaknesses. However I think ist is still better than email. May be you see me as a heretic now, but I beleive for most applications in the Internet it is fine yet. Anyway I am not aware of an authentication solution which is free of security issues. Personally. I would restrict the NIST verdict to applications with high protection requirements.

**Comment by vanderaj** [comment]
We are in the process of re-writing V2 completely. We will de-dupe in a little while. The jargon will become 800-63 jargon, and there is already a 800-63 jargon glossary on the page. 

We might need to be pragmatic on transition of extremely common but ineffective controls, and suggest a sunset strategy instead. Happy to have a sunset strategy discussion.

**Comment by vanderaj** [comment]
Can you please review the current version @tjherzog as I think we've dealt with this issue. If not, please let me know.

**Comment by vanderaj** [comment]
Hi there, I'm closing this as I did not hear back. I'm pretty sure I've dealt with this, but in case I've not done so, please re-open.
