### ISSUE TITLE
How do we handle 8.3.11?

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#2350]
Spin off from #2330, what do we do about requirement [v8.3.11](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x16-V8-Data-Protection.md#v83-sensitive-private-data)?

This is the comment that @elarlang provided.

> > V8.3.11 Verify that the application does not ask for unnecessary or excessive permissions to privacy related features or sensors, such as cameras, microphones, or location.
> 
> Requirement needs improvement, but is not a policy and it is in.
> 
> Previously it was in V10 that application should not contain malicious code that asks unnecessary privileges.
> 
> It is not a V4 topic, as it is not an authorization verification issue.
> 
> Level must be rechecked, as for everything.
> 
> Wording is also negative...

**Comment by tghosth** [comment]
Comment from @jmanico:

> I like all of Elar's suggestions. But I would suggest we drop 8.3.11 since users can make the choice to not allow that feature in the browser, they are not automatic.

**Comment by ryarmst** [comment]
Worth considering, but vote drop

**Comment by danielcuthbert** [comment]
Second this, this is all now controlled by the user both on legacy desktops and mobiles, so yeah this doesn't really work anymore
