### ISSUE TITLE
Add token requirement - key material from a trusted source

### ISSUE THREAD

**Issue by TobiasAhnoff** [OWASP/ASVS#2362]
Add access token requirement for to mitigate the risk of getting keys from an untrusted source.

This is part of "cleaning up 3.5" see https://github.com/OWASP/ASVS/issues/1917#issuecomment-2466143871

> Verify that all key material is from a trusted source for each token issuer. For JWTs this is typically achieved by having a preconfigured JWKS URI for the given issuer.

**Comment by randomstuff** [comment]
Would it be worth explicitly mentioning (because this is mistake which is easy to do) that `jku` and `jwk` in the JWS header must not be blindly trusted? I would say it's probably not necessary because this is already covered by this requirement.

**Comment by TobiasAhnoff** [comment]
We could do that to provide more JWT detailes, perhaps like this 

> Verify that all key material is from a trusted source for each token issuer. For JWTs this is typically achieved by having a preconfigured JWKS URI for the given issuer ** and assert that the claims 'jku' and 'jwk' are only accepted if they are validated against an allow list and that no cookies are sent in any GET requests to those URLs.**

But I think this might be too much and the first suggestion is enough?

**Comment by elarlang** [comment]
> and that no cookies are sent in any GET requests to those URLs.

I can not understand this part. How the application have control over that? If the browser has cookies for the issuer then it sends those cookies automatically, the application does not have any control over that.

The opening part should be written "per connection":

> Verify that key material for token issuer is from a pre-configured trusted source.

Maybe also note what is the attack vector to mitigate?

**Comment by TobiasAhnoff** [comment]
The "cookie part" is from https://www.rfc-editor.org/rfc/rfc8725.html#name-do-not-trust-received-claim. The attack to mitigate is SSRF and the risk of getting key material from an untrusted source, see e g https://portswigger.net/web-security/jwt/lab-jwt-authentication-bypass-via-jku-header-injection.

Attacks using the 'kid' claim are also mentioned, and maybe we should add that as a separate issue? But that might be covered in some of the validation requirements in V5?

**Comment by elarlang** [comment]
The rest is clear and worth a requirement.

From https://www.rfc-editor.org/rfc/rfc8725.html#section-3.10
> Similarly, blindly following a "jku" (JWK set URL) or "x5u" (X.509 URL) header, which may contain an arbitrary URL, could result in server-side request forgery (SSRF) attacks. Applications SHOULD protect against such attacks, e.g., by matching the URL to a whitelist of allowed locations and ensuring no cookies are sent in the GET request.

The cookie part is still meh for me.  In the same line are described server-side request forgery and cookies. It is not understandable for me, what kind of cookies are described here? Server sends cookies?

**Comment by randomstuff** [comment]
Maybe the attack scenario would be something like:

1) the consumer server uses session-based sessions for accessing JWK sets on another server (`https://keyserver.internal/keys.jwks`);
2) the attacker would forge a JWK with a `jku` URI pointing to `https://keyserver.internal/keys.jwks`;
3) the consumer server would fetch the JWKs using the cookies (or some other kind of credentials).

This way the attacker might trick the consumer server into using some private/internal key material for some unintended usage. But I'm not sure what the impact would be.

This is quite far-fetched.

**Comment by ryarmst** [comment]
I also find the cookie line the RFC confusing. My best guess (especially as they mention SSRF) is that they are considering the possibility of a server-side HTTP client that stores and transmits cookies (as @randomstuff noted), but this is probably rare at best. I have never seen a client-side (browser) app that validates JWTs in this way. IMO it's an obscure defense in depth consideration and is quite possibly captured by unrelated requirements. 

I propose the following: 

> Verify that only trusted key material and key sources for each token issuer are used to validate cryptographically secured tokens, preventing attackers from specifying untrusted sources and keys. For JWTs, claims such as "jku" and "x5u" must be validated against an allow-list of trusted sources. 


Notes on changes:
- Generalized to consider tampered key sources (such as via `jku`) and key material (I am no OpenID expert, but there exists the `sub_jwk` claim to embed key material directly)
- Added my favourite definition that @elarlang hates: cryptographically secured tokens
- The attack to mitigate is included
- Added JWT-specific claims

**Comment by randomstuff** [comment]
Two notes:

* `jku` and `x5u` are JWS *headers* not JWT *claims*.
* `jwk` should probably listed here as well (i.e. you must not blindly trust the public key listed in the JWT).

I therefore propose the following:

> Verify that only trusted key material and key sources for each token issuer are used to validate cryptographically secured tokens, preventing attackers from specifying untrusted sources and keys. For JWTs, headers such as `jku`, `x5u` and `jwk` must be validated against an allow-list of trusted sources.

Nitpick: this is technically applicable to any *JWS*, not only JWTs but I'm not sure using "JWS" instead of "JWT" in the requirement would be very clear.

**Comment by ryarmst** [comment]
You could have both:

> Verify that only trusted key material and key sources for each token issuer are used to validate cryptographically secured tokens, preventing attackers from specifying untrusted sources and keys. For JWTs and other JWS structures, headers such as jku, x5u, and jwk must be validated against an allow-list of trusted sources.

That said, I don't think it needs to be comprehensive for types of relevant tokens or for relevant headers. The second sentence is essentially: "here is a common example".

**Comment by randomstuff** [comment]
Yes, as this is an example, we can probably skip the "JWS" here.

**Comment by ryarmst** [comment]
Looks good! I dropped it in a PR to add as 3.5.7. See #2377

**Comment by ryarmst** [comment]
Closing as completed with #2377
