### ISSUE TITLE
Small change to 6.2.1

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#2366]
From

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
6.2.1 | Verify that all cryptographic modules fail securely, and errors are handled in a way that does not enable Padding Oracle attacks. | ✓ | ✓ | ✓ | 310

To

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
6.2.1 | Verify that all cryptographic modules fail securely, and errors are handled in a way that does not enable vulnerabilities, such as Padding Oracle attacks. | ✓ | ✓ | ✓ | 310

**Comment by danielcuthbert** [comment]
Like this, more precise. Thanks, will add and do a PR
