### ISSUE TITLE
password policy

### ISSUE THREAD

**Issue by tjherzog** [OWASP/ASVS#237]
With the exception of 2.25 there is nothing about a password policy which which should state explicitly:
- minumum password length
- complexity requirements
- maximum number auth. attempts
- minimum and maximum validity period (yes, here NIST has something new to say)
- use of tarpits
The password policy should also reflect the concret protection requirements and the thread situation of the application.
(see more in the OWASP authentication cheat sheet.)

**Comment by vanderaj** [comment]
We are aligning with NIST 800-63 B normative policies for the three different levels. I believe this will close this ticket. I'll ping you when it's done.

**Comment by m8urnett** [comment]
One thing that should be stated is to avoid overly-complex or restrictive policies (See exhibit A), preferring password length as the main factor for increasing password strength. 

Exhibit A:
![pwtoostrong-751111061860978688-cmx7hzqxeaipxe6](https://user-images.githubusercontent.com/2274288/42390262-8d6917ba-8108-11e8-980b-8bcc3eaedeb0.jpg)

**Comment by m8urnett** [comment]
Also, let's tell people to stop blocking paste and other techniques hostile towards password-managers.

**Comment by m8urnett** [comment]
And applications should consider supporting the full UTF-8 character set.

**Comment by m8urnett** [comment]
And no policies based on the type of character in a specific position, like password cannot begin with a number (see exhibit A). 

Exhibit A
![pwtoostrong-750778554263146497-cmtnhriwcae-4rc](https://user-images.githubusercontent.com/2274288/42390768-44bf5eb4-810a-11e8-88cd-11dd9cbd53ab.jpg)

**Comment by m8urnett** [comment]
And clearly state the policy before someone enters a password, don't make them guess (Exhibit A).

Exhibit A:
![crug_flueaahyoe](https://user-images.githubusercontent.com/2274288/42391082-6208737e-810b-11e8-90fc-ab10558353f8.jpg)

**Comment by m8urnett** [comment]
And passwords should be exactly as they are typed. No case-insensitivity, truncating, or converting unicode to ASCII. Why do we even have to state that?

**Comment by vanderaj** [comment]
Yes, NIST 800-63 has all of these in it. We are on our way (have a look at the latest check in). There will be a fair few removals for NIST 800-63 compliance.

**Comment by vanderaj** [comment]
@m8urnett @tjherzog please check that we have covered off this ticket. I think we have.

**Comment by vanderaj** [comment]
Closing this ticket as I've not heard back. Feel free to re-open if you disagree
