### ISSUE TITLE
V6 - "Stored cryptography" vs "cryptography"

### ISSUE THREAD

**Issue by randomstuff** [OWASP/ASVS#2375]
The V6 chapter is now called "Stored Cryptography" (and was before named "Cryptography"). I actually missed that point until now.

Do we want V6 to be only about Stored Cryptography only?

Some things here would me applicable in other context (such as "Random Values").

If we want V6 to be about "Stored Cryptography", this should probably be clearer in the introduction. In this case, #2310 for example should go somewhere else.

If we keep V6 "Stored Encryption" and V9 "Communication Encryption":

* What about general cryptographic requirements which applies to both? (such as "Random Values")
* Is V9 about "transport layer" security only or should application-layer crypto be in V9 as well?

Related #2252, #2310

**Comment by elarlang** [comment]
This is defining the scope for V6. We need to define, what and based on what rules fits to this paragraph.

In:
* The main problem to solve is about cryptography
* How to implement cryptography correctly

Questionable:
* Using cryptography is (just a possible) solution to solve the main problem

For example, 6.4.1 in the secret management section - the main problem to solve is incorrect handling of secrets, although the solution to solve is to use cryptography (key vault). 6.4.1 got merge from 2.10.4, probably it was not good move.

**Comment by elarlang** [comment]
To solve this issue, you can change the title.

The entire chapter needs review and scoping, but it is a separate topic.

**Comment by tghosth** [comment]
> This is defining the scope for V6. We need to define, what and based on what rules fits to this paragraph.
> 
> In:
> 
>     * The main problem to solve is about cryptography
> 
>     * How to implement cryptography correctly
> 
> 
> Questionable:
> 
>     * Using cryptography is (just a possible) solution to solve the main problem
> 
> 
> For example, 6.4.1 in the secret management section - the main problem to solve is incorrect handling of secrets, although the solution to solve is to use cryptography (key vault). 6.4.1 got merge from 2.10.4, probably it was not good move (edit: reopened #2130).

I agree with this overall approach and I think we need to be looking at V6 in this context. 

I would suggest something like:

V6: Secure Cryptography - How to securely configure and use cryptography
V8: Data Protection - How to handle generally data in a secure way and be careful that it doesn't end up in the wrong places.
V9: Secure Communication - How to securely configure communication channels.
