### ISSUE TITLE
V1.6 cleanup from non-documentation requirements

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#2376]
V1 requirements got cleaned up from non-documentation requirements, except V1.6 https://github.com/OWASP/ASVS/issues/2137

V1.6 has now moved to V6, but 2 requirements do not seem to be security decision documentation requirements:

* V1.6.2 Verify that consumers of cryptographic services protect key material and other secrets by using key vaults or API based alternatives.
* V1.6.4 Verify that the architecture treats client-side secrets (such as symmetric keys, passwords, or API tokens) as insecure and never uses them to protect or access sensitive data.

**Comment by danielcuthbert** [comment]
I wonder if 1.6.2 is of any use anymore? I mean given what we have in V6 now, does it offer much? I guess same goes for 1.6.4 in a way too

**Comment by elarlang** [comment]
Let's start from the first one.

V1.6.2:
> V1.6.2 Verify that consumers of cryptographic services protect key material and other secrets by using key vaults or API based alternatives.

is it duplicate of 6.4.1 and 6.4.2?
> V6.4.1 Verify that a secrets management solution such as a key vault is used to securely create, store, control access to, and destroy back-end secrets, such as passwords, integrations with databases and third-party systems, seeds and internal secrets, and API keys. Secrets must not be included in source code or be received as CI/CD variables. For a L3 application, this should involved a hardware-backed solution such as an HSM.

> V6.4.2 Verify that key material is not exposed to the application (neither the front-end nor the back-end) but instead uses an isolated security module like a vault for cryptographic operations.

**Comment by tghosth** [comment]
Note #684 about 1.6.4

**Comment by danielcuthbert** [comment]
I dont think it is a duplicate and keep it in V6.4. Cleaner and easier.

**Comment by tghosth** [comment]
> I dont think it is a duplicate and keep it in V6.4. Cleaner and easier.

@danielcuthbert are you sure that 1.6.2 and 6.4.1 are not duplicates? Seems like we could easily merge them as follows:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.6.2** | [DELETED, MERGED TO 6.4.1] | | | | |
| **6.4.1** | [MODIFIED, MERGED FROM 1.6.2, 2.10.4] Verify that a secrets management solution such as a key vault is used to securely create, store, control access to, and destroy back-end secrets. These could include passwords, **key material**, integrations with databases and third-party systems, seeds and internal secrets, and API keys. Secrets must not be included in source code or be received as CI/CD variables. For a L3 application, this should involved a hardware-backed solution such as an HSM. | | ✓ | ✓ | 798 |

What do you think?

**Comment by randomstuff** [comment]
Nitpicking as always:

> Secrets must not be included in source code or be received as CI/CD variables.

Secrets must not be included by CI/CD into deliverables/artifacts but CI/CD can receive secrets used for running CI tasks (publishing, etc.).

Proposition:

> [MODIFIED, MERGED FROM 1.6.2, 2.10.4] Verify that a secrets management solution such as a key vault is used to securely create, store, control access to, and destroy back-end secrets. These could include passwords, key material, integrations with databases and third-party systems, seeds and internal secrets, and API keys. Secrets must not be included in source code **or included in build artifacts generated by CI/CD or otherwise**. For a L3 application, this should involve a hardware-backed solution such as an HSM.

**Comment by elarlang** [comment]
@randomstuff - note that we defined CI/CD and the build process as out of scope from ASVS. In scope is the result of what those built - the application. So we need to have requirements based on that we can do verification from the built application itself.

**Comment by randomstuff** [comment]
@elarlang, yes, I was just pointing out that "received as CI/CD variables" which was in the previous proposition was probably not completely accurate.

Maybe this would focus more on the intent:

> [MODIFIED, MERGED FROM 1.6.2, 2.10.4] Verify that a secrets management solution such as a key vault is used to securely create, store, control access to, and destroy back-end secrets. These could include passwords, key material, integrations with databases and third-party systems, seeds and internal secrets, and API keys. Secrets must not be included in (application ?) source code **or included in build artifacts**. For a L3 application, this should involve a hardware-backed solution such as an HSM.

**Comment by tghosth** [comment]
Ok I am comfortable with that modification. Thanks for the updated proposal @randomstuff.

Any further thoughts @danielcuthbert ?

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.6.2** | [DELETED, MERGED TO 6.4.1] | | | | |
| **6.4.1** | [MODIFIED, MERGED FROM 1.6.2, 2.10.4] Verify that a secrets management solution such as a key vault is used to securely create, store, control access to, and destroy back-end secrets. These could include passwords, key material, integrations with databases and third-party systems, seeds and internal secrets, and API keys. Secrets must not be included in (application ?) source code or included in build artifacts. For a L3 application, this should involve a hardware-backed solution such as an HSM. | | ✓ | ✓ | 798 |

**Comment by tghosth** [comment]
Yeah I think I fixed that, thanks

**Comment by randomstuff** [comment]
O sorry I missed that :)
