### ISSUE TITLE
2.5.4 doesn't relate to credential recovery

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#2394]
We have spoken about this requirement before but bottom line is that this doesn't seem to belong in "Credential Recovery"

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **[2.5.4](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x11-V2-Authentication.md#v25-credential-recovery)** | [MODIFIED] Verify that default user accounts (e.g. "root", "admin", or "sa") are not present in the application or are disabled. | ✓ | ✓ | ✓ | 798 |

I think we have a few potential target locations:

* Option 1 - [V2.2 General Authentication Security](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x11-V2-Authentication.md#v22-general-authentication-security) - This doesn't really fit anywhere else in V2 otherwise.
* Option 2 - [V14.6 Web or Application Server Configuration](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x22-V14-Config.md#v146-web-or-application-server-configuration) - This could be considered configuration as it is not necessarily something that is coded into the application but I think this is a weaker choice

What do people think? @elarlang

**Comment by elarlang** [comment]
V2 is "do authentication correctly". If default credentials are used, from V2 perspective it is handled correctly.

For me it is a V14 issue.

Not a perfect match, but V14.1 deploy is dealing with "do not put test-code", "debug modes", "demo functionality" etc to the production.

**Comment by tghosth** [comment]
@jmanico @ryarmst @randomstuff any thoughts on this?

**Comment by jmanico** [comment]
This is more user policy than general authN so I agree v14 seems better.

**Comment by tghosth** [comment]
V14.1 gives me the best vibes here, opened PR #2403
