### ISSUE TITLE
V1.6.5 - Unclear "cryptographic discovery mechanism"

### ISSUE THREAD

**Issue by randomstuff** [OWASP/ASVS#2395]
Current 1.6.5 (as per #685) is:

> [ADDED] Verify that **cryptographic discovery mechanisms** are employed to identify all instances of cryptography in the system, including encryption, hashing, and signing operations.

I don't really understand what "cryptographic discovery mechanisms" are. Can we clarify this?

**Comment by tghosth** [comment]
It would be good to get some clarification in the section text for this section @danielcuthbert

**Comment by jmanico** [comment]
cryptographic discovery mechanisms: I assume these are things like SAST, DAST, SSLLabs type analysis,  manual code review and similar. Standard security review. Is this right Daniel? Can I help with text here?

**Comment by randomstuff** [comment]
Would "manual code review" count as a cryptographic discovery mechanism?

* If so, the requirement is redundant with 1.6.4.
* It not, maybe this should be clarified. I feel this should be more a recommendation around 1.6.4 than a strict requirement. (For example, there might be OS/languages/architectures where tooling might not be very well supported.)

**Comment by tghosth** [comment]
I think that this is automated and I think for L3 it seems reasonable to need an automated way to handle this

**Comment by tghosth** [comment]
@randomstuff any more thoughts on this?

**Comment by randomstuff** [comment]
No, OK for me.
