### ISSUE TITLE
V4 Access Control: Maybe we should add something about the secure use of direct object references

### ISSUE THREAD

**Issue by tjherzog** [OWASP/ASVS#240]
Something like: 
Verify that no direct object references are accessible to users. Instead use only indirect references (e.g. cryptographically strong random values that “map to” the original values).

**Comment by stuartgunter** [comment]
I'm not convinced that indirect object references are a good solution to the problem. It feels to me that IDORs are simply masking a lack of proper authorisation. Making the underlying objects (through IDORs) doesn't fix the underlying vulnerability, as there's still the possibility of link sharing or accidental Google indexing of 'hidden' objects.

From an architectural perspective, any kind of indirection can be very hard to scale for heavy traffic sites with global distribution. However, the underlying authorisation problem is something that can be solved a lot easier in most cases.

Thoughts?

**Comment by subrosaassociates** [comment]
> I'm not convinced that indirect object references are a good solution to the problem. It feels to me that IDORs are simply masking a lack of proper authorisation.

100%
