### ISSUE TITLE
Requirement for managing user consents

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#2401]
Spin-off from #2120

Latest proposal with the intent to have a general (not OAuth and OIDC scenario specific) requirement:
> Verify that the user can review, modify and revoke granted consents at any time.

Problem (for me) to solve: where goes line between "authorization" and "consent"?

How I define consent - user can understand and agrees with proposed event/action to happen. If we consider consent as an event, then it is not possible to "rollback" or revert it later. If we don't consider it as an event or action, how it is different from granting access? Where goes the line between them?

Related added requirements from OAuth and OIDC section:
| # | Description | L1 | L2 | L3 |
| :---: | :--- | :---: | :---: | :---: |
| **51.2.16** | [ADDED] Verify that the authorization server ensures that the user consents to each authorization request. If the identity of the client cannot be assured, the authorization server must always explicitly prompt the user for consent. | | ✓ | ✓ |
| **51.2.17** | [ADDED] Verify that when the authorization server prompts for user consent, it presents sufficient and clear information about what is being consented to. When applicable this should include the nature of the requested authorizations (typically based on scope, resource server, rich authorization requests (RAR) authorization details), the identity of the authorized application and the lifetime of these authorizations. | | ✓ | ✓ |

**Comment by tghosth** [comment]
> Verify that the user can review, modify and revoke granted consents at any time.

I don't want to split this from OIDC/OAuth because it opens a nasty can of worms on other theoretical mechanisms for doing delegated authorization.

The way I see this requirement is that if an app is going to support using OAuth to give consent to other apps to access the user's content in the app , it also needs to provide functionality to allow users to see the consents they have granted to modify or revoke these consents.

My only question is if this is a responsibility of the authorization server or the resource server but either way I would like to see a requirement proposal with the relevant section specified @randomstuff @TobiasAhnoff.

**Comment by elarlang** [comment]
Those I could call authorization, not consents. Those examples are clear - you have access, you take it away:
* "I authorize user A to access my gallery B."
* "I authorize client application A to access gallery B on my behalf."
* "I authorize user A to user client application B to access gallery C on my behalf."

Those are a bit policy oriented - there is a bit of privacy involved, but what is the security problem to solve?
* "I consent of using cookies for tracking me."
* "I consent of telemetry."

If you agreed terms of service - what is the expected action if you redecide or tried to revoke previous consent? What is the security problem to solve?
* "I consent for these terms of service."

Revoking this consent is just "delete your account"?
* "I consent on having an account on this website."

---

My proposal is - let's solve the requirement (at least at the moment) for OAuth and OIDC scenario with specific workding and see, is it clear and actionable at least in this context.

The rest seems low-impact and/or policy-oriented gray area for me.

**Comment by randomstuff** [comment]
> ose are a bit policy oriented - there is a bit of privacy involved, but what is the security problem to solve?

I agree with your question :) My point was that maybe my wording was too general because it might apply to non-security topics.

> My proposal is - let's solve the requirement (at least at the moment) for OAuth and OIDC scenario with specific workding and see, is it clear and actionable at least in this context.

Yes, I agree.

I'm not so clear about consent vs. (user) authorization. They are somewhat the same thing to me.

**Comment by TobiasAhnoff** [comment]
Maybe we could have this to keep it OAuth/OIDC specific?

> Verify that the user can review, modify and revoke consents granted by the authorization server at any time.

**Comment by elarlang** [comment]
I would remove "at any time" as it does not give anything extra.
> Verify that the user can review, modify and revoke consents he has granted through the authorization server ~~at any time~~.

> Would that be "consents" or "consents and authorization"?

"Verify that the user can revoke authorization" sounds very much to have possibility to revoke access tokens.

I think the authorization part is covered by the requirement:
> V51.2.14 Verify that refresh tokens and reference access tokens can be revoked by an authorized user. It can be achieved by using the authorization server user interface, or by a client that is using authorization server APIs for revocation.

**Comment by tghosth** [comment]
So the proposed requirement is:

> Verify that the user can review, modify and revoke consents which the user has granted through the authorization server.

What section are we proposing for this?

**Comment by elarlang** [comment]
> What section are we proposing for this?

It's authorization server responsibility. so it is V51.2 OAuth Authorization Server

Not sure, should it cover "V51.5 OIDC OpenID Provider" as well.

We also have too many requirements in the "V51.2 OAuth Authorization Server" already and 3 requirements about consent. There can be some grouping done.

**Comment by randomstuff** [comment]
> Not sure, should it cover "V51.5 OIDC OpenID Provider" as well.

I think, it should apply as OIDC as well.

**Comment by tghosth** [comment]
Sounds like OIDC also has an Authorization Server so maybe section 51.2 should be V51.2 OAuth/OIDC Authorization Server

@randomstuff do you think you could propose how it could fit into 51.2 including grouping some of the consent requirements?

**Comment by TobiasAhnoff** [comment]
> Sounds like OIDC also has an Authorization Server so maybe section 51.2 should be V51.2 OAuth/OIDC Authorization Server

The idea is to make this clear with the first section of title text

> OAuth2 has become industry standard for delegating API authorization and also the basis for end-user authentication using OpenID Connect (OIDC), where OIDC is an identity layer on top of OAuth2. Thus, all OAuth2 verifications in this chapter also apply to OIDC, while OAuth2 can be used without OIDC verifications.

That is why 5.2 is called just OAuth and not OAuth/OIDC...but I think it is good to also have OAuth/OIDC in the title to make that clearer, but  if we change to OAuth/OIDC for 5.2 then we also need to do the same change for 5.3 and 5.4 (all OAuth requirements applies to OIDC as well). Perhaps also some note on terminology for OAuth Authorization Server and OIDC OpenID Provider.

> We also have too many requirements in the "V51.2 OAuth Authorization Server" already and 3 requirements about consent. There can be some grouping done.

Yes, sounds like good idea!

**Comment by randomstuff** [comment]
>  including grouping some of the consent requirements?

I think the consent requirements are quite long/verbose enough, I'm not sure how we can stick more things into them :)

**Comment by elarlang** [comment]
Proposal for new section `## V51.X OAuth Authorization Server - Consent management`

Move to new section:
* V51.2.16 Verify that the authorization server ensures that the user consents to each authorization request. If the identity of the client cannot be assured, the authorization server must always explicitly prompt the user for consent.
* V51.2.17 Verify that when the authorization server prompts for user consent, it presents sufficient and clear information about what is being consented to. When applicable this should include the nature of the requested authorizations (typically based on scope, resource server, rich authorization requests (RAR) authorization details), the identity of the authorized application and the lifetime of these authorizations.

And add new requirement to this section:
* Verify that the user can review, modify and revoke consents which the user has granted through the authorization server.

Depends how to scope the section, it may cover also "access management"
* V51.2.14 Verify that refresh tokens and reference access tokens can be revoked by an authorized user. It can be achieved by using the authorization server user interface, or by a client that is using authorization server APIs for revocation.

But at the moment I don't have any good wording in mind for section title to cover also V51.2.14, so at the moment the proposal is to have 3 consent-related requirement into new section.

Action needed: section title.

**Comment by elarlang** [comment]
> As currently we have one requirement which says "or by a client that is using authorization server APIs for revocation", this may not be stricly/only a authorization server requirements.

but it is AS responsibility to provide that API, for that reason the requirement is in that section. I don't see the conflict there.

I'm afraid that "authorization management" is too vague and can be said everything related to authorization, so a safe option is to have "consent management" section for 3 consent-related requirements and leave the current V51.2.14 where it is at the moment.

**Comment by TobiasAhnoff** [comment]
It looks good to me, I think user works since this is for the consent context
