### ISSUE TITLE
New 6.6.1 and 6.6.5 are duplicates

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#2402]
We currently have the following requirements

## [V6.6 Hashing and Hash-based Functions](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x14-V6-Cryptography.md#v65-cipher-algorithms)

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **6.6.1** | [ADDED] Verify that only approved hash functions are used for general cryptographic use cases, including digital signatures, HMAC, KDF, and random bit generation. | | ✓ | ✓ | |
| **6.6.5** | [ADDED] Verify that suitable hash functions are used in HMACs, KDFs, and random bit generation. | | ✓ | ✓ | |

Are these requirements different or could they be merged @danielcuthbert?

**Comment by danielcuthbert** [comment]
100% can be merged and ill make it 6.6.1
