### ISSUE TITLE
V4 Access Control: Use of roles as a requirement?

### ISSUE THREAD

**Issue by tjherzog** [OWASP/ASVS#241]
A role model (RBAC) should exist and the authorization for access to resources should be based on such roles. Thos should be verified.
Note: I am not a real expert on this topic. There are definitly better ways to formulate this.

**Comment by vanderaj** [comment]
We can't be holding back the use of claim based and capabilities or MAC. If there is a specific wording, please re-open, otherwise this is closed.

**Comment by vanderaj** [comment]
Note: hard coding roles in code is coupling policy with code, and is discouraged in modern applications.

**Comment by tjherzog** [comment]
I agree completly with you in this . I just wanted to state for business applications with hundreds or thousands of users or more access control should be based on the usage of role models (IsUserInRole) and not on individual access rights.

**Comment by jmanico** [comment]
I politely disagree. Basing access control enforcement points on roles (ie: hard coding roles) is an anti-pattern. Modern applications should be hard-coding features or capabilities; not roles.

--
Jim Manico
@Manicode
