### ISSUE TITLE
V51 Reorder sections

### ISSUE THREAD

**Issue by randomstuff** [OWASP/ASVS#2417]
We currently have this structure:

* V51.2 OAuth Authorization Server
* V51.3 OAuth Client
* V51.4 OAuth Resource Server
* V51.5 OIDC Client
* V51.5 OIDC OpenID Provider

I find it weird that the ordering is not the same for OAuth and OIDC :

* OAuth AS then OAuth client
* but OIDC client then OIDC OP (=AS)

could we move things around to keep the ordering more consistent?

**Comment by elarlang** [comment]
We can move things around, propose order.

**Comment by randomstuff** [comment]
I would suggest something like:

* V51.1 OAuth Client
* V51.2 OAuth Resource Server
* V51.3 OAuth Authorization Server
* V51.4 OIDC Client
* V51.5 OIDC OpenID Provider

Changes:

* Move client considerations first as we intent to have to check it for more applications
* Consistent order for OAuth part and OIDC part

Nitpick: "OIDC OpenID Provider" is somewhat redundant as it means "OpenID Connect OpenID Provider". Should we have "OpenID Provider (OIDC)" instead?

**Comment by elarlang** [comment]
V51.1 OAuth Client as the first one? At the moment we have 1st "V51.1 Generic OAuth and OIDC security" as the first one, and we have PR to add "V51.7 Consent Management" as the last one.

So please add those 2 also to your proposal.

**Comment by randomstuff** [comment]
Oh yes sorry I forgot the first one :)

**Comment by randomstuff** [comment]
Proposition:

* V51.1 Generic OAuth and OIDC security
* V51.2 OAuth Client
* V51.3 OAuth Resource Server
* V51.4 OAuth Authorization Server
* V51.5 OIDC Client
* V51.6 OIDC OpenID Provider
* V51.7 Consent Management

**Comment by elarlang** [comment]
https://github.com/OWASP/ASVS/pull/2415/commits/2cd43ca73c6573cce2859a8658568f0e6846816b

changed "V51.6 OIDC OpenID Provider" to "V51.6 OpenID Provider"
