### ISSUE TITLE
V50.2.1 (v4.0.3-3.4.1) - cookie secure attribute

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#2419]
Current requirement, moved from V3.4.1 to V50.2.1 via #2410:
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **50.2.1** | [MOVED FROM 3.4.1] Verify that cookie-based session tokens have the 'Secure' attribute set. | ✓ | ✓ | ✓ | 614 |

As the requirement is now a general cookie security requirement, the wording must be non-session-cookie specific.

Proposal:
> Verify that cookies have the 'Secure' attribute set.

Level: keep level 1

**Comment by elarlang** [comment]
Proposal update based on https://github.com/OWASP/ASVS/issues/2422#issuecomment-2507489508 + https://github.com/OWASP/ASVS/issues/2422#issuecomment-2507546095

> Verify that cookie-based session tokens have the 'Secure' attribute set, and if the '__Host-' prefix is not used for the cookie name, the '__Secure-' prefix must be used for the cookie name.

The reasons:
* `Secure` gives that browser is not allowed to send the cookie over `http:` connection
* `__Secure-` gives that it is not possible to write a cookie with the same name without a `Secure` flag (including over `http:` connection)

**Comment by tghosth** [comment]
Does every cookie need this or only sensitive cookies?

**Comment by Sjord** [comment]
I suggest to make this requirement simply "all cookies must have the secure flag set", and then have a separate requirement for the cookie prefix.

**Comment by elarlang** [comment]
I prefer not, because:
* `__Secure-` is related to `Secure` - both are for sending the message to the browser, that "cookies only over HTTPS"
* `__Secure-` itself requires usage of `Secure`
* `__Secure-` we can require only, if it is not valid to require `__Host-` to be used

**Comment by tghosth** [comment]
> Verify that cookies have the 'Secure' attribute set, and if the '__Host-' prefix is not used for the cookie name, the '__Secure-' prefix must be used for the cookie name.

Agree with this wording, I agree that I don't want more requirements out of this :)
