### ISSUE TITLE
Authentication -- Make sure user can modify credentials

### ISSUE THREAD

**Issue by TheDauntless** [OWASP/ASVS#242]
Currently, there is no control that states that a user should be able to change his password. The closest related control is 2.31:

> Verify that if an application allows users to authenticate, they can authenticate using two-factor authentication or other strong authentication, or any similar scheme that provides protection against username + password disclosure.

But this doesn't really cover it. I would add a control as follows:

> Verify that if an application allows users to authenticate using credentials, they can manually modify the primary credentials.

**Comment by vanderaj** [comment]
I created a new item V2.34, but I've also tidied up this partially complete section. Please review. We are adopting NIST 800-63's terminology to avoid confusion.
