### ISSUE TITLE
V50.2.2 (v4.0.3-3.4.2) - cookie httponly attribute

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#2420]
Current requirement, moved from V3.4.2 to V50.2.2 via #2410:
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **50.2.2** | [MODIFIED, MOVED FROM 3.4.2] Verify that cookie-based session tokens are not readable by client-side scripts. The session token cookie should have the 'HttpOnly' attribute set and the session token value should only be transferred to the client via the Set-Cookie header field. | ✓ | ✓ | ✓ | 1004 |

As the requirement is now a general cookie security requirement, the wording must be non-session-cookie specific.

Proposal:
> Verify that if the cookie is not meant to be accessible for client-side scripts (such as a cookie for session token), the cookie must have the 'HttpOnly' attribute set and the same value (e. g. session token) must only be transferred to the client via the 'Set-Cookie' header field.

Level: 2nd layer of defense, level 2

**Comment by tghosth** [comment]
Minor tweaks:

_Verify that if the **value of** a cookie is not meant to be accessible to client-side scripts (such as a **session token**), the cookie must have the 'HttpOnly' attribute set and the same value (e. g. session token) must only be transferred to the client via the 'Set-Cookie' header field._
