### ISSUE TITLE
V50.2.3 (v4.0.3-3.4.3) - cookie samesite attribute

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#2421]
Current requirement, moved from V3.4.3 to V50.2.3 via #2410:
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **50.2.3** | [MOVED FROM 3.4.3] Verify that cookie-based session tokens utilize the 'SameSite' attribute to limit exposure to cross-site request forgery attacks. | ✓ | ✓ | ✓ | 1275 |

As the requirement is now a general cookie security requirement, the wording must be non-session-cookie specific.

Proposal:
> Verify that cookies have the 'SameSite' attribute set according to the purpose of the cookie. For example, if the cookie is not meant to be sent from a cross-site party, it must have the 'SameSite' attribute set with the value 'Lax' or 'Strict' to limit exposure to cross-site request forgery and user interface redress attacks.

Level: from mostly 2nd layer of defense point of view, it can be level 2. from easy to implement point of view, level 1

**Comment by tghosth** [comment]
Grammar:

_Verify that each cookie's 'SameSite' attribute value is set according to the purpose of the cookie. For example, if the cookie is not meant to be sent from a cross-site party, it must have the 'SameSite' attribute set with the value 'Lax' or 'Strict' to limit exposure to cross-site request forgery and user interface redress attacks._

**Comment by elarlang** [comment]
... it requires some further work:
* Lax - cookie is sent with top-level navigation request with cross-site request
* String - not sent with any cross-site request

**Comment by tghosth** [comment]
_Verify that each cookie's 'SameSite' attribute value is set according to the purpose of the cookie. For example, if the cookie is not meant to be sent from a cross-site party, it must have the 'SameSite' attribute set with the value 'Lax' to limit exposure to cross-site request forgery and user interface redress attacks. L3 applications should have sensitive cookies set with the value 'Strict'._

What do you think?

**Comment by elarlang** [comment]
no, Lax vs Strict is not about he levels but how the application works.

**Comment by tghosth** [comment]
I know but stricter is more secure but requires more thought to implement

**Comment by tghosth** [comment]
Maybe we just need to not be prescriptive like in the original requirement

**Comment by tghosth** [comment]
Proposed following discussion with Elar:

_Verify that each cookie's 'SameSite' attribute value is set according to the purpose of the cookie, to limit exposure to cross-site request forgery and user interface redress attacks._

@elarlang to open PR

**Comment by jmanico** [comment]
The SameSite strict/lax rules can be quite complicated. Here is a chart I use to explain it just in case you wish to be more prescriptive. Strict generally provides better security but limits functionality.

![Screenshot 2024-12-05 at 4 01 26 PM](https://github.com/user-attachments/assets/1a398dfc-6d41-41d0-8654-f45d69838829)

**Comment by elarlang** [comment]
> The SameSite strict/lax rules can be quite complicated. Here is a chart I use to explain it just in case you wish to be more prescriptive. Strict generally provides better security but limits functionality.

As you can see, we decided to not be prescriptive. Your table is also simplified, for example, it does not take into account embedded content.

To describe all the scenarios we enter to the cheat sheet area, it is not helpful for the requirement.

Closing this at the moment.
