### ISSUE TITLE
V50.2.4 (v4.0.3-3.4.4) - cookie __Host- name prefix

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#2422]
Current requirement, moved from V3.4.4 to V50.2.4 via #2410:
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **50.2.4** | [MOVED FROM 3.4.4] Verify that cookie-based session tokens use the "\_\_Host-" prefix so cookies are only sent to the host that initially set the cookie. | ✓ | ✓ | ✓ | 16 |

As the requirement is now a general cookie security requirement, the wording must be non-session-cookie specific.

Proposal:
> Verify that if the cookie is meant to be used only by the same host from where it is written, the cookie has the "\__Host-" prefix for the cookie name.

updated proposal from https://github.com/OWASP/ASVS/issues/2422#issuecomment-2507457902
> Verify that the cookie has the '__Host-' prefix for the cookie name unless it is explicitly designed to be shared with other hosts.

level: from easy to implement point of view, level 1. can be level 2

**Comment by randomstuff** [comment]
Alternative "stronger" wording:

> Verify that the cookie the cookie has the "__Host-" prefix for the cookie name unless it is explicitly designed to be shared with other hosts.

Optional sentence at the end of the requirement:

> In this case, it must have the "__Secure-" prefix instead.

If we don't include this extra sentence, we should probably have a requirement which says "user either __Host- or __-Secure-".

**Comment by elarlang** [comment]
I don't agree with that. Those prefixes are different things and address different problems
* `__Host-` avoid competitive cookies (over)written from same-site scope
* `__Secure-` basically enforce the usage of `Secure` attribute

**Comment by elarlang** [comment]
> > __Secure- basically enforce the usage of Secure attribute
> 
> It prevents an adversary from setting the cookie from `http:`. This is not a problem when using HSTS unless the cookie is set before the browsers sees the HSTS.

it can be still a problem when HSTS is not set to the main domain. Then any site from the eTLD+1 scope can write cookie. Including when someone serves `http:` service from own-controlled network.

But it is not the topic for `__Host-`, it is for `Secure`. `__Secure-` can be part of 50.2.1 (#2419).

**Comment by randomstuff** [comment]
For me both "__Host-" and "__Secure-" prefixes are about making sure that adversaries do not define/overwrite the cookie for us and should be together in 50.2.4.

On the other hand, 50.2.1 would be about making sure that the data stored in the cookie is not exfiltrated. The "__Secure-" prefix does not help with that.

But I can live with __Secure- being discussed in 50.1.2 :smile:

**Comment by elarlang** [comment]
> For me both "__Host-" and "__Secure-" prefixes are about making sure that adversaries do not define/overwrite the cookie for us and should be together in 50.2.4.

`__Secure-` prefix does not provide that.

> On the other hand, 50.2.1 would be about making sure that the data stored in the cookie is not exfiltrated. The "__Secure-" prefix does not help with that (the Secure attribute alone does).

They are not the same. `__Secure-` vs `Secure` :
* `Secure` - this cookie is can not be written and later sent over `http:` connection, but you can (over)write existing cookie (key: name+domain/host+path) without setting the `Secure` flag from `http:` connection
* `__Secure-` - is it requires `Secure` to be set, it has the same as `Secure` PLUS - you can not write the cookie with `__Secure-` from `http:` connection.

If there is further need to explain those, I'll invite you to my training ;)

**Comment by elarlang** [comment]
Yes, `__Host-` provides that you can not write so-called competitive cookie (a cookie with the same name valid to the same scope) choosing different path or domain values. This is something that `__Secure-` does not provide.

For that reason, those Keycloak cookies are manipulatable from any site from the same-site scope. And for that reason I proposed:
> V50.1.1 Verify that separate applications are hosted on different hostnames to leverage the restrictions provided by same-origin policy, including how documents or scripts loaded by one origin can interact with resources from another origin and hostname-based restrictions on cookies.

**Comment by Sjord** [comment]
> but you can (over)write existing cookie

It is [no longer possible](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-cookie-alone-01) to overwrite an existing secure cookie.

> In this case, it must have the "__Secure-" prefix instead.

I agree. I think it makes sense to put both prefixes in one requirement. __Host has the behavior of __Secure and more, and it is not possible to include both prefixes. So all cookies should have either the __Secure or __Host prefix.

**Comment by elarlang** [comment]
> > but you can (over)write existing cookie
> 
> It is [no longer possible](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-cookie-alone-01) to overwrite an existing secure cookie.

Re-checked, that's correct. But you can still write a cookie with the same name to valid for the same request. That is the reason to use `__Host-`.

> > In this case, it must have the "__Secure-" prefix instead.
> 
> I agree. I think it makes sense to put both prefixes in one requirement. __Host has the behavior of __Secure and more, and it is not possible to include both prefixes. So all cookies should have either the __Secure or __Host prefix.

The only duplicating behavior is that you can not write a cookie with the same name from `http:` connection.

**Comment by tghosth** [comment]
> Verify that the cookie has the '__Host-' prefix for the cookie name unless it is explicitly designed to be shared with other hosts.

I think this makes sense to me
