### ISSUE TITLE
V51 - Restrictions about the OAuth/OIDC flows

### ISSUE THREAD

**Issue by randomstuff** [OWASP/ASVS#2428]
We currently don't really disallow any (legacy) OAuth/OIDC flows as far as I understand.

In V51.4 OAuth Authorization Server

> 51.4.5 [ADDED] Verify that for a given client, the authorization server only allows the usage of grants that this client needs to use. Note that the grants 'token' (Implicit flow) and 'password' (Resource Owner Password Credentials flow) *should* no longer be used.

In V51.6 OpenID Provider:

> 51.6.1 [ADDED] Verify that the OpenID Provider only allows values 'code', 'ciba', 'id-token', or 'id-token code' for response mode. Note that 'code' is preferred over 'id-token code' (the OIDC Hybrid flow), and 'token' (any Implicit flow) *should* not be used

Can we be more specific?

* The resource Owner Password Credentials flow is currently "should not be used" as far as I understand. Can we have this a "MUST not be used" instead?
* The implicit flow is currently "should not use used". Can we have a "MUST not be used" (or maybe we can allow it for L1?).
* For the OIDC Hybrid flow: probably like the implicit flow?

**Comment by jmanico** [comment]
*> *The resource Owner Password Credentials flow is currently "should 
not be used" as far as I understand. Can we have this a "MUST not be 
used" instead?

I suggest only a /should /at best. There are niche situations where ROPC 
is just fine. For example, when using a *Trusted First-Party Client 
*(ie: the same client and service from the same provider - like a 
dropbox app from dropbox)*then ROPC* is just fine.*
*

**Comment by randomstuff** [comment]
> the same client and service from the same provider - like a dropbox app from dropbox

There are important downsides to that:

* You are limited to authenticating using only a password (as opposed to using a TOTP, WebAuthn, X.509 certificates, "remember this device", delegating to another SSO provider, confirmation code sent through another channel, grant this authorization from another device, CAPTCHA (**), etc).
* You cannot ask for user consent and let the user review the requested authorization.

(Moreover, this is not specified in OAuth 2.1.)

Actually we have this requirement at L2 which seems like in conflict with allowing the usage of resource owner password credentials flow (*):

> [ADDED, SPLIT FROM 2.2.4] Verify that the application requires users to either use a multi-factor authentication mechanism or a requires a combination of single-factor authentication mechanisms.

It would be consistent to allow the resource owner password credentials at L1 but probably not at L2 (?).

(*) Unless the additional factor is implement in the client application / relying party. This not make much sense for authorization Oauth. For OIDC, this would mean having some authentication credentials stored in the IdP and some authentication credentials stored in the client applications which does not seem very nice/scalable to me and defeats the purpose of a SSO solution.

(**) You can have a CAPTCHA in the RP but it would certainly make more sense to have a CAPTCHA in the IdP.

**Comment by elarlang** [comment]
Maybe it fires back in some edge cases, but as both are dropped from the [OAuth 2.1](https://oauth.net/2.1/):
* _The Implicit grant (response_type=token) is omitted from this specification_
* _The Resource Owner Password Credentials grant is omitted from this specification_

So I think it is ok to go with "must".

**Comment by TobiasAhnoff** [comment]
For L3 is is a MUST (according to FAPI specs), for L1 and even some L2 it might be fine...in example Microsoft has this note (for both ROPC and Implicit)

_Microsoft recommends you do not use the ROPC [or Implicit] flow. In most scenarios, more secure alternatives are available and recommended. This flow requires a very high degree of trust in the application, and carries risks that are not present in other flows. You should only use this flow when other more secure flows aren't viable._ 

Perhaps have something like, or perhaps split on different levels?   

> 51.4.5 [ADDED] Verify that for a given client, the authorization server only allows the usage of grants that this client needs to use. For L3, the grants 'token' (Implicit flow) and 'password' (Resource Owner Password Credentials flow) must no longer be used. For L1 and L2 they must not be used if more secure flows are viable.

For OIDC 51.6.1 it is the basically the same and the reason for "code preferred over Hybrid" is that Hybrid is allowed in FAPI 1.0 Advanced and 2.0 is a draft.

**Comment by elarlang** [comment]
It can be also the question of language - is there in MS material anything that they require with "MUST" or it is just a political way to say "must"?

One option is, that we use the word "must" and it is a level 2 requirement.

**Comment by TobiasAhnoff** [comment]
I think "must" and L2 works (it is clear and in most cases it is correct).

**Comment by elarlang** [comment]
https://github.com/OWASP/ASVS/pull/2453/commits/107a9e7b99b20489a0ad5fd1863c3aa58d0a0cde
