### ISSUE TITLE
Potential issues in the bleeding edge chapter 14 and 20. 

### ISSUE THREAD

**Issue by ValdiGit01** [OWASP/ASVS#2454]
Hi, I have been following the great work you are doing on v5.0. Unless I'm mistaken, I’ve found an issue you might want to fix:

**Issue with 14.4.6:**
14.4.6 refers to 50.2.4, while 50.2.4 appears to be moved and modified from 3.4.4 appears to have been moved and modified from 3.4.4. (See snippet below from the RAW version)

| **14.4.6** | [MOVED TO 50.2.4] | | | | |  
from -> https://github.com/OWASP/ASVS/blob/master/5.0/en/0x22-V14-Config.md

| **50.2.4** | [MODIFIED, MOVED FROM 3.4.4, LEVEL L1 > L2] Verify that cookies have the '__Host-' prefix for the cookie name unless they are explicitly designed to be shared with other hosts. | | ✓ | ✓ | |   
Source-> https://raw.githubusercontent.com/OWASP/ASVS/refs/heads/master/5.0/en/0x50-V50-Web-Frontend-Security.md

**Issue with 14.4.7:**
14.4.7 refers to 50.2.5 but there is no 50.2.5 in v5.0 (it ends with 50.2.4) 
Copy paste from chapter 14:
| **14.4.7** | [MOVED TO 50.2.5] | | | | |
Source -> https://github.com/OWASP/ASVS/blob/master/5.0/en/0x22-V14-Config.md AND https://raw.githubusercontent.com/OWASP/ASVS/refs/heads/master/5.0/en/0x50-V50-Web-Frontend-Security.md 

Best regards, 
Thor

**Comment by elarlang** [comment]
Yes, that is correct - the mapping is incorrect after inserting the cookie section into the V50 and changed many numbers there. Thank you!

**Comment by elarlang** [comment]
After the merge of https://github.com/OWASP/ASVS/pull/2455/commits/ee0ff1fa82bf179197b7051aaeff960357c107bc via #2455 the mapping should be up to date again. Thank you @ValdiGit01 !

**Comment by tghosth** [comment]
@ValdiGit01 did you find these manually or using a tool?

**Comment by ValdiGit01** [comment]
> @ValdiGit01 did you find these manually or using a tool?

I did it manually. Im using the bleeding edge to plan for work in 2025 :-)
