### ISSUE TITLE
5.1.6 move cookie value max length to dedicated cookie section V50.2

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#2458]
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **5.1.6** | [ADDED] Verify that untrusted input is validated for length before being included in a cookie (including as part of a JWT) and that the cookie name and value length combined are not over 4096 bytes. | | ✓ | ✓ | |

We have now dedicated section "V50.2 Cookie Setup" for cookies and I think this requirements belongs there.

Maybe need to change the section title to "HTTP Cookies"?

**Comment by tghosth** [comment]
I don't love it but I am ok with it

**Comment by jmanico** [comment]
Small change suggestion and language cleanup, and the addition of encoding.

_Verify that untrusted input is validated for length before inclusion in a cookie (including JWTs) and ensure the total cookie size (name and value, including encoding) does not exceed 4096 bytes._

**Comment by elarlang** [comment]
> including JWTs

I think it has different meaning than "including as part of a JWT"

> including encoding

What encoding you are talking here?

**Comment by jmanico** [comment]
Some libraries may encode data before dropping them into a cookie, so what happens is the size of not the raw data but sometime the size of the *ended* data.

The JWT confuses me a lot because we are talking about cookies and cookie limits, what does JWT have to do with this?

**Comment by elarlang** [comment]
JWT is for hiliglighting potential issue - if user input is included into JWT and JWT is put into a cookie, then the application must take into account that the generated value does not exceed the 4kB limit. Probably it covers your encoding scenario as well.

**Comment by elarlang** [comment]
> Make me an offer :)

Pick one:
> Verify that when the application writes a cookie the cookie name and value length combined are not over 4096 bytes.

> Verify that when the application writes a cookie the cookie name and value length combined are not over 4096 bytes, otherwise the cookie is ignored by the user-agent.

**Comment by jmanico** [comment]
I prefer “Verify that when the application writes a cookie the cookie name and value length combined are not over 4096 bytes”.

I know you’re tough Elar, but with “otherwise the cookie is ignored by the user-agent” you can’t always force a user-agent to behave in a certain way.

**Comment by elarlang** [comment]
> I know you’re tough Elar, but with “otherwise the cookie is ignored by the user-agent” you can’t always force a user-agent to behave in a certain way.

This just the way how the reality is nowadays - browsers ignore this kind of attempts to write cookies.

**Comment by jmanico** [comment]
Several of today's browsers truncate, not block the write, when the size is exceeded.

FireFox 133 truncates after 4096 bytes (total cookie size), but still allows the write
Safari 18.1.1 truncates after 12360 bytes, but still allows the write

**Comment by elarlang** [comment]
> Several of today's browsers truncate, not block the write, when the size is exceeded.
> 
> FireFox 133 truncates after 4096 bytes (total cookie size), but still allows the write Safari 18.1.1 truncates after 12360 bytes, but still allows the write

No, Firefox 133 does not do truncation.

Test 1:
```js
document.cookie='a='+('0'.repeat(4094));
document.cookie;
```

Test 2:
```js
document.cookie='b='+('0'.repeat(4095)); // one symbol too much
document.cookie;
```

From test 1 cookie `a` is written, from test 2 cookie `b` is not.

Can not test with Safari right now, but it's hard to believe the limit is 12360 bytes, as servers mostly can not handle more than 8kB. So it just does not make sense, but... it's Safari.

**Comment by jmanico** [comment]
I sent you my test code so you can see how I got to my values. I’m testing the write with document.cookie.length.

Also, the RFC for cookies says there should be no arbitrary max length for cookies, I can point that out later today (admittedly it’s an old RFC).

**Comment by elarlang** [comment]
And I shared my little simple-stupid snippet to prove your script to be wrong.

You can count that I have went through all related RFC's and pointing to those does not give any extra value. Especially, cookies are this kind of piece of technology, where reality and specs are not always walk hand-in-hand.

**Comment by jmanico** [comment]
Yup, you're right.

- In Firefox the failure is here: document.cookie='b='+('0'.repeat(4095)); 
- In Safari the failure is here document.cookie='c='+('0'.repeat(4096)); 

Your test code fails to run in Chrome or Edge, but I get your point.

**Comment by tghosth** [comment]
> Verify that when the application writes a cookie the cookie name and value length combined are not over 4096 bytes, otherwise the cookie is ignored by the user-agent.

Are we saying that the browser won't accept a cookie of that size anyway? If so, is this necessary as a security requirement as surely from a functionality requirement the app will fail to work?

I thought the original problem here was some sort of denial of service where the user ends up with a such a large cookie that they can no longer work with the application?

Do we want to clarify?

> Verify that when the application writes a cookie the cookie name and value length combined are not over 4096 bytes, otherwise the cookie is ignored by the user-agent and the end user may therefore not be able to use the application.

Or have I misunderstood?

**Comment by elarlang** [comment]
> I thought the original problem here was some sort of denial of service where the user ends up with a such a large cookie that they can no longer work with the application?

This DoS scenario is covered by other requirement:
> 5.1.8 Verify that the application validates that user-controlled input in HTTP request header fields does not exceed the server's maximum header field size limit (usually 4kB or 8kB) to prevent client-based denial of service attacks.

As you proposed yourself, this scenario may lead to (client-based) denial of service as well. Example: Iif an untrusted input reach to the set-cookie, command, browser ignores that and the cookie is not usable. May easily happen if untrusted data goes into JWT - then there is additional length for JSON formating, then additional length for base64uri encoding and additional length for signature.

**Comment by tghosth** [comment]
So can you clarify the reason in the requirement whilst we are making changes anywy?

**Comment by elarlang** [comment]
> So can you clarify the reason in the requirement whilst we are making changes anyway?

https://github.com/OWASP/ASVS/issues/2458#issuecomment-2539903544 ?

**Comment by tghosth** [comment]
> > So can you clarify the reason in the requirement whilst we are making changes anyway?
> 
> [#2458 (comment)](https://github.com/OWASP/ASVS/issues/2458#issuecomment-2539903544) ?

I meant can you provide a proposal for the requirement which includes the reason

**Comment by elarlang** [comment]
I think this is enough from https://github.com/OWASP/ASVS/issues/2458#issuecomment-2540693641

> Verify that when the application writes a cookie the cookie name and value length combined are not over 4096 bytes, otherwise the cookie is ignored by the user-agent.

---

Your proposal may and may not be true, it depends what kind of cookie it is: https://github.com/OWASP/ASVS/issues/2458#issuecomment-2543512026

> Verify that when the application writes a cookie the cookie name and value length combined are not over 4096 bytes, otherwise the cookie is ignored by the user-agent and the end user may therefore not be able to use the application.

**Comment by tghosth** [comment]
I just think the issue we are solving here needs to be clearer

**Comment by elarlang** [comment]
> Verify that when the application writes a cookie the cookie name and value length combined are not over 4096 bytes, otherwise the cookie is ignored by the user-agent.

If this proposal is not clear enough, then what is your proposal to improve it, taking into account comments from here: https://github.com/OWASP/ASVS/issues/2458#issuecomment-2543518593

**Comment by tghosth** [comment]
"_Verify that when the application writes a cookie the cookie name and value length combined are not over 4096 bytes. Overly large cookies might be ignored by the browser and not sent with requests. This might prevent the end user from using the application until a replacement cookie of an allowed size is sent._"

Did I understand correctly?

**Comment by elarlang** [comment]
By principle yes.

> Overly large cookies might be ignored by the browser and not sent with requests.

Technically is not precise, proposed version may me interpreted as "browser stores the cookie but just do not send it", but the reality is that browser ignores the set-cookie header field (or the command browser cookie API alternative).

I'm not sure that so long text is required for that requirement. I think this is enough:

> otherwise the cookie is ignored by the user-agent.

**Comment by tghosth** [comment]
Shorter and more exact?

"_Verify that when the application writes a cookie the cookie name and value length combined are not over 4096 bytes. Overly large cookies will not be stored by the browser and therefore not sent with requests, preventing the user form accessing the session mechanism._"

**Comment by elarlang** [comment]
> reventing the user form accessing the session mechanism.

We are not in the "session management" section anymore and cookies are not limited to sessions. I would skip that part.

**Comment by tghosth** [comment]
I think I meant:

"_Verify that when the application writes a cookie the cookie name and value length combined are not over 4096 bytes. Overly large cookies will not be stored by the browser and therefore not sent with requests, preventing the user from accessing the application._"

**Comment by elarlang** [comment]
> preventing the user from accessing the application

This is not correct either, as you can still access application. Just without this cookie being sent.

**Comment by tghosth** [comment]
I think I meant:

"_Verify that when the application writes a cookie the cookie name and value length combined are not over 4096 bytes. Overly large cookies will not be stored by the browser and therefore not sent with requests, preventing the user from using application functionality which requires that cookue._"

**Comment by elarlang** [comment]
Maybe requires > relies, but otherwise ok.

Do we have an agreement to move it to V50 or this is another discussion?

**Comment by tghosth** [comment]
Fine with moving, opened #2473

**Comment by tghosth** [comment]
Previous 5.1.8 becomes 5.1.6.
