### ISSUE TITLE
clarification for 2.3.4

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#2460]
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **2.3.4** | [ADDED] System administrators should not be able to change or choose any user's password, but rather only be able to initiate the password reset process for the user. | ✓ | ✓ | ✓ | 620 |

"should" - is it a requirement or recommendation?

If it is a recommendation - it must be moved to the recommendation list.

If it is requirement, text must be modified to positive requirement, with "must" and start with "Verify".

**Comment by randomstuff** [comment]
I think this should be a "must".

**Comment by tghosth** [comment]
Opened #2464

**Comment by elarlang** [comment]
> Must start with "Verity that"

**Comment by elarlang** [comment]
Current proposal:
> Verify that system administrators cannot change or choose any user's password, but rather can only initiate the password reset process for the user.

I think it requires further changes:
* switch negative + positive requirement to positive + negative requirement
* "system administrator" is maybe not precise, if there is UI for password reset, it is just one user with certain privileges for managing users, I would not call this user as "system administrator". So I propose "administrative user"
* add actual goal into the requirement text: administrative user do not know the password for the user after the process

**Comment by tghosth** [comment]
"_Verify that administrative users can initiate the password reset process for the user, but that this does not allow them to change or choose the user's password. This should prevent a situation where they know the user's password._"

Better?

**Comment by elarlang** [comment]
This should > This must?

**Comment by tghosth** [comment]
"_Verify that administrative users can initiate the password reset process for the user, but that this does not allow them to change or choose the user's password. This **will** prevent a situation where they know the user's password._"

**Comment by tghosth** [comment]
Is this ok @elarlang ?

**Comment by elarlang** [comment]
"will prevent" > "prevents" and PR

**Comment by tghosth** [comment]
@elarlang thanks, updated
