### ISSUE TITLE
update 6.2.9

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#2461]
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **6.2.9** | [ADDED] All cryptographic primitives MUST utilize a minimum of 128-bits of security, with exceptions only made for equipment or applications approaching end of life, where the requirement is at least 112-bits of security for all cryptography. | ✓ | ✓ | ✓ | 311 |

* the requirement text must be aligned with the rest of the document - start with "Verify that"
* MUST > must
* Is it really a level 1 requirement?

**Comment by randomstuff** [comment]
I thinks this should still be a L1 requirement. Maybe the "applications approaching end of life" conditions should be changed to "as a temporary solution with definite plans to upgrade to suitable mechanisms".

**Comment by tghosth** [comment]
I prefer that we deal with level fixes all together rather than requirement by requirement.

I feel like "as a temporary solution with definite plans to upgrade to suitable mechanisms" is giving people an excuse to say they comply when they don't. If they don't comply they need to explain why, unless this is really an EOL product.

**Comment by tghosth** [comment]
Opened #2465

**Comment by randomstuff** [comment]
I was actually intending to have a more restrictive wording than the current wording i.e. even EOL products should move to stronger cryptographic mechanisms. EOL products can be kept alive for a long time…

**Comment by elarlang** [comment]
Updated requirement:
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **6.2.9** | [ADDED] Verify that all cryptographic primitives utilize a minimum of 128-bits of security, with exceptions only made for equipment or applications approaching end of life, where the requirement is at least 112-bits of security for all cryptography. | ✓ | ✓ | ✓ | 311 |

**Comment by jmanico** [comment]
I suggest dropping the "end of life" part. That is not relevant to security, at all. Attackers will not give older applications a break. And this will make it simpler, too.

Also, bit strength changes when you move to eliptical curve cryptography.  A 256-bit ECC key provides roughly 128 bits of security. For RSA or finite field Diffie-Hellman (FFDH), achieving 128 bits of security requires a 3072-bit key.

So I politely suggest:

# | Description | L1 | L2 | L3 | CWE
-- | -- | -- | -- | -- | --
6.2.9 | [ADDED] Verify that all cryptographic primitives utilize a minimum of 128-bits of security based on the algorithm, key size, and configuration. For example, a 256-bit ECC key provides roughly 128 bits of security where RSA requires a 3072-bit key to achieve 128 bits of security. | ✓ | ✓ | ✓ | 311

**Comment by randomstuff** [comment]
Looks good to me.

**Comment by tghosth** [comment]
Opened #2482
