### ISSUE TITLE
Requirements that do not start with "Verify that"

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#2469]
In case we want every requirement to start with "Verify that", then those requirements do not do that.

* V2.1.5 Verify users can change their password.
* V2.3.4 System administrators should not be able to change or choose any user's password, but rather only be able to initiate the password reset process for the user.
  * https://github.com/OWASP/ASVS/issues/2460
* V2.5.2 Verify password hints or knowledge-based authentication (so-called "secret questions") are not present.
* V2.8.8 Ensure that generation of the time-based multi-factor OTP token is based on the server's system time and not the client's machine.
  * https://github.com/OWASP/ASVS/issues/2462
* V3.1.5 Verify the application generates a new session token on user authentication, including re-authentication, and terminates the current session token.
* V8.1.4 Verify the application can detect and alert on abnormal numbers of requests, such as by IP, user, total per hour or day, or whatever makes sense for the application.
* V50.8.2 Verify the application only uses client-side technologies which are still supported and considered secure. Examples of technologies which do not meet this requirement include NSAPI plugins, Flash, Shockwave, ActiveX, Silverlight, NACL, or client-side Java applets.

**Comment by tghosth** [comment]
Opened #2471 

I didn't deal with 2.3.4 and 2.8.8 because that will be handled separately
