### ISSUE TITLE
List of missing full stop on the end.

### ISSUE THREAD

**Issue by NocFlame** [OWASP/ASVS#247]
Using the Application Security Verification Standard
-> Both bullet items

Applying ASVS in Practice
-> Industry: Manufacturing...defense -> L3 -> Spelling error on life and sentence ends with no full stop
-> Industry: Healthcare -> Threat profile -> Link is missing closing paratesis
-> Industry: Healthcare -> L1 -> Missing full stop

V1: Architecture, design and threat modelling
Control objective -> All 3 bullet items

V3: Session Management Verification Requirements
Control objective -> First bullet item
3.12

5.10
5.17
5.21

8.1
8.13

V9: Data protection verification requirements -> Last bullet item

V10: Communications security verification requirements -> First bullet item
10.11

V11: HTTP security configuration verification requirements -> First bullet item

V13: Malicious controls verification requirements -> Last 3 bullet items

V15: Business logic verification requirements -> First bullet item

V16: Files and resources verification requirements -> First bullet item

V17: Mobile verification requirements -> First 2 bullet items

V18: Web services verification requirements -> All 3 bullet items

Following items in Appendix A also ends with no dot in the description part
The "Reason" field is mixed for all items on however the text should end
with dot or not. 
3.8
3.9
3.13
5.2
5.4
5.9
5.14
5.19
7.1
7.4
7.5
7.10
8.2
10.2
10.7
17.1 

Appendix B
Bullet FIPS 140-2
Bullet Transport Layer Security 

Appendix D
6.5.1 PCI_DSS 3.0
6.5.2 PCI_DSS 3.0 + Description
6.5.3 PCI_DSS 3.0 + Description
6.5.4 PCI_DSS 3.0 + Description
6.5.5 PCI_DSS 3.0 + Description
6.5.7 PCI_DSS 3.0 + Description
6.5.8 Only description
6.5.10 Only description

**Comment by stuartgunter** [comment]
This sounds like the kind of thing that would be better addressed with a PR. It doesn't need prior discussion, so perhaps just make the changes and submit them. I'm sure if it's just a matter of improving punctuation, grammar, etc. it can be merged without much/any discussion.

Seeing as you already know all the places where this needs work, perhaps you could make the changes instead of listing them?
