### ISSUE TITLE
Requirements for session-less apps

### ISSUE THREAD

**Issue by marpuch** [OWASP/ASVS#248]
I am currently looking on V3: Session Management Verification Requirements. I was wondering, how the requirements there address security of stateless apps that rely on - let's say - JWT tokens (which happen to be really popular right now). My understanding is - they don't. I searched through the whole ASVS 3.0.1 and did not find any points mentioning JWT.

Did I miss something? Or are the stateless apps out of the picture on purpose?

**Comment by vanderaj** [comment]
This is resolved in a2913a13c13fad386d1539c1d36ec5ee2edd5460
