### ISSUE TITLE
Early Access Issues

### ISSUE THREAD

**Issue by ossie-git** [OWASP/ASVS#249]
Hi,

Most of the content + tables in the early access version over on the main project page are messed up - https://www.owasp.org/index.php/Category:OWASP_Application_Security_Verification_Standard_Project  Only V1 and V2 render correctly.

**Comment by vanderaj** [comment]
@danielcuthbert @torsten - Please work on updating the Wiki with the replacement content. Torsten has a lot of experience with this.

**Comment by vanderaj** [comment]
Once we have an acceptably complete V2 and figured out how do we re-do the tables in earlier informative sections, I'll work with Torsten to get a re-render of the website done.

**Comment by danielcuthbert** [comment]
Closing this for now, we can open up a new one once 4.0 is ready to go.
