### ISSUE TITLE
19.10 Discouraging CDN seems unnecessary

### ISSUE THREAD

**Issue by stuartgunter** [OWASP/ASVS#251]
> 19.10: Verify that all application assets are hosted by the application, such as JavaScript libraries, CSS stylesheets and web fonts are hosted by the application rather than rely on a CDN or external provider.

Given the availability of [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity), I don't think it is necessary to discourage the use of a CDN or external provider. There are significant benefits in using a CDN that I don't think should be discounted when other security mechanisms may be available.

What do you think about modifying this along the lines of:
> 19.10 Verify that all application assets that are not hosted by the application (e.g. via a CDN or external provider), such as JavaScript libraries, CSS stylesheets and web fonts are configured to use Subresource Integrity.

**Comment by vanderaj** [comment]
Agreed. Will resolve

**Comment by vanderaj** [comment]
Please review
