### ISSUE TITLE
Alignment with OWASP Testing Guide

### ISSUE THREAD

**Issue by D00gs** [OWASP/ASVS#252]
Hi

It would be really great if ASVS aligns with the OWASP Testing guide in a similar way to what was done with the MASVS and checklist for mobile. I run an appsec program that is using the mobile standard and it has so far gone over very well with clients.

Thanks,

doogs

**Comment by danielcuthbert** [comment]
100% agree. Can you give me an example of how you think this would work best? I'm starting to work on this for the 3.1 release.

**Comment by PPS-BhaumikShah** [comment]
Let me know if you need any help. I have done some mapping already till some extent for ASVS current version.

**Comment by dyjakan** [comment]
Same as https://github.com/OWASP/ASVS/issues/269, I'll continue discussion in #269 since @danielcuthbert already provided example over there.

**Comment by tghosth** [comment]
Discussion seems to have continued in #269 so closed as duplicate.
