### ISSUE TITLE
Assessing software has achieved a verification level

### ISSUE THREAD

**Issue by mastacheata** [OWASP/ASVS#255]
I'd love to see either if or that inserted between Assessing and software.
That would make that sentence much easier to understand for people not so familiar with the english language.

Just stumbled upon this while working on the German translation and apparently someone working on the brazilian portugese version has had the same "problems" judging from the comment in crowdin.

**Comment by mastacheata** [comment]
It's the headline for page 16 in v3.1 and 3.0  and page 15 in v3.0.1

This is where I stumbled upon it:
https://crowdin.com/translate/owasp-asvs/1397/engb-de#57618

**Comment by vanderaj** [comment]
This is now called "Assessment and Certification"

Closing
