### ISSUE TITLE
Review bug bounty disclosed issues for trending vulns

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#256]
Review public disclosed bug bounties for trending vulns

In particular, race conditions.

**Comment by jmanico** [comment]
Yea these are pretty serious https://www.cyberscoop.com/shopify-bug-bounty-canada-hackerone/ do you want to add one on like

x.1.1 Verify that code that is vulnerable to race conditions is properly synchronized

?

**Comment by jmanico** [comment]
added as 4.3.3 aa13f37 and closed; please reopen if needed
