### ISSUE TITLE
V7.14 Missing anything? 

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#258]
V7.14 asks for keys to be replaceable. Are we missing anything from that control that this one might have covered? Expiry dates stored, warnings for up and coming expiry? What would help ops teams manage the expiry of key materials?

**Comment by ossie-git** [comment]
the above + a defined + tested process in place in case keys are compromised and you want to re-encrypt sensitive data (mostly for sensitive data stored on the backend as logging out users isn't a problem)

**Comment by jmanico** [comment]
clarification added f1bc123
