### ISSUE TITLE
V4.9 - Currently dupes 4.16, but needs aligning with OWASP Top 10 2017

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#259]
We need to bring 4.9 into the OWASP Top 10 2017 A5 fold, to discuss modern application architecture, where presentation layer access controls may only be done on the presentation layer. 

@jmanico @danielcuthbert I will want to discuss this with you as I think we need to get the meaning right before we gut this one. Otherwise, it's just a dupe of #181 and that's not really useful. I'd like to keep 4.16 as it's got PEP right.

**Comment by jmanico** [comment]
These are all renumbered and cleaned up, please reopen with new number if needed
