### ISSUE TITLE
Deserialization Update (5.29)

### ISSUE THREAD

**Issue by ossie-git** [OWASP/ASVS#262]
https://www.owasp.org/index.php/ASVS_V5_Input_validation_and_output_encoding

I think we can expand on 5.29 considering that Deserialization Attacks was one of the OWASP Top 10 yet only gets a single item in the ASVS.  The wording currently states:

"Verify that deserialization of untrusted data is avoided or is extensively protected when deserialization cannot be avoided."

and the References don't point to anything related to deserialization.

I think we should mention that JSON, XML and YAML aren't secure either (as highlighted in the marshalsec paper and the "Friday the 13th: JSON Attacks" Black Hat talk) unless properly configured (whitelisting) and/or a schema is used as developers will naturally pivot to these formats thinking they are not susceptible to deserialization attacks

I also think we should add references to:

OWASP Top 10 (Deserialization attacks section)

Deserialization Cheat Sheet
https://www.owasp.org/index.php/Deserialization_Cheat_Sheet

Deserialization of Untrusted Data
https://www.owasp.org/index.php/Deserialization_of_untrusted_data

**Comment by vanderaj** [comment]
I've created its own section. Please review

**Comment by jmanico** [comment]
Not sure 5.4.1 or 5.4.2 fit in that category.....

**Comment by jmanico** [comment]
This is now well well covered
