### ISSUE TITLE
"Memorized secrets"

### ISSUE THREAD

**Issue by m8urnett** [OWASP/ASVS#263]
The developer in me wants to like this term because there are multiple things that could fall into this category (password, PIN, pattern, passphrase, etc.) but I think it affects the readability as opposed to simply calling it a _password_ or even just a _secret_. The sentence structure is already quite complex without adding extra and often unnecessary adjectives. 

And besides, some things do not apply to all memorized secrets, such as in 2.7 talking about length, which certainly doesn't apply to a pattern or graphical password. 

On that same note, I think the terminology in general should move away from precise technical terms to more friendly and readable words. For example, instead of "Verify authenticators are resistant..." use "Verify the application is resistant..." I mean I do this for a living and I found the wording a bit confusing at times.

**Comment by jmanico** [comment]
I am having trouble parsing this comment. Give me more specifics please?

**Comment by m8urnett** [comment]
While I think the term (used in 0x11-V2-Authentication.md) *memorized secrets* is more accurate, I think that more friendly terminology--such as simply saying *passwords*--would make it easier to read. IMHO.

**Comment by philippederyck** [comment]
I agree that there is at least some inconsistency, along with hard-to-digest terminology.

One example is that the introductory text declares "memorized secrets" to be passwords, PINs, pictures, ..., but the first items talk about character sets and lengths. Rewording is probably preferred (I don't mind going over it if preferred)

**Comment by vanderaj** [comment]
Fixed in the latest version. Please have a look and let me know if you think it's resolved as well. @m8urnett @philippederyck

**Comment by philippederyck** [comment]
Looks good to me. Will do a more thorough pass of the chapter soon
