### ISSUE TITLE
2.23 issues

### ISSUE THREAD

**Issue by m8urnett** [OWASP/ASVS#264]
1. I don't think a number should be specified, the actual number would largely depend on what is appropriate for the organization. 

2. Instead of soft lock out, would _temporary_ lock out be more clear? 

3. Is it necessary to reveal the number of attempts left (other than maybe the last few), especially as a security requirement?

**Comment by jmanico** [comment]
I changed 2.23 to "Verify the authenticator permits a limited number of bad login attempts before temporarily locking the account, particularly where longer memorized secrets are required. " per dcdd2229e6f34a86a04e313b5de6ddc5b81271e5
