### ISSUE TITLE
2.24 and 2.25 removal

### ISSUE THREAD

**Issue by m8urnett** [OWASP/ASVS#265]
Instead of removing these, how about making them requirements? 

2.24. Verify the application does not rely on knowledge-based or secret questions for authentication.

2.25. Verify the application does not enforce a password history as a substitute for poor password policy.

**Comment by jmanico** [comment]
I made both of these changes via 0c17e4af03cb3d104c5d879b09f1dd09d7089482 and am closing this out, but we try to avoid negative rules so these might go away.
