### ISSUE TITLE
2.46 and 2.50 are duplicates

### ISSUE THREAD

**Issue by m8urnett** [OWASP/ASVS#266]
Besides, wouldn't these both be a duplicate of requiring TLS, which makes the issue irrelevant?

Also, should the authentication section even get into the transport layer stuff other than requiring TLS? 2.16, 2.43, and 2.44 are also duplicates or mostly overlap.

**Comment by jmanico** [comment]
Can you kindly split out "2.16, 2.43, and 2.44 are also duplicates or mostly overlap" into a different issue, I'll handle the 2.46 and 2.5 and then plan to close this issue out. Cool?

**Comment by jmanico** [comment]
Removed 2.5 via ed164b0c85743b26174e9c3599616e71028fb187 and closing this out.
