### ISSUE TITLE
Address command injection for IoT somehow

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#267]
Command injection is a special problem in the world of IoT. We need to do one of the following:

1) Modify 5.12 to something like: "Verify that the firmware and applications are not susceptible to OS Command Injection, or that security controls prevent OS Command Injection."

2) Move section 20 into the appendix as a separate section as a teaser to IoT ASVS

3) Drop 20 from ASVS 4.0 and make it a separate ASVS version run by the IoT OWASP working group.

20 is a big thrash since it's IoT and the rest is web. I lead toward 2 and 3.

**Comment by danielcuthbert** [comment]
I've thought long and hard on this and it's actually not the best place for IoT. I truly believe there needs to be some ISVT (IoT Security Verification Standard) for all things IoT (which is a very broad subject) but this isn't the right place. 

the more I see suggestions on how to make IoT devices secure, the more I realise how many haven't been involved in designing and producing such devices. Often the advice is well-meant but doesn't help. For example, HTTPS on web ui. On an embedded device, this isn't as easy as you think (how will user get signed CA cert?), anti-brute force (no, this would be terrible)

I'm going to be the unpopular one here and suggest we do not have IoT in the ASVS standard and rather try and help the IoT OWASP working group, which really needs it
