### ISSUE TITLE
2.16, 2.43, and 2.44 are also duplicates or mostly overlap

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#268]
From @m8urnett 

"Also, should the authentication section even get into the transport layer stuff other than requiring TLS? 2.16, 2.43, and 2.44 are also duplicates or mostly overlap."

**Comment by jmanico** [comment]
Preserving content for this thread. These are the three items Mark was talking about. I removed 2.43 and 2.44 per 477cc4a4ca075a3150600e696ca403faf0a741d2 but want to make sure we didn't lose anything that should be rolled into 2.16. I think 2.16 needs cleanup, even though it's the closest.

I am especially eager to 2.44 since strong authentication like FIDO is still resistant to phishing and phishing protecting is largely a user awareness issue and less of a technical one.

| **2.16** | Verify communication between the claimant and verifier (the primary channel in the case of an out-of-band authenticator) SHALL be via an authenticated protected channel to provide confidentiality of the authenticator output and resistance to man in the middle attacks. | ✓ | ✓ | ✓ | 4.0 | TBA |

| **2.43** | Verify the authentication system is man-in-the-middle resistant, such as mandatory use of TLS certificates | ✓ | ✓ | ✓ | 4.0 | TBA |

| **2.44** | Verify the authentication system is impersonation resistant, such as anti-phishing countermeasures or mutual authentication TLS connections. |  |  | ✓ | 4.0 | 5.2.3 |

**Comment by vanderaj** [comment]
This is done
