### ISSUE TITLE
v4 Feedback: 0x18-V11-HTTP security configuration verification requirements.md

### ISSUE THREAD

**Issue by ossie-git** [OWASP/ASVS#289]
Minor update:

11.4 "Verify that a suitable X-FRAME-OPTIONS header is in use for sites where content should not be viewed in a 3rd-party X-Frame." -> "Verify that a suitable X-Frame-Options or Content-Security-Policy: frame-ancestors header is in use for sites where content should not be embedded in a 3rd party site."

**Comment by vanderaj** [comment]
We might need to revisit this item in light of near universal support of CSP at this time.

**Comment by danielcuthbert** [comment]
Agree about CSP, let's see how that matures and what happens and adjust. Good bug, thanks
