### ISSUE TITLE
v4 Feedback: Remove IoT Section

### ISSUE THREAD

**Issue by ossie-git** [OWASP/ASVS#291]
After some thought, I think removing the IoT section from the standard and encouraging the OWASP IoT Project (https://www.owasp.org/index.php/OWASP_Internet_of_Things_Project) to re-write the IoT section + and release it as an independent publication in much the same way that the MASVS covers mobile applications would be a better approach IMHO

**Comment by scriptingxss** [comment]
I believe thats the plan for the next version. The idea is to introduce the topic for visibility being that ASVS is a flagship project, then pass it over to the IoT Project to breakdown and add maturity similar to the MASVS.

**Comment by vanderaj** [comment]
I think this is one of those times we need to look at the relationship between the main ASVS and topic areas. I would like to work with the MASVS and so on to provide a way for related efforts to use us as a baseline, and move specific things like IoT to their own project that can move faster. For now, we will be keeping it.

**Comment by vanderaj** [comment]
@danielcuthbert @jmanico

**Comment by danielcuthbert** [comment]
I agree with removing this (See https://github.com/OWASP/ASVS/issues/267). We should not try and be everything to everyone. IoT security is needed, but this is not the place

**Comment by MazeOfThoughts** [comment]
There is currently a mismatch between the "What's new in 4.0" section and the existence of the IoT section. "What's new" states that the IoT section has been retired in favor of OWASP IoT projects, but the section is still in the document. 
Seeing this issue, I believe the IoT section should be removed.

**Comment by Sjord** [comment]
I think the technical measures in the [Baseline Security Recommendations for IoT](https://www.enisa.europa.eu/publications/baseline-security-recommendations-for-iot) already provide good guidelines to develop IoT devices and test against, so there is less of a need for OWASP to set up an IoT ASVS.
