### ISSUE TITLE
Verification requirements

### ISSUE THREAD

**Issue by marcortw** [OWASP/ASVS#293]
Hi all,

This looks like an interesting project which I'd like to use for some security analyses we perform for our customers. I was already looking at it a few years ago and it's great to see how it evolved and that it has become quite mature!

There's this antique page [here](https://www.owasp.org/index.php/How_to_meet_verification_reporting_requirements) which describes a method on how to report "conformance" with the spec, but it's outdated. The current 3.0.1 PDF available on the OWASP main site basically specifies the following in regard to reporting requirements:

> A certifying organization must include in any report the scope of the verification (particularly if a key component is out of scope, such as SSO authentication), a summary of verification findings, including passed and failed tests, with clear indications of how to resolve the failed tests.

So is that really all that's required from a certifying organization in the current version or is there more to it/more available guidance?

**Comment by vanderaj** [comment]
This is a valid issue and one we will look at during the tidy up of the front informational materials.

**Comment by marcortw** [comment]
@vanderaj how far is 4.0 progressed? I saw a draft of the .docx [here](https://github.com/OWASP/ASVS/blob/master/4.0/OWASP%20Application%20Security%20Verification%20Standard%204.0-en.docx) and it looks nearly finished. If you like I could contribute a few paragraphs in the "Assessment and Certification" section. I see two main topics there:
- Methodology: nothing is yet stated in regard to the concrete testing method (e.g. pen testing vs source code review, of course only where multiple test methods are possible) and it would be good to at least explicitly state that an analyst is free to choose the method, but should indicate the method in a report.
- Reporting: I have some ideas how comparable reports could look like. Where is it possible to discuss this? Of special importance: How to handle requirements which are not applicable in a given context.

best regards,
Marco

**Comment by marcortw** [comment]
I don't have much time currently, but I'd love to. But how and where? Do you have the raw text data somewhere? To which branch? Do you have something like contribution guidelines?

**Comment by tghosth** [comment]
Hi @marcortw, the raw text is in [this folder](https://github.com/OWASP/ASVS/tree/master/4.0/en). I don't think there are any specific contribution guidelines.

**Comment by vanderaj** [comment]
@marcortw - please do the usual - fork us as a private repo, make the changes you want and create a pull request. We will look at the changes and merge. This will help us the most as we can take your changes and apply them in a few minutes. 

https://help.github.com/categories/collaborating-with-issues-and-pull-requests/

In particular, this will be helpful:
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by vanderaj** [comment]
We will need the PR by the start of next week, otherwise this will have to wait for 4.1.

**Comment by marcortw** [comment]
Ok, thanks for the hint. Hope I'll find an hour or two this weekend to contribute.

**Comment by marcortw** [comment]
@vanderaj @tghosth please have a look at the above PR. I added just a few sentences, but for my recent analyses these would have been helpful to give me basic guidance on what is acceptable in regard to testing methods and reporting non-applicability. However, I'm aware that this non-applicability thing could end up in lengthy discussions. Therefore I tried to keep it short, to at least serve as a basis for discussion.

**Comment by marcortw** [comment]
I forgot to mention that I was thinking of a larger 'reporting' section, but I can't find the time to write something at the moment. Some ides for such a section:

- Management summary requirements, including a table with numbers/list of failed, passed, non-applicable requirements (or sections)
- Definition of 'compliance' and self-attestation
- Percentage of an analysis performed with which method
- Description of the analyst(s) skills
- Effort spent on the analysis

All of these should serve the reader of a report to proof that the analysis was performed with adequate quality, accuracy and diligence (and give the author better guidance on how to reach such a goal).

**Comment by vanderaj** [comment]
Marco, I need to close off any PRs preferably today, and certainly no later than by Friday this week as we absolutely must get it fully QA'd and re-PDFd in time for its release next week. Please let us know if we should push this to 4.1, or if we are likely to have the PR this week?

**Comment by marcortw** [comment]
Hi @vanderaj. I thought that PR #446 would make it to 4.0 since it's already merged? In regard to the other ideas: I will definitely not be able to produce something useful just now. But I'm happy to contribute a bit more for 4.1 if you like. We can leave this issue open until then or you can close it for now, however you want.

**Comment by vanderaj** [comment]
Marco, I'm going to push it to 4.1. If we find that we have time before release, we might try to address it. Thank you for PR #446 - and yes, it's been incorporated.

**Comment by tghosth** [comment]
Hi @marcortw, did you have additional content you wanted to add here?

**Comment by marcortw** [comment]
Hi @tghosth, I would still love to, but can't seem to find the time for it, sorry! Is there something like a timeline for the next release? If so, I can organize myself a bit around your planning and reserve myself a day to provide a PR

**Comment by tghosth** [comment]
There is no formal timeline at the moment. The next major release is planned for 2021 but we could potentially issue another 4.0.x release before then if we had additional content.

**Comment by jmanico** [comment]
Since this is merged to the master branch I'm closing it out. If done in haste please reopen.
