### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by m8urnett** [OWASP/ASVS#296]
This item covers several very different topics, I think it should be broken apart.

Maybe something like this:

3.x Verify that session tokens are only stored in temporary session cookies rather than persistent cookies. (L3)

3.x Verify that cookies limit scope to a specific path and make use of the SameSite and, for compatibility with older browsers, Domain attributes.

3.x Verify the application always transmits cookies over TLS by setting the Secure attribute.

3.x Verify that cookies set the HTTPOnly attribute to prevent script access to cookie contents.

The first one also brings up the issue with 3.3 and 3.4, because setting an expiration will change a session cookie into a persistent cookie, which is not something you would want in a sensitive application such as banking. 

Also I feel like something should be said about storing actual passwords in cookies. I want to think that shouldn't have to be said but I'm afraid it does.

**Comment by vanderaj** [comment]
Please check the current text and see if we cover your points. The main one that is missing is the storage of passwords in cookies. let me know if I'm close.

**Comment by vanderaj** [comment]
Hi there, I'm closing this out as I'm pretty sure I've covered this off. If you disagree, please re-open the ticket.
