### ISSUE TITLE
Authentication + SSO

### ISSUE THREAD

**Issue by ossie-git** [OWASP/ASVS#297]
I think we could add something related to the subtle issues highlighted in this research (https://www.cs.uic.edu/~polakis/papers/sso-usenix18.pdf and summarized here - https://twitter.com/jpolakis/status/1046086964410294272)

In their research, an attacker obtaining the account token to an SSO provider such as Facebook could then use it to obtain access to a user's account on a 3rd party site even if the user doesn't use Facebook / SSO provider to access their account on this 3rd party site.

**Comment by vanderaj** [comment]
I've added text for this in 2.1.1 in the latest text. Please confirm.
