### ISSUE TITLE
v4 feedback: 0x13-V5-Input-Validation.md

### ISSUE THREAD

**Issue by LewisArdern** [OWASP/ASVS#299]
Hey ASVS,

After speaking briefly on Twitter to Jim regarding this section in particular, I saw some small improvements that could be improved to the document.

###  Improvements 
* Changes to lower case security issues such as cross site scripting to Cross-Site Scripting (XSS)
* Fix Server Side to Server-Side
* Add more examples for 'auto-escaping' AngularJS is now outdated, so in favour of angular 
* Make .val explicit that it's from JQuery to not confuse people 

### Start a conversation

* Sanitization

In this document we discuss Sanitization, but the title states Input validation and Encoding. I'm fine with the content that exists, there is nothing at the moment in my mind if we need a new section, but do we deem Sanitization as Input validation?  My recommendation would be to add it to the title of the text, or at least make it clear this is what's in this section also.

**Comment by LewisArdern** [comment]
I Also saw that 5.15 mentions:

> 
Verify that all string variables placed into HTML or other web client code are either properly contextually encoded manually, or utilize templates that automatically contextually encode to ensure the application is not susceptible to reflected, stored or DOM Cross-Site Scripting (XSS) attacks.
--

Do we want to tell developers to manually encode all HTML output? That sounds like a bit like shoot yourself in the food

**Comment by LewisArdern** [comment]
Also left some comments on the commit, don't know if they will be useful. 

The only thing i see quite more apparent that in the external references, its only XSS related ones; we should probably have some good external content that OWASP doesn't already cover for the other issues such as SQLi, SSRF e.g the SSRF bible.... if that's applicable for a defender. The references should be an extension for developers and security people to understand the context for prevention or how to mitigate with X tool

**Comment by jmanico** [comment]
I committed your change and changed the title. Check it out! If you want anything more changed please add a new comment or change request. :)
