### ISSUE TITLE
Please update API security to include coverage of API keys

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#301]
See the RESTful security cheat sheet on API security topics. Many of the topics in this page would make a welcome update to some of this section as well. 

"Public REST services without access control run the risk of being farmed leading to excessive bills for bandwidth or compute cycles. API keys can be used to mitigate this risk. They are also often used by organisation to monetize APIs; instead of blocking high-frequency calls, clients are given access in accordance to a purchased access plan.

API keys can reduce the impact of denial-of-service attacks. However, when they are issued to third-party clients, they are relatively easy to compromise.

- Require API keys for every request to the protected endpoint.
- Return 429 "Too Many Requests" HTTP response code if requests are coming in too quickly.
- Revoke the API key if the client violates the usage agreement.
- Do not rely exclusively on API keys to protect sensitive, critical or high-value resources."

https://www.owasp.org/index.php/REST_Security_Cheat_Sheet#API_Keys

**Comment by danielcuthbert** [comment]
Agree and on this

**Comment by danielcuthbert** [comment]
Added 

If no access control is present, verify that the REST service isn't susceptible to excessive calls, which could lead to increased overhead or CPU/bandwidth bills. A potential solution could be API keys, or returning error code 429 "Too Many Requests" if requests are excessive

We do need to reword this, API keys aren't the saviour for all issues, but they do help. Not sure on the best way to word this, or even if it needs to be broken down further. 

then, do we add Cross-Site WebSocket Hijacking (CSWSH)? would 18.8 cover this?
