### ISSUE TITLE
2.1.10 Restricted authenticators

### ISSUE THREAD

**Issue by m8urnett** [OWASP/ASVS#306]
I don't think I agree with this verification--I think the issue in real life (and even in NIST SP 800-63B) is much more nuanced and to have such a hard requirement. 

The main problem is that there aren't enough alternatives in place so what would be the recommendation? 

I think this falls under one of those things where we know it sucks but we don't have a better way of doing it. NIST tried to address it as something where both parties are aware of the risk and some time in the future we are going to say never do it, but right now go ahead because we don't know what to do about it either. 

So there are several places where we use email or sms in authentication:

- As a primary means of authentication
- As a secondary means of authentication for 2SV (or when OTP or hardware not available)
- As a secondary means in case of unidentified computer or suspicious activity
- To reset a password
- For approval (or soft re-authentication) for sensitive account actions

I think what we want to say is that we should never rely on restricted authenticators for primary authentication (although we have big sites like Tumblr and Facebook doing just that). 

We know that it's not the best choice for 2SV or password recovery, but it is an acceptable risk in many cases, especially when combined with other soft authentication and anti-automation controls. But it might not be the best choice if some other risk factor is in play, such as a new IP address for the login, after many failed login attempts, etc. We also know our bank shouldn't be doing this. 

I guess my point is that this is quite subjective and maybe way too big for a single verification. How about "Verify the appropriate use of restricted authentication factors such as email and sms"?

**Comment by tghosth** [comment]
Hi @m8urnett, do you think you could prepare a PR with some suggested wording?

**Comment by tghosth** [comment]
Hi @m8urnett do you think will be able to look at this before we want to close the 4.0 version at the end of Feb?

**Comment by m8urnett** [comment]
I'll take a look at it tomorrow.
