### ISSUE TITLE
Add notify activity via email/SMS to L2/L3

### ISSUE THREAD

**Issue by Shaked** [OWASP/ASVS#311]
I'd add a L3 section (at least) to notify the user via email/SMS about activity in his own account even if he might know about it. 

In case it's too much, a daily notification would be good enough (L2).

**Comment by danielcuthbert** [comment]
Can you elaborate further? would this be for activity such as 'you've logged in from X'? 
My worry would be how this might be abused, say in a phishing attempt. What value does it bring?

**Comment by Shaked** [comment]
Once a user's profile is hacked, it takes long time to figure that out while the users themselves can prevent it (by changing their password, blocking and logging out other sessions, informing the company). 

When it comes to sensitive information, it might be very helpful. Also, it might make attackers assume that they shouldn't log-in "just like that" as it might switch of the alarm (notification). 

I haven't thought about phishing attempts. Maybe it should be a bit more sophisticated where the user receives a notification with a predefined secret token which in that case can help knowing if they were a victim of phishing or not.

**Comment by Shaked** [comment]
I agree that a token might be complex. I'd start with that and then maybe come up with a better idea.

Just to make sure - the difference between multiple sessions to my idea is that you might not be logged in at the same moment or maybe for awhile (most people don't connect to their health care service every day). For these reasons (and probably more), it is important to notify the user somehow (SMS/email/verified account) that their account was active on X date.
