### ISSUE TITLE
V2: Authentication Verification Requirements - Specific link to NIST section

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#315]
Could the start of this section (and subsequent sections) be specific that the NIST section links are for sp800-63**b** and maybe even link to the start of the relevant section (e.g. https://pages.nist.gov/800-63-3/sp800-63b.html#5-authenticator-and-verifier-requirements)

**Comment by danielcuthbert** [comment]
Good idea, amended and will sort once NIST is back :(
