### ISSUE TITLE
Duplicates in V18

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#334]
- Is 18.2 "Verify that suitable generic error messages are returned when in production mode, so as to not leak sensitive debug information." a duplicate of 8.1 "Verify that the application does not output error messages or stack traces containing sensitive data that could assist an attacker, including session id, software/framework versions and personal information."?
- Are 18.5 "Verify that all received input meets service type/length/range and format." and 18.6 "Verify that all received input, before processed, is sanitised accordingly to ensure it is safe to handle." duplicates of controls in V5 Input Validation such as the 5.1.x section?
- Is 18.7 "Verify that logging is performed for all security-related events." a duplicate of 8.3 "Verify that the application logs security relevant events including successful and failed authentication events, access control failures and input validation failures."?

**Comment by jmanico** [comment]
duplicates removed 3a572f1
