### ISSUE TITLE
18.4 - XML/JSON schema - really L1?

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#335]
> Verify that XML or JSON schema is in place and verified before accepting input.	

I am not sure how many frameworks really support strict XML/JSON schema validation without hassle. Sounds like the sort of thing you would need an API gateway or WAF to do easily. I assume that other controls (e.g. 18.5) would cover the need for validation of the values within the schema so I would consider raising this to L2 or L3.

**Comment by jmanico** [comment]
I think this is really basic API security and wish to leave it as L1 to push the envelope. This is REALLY basics security controls and most frameworks integrate it anyhow...
