### ISSUE TITLE
18.11 is a little unclear

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#336]
So I *think* @vanderaj added 18.11 "Verify that alternative and less secure access paths do not exist."

Is there any way a little more detail could be added to this to make it clearer what it is specifically referring to?

**Comment by tghosth** [comment]
This is now 18.8.

**Comment by danielcuthbert** [comment]
Agree with this but also not sure it makes any sense. I've replaced the text with sensitive info in URLS but do think we need to spend more time on this overall. The API side is vital we get right, and right now it is missing a lot.

**Comment by TheDauntless** [comment]
Are there currently style guides for the issues? In my opinion, positive sentences are better, but at first sight, the ASVS uses both positive and negative sentences.

For example, I would propose:
> Verify that all access paths to a resource provide the same level of security

**Comment by jmanico** [comment]
This is resolved for 18.8 please open new ticket if other issues with 18x are outstanding.
