### ISSUE TITLE
Are 13.1 and 19.4 duplicates or is that intentional?

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#343]
13.1 "Verify all malicious activity is adequately sandboxed, containerized or isolated to delay and deter attackers from attacking other applications."

19.4 "Verify application deployments are adequately sandboxed, containerized or isolated to delay and deter attackers from attacking other applications."

**Comment by vanderaj** [comment]
This is a good point. As long as 19.4 has sufficient level coverage, we can de-dupe.

**Comment by vanderaj** [comment]
De-duped.
