### ISSUE TITLE
Final 4.0 release checklist

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#357]
As I go along, I am noticing things that we probably only want to fix just before release so I will note them here, feel free to add :)

|Task|Assignee|Status|
 | --- | --- | -- |
|"_Pass over the entire thing to weed out useless controls and those that are un-developable or un-testable or are compound tests. An ASVS item should be atomic and not compound. It should be specific as to an action for (dev, testers, ops, security folks, auditors)_" - Andrew| | Complete |
|Full check of numbering (as requested in #298)| | Complete |
|Check heading formatting consistency| | Complete |
|Add CWE numbers (as requested in #67) | | Complete |
|<del>Check requirement number formatting consistency| @tghosth | Complete |
|Check page layout consistency| | Complete |
|Check spelling and grammar| | Complete |
|Check that all Top 10 Risks are L2, assuming that ratings are based on [this comment](https://github.com/OWASP/ASVS/issues/350#issuecomment-453808135). | | Complete |
|Check that all Top Ten Proactive controls are L2, assuming that ratings are based on [this comment](https://github.com/OWASP/ASVS/issues/350#issuecomment-453808135), see #322 for mapping. | | Complete |
|Move the IoT controls to an Appendix as per [this comment](https://github.com/OWASP/ASVS/pull/369#issuecomment-455332384). | | Complete |

**Comment by mastacheata** [comment]
> TBD - Need to re-do case studies / applicability.

In [Using the ASVS](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x03-Using-ASVS.md)

**Comment by vanderaj** [comment]
Suggest we leave Proactive Controls for now - many ended up in L1 due to being pen-testable. I'm going to mark them Complete.

**Comment by vanderaj** [comment]
Release candidate 4.0 released. I created and paginated 4.0 PDF as well.

**Comment by tghosth** [comment]
That L2 thing was when we were thinking about a different level rating method so I think that is fine now.

Amazing work getting this all pushed through!
