### ISSUE TITLE
Should ASVS include guidelines to mitigate effects of a security breach? (Backups etc.)

### ISSUE THREAD

**Issue by mastacheata** [OWASP/ASVS#360]
The ASVS already includes some guidelines that would only take effect if a security breach or mishap has happened before, like not storing plain text passwords in the sourcecode. (Users shouldn't be able to see the sourcecode anyway, so this is a non-issue unless you already had a security problem)

I was wondering if backups should be included in the scope of the ASVS as well?

**Comment by tghosth** [comment]
Sounds like it should be in [V9](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x16-V9-Data-Protection.md). Fancy creating a PR with some calls?

**Comment by tghosth** [comment]
@mastacheata can this now be closed?

**Comment by mastacheata** [comment]
Unless anyone got other ideas about this more generic suggestion, sure.
Backups is the only thing that comes to my mind that isn't already covered as a security thing (i.e. protecting personal data, not storing plaintext passwords, having logs of all authentication decisions etc.)

**Comment by tghosth** [comment]
Ok so I think I will close for now, thanks for your help :)
If you have any other ideas, feel free to open a PR!
