### ISSUE TITLE
Isolation of concerns

### ISSUE THREAD

**Issue by mastacheata** [OWASP/ASVS#361]
I think isolation of concerns should be discussed in the architecture section.
That could be either within the application (i.e. separate display related controls and logic from business logic) or even as separate applications (i.e. frontend SPA and backend API service).

But I'm not really sure if that's just my personal experience and the way I like things to be or if this is actually a relevant security concern. (It can definitely enhance security if you separate those things, but only if implemented correctly)

**Comment by mastacheata** [comment]
Or do you people think this is already coverd by V19.1.2 and V19.1.3?

**Comment by tghosth** [comment]
I think this makes sense although I don't think we would want to be too specific, can you draft a PR?

**Comment by danielcuthbert** [comment]
Agree with this, would love to see a PR please
