### ISSUE TITLE
"TBD - Need to re-do case studies / applicability." in 0x03-Using-ASVS.md

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#367]
As @mastacheata pointed out, there is a note `TBD - Need to re-do case studies / applicability` in the [0x03-Using-ASVS.md](https://github.com/OWASP/ASVS/blob/2bdfdb9b216c3e96ad9e30da337be617282be0dd/4.0/en/0x03-Using-ASVS.md#applying-asvs-in-practice) file which should be resolved.

**Comment by danielcuthbert** [comment]
Have reached out to the community here.

**Comment by vanderaj** [comment]
We are going to have to fix this on the wiki post release. We do not have any new case studies. I would suggest someone take the case studies from 3.0 and put them on the Wiki and that'll have to do for 4.0. We will come back and revisit this in 4.1.

**Comment by takaharuogasa** [comment]
I am researching the real world ASVS use cases/stories for my local chapter meeting talk. I will put some replies already got through the ML. Hope more will come:)

**Comment by takaharuogasa** [comment]
From Matthew Hackling (@mhackling)
Drive pen test scope and test cases.. drive security requirements for designs help Populate an ISO27034 organisational normative framework aka requirements library etc.

**Comment by takaharuogasa** [comment]
From: Dominique Righetto 
I heavily use it for code review and, as a complementaty checklist, when I perform web application vulnerability assessments missions.

**Comment by takaharuogasa** [comment]
From: Giovanni Cruz
In our last OWASP Latam Tour Bogotá 2019 we made a training totally based on ASVS, we create all the content with a vulnerable platform, to our training mainly assist developers, and we got a great feedback, because in some way we try to show them how to use it and what levels of security they might want to achieve based on some standard.

**Comment by takaharuogasa** [comment]
From: Matt Tesauro
OWASP Defectdojo has built in ASVS support https://www.defectdojo.org/

**Comment by takaharuogasa** [comment]
From: @FluxReiners
A few weeks after ASVS 4 release, RIPS added support for it
https://blog.ripstech.com/2019/rips-3.1-adds-teamcity-ldap-jsp-support/

**Comment by takaharuogasa** [comment]
From: Sebastien Gioria
For some customers, I derivate it to make it a mandatory requirements to perform secure design and coding.

**Comment by takaharuogasa** [comment]
From: Riotaro Okada
Case 1:
Recent years I have observed some banks in Japan included ASVS into
their RFP for security testing services, as their mandatory
requirement.
They wanted proposals which security vendors would fit appropriate ASVS levels.

Case 2:
A local software vendor in Japan sells SFA related packages received
customer criteria to check whether their products would fit ASVS, and
which levels the product aligned.  (It was a good start for the vendor
to introduce secure development and verifications into their teams ;-)

**Comment by takaharuogasa** [comment]
From: John Patrick Lita
I use this and integrate this in our CI/CD activity
