### ISSUE TITLE
generate_document.sh error

### ISSUE THREAD

**Issue by hasousa** [OWASP/ASVS#368]
When running the generate_document.sh an error shows up:
"Generating OWASP ASVS 4.0 (en)...--reference-docx has been removed. Use --reference-doc instead.
Try pandoc.exe --help for more information"

Changing the line
pandoc -s -f markdown_github **--reference-docx**=../templates/reference.docx --columns 10000 -t docx -o "../OWASP Application Security Verification Standard 4.0-$1.docx" *.md

to 
pandoc -s -f markdown_github **--reference-doc**=../templates/reference.docx --columns 10000 -t docx -o "../OWASP Application Security Verification Standard 4.0-$1.docx" *.md

The file was created successfully.

**Comment by tghosth** [comment]
Thanks, addressed by #375
