### ISSUE TITLE
PCI Software Security Standard and ASVS 4.0

### ISSUE THREAD

**Issue by danielcuthbert** [OWASP/ASVS#378]
Oleg Gryb @oleggryb tweeted about the a new PCI Software Security Standard that has been [published](https://blog.pcisecuritystandards.org/just-published-new-pci-software-security-standards). It will eventually replace PA-DSS, and he commented "it's similar to #ASVS. We might need to think about bridging these two"

Sadly the new standard doesn't reference ASVS at all, which I feel is a mistake. Yes, as Oleg said, PCI is mandatory, but that doesn't mean it automatically makes it good. There is no doubt there is a need for such a standard as the new PCI SSS, I but worry that rather than working together and helping make an already used and acknowledged standard, such as the ASVS, even better for payment systems, we are working against each other, for what is in essence, the same goal.

So with that in mind, Oleg and I talked and he raised a possible way we can help:

> Think of it from a PCI assessor PoV who needs to verify a quality of e.g. security testing. He or she gets evidences like 3rd party pen test results, internal company's pen test results, static code analysis results (again could be internal or external), and tries to understand if they are good or not. How do they evaluate a quality of all that? That's a qs that we're trying to answer recently. It would be nice to have a prescriptive guidance.

How do we ensure the forthcoming 4.0 release does this? Is there something we can do to ensure more assessors leverage the ASVS?

**Comment by vanderaj** [comment]
As this new standard becomes mandatory in 2020 or so, I would suggest we push this for 4.1, and work with PCI on closer integration. I would suggest that we should probably encourage a mapping for 4.0 against this new standard, and I'm happy to include it if it can be done before we ship, but closer integration is definitely post 4.0. 

Thoughts? I'm going to push the milestone to 4.1. If it can be done earlier, great, if not, we plan for the next release.

**Comment by danielcuthbert** [comment]
Closing this for now

**Comment by cmlh** [comment]
[Secure Software Requirements and Assessment Procedures v1.1 (April 2021)](https://www.pcisecuritystandards.org/documents/PCI-Secure-Software-Standard-v1_1.pdf) is a minor release.

[Transition to Version 1.1 for New Secure SLC and Secure Software Submissions](https://blog.pcisecuritystandards.org/transition-to-version-1.1-for-new-secure-slc-and-secure-software-submissions) was published on 30 July 2021
