### ISSUE TITLE
18.5 - WS-I/SOAP - Replace with generic rule for using HTTPS?

### ISSUE THREAD

**Issue by mastacheata** [OWASP/ASVS#379]
The WS-Interop group disbanded in 2010 and joined OASIS.   
If you look at the OASIS page linked from WS-i.org, it says the WS-I project is done and all but one profile have been transfered to ISO standards. However they don't tell **which** ISO standards.  
Does anyone know? And did they add anything there that's not part of WS-Interop Basic 2.0?

If the only security requirement of WS-I Basic Profile 2.0 is "use HTTPS", can't we just use that as the rule in ASVS instead of pointing people to a standard that apparently no longer exists?
That also has the benefit of not being tied to SOAP. REST and GraphQL and *-RPC and who knows what should be using HTTPS in 2019 as well.

**Comment by tghosth** [comment]
So the [basic profile](http://ws-i.org/profiles/basicprofile-2.0-2010-11-09.html) seems to require a variety of things other than just TLS so I don't know if that can just be replaced.

Unfortunately, I don't know enough about SOAP specs to know what the best course of action should be.

**Comment by mastacheata** [comment]
The basic profile requires a bunch of things, but the security section only explains in detail how to secure a SOAP API using HTTPS. I guess that's also the reason why the ASVS says implementing WS-I is basically just HTTPS.
The rest of the basic profile is just about how to design a SOAP API so it works with other XML-based standards.

**Comment by jmanico** [comment]
SOAP is dead, can we just drop it from the standard?

**Comment by tghosth** [comment]
Sounds good to me, 

>If the only security requirement of WS-I Basic Profile 2.0 is "use HTTPS", can't we just use that as the rule in ASVS instead of pointing people to a standard that apparently no longer exists?
> That also has the benefit of not being tied to SOAP. REST and GraphQL and *-RPC and who knows what should be using HTTPS in 2019 as well.

@mastacheata would you be able to create a PR for this?

**Comment by jmanico** [comment]
We already have HTTPS rules elsewhere. It’s assumed for all web and APi dev. Perhaps just wipe this requirement?

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805
