### ISSUE TITLE
V4 Alignment with NIST?

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#382]
Hi @vanderaj, in [V2](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#control-objective) it says that [V4: Access Control](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x12-V4-Access-Control.md) is aligned with NIST but I see no evidence of this in V4.

Does this mean that V4 still needs aligning or that it will not be aligned?

**Comment by danielcuthbert** [comment]
We still need to align it https://nvd.nist.gov/800-53/Rev4/control/IA-2. Ill take this

**Comment by vanderaj** [comment]
ping. Do we push this to post 4.0?

**Comment by vanderaj** [comment]
Fixed with latesst push
