### ISSUE TITLE
V19 - Control objective - User initiated changes not reflected in requirements

### ISSUE THREAD

**Issue by mastacheata** [OWASP/ASVS#383]
The third control objective in V19 talks about user initiated changes, but no requirement even touches that topic.
This is what the control objective says;
> Sufficient hardening that user initiated changes to default configuration do not unnecessarily expose or create security weaknesses or flaws to underlying systems.

None of the requirements talk about changing configurations at all. This control objective looks like it's targeting open source software or libraries that are going to be reused. I don't think the term user is sufficiently defined in this case. The actual end user is not supposed to change system configuration on a web app at all, right?
This objective doesn't make any sense when user is referring to developers, sysadmins or other people involved with managing/creating the app.
Especially since there is also no definition of what a default config would be in that scenario and how it would differ from the final configuration used. 

Anyone of the core maintainers remember what this was supposed to mean?

**Comment by tghosth** [comment]
I think the point here is the hardening such that even if configuration changes are made to the application, the hardening controls reduce the likelihood of anything bad happening. The requirements themselves are about those hardening measures.

**Comment by ronperris** [comment]
@mastacheata 

Great points, I was also puzzled by that bullet, but let me attempt to defend it. It seems that at least one requirement is related to the bullet. `19.3.1 Verify that all components are up to date with secure or hardened configuration(s) and version(s), preferably using a dependency checker during build or compile time.`

Consider these examples of `hardened configuration`:
An application component should enable TLS when connecting to its database. This is often a configuration  flag/option when connecting via library code.

An application component should disable inline scripts for SVGs. Most libraries take this as an option.

An application component should remove any scripts from HTML produced by interpeting Markdown. Again library code exposes this as an option.

It shouldn't be possible for a normal user of the application to allow scripts in SVG or Markdown, and/or disable TLS when using the application components.

**Comment by vanderaj** [comment]
TLS is covered in Secure Communications. 
Please work on CWE linkages.
