### ISSUE TITLE
Mapping to BSI-IT-Grundschutz Baustein Webanwendungen

### ISSUE THREAD

**Issue by mastacheata** [OWASP/ASVS#384]
Not sure if other International / European states have similar IT-Security standards, but in Germany we have the BSI IT-Grundschutz, which is plugged on top of ISO27001 (and is also considered one of the standards that are replaced by the ISO 27000 family alongside the british one)

What makes the German concept so special is that they provide a catalogue of requirements/requirement blocks.
You first pick those requirements / blocks that fit your IT-System and then perform an audit via ISO27001 and the requirements you picked from the catalogue.

Block 5.21 of that catalogue is about web applications and pretty much is an extended version of the OWASP Top10 / SAN&CWE Top 25.

I'd find it quite interesting to build a mapping for that catalogue in addition to the PCI-DSS.
And maybe someone from elsewhere around the globe could find similar documents produced by their local institutions that look like they could be mapped to ASVS requirements.

Although: I'm not sure if this would be of enough interest to include in the actual ASVS document or if it would be better to suggest a separate document or Wiki page for this (and maybe other local mappings).

You can find the Block for Webapps over here (sorry, but only available in German for now): https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Grundschutz/Download/Vorabversionen/Baustein_Webanwendungen.pdf?__blob=publicationFile&v=1

Any feedback would be highly welcome. If this doesn't fit the scope for the final ASVS document, please suggest a route how I (and hopefully some other Germans would join in for compiling the mapping) could have that published by OWASP? Maybe the Wiki? Maybe a separate document to include multiple mappings to local standards?

**Comment by vanderaj** [comment]
I'm with Dan - we're rapidly running out of time. @mastacheata if you can provide an appendix via a pull request in the next week or so, happy to consider it, or would it work in the WIki? But otherwise, we might need to push this to the next release.

**Comment by mastacheata** [comment]
I'm open to either idea. Just came across this as part of my master thesis.
I'll be glad to work on that, but can't really tell if I can get this ready by next week. (have to prepare for the oral exam part of my thesis on Wednesday)

**Comment by hljupkij** [comment]
There is also a requirement list from BSI for [webserver](https://www.bsi.bund.de/DE/Themen/ITGrundschutz/ITGrundschutzKompendium/bausteine/APP/APP_3_2_Webserver.html?nn=10134826#doc10095776bodyText13) and for [webapplication](https://www.bsi.bund.de/DE/Themen/ITGrundschutz/ITGrundschutzKompendium/bausteine/APP/APP_3_1_Webanwendungen.html?nn=10134826#doc10095904bodyText14).

**Comment by tghosth** [comment]
Hi, @mastacheata is this something you are interested in doing?

**Comment by mastacheata** [comment]
sure, I just didn't have much time in the last few months.


I'll look into it and see if I can get this started before summer.




I'm sorry for suggesting this and not getting more involved right away. This idea came about when I was in the final stages of my masters thesis on applying the ASVS in practice. I finished the thesis in February and just started a new job in April, so life was and still is a bit busy this year.




Regards


Benedikt Bauer







On Sun, May 19, 2019 at 7:23 PM +0200, "Josh Grossman" <notifications@github.com> wrote:












Hi, @mastacheata is this something you are interested in doing?

**Comment by tghosth** [comment]
No problem at all, I'll leave the issue open so we don't forget it and then when you get time you can look at it :)

**Comment by sanmai-NL** [comment]
@mastacheata Are you still considering working on this?

**Comment by danielcuthbert** [comment]
We are working towards version 5.0 and closing issues that don't relate to bugs. We will create a new document that explains mappings and how they might work with the ASVS.
