### ISSUE TITLE
More v4 V2 - Authentication Feedback

### ISSUE THREAD

**Issue by ossie-git** [OWASP/ASVS#385]
I've been really busy so I haven't been able to go through the updates or even reply to feedback on previous issues I brought up.  I was just looking at the latest version of V2 and I think some points really do need to be addressed if we want the standard to be more widely adopted.

Here's a quick litmus test.  Take V2 and share it with any developer or security professional you know.  Ask them for candid feedback.  I'm betting a lot of people will be puzzled over the terminology and the requirements.  The other sections are I think a lot easier to understand largely due to the lack of NIST-like language.

The reason getting V2 right is critical is that:

- it's the 2nd requirement and is one that all applications have to comply with
- if readers find it ambiguous or confusing, they won't bother reading the rest of the standard

Off the bat, terms that are used a lot should be defined at the beginning when introducing the topic.  It's better than someone starting to read, not understanding the title (what is an authenticator?) and having to jump to the end of section to understand what the topic even means.  Here's a definition you can use for authenticator:

"An authenticator is a way to prove to a system or application that you are who you claim to be.  For example, this can be a password, a numeric PIN, a bearer token, a one-time password, etc."

V2 I think has a number of problems including:

- terminology
  - the language is too rigid and NIST-like and some of the terms won't make sense unless you've read NIST and are familiar with OAuth2.  The very first requirement (2.1.1) requires that you understand what an authenticator is and what an Identity Provider and Relying Parties are.  Someone who's read NIST and understands OAuth won't have a hard time understanding them, but the vast majority of people reading the standard will scratch their heads, especially if they are still at L1.  Also, why are we talking about physical authenticator right off the bat?  Most systems at the L1 level and even at L2 won't have physical authenticators.
- re-order by requirement levels
  - I think it makes more sense to have all the items related to L1 at the very top instead of each sub-section instead of the reader having to jump from 2.1.1, 2.1.2 and then to 2.1.8 to cover L1
  - why as a reader am I reading about biometrics at 2.1.3?  Sure it makes sense for L3, but it would make more sense for us to provide L1 requirements at the beginning of each sub-section with L3 at the end
- ambiguity
  - "Verify that no more than 100 failed attempts is possible on a single account".  In what time period?  Also, why isn't black listing the top X leaked passwords an option for L1 apps?  Also, what are "risk-based restrictions" (I can guess what you mean but don't assume that others will)?
  - what is a "restricted authenticator"?  Why not just use the term insecure or weak authenticators.  Someone who isn't familiar with NIST terminology would have to Google to look it up (a Google search returns only 71 hits for the phrase - all by NIST).  Also, email and SMS are channels, not "restricted authenticators".  OTPs using SMS are "restricted authenticators".   Also, why is this L1?  Finally, unless I missed something, an OTP using email isn't mentioned as a "restricted authenticator" - https://pages.nist.gov/800-63-FAQ/#q-b1
- why are there so many L1 requirements?
  - do we seriously think that an L1 application should support U2F or FIDO tokens?  Really?  Same goes for 2.3.4 and the out of band verifier requirements + V2.10
- the order of the sub-sections is confusing to readers
  - Why are they reading about rate limiting before they even know anything about the actual password requirements?  I understand the overall reasoning but I think we should either:
    - explain this in V2's introduction 
    - re-order the sections
- "Memorized secrets are not sufficient to protect against today's threats. ... The ASVS Leadership Team strongly feels that it is essential to start the process of universal multi-factor authentication, as it defeats the most common attacks against passwords. Therefore, we have set multi-factor authentication as a baseline L1 requirement."
  - I don't really see this position as being constructive + it defeats the definition of L1 highlighted in the beginning (Opportunistic).  
  - The overwhelming majority of applications are perfectly fine with just a strong password that isn't in the 1M most commonly leaked passwords + rate limiting login attempts + secure transit. Targeted attacks are different and 2FA can still be defeated in targeted attacks
  - Funnily enough, this requirement isn't actually mentioned as a requirement in V2 :D

The above are just a few quick comments on section V2.  I didn't have time to go through all of them.

**Comment by jmanico** [comment]
I think this is a fair comment. At the very least I think we should do a little wordsmithing and make the v2 requirements more readable.

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by vanderaj** [comment]
As always, a very insightful comment. I'll take this on.

**Comment by m8urnett** [comment]
Very much the same complaints I have had with that section.

**Comment by vanderaj** [comment]
The ordering of sections is such that we need to have them grouped by activity as often these are done by different groups (IAM, monitoring, etc). I do agree that there are too many L1 things. Let me go over this in detail and make a change.

**Comment by vanderaj** [comment]
@ossie-git I've taken on board as much feedback as I could here. I've re-worded the introductory text. 
I've worked on making the terminology for all L1 controls much easier to understand and most of the L2 controls. I've removed most L1 controls unless they can be pen-tested or are about passwords. I've re-ordered to make passwords first, and then everything else in a suitable order that moves up the complexity pathway. I've made all biometric items L3 (unless they also cover plain MFA), I've fixed the 100 attempts issue. I've made restricted much less prominent, replacing it with what I meant. I've de-duped again, removing about 2 items. I've re-ordered each section to be L1/L2/L3 -> L2/L3 -> L3. I want to keep the grouping so that folks who only care about passwords only have ~ 12-15 items to comply with. 

@ossie-git @jmanico @danielcuthbert @tghosth @m8urnett please review as I think this is very close to final V2.

**Comment by ossie-git** [comment]
Hi Andrew,

Had a look at V2 - Authentication.  It's much much better now IMHO.  Well done.

Just a few pending comments:

"For example, NIST 800-63 considers usernames and knowledge based authentication (KBA) as public information, SMS and email notifications as insecure, and passwords as pre-breached. This reality renders knowledge based authenticators, SMS and email recovery, password history, complexity, and rotation controls useless." -> My $0.02 is that this is a little sensationalist.  Strong passwords are still a powerful deterrent, especially when combined with blacklisting commonly breached passwords, rate limiting and safe password storage (PBKDF2, etc.).  I'd recommend changing this to say that passwords alone are not secure anymore.  Instead, they should be combined with other controls such as rate limiting, blacklisting the top 10K, etc. known passwords or moving to MFA.

2.1.10 - means all current PCI-compliant web apps can never make it to L1

2.1.12 - not sure why this is required

V2.2 General Authenticator Requirements - just add the definition of authenticator as the first line of this section so readers don't have to jump to the terminology just to understand the section title.  You did this is in V2.3.

"Applications should plan a roadmap that does not require the use of email or SMS." -> ... "for authentication-related activities."

2.2.1 - Fun fact:  This requirement is basically impossible to implement in serverless environments such as AWS Lambda.  You can only do rate limiting once a user logs in and you provide them with an API usage plan.  Even with AWS's WAF, rate limiting only kicks in after 2000 requests are sent

V2.4: "This section cannot be penetration tested, so controls are not marked as L1. However, this section is of vital importance to the security of credentials if they are stolen, so if forking the ASVS for an architecture or coding guideline or source code review chceklist, please place these controls back to L1 in your private version."  - I really think that not marking something as L1 because it is not pen-testable isn't the right direction.  If someone glosses over this section (or depends on an Excel sheet or other tool that just copies them as is), then they would be compliant without having any credential storage requirements at L1.  Also, if you go down this path, then review the entire document and you'll end up removing a lot of items.  For example, all the L1 items in the Architecture section (V1), logging (V7) and items such as 3.3.2 (pen tests are shorter than 30 days), etc. I made a list of these in a previous issue I raised.  Let's not hack the standard just to try to be pen-testable.  In fact, we want to drive developers and security teams to understand that pen-testing alone will never give them the assurance they need and that at the very least, should be combined with other activities.

"authentication API" -> "authentication APIs"

General comments: I really think we are over-doing it with the don't use SMS or email, especially for L1.  As I mentioned in my above comment, I didn't see email explicitly singled out in NIST (although they did mention SMS).  Also, the most popular free TOTP application (Google Authenticator) doesn't support syncing which means that users who lose their mobiles will have trouble logging in.  I know other apps such as Authy do, but most users probably use Google Authenticator.  Also, unless I mis-read NIST 800-63B, they only mentioned telephone / PSTN and SMS, not email and VOIP.

2.11: Same comment as above about being pen-testable.
