### ISSUE TITLE
V1 review - attacker-driven design

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#390]
I am not sure what this is (from [1.1.3](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x10-V1-Architecture.md#v11-secure-software-development-lifecycle-requirements)) and a quick Google didn't turn anything up. Is there a link about this or a different name for it?

**Comment by jmanico** [comment]
I say remove it. The treat modeling req above that one is enough.

**Comment by vanderaj** [comment]
I'm going to go with Jim's suggestion. The reality is that this is the descendant of the old requirement to understand who your attackers are. I've seen some presentations of attack driven penetration testing (is there any other type?) but I agree with Jim that it's covered by threat modeling if you're doing that properly.
