### ISSUE TITLE
V2.11 Service Authentication Requirements - NIST Reference?

### ISSUE THREAD

**Issue by ronperris** [OWASP/ASVS#397]
Maybe this is two or three separate requirements?

The current text for 2.11.1 seems to be focused at least three distinct requirements. First "unchanging passwords", second "default accounts" and third "recovery attack resistance". 

The NIST guidance doesn't mention any of this in the referenced requirement 5.1.1.1. Here is the section from the NIST document.
> 5.1.1.1 Memorized Secret Authenticators
> Memorized secrets SHALL be at least 8 characters in length if chosen by the subscriber. 
> Memorized secrets chosen randomly by the CSP or verifier SHALL be at least 6 
> characters in length and MAY be entirely numeric. If the CSP or verifier disallows a chosen 
> memorized secret based on its appearance on a blacklist of compromised values, the 
> subscriber SHALL be required to choose a different memorized secret. No other 
> complexity requirements for memorized secrets SHOULD be imposed. A rationale for this 
> is presented in Appendix A Strength of Memorized Secrets.
> https://pages.nist.gov/800-63-3/sp800-63b.html

Could it be separated into these three separate requirements?

"Integration secrets SHOULD NOT rely on unchanging passwords, such as API keys or shared privileged accounts."

AND

"If passwords are required, the credential should not be a default account"

AND

"Passwords MUST be stored with sufficient protection to prevent offline recovery attacks, including local system access."

**Comment by jmanico** [comment]
completed ff6ae74

**Comment by jmanico** [comment]
also changed to "Verify" language here 5b49f1b
