### ISSUE TITLE
1.2.1 shared application accounts

### ISSUE THREAD

**Issue by m8urnett** [OWASP/ASVS#408]
This verification states that all applications must have unique accounts, but in Windows, services often use the Network Service or Local Service accounts which were made for this purpose. This is a preferred over unique accounts because they have been extensively secured and the passwords are automatically managed by the system. 

There are also [group managed service accounts](https://docs.microsoft.com/en-us/windows-server/security/group-managed-service-accounts/group-managed-service-accounts-overview) and virtual accounts that also have managed passwords. 

Unique, manually-created accounts tend to have neglected passwords and overly permissive rights and privileges. 

Maybe a better wording would be "unique or special low-privilege operating system accounts designed for this purpose..."

In fact, I'm not sure I even agree with the fact that each application have it's own account. I'd rather have someone spend the time to secure one shared account for a group of similar applications than have them have to secure and manage a bunch of unique accounts.

**Comment by mastacheata** [comment]
Not familiar with Windows Services, but how does windows make sure that one service can't interfere with others running in the same account?
Unique is one option. If Windows properly isolates services by architectural means, that is obviously serving the same purpose, though.
I'd agree that this needs additional clarification.

**Comment by m8urnett** [comment]
It depends on what you mean by isolation, but each process has it's own process context, memory space, and security token. Additionally, windows does provide further inter-service isolation and in some cases will make use of virtualization. Some services will be running in different sessions providing further isolation. And there are integrity levels that could be different for each service. While each of these technically are not complete security boundaries in themselves, they are each partial boundaries nonetheless and require that specific conditions be met to cross. 

There are also different built-in service accounts, each with certain restrictions (such as no network access) on a default install and other services such as IIS will install their own service accounts. Windows provides the Local Service and Network Service accounts specifically for our use with services. 

However, although process isolation is good, there is little file system isolation between processes, The benefit is that you have pre-secured accounts that don't require password management--they do not have passwords and cannot be used to login. 

Anyway, my point was that while I agree with 1.2.1 in theory, in the last twenty+ years I have seen that creating, securing, and managing separate accounts for each service is much more error prone than using the built-in service accounts.

**Comment by jmanico** [comment]
Updated cf5a259 if you still have issue with this please re-open a new issue.
