### ISSUE TITLE
1.19.3 - outdated components

### ISSUE THREAD

**Issue by m8urnett** [OWASP/ASVS#412]
"Verify that the build pipeline has a mandatory build step that warns if it finds out of date components, and breaks the build if vulnerable components are discovered."

To me, breaking the build process may not be appropriate action in all cases. For example, the build process might just update the components. I think that should be softened a bit. 

This is what I would propose:

"Verify that the build pipeline warns of out-of-date or insecure components and takes appropriate actions."

**Comment by jmanico** [comment]
This change pushed live; thanks Mark
