### ISSUE TITLE
V3.4.4 - session cookie and lifetime

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#414]
It's not clear, what is the purpose for V3.4.4. requirement.

What is the risk, if session is correctly expired on the server side but cookie is still valid? Let's say, it's "session cookie" (cookie without expires time set). I can not see any risk here.

Where I can see risk is when session lifetime is only "handled" by cookie expires time. So, maybe this requirements shoud be "Session lifetime must be handled from the server side"?

**Comment by tghosth** [comment]
> So, maybe this requirements shoud be "Session lifetime must be handled from the server side"?

Did you check to see if there is a requirement like this already? If not, maybe 3.4.4 should be removed.

**Comment by elarlang** [comment]
I can not see any candidate for that.

Maybe "3.3.2 Verify that absolute or idle timeouts invalidates or erases any client- or server-side session storage." is closest, but it does not define, how "logout" process is triggered.

In my opinion this kind of requirement ("Session lifetime must be handled from the server side") is needed, because I have seen in pen-test cases too often situation, when "log out" just sets a session cookie "expired" but on the server side session is still alive.

**Comment by jmanico** [comment]
I think 3.4.4 should just go away. It's not a useful requirement at all.
Cookie expiration is meaningless. We need server side expiration (or
JWT's that have proper expiration times).

- Jim

**Comment by jmanico** [comment]
Let's just enhance 3.3.2 to be more clear and make 3.4.4 go away. My 2
cents.

**Comment by ronperris** [comment]
@jmanico @tghosth PR was merged that resolves this, feel free to close it.
