### ISSUE TITLE
V3.4.3 - Clarification with host vs domain attribute for session-cookie.

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#426]
requirement 3.4.3
"Verify that cookie-based session IDs have minimum practical hostnames, domain and path attributes, along with the 'SameSite' attribute."

1) "minimum practical hostnames, domain" is a bit too abstract. copy-paste from NIST.
2) style: if secure and httponly are in separate requirements, why to put host/domain, path and samesite to one requirement?

I explain why I would like to get a bit more attention to host/domain and path attributes.

**host vs domain**

host attribute is set by browser when no domain parameter is set for cookie. it's precise value.
domain attribute is used when it's set by set-cookie command. it's wildcard.

there should be clear and separate requirement that host value is recommended to use for session cookie OR if domain parameter is set, domain value for cookie should be as precise as possible.

Why?
If domain parameter IS NOT set in set-cookie command, host value is used. Host value is precise - if set-cookie command came from domain.com it goes back only to domain.com (and not to www.domain.com etc).
If domain parameter IS set, then domain it always works as "wildcard". If value for domain parameter is ".domain.com" (2 dots requirement) then browser sends it also to all subdomains (like www.domain.com, campaign.domain.com etc).

As an attack scenario - if an attacker gets control over some subdomain, he/she can lure victim browser to visit this site, and if victim has an active session, then attacker can steal it from another subdomain.

**path**
if application is located in some subfolder (and another application in different folders) and/or session cookie is actually required only by one path (ex /admin/) then with setting precise path value we can take away potential information leakage.

**Comment by m8urnett** [comment]
I agree that this is not clear. Setting the domain attribute includes subdomains, but not setting it is the equivalent to host-only so that example.com, and www.example.com are different. Which you would use depends on the specific site and requirements. 

However, you can set the cookie domain to www.example.com and it will be valid at example.com but not evil.example.com. 

I'll take a closer look at this and see if I can word it better.

**Comment by elarlang** [comment]
> However, you can set the cookie domain to [www.example.com](http://www.example.com) and it will be valid at example.com but not evil.example.com.

How?
Based on my knowledge, cookie with domain value www.example.com is not valid for http://example.com. It is true vice-versa, but not that way.

https://tools.ietf.org/html/rfc6265#section-5.1.3

> "The domain string is a suffix of the string."
In your example, www.example.com is not suffix for example.com.

**Comment by m8urnett** [comment]
My bad, I read that too quickly.

**Comment by jmanico** [comment]
Hey @elarlang can you look at 800c8c4 and let me know if this meets your approval?

**Comment by elarlang** [comment]
Yes. (y)
