### ISSUE TITLE
V4.1.8 "control decisions can be logged" - seems like V8 requirement

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#432]
**requirement**
4.1.8 Verify that all access control decisions can be logged and all failed decisions are logged.

**recommendation**
move to V8? Like there is already V8.1.10 for authentication logs.

edit: actually, it's probably more generic decision - are "category specific" logging requirements in each category or are all logging requirements in V8.

If every category specific requirements should be inside category, then V8.1.10 should go back to V2.
If all logging requirements should go to V8, then additionally to mentioned V4.1.8 also V5.1.2 and V5.1.4 should go to V8

**Comment by jmanico** [comment]
Agreed, I'll take this one on.

**Comment by jmanico** [comment]
Done, closing this one out
