### ISSUE TITLE
V16.4.2 split requirement - expected type and virus check separately

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#433]
**requirement**
16.4.2 Verify that files obtained from untrusted sources are validated to be of expected type and scanned by antivirus scanners to prevent upload of known malicious content.

**recommendation**
from testing and writing report perspective I personally would like to see two separate problems written in two separate requirements (expected type and virus check separately)

**Comment by jmanico** [comment]
This is complete, closing out.
