### ISSUE TITLE
V8.1.3 + V8.1.4 covers/duplicates V8.1.10, V8.1.11, V5.1.2, V5.1.4

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#435]
Previous logging related issue #432.

**V8.1.3 and V8.1.4**
  * V8.1.3 Verify that the application logs security relevant events including successful and failed authentication events, access control failures, deserialization failures and input validation failures.
  * V8.1.4 Verify that each log event includes necessary information that would allow for a detailed investigation of the timeline when an event happens.

VS

**V8.1.10, V8.1.11, V5.1.2, V5.1.4**
  * V8.1.10 Verify that all authentication decisions are logged, without storing sensitive session identifiers or memorized secrets. This should include requests with relevant metadata needed for security investigations.
  * V8.1.11 Verify that all access control decisions can be logged and all failed decisions are logged. This should include requests with relevant metadata needed for security investigations.
  * V5.1.2 Verify that server-side input validation failures which result in request rejection and are logged.
  * V5.1.4 Verify that server side validation faults for rules, enforced on both the client and server, are logged.

**recommendations**
  a) Merge V8.1.10, V8.1.11, V5.1.2, V5.1.4 to V8.1.3+V8.1.4
  b) OR V8.1.3 can be removed
  and "This should include requests with relevant metadata needed for security investigations." can be removed from V8.1.10 and V8.1.11 because it's already written to V8.1.4

V5.1.2 and V5.1.4 are logging requirements and belong to category V8

**Comment by vanderaj** [comment]
Took option (a). Thank you for the feedback!
