### ISSUE TITLE
idea: new subcategory to V8 to split from V8.1.* "log content" and "log processing" requirements

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#436]
**requirements what logs should or should not contain (content)**
  * V8.1.1 Verify that the application does not log credentials, session tokens or payment details.
  * V8.1.2 Verify that the application does not log other sensitive data as defined under local privacy laws or relevant security policy.
  * V8.1.3 Verify that the application logs security relevant events including successful and failed authentication events, access control failures, deserialization failures and input validation failures.
  * V8.1.4 Verify that each log event includes necessary information that would allow for a detailed investigation of the timeline when an event happens.
  * V8.1.10 Verify that all authentication decisions are logged, without storing sensitive session identifiers or memorized secrets. This should include requests with relevant metadata needed for security investigations.
  * V8.1.11 Verify that all access control decisions can be logged and all failed decisions are logged. This should include requests with relevant metadata needed for security investigations.
  * V8.1.12 Verify that a common logging format and approach is used across the system.

In my opinion some of those requirements are duplicates and there is separate case #435 for that.

**requirements how logs should be stored or processed**
  * V8.1.5 Verify that all events are protected from injection when viewed in log viewing software.
  * V8.1.6 Verify that security logs are protected from unauthorized access and modification.
  * V8.1.7 Verify that the application appropriately encodes user-supplied data to prevent log injection.
  * V8.1.8 Verify that logs are transmitted to a remote system for analysis, detection, alerting, and escalation.
  * V8.1.9 Verify that time sources are synchronized to the correct time and time zone.

**recommendation**
Create new V8 subcategory.

**Comment by vanderaj** [comment]
Thank you - done!
