### ISSUE TITLE
V9.9 needs clafification

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#438]
**requirement**
9.9 Verify the application has the ability to detect and alert on abnormal numbers of requests.

**recommendation**
Requirement should specify, is it
  * requests from one user
  * from one IP
  * in total
  * something else?
  * all of them?

Is this requirements for monitor DoS attacks or is there some another reason?

**Comment by vanderaj** [comment]
Solid question. I will try to make it a bit more obvious. Basically all of the above, but even one of them is better than none.

**Comment by vanderaj** [comment]
Hi there, I've made a change. Please review and re-open if necessary

**Comment by elarlang** [comment]
Description is now more understandable and testable, but isn't it more V15 requirement?
If it by one IP, by one user etc, then there can be "expected behaviour" which is already related to business logic rules.

**Comment by elarlang** [comment]
**new version of V9.1.4 (previously V9.9)**
9.1.4 Verify the application has the ability to detect and alert on abnormal numbers of requests, such as by IP, user, total per hour or day, or whatever makes sense for the application.

**V15.* category requirements**

  * 15.6 	Verify the application has configurable alerting when automated attacks or unusual activity is detected.
  * 15.7 	Verify the application has automated reactions when automated attacks or unusual activity is detected.

**question**
Feels like 9.1.4 is covered by V15.* requirements. Or if not, what's the difference?
