### ISSUE TITLE
V1.4.2 - V4.1.1 - duplicates

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#442]
**V1.4.2 vs V4.1.1**
* V4.1.1 Verify that the chosen access control solution is flexible enough to meet the application's needs.
* V1.4.2 Verify that the chosen access control solution is flexible enough to meet the application's needs.

**recommendation**
Remove V4.1.1 - it's too abstract and it's hard to create clear test-case out of that requirement.

Not sure this requirement does provide anything extra which is not covered already by other V4 requirements.

**Comment by vanderaj** [comment]
Agreed.
