### ISSUE TITLE
Conflict between V2.1.1 and V2.3.1 OR missing requirement for activation code expires time

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#443]
**requirements**

  * V2.1.1 Verify that passwords are at least 12 characters in length.
  * V2.3.1 Verify system generated initial passwords or activation codes SHOULD be securely randomly generated, SHOULD be at least 6 characters long, and MAY contain letters and numbers.

**problem**
If activation code does not have relatively short expires time, we should consider it as passwords and in this case requirements for password/code in V2.3.1 and V2.1.1 are different (in conflict)

**recommendation**
  * a) add requirement "expires time for actication code" to V2.3.*
  * b) increase password/code length requirement in V2.3.1

**Comment by vanderaj** [comment]
Initial activation passwords are essentially one time passwords. NIST chooses 6 characters to allow for PIN numbers for this first login, like Apple's device authorization. I think I would be miffed if I had to type 12 numbers when I add a new device. 

Thoughts? Does this change your view?

**Comment by elarlang** [comment]
I don't have anything against this 6 number length but without "expires time" and without clearly one-time-password explanations we need to look it as usual password. From this point I can see 2 directions (like written in initial recommendation):

  *  a) add expires time requirement for initial password + say it out clearly - you can use "initial password" only once. My experience from pen-test cases: if users are not forced to change their initial password, they will keep using it.
  * b) if it does not have extra requirement like expires time and OTP requirement, we need to consider as usual password (from attacker perspective)

**Comment by vanderaj** [comment]
I've made changes as per checkin fa169b4. Please review and re-open if I didn't get it right
