### ISSUE TITLE
Move V5.3.10 (protect against mass parameter assignement attacks) from V5.3 (Injection Prevention) subcategory to V5.1 subcategory (Input Validation)

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#448]
**requirement**
5.3.10 Verify that frameworks protect against mass parameter assignment attacks, or that the application has countermeasures to protect against unsafe parameter assignment, such as marking fields private or similar.

**recommendation**
Does not feel like "Injection Prevention" or "Output Encoding" topic. I see it as input validation.
Application/controller must accept only (white)listed parameters from user.

Move to subcategory V5.1 Input Validation Requirements

**Comment by jmanico** [comment]
Completed here 8c330fa
