### ISSUE TITLE
Questions about V5.2 "Output Encoding" and 5.3 "Injection Prevention" categories

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#449]
**V5.2 "Output Encoding" and 5.3 "Injection Prevention"**

  * V5.2 Output Encoding
  * V5.3 Injection Prevention

**previously...**
Feedback - I like to have "building output" topic separated again from usual "input validation" requirement pool. I shared my opinion almoust 5 years ago: http://lists.owasp.org/pipermail/owasp-application-security-verification-standard/2014-June/000589.html

To give more detailed and valueable recommendations, I need to start with questons. Maybe it makes sense to have each question/recommendation as separate issue, but I'm afraid that then we lack overview.

**question 1**

What is the difference between V5.2 and V5.3 categories and the reason to keep them separately?

**question 2**

Do you consider "escaping" part of "encoding" and all requirements which are mentioning "encoding" are valid also for "escaping"?

**question 3**

  * 5.2.2 Verify that output encoding is relevant for the interpreter and context required. For example, use encoders specifically for HTML values, HTML attributes, URL Parameters, HTTP headers, SMTP, and others as the context requires.

It's nice abstract requirement. But there are chosen technologies/syntaxes which have separate requirements:

  * 5.3.1 SQL
  * 5.3.2 LDAP
  * 5.3.3 OS command
  * 5.3.4 LFI/RFI
  * 5.3.5 XPath/XML
  * 5.3.7 SMTP/IMAP

How the list of technologies is chosen and why most common ones (HTML injection, JavaScript injection) does not exist as separate points?

**Comment by vanderaj** [comment]
@jmanico Allocating to you as you're our output encoding enthusiast.

**Comment by jmanico** [comment]
1) 5.2 and 5.3 can be merged, potentially.
2) I consider escaping and encoding to be functionality the same and do not wish to split them out.
3) 5.2.2 is aimed to be specific to XSS

I am ok to rearrange this. Are you at SecAppDev? Happy to work on all of this together while we're in the same room.

**Comment by elarlang** [comment]
At the moment I just wanted to know the reasons, why it's made like it is. Maybe there are some patterns or reasons what I wasn't able to figure out myself.

So far I haven't find solution what I like myself, every way fires somehow back.

It's a bit confusing to have encoding requirements separated from injection prevention requirements as current encoding requirements matching to "injection prevention" subcategory also. 

No actions to recommend yet.

**Comment by elarlang** [comment]
I try to move on with **question 1** ("What is the difference between V5.2 and V5.3 categories and the reason to keep them separately?") and put my idea here **for brainstorm** (not as recommendation yet).

Proposal for **V5 subcategories** (names and texts needs language corrections):

  * **V5.1 Input validation** - requirements for accepting or/and not accepting user input.
It should contain requirements where output is boolean - is input valid or not.

  * **V5.2 Sanitize** - automatic modification to (user input OR dynamically build command like path) to be sure, it's later safe, like input from wysiwyg, sanitize svg, sanitize for SMTP, sanitize filename.
It should contain requirements where output is sanitized to be safe for interpreter.

  * **V5.3 Building dynamic content** - escaping and encoding content for next component (interpretator). 
It should contain requirements where output is command to interpreter in correct encoding/escaping.

  * **V5.4 Deserialization** - no changes, extracting data from serialized content like JSON.parse, php unserialize etc
  * **V5.5 Unmanaged Code** - no changes (no L1 requirements, would like to see it as last subcategory)

Current "5.2 Output Encoding Requirements" and "V5.3 Injection Prevention Requirements" is a bit confusing. In general, encoding/escaping IS defence against Injection attacks. To have 2 categories "Encoding" AND "Injection prevention" does not make sense for me.


Why?
It makes sense from defence point of view - where and what exactly is missing or done incorrectly that problem exists.
In my opinion (which is based on pen-test and 2500h security trainings for developers) a lot of security holes happen because defence is built to incorrect place - like input validation is not correct way to avoid HTML injection and JavaScript injection attacks. Input validation is business logic rule but HTML injection and JavaScript injection are output encoding problems. Between them is sanitize, where you try to eliminate bad things or allow good things. But they are all different. But they all MAY prevent injection attacks.

Does it makes any sense for you?

**Comment by vanderaj** [comment]
Hi folks, I've had a crack at it. One obvious thing to me is that I wanted to change the order of 5.2 and 5.3 so that penetration testers can stop at the end of 5.2. I've renamed it per the suggestions above, but also kept some of the names we've previously used. 

@elarlang @jmanico Please let me know if this is okay. Re-open if not. Otherwise, let's call it done and move on.

**Comment by elarlang** [comment]
It ended up a bit different way.

My idea was to separate Input sanitize and output encoding requirements. At the moment requirements really don't mach with subcategories.

My proposal:

**Input validation**
  * 5.1.1 Verify that input validation is enforced on the server-side.
  * 5.1.2 Verify that the application has defenses against HTTP parameter pollution attacks, particularly if the application framework makes no distinction about the source of request parameters (GET, POST, cookies, headers, or environment variables).
  * 5.1.3 Verify that frameworks protect against mass parameter assignment attacks, or that the application has countermeasures to protect against unsafe parameter assignment, such as marking fields private or similar.
  * 5.1.5 Verify that all input (HTML form fields, REST requests, URL parameters, HTTP headers, cookies, batch files, RSS feeds, etc) is validated using positive validation (whitelisting).
  * 5.1.6 Verify that structured data is strongly typed and validated against a defined schema including allowed characters, length and pattern (e.g. credit card numbers or telephone, or validating that two related fields are reasonable, such as checking that suburb and zip/postcode match).
  * 5.1.7 Verify that unstructured data is sanitized to enforce safety measures such as allowed characters and length, and characters potentially harmful in given context should be escaped (e.g. names with Unicode or apostrophes, such as ねこ or O'Hara).


**sanitize and sandbox**
  * 5.1.4 Verify that all untrusted HTML input from WYSIWYG editors or similar is properly sanitized with an HTML sanitizer library or framework feature.
  * 5.2.7 Verify that the application sanitizes user input before passing to mail systems to protect against SMTP or IMAP injection.
  * 5.2.8 Verify that the application avoids the use of eval() or other dynamic code execution features. Where there is no alternative, any user input being included must be sanitized or sandboxed before being executed.
  * 5.2.9 Verify that the application protects against template injection attacks by ensuring that any user input being included is sanitized or sandboxed.
  * 5.2.10 Verify that the application protects against SSRF attacks, by validating or sanitizing untrusted data or HTTP file metadata, such as filenames and URL input fields, use whitelisting of protocols, domains, paths and ports.
  * 5.2.11 Verify that the application sanitizes, disables, or sandboxes user-supplied SVG scriptable content, especially as they relate to XSS resulting from inline scripts, and foreignObject.
  * 5.2.12 Verify that the application sanitizes, disables, or sandboxes user-supplied scriptable or expression template language content, such as Markdown, CSS or XSL stylesheets, BBCode, or similar.


**Output encoding and Injection Prevention Requirements**
  * 5.3.1 Verify that output encoding occurs close to or by the interpreter for which it is intended.
  * 5.3.2 Verify that output encoding is relevant for the interpreter and context required. For example, use encoders specifically for HTML values, HTML attributes, URL Parameters, HTTP headers, SMTP, and others as the context requires.
  * 5.3.3 Verify that output encoding preserves the user's chosen character set and locale, such that any Unicode character point is valid and safely handled.
  * 5.3.4 Verify that context-aware, preferably automated - or at worst, manual - output escaping protects against reflected, stored, and DOM based XSS.
  * 5.3.5 Verify that any user-supplied data included in the browser's DOM or web views protects against JavaScript code execution and XSS attacks.
  * 5.2.6 Verify that where potentially untrusted data is copied one DOM context to another, the transfer uses safe JavaScript methods, such as using innerText or JQuery .val to ensure the application is not susceptible to DOM Cross-Site Scripting (XSS) attacks.
  * 5.3.6 Verify that where parameterized or safer mechanisms are not present, context-specific output encoding is used to protect against injection attacks, such as the use of SQL escaping to protect against SQL injection.
  * 5.2.1 Verify that data selection or database queries (e.g. SQL, HQL, ORM, NoSQL) use parameterized queries, ORMs, entity frameworks, or are otherwise protected from database injection attacks.
  * 5.2.2 Verify that the application protects against LDAP Injection vulnerabilities, or that specific security controls to prevent LDAP Injection have been implemented.
  * 5.2.3 Verify that the application protects against OS command injection and that operating system calls use parameterized OS queries or use contextual command line output encoding.
  * 5.2.4 Verify that the application protects against Local File Inclusion (LFI) or Remote File Inclusion (RFI) attacks.
  * 5.2.5 Verify that the application protects against XPath injection or XML injection attacks.



Additional points/questions:
  * 5.3.2 - mention JavaScript or separate requirement for JavaScript injection - it's widespread enought to have separate point.
  * 5.2.6 - JQuery -> jQuery (this is how they write their own name)
  * 5.3.4 - what is different compared to 5.3.2?
  * 5.3.5 - what is the point of this requirement?

**Comment by elarlang** [comment]
Please re-open this case.
