### ISSUE TITLE
Move/Merge V16.4.2 to V16.2.1

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#450]
Previously I recommended to split expected type and virus check (#433) but seems that we created one duplicate requirement.

**requirements**

  * V16.2.1 Verify that files obtained from untrusted sources are validated to be of expected type based on the file's "magic number" or other content.
  * V16.4.2 Verify that files obtained from untrusted sources are validated to be of the expected type.

**recommendation**
Merge V16.4.2 to V16.2.1 or just remove V16.4.2 as it is not really storage requirement (V16.4 File Storage Requirements).

**Comment by jmanico** [comment]
Aye, good catch. I’ll fix this when I’m back at my computer.

**Comment by jmanico** [comment]
Addressed here 78f252e please reopen if not satisfied.
