### ISSUE TITLE
V16.5.2 - from "html and svg" blacklist to "avoid executing HTML/JavaScript from uploaded files in general"

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#451]
**requirement**
16.5.2 Verify that untrusted uploaded HTML and SVG files are only returned as text/plain, and a separate sub-domain with no permission to access session cookies or tokens is used to prevent the uploaded file being used to launch an XSS attack.

**recommendation**
If to mention only HTML and SVG files, it works as blacklist. At least XML is missing from that list, but then it could be still blacklist. We may have surprises  from browsers what those can execute as HTML content.

Idea for the requirement should be: if user makes direct request to uploaded file, it will never be executed as HTML/JavaScript content.

Solutions:
  * a) set content-type as plain/text for inline file serving
  * b) serve uploaded files files as attachments

**Comment by vanderaj** [comment]
@jmanico you're our resident output encoding enthusiast. can I pls allocate this one to you?

**Comment by jmanico** [comment]
I made this change 5c8dcd6 please reopen if this does not address your concern.
