### ISSUE TITLE
Export script doesn't return all the requirements it should.

### ISSUE THREAD

**Issue by ronperris** [OWASP/ASVS#453]
# What I expected
The `python export.py --format=json` command should return all the requirements as json.

# What I experienced
Only the Data Protection requirements are returned.

The regex in asvs.py:50 only matches one level of subsection numbering, like 9.7 or 10.1 but doesn't match two levels like 9.7.1 or 10.1.2.

**Comment by vanderaj** [comment]
@tghosth @jmanico @danielcuthbert @m8urnett any one of you able to look at the code and fix? I'm trying to make it the same few columns in each requirement, will take a little to get rid of CWSS. There will be a NIST extra column in V2 and V3, which probably needs to be ignored.

**Comment by vanderaj** [comment]
Also Vnn.n.nn renumbering is nearly complete. I will make sure all chapters have at least one Vnn.n section to make section parsing easier.

**Comment by vanderaj** [comment]
@ronperris does merging your pull resolve this issue? If so, can we can close this now?

**Comment by ronperris** [comment]
@vanderaj Yep, sorry if that wasn't clear. =/
