### ISSUE TITLE
V7 Issues

### ISSUE THREAD

**Issue by ossie-git** [OWASP/ASVS#454]
Had a quick look at V7.  Am I missing something or should all of 7.1.x also apply to L1?  It says that all items are marked as L1 and then doesn't mark them.  The same observation is true for V7.2

How can you have 7.3.1 without 7.3.3?

Would think that 7.3.4 would definitely be a requirement for L2

I would add 7.3.6: Log in UTC to make log analysis across different time zones easier and have it applicable to L2 and L3

For 7.4, I would add an additional quick win which is similar to 7.4.3 but at the application server level (IIS, Tomcat, etc.)

"in situ" -> "locally" (easier to digest)

**Comment by elarlang** [comment]
Disclaimer: I'm not maintainer for ASVS document, just share my opinions.

> How can you have 7.3.1 without 7.3.3?

**7.3.1** Verify that all events are protected from injection when viewed in log viewing software.
Defence against log viewing software - let's say you watch logs via web (as HTML document) then injection in this context means that logs must be converted to HTML.

**7.3.3** Verify that the application appropriately encodes user-supplied data to prevent log injection.
Log injection in general - if logs have separators between different data fields, then you need to be sure that you can not enter those separator fields in text or you need to escape/encode them somehow. Classical example: what happens, if you can insert newline to log?


> I would add 7.3.6: Log in UTC to make log analysis across different time zones easier and have it applicable to L2 and L3

It would not have anything extra to 7.3.5:
7.3.5 Verify that time sources are synchronized to the correct time and time zone.

**Comment by vanderaj** [comment]
@ossie-git @elarlang Please review and re-open. There were changes in config as well to deal with some of these items
