### ISSUE TITLE
V19.4.12 - Rephrase and move to V5

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#455]
**requirement**
19.4.12 Verify that application components remove, disable, or sandbox inline scripts found in SVG files.

**problems**
  * "remove" and disable" are not configuration (19.4 Hardened Configuration), those are more sanitize (somewhere in V5 category)
  * "remove bad things" in general is blacklist - do we know all bad things? For example - if I can use foreignObject tag, it's still possible to do damage (https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject). I remember one pen-test case, when developers started sanitize SVG content with blacklist - it took 6 iterations till I didn't find new solution immediately.
  * "sandboxing" (from direct HTTP request vector) is covered by V16.5.2 "Verify that direct requests to uploaded files will never be executed as HTML/JavaScript content."

**recommendation**
  * idea for requirement: "sanitize SVG content with whitelist approach - accept only expected tags and parameters"
  * move it to V5 category. Should belong to same (sub)category like "5.1.5 Verify that all untrusted HTML input from WYSIWYG editors or similar is properly sanitized with an HTML sanitizer library or framework feature.".
  * Not sure "Input validation" is correct for "making automatic modification to user input" (separate issue for V5.1.5?).
  * If agreed with those recommendations, same approach can be taken with requirement "19.4.13 Verify that application components remove, disable, or sandbox scripts by Markdown and other markup languages such as BBCode."

**Comment by vanderaj** [comment]
These are excellent points. I think the answer here is to move them to V5, and then to improve V16.5.2 to include sandboxing / sub-domains / SOP. I think this might be more of an architectural issue as well; sandboxing is a powerful way to restrain the power of uploaded objects outside of XSS.

**Comment by vanderaj** [comment]
I've made the changes as per the changeset above. Please review and let me know if I've hit the mark. I think this might make a dupe of the outside the webroot control between V1 and V12, but I'm okay with that, and we can deal with that separately.
