### ISSUE TITLE
V2.1.7 - concern about plain-text leakage during "checking breached passwords"

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#456]
**requirement**
V2.1.7 Verify that passwords submitted during account registration, login, and password change are checked against a set of breached passwords either locally or via API. If the password is breached, the application must require the user to choose another non-breached password.

**concern**
What if someone start checking plain-passwords via API? I think it's more risky than do not have this check at all.

**recommendation**
Add warning/instruction that password must never be used in plain-text to check the leakage.

**Comment by vanderaj** [comment]
I've added some text. Please review and re-open if I got it wrong. I agree with you, btw.
