### ISSUE TITLE
Renaming files in repository

### ISSUE THREAD

**Issue by athiasjerome** [OWASP/ASVS#46]
Would it be possible to rename files by including a leading 0 (zero)
e.g.:
V2 - Authentication.xlsx
would be
V02 - Authentication.xlsx

this making it more logical ordering

**Comment by vanderaj** [comment]
Hi there,

Sure. Please be aware that I've incorporated all of the spreadsheet items
in the repository into the main doc, so they should be treated as old.

thanks
Andrew

**Comment by vanderaj** [comment]
Fixed.

Andrew
