### ISSUE TITLE
Remove unused images.

### ISSUE THREAD

**Issue by ronperris** [OWASP/ASVS#464]
Do we still need the images folder and its contents? I didn't notice any images in the exportable formats.

**Comment by vanderaj** [comment]
We might. They are available in 3.0 folder, so I agree we can delete them once the frontispiece is re-written.

**Comment by vanderaj** [comment]
The OWASP logo is used in the Word document, I've added the levels, and the CCSA logo is used in the frontispiece. No further removal is required.

**Comment by vanderaj** [comment]
p.s. Thanks for pointing this out. There might have been MASVS graphics in here for example, so it's good you were looking!
