### ISSUE TITLE
Create leader and collaborator credits

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#468]
We need to have an accurate project lead and collaborator list for 4.0. 

I'd suggest rolling up the credits for 3.0 in there somehow as well, as it's important to keep credits for many of the items that still exist in their original form from 1.0 - 3.0

**Comment by vanderaj** [comment]
Done a first pass. Please find out if you need to have your name in lights.

**Comment by vanderaj** [comment]
Resolved in 3b417a7

**Comment by elarlang** [comment]
What are the criterias for contributors/reviewers to get listed?
