### ISSUE TITLE
V11 - make requirement number format like other categories (3 levels)

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#471]
**problem**
"V11 Business Logic Security Requirements" is the only category with requirement numbers formated to X.X (not X.X.X like others)

**recommendation**
  * "Rename" subcategory "V11 Business Logic Security Requirements" to "**V11.1** Business Logic Security Requirements"
  * Fix requirement numbers from X.X to X.X.X

**Comment by tghosth** [comment]
See https://github.com/OWASP/ASVS/commit/cb88498b745a5b1ee5703369e58fbd30395cdf61
