### ISSUE TITLE
V14.1 subcategory missing

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#472]
**problem**
there is no subcategory like V14.1

**recommendation**
Fix numeration.

**Comment by tghosth** [comment]
As this is renumbering, we probably want to leave this for the end

**Comment by elarlang** [comment]
At the end it must be done to be sure, that everything is ok, but so far all my numbering related reported issues (#439, #467, #471) are fixed.

**Comment by vanderaj** [comment]
I can't count! Gonna fix once I've done the rest.
