### ISSUE TITLE
V8.3.3 - improve/clarify, remove or move to V4

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#476]
**request**
V8.3.3 Verify the application protects against unauthorized creation, reading, updating or alteration, or deletion of all other user's records unless specific permission is granted.

**problem**
From description it's not clear what kind of "records" are in scope for this requirement.

**recommendation**
  a) Improve/clarify verification text
  b) remove requirement, as it's covered by "V4 Access Control" requirements
  c) if it has something unique, consider moving this requirement to V4 category

**Comment by vanderaj** [comment]
Agreed. I'll remove it and put an explanatory text that they need to comply with 4.2.1
