### ISSUE TITLE
Ensure all Proactive Controls CWEs are in ASVS

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#480]
We claim compliance with the Proactive Controls. Ensure that every one of the Proactive Controls is present as a L1 control in the ASVS.

**Comment by tghosth** [comment]
I did some work on this #322 and eventually came up with a list of relevant requirements for Proactive Controls which I [included here](https://github.com/OWASP/ASVS/issues/322#issuecomment-453858977).

I will go through this again now.

**Comment by tghosth** [comment]
Created #534 for @vanderaj to review

**Comment by vanderaj** [comment]
Thank you - applied.
