### ISSUE TITLE
Preface - IoT text needs to be re-worded

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#482]
Need to ensure that we describe IoT is as being present in Appendice D, but it is informative in this release and will be superceded by a final IOT project deliverable at some point in the future.

**Comment by tkisason** [comment]
Fixed in https://github.com/OWASP/ASVS/pull/522 , this issue can be closed.

**Comment by vanderaj** [comment]
Fixed in final QA pass. This section is now ready for final.
