### ISSUE TITLE
Serverless Top 10 - Preface and API chapter compliance

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#483]
We don’t yet mention Server-less Top 10 anywhere. 

Need a paragraph on it, and ensure V13 API security chapter contains every single element of the Serverless Top 10 as a L1 concern.

**Comment by tkisason** [comment]
I'll try to add something today/tommorow

**Comment by vanderaj** [comment]
We'll have to come back to Serverless Top 10 in 4.1. I think we do have coverage due to the overlap between Serverless and the OWASP top 10, but we no longer have time to make sure.
