### ISSUE TITLE
Q about V7.13: PII refers to "personally identifiable information"? 

### ISSUE THREAD

**Issue by pgwammes** [OWASP/ASVS#51]
Does PII refers to "personally identifiable information"?

**Comment by athiasjerome** [comment]
yes

**Comment by pgwammes** [comment]
Thanks, I wasn't sure if it was pii or pll (the last search query brings up results for a tv series that I'd never heart about :-))

**Comment by mgrinsven** [comment]
Perhaps PII should be in the glossary or as a footnote. Because for someone not knowing what PII stands for, requirement V7.13 is a bit cryptic.

**Comment by vanderaj** [comment]
I will make it clear that it's personally identifiable information, and put an entry in the glossary.

**Comment by danielcuthbert** [comment]
added to glossary
