### ISSUE TITLE
V13.2.4 Is not in the standard format. What is we are verifying?

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#514]
This item has no clear verification objective. Please rephrase with “Verify that... “  and make it clearer as to what the objective is - could it be solved with anti-automation, rate limiting, API gateway, what? 

I think this has the wrong CWE - it’s anti-automation (CWE-799) rather than CWE 770.

**Comment by demideus** [comment]
@vanderaj 
CWE was changed to 779 in stead of 799.
Please correct this typo.
