### ISSUE TITLE
Q on V5.21: grey-listing?

### ISSUE THREAD

**Issue by pgwammes** [OWASP/ASVS#52]
Hi, I dont understand V5.21 "Verify that applications have defined positive validation for all input fields, with permissible exceptions to allow characters that might otherwise be rejected." 

The first part is white-listing, right? The second part grey-listing? How would you do that?

**Comment by kravietz** [comment]
This is indeed quite cryptic and should be reworder to say more clearly what is expected. "Positive validation" and "white-listing" are jargon. I would start with agreeing on what we want to achieve and then wording it in unambigous way:

* All input data should be validated *(not only "fields", as "fields" imply HTML forms, and input may come through REST calls, query parameters etc)*
* Structured data should be strictly validated against a defined schema including allowed characters, length and pattern *(e.g. a social security number or telephone)*
* Unstructured data should be sanitized to enforce generic safety measures such as allowed characters and length, and characters potentially harmful in given context should be removed or escaped *(e.g. natural names with Unicode or apostrophes, such as Këvïn or O'Hara)*

**Comment by vanderaj** [comment]
These are great suggestions to improve an old requirement. I will work on incorporating new text.

**Comment by vanderaj** [comment]
Fixed. 

![screen shot 2015-08-11 at 14 05 36](https://cloud.githubusercontent.com/assets/5029993/9189871/1a1596cc-4032-11e5-869d-1e20b467c4a7.png)
