### ISSUE TITLE
Appendix B references QA notes

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#520]
Add OWASP Top 10 2017,
Add OWASP Testing Guide 4.0
Add OWASP Proactive Controls (2018)
Add a link to the OWASP IOT project
Add a link to the OWASP Serverless Project

Add a link to the SecLists Github
Update PCI DSS to 3.2.1
Add PCI Secure Development Standard (2019)

Remove the reverse engineering guide (we don’t really refer to it in the ASVS). 

Move the Mobile links to their own section away from the main list as we’re referencing them rather than including them.

**Comment by tkisason** [comment]
Done all of that and added the PCI Secure Software Lifecycle too, added OWASP Software Assurance Maturity Model too. 

See https://github.com/OWASP/ASVS/pull/533

**Comment by vanderaj** [comment]
Thank you! :-) This is amazing work. :-) Please make sure you put yourself down in the Credits ticket so we can credit you for your work on this.
