### ISSUE TITLE
13.2.2 schema validation concerns

### ISSUE THREAD

**Issue by jaxley** [OWASP/ASVS#525]
I'm all for schema validation where it adds value without risk, but to suggest it for all REST services seems overkill.

The JSON schema is not even standardized yet (latest draft is 07 from a year ago -- latest on IETF is 01) . Do implementations adequately keep up with the drafts and implement reliable validations?  How secure are the implementations?

I worry about the additional attack surface that JSON validation adds and wonder what additional tangible benefits it provides that are worth that additional attack surface.  e.g. this nodejs library for doing schema validation introduced a regex DoS that wouldn't have been there without adding JSON schema:  https://snyk.io/test/npm/json-schema-validation

The recommendation currently applies this to L1, L2 and L3.  That seems excessive.

I see "input validation" mentioned in the overview, but there aren't any requirements listed specific to input validation.  There could be levels of validation.

1. schema validation (there are varying tolerances here as well depending on the schema definition)
2. JSON parsing validation (there are varying tolerances for extra properties or missing properties when deserializing)
3. Validation of the values in each JSON object value by standard input validation rules (they all still apply to APIs) -- data type, data format, length, etc.

I'll add another issue related to deserialization issues and another for serialization.  I don't see any coverage of these in the guidelines.

**Comment by jmanico** [comment]
If you do JSON sanitization before JSON validation you mitigate these risks.

I think it’s otherwise •absolutely fundamental• to do JSON schema validation to ensure only specific JSON allowed for each endpoint.

I ask us to please keep this is, and potentially add JSON sanitization. Folks can remote it in their fork.

**Comment by vanderaj** [comment]
I agree that chasing drafts of standards is sub-optimal, but many are not even aware of them. If we can't drive adoption, the draft RFCs will dry up and we're stuck with a nothing burger again. 

We need to button this issue up this weekend, so please suggest some extra words to 13.2.2 that might ameliorate the issue for you, such as urging caution with draft validation standards.

**Comment by tghosth** [comment]
Hi @jaxley do you have any suggestions of how to reword 13.2.2?
Deserialiazation is covered in 5.5.

**Comment by vanderaj** [comment]
I've left 5.2.2 as is per Jim, but put in some informative text at the top. 

@jaxley please re-open if you think this is not sufficient, but otherwise, this is it for 4.0

**Comment by jaxley** [comment]
It's probably ignorance of a particular attack vector, but I'm not seeing what makes JSON schema validation *essential* as a primary control, especially given that it would expose you to god knows how much attack surface as a tradeoff.  It may be appropriate in some contexts to be explicit, but in large part, it is really duplicating the validation that would be done as recommended in 

* The typical JSON deserializer library that is secure will catch any JSON syntactical deviation so invalid JSON will not be accepted
* The typical JSON deserializer is already going to enforce most, if not all, of the structural validation of a JSON document based on the deserialization configuration directives or conventions of the JSON library. 
* 5.1.2 covers mass assignment risks already
* 5.1.4 covers validation of the individual data properties that would be inside the JSON payload
* Many cases in programming do not require deserialization to strongly-typed data; leaving values as maps and lists is sufficient and data can be validated as it is extracted and converted to the appropriate type, if necessary, or just leave as strings if that is all that is required.  Or using JSON parsing APIs to extract strings directly without marshaling to another data structure may be appropriate.

@jmanico can you help fill in the gaps that JSON schema validation addresses?

It's the additional attack surface tradeoff that I'm not sure I would say is always weighted toward adding this from a risk/reward standpoint.  If there is a compelling case where this kills whole classes of attacks that otherwise would be difficult to mitigate or left unmitigated, then by all means we should recommend it, but definitely not for L1 IMO.  I'm all for layered defenses, but would possibly see this as a nice-to-have defense-in-depth secondary control, not a primary control.

The fact that JSON schema is a moving target and who knows how complete the implementations are is a minor thing by comparison.

**Comment by jaxley** [comment]
Here's a fun one:

```
json-schema-validator jaxley$ snyk test

Testing /private/tmp/json-schema-validator...

✗ Medium severity issue found in org.mozilla:rhino
  Description: MPL-2.0 license
  Info: https://snyk.io/vuln/snyk:lic:maven:org.mozilla:rhino:MPL-2.0
  Introduced through: com.github.java-json-tools:json-schema-core@1.2.9
  From: com.github.java-json-tools:json-schema-core@1.2.9 > org.mozilla:rhino@1.7.7.1

✗ Medium severity vulnerability found in com.google.guava:guava
  Description: Deserialization of Untrusted Data
  Info: https://snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-32236
  Introduced through: com.github.java-json-tools:json-schema-core@1.2.9
  From: com.github.java-json-tools:json-schema-core@1.2.9 > com.github.fge:uri-template@0.9 > com.google.guava:guava@16.0.1
  From: com.github.java-json-tools:json-schema-core@1.2.9 > com.github.java-json-tools:jackson-coreutils@1.9 > com.google.guava:guava@16.0.1

✗ Medium severity vulnerability found in com.fasterxml.jackson.core:jackson-core
  Description: Denial of Service (DoS)
  Info: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-31519
  Introduced through: com.github.java-json-tools:json-schema-core@1.2.9
  From: com.github.java-json-tools:json-schema-core@1.2.9 > com.github.java-json-tools:jackson-coreutils@1.9 > com.fasterxml.jackson.core:jackson-databind@2.2.3 > com.fasterxml.jackson.core:jackson-core@2.2.3

✗ Medium severity vulnerability found in com.fasterxml.jackson.core:jackson-core
  Description: Denial of Service (DoS)
  Info: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-31520
  Introduced through: com.github.java-json-tools:json-schema-core@1.2.9
  From: com.github.java-json-tools:json-schema-core@1.2.9 > com.github.java-json-tools:jackson-coreutils@1.9 > com.fasterxml.jackson.core:jackson-databind@2.2.3 > com.fasterxml.jackson.core:jackson-core@2.2.3

✗ High severity vulnerability found in com.fasterxml.jackson.core:jackson-databind
  Description: Deserialization of Untrusted Data
  Info: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-31507
  Introduced through: com.github.java-json-tools:json-schema-core@1.2.9
  From: com.github.java-json-tools:json-schema-core@1.2.9 > com.github.java-json-tools:jackson-coreutils@1.9 > com.fasterxml.jackson.core:jackson-databind@2.2.3

✗ High severity vulnerability found in com.fasterxml.jackson.core:jackson-databind
  Description: Deserialization of Untrusted Data
  Info: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-31573
  Introduced through: com.github.java-json-tools:json-schema-core@1.2.9
  From: com.github.java-json-tools:json-schema-core@1.2.9 > com.github.java-json-tools:jackson-coreutils@1.9 > com.fasterxml.jackson.core:jackson-databind@2.2.3

✗ High severity vulnerability found in com.fasterxml.jackson.core:jackson-databind
  Description: Deserialization of Untrusted Data
  Info: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-32043
  Introduced through: com.github.java-json-tools:json-schema-core@1.2.9
  From: com.github.java-json-tools:json-schema-core@1.2.9 > com.github.java-json-tools:jackson-coreutils@1.9 > com.fasterxml.jackson.core:jackson-databind@2.2.3

✗ High severity vulnerability found in com.fasterxml.jackson.core:jackson-databind
  Description: Deserialization of Untrusted Data
  Info: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-32044
  Introduced through: com.github.java-json-tools:json-schema-core@1.2.9
  From: com.github.java-json-tools:json-schema-core@1.2.9 > com.github.java-json-tools:jackson-coreutils@1.9 > com.fasterxml.jackson.core:jackson-databind@2.2.3

✗ High severity vulnerability found in com.fasterxml.jackson.core:jackson-databind
  Description: Deserialization of Untrusted Data
  Info: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-32111
  Introduced through: com.github.java-json-tools:json-schema-core@1.2.9
  From: com.github.java-json-tools:json-schema-core@1.2.9 > com.github.java-json-tools:jackson-coreutils@1.9 > com.fasterxml.jackson.core:jackson-databind@2.2.3

✗ High severity vulnerability found in com.fasterxml.jackson.core:jackson-databind
  Description: Deserialization of Untrusted Data
  Info: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72445
  Introduced through: com.github.java-json-tools:json-schema-core@1.2.9
  From: com.github.java-json-tools:json-schema-core@1.2.9 > com.github.java-json-tools:jackson-coreutils@1.9 > com.fasterxml.jackson.core:jackson-databind@2.2.3

✗ High severity vulnerability found in com.fasterxml.jackson.core:jackson-databind
  Description: Deserialization of Untrusted Data
  Info: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72446
  Introduced through: com.github.java-json-tools:json-schema-core@1.2.9
  From: com.github.java-json-tools:json-schema-core@1.2.9 > com.github.java-json-tools:jackson-coreutils@1.9 > com.fasterxml.jackson.core:jackson-databind@2.2.3

✗ High severity vulnerability found in com.fasterxml.jackson.core:jackson-databind
  Description: Deserialization of Untrusted Data
  Info: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72447
  Introduced through: com.github.java-json-tools:json-schema-core@1.2.9
  From: com.github.java-json-tools:json-schema-core@1.2.9 > com.github.java-json-tools:jackson-coreutils@1.9 > com.fasterxml.jackson.core:jackson-databind@2.2.3

✗ High severity vulnerability found in com.fasterxml.jackson.core:jackson-databind
  Description: Deserialization of Untrusted Data
  Info: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72448
  Introduced through: com.github.java-json-tools:json-schema-core@1.2.9
  From: com.github.java-json-tools:json-schema-core@1.2.9 > com.github.java-json-tools:jackson-coreutils@1.9 > com.fasterxml.jackson.core:jackson-databind@2.2.3

✗ High severity vulnerability found in com.fasterxml.jackson.core:jackson-databind
  Description: Deserialization of Untrusted Data
  Info: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72449
  Introduced through: com.github.java-json-tools:json-schema-core@1.2.9
  From: com.github.java-json-tools:json-schema-core@1.2.9 > com.github.java-json-tools:jackson-coreutils@1.9 > com.fasterxml.jackson.core:jackson-databind@2.2.3

✗ High severity vulnerability found in com.fasterxml.jackson.core:jackson-databind
  Description: Deserialization of Untrusted Data
  Info: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72450
  Introduced through: com.github.java-json-tools:json-schema-core@1.2.9
  From: com.github.java-json-tools:json-schema-core@1.2.9 > com.github.java-json-tools:jackson-coreutils@1.9 > com.fasterxml.jackson.core:jackson-databind@2.2.3

✗ High severity vulnerability found in com.fasterxml.jackson.core:jackson-databind
  Description: Deserialization of Untrusted Data
  Info: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72451
  Introduced through: com.github.java-json-tools:json-schema-core@1.2.9
  From: com.github.java-json-tools:json-schema-core@1.2.9 > com.github.java-json-tools:jackson-coreutils@1.9 > com.fasterxml.jackson.core:jackson-databind@2.2.3

✗ High severity vulnerability found in com.fasterxml.jackson.core:jackson-databind
  Description: Deserialization of Untrusted Data
  Info: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72882
  Introduced through: com.github.java-json-tools:json-schema-core@1.2.9
  From: com.github.java-json-tools:json-schema-core@1.2.9 > com.github.java-json-tools:jackson-coreutils@1.9 > com.fasterxml.jackson.core:jackson-databind@2.2.3

✗ High severity vulnerability found in com.fasterxml.jackson.core:jackson-databind
  Description: Deserialization of Untrusted Data
  Info: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72883
  Introduced through: com.github.java-json-tools:json-schema-core@1.2.9
  From: com.github.java-json-tools:json-schema-core@1.2.9 > com.github.java-json-tools:jackson-coreutils@1.9 > com.fasterxml.jackson.core:jackson-databind@2.2.3

✗ High severity vulnerability found in com.fasterxml.jackson.core:jackson-databind
  Description: Deserialization of Untrusted Data
  Info: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72884
  Introduced through: com.github.java-json-tools:json-schema-core@1.2.9
  From: com.github.java-json-tools:json-schema-core@1.2.9 > com.github.java-json-tools:jackson-coreutils@1.9 > com.fasterxml.jackson.core:jackson-databind@2.2.3
```

**Comment by tghosth** [comment]
Re-opening this issue as I wanted to check the status of JSON Schema, my understanding is that it is now considered stable but I am waiting for final confirmation. I have opened #1914 and will merge when I have final confirmation

**Comment by tghosth** [comment]
At the request of @elarlang, we will make the requirement L3.
