### ISSUE TITLE
V13.2.6: signing requests

### ISSUE THREAD

**Issue by jaxley** [OWASP/ASVS#528]
The wording doesn't seem to accurately describe this:

Current:

> Verify that the message payload is signed to ensure reliable transport between client and service, using JSON Web Signing or WS-Security for SOAP requests.

Proposed:

> Verify that the message headers and payload are trustworthy and not modified in transit.
Requiring strong encryption for transport (HTTPS only) may be sufficient in many cases as it provides both confidentiality and integrity protection.  Per-message digital signatures can provide additional assurance on top of the transport protections for high-security applications but bring with them additional complexity and risks to weigh against the benefits.

Signing requests adds several additional items to the attack surface of a client and server (in order to sign, the client and server need key establishment and key protections).

1. The JOSE standards that JSON Web Signatures are a subset of, have shown to be problematic due to the ciphersuite agility and the complexity of the standard.
2. Proper signature by the client requires key establishment and secure key storage.  This will not be available to all clients of all services (e.g. web clients).  This is a nontrivial endeavor.
3. JSON payload is not the *only* data that may require integrity protection in a request.  Services often depend on HTTP headers for routing and other things so they can have integrity assured.
4. If you are including in the threat model a MiTM attacker who can see and modify plaintext, then you would also need to consider a MiTM attacker who can implement replay attacks as well.  Knowing that a message was not modified is not strictly required to prevent unauthorized requests.  Replaying captured messages that are already signed (e.g. a message to delete an object) can still accomplish the attacker's goal.  So any threat model would need to consider message replay prevention as well.

I would suggest that for high-security applications, an approach that replaces bearer tokens with a proof-of-possession plus a request digital signature would be ideal.  That's akin to what AWS has done with its request signature approach. You get authentication and integrity protection in one and mitigate MiTM disclosure of API token risk.  But it's nontrivial to get requests to be canonicalized and ensure the right bits are protected for integrity.  And it does still require key establishment (although they use a key derivation algorithm with the existing secret key to generate dynamic signature keys)

**Comment by jmanico** [comment]
Like this, do you have time to give us a pull request?

**Comment by vanderaj** [comment]
Thank you for the suggestion. I've incorporated it and included a tweak to its close cousin in V13.3.

**Comment by jaxley** [comment]
Thanks!  Sorry, was out of pocket and couldn't respond
