### ISSUE TITLE
New item: consistent controls on authentication and identity management APIs

### ISSUE THREAD

**Issue by jaxley** [OWASP/ASVS#529]
An issue that continues to bite dev teams is creation of APIs that allow identity management operations (password changes, authentication, etc.) but don't include the 

Suggested item:

> Any authentication or identity management APIs must implement consistent security controls for all API versions and with any user interfaces. UI logic needs to be part of the service for consistency.

Some examples would be, ensure API responses do not leak information (e.g. user existence) that is not available in other channels (e.g. the UI or other versions of the same API).  Ensure APIs for authentication prevent brute-force password guessing attacks with the same protections as other channels.  e.g. https://hackerone.com/reports/127202

**Comment by vanderaj** [comment]
Discussion co-leaders?

**Comment by vanderaj** [comment]
My $0.02 - This might be a V1.2 Architectural issue, as I believe if we include this in V13 API and V2, it would be a duplicate control in both. 

That said, it's getting pretty late for new content for 4.0. I'll see what happens as I move architectural controls from chapters to V1. If I can include it, I will.

**Comment by jaxley** [comment]
Perfect.  Tks
