### ISSUE TITLE
Data Integrity Requirements

### ISSUE THREAD

**Issue by mgrinsven** [OWASP/ASVS#53]
Hi Andrew,

I have been reviewing ASVS and have some general remarks or discussion points. I cannot find clear statements about Data Integrity. The scope of ASVS seems to focus on user - machine interaction. But webservices are also used for machine - machine interaction (also using the internet). In machine - machine interaction, data integrity is an important aspect.

You want to make sure that the data transported between two machines has not been altered in any way and that the originator can be identified. 
So some words about signing, WS-Security, WS-RM, ebMS and so on would be a goodd addition. In large organisations (like government or financial institutions) the chain between originator and destination van be quite long and.

I do not know if this has been discussed before, but would like to hear some feedback about this.

A second general remark is that some verification requirements can involve network architecture and components. In large organisations there can be a split between hardware/infrastructure/middleware and software development. Because of this it would be great if the requirements that involve hardware / middleware / network would be marked as such (perhaps a different color).

**Comment by vanderaj** [comment]
Hi there,

I've updated the integrity controls within the web service section. 

There is an effort I believe to create a network / infrastructure version of ASVS. I think it might be out of scope for us to deal with that here, but we will probably work on an ASVS 4 for next year, so instead of closing this issue out, I am going to bump it to the next version.

**Comment by vanderaj** [comment]
So if you have a check list for infrastructure that you'd think is a good starting point, please let us know.

**Comment by vanderaj** [comment]
@mgrinsven can you please check the latest draft and see if there are specific areas we need to include integrity controls? I'm thinking:

V2 Authentication - as this controls who can access which identity, so integrity over IAM data
V4 Access Control - as this controls who can access which data, so integrity over access control matrices and metadata
V9 Data Protection - as this is critical and probably where we need to add more guts to the standard
V19 Configuration - as this is the metadata to the entire thing. There are requirements that asks for the application to be signed and configuration to be signed, but looking to see if we need to beef this up
V20 IoT - has a lot of integrity controls built in. Happy to take advice on this if you think it's relevant.

**Comment by mgrinsven** [comment]
Thanks, i will have a look at them

**Comment by vanderaj** [comment]
Hi there,

Please let me know how you go with the new draft. We've received a bunch of
excellent feedback which highlighted much the same concepts, so feel free
to reply to those if you feel reviewing the entire thing again is
problematic.

thanks
Andrew

**Comment by vanderaj** [comment]
@mgrinsven - We have just pushed an additional control in V9 relating to encryption of private data. We are likely to make a few more, could you please review.
