### ISSUE TITLE
V12.6.1 - open redirect description in SSRF subcategory

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#535]
**subcategory**
V12.6 SSRF Protection Requirements

**requirement**
12.6.1 Verify that URL redirects and forwards only allow whitelisted destinations, or show a warning when redirecting to potentially untrusted content.

**problem**
Requirement 12.6.1 is not limited to Server-Side Request Forger and describes/covers Open Redirect (which is in most cases command to client)

**recommendation**
Fix the mismatch.
At the moment id does not feel correct but I don't have one-and-only clear recommendation how it should be fixed.
Requirement is not clear SSRF. If to watch it as open redirect (for browser), it does not even belong to V12 category.

**Comment by pich4ya** [comment]
Agreed.

**Comment by tghosth** [comment]
Opened #567 to address

**Comment by tghosth** [comment]
This has now been merged
