### ISSUE TITLE
Possible Issues with L1 Items & Grey-Box Testing

### ISSUE THREAD

**Issue by adamcaudill** [OWASP/ASVS#536]
I have reviewed all of the L1 items as they stand today - there are some possible issues with some of these and being able to check for them in an external/third-party grey-box application test (assuming manual & automated testing). Here are the items I found that could be problematic, and suggestions for each. 

This list has turned out to be substantially larger than I expected, so apologies for such a large list - 3.0 was far closer to working for grey-box tests than 4.0 is currently, even with some of the changes that have already been made to better align L1 with grey-box testing.

A notable percentage of these items appear to be the result of #534 - as these controls were set to L1, though not all are testable without access to source code, systems, logs, or documentation that would be considered proprietary (I'm reviewing this from the perspective of a third-party tester).

Section [10.3](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x18-V10-Malicious.md#v103-deployed-application-integrity-controls) is somewhat problematic in its entirety - I'm honestly not sure how to address it. Should it be moved to L2? I'm not sure what the right route for it is - it's not something that could be addressed in an external/third-party grey-box application test. It's not included in either list below, as I'm honestly not sure what the right approach for it is.

#### Addressable via Interview / Questionnaire / Documentation Request

Some of the items that have issues can't be tested for, simply by their nature. For these items, it's possible to address them via interviews, a questionnaire, or through requesting documentation. Using this approach, it would still be possible to meet L1 requirements in an external/third-party grey-box application test.

For these items, this is the best solution I see - as I'm not sure changing them to L2 makes sense.

* [1.1.1](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x10-V1-Architecture.md#v11-secure-software-development-lifecycle-requirements) - "Verify the use of a secure software development lifecycle that addresses security in all stages of development. (C1)"
* [1.1.5](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x10-V1-Architecture.md#v11-secure-software-development-lifecycle-requirements) - "Verify definition and security analysis of the application's high-level architecture and all connected remote services. (C1)"
* [1.1.6](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x10-V1-Architecture.md#v11-secure-software-development-lifecycle-requirements) - "Verify implementation of centralized, simple (economy of design), vetted, secure, and reusable security controls to avoid duplicate, missing, ineffective, or insecure controls. (C10)"
* [1.2.1](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x10-V1-Architecture.md#v12-authentication-architectural-requirements) - "Verify the use of unique or special low-privilege operating system accounts for all application components, services, and servers. (C3)"
* [8.3.4](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x16-V8-Data-Protection.md#v83-sensitive-private-data) - "Verify that all sensitive data created and processed by the application has been identified, and ensure that a policy is in place on how to deal with sensitive data. (C8)"
* [14.2.5](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x22-V14-Config.md#142-dependency) - "Verify that an inventory catalog is maintained of all third party libraries in use. (C2)"

#### Untestable via Grey-Box

These items, as they stand, can not be tested for in an external/third-party grey-box assessment. It's possible that some of these could be moved up to the category above, though it would be impossible for the tester to verify.

* [1.2.2](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x10-V1-Architecture.md#v12-authentication-architectural-requirements) - "Verify that communications between application components, including APIs, middleware and data layers, are authenticated with the least necessary privileges. (C3)" - *Recommend moving this to L2*
* [1.14.5](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x10-V1-Architecture.md#v114-configuration-architectural-requirements) - "Verify that application deployments adequately sandbox, containerize and/or isolate at the network level to delay and deter attackers from attacking other applications, especially when they are performing sensitive or dangerous actions such as deserialization. (C5)" - *Recommend moving this to L2*
* [2.4.1](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#v24-credential-storage-requirements) - "Verify that passwords are stored in a form that is resistant to offline attacks. Passwords SHALL be salted and hashed using an approved one-way key derivation or password hashing function. Key derivation and password hashing functions take a password, and a cost factor as inputs then generate a password hash. (C6)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code.*
* [2.4.2](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#v24-credential-storage-requirements) - "Verify that the salt is at least 32 bits in length and be chosen arbitrarily to minimize salt value collisions among stored hashes. For each credential, a unique salt value and the resulting hash SHALL be stored. (C6)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code.*
* [2.4.3](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#v24-credential-storage-requirements) - "Verify that if PBKDF2 is used, the iteration count SHOULD be as large as verification server performance will allow, typically at least 100,000 iterations. (C6)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code.*
* [2.4.4](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#v24-credential-storage-requirements) - "Verify that if bcrypt is used, the work factor SHOULD be as large as verification server performance will allow, typically at least 13. (C6)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code.*
* [3.1.1](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x12-V3-Session-management.md#v31-fundamental-session-management-requirements) - "Verify the application never reveals session tokens as GET parameters in URLs, in error messages, or in log files." - *Recommend splitting this into two items; adding a new item that addresses log files at the L2 level, leaving GET parameters and error messages at L1.*
* [3.2.2](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x12-V3-Session-management.md#v32-session-binding-requirements) - "Verify that session tokens use approved cryptographic algorithms with at least 64 bits of entropy. (C6)" - *Recommend splitting this item into two, one that addresses entropy (testable via grey-box), and one that addresses the use of approved cryptographic algorithms at L2 (as source code access is needed to confirm the algorithms used).*
* [4.2.3](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x12-V4-Access-Control.md#42-operation-level-access-control) - "Verify that there is only one vetted access control mechanism for protecting access to protected data and resources which all requests must go through. This should mean that hard coded access control checks are not required throughout the application. (C7)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code.*
* [4.2.4](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x12-V4-Access-Control.md#42-operation-level-access-control) - "Verify that attribute or feature-based access control is used whereby the code checks the user's authorization for a feature/data item rather than just their role. Permissions should still be allocated using roles. (C7)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code.*
* [5.1.1](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x13-V5-Validation-Sanitization-Encoding.md#51-input-validation-requirements) - "Verify that input validation is enforced on a trusted service layer. (C5)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code.*
* [5.3.1](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x13-V5-Validation-Sanitization-Encoding.md#53-input-sanitization-and-output-encoding-requirements) - "Verify that output encoding occurs close to or by the interpreter for which it is intended. (C4)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code.*
* [6.2.2](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x14-V6-Cryptography.md#62-algorithms) - "Verify that industry proven or government approved cryptographic algorithms, modes, and libraries are used, instead of custom coded cryptography. (C8)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code.*
* [6.2.4](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x14-V6-Cryptography.md#62-algorithms) - "Verify that random number, encryption or hashing algorithms, key lengths, rounds, ciphers or modes, can be reconfigured, upgraded, or swapped at any time, to protect against cryptographic breaks. (C8)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code.*
* [6.4.1](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x14-V6-Cryptography.md#64-secret-management) - "Verify that a secrets management solution such as a key vault is used to securely create, store, control access to and destroy secrets. (C8)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code.*
* [6.4.2](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x14-V6-Cryptography.md#64-secret-management) - "Verify that key material is not exposed to the application but instead uses an isolated security module like a vault for cryptographic operations. (C8)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code.*
* [7.1.1](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x15-V7-Error-Logging.md#v71-log-content-requirements) - "Verify that the application does not log credentials, session tokens or payment details. (C9, C10)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code or log files.*
* [7.1.2](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x15-V7-Error-Logging.md#v71-log-content-requirements) - "Verify that the application does not log other sensitive data as defined under local privacy laws or relevant security policy. (C9)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code or log files.*
* [7.1.3](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x15-V7-Error-Logging.md#v71-log-content-requirements) - "Verify that the application logs security relevant events including successful and failed authentication events, access control failures, deserialization failures and input validation failures. (C5, C7)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code or log files.*
* [7.1.4](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x15-V7-Error-Logging.md#v71-log-content-requirements) - "Verify that each log event includes necessary information that would allow for a detailed investigation of the timeline when an event happens. (C9)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code or log files.*
* [7.2.3](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x15-V7-Error-Logging.md#v72-log-processing-requirements) - "Verify that a common logging format and approach is used across the system. (C9)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code or log files.*
* [7.3.1](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x15-V7-Error-Logging.md#v73-log-protection-requirements) - "Verify that the application appropriately encodes user-supplied data to prevent log injection. (C9)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code.*
* [7.3.2](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x15-V7-Error-Logging.md#v73-log-protection-requirements) - "Verify that all events are protected from injection when viewed in log viewing software. (C9)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code.*
* [7.3.3](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x15-V7-Error-Logging.md#v73-log-protection-requirements) - "Verify that security logs are protected from unauthorized access and modification. (C9)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code.*
* [7.3.4](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x15-V7-Error-Logging.md#v73-log-protection-requirements) - "Verify that logs are securely transmitted to a preferably remote system for analysis, detection, alerting, and escalation. (C9)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code.*
* [7.3.5](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x15-V7-Error-Logging.md#v73-log-protection-requirements) - "Verify that time sources are synchronized to the correct time and time zone. Strongly consider logging only in UTC if systems are global in nature to assist with post-incident forensic analysis. (C9)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code.*
* [8.3.7](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x16-V8-Data-Protection.md#v83-sensitive-private-data) - "Verify that sensitive or private information that is required to be encrypted, is encrypted using approved algorithms that provide both confidentiality and integrity. (C8)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code.*
* [11.1.7](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x19-V11-BusLogic.md#v111-business-logic-security-requirements) - "Verify the application monitors for unusual events or activity from a business logic perspective. For example, attempts to perform actions out of order or actions which a normal user would never attempt. (C9)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code.*
* [14.2.1](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x22-V14-Config.md#142-dependency) - "Verify that all components are up to date, preferably using a dependency checker during build or compile time. (C2)"  - *Recommend moving this to L2 - there's no way to verify this without access to application source code (with the exception of JavaScript libraries served to the user).*
* [14.2.4](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x22-V14-Config.md#142-dependency) - "Verify that third party components come from pre-defined, trusted and continually maintained repositories. (C2)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code.*
* [14.2.6](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x22-V14-Config.md#142-dependency) - "Verify that the attack surface is reduced by sandboxing or encapsulating third party libraries to expose only the required behaviour into the application. (C2)" - *Recommend moving this to L2 - there's no way to verify this without access to application source code.*

**Comment by vanderaj** [comment]
Thank you for such an extensive review. Dealt with all of these, plus a couple of others I found. Sometimes L2 might be testable, but not important. In this case, we might take the view that is it actually required to be tested, and if not, then should we remove it.

**Comment by adamcaudill** [comment]
@vanderaj It looks like two of the changes were reverted in a later [commit](https://github.com/OWASP/ASVS/commit/d4444476d8c74c5faac2653d90bb4ffb0a448b01#diff-53e8e9816a05465c2b6b23fcb3479d86) - two of the logging items that were changed to L2 where re-added to L1. Just checking to make sure this was intentional.

**Comment by tghosth** [comment]
These are part of the OWASP Top 10 which I believe is why there were made L1
