### ISSUE TITLE
V6.4: Key Rotation & Replacement

### ISSUE THREAD

**Issue by adamcaudill** [OWASP/ASVS#538]
For 6.4, I would like to suggest the following additions:

> Verify that a mechanism exists to re-encrypt existing data using new key material in the event that key material is exposed, or key rotation is otherwise required. (L2)

and

> Verify that a key management policy exists, that defines access to key material, key creation and destruction processes, key rotation process, and key material exposure procedures. (L3)

These two items ensure that the lifetime of key material is defined, and that there is a way to recover from key material being exposed to unauthorized parties. Data re-encryption after key material exposure is an area that many organizations have issues with, and pushing them to address this will allow them to handle these events in a much smoother way than most can today.

**Comment by tghosth** [comment]
hi @adamcaudill do you think [section 1.6](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x10-V1-Architecture.md#v16-cryptographic-architectural-requirements) covers this?

**Comment by adamcaudill** [comment]
I must have forgotten about 1.6 when I was reviewing section 6 - yes, I think that's sufficient. Thanks for pointing that out.
