### ISSUE TITLE
V11.13 no-sniff

### ISSUE THREAD

**Issue by kravietz** [OWASP/ASVS#54]
There's a typo in the header value - it should be "nosniff" instead of "no-sniff". I would also suggest to reword this into the following:

*Verify that all API responses contain X-Content-Type-Options: nosniff and Content-Disposition: attachment; filename="api.json" (or other appropriate file name for the content type).*

Adding Content-Disposition to API responses helps prevent many attacks based on misunderstanding on the MIME type between client and server, and the "filename" option specifically helps prevent [Reflected File Download](https://www.blackhat.com/docs/eu-14/materials/eu-14-Hafif-Reflected-File-Download-A-New-Web-Attack-Vector.pdf) attacks.

**Comment by vanderaj** [comment]
Resolved.
