### ISSUE TITLE
Preface - "controls that cannot get you hacked"?

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#540]
I'm not fully sure what is meant with the sentence "Lastly, we have de-duped and retired **controls that cannot get you hacked**.", it doesn't seem to make sense to me. It seems to imply that the controls we don't retire would then be the ones that could get you hacked, which seems counterproductive. Finally I think it's wrong to say that a control can/cannot get you hacked, it's rather a weak or missing control that could contribute to something being hacked.

**Comment by vanderaj** [comment]
Thank you for pointing this out!
