### ISSUE TITLE
How to use this standard - Level 3 - grammar change

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#541]
Last paragraph - first sentence: "An application at ASVS Level 3 requires more in depth analysis, architecture, coding, and testing than all the other levels.", suggest change to "An application at ASVS Level 3 requires more in depth analysis **of** architecture, coding, and testing than all the other levels." as it sounds wrong to say something requires more in depth architecture and coding. 

Last paragraph - second sentence: "A secure application is modularized in a meaningful way (to facilitate e.g. resiliency, scalability, and most of all, layers of security), and each module (separated by network connection and/or physical instance) takes care of its own security responsibilities (defense in depth), that need to be properly documented. ", change first parenthesis so sentence become "A secure application is modularized in a meaningful way (**e.g., to facilitate resiliency,** scalability, and most of all, layers of security), and each module (separated by network connection and/or physical instance) takes care of its own security responsibilities (defense in depth), that need to be properly documented. "

**Comment by tghosth** [comment]
Addressed in https://github.com/OWASP/ASVS/commit/2de29a7abb01249255753fb2d413c55bd6de86e6
