### ISSUE TITLE
Guidance for Certifying Organizations - "failed tests" instead of "failed issues"?

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#543]
Second paragraph - first sentence - "Historically, penetration testing and secure code reviews have included issues “by exception” - that is only **failed issues** appear in the final report."

I believe it would read better to say "failed tests".

**Comment by tghosth** [comment]
Addressed by https://github.com/OWASP/ASVS/commit/166e0cc555ed9e6f401649d1c55b52abec7a16b2
