### ISSUE TITLE
As a Guide for Automated Unit and Integration Tests - common usernames?

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#544]
"For example, additional tests can be crafted for the test suite for a login controller, testing the username parameter for **common usernames**,..." - I'm not sure what this is meant for, do we mean that usernames should be random or have similar properties as passwords? How do we define a common username? Should people be prevented from using usernames that have been found in data breaches? I'm not sure this is feasible or worth the effort.

**Comment by mastacheata** [comment]
This looks like someone split a requirement that was previously talking about access credentials in general into two separate ones for username and password.

There are however a few common usernames that might be relevant from a security perspective: i.e.: _admin, administrator, root, superuser, moderator_ etc.

**Comment by tghosth** [comment]
Clarified in https://github.com/OWASP/ASVS/commit/da0472e5e09c53f8967cf2206e08475aa5f84f20
