### ISSUE TITLE
As a Guide for Automated Unit and Integration Tests - account enumeration on password field?

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#545]
Last sentence states "Similarly, a test on the password parameter should include common passwords, password length, null byte injection, removing the parameter, XSS, account enumeration, and more."

I don't see how account enumeration makes sense for the password field, and it can't be tested with the password field in isolation. Usually it would mean testing that an incorrect password with a valid or invalid username produces not observable difference in response or timing to determine whether the username was a valid account. This test belongs to the username and not the password field in my view.

**Comment by mastacheata** [comment]
I disagree.
If you have a combination of username/password field and need to enter both, this test doesn't work on the username field alone. As asking for both is the most common way of authentication, I'd argue you always need to apply such a test to both fields in combination as you can't find anything out without taking the other field into account.

**Comment by tghosth** [comment]
I have removed it for now in commit https://github.com/OWASP/ASVS/commit/3771a1b5ccc53a456c0edf1d82c69c451907c312 as it is a little confusing.
