### ISSUE TITLE
V1 - Control Objective - "may know a great deal better way"

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#547]
The end of the sentence "All too often, security is seen as inflexible and demanding that developers fix code in a particular way, when the developers may know a **great deal better way** to solve the problem." sounds strange. Perhaps change to "All too often, security is seen as inflexible and demanding that developers fix code in a particular way, when the developers may know a **great deal about a better way** to solve the problem."

**Comment by mastacheata** [comment]
Not a native english speaker, but "a great deal better" and "a great deal about a better sth." does not mean the same thing.
"A great deal better way" is just a convoluted saying for "a much better way".
Therefore I'd propose just using this simpler wording instead.

> when the developers may know a **much better way** to solve the problem.

**Comment by tghosth** [comment]
This was addressed
