### ISSUE TITLE
V1 - Control Objective - "SAML is neither the best or remain the authentication solution"

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#548]
This sentence sounds strange: 
"SAML is neither the best or remain the authentication solution - it might be swapped out with JWT or similar as needs arise. "

Suggested edit:
"However, SAML will not always remain as the best or most suitable authentication solution - it might need to be swapped out for other solutions as requirements change."

**Comment by tghosth** [comment]
Yeah I agree, see: https://github.com/OWASP/ASVS/commit/5cade888efe1578bd8f44cf4ac1f2a1cdbf3a148
