### ISSUE TITLE
Reword requirements - remove "verify that"

### ISSUE THREAD

**Issue by countermode** [OWASP/ASVS#55]
Since this is a verification standard, it is not necessary to start every requirement with "verify that". I suggest to reword the statements "verify that X holds" to "X shall hold" or "X must hold".

**Comment by vanderaj** [comment]
I've resisted the MAY, SHOULD and MUST definitions of RFC 2119 as we have L1, 2 and 3. I will think about a different way. Let's look at some alternatives. The last one is probably what you are suggesting, but we as currently straddle the passive voice MUST meaning, and weasel out of MUST for L1 and L2 in most cases by not requiring it (thus meaning MAY for L1 in most cases). I was trying to avoid that confusion by not using these words in our requirements. 

"Verify all authentication controls (including libraries that call external authentication services) have a centralized implementation."

"Ensure all authentication controls (including libraries that call external authentication services) have a centralized implementation."

"All authentication controls (including libraries that call external authentication services) should have a centralized implementation."

**Comment by vanderaj** [comment]
After discussions with Dan Cuthbert, we are not going to change this for v3.0.
