### ISSUE TITLE
V1.9.2 - Change "person-In-the-middle attacks." to "man-in-the-middle attacks"?

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#550]
The text at the end of the sentence "Verify that application components verify the authenticity of each side in a communication link to prevent **person-In-the-middle** attacks." looks a bit strange. Apart from the formatting, I think people are much more used to the term "man-in-the-middle".

**Comment by mastacheata** [comment]
This must be an attempt to make the text more diverse.
Not sure how widespread this phenomenon is in the english language that doesn't have an intrinsic gender for words, but over here in Germany applying all/removing all genders to/fom language is a huge trend.

**Comment by tghosth** [comment]
Person in the middle is indeed preferable. I am sure people will get used to it :)
However, thanks for pointing out that "In" should be "in" ;)
