### ISSUE TITLE
V1.12.2 - Change "downloaded by" to "downloaded from"

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#551]
The sentence "Verify that user-uploaded files - if required to be displayed or **downloaded by the application** - are served by either octet stream downloads, or from an unrelated domain, such as a cloud file storage bucket." seems to indicate the file is downloaded by the application, but I think the intention is to say "displayed or downloaded from the application".

**Comment by tghosth** [comment]
Committed https://github.com/OWASP/ASVS/commit/17c68363ce9344a594fb415524af161318973ea4
