### ISSUE TITLE
V3.4.5 - Misleading advice on host and domain

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#556]
The statement "Verify that cookie-based session tokens utilize the 'host' attribute. If the 'host' attribute is missing ensure the 'domain' attribute is set and is as precise as possible." is wrong. There is no host attribute for cookies. What it probably means is to make use of the __Host-prefix in cookie names. 

The second advice about the domain is also wrong, you can only decrease security by setting it and it is forbidden to set if you are to use the __Host- cookie prefix.

Please see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Cookie_prefixes for  reference.

**Comment by securitybits** [comment]
@elarlang I think the advice we should give is to leave out the domain attribute and not set it at all. We should also encourage use of the __Host- cookie prefix.

**Comment by elarlang** [comment]
> I think the advice we should give is to leave out the domain attribute and not set it at all.

Yes. To use Host instead of domain is first recommendation.

> We should also encourage use of the __Host- cookie prefix.

Described my opinion in https://github.com/OWASP/ASVS/issues/555#issuecomment-467320056
