### ISSUE TITLE
V10.8 should be dropped

### ISSUE THREAD

**Issue by kravietz** [OWASP/ASVS#56]
In my opinnion, the V10.8 guideline is obsolete and confusing. The referenced FIPS 140-2 standard is indended for United States government organisations and not general public in the global public. It makes no sense to recommend usage of US FIPS-approved algorithms to global commercial businesses, especially that many of these algorithms mentioned in FIPS are old and deprecated like 3DES.

**Comment by vanderaj** [comment]
Resolved.
