### ISSUE TITLE
7.1.1 - "application does not log" > "does not log as plain-text"

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#563]
Originally proposed/recommended in issue #560.

**requirement**
7.1.1 Verify that the application does not log credentials, session tokens or payment details.

**problem**
In reality, for debuging/tracking/investigate there is still need to log session identifier somehow - in practice same hash of session id is logged instead of original session id.

**recommendation**
Maybe 7.1.1 should be widened to something like "does not log" > "does not log as plain-text". Recommendation how to log should be given. Otherwise some may start logging them in base64 encoding.

**Comment by tghosth** [comment]
Why is a valid session ID needed in the log?

How would a hashed ID help?

(Apologies for brevity)

**Comment by elarlang** [comment]
You can filter one user/session related logs. Helps investigating.

**Comment by tghosth** [comment]
Ok so all it needs to be is a value which uniquely identifies a set of log entries which all belong to the same logged in session?

**Comment by adamcaudill** [comment]
If this change is made, I would say that that advice should be quite specific - in addition to base64 as mentioned, you could also see session tokens in other reversible forms, such as encrypted tokens. 

Assuming adequate entropy, a hashed session token would effectively be impossible to reserve - if it was encrypted, you suddenly have another encryption key in play, that if exposed in a config file or the like, could render the protection of the token moot.

**Comment by tghosth** [comment]
Hashed would make sense to me

**Comment by tghosth** [comment]
What do you think about #564

**Comment by elarlang** [comment]
> Ok so all it needs to be is a value which uniquely identifies a set of log entries which all belong to the same logged in session?

Yes. This is probably also the reason, why plain-text session id ends up in log file.

> Hashed would make sense to me

+1 for hashed.

**Comment by elarlang** [comment]
Ok for me :)

**Comment by tghosth** [comment]
Merged
