### ISSUE TITLE
V2.1 - "Okta, Ping Identity, Google, and others" - it's hard to be vendor neutral

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#569]
This is a tricky balance, OWASP should be vendor neutral and not promote specific commercial entities, but at the same time I understand we want to give concrete examples as actionable advice. Not sure what the best approach is here, just want to highlight that whoever we use as an example, there will always be someone else left out that may think it's unfair and biased.

**Comment by securitybits** [comment]
This also applies to V2.2.6:

> Verify that where a credential service provider (CSP, such as Azure AD, Facebook, Google, etc)

**Comment by vanderaj** [comment]
Agreed. For the actual verification, it needs to come out. For the informative bit, it might be able to stay. Let me try to address.

**Comment by vanderaj** [comment]
I've moved the explanation to the informative area, made it clear that we don't endorse them, and provided additional context. I removed vendors from all other sections, including a verification.
