### ISSUE TITLE
remove excessive logging requirements

### ISSUE THREAD

**Issue by countermode** [OWASP/ASVS#57]
Various items require logging to which I strongly disagree. To begin with, in countries with stricter privacy protection laws this kind of logging requires the consent of the users and/or employees. Even if this consent is given, this data is personally identifiable (and this includes even MAC- and IP-addresses as by the European Court of Justice) and must be controlled very strictly. Many enterprises and organizations opt for not logging for this reason. Secondly, what is the benefit of logging without reaction? Most of my customers hoard mounds of data without being able to get any benefit from that.
I propose to replace requirements of the kind "verify that events XYZ are logged" are converted to "verify that events XYZ are properly reacted on".

**Comment by vanderaj** [comment]
This is an interesting issue. Would an first section item on the effect of local laws and regulations that states something like this:

"Local laws, regulations and data privacy directives may override requirements within the Application Security Verification Standard. Where there is any doubt, local laws, regulations and privacy directives apply before requirements stipulated in this standard"

Monitoring and detection are predicated upon both an active response, but also the ability to look back through logs to find other relevant events. I think it might be useful to have some commentary in Chapter v8 on this topic as it's vital and important.

**Comment by vanderaj** [comment]
I've put this in for now at the top of V8

The primary objective of error handling and logging is to provide a useful reaction by the user, administrators, and incident response teams. The objective is not to create massive amounts of logs, but high quality logs, with more signal than discarded noise. 

High quality logs will often contain sensitive data, and must be protected as per local data privacy laws or directives. This should include:

* Not collecting or logging sensitive information if you don’t need it
* Ensuring all logged information is handled securely and protected as per its data classification
* Ensuring that logs are not forever, but have an absolute lifetime that is as short as possible. 

If logs contain private or sensitive data, the definition of which varies from country to country, the logs become some of the most sensitive information held by the application and thus very attractive to attackers in their own right."

I will review the other logging requirements and all of V8 tomorrow. Let me know what you think of the control objective preamble to V8.

**Comment by vanderaj** [comment]
The revised preamble text is now checked in, please download and check.

**Comment by countermode** [comment]
Hello Andrew,

Am 08.07.2015 um 15:04 schrieb Andrew van der Stock:
> This is an interesting issue. Would an first section item on the
> effect of local laws and regulations that states something like
> this:
>
> "Local laws, regulations and data privacy directives may override
> requirements within the Application Security Verification Standard.
> Where there is any doubt, local laws, regulations and privacy
> directives apply before requirements stipulated in this standard"

Hmm, it is the right direction, but I'd prefer a more generic element 
like the SOA of ISO 27001 in the ASVS. There you can dismiss certain 
items on the ground of any reasonable justification, be it legal 
regulations or risk analysis.

> Monitoring and detection are predicated upon both an active response,
> but also the ability to look back through logs to find other relevant
> events. I think it might be useful to have some commentary in Chapter
> v8 on this topic as it's vital and important.

yes please.


Thanks

-- 

There are 10 types of people - those who understand ternary,
those who confuse it with binary, and those who don't get it at all.

**Comment by vanderaj** [comment]
V8.10 has been adjusted:

Verify that the application does not log sensitive data as defined under local privacy laws or regulations, organizational sensitive data as defined by a risk assessment, or sensitive authentication data that could assist an attacker, including user’s session identifiers, passwords, hashes, or API tokens. 

This covers off the text at the beginning and is quite specific. Please let me know if this is sufficient, or if we need to have another go.

**Comment by countermode** [comment]
Hello Andrew,

I think that will do.


Best

Am 11.08.2015 um 06:24 schrieb Andrew van der Stock:
> V8.10 has been adjusted:
>
> Verify that the application does not log sensitive data as defined
> under local privacy laws or regulations, organizational sensitive
> data as defined by a risk assessment, or sensitive authentication
> data that could assist an attacker, including user’s session
> identifiers, passwords, hashes, or API tokens.
>
> This covers off the text at the beginning and is quite specific.
> Please let me know if this is sufficient, or if we need to have
> another go.

-- 
--------------------------------------------------------
Secorvo ist TOP CONSULTANT 2015, Kategorie "IT-Berater"
http://www.secorvo.de/auszeichnungen
--------------------------------------------------------

Dr. Safuat Hamdy
Security Consulting

Secorvo Security Consulting GmbH
Ettlinger Strasse 12-14, D-76137 Karlsruhe
Tel. +49 721 255171-304, Fax +49 721 255171-100
safuat.hamdy@secorvo.de, http://www.secorvo.de
PGP: 6A83 EC49 8474 D77C 1258  AE91 4BB4 8DEE 952A 2506

Mannheim HRB 108319, Geschaeftsfuehrer: Dirk Fox
