### ISSUE TITLE
V2.1.12 - Is this the duty of application developers or browsers?

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#570]
> Verify that the user can choose to either temporarily view the masked entered password, or temporarily view the last typed character of the password.

I'm not sure that this is a fair requirement to put on application developers, if they use the password type for input fields containing passwords (which I think we want them to), then I think it's up to the browser to provide such controls unless I'm missing something. If not actionable by application developers, I would suggest to remove requirements they don't have influence over. If this advice is intended for non-browser-based applications, then I think we may need to clarify this so that web applications are not impacted.

**Comment by vanderaj** [comment]
I've included some informative text with a small clarification on the actual item. Please review and re-open if you think I didn't hit it well enough.

**Comment by Sjord** [comment]
I would like to revisit this issue. As it currently stands, application developers need to implement password revealing functionality to conform to this requirement. I think a `<input type="password">` should be sufficient. @vanderaj, could you consider reopening this issue?

**Comment by elarlang** [comment]
If reopened, then this requirement should be optional (by NIST), not required. See #683

**Comment by Sjord** [comment]
@jmanico Could you take a look at this? I think browsers should implement user-friendly password input fields, and not every web application should implement a custom password input field to conform to this requirement. I think this requirement should be removed, or at least moved from level 1 to level 2 or 3.

**Comment by jmanico** [comment]
I consider this to be the duty of the browser and I’d prefer to see this requirement go. 🤙🏼

**Comment by elarlang** [comment]
I duplicate my comment from PR here.

Personally I don't mind to remove it, but there is some reason, why this requirement was built.

It is a bit larger question - how to be aligned with NIST.

I recommend to carry out all argumentation in (reopened) issue and make PR after some "reaction time".

**Comment by jmanico** [comment]
I'm ready for a PR on this one, we really do not need gestation time. This is a very basic requirement and for web apps the browser handles in. And in general, I am always eager to remove requirements so the really important work here is more clear. So if I see a PR I'll accept it.

**Comment by maizuka** [comment]
The removing of 2.1.12 at #1020 has also removed a requirement that input password is masked.
Should we add this as a new requirement, or is it no longer needed?

My suggestion:
> Verify that passwords are not displayed as plain text in pages and password fields. Input fields should use type=password.
