### ISSUE TITLE
V2.2.4 - Unclear what purpose is of checking unexpected tokens?

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#571]
> Verify that all authentication data provided by the user is checked for validity, even if it is unexpected. For example, if an authentication form offers a username and password and an optional token, the server should always check a token value provided, even if the user was not expected to have a token value to provide.

I'm struggling to see what the intended purpose behind this is, and what a token should be validated against if the user is not expected to have such a token in the first place. Can we clarify what the value of this control is?

**Comment by vanderaj** [comment]
Removed

**Comment by tghosth** [comment]
This was added in response to #996 257 

> Verify that all authentication data provided by the user is checked for validity, even if it is unexpected. For example, if an authentication function checks a username and password and an MFA token, the server should always check the MFA value provided, even if the user was not expected to provide an MFA value.

Not sure if we should put this back for 5.0...

**Comment by tghosth** [comment]
@stevespringett
