### ISSUE TITLE
V2.4 Credential Storage Requirements - misspelling of checklist 

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#572]
> This section cannot be penetration tested, so controls are not marked as L1. However, this section is of vital importance to the security of credentials if they are stolen, so if forking the ASVS for an architecture or coding guideline or source code review **chceklist**, please place these controls back to L1 in your private version.

**Comment by tkisason** [comment]
Suggested fix in: https://github.com/OWASP/ASVS/pull/608

**Comment by vanderaj** [comment]
Resolved. Thank you!
