### ISSUE TITLE
V2.4.1 - Refactor last sentence

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#573]
> Key derivation and password hashing functions take a password, and a cost factor as inputs then generate a password hash.

Suggest change to:

> Key derivation and password hashing functions take a password, a salt, and a cost factor as inputs when generating a password hash.

**Comment by tkisason** [comment]
Suggested fix in: https://github.com/OWASP/ASVS/pull/607

**Comment by vanderaj** [comment]
Resolved.
