### ISSUE TITLE
Consolidate V2.8 and V2.9 or at least harmonize language?

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#575]
It seems that V2.8 and V2.9 are very similar and duplicate most controls, but use slightly different wording (e.g., 2.8.1 vs. 2.9.1 and 2.8.4 vs. 2.9.4):
> Verify that symmetric keys used to verify submitted codes is highly protected, such as using an **HSM or OS based** key storage.

vs.

> Verify that symmetric keys used to verify submitted codes is highly protected, such as using an **hardware security module or secure operating system** key storage.

**Comment by tghosth** [comment]
I am writing this

**Comment by tghosth** [comment]
OK PR #612 opened

**Comment by vanderaj** [comment]
Resolved.
