### ISSUE TITLE
V2.11.2 - "credentials are" or "credential is"

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#576]
> Verify that if passwords are required, **the credential are** not a default account.

I think it sounds better to either use "credential is" or "credentials are".

**Comment by tkisason** [comment]
Suggested fix in: https://github.com/OWASP/ASVS/pull/609

**Comment by tkisason** [comment]
@securitybits , next time send pull requests :) Makes less work for all of us :)

**Comment by vanderaj** [comment]
Resolved! Thank you all
