### ISSUE TITLE
V5.1.6 - should escaping really be under input validation?

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#578]
> Verify that unstructured data is sanitized to enforce safety measures such as allowed characters and length, **and characters potentially harmful in given context should be escaped (e.g. names with Unicode or apostrophes, such as ねこ or O'Hara).**

The second part of this sentence (or perhaps all of it) might fit better under 5.3 Input Sanitization and Output Encoding Requirements

**Comment by elarlang** [comment]
Related issue, reorganising V5 subcategories #523

**Comment by vanderaj** [comment]
Divided last part into 5.3.1, as it was all about CWE 116. No point in having a new item.
