### ISSUE TITLE
V10.10

### ISSUE THREAD

**Issue by kravietz** [OWASP/ASVS#58]
Reword:

*Verify that [TLS certificate public key pinning](https://tools.ietf.org/html/rfc7469) is implemented with production and backup public keys*

https://tools.ietf.org/html/rfc7469 should be linked as in the proposed text. Business continuity is the rationale for explicitly mentioning production and backup keys - see https://noncombatant.org/2015/05/01/about-http-public-key-pinning/

**Comment by vanderaj** [comment]
Resolved
