### ISSUE TITLE
V5.3 - last sentence applies to parameterized queries too 

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#580]
> Note that escaping SQL is not always sufficient; table and column names, ORDER BY and so on, cannot be escaped. The inclusion of escaped user-supplied data in these fields results in failed queries or SQL injection.

As this comes just after 5.3.5, it sounds as if it's a warning about the limitations of escaping only, but the same issue applies to parameterized queries. Suggested edit:

> Note that using parameterized queries or escaping SQL is not always sufficient on its own; table and column names, ORDER BY and so on, cannot be parameterized/escaped. The inclusion of escaped user-supplied data in these fields results in failed queries or SQL injection. In these situations, strict input validation (exact-match whitelist) needs to be used too.

**Comment by tkisason** [comment]
Suggested fix in: https://github.com/OWASP/ASVS/pull/606

**Comment by vanderaj** [comment]
Resolved
