### ISSUE TITLE
V5.4.3 - Integer overflow applies outside this section?

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#581]
> Verify that sign, range, and input validation techniques are used to prevent integer overflows.

5.4.1 and 5.4.2 seems targeted towards C and similar languages, but 5.4.3 applies to a broader range of languages, e.g., Java is affected too. What is our definition of unmanaged code for this section? Is it the literal view of anything outside the .NET CLR or languages where there developer is responsible for memory management?

**Comment by vanderaj** [comment]
I'm going to change the heading to be inclusive of overflows regardless of language.
