### ISSUE TITLE
V5.5.4 - Shouldn't this be Level 1?

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#582]
> Verify that when parsing JSON in browsers or JavaScript-based backends, JSON.parse is used to parse the JSON document. Do not use eval() to parse JSON.

This is a very fundamental requirement and should be testable too, so I don't see why this isn't mandated for Level 1.

**Comment by tkisason** [comment]
Not only for JSON, but XXE and Deserialization wasn't covered by L1, i added them all in this suggestion:
https://github.com/OWASP/ASVS/pull/605

**Comment by vanderaj** [comment]
Thank you - looks to be resolved now. and agree it's a L1 control
