### ISSUE TITLE
6.3 - Replace "True pseudo-random" with "Cryptographically secure pseudo-random"?

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#583]
> True pseudo-random number generation (PRNG) is incredibly difficult to get right. 

This sounds a bit strange to me, psuedo-random means that it's not truly random so "true pseudo-random" is very confusing. 

I think it would be better to replace with something like
> Cryptographically secure pseudo-random number generation (CSPRNG) is incredibly difficult to get right.

**Comment by tkisason** [comment]
True PRNG is difficult to get right, i did edit the statement to say that a cryptographically secure PRNG should be used. 

https://github.com/OWASP/ASVS/compare/master...tkisason:patch-35

**Comment by vanderaj** [comment]
Resolved
