### ISSUE TITLE
V13.3.1 - Should we really advise use of DTD / XSD validation?

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#587]
> Verify that XML schema validation (e.g. DTD or XSD validation) is in place and verified before accepting input.

I'm not convinced that this is sound advice. First of all, DTD processing should preferably be disabled in XML parsers to prevent XXE and XEE attacks. Secondly, by default these validations often rely on validating against the schema pointed to by the XML document itself - e.g., in best case we allow the attacker to define their own criteria for passing validation, and in worst case it could lead to SSRF attacks with the attacker tricking the parser to try load remote schemas from attacker-controlled URI. 

I see more opportunities for developers to introduce issues by following this advice than it does to help them.

**Comment by vanderaj** [comment]
@jmanico please weigh in here

**Comment by m8urnett** [comment]
Agreed. The best you can do is check for valid XML and then validate each individual field used. You definitely do not want DTD checking. 

Ref: https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.md#general-guidance

There are also XSD issues with schema poisoning or SSRF.
