### ISSUE TITLE
14.3 - Superfluous "cross-site" in "cross-site XSS"?

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#589]
> Configurations for production should be hardened to protect against common attacks, such as debug consoles, raise the bar for **cross-site XSS** and RFI attacks, and to eliminate trivial information discovery "vulnerabilities" that are the unwelcome hallmark of many penetration testing reports.

**Comment by tkisason** [comment]
Suggested fix in: https://github.com/OWASP/ASVS/pull/601

**Comment by vanderaj** [comment]
Resolved
