### ISSUE TITLE
14.3.14 - Why not protect against clickjacking in L1?

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#591]
> Verify that a suitable X-Frame-Options or Content-Security-Policy: frame-ancestors header is in use for sites where content should not be embedded in a third-party site.

This is only for Level 2+, but I don't see any reason why this shouldn't apply for Level 1 as well. It's a protection we expect and that most people would test for anyway.

**Comment by tghosth** [comment]
I agree there is no reason why this should not be L1, opened #611

**Comment by tghosth** [comment]
Was merged
