### ISSUE TITLE
Appendix A - CWE - Why not write out what the abbreviation stands for?

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#592]
> CWE - CWE is a community-developed list of common software security weaknesses. It serves as a common language, a measuring stick for software security tools, and as a baseline for weakness identification, mitigation, and prevention efforts.

vs. 

> CWE - Common Weakness Enumeration (CWE) is a community-developed list of common software security weaknesses. It serves as a common language, a measuring stick for software security tools, and as a baseline for weakness identification, mitigation, and prevention efforts.

**Comment by tkisason** [comment]
Suggested fix in https://github.com/OWASP/ASVS/pull/597

**Comment by vanderaj** [comment]
Resolved
