### ISSUE TITLE
Appendix A - PKI - Explain what the abbreviation stands for

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#593]
> PKI – A PKI is an arrangement that binds public keys with respective identities of entities. The binding is established through a process of registration and issuance of certificates at and by a certificate authority (CA).

vs

> PKI – A Public Key Infrastructure (PKI) is an arrangement that binds public keys with respective identities of entities. The binding is established through a process of registration and issuance of certificates at and by a certificate authority (CA).

**Comment by tkisason** [comment]
Suggested fix in https://github.com/OWASP/ASVS/pull/596

**Comment by vanderaj** [comment]
Resolved
