### ISSUE TITLE
Appendix A - SSO - refactor last sentence

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#594]
> SSO Authentication – Single Sign On(SSO) occurs when a user logs into one application and is then automatically logged into other applications without having to re-authenticate. **For example when you log in in Google, you automatically login in the youtube , docs and mail service.**

Suggestion:

> SSO Authentication – Single Sign On(SSO) occurs when a user logs into one application and is then automatically logged in to other applications without having to re-authenticate. For example, when you log in to Google, you will be logged in automatically when accessing other Google services such as Youtube , Google Docs, and Gmail.

**Comment by tkisason** [comment]
Suggested fix in: https://github.com/OWASP/ASVS/pull/599
