### ISSUE TITLE
Splitting V19.1

### ISSUE THREAD

**Issue by marpuch** [OWASP/ASVS#61]
I am very glad to see V19.1 "All components should be up to date with proper security configuration(s) and version(s). This should include unneeded configurations and folders (sample applications)." introduced in the latest standards revision.

What I see here are two OWASP Top 10 points: "A5 Security Misconfiguration" and "A9 Using Components with Known Vulnerabilities" merged into a single ASVS requirement. Does it make sense to split the requirement in two just to put additional pressure on the A9 point just as OWASP Top 10 did? Checking versions and security configurations are pretty different project activities for me. What do you think?

**Comment by vanderaj** [comment]
Agreed.

**Comment by danielcuthbert** [comment]
I'm not sure if it does make sense to split. Sure, they are different activities but if you are doing one, you are doing the other. V19.1 says 'do both'

I'm loathe to copy the Top 10 here
