### ISSUE TITLE
V12.6.1 - move from V12.5 to to V14.2

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#610]
**category - subcategory**
  * V12: File and Resources Verification Requirements
  * V12.5 File Download Requirements

**requirement**
12.6.1 Verify that the web or application server is configured with a whitelist of resources or systems to which the server can send requests or load data/files from.

**recommendation**
By content it's seems to belong more to:
"V14: Configuration Verification Requirements" > "14.2 Dependency"

**Comment by tghosth** [comment]
So 12.6.1 is a specific control related to SSRF (and the only one we have) which is an issue at runtime. V14.2 is talking about dependencies at compile/deploy time which is a different issue.

if you feel like 12.6.1 needs clarifying, a PR would be great but I am closing this one for now :)

**Comment by elarlang** [comment]
I'm a bit sceptical to resolve this issue _only_ runtime. If you have vulnerability in run-time code, you most-likely can bypass runtime checks also. It depends on application and implementation anyway.
