### ISSUE TITLE
question: criterias to get listed as reviewer?

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#615]
What are criterias for contributors/reviewers to get listed?
( https://github.com/OWASP/ASVS/blob/master/4.0/en/0x01-Frontispiece.md )

**Comment by tghosth** [comment]
I believe the list was taken based on PRs but I can see that it should also include issue raisers. I have added you with commit https://github.com/OWASP/ASVS/commit/07b073ac4dd2cb187f16b177710d3a9a70857daa
