### ISSUE TITLE
5.3 description contradicts table

### ISSUE THREAD

**Issue by jsulinski** [OWASP/ASVS#619]
https://github.com/OWASP/ASVS/blob/master/4.0/en/0x13-V5-Validation-Sanitization-Encoding.md#v53-output-encoding-and-injection-prevention-requirements

Erroneous copy: "Many of these items are not directly penetration testable (L1), and so although they are critical to the security of any application, they are L2."

Relevant commits:
https://github.com/OWASP/ASVS/commit/88638d8eefa07546a19c7c54c3c61cc6b988d4d7
https://github.com/OWASP/ASVS/commit/ef292d49c602b9a78711d98d14d46e9f4dc4ee50
https://github.com/OWASP/ASVS/commit/be2d4138ac3a10ea6e0d25b79b4f5aeacd03ffd9

**Comment by vanderaj** [comment]
Fixed in 4.0.1. I had to add a missing credit to the frontispiece, so thank you for this in such a timely fashion!

**Comment by vanderaj** [comment]
Please download the standard again, and you'll have the corrected version.
