### ISSUE TITLE
V20.6 – Missing CSP 2.0 headers

### ISSUE THREAD

**Issue by vizzdoom** [OWASP/ASVS#62]
Enabling XSS Protections in web browsers can be also achieved by CSP 2.0 headers:
`Content-Security-Policy: reflected-xss 'block';`

**Comment by danielcuthbert** [comment]
My concern with CSP and trusting the browser to act as a firewall is that it's easy to bypass still and at the end of the day only gives us a small additional layer of protection. However, it is not a replacement for proper and stringent data input and output validation, which we do mention. 

if we take JavaScript, which most web apps today use heavily, the above default settings would make the site horrible to use.
