### ISSUE TITLE
Link to the Cheat Sheet Series project in section "Appendix B: References".

### ISSUE THREAD

**Issue by righettod** [OWASP/ASVS#620]
Hello,

It is possible to add a link to the OWASP [Cheat Sheet Series](https://www.owasp.org/index.php/OWASP_Cheat_Sheet_Series) project in the section **Appendix B: References** of the ASVS ? 

In order to help to identify which cheat sheet is useful in a section of the ASVS, we have created this dedicated [index](https://github.com/OWASP/CheatSheetSeries/blob/master/IndexASVS.md) and we will maintain it in sync with the ASVS lifecyle.

Thanks you very much in advance.

**Comment by righettod** [comment]
Thanks you very much 😃 
I have noticed a small a typo on the following sentence: *for* is present 2 times.
 > has a number of cheat sheets which will be relevant for for different topics in the ASVS

**Comment by tghosth** [comment]
Oops! Fixed, thanks!

**Comment by righettod** [comment]
You are welcome, thanks a lot for the referencing 😃
