### ISSUE TITLE
v6.1 Data Classification

### ISSUE THREAD

**Issue by hljupkij** [OWASP/ASVS#624]
Is there any reason to have 3 subitems? The main requirement ("Verify that regulated $class data is stored encrypted while at rest, such as") is in all 3 subitems the same, they are only different in data classes (private/health/financial) and examples.

**Comment by vanderaj** [comment]
The activities in each vertical might be different, depending on local laws and regulations. There's always a case for a more encompassing single finding, and if the actions taken by each vertical are identical, then yes, they could be collapsed. 

I would love to get feedback from folks responsible for this in each industry for their feedback.

**Comment by jmanico** [comment]
Unless there is more to be said here I'd like to close this out.
