### ISSUE TITLE
2.5.1 unclear description for system generated initial secret

### ISSUE THREAD

**Issue by mal33** [OWASP/ASVS#625]
It's unclear what is meant by this description
> Verify that a system generated initial activation or recovery secret is not sent in clear text to the user

Could somebody add more details on this requirement ?

**Comment by vanderaj** [comment]
Hi @mal33 it means that if as part of initial sign up or password / credential recovery, that you're not sending a "password" or secret in the clear. It's part of the two items that says don't email passwords. Phrased positively, it would be "send a time-limited random activation code (similar to YouTube entering a code on Apple TV), push notification, or link that can only be used by that user right now". 

Does that help? If so, do we need to clarify this requirement in 4.0.2?

**Comment by mal33** [comment]
Hi @vanderaj,
> Does that help? 

Yes, it was really helpful.

> If so, do we need to clarify this requirement in 4.0.2?

Yes, please

**Comment by tghosth** [comment]
Hi, @vanderaj and @mal33, does #650 do what you need?

**Comment by mal33** [comment]
> Hi, @vanderaj and @mal33, does #650 do what you need?

Looks good to me

Optional : Utilizing a `secured channel`, if possible
