### ISSUE TITLE
2.1.10 (ASVS March 2019) Is unclear

### ISSUE THREAD

**Issue by belalena** [OWASP/ASVS#627]
Please clarify what does it mean 
2.1.10
Verify   that there are no periodic credential rotation or password history   requirements.
--

main question is about " no periodic credential rotation " - what does it mean ? not to ask  user to change password periodically (e.g. once per year) ?

**Comment by MazeOfThoughts** [comment]
I'm not one of the authors, but that's what I've seen this phrase refer to, so you seem to guess right.

**Comment by tghosth** [comment]
Yes @belalena, mandatory password rotation is no longer considered to be good practice.
