### ISSUE TITLE
2.3.3 (ASVS March 2019) Is unclear 

### ISSUE THREAD

**Issue by belalena** [OWASP/ASVS#628]
2.3.3. Verify that renewal instructions are sent with sufficient time to renew time bound authenticators.

What is renewal instructions??

below we see in this section description:  
"Note: Passwords are not to have a maximum lifetime or be subject to password rotation. Passwords should be checked for being breached, not regularly replaced."

**Comment by MazeOfThoughts** [comment]
This is not about a password, it's about authenticators like a yubikey or an authenticator app and the note is to make that distinction clear.

_Such_ an authenticator may be bound to an account only for a limited time and have to be replaced periodically. If that is the case, renewal instructions should be sent, and a replacement bound to the account with enough time left on the original.

**Comment by tghosth** [comment]
Yes I think @MazeOfThoughts of thoughts is correct, @belalena
