### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by mrtnrdl** [OWASP/ASVS#633]
I'd like to help with the translation effort and could provide a german translation. How should I proceed - simply creating a seperate branch and going forward from there?

Cheers,
martin

**Comment by andifalk** [comment]
I could also support translating into German language as well

**Comment by mrtnrdl** [comment]
Are you already in the owasp slack? we could just start and see if anyone else wants to join in.

**Comment by tghosth** [comment]
A German translation would need to created in a "de" directory under the https://github.com/OWASP/ASVS/tree/master/4.0 directory in the same way that the English version lives in a "en" directory under this directory.

Does that help?

**Comment by andifalk** [comment]
@tghosth thanks, so we just create pull requests adding this under this directory 
@mrtnrdl yes I am already on owasp slack

**Comment by tghosth** [comment]
yes, any problems let me know.
