### ISSUE TITLE
Split Level 1 Into 2 Sub-Categories

### ISSUE THREAD

**Issue by ossie-git** [OWASP/ASVS#639]
Pentestability of L1 items has been an on-going issue for a long time (I think I first sent something related to this over 2 years ago although I'm sure it's been an ongoing discussion for an even longer period of time).  More recently, I opened this issue: https://github.com/OWASP/ASVS/issues/290  In the release of v4, we went with only having items that can be pentested as L1 while others started at L2.  Although I understand the reasoning behind this, I still think that this might give clients a false sense of security.  For example, they can have absolutely no logging in place (even though logging is a requirement in the OWASP Top 10) and still pass an ASVS V1 assessment.  An application can store passwords in clear-text and still pass an L1 assessment.  The same goes for other key areas such as: security architecture, etc.

I think a possibly better approach is to create two sub-categories under L1:

L1 - P (Pentestable items)
L1 - O (Non-pentestable)

Items that can be verified using pentesting (or other means) would have an P under the L1 column item while O would be for items that can't be verified in this way.  It would also mean that users who want to use it for just the penetration testing side could continue to do so.  It would also help enforce that companies look beyond pentesting.

I just think that L1 is a pretty decent bar for a lot of applications and that removing a lot of key items from L1 for the sake of pentestability is more harmful than it is useful.  By moving to the above structure, I think we can maintain all the pros of highlighting what can be pentested while being more comprehensive for the overwhelming majority of web apps (L1)

PS.  We can also extend the P/O labelling to L2 and L3 items as well

**Comment by mgargiullo** [comment]
Honestly, there are already ways to address this issue. If you want to perform an assessment that is penetration test only (only items that are tests of controls), then create you're own Level 0 definition, that's what it's for.
 
 However, I do like the guidance of declaring the best way to assess the requirement.  T (test) vs. A (audit). Some requirements are better assessed via an audit, than via a dynamic test, assuming the assessor has the requisite skill set.

**Comment by jmanico** [comment]
I think this is already addressed and I'm closing it out
