### ISSUE TITLE
V20 – Client-side sandboxing

### ISSUE THREAD

**Issue by vizzdoom** [OWASP/ASVS#64]
I am really glad about new ASVS sections, like V20. I have one more suggestion related with enhancing client-site (browser) security.

I saw a lot of web applications which were framing third-party sites – for example, one site (`asvs.audited.com`) used iframe pointing to `books.advertisement.com` (third party). In that situation, potential attacker had a possibility to attack `asvs.audited.com` through infecting `books.advertisement.com`.

In HTML5 and modern web browsers we have `sandbox` attribute for HTML `iframe` element. It helps with fighting against that kind of vulnerabilities. In my opinion, this is very important to use iframe sandboxing in situations when we are pointing to external resources, so I suggest to add an extra ASVS requirement to that. 

Also, there is CSP 2.0 sandbox directive, which can mark any kind of site resources as sandbox (`Content-Security-Policy: sandbox` header). Maybe we should also add the additional ASVS requirement for this header?

**Comment by danielcuthbert** [comment]
don't get me wrong, i love what this brings to apps that make use of iframes but right now, the app would need to support not only html5 but also use iframes and im not sure this is worthy of it being a single V20.9 on that basis. This could possibly be an addition to the next release in my mind.
