### ISSUE TITLE
Links don't work in PDF version of ASVS 4.0

### ISSUE THREAD

**Issue by davewichers** [OWASP/ASVS#645]
There are lots of links, like in the references section for each area, but they don't work in the PDF. There are also C#s at the end of each requirement that look like links, but don't work either. They point to the OWASP common controls.

It appears the links do work in the Word version of ASVS. Can we tweak the way we generate the PDF so the links in the PDF work too?

**Comment by tcaesvk** [comment]
You may get hyperlinked PDF when open Word version and then save as PDF. Current PDF version seems be printed via Microsoft Print to PDF which doesn't generate hyperlink. I hope PDF file in downloads section of the project page should be updated.

**Comment by tghosth** [comment]
So it looks like the PDF is generated manually from the docx rather than automatically. I have regenerated it for now with links working and I guess we will need to remember when people are updating the docx in the future.
