### ISSUE TITLE
ASVS Level 3 includes non-repudation??

### ISSUE THREAD

**Issue by davewichers** [OWASP/ASVS#646]
There are two references in ASVS 4.0 that refer to Level 3 including non-repudiation as a requirement. These references are only in text but not in any actual requirements, as the one non-repudiation requirement was deleted per issue #197.

As such, is it intended that non-repudiation NOT be required at level 3? If so, then the references to non-repudiation should be removed. If it is intended that it IS required, then new (non-audit) non-repudiation requirements need to be added back.  I agree with issue #197, that non-repudiation isn't accomplished via audit logs.

**Comment by commjoen** [comment]
Given https://github.com/OWASP/owasp-masvs/issues/286 I was wondering as well: which non-repudiation requirements are currently in the ASVS?

**Comment by tghosth** [comment]
Hi @davewichers do you have some suggestions for non-repudation requirements off the top of your head?

**Comment by vanderaj** [comment]
Additional requirements would be a 4.1 change, not a 4.0.2. 

@davewichers any chance of some non-repudiation items for 4.1 as a pull request?

**Comment by davewichers** [comment]
Non-repudiation requires proof of the identity of the entity that did the action, and the exact action they did. Typically this involves the creation of some document, and then digitally signing that document in such a manner that can prove:
1) The identity of the signer,
2) The exact document that was signed (i.e., proof that it was not changed/tampered with)

This is discussed here: https://blog.finjan.com/what-is-non-repudiation/ and I'm sure many other places.

Such signatures almost always leverage some kind of PKI, so the signers can sign things (with their private key), and others can verify them (with the signer's public key). In the case of a contract, where both parties can prove it is a binding contract, both parties have to sign the document, and the 2nd signer can include the 1st signer's signature in what they sign (to prove the offerer signed it first), and when the 2nd signer signed everything, that makes it a binding contract (assuming that is what the 2nd signature even means). The 2nd signature could simply indicate proof of receipt, and not necessarily acceptance of the contract.  The MEANING of each signature has to also be defined. But these later points probably go beyond what ASVS needs to talk about as we aren't necessarily talking about contracts here.

So items 1) and 2) first listed is probably as far as ASVS needs to take things on this topic.

**Comment by jmanico** [comment]
I removed the use of the term repudiation and non-repudiation from ASVS in the main branch 3dd73ce and am closing this out.

Can you please add new comments or PR's with your suggested specific requirements and we can add it back in?
