### ISSUE TITLE
Web Sockets ?

### ISSUE THREAD

**Issue by c69** [OWASP/ASVS#649]
There are no mentions of Web Sockets in current version of document (4.0)

As you can guess - very often Websockets are being a second-class citizen, missing some (or all) security mechanisms of their REST counterparts, like schema validation, 1-time use request tokens, data sanitation and so on.

I believe '13.5 Web-Sockets' section should be added to standard.

**Comment by tghosth** [comment]
You make a good point. Could you open a PR with some specific controls?

**Comment by vanderaj** [comment]
This would be a 4.1 merge, not a 4.0.2 merge

**Comment by vanderaj** [comment]
Hi @c69 can you please let us know if you're in a position to create a PR in the proposed sections?

**Comment by Racater** [comment]
Since there was no update on this issue for the last 3 months, I took the matter in hands and created a pull request. This is based on OWASP recommendations and multiple pentests done in our systems. Please suggest improvements or ask for clarifications.

**Comment by jmanico** [comment]
We need the following changes:

1) 13.5.4, 13.5.5, 13.5.6 all need to start with "Verify that".
2) Whitelist needs to change to allow list
3) "you are using" looks like odd language.

I'm going to make these changes myself, I am on it.

**Comment by jmanico** [comment]
Language fixed per dbfd721 and closing
