### ISSUE TITLE
Clarification on 2.1.10 

### ISSUE THREAD

**Issue by guysmithson** [OWASP/ASVS#651]
Hi There, 2.1.10 - Verify that there are no periodic credential rotation or password
history requirements. It relates to CWE 263, which states that passwords should not be allowed to age and therefore a maximum lifetime should be implemented. Can somebody expand on the password history requirement element of this statement - in order to prevent reuse of a password by a user their password history would be required? Also, does "no periodic credential rotation" simply mean that users should never be allowed to reuse a password?

**Comment by tghosth** [comment]
So this is actually saying that credential rotation should not be enforced as per [5.1.1.2 of sp800-63b](https://pages.nist.gov/800-63-3/sp800-63b.html) and therefore password history is irrelevant.

> Verifiers SHOULD NOT require memorized secrets to be changed arbitrarily (e.g., periodically).

The link to CWE-263 is a little bit funny as it says the opposite but it is older and I will leave it for now.
