### ISSUE TITLE
Json with ASVS / NIST requirements?

### ISSUE THREAD

**Issue by javixeneize** [OWASP/ASVS#655]
Hi

Is there any json with the data from ASVS and the mapped NIST controls? I would like to write a tool that checks the controls needed against those two frameworks.

If it does not exist, is this something that can be created? I would be happy to be part of this, if it happens :)

Thanks

**Comment by javixeneize** [comment]
Ok. My idea is to have a service that receives a keyword (eg - database, authentication etc...) and it returns the relevant ASVS/NIST controls related to this. Do you think this would be a good idea? If so, should be part of this project or an independent project?

**Comment by tghosth** [comment]
So I know there is this but not sure if it is updated for V4 and not sure if it includes a conversion to JSON
https://github.com/Santandersecurityresearch/asvs

**Comment by javixeneize** [comment]
Great! Will use this then. I feel its better to keep this as a separate application, although its just an idea inside my head..)

Thanks for the help. I will close the issue now

**Comment by tghosth** [comment]
ok thanks, feel free to share what you come up with :)
