### ISSUE TITLE
Add Hostname Verification (4.3.3?)

### ISSUE THREAD

**Issue by sbani** [OWASP/ASVS#656]
Hi,

I'm currently customizing the document and maybe it's a point that makes sense for more people.

I'm just dropping the sentences here and hope for a good conversation about it:

> Verify that requests for all hostnames are handled and configured properly. Also include testing the default host by opening the IP, a random host and "localhost" in your browser. All options should lead to an expected and configured result.

In my view it should be Level 1.

I'm missing this point because I see this misconfiguration really often in the wild. I'm not a native speaker, but hope my ideas are clear.

Let me know if you need further description.

Best regards

**Comment by jmanico** [comment]
This looks to be in part lan infrastructure issue and not an appsec issue, especially the localhost part.

--
Jim Manico
@Manicode

**Comment by sbani** [comment]
It's true. but many times, the application enables a debug console or other tools for the case of "locahost" in the server host name.
It can be an issue on both ends.

**Comment by m8urnett** [comment]
It is a good point though and something I too see way too much. It can get really bad when you throw regex's into the mix. I think it's an idea that could be further developed and refined to fit in.

**Comment by elarlang** [comment]
In general validating host header is covered by input validation requirement: V5.1.1 Verify that the application has defenses against HTTP parameter pollution attacks, particularly if the application framework makes no distinction about the source of request parameters (GET, POST, cookies, headers, or environment variables).

If "localhost situation" gives you extra debug tools, then: V14.3.2 Verify that web or application server and application framework debug modes are disabled in production to eliminate debug features, developer consoles, and unintended security disclosures.

If you want to create requirement for validating host header, it should belong to V14.5 subcategory "V14.5 Validate HTTP Request Header Requirements"

Additionally, what I have in my "ASVS v4.1 pool" is requirement for validating "IP" headers, example that attacker could not override correct remote-addr (IP) with `X-Forwarded-For: localhost`. Also requirement to V14.5 subcategory.

**Comment by tghosth** [comment]
@sbani any further comments?

**Comment by sbani** [comment]
no @tghosth. I'm not able to add more to the conversation.
I think @elarlang is right with his explanations. It's covered in some of the other points.

I'm still adding some points to our own version of the document because I'm a think being more precise is better although it's redundant.

Thank you all for taking part in this conversion!

**Comment by tghosth** [comment]
ok @sbani, thanks for the input and let us know if you have other ideas!
