### ISSUE TITLE
1.2.1 and 1.2.2 are not really Authentication

### ISSUE THREAD

**Issue by bschach** [OWASP/ASVS#657]
> 1.2.1 Verify the use of unique or special low-privilege operating system accounts for all application components, services, and servers.

In my opinion this is configuration (or maybe Access Control) but not Authentication.

> Verify that communications between application components, including APIs, middleware and data layers, are authenticated with the least necessary privileges.

This sounds like the focus was on least privilege, which is Authorization/Access Control and not Authentication.

How about splitting this into 2 Controls:

- Authentication: Verify that communications between application components, including APIs, middleware and data layers, are authenticated.
- Access Control: Verify that communications between application components, including APIs, middleware and data layers, are performed with individual users with the least necessary privileges.

**Comment by jmanico** [comment]
I think this is a really good idea. Solid clarification.

- Jim

**Comment by elarlang** [comment]
Offtopic for the issue, but do you collect at the moment ideas and fixes for v4.1 or will you modify current version? When next version (v4.1 ?) is planned? (Then I know, when I can start throw my ideas)

**Comment by bschach** [comment]
Cool! Should I just open a PR? Is it "allowed" to change the Control Numbers and Ordering?

**Comment by jmanico** [comment]
Yes please!

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by tghosth** [comment]
Thanks for this @bschach.

I made a couple of minor changes to your PR, could you confirm you agree with them:
https://github.com/OWASP/ASVS/pull/658/commits/2eac0b4dc1868f9dfb571af949cc2da0f80985c6
https://github.com/OWASP/ASVS/pull/658/commits/9f7c1884974d5ec46a6892e3568df4f7ffa212bd

**Comment by tghosth** [comment]
Approved via slack :)
