### ISSUE TITLE
Changelog available

### ISSUE THREAD

**Issue by AresSec** [OWASP/ASVS#660]
Hi,
is anywhere a changelog for the new release 4.0 available? In particular a diff to version 3.1? This would be really helpful.

**Comment by tghosth** [comment]
Unfortunately not. One of the difficulties is that so many changes get made between versions that it would be hard to keep track of that sort of thing. In particular, sections V2, V3 and V4 underwent mapping to NIST so presumably changed a very great deal.

**Comment by AresSec** [comment]
Hi @tghosth ,
thanks a lot for the reply. Just for the background info why I'm asking. I'm the one of the project owner of OWASP SecurityRAT (https://github.com/SecurityRAT/SecurityRAT) and we do provide as inital requirement set a mySQL Dump for OWASP ASVS3.0.1 (https://github.com/SecurityRAT/Security-Requirements). At the moment I update this one to ASVS4.0 and thought it might be easier to figure out the deltas with a changelog :). But nevermind I'll create a new one from scratch then.

Cheers,
Ares
