### ISSUE TITLE
Should 9.2.1 (trusted cert) be Level 1 not Level 2?

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#662]
Should [9.2.1](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x17-V9-Communications.md#v92-server-communications-security-requirements) be a level 1 control? This seems like a must have. If an untrusted cert is used then the TLS is pretty useless, no?

**Comment by vanderaj** [comment]
If this adds a L1 requirement, it needs to go into 4.1, not 4.0.2

**Comment by jmanico** [comment]
We're past 4.0.2, lets finalize this PR please?
