### ISSUE TITLE
Add a cert pinning requirement (L3)?

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#663]
Does ASVS cover desktop apps? If so, should we recommend certificate pinning for level 3? I think this is something that the application and not the OS will have to handle.

However, I note that the introduction says:

> As of version 4.0, the ASVS will focus solely on being the leading web apps and service standard, covering traditional and modern application architecture, and agile security practices and DevSecOps culture.

**Comment by tghosth** [comment]
I also note that [10.3.1](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x18-V10-Malicious.md#v103-deployed-application-integrity-controls) refers to client auto-update which makes it sound like it refers to a desktop app

**Comment by danielcuthbert** [comment]
I agree we should add it

**Comment by jmanico** [comment]
Since we agree desktop apps are out of scope and pinning is not part of the browser anymore, I am closing this out. Please re-open if I closed this ins haste!

**Comment by elarlang** [comment]
If we agreed that it is out of scope, who to close the issue and leave the requirement in standard? :)
https://github.com/OWASP/ASVS/blob/master/5.0/en/0x17-V9-Communications.md#v91-client-communication-security

As Josh was setting it in, would like to get final confirmation from him as well.

**Comment by tghosth** [comment]
Based on this thread and on #803 I think we need to remove the requirement
