### ISSUE TITLE
Parenthesis missing

### ISSUE THREAD

**Issue by carhackpils** [OWASP/ASVS#665]
Hi, there is a parenthesis missing at item 2.2.2 on the xlsx version.

It is currently "... authenticators (such as SMS and email is ...".
It should be "... authenticators (such as SMS and email) is ..."

**Comment by carhackpils** [comment]
Same for the 2.7.1 for the parenthesis around _NIST "restricted"_

**Comment by tghosth** [comment]
Thanks! Please could you submit a Pull Request?

**Comment by danielcuthbert** [comment]
@tghosth manually, but i'll fix

**Comment by tghosth** [comment]
This should get fixed when updated versions are generated for v4.0.2
