### ISSUE TITLE
discussion: ASVS v4.0.* release strategy

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#666]
ASVS as a living standard is not really ok - it makes it hard to use for pentest cases.

Making hotfixes to the latest version is completely ok and by hotfixes I mean fixing typos.
In a hotfix, the meaning (requirement description) and structure (requirement number) should not be changed.

The main problem I have is changing requirement numbers.
Example commit: https://github.com/OWASP/ASVS/commit/c80914a97fa5cdc91cb0dc7db338416611d4096e

If we compare the initial release to today's situation, 12 requirement numbers have been changed. Actual change was done to 2 requirements. Now, if I have done a pentest based on ASVS v4.0.1 let's say in April 2019 and need to do a retest today, I might not be able to keep up to date with the standard, because the changes cause conflicts. 12 requirements have a different number, but the standard version remains the same?

So - it's not possible to take hotfixes from https://github.com/OWASP/ASVS into use, because it's complicated to fix it to a contract. The only option is using https://github.com/OWASP/ASVS from X date (from Y commit). But it means that everyone needs to have their own logic for ASVS "releases".

The same problem is with organizing internal work flow - if I have mapped test cases to requirements, and requirement relations between different standard versions (eg ASVS v3.0.1 and ASVS v4.0.1), I need to have my own ASVS release logic based on change dates or commits from ASVS git.

It's even more confusing from the perspective that the v4.0.1 release was made without any changes to requirements content. Can you clarify, what is the trigger or policy to make new releases?

Recommendation:

* a) [PREFERRED] if some significant changes are made, especially ones involving changing requirement numbers or description meanings, make a new release (e.g. 4.0.2)
* b) if there is a need to reorganize some requirements to other categories and a new release is not an option, please keep all the old numbers as they are.

**Comment by dschwarz91** [comment]
I have the same problem here!
@elarlang : do you still have the numbers of the 12 changed requirements at hand? It would be awesome if you could share them - would save me the time going through the commits. Thanks in advance!

**Comment by elarlang** [comment]
disclaimer: please recheck yourself before taking this information in use

# mapping changes from old (March 2019) to new (August 2019)
* 1.2.1 => 1.14.1
* 1.2.2 => 1.2.1 (need to recheck)
  * commmon: Verify that communications between application components, including APIs, middleware and data layers, are ...
  * old:       ... authenticated and use individual user accounts.
  * new 1.2.1: ... authenticated. Components should have the least necessary privileges needed.
  * new 1.4.4: ... performed with the least necessary privileges.
* 1.2.3 => 1.2.2
* 1.2.4 => 1.2.3
* 1.4.4 => 1.4.5
* 1.4.5 => 1.4.6
* 1.14.1 => 1.14.2
* 1.14.2 => 1.14.3
* 1.14.3 => 1.14.4
* 1.14.4 => 1.14.5
* 1.14.5 => 1.14.6
* 1.14.6 => 1.14.7

# content changes
* V1.12.2 - CSP clarification
* V3.6.1 - CSP clarification
* V3.6.2 - CSP clarification
* V5.2.7 - SVGs clarification
* V5.3.6 - typofix + CSP clarification
* V10.2.4 - do vs does
* V10.2.5 - do vs does
* V11.1.5 - typofix, modeling vs modelling
* V12.1.1 - "cause denial of service" vs "cause denial of service attacks"
* V12.3.1
  * old: Verify that user-submitted filename metadata is not used directly with system or framework file and URL API to protect against path traversal.
  * new: Verify that user-submitted filename metadata is not used directly by system or framework filesystems and that a URL API is used to protect against path traversal.
  * https://github.com/OWASP/ASVS/pull/648
* V14.4.3 - CSPv2 vs CSP

**Comment by dschwarz91** [comment]
Thank you very much @elarlang !

**Comment by dschwarz91** [comment]
I just rechecked it and found two more minor differences:
- 10.3.3 - (autogen-bucket-id.cloud.example.com) -> (*autogen-bucket-id*.cloud.example.com)
- 11.1.2 - CWE 779 -> CWE 799

Furhtermore I think the following was the other way round:
 > 1.2.2 => 1.2.1 (need to recheck) 
 >     old: ... authenticated and use individual user accounts.
 >     new 1.2.1: ... authenticated. Components should have the least necessary privileges needed.

so the new Version of 1.2.1 is "Verify that communications between application components, including APIs, middleware and data layers, are authenticated and use individual user accounts."

**Comment by elarlang** [comment]
Actually, FYI - I ignored all NIST and CWE changes. There were more of them. I only checked requirement number and description.

**Comment by kingthorin** [comment]
This could be addressed by a [Formalized Reference Standard](https://github.com/OWASP/ASVS/issues/715)

**Comment by elarlang** [comment]
What is the plan with next releases?

Will be there v4.0.2? Milestone due date was 10 months ago (https://github.com/OWASP/ASVS/milestones)

**Comment by jmanico** [comment]
4.1 is the next release I think

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by tghosth** [comment]
@vanderaj has previously said that he wants to wait until after the next version of the OWASP Top 10 is released to produce ASVS 4.1

The target release date for the next OWASP Top 10 is mid-Feb 2021 so I doubt we will see a 4.1 before the end of April 2021.

Not currently clear whether there will be a 4.0.2 for now.

**Comment by tghosth** [comment]
@elarlang I am going to close this for now as I think we have clarified the underlying principles. I am going to open a separate issue about v4.0.2.
