### ISSUE TITLE
Include CWE mapping for all ASVS items

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#67]
Please include a CWE mapping for all ASVS items.

**Comment by csphils** [comment]
I'm looking to get ASVS cross mapping to CWE. Is this still going to be implemented? Thanks!

**Comment by skhakimov** [comment]
+1 .Looking to get CWE to ASVS mappings. The documentation says this has already been completed.

**Comment by FreeWillaert** [comment]
+1. The documentation says a mapping to the CWE dictionary should exist, but I can't find it.
Has this idea been abandoned? Could anybody confirm?

**Comment by jmanico** [comment]
@FreeWillaert This is on our short list to address before 4.0

**Comment by vanderaj** [comment]
I've put in a call to Twitter. Abhay Bhargav @abhaybhargav will assist with this

**Comment by abhaybhargav** [comment]
@vanderaj I see that some of the items in the `Architecture` section seem to be difficult to find CWEs for, as they are SDLC and process-related. Any suggestions for these items?

**Comment by abhaybhargav** [comment]
@vanderaj, @tghosth there is a section in a few files called `NIST`, which is in the place of `CWE`. Can I remove that? Let me know if that has to be preserved?

**Comment by jmanico** [comment]
> @vanderaj I see that some of the items in the `Architecture` section seem to be difficult to find CWEs for, as they are SDLC and process-related. Any suggestions for these items?

Just ignore for now

**Comment by jmanico** [comment]
> @vanderaj, @tghosth there is a section in a few files called `NIST`, which is in the place of `CWE`. Can I remove that? Let me know if that has to be preserved?
> 
> Currently, I am adding another CWE column to not mess with that dataset

go ahead and remove if appropriate

**Comment by vanderaj** [comment]
There are only a few chapters left without finalized CWE. I've removed all CWSS columns, and moved CWE to have the same location in all tables, so that in V2 and V3, NIST appears to the right of CWE. If we could have all remaining "tbd" CWEs filled in (or blank if no suitable CWE) by Friday, that would be awesome.

**Comment by abhaybhargav** [comment]
Andrew

Sorry for the delay. I have been snowed in suddenly with some client
engagements. Hoping to sit on this today through friday.

Regards
Abhay Bhargav
Chief Executive Officer
Website: http://www.we45.com


*Note*
The contents of this email (and its attachments) are confidential /
privileged and may be subject to legal privilege. Access to this e-mail by
anyone other than the intended recipient is unauthorised. If you are not
the intended recipient, you may not use, copy, distribute or deliver this
message (or any part of its contents) or take any action in reliance
thereon. If you have received this e-mail in error, please notify us
immediately by e-mail or telephone and delete/destroy the message
immediately.
