### ISSUE TITLE
Privacy requierments

### ISSUE THREAD

**Issue by commjoen** [OWASP/ASVS#673]
As part of https://github.com/OWASP/owasp-masvs/issues/203 I was wondering: are there requirements within the ASVS regarding "the use of privacy enhancing technologies, that support data minimization, anonymization and security of personal data"? Or are there other OWASP projects that cover this?

**Comment by commjoen** [comment]
Similar as to https://github.com/OWASP/ASVS/issues/674 i don't see myself picking this up anytime soon with 2 youngsters in the house. maybe we can close the issue for now or check if someone else can pick it up? apologies for the inconvenience .

**Comment by jmanico** [comment]
We are already addressing privacy in many requirements. I'm going to politely close this out.
