### ISSUE TITLE
Integration with ASVS on possible mobile client device binding

### ISSUE THREAD

**Issue by commjoen** [OWASP/ASVS#674]
As part of https://github.com/OWASP/owasp-masvs/issues/203 we are working on requirements such as https://github.com/OWASP/owasp-masvs/issues/306. Would it be a good idea to collaborate on that subject and have a similar serverside requirement for device binding?

**Comment by tghosth** [comment]
Did you add this requirement to MASVS in the end?

**Comment by commjoen** [comment]
Not yet

**Comment by vanderaj** [comment]
Hi there - I've allocated this to 4.1, as it might require us to make additional room for MASVS content to make it easier for MASVS to align / integrate. 

@commjoen - are you okay with integrating in the 4.1 time frame? It's likely to be February 2021

**Comment by commjoen** [comment]
Sounds like a great plan to me! Let's have a chat about it a bit earlier so we can explore it together.

**Comment by jmanico** [comment]
We are closing in on 4.1, any PR's or more discussion needed?

**Comment by commjoen** [comment]
Hi there, in the mean time our second child got born. So sorry for not picking this up, I completely forgot about it. Maybe it is good to pick this up with the new leadership team of the MSTG?

**Comment by jmanico** [comment]
I'm going to politely close this out and reopen if anyone else is interested in chasing this. I'd rather remove it to clean up existing issues since its non critical I state with respect.
