### ISSUE TITLE
Requirement on session identifiers

### ISSUE THREAD

**Issue by commjoen** [OWASP/ASVS#675]
Maybe I am missing it/overlooking it, but is there a requirement on the entropy of session identifiers?

**Comment by elarlang** [comment]
https://github.com/OWASP/ASVS/blob/master/4.0/en/0x12-V3-Session-management.md

ctrl+f "entropy"

> V3.2.2 Verify that session tokens possess at least 64 bits of entropy.

**Comment by commjoen** [comment]
I did.. i guess i did something wrong. Sorry! And thanks!
