### ISSUE TITLE
Discussion why 8.1.5 and 8.1.6 are only necessary for L3

### ISSUE THREAD

**Issue by dschwarz91** [OWASP/ASVS#677]
Hi everybody.
I just wondered why 8.1.5 (backups of important data) and 8.1.6 (backups stored securely) are only necessary for L3.
Shouldn't they be required for at least L2?
As soon as somebody operates with somehow "important" data (and I think this should be the case for all L2 applications), it is one of the most essential things, in my opinion, to have a simple backup.
Or did I miss any reason behind this decision?
Thanks in advance!

**Comment by tghosth** [comment]
See #503

**Comment by tghosth** [comment]
Hi @dschwarz91, any further comments or can we close this?

**Comment by dschwarz91** [comment]
Sry for my late reply and thank you very much for the reference.
Imho its not really correct to place it in the highest category, just because it is actually a little bit outside of the standards scope (either it's included and treated equally, or not included at all).
However, if it was discussed already and its ok for everybody else, I can also live with it based on the reasoning described at #503 ;-)
