### ISSUE TITLE
Question about 11.1.2 ( requirement about realistic human time)

### ISSUE THREAD

**Issue by belalena** [OWASP/ASVS#680]
11.1.2 
Verify the application will only   process business logic flows with all steps being processed in realistic   human time, i.e. transactions are not submitted too quickly.

Does it mean that realistic human time should be checked when creating / updating / deleting objects (as well as incorrect password sending) so that user can not e.g. create 10000 instanses at the moment?
So it can be count like 1 user (e.g. by session token) can perform operation Create user once per 1 min (e.g.) 

OR it's about "ALL steps" in one action. Case for example - open Add user page and Submit page so that between this two actions - human realistic time (e.g. 30 sec) ?

Smth different at all?
Thank you.

**Comment by tghosth** [comment]
Are you asking if it means that each step must be completed in realistic time or that all steps together must be completed in realistic time?

**Comment by belalena** [comment]
> Are you asking if it means that each step must be completed in realistic time or that all steps together must be completed in realistic time?

"Each step" is one of my variants - for example Open page - Change fields - Update button pressed (between Open and Update should be realistic time to fill fields)

OR

second variant
Realistic time between requests - for example I cannot sent in one sec 100 update requests  (may be restriction one update request from one user per 5 sec or so) 


OR
both


OR 
smth else

**Comment by tghosth** [comment]
I think potentially both...

**Comment by tghosth** [comment]
Any further question @belalena

**Comment by jmanico** [comment]
no change needed, please reopen if needed
