### ISSUE TITLE
Do requirement 3.7.1. and CWE 778 about the same ?

### ISSUE THREAD

**Issue by belalena** [OWASP/ASVS#681]
3.7.1  Verify the application ensures a   valid login session or requires re-authentication or secondary verification   before allowing any sensitive transactions or account modifications.

CWE-778: Insufficient Logging - is mentioned in CWE column
When a security-critical event occurs, the software either does not record the event or omits important details about the event when logging it.

For me it's seems to be about differrent things. Furthermore CWE-778 is mentioned in other requirements: 7.1.3, 7.1.4, 7.2.1

**Comment by tghosth** [comment]
Agree this sounds incorrect, do you have a suggestion for a better CWE/s for these items?

**Comment by philipdturner** [comment]
CWE-306 sounds closer to what this describes.

**Comment by jsulinski** [comment]
Agreed, CWE-306 is the closest I could find.

**Comment by tghosth** [comment]
Thanks all
