### ISSUE TITLE
About Translations

### ISSUE THREAD

**Issue by pkka** [OWASP/ASVS#684]
Can I translate the standard and place a pull request? what is the translation requirements?

**Comment by markderijkinfosec** [comment]
Do you need a translation to the Dutch language? If so I would be happy to assist.

**Comment by tghosth** [comment]
@pkka all translations gratefully received although maybe open an issue with the title being the language you are translating to, hopefully this will avoid duplication. What do you means translation requirements?
@markderijkinfosec I'm not aware of a Dutch translation but maybe just note the suggestion above I made to @pkka

**Comment by pkka** [comment]
I mean when I completed the translation, how should I send it to you?

**Comment by tghosth** [comment]
Open a pull request. Ideal if the translation is in an editable format such as markdown or docx
