### ISSUE TITLE
V14.5.3 - split to "validating Origin request header" and "building Access-Control-Allow-Origin response header" requirements

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#686]
> V14.5.3 Verify that the cross-domain resource sharing (CORS) Access-Control-Allow-Origin header uses a strict white-list of trusted domains to match against and does not support the "null" origin.

Often `Origin` request header is just reflected back to `Access-Control-Allow-Origin` response header, but this requirement contains 2 separate problems.

Recommendation to split requirement to:

1. validating `Origin` request header - an API must not accept request with Origin "null" or with Origin which does not belong to white-list
    - it is diffent from V14.5.2 but it can be merged with it
    - based on that requirement/outcome, server makes decisions
2. building correct `Access-Control-Allow-Origin` response header - user must not be able to control the value for `Access-Control-Allow-Origin` header (or value must be validated against whitelist of accepted domains), because it allows then content reading for browsers with Cross-Origin requests
    - this requirement must belong to subcategory "V14.4 HTTP Security Headers Requirements" (which contains requirements for HTTP response headers)
    - based on that requirement/outcome, browser makes decisions

Why to keep them separately?

1. server must not accept request from "unknown" Origin, and it's not related (without pre-flight requests) anyhow how `Access-Control-Allow-Origin` is built
2. value for `Access-Control-Allow-Origin` may come from some other user-controlled parameter, not only from `Origin` header.

Additional discussion: both requirements may match better with "V13 API and Web Service Verification Requirements" category.

**Comment by tghosth** [comment]
Not sure I understand. What do you mean by "unknown" origin? It seems like saying "whitelist" is a perfectly good catch all, no?

**Comment by elarlang** [comment]
My original idea was to split "input validation" (check the `Origin` header) and Response header (use whitelisted `Access-Control-Allow-Origin` requirements. As those two problems are "close to always" together, then this requirement itself can stay like it is. Otherwise in practice during pen-test we need to report in practice the same problem twice.

As it is API specific (compared to other header validation requirements), then I would like to see it in "V13 API and Web Service Verification Requirements" category.

**Comment by tghosth** [comment]
> As it is API specific (compared to other header validation requirements), then I would like to see it in "V13 API and Web Service Verification Requirements" category.

So maybe open up a separate issue for that and close this one if you are ok with the current wording. Thanks :)
