### ISSUE TITLE
Authentication feedback

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#69]
V2: Authentication Verification Requirements
V2.7: Sentence difficult to read
V2.12: This states ALL authentication decisions. So also successful authentication attempts? It is not always a good idea to log everything, especially in a high load environment
V2.13: Does this have to be formulated in this way? It is a bit technical and perhaps it would be better to just mention that the encryption needs to be of sufficient strength and should withstand brute force attacking the password encryption.
V2.16: Not that easy to understand for not native English speakers
V2.22: Shouldn’t that be forgotten password and recovery paths???
V2.27: That is not correct. Should be something like: Verify that checks against the use of commonly chosen passwords and passphrases (such as “let me in” or “Password1!”) are in place.

**Comment by danielcuthbert** [comment]
done.
