### ISSUE TITLE
Was requirement 2.28 (Auth should respond in the same avg response time) from ASVS 3.0.1 removed in the latest version?

### ISSUE THREAD

**Issue by tw2as** [OWASP/ASVS#690]
In ASVS ver. 3.0.1 we had requirement 

_2.28 Verify that all authentication challenges, whether successful or failed, should respond in the same average response time._

I can't find it now in the latest ASVS ver. 4.0. Was it removed purposely and if so then why?

**Comment by tghosth** [comment]
Interesting, it looks like it. Let's leave this open and we will need to discuss whether this goes back in, in the next release. Thanks!

**Comment by tw2as** [comment]
IMHO it's not only important from technical security side (like finding out through brute force logins) but also from the protection of personal data side as this can give anyone chance to verify if a given person is using a given system.

**Comment by jmanico** [comment]
I would like to propose that we add 

2.2.8 Verify that all failed authentication challenges should respond in the same average response time.

Successful AuthN events will always take longer than failed one, the real issues is failed events need to be consistent. If you like my suggestion can I get a PR please?

**Comment by tw2as** [comment]
IMHO it's OK. In addition to that I would add an example making it something like this:
_the real issues is failed events need to be consistent **(e.g. regardless if the user/login exists or not)**_

**Comment by jmanico** [comment]
I really like that addition, well done @tw2as - Would you like to submit a PR for this?

**Comment by danielcuthbert** [comment]
Acted upon the comments here, which are all valid, and closing this out with the addition of 2.2.8 26cbd67..e0c50ea
