### ISSUE TITLE
Using the ASVS - ... in depth analysis of architecture ...

### ISSUE THREAD

**Issue by tw2as** [OWASP/ASVS#692]
_An application at ASVS Level 3 requires more in depth analysis **or** architecture, coding, and testing than all the other levels._

I believe it actually should be: 

_An application at ASVS Level 3 requires more in depth analysis **of** architecture, coding, and testing than all the other levels._

**Comment by tghosth** [comment]
Can you open a PR :)

**Comment by tw2as** [comment]
https://github.com/OWASP/ASVS/pull/693
