### ISSUE TITLE
Page 10 statement about "black box" testing is abrupt

### ISSUE THREAD

**Issue by willc** [OWASP/ASVS#695]
> However, even if L1 allows "black box" (no documentation and no source) testing to occur, it is not effective assurance and must stop. 

I find it odd that this statement includes an order that you "must stop" an activity. Is this really what needs to be said here? Perhaps it should be less directive, and say something like:

>However, even if L1 allows "black box" (no documentation and no source code) testing to occur, it is often not an effective assurance activity.

**Comment by tghosth** [comment]
We want this to be directive but I would be open to something that is a little less abrupt.

**Comment by tw2as** [comment]
IMHO this might be too abrupt. Especially that sentence above says:

> Level 1 is the only level that is completely penetration testable using humans. All others require access to documentation, source code...

I would just say that the black box testing _is not effective assurance and it's not recommended at any level_.

**Comment by tghosth** [comment]
What do people think about:


> However, even if L1 allows "black box" (no documentation and no source) testing to occur, it is not an effective assurance activity and should be actively discouraged.

**Comment by willc** [comment]
That sounds good to me.
