### ISSUE TITLE
Wrong year for OWASP Top 10

### ISSUE THREAD

**Issue by digininja** [OWASP/ASVS#698]
Page 8 of https://github.com/OWASP/ASVS/blob/master/4.0/OWASP%20Application%20Security%20Verification%20Standard%204.0-en.pdf says:

```
As the OWASP Top 10 2018 is the bare minimum...
```

Should be 2017.

**Comment by digininja** [comment]
It is wrong in the PDF as well, fixed it in PR https://github.com/OWASP/ASVS/pull/699

**Comment by tghosth** [comment]
Thanks, see my comments in #699!
