### ISSUE TITLE
export.py script is broken for me

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#700]
export.py script is broken for me and in the mean time we have "generate-json.py" and "generate-csv.py" which seem to work better.

How do we want to proceed?

**Comment by lfservin** [comment]
would a "Makefile" be the way forward? it would be a more standard way to generate the target files. These "targets" could be created:
* pdf
* doc
* xls
* json
* csv
* all (all of the previous)

It would take all the guessing away. Could be matched with a "configure" file to make sure that python and pandoc are installed.

**Comment by tghosth** [comment]
Sounds good in principle. I believe the [MSTG](https://github.com/OWASP/owasp-mstg) have a clever way of doing this as well? Did you look at that?

**Comment by lfservin** [comment]
I just looked at that, but they seem to have a similar approach to the one in ASVS. they just have all across in a single directory called tools. It might be more convenient to have a makefile and the out the recipes for all other outputs there. 
Should I contribute one? I just need to understand which of all the scripts are still valid. There seems to be a bit of overlap between them.

**Comment by tghosth** [comment]
"generate-json.py" and "generate-csv.py" seemed to work for me but export.py did not. You may need to experiement. Curious to see what you can come up with though :)

**Comment by lfservin** [comment]
i'll create an issue. unfortunately the solution might involve moving the scripts into another directory to "unpollute" the root directory. This is against your pull request guideline. If I do it, I'd love to see it merged (at some point) to the directory, not just rejected. If you say it's ok, I'll create the issue and pull request

**Comment by tghosth** [comment]
Which pull request guideline? I didn't understand what you mean.

**Comment by lfservin** [comment]
this is the text of the pull_request_template.md:
`

This Pull Request relates to issue #...`
here's the file: https://github.com/OWASP/ASVS/blob/master/.github/pull_request_template.md

on a closer read, I might have mixed it with the MASVS guideline. I'll then make a pull request with a tools directory and a Makefile to be able to build this.

**Comment by mgargiullo** [comment]
I ended up taking the export script a bit farther to use in one of our
reporting engines. I built an ASVS Python module that returns an object.

The object contains a list of Objectives as objects, each contain a list of
Sections as objects, which each contain a list of requirements objects.

From there, I can build any format I need.  Let me know if you'd like to
take a look at it... Maybe you can use it.

**Comment by tghosth** [comment]
@mgargiullo this sounds like it would be useful. 
@lfservin, if you create a pull request with the relevant directory, would the script from @mgargiullo then be useful there?

**Comment by lfservin** [comment]
It sure would be useful. But it might replace the other script. It would help to get the script beforehand. @mgargiullo do you have it on GitHub? How can we synchronize?

**Comment by tghosth** [comment]
Hi @mgargiullo @lfservin any progress on this? Would be great to have it done before v4.0.2 which will *hopefully* be around the end of June.

**Comment by lfservin** [comment]
all formats will be created from the makefile. there might be a duplication of code, inherited from the MASVS. I'm looking at the actual differences to create the json, xml, and csv formats. I'v already created a couple of scripts to produce a compact form with only the requirements for a given level.

**Comment by vanderaj** [comment]
I'll follow this up this week to help generate 4.0.2

**Comment by lfservin** [comment]
pdf and docx targets are done. next problem to tackle is the json and csv export. 

how were the excel sheets created in the past?

**Comment by lfservin** [comment]
export.py works for me, except for csv. 

Looking at the MASVS project, from which apparently this file +asvs.py come from, there have been a couple of changes in that md file format. They have created a Tag for each requirement, that is now also exported. They are also tracking what category flags (L1,L2,L3) each requirement belongs to. 

It seems like generate-json.py includes the contents of the asvs.py file in itself and generates json through a bit different process. exemplary json output:
```json
            {
              "Shortcode": "V14.5.4",
              "Ordinal": 4,
              "Description": "Verify that HTTP headers added by a trusted proxy or SSO devices, such as a bearer token, are authenticated by the application.",
              "L1": {
                "Required": false,
                "Requirement": ""
              },
              "L2": {
                "Required": true,
                "Requirement": ""
              },
              "L3": {
                "Required": true,
                "Requirement": ""
              },
              "CWE": [
                306
              ],
              "NIST": []
            } 
```
vs the output from export.py:
```json
{
    "id": "14.5.4", 
    "text": "Verify that HTTP headers added by a trusted proxy or SSO devices, such as a bearer token, are authenticated by the application.", 
    "file": "0x22-V14-Config.md"
}
```
I do prefer the output of generate-json.py. I believe that maybe making that one a bit more versatile can lead to having the same information in xml and csv. 

generate-csv.py is doing a very different process and is incredibly slow compared to the json one. once everything has been loaded in memory as json, it should be very easy to export both xml and csv. it would also make it easier to maintain. 

I'll include the generate scripts in the Makefile for making the deadline. the scripts do need some love to make them better.

**Comment by lfservin** [comment]
i think for this release the work is done. 
by calling make, all targets are created: pdf, docx, json, csv
there is an optional target: tex in case there is need for debugging the pdf being created

The existing scripts are used. export.py could be deleted to avoid confusion since its output is not as good at that from generate-json or generate-csv

i'll make a pull request to close this and also #777

Files are being output into the build directory. it is trivial to change where they should endup. is the root directory the best place for them?

**Comment by tghosth** [comment]
Hi @lfservin, thanks for your efforts with this. Sorry for the delay in response :(. I started looking through what had been done here and I had a few questions:
- Are you able to get the docx looking more like the [4.0 docx](https://github.com/OWASP/ASVS/raw/master/4.0/OWASP%20Application%20Security%20Verification%20Standard%204.0-en.docx) or is that a limitation of the original script?
- Regarding the PDF and the docx, like I said on Slack, "I think it is important that they are similar cosmetically and have the header/footers"
- Why are there 2 YAML files?
- Do you have a list of the dependencies to install to run the makefile

**Comment by lfservin** [comment]
I'll number the questions to be able to answer them better:
1. Docx - Pdf looking the same
  * It's not trivial. I am proposing two variants of the pdf document produced through pandoc and some latex magic. If not happy with the pdf, please mention what you'd like to change and I can work on it. I suppose the question here is what is the main document? The PDF or the word file? if the word file  then there is no real need to produce pdfs from markdown and "just" print to pdf in word.
2. Is it not the same as 1?
3. The yaml files are the headers. Since  I am proposing two different formats, we need two different headers. The headers allow to set the title, logo and some other details of the document. When and if a format is chosen, one of the header.yaml files disappear. These headers are necessary for pandoc
4. There is no need for the dependencies list, since all dependencies are in the docker build environment I committed in the latest pull request update. 

Hope this clears some questions.

**Comment by jmanico** [comment]
I do not, I am far away from the make file, but I suggest we just close this and have someone reopen if needed.

In fact, I'll do that right now, I think this is a legacy issue.

please re-open if I closed this in haste.

**Comment by jmanico** [comment]
Perfect
