### ISSUE TITLE
ASVS 4.0 - 1.14.2 Deploying binaries description

### ISSUE THREAD

**Issue by Bankde** [OWASP/ASVS#707]
The current description of ASVS 4.0 - 1.14.2 is
```
Verify that if deploying binaries to untrusted devices makes use of binary signatures, trusted connections, and verified endpoints.
```

However, the [CWE 494](https://cwe.mitre.org/data/definitions/494.html) description is
```
Download of Code Without Integrity Check
The product downloads source code or an executable from a remote location and executes the code without sufficiently verifying the origin and integrity of the code. 
```

I think it would be more accurate to replace "untrusted device" with "remote device" since CWE's description focuses on the owner's security of the device that runs the code. That does not really sound like "untrusted" component.

I propose the new description as follows:
```
Verify integrity of binaries when deploying to remote devices by using binary signatures, trusted connections, and verified endpoints.
```

What's your opinion on this?

**Comment by tghosth** [comment]
Is it possible that a different CWE is needed to fit the requirement or do you think that the requirement itself doesn't seem correct?

**Comment by Bankde** [comment]
I think this CWE is pretty well defined while the ASVS requirement is still confusing.

In my opinion, "untrusted device" usually means malicious device or device that we have no control over it.  Since it's untrusted, their owner could run any unverified binary on it anyway. I don't think untrusted device should be the main focus.

Using the word "untrusted device"  also scopes to very small domain - such as user devices. Using the word "remote device" will include any untrusted and trusted device (including the servers we own) on remote network. I think the latter is better.

It is important that I do not know the original intention of this requirement so I'm fine we wait for a confirmation from others.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tghosth** [comment]
Thanks @Bankde, what do you think about #747?

**Comment by Bankde** [comment]
Thank you @tghosth 
It looks a lot clearer to me.
