### ISSUE TITLE
Question regarding CWE Mapping for 13.2.4 

### ISSUE THREAD

**Issue by ramshazar** [OWASP/ASVS#709]
Hi,

for 13.2.4 "Verify that REST services have anti-automation controls to protect against excessive calls, especially if the API is unauthenticated." you chose to map this to "CWE-779: Logging of Excessive Data" instead of "CWE-770: Allocation of Resources Without Limits or Throttling".
Are there any specific reasons why CWE-779 is a better fit or is it just the "most commony used" as described in the "What's new in 4.0" section?

Kind regards,
Matthias

**Comment by tghosth** [comment]
I agree 779 sounds wrong. Are you sure that 770 is correct? 770 seems to be talking about system resources where as 13.2.4 is more about excessive use of a particular function.

**Comment by ramshazar** [comment]
Sorry for the delay. 
I am not sure that CWE-770 is correct or even the best choice.
I thought that 13.2.4 and CWE-770 are not too far away from each other. Additionally CWE-779 could easily be a typo of CWE-770.

**Comment by pikeje** [comment]
Throwing my hat in. CWE-770 feels like the correct weakness mapping over CWE-410 or CWE-779 as this relates to throttling/rate limiting.

**Comment by tghosth** [comment]
Ok, changed for now
