### ISSUE TITLE
Web service feedback

### ISSUE THREAD

**Issue by vanderaj** [OWASP/ASVS#71]
V18.5: This has been mentioned before in requirement v5.13. 
V18.6: I would put this as a requirement also for L1 

I can think of the following additional requirements:
-	Verify that the message payload is signed to ensure reliable transport between client and service. (L2+ and L3). For instance based on WS-Security.
-	Verify that alternative and less secure access paths do not exist (L2 and L3).

**Comment by danielcuthbert** [comment]
added/removed
