### ISSUE TITLE
Linking to sections of ASVS

### ISSUE THREAD

**Issue by rbsec** [OWASP/ASVS#713]
What is the best way to link to a specific section of the ASVS? I'm looking to reference parts of it from the Cheat Sheets project (in this case, section 6.0 related to cryptography).

Linking to a PDF or docx file isn't very friendly (and you can't link to specific sections that way. I can link to the [markdown page](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x14-V6-Cryptography.md), but because of the `4.0` in the path, as soon as a new version of ASVS is released the link will be broken.

Is there an authoritative hosted version I can link to that will remain consistent, or do you have any other recommendations about the best way to handle this?

Thanks

**Comment by tghosth** [comment]
Are you looking for a long term link that will stay valid and unchanged or are you looking or a link that will always be to the latest version of the standard?

**Comment by rbsec** [comment]
Hi @tghosth.

I'm pointing to section 6 (stored cryptography) - so assuming that the major section numbers aren't likely to change in future then a link to the latest version of that would be ideal. If that's not a safe assumption then a permanent link to that section would be better (although the current markdown page would work probably work for that).

Thanks

**Comment by tghosth** [comment]
So if you want a link to a static version that will never change, you can use the v4.0.1 tag:
https://github.com/OWASP/ASVS/blob/v4.0.1/4.0/en/0x14-V6-Cryptography.md#v6-stored-cryptography-verification-requirements

If you want the bleeding edge version then there is a risk that that will change at some point in the future but currently it is:
https://github.com/OWASP/ASVS/blob/master/4.0/en/0x14-V6-Cryptography.md#v6-stored-cryptography-verification-requirements.

Does that help you at all?

**Comment by rbsec** [comment]
Hi @tghosth,

My potential concern with the bleeding edge link (i.e, master branch) is that as soon as ASVS 4.1 is release that link will no longer be up to date (as the versions are in their own separate folders in the GitHub repo) - however it looks like that's probably the best option available for now.

It's not a project that's releasing new versions very often, so just updating the URL(s) when a new major version comes out shouldn't be a huge task.

Thanks

**Comment by tghosth** [comment]
I agree it is a little tricky but at the same time as you say since there are not very frequent versions it should not be a big task. Also, there are often significant changes between versions so a requirement might change a lot between versions.

**Comment by vanderaj** [comment]
Hi @rbsec - I will close this if we don't have a response by the time 4.0.2 comes around. Please let us know if this answers this issue for you?

**Comment by rbsec** [comment]
Yeah, I think this might as well be closed.

WSTG have implemented a "stable" branch which is the sort of thing I was looking for, but if there's nothing like that for ASVS that's fine:

https://owasp.org/www-project-web-security-testing-guide/stable/
