### ISSUE TITLE
Missing license impedes corporate support

### ISSUE THREAD

**Issue by thatsjet** [OWASP/ASVS#714]
I'm pushing my company (Nike) to officially sanction my ongoing contributions to ASVS but since there isn't an associate license published anywhere we can't get the request through legal. Is there any chance of us adopting a license for the ASVS? Perhaps Creative Commons v3.0 (which is what many of the other OWASP projects use)?

**Comment by stevespringett** [comment]
All OWASP project must have an open source license. Refer to the PDF and doc (usually towards the beginning) for the exact license that applies to a specific version of ASVS. Page7 of the ASVS v4.01 spec contains the license.

**Comment by thatsjet** [comment]
> All OWASP project must have an open source license. Refer to the PDF and doc...
Got it. However, as the "source" of the project is the github repo that is where the license is expected to be disclosed. Anyone have an objection to me opening a PR to update the Readme.md with explicit callout of the license?

**Comment by thatsjet** [comment]
RESOLVED PR #716
