### ISSUE TITLE
Formalize reference standard

### ISSUE THREAD

**Issue by kingthorin** [OWASP/ASVS#715]
As discussed on Slack, it would be wonderful if ASVS had a stated reference standard. I had asked:

> Is there a standard or preferred way of referencing ASVS controls? Ex: combination of ASVS release/milestone version and shortcode?

And subsequently suggested the example: `v4.0.1-1.1.3`
Which breaksdown as `v<version_number>-<requirement_number>`

@tghosth @vanderaj @jmanico @danielcuthbert if we can get some consensus on this I'd be glad to create a PR for the repo's README to document it.

Having this established will help other projects reference ASVS requirements.

<sub>Side note: Also from Slack, consistency in whether they are 'requirements' or 'controls' would also be something to keep in mind for the future 👍 </sub>

**Comment by tghosth** [comment]
> And subsequently suggested the example: `v4.0.1-1.1.3`
> Which breaksdown as `v<version_number>-<requirement_number>`

I like this

**Comment by kingthorin** [comment]
@vanderaj @jmanico @danielcuthbert any thoughts? Agreement? Disagreement?

**Comment by elarlang** [comment]
What is the use-case for this?

**Comment by kingthorin** [comment]
Cross referencing between ASVS and other tools/docs.

**Comment by kingthorin** [comment]
I could be done in such as way that using versioned references is encouraged but not technically required. Similar to: 
-https://owasp.org/www-project-web-security-testing-guide/#how-to-reference-wstg-scenarios
- https://github.com/OWASP/wstg/pull/472

**Comment by kingthorin** [comment]
It's been months, it'd be really nice to get some feedback on this and have it documented. So that people and other projects can move forward referencing ASVS in a formalized manner.

@vanderaj @jmanico @danielcuthbert any thoughts? Agreement? Disagreement?

**Comment by kingthorin** [comment]
Thanks @jmanico now that I have two of you in agreement I'll knock something together over the next few days. Note I "shouldn't" need a partial review, I just plan to document it as a "you should do this" paragraph or two, not to actually change the doc/headings (for now at least).

**Comment by vanderaj** [comment]
Hi @kingthorin. I'm still between jobs, so if you want me to help, or set something up with me (vanderaj@owasp.org) to discuss further, happy to do so. This would definitely be a 4.1 or later change, but I am in full support. We have had similar discussions in the OWASP Top 10 @sslhello @infosecdad @neilsmithline

**Comment by vanderaj** [comment]
See PR might be ready to go

**Comment by vanderaj** [comment]
For 4.0.2, I will be normalizing our usage of V, but 4.1 can go further if more changes are required.

**Comment by kingthorin** [comment]
To add this to the document do you want to PR against 4.0.2 or master?

Also are we in agreement that it should be inserted in `0x03-Using-ASVS.md` after "Applying ASVS in Practice"?
<sub>(Which makes me notice that you need to standardize headings either with or without Title Caps... topic for another ticket :wink:)</sub>

**Comment by tghosth** [comment]
There was some more discussion on this which will change things slightly but I will get on that in next week or so

**Comment by tghosth** [comment]
See https://github.com/OWASP/ASVS/issues/812#issuecomment-657759067

**Comment by tghosth** [comment]
Hi @kingthorin, what did you mean [here](https://github.com/OWASP/ASVS/pull/820#pullrequestreview-447569902) by integrating into the doc?

Also, are you opening a PR on the www repo?

**Comment by kingthorin** [comment]
The reference standard should appear within the ASVS doc's content as well. For example:

> Also are we in agreement that it should be inserted in `0x03-Using-ASVS.md` after "Applying ASVS in Practice"?

**Comment by tghosth** [comment]
The merge is done so you can do the PR :) Thanks!

**Comment by kingthorin** [comment]
Third time, two questions:

> To add this to the document do you want to PR against 4.0.2 or master?
> Also are we in agreement that it should be inserted in 0x03-Using-ASVS.md after "Applying ASVS in Practice"?

**Comment by tghosth** [comment]
Sorry, I silently dealt with both those questions [here](https://github.com/OWASP/ASVS/pull/820) and [here](https://github.com/OWASP/ASVS/pull/827) :) Correct?

I think all that is left is the PR in www

**Comment by kingthorin** [comment]
No problem, I was expecting to have to tackle it that's why I was after answers. No problem. Thanks!

I'll proceed with the www part 😀

**Comment by kingthorin** [comment]
www PR opened: https://github.com/OWASP/www-project-application-security-verification-standard/pull/4
