### ISSUE TITLE
Some naming corrections

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#720]
## 1 header: Origin

> V13.2.3 Verify that RESTful web services that utilize cookies are protected from Cross-Site Request Forgery via the use of at least one or more of the following: triple or double submit cookie pattern (see [references](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet)), CSRF nonces, or ORIGIN request header checks.

`ORIGIN` request header > `Origin` request header

## 2 Content-Type: application/json

> V13.2.5 Verify that REST services explicitly check the incoming Content-Type to be the expected one, such as application/xml or application/JSON.

`application/JSON` > `application/json`

## 3 Content-Type

> V14.4.1 Verify that every HTTP response contains a content type header specifying a safe character set (e.g., UTF-8, ISO 8859-1).

Correct header name is `Content-Type`

## 4 header vs policy

> V14.4.5 Verify that HTTP Strict Transport Security headers are included on all responses and for all subdomains, such as Strict-Transport-Security: max-age=15724800; includeSubdomains.

- "HTTP Strict Transport Security" is policy
- "Strict-Transport-Security" is header

> "... HTTP Strict Transport Security headers ..."

- It's not correct policy name and not correct header name. I think we should choose one correct.
- Additionally, header vs headers

As other requirements in this subcategory are using header names, it makes sense to use also header name. Personally I actually like when we should use policy name first, because correct header name is used later. Then we may need to look to other requirements also.

**Comment by tghosth** [comment]
Can you go through the rest of the requirements to look for fixes like this and open a PR please. Thanks :)

**Comment by elarlang** [comment]
Just in case also as comment, I made PR.
