### ISSUE TITLE
V14.4.7 (50.2.5) - X-Frame-Options is obsolete + sites vs resources + discussion

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#722]
edit: 
* proposal for v4.0.3 2020-02-23 is in: https://github.com/OWASP/ASVS/issues/722#issuecomment-590039185
* proposal for v5.0 2023-12-13 is in: https://github.com/OWASP/ASVS/issues/722#issuecomment-1853461657

> V14.4.7 Verify that a suitable X-Frame-Options or Content-Security-Policy: frame-ancestors header is in use for sites where content should not be embedded in a third-party site.

## X-Frame-Options
As `X-Frame-Options` is obsolete (or will be?), we should use only `Content-Security-Policy: frame-ancestors`.

- CSP2 <https://www.w3.org/TR/CSP2/#frame-ancestors-and-frame-options>
- CSP3 <https://www.w3.org/TR/CSP3/#frame-ancestors-and-frame-options>

caniuse.com:
- <https://caniuse.com/#search=ancestors>
- <https://caniuse.com/#search=x-frame-options>

## "is in use for sites"
Classical problem - if for one resource there is need to be embedded by 3rd party, then entire site is allowed to be embedded by 3rd party. Embedding by 3rd party should be allowed only for those resources when it's needed, not for entire site. (As I'm not that good with english, I need help here with proper wording)

## Discussion: V14.4.3 vs/and V14.4.7
Discussion (for ASVS v4.1): Which raises another question - should we have 2 separate requirement to use `Content-Security-Policy` (V14.4.3) or we should merge them?

Separate:
- positive: it's good to have separate requirement for "mitigate XSS impact" and "avoid 3rd party embedding"
- negative: V14.4.3 already covers V14.4.7 with "suitable Content-Security-Policy"

**Comment by jmanico** [comment]
I suggest both, x-frame-options works well and it’s a single easy to use header. No need to drop x-frame yet; lots of folks still do not use CSP.

--
Jim Manico
@Manicode

**Comment by elarlang** [comment]
`X-Frame-Options` as only header is no-go in my opinion. The only argument why to use it all, is some old browser which does not support `Content-Security-Policy` `frame-ancestors` (but how old it must be already!?)

<https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options>

> allow-from uri (obsolete)
> This is an obsolete directive that no longer works in modern browsers. Don't use it.

Let's take situation - you have a list of partners for whom you allow to embed content from your site. With `X-Frame-Options` you can not do it (as `allow-from` directive is obsolete even more than `X-Frame-Options` itself. With `Content-Security-Policy` you can build nice whitelist using correctly protocols and paths.

And...
> lots of folks still do not use CSP

should we say Windows XP is still ok, beause a lot of PC's are using it? :) No! It's time to move on.

**Comment by jmanico** [comment]
I still disagree, strongly, and let me explain why with more data.

If you want to stop framing then x-frame-options deny or sameorigin are just fine. We can add that point as a clarification.

X-frame-options deny and sameorigin are supported in more browsers than frame-ancestors by a wide margin. Also, philosophically I prefer dedicated headers vs the mess that is CSP. 

So again I’ll politely keep asserting to keep x-frame-options around for one more ASVS version. If you want clarification that allow-from is poorly supported I’m ok with that. But let’s also be clear that CSP frame ancestors is not supported on browsers like ie11 and others and ie11 still matters in the enterprise.

https://caniuse.com/#search=Frame-ancestors

Compare that to how well x-frame-options deny and sameorigin support are supported. It’s every browser tracked by caniuse.

https://caniuse.com/#search=X-frame-options

I hope this explains why we are keeping x-frame-options. If you want to help wordsmith this to address the lack of x-frame-options allow-from and CSP browser limitations that would help a lot.

--
Jim Manico
@Manicode

**Comment by elarlang** [comment]
Got your point, IE11 is party-stopper here. So, I agree we can not drop `X-Frame-Options`, yet.

At the same time I think we can not ignore the fact, `X-Frame-Options` will be obsoleted and we should not direct people to use it as only defense method. So, I still standing with my opinion: `X-Frame-Options` **as only header** is no-go in my opinion.

> I still disagree, strongly, and let me explain why with more data.

Not clear for me, was strong disagree for "drop X-Frame-Options" or "do not use X-Frame-Options as only header".

# Conclusion so far

- Too early to drop `X-Frame-Options`
- In practice, both headers are required at the moment but web is moving towards `Content-Security-Policy: frame-ancestors`
- V14.4.3 and V14.4.7 merge is not the topic till X-Frame-Options exist in requirement
- Embedding must be disabled for every (at least HTML content) response by default, including error messages, because other ways it opens some (CSP) bypassing vectors (like: HTML injection > open iframe to error message page > write dynamic script tag or content there > CSP restrictions for whitelisted script src bypassed).

## Proposal
To address described issues, my proposal is something like that (**it requires "translation" to correct English**):

V14.4.7 Verify that content of the entire site is not allowed to be embedded by third-party by default and that embedding of the exact resources is allowed only where needed (with whitelisting 3rd party when possible) by using suitable `Content-Security-Policy: frame-ancestors` **and** `X-Frame-Options` (for older browsers) headers.

It contains 3 separate requirements:
- disable embedding by default the entire site, even for error pages (like 400, 403, 404, 500, ...)
- allow only for special resources
- use both headers (`Content-Security-Policy: frame-ancestors` and `X-Frame-Options`)

**Comment by jmanico** [comment]
I like this direction.  CSP is the future and I do support this compromise of ideas.

Elar, well done. Please CC me @jmanico into any other major change you want to make. I want to get into more of these debates with you.

--
Jim Manico
@Manicode

**Comment by devd** [comment]
Hi! Also consider that x-frame-options doesn't work if you iframe any untrusted content in your origin. see https://bugzilla.mozilla.org/show_bug.cgi?id=725490

My worry with X-F-O is that I have repeatedly seen it give a false sense of security. For example, the proposal above doesn't make it clear that the X-F-O sameorigin will not be secure if you iframe any untrusted content.

**Comment by elarlang** [comment]
> Hi! Also consider that x-frame-options doesn't work if you iframe any untrusted content in your origin. see https://bugzilla.mozilla.org/show_bug.cgi?id=725490
> 
> My worry with X-F-O is that I have repeatedly seen it give a false sense of security. For example, the proposal above doesn't make it clear that the X-F-O sameorigin will not be secure if you iframe any untrusted content.

This is completely different problem. "To be shown by untrusted source" vs "To show untrusted source".

**Comment by devd** [comment]
not sure I understand. The point is that if you use x-frame-options same-origin and iframe even one untrusted source, you cannot prevent yourself from being shown by untrusted source. I.e., imagine you have set x-frame-options sameorigin on all your pages. If you iframed attacker.com even once, the x-frame-options sameorigin can be bypassed. Attacker.com can iframe any page and x-frame-options only checks the top most frame. CSP Frame-ancestors checks the whole tree; x-frame-options only checks window.top.

**Comment by elarlang** [comment]
> For example, the proposal above doesn't make it clear that the X-F-O sameorigin will not be secure if you iframe any untrusted content.

1) Your site or visitors are not secure anyway, if you include untrusted content in iframe - this is the problem what you need to address in your example. As a site owner, you can choose, what content and from where you going to include in iframe.
2) If your example is fixed by `Content-Security-Policy: frame-ancestors`, then my proposal already contains "the fix" for this. `X-Frame-Options` should stay only because of IE and only additionally to `Content-Security-Policy`. I don't think this requirement need to contain "do not include any untrusted content in your site".

**Comment by tghosth** [comment]
Is there any consensus on a change to the requirement. Please remember requirements should be relatively short.

**Comment by elarlang** [comment]
From last proposal:
> V14.4.7 Verify that content of the entire site is not allowed to be embedded by third-party by default and that embedding of the exact resources is allowed only where needed (with whitelisting 3rd party when possible) by using suitable Content-Security-Policy: frame-ancestors and X-Frame-Options (for older browsers) header

we can remove brackets:
> V14.4.7 Verify that content of the entire site is not allowed to be embedded by third-party by default and that embedding of the exact resources is allowed only where needed by using suitable Content-Security-Policy: frame-ancestors and X-Frame-Options header

(it requires language check)

**Comment by tghosth** [comment]
Ok, open a PR please.

**Comment by tghosth** [comment]
Merged

**Comment by elarlang** [comment]
Current requirement 14.4.7

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **14.4.7** | Verify that the content of a web application cannot be embedded in a third-party site by default and that embedding of the exact resources is only allowed where necessary by using suitable Content-Security-Policy: frame-ancestors and X-Frame-Options response headers. | ✓ | ✓ | ✓ | 1021 |



https://github.com/OWASP/ASVS/issues/722#issuecomment-590039185

Close to 4 years later, is it now time to remove X-Frame-Options as required response header?

Proposal direction (recommendations to improve it are welcome)

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **14.4.7** | Verify that the content of a web application cannot be embedded in a third-party site by default and that embedding of the exact resources is only allowed where necessary by using suitable Content-Security-Policy: frame-ancestors. **Note that the X-Frame-Options solution is obsoleted.** | ✓ | ✓ | ✓ | 1021 |

**Comment by elarlang** [comment]
ping @jmanico - have your views on the topic changed from 2020 (https://github.com/OWASP/ASVS/issues/722#issuecomment-590006824)?

**Comment by jmanico** [comment]
I support removing x-frame-options from this requirement

**Comment by elarlang** [comment]
@jmanico - are you happy with the proposed wording change or do you have some recommendations?

**Comment by jmanico** [comment]
I'm OK with a suggested text. Thank you for seeing this one to completion Elar.

**Comment by elarlang** [comment]
The requirement is moved to web front end category, 50.2.5.

PR for update #1816
