### ISSUE TITLE
V3.3.4 - if session is taken over, it gives attacker a tool to keep victim away from using account

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#723]
At the moment, requirement V3.3.4 gives attacker potential tool to keep victim away from his/her account.

> V3.3.4 Verify that users are able to view and log out of any or all currently active sessions and devices.

Situation:
- victim's session is taken over (whatever is the reason - fixation, hijacking, not locked computer, ...).
- application provides functionality to get overview of active sessions and to terminate them
- note 1: attacker does not know credentials, otherwise he/she could take over account anyway
- note 2: session maximum lifetime is really long or not set at all (and not "inactivity time", this one is easy to bypass with just making periodically some HTTP requests to keep the session alive)

Attacker can monitor and automatically kill any new active session - how victim can get back to own account?

## Password recovery

Successful password recovery should terminate all other active sessions.
- new requirement to "V2.5 Credential Recovery Requirements" subcategory
- OR add phrase "including password recovery" to V3.3.3, for example:

> V3.3.3 Verify that the application terminates all other active sessions after a successful password change **(including change via password recovery)**, and that this is effective across the application, federated login (if present), and any relying parties.

## Re-Authentication on session termination

Terminating session should by done with re-authentication. Some addons to requirement V3.3.4 (I don't know how to write it in correct English :))

> V3.3.4 Verify that users are able to view and log out of any or all currently active sessions and devices. 

Alternative is to cover it in V3.7.1 (again, need help with wording):
>  V3.7.1 Verify the application ensures a valid login session or requires re-authentication or secondary verification before allowing any sensitive transactions or account modifications.

**Comment by tghosth** [comment]
Please open a separate issue for V3.3.3.

PLease review my change in #733

**Comment by elarlang** [comment]
> Please open a separate issue for V3.3.3.
> 
> PLease review my change in #733

#734

**Comment by tghosth** [comment]
I have made this update in #734
I will merge in a few weeks if no one objects
