### ISSUE TITLE
Link to Threat Modelling Cheat sheet is broken on 0x10-V1-Architecture.md (v4)

### ISSUE THREAD

**Issue by JoelClemence** [OWASP/ASVS#724]
On: https://github.com/OWASP/ASVS/blob/master/4.0/en/0x10-V1-Architecture.md the link to the Threat Modelling Cheat sheet is broken, having gone to the link fo 'OWASP Secure SDLC Cheat Sheet' there is a cheat sheet available: https://cheatsheetseries.owasp.org/cheatsheets/Threat_Modeling_Cheat_Sheet.html. Should this be corrected?

**Comment by benbhall** [comment]
Looks like the 'Attack Surface Analysis Cheat Sheet' link is broken too, which I presume should be https://cheatsheetseries.owasp.org/cheatsheets/Attack_Surface_Analysis_Cheat_Sheet.html if you're doing a PR @JoelClemence :)

**Comment by tghosth** [comment]
Thanks @benbhall @JoelClemence @rewtd , I merged #729 and swapped the defunct SDLC cheatsheet for a link to OWASP SAMM.
