### ISSUE TITLE
V2.9 Password Strength Indicator

### ISSUE THREAD

**Issue by weasel0x00** [OWASP/ASVS#73]
V2.9 specifies that the change password functionality should include a "Strength Indicator." I Don't think this is necessary, and in fact can lead to a false sense of Security.  Most Strength Indicators are simply based off length and the character set used in the password, Because of this "Password123456!" is often seen as a "strong" password, when it really isn't.  I would recommend simply removing the language that is recommending password strength indicators.

**Comment by danielcuthbert** [comment]
Agreed. this paragraph has been removed.
