### ISSUE TITLE
Minimum Password Length

### ISSUE THREAD

**Issue by whitehacklabs** [OWASP/ASVS#730]
Why ASVS V4 requires 12 character password length while NIST SP800-63b requires 8
![image](https://user-images.githubusercontent.com/44908209/78893475-684fb480-7a39-11ea-98c5-892c159715f3.png)

**Comment by jmanico** [comment]
We are going with other industry guidance. This is the one area we deviated SP800-63b on purpose.

If this harms your efforts we advise forking the standard. Frankly ASVS is more of a framework than a standard and we encourage forking for individual needs!

--
Jim Manico
@Manicode

**Comment by whitehacklabs** [comment]
Thanks
