### ISSUE TITLE
Discussion: ASVS development process

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#732]
As ASVS v4.1 peak-development time is knocking on door I would like to have small change in ASVS development process.

Current README contains:

> Please log issues (or even better, open a pull request) if you find anything. We are actively looking for translations of the 4.n branch.

The reason to rise this topic: https://github.com/OWASP/ASVS/pull/731 (to be clear - direct pull request is not he's mistake, he was following instructions)

The problem so far for me is - if there is some requirement, it's not possible to detect the reason why this requirement exists, or requirement related discussions etc.

"Discussion" over pull-requests is just a mess.

Yes, it puts more load for maintainers, but I think it's not possible to maintain entire ASVS anyway, if everyone put their requirements to this document on their own way, using own style etc.

Maybe pull-requests for non-maintainers could be only for fixing typos, language corrections etc. If someone (non-maintainer) want to change the meaning for some requirement, it requires discussion.

Maintainer anyway need to decide later, is the change worth to make new release or not. (If #666 takes place finally).

**Comment by tghosth** [comment]
Would a quick fix be to request always opening an issue first and then after discussion, opening a PR?

**Comment by elarlang** [comment]
That way we have some history and reasons why some change was made. But I don't know what kind of extra issues/problems/load it may make for maintainers.

**Comment by tghosth** [comment]
As well as https://github.com/OWASP/ASVS/commit/2124ad297e7063d9a1bbe03905778f8b439c66d5 I also committed https://github.com/OWASP/ASVS/commit/f53bf7a857cbee5911d585fbeedcd4edc68b1a91 based on this.
