### ISSUE TITLE
V3.3.3 - application should terminate all active sessions on successful password change also via password recovery/reset

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#734]
"Spin-off" from #723 

Current requirement (v4.0.1, 2020-04-12):
> V3.3.3 Verify that the application terminates all other active sessions after a successful password change, and that this is effective across the application, federated login (if present), and any relying parties.

Proposal:
V3.3.3 Verify that the application terminates all other active sessions after a successful password change (including change via password recovery), and that this is effective across the application, federated login (if present), and any relying parties.

**Comment by tghosth** [comment]
Please review #735 and make the issue title a little more specific

**Comment by jmanico** [comment]
Rather than “does” I suggest “gives the user the option to”. Please don’t make me log into my iPhone again with a big password just because I changed it and know it was me!

--
Jim Manico
@Manicode

**Comment by tghosth** [comment]
Hi @jmanico, the current text is:

> V3.3.3 Verify that the application terminates all other active sessions after a successful password change, and that this is effective across the application, federated login (if present), and any relying parties.

Are we saying this requirement should be changed to give the user the option rather than forcing it?

**Comment by tghosth** [comment]
I have made this update in #735 
I will merge in a few weeks if no one objects
