### ISSUE TITLE
1.4.2 - [Clarification/For Discussion] for "flexible" access control solution

### ISSUE THREAD

**Issue by csfreak92** [OWASP/ASVS#736]
ASVS 4.0 - 1.4.2 verification requirement is: 

`Verify that the chosen access control solution is flexible enough to meet the application's needs.`

This control is too vague, what does it mean by having a flexible access control solution? Maybe this be expanded to explain to developers and tester what this requirement really means?

**Comment by jmanico** [comment]
I’d just drop this one. It‘s not helpful.

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by csfreak92** [comment]
Hi @jmanico, do you mean you would drop this 1.4.2 verification requirement for the next ASVS iteration? Or was my open issue not helping as well?

**Comment by jmanico** [comment]
I think you’re exactly right. This requirement is too vague. I suggest we drop this requirement as you suggested in the next ASVS version.

--
Jim Manico
@Manicode

**Comment by elarlang** [comment]
One thing less to report :)

@jmanico Peale set milestone 4.1 to the issue, then it's clear and easy to follow.

**Comment by jmanico** [comment]
How do you do that? My github skills are

1) answer email with my snark
2) commit to master oh yea

Something tells me there are more mature ways to github?

--
Jim Manico
@Manicode

**Comment by tghosth** [comment]
Done, leaving this for when we prepare 4.1

**Comment by csfreak92** [comment]
@tghosth, shall I create a pull request ready to remove this control?

**Comment by tghosth** [comment]
let's leave this open for now. I am not sure if we want a PR at this point for something relatively basic. We currently have a discussion about releasing a 4.0.2 (#750) so I am not running to change requirements at this point.

**Comment by jmanico** [comment]
Hey @csfreak92 we'll take that PR now please!

**Comment by jmanico** [comment]
Completed here 480bb9d and closing this out
