### ISSUE TITLE
V2.5.7 - should be applied to L1

### ISSUE THREAD

**Issue by fujiokayu** [OWASP/ASVS#739]
>V2.5.7 - Verify that if OTP or multi-factor authentication factors are lost, that evidence of identity proofing is performed at the same level as during enrollment.

If the application implements OTP or multi-factor authentication, the requirements of V2.5.7 is really important.
And V2.5.7 can be verified with DAST.

I think this item should be verified in L1.

**Comment by bedirhan** [comment]
Same with 3.3.3

**Comment by tghosth** [comment]
For reference, 3.3.3 is:

> Verify that the application terminates all other active sessions after a successful password change, and that this is effective across the application, federated login (if present), and any relying parties.

**Comment by tghosth** [comment]
@jmanico what do you think about the claim that these should be L1 controls?

**Comment by vanderaj** [comment]
This would represent a new requirement level change, and thus is a breaking change. 4.1

**Comment by jmanico** [comment]
I think moving this to L1 is fundamental. I agree. Can we see PR's on this please? cc @fujiokayu  and @bedirhan  ?

**Comment by fujiokayu** [comment]
@jmanico 
Thank you for checking this issue. I will send PR later.

**Comment by fujiokayu** [comment]
Now that my PR has been merged, close this issue.
Thanks @jmanico , @bedirhan
