### ISSUE TITLE
General suggestion - use case for non-functional requirements in outsourced development

### ISSUE THREAD

**Issue by raoul361** [OWASP/ASVS#74]
Hi, great work; have a suggestion that would have come in very handy at my previous employer, which is to have a set of non-functional requirements that can be used as part of an RFP or even contractual schedule to ascertain/specify the level of rigor provided by a third party development shop. Many organisations do not have internal skills to assess software vendors, this could be a useful benchmarking tool.

Suggest identifying a case study or providing guidance to this effect.

**Comment by vanderaj** [comment]
That's a good idea. We'll incorporate it into the front bits.
