### ISSUE TITLE
ASVS 7.4.3 - CWE 460 

### ISSUE THREAD

**Issue by bedirhan** [OWASP/ASVS#740]
I couldn't map ASVS 7.4.3 to CWE-460. I'm not sure if CWE has one for it. Maaaybe CWE-756...

**Comment by tghosth** [comment]
I agree 460 isn't right although I can see how that got in there :)

I don't think 756 is right.

What do you think about one of the following:
https://cwe.mitre.org/data/definitions/431.html
https://cwe.mitre.org/data/definitions/544.html
https://cwe.mitre.org/data/definitions/755.html

**Comment by bedirhan** [comment]
IMHO, CWE-431 is cool. CWE title is misleading that's why I missed that too I guess.
