### ISSUE TITLE
14.5.3: Clarify not using rules matching URL prefixes or suffixes

### ISSUE THREAD

**Issue by hazanasec** [OWASP/ASVS#741]
I have seen time and time again mistakes implementing CORS origin whitelists around allowing access from subdomains. The current `14.5.3` states `uses a strict white-list of trusted domains` - I think this may cause confusion of organisations allowing access for all the subdomains of _trusted_ domains (including future subdomains), and even from other organisations subdomains. When implementing, they will use rules matching URL prefixes & suffixes, however often mistakes lead to access of malicious external domains. 

For example, an implementation allowing access to all domains ending in:

`this-site.com`

An attacker could register the domain for access:

`evilthis-site.com`

Or, an implementation granting access to all domains beginning with

`this-site.com`

An attacker could register:

`this-site.com.evil.com`

It's worth mentioning `uses a strict white-list of trusted domains, avoiding rules including prefixes or suffixes of trusted domains or subdomains`

i.e. `Verify that the cross-domain resource sharing (CORS) Access-Control-Allow Origin header uses a strict white-list of trusted domains, avoiding rules including prefixes or suffixes of trusted domains or subdomains and does not support the "null" origin.`

**Comment by elarlang** [comment]
Current full requirement is (to make it easy to follow in future):
>  V14.5.3 Verify that the Cross-Origin Resource Sharing (CORS) Access-Control-Allow-Origin header uses a strict white-list of trusted domains to match against and does not support the "null" origin.

**Comment by tghosth** [comment]
He @hazanasec,

How about:

`V14.5.3 Verify that the Cross-Origin Resource Sharing (CORS) Access-Control-Allow-Origin header uses a strict white-list of trusted domains and sub-domains to match against and does not support the "null" origin.`

I don't really want to make the requirement too long.

**Comment by hazanasec** [comment]
Hi @tghosth,

I think that removes some confusion whilst keeping short 👍

**Comment by tghosth** [comment]
Ok thanks @hazanasec, opened PR #745. What do you think?
