### ISSUE TITLE
2.8.3: Clarify that the requirement applies to OTPs

### ISSUE THREAD

**Issue by LarsH** [OWASP/ASVS#744]
The current formulation of 2.8.3 is

> Verify that approved cryptographic algorithms are used in the generation, seeding, and verification.

and without the context of section 2.8 (Single or Multi Factor One Time Verifier Requirements) it is not obvious what the requirement applies to. This happens when working with the extracted requirements in CSV/Excel-format.

All other requirements of section 2.8 specify that requirements apply to OTPs. I suggest that this is added to the formulation of 2.8.3 as well:

> Verify that approved cryptographic algorithms are used in the generation, seeding, and verification of OTPs.

**Comment by tghosth** [comment]
Good point, please open a PR.
