### ISSUE TITLE
Clarification relating to penetration testing

### ISSUE THREAD

**Issue by dmeans82** [OWASP/ASVS#748]
The language and directives around penetration testing is confusing, or at least inconsistent.
First, penetration testing is always performed by humans.  This sentence should be re-worded: 

> Level 1 is the only level that is completely penetration testable using humans.  

First, humans make use of penetration testing, rather than penetration making use of ("using") humans.  Secondly, the assumption of human interaction during penetration testing is well-known and does not need to be expressed.

In the next sentence, place the emphasis upon best practice rather than dictating terms of 'must stop':

> However, even if L1 allows "black box" (no documentation and no source) testing to occur, it is not effective assurance and must stop.

First, the phrase "even if L1 allows..." draws attention towards an implied, non-permissive behavior of the verification standard which is not elsewhere concretely expressed, rather the contrary is expressed in "The Role of Penetration Testing".  As such, it distracts the reader in several ways: first the reader is lead to ask why must black box penetration testing stop, what's wrong with it, and why does it never provide value?  Lastly, penetration testing should not be conflated with automated, dynamic testing - whether that testing be performed in situ (unit/security tests), or externally (e.g., probing APIs with vulnerability detection tools).

A better wording of this text may be:

> Black-box penetration testing, while potentially effective in limited use cases, should not be considered to be a singular best practice, but should be performed as a component within a comprehensive Security Architecture program.

Overall, a much better solution may be to provide a section discussing penetration testing and the role it plays within a Security Architecture program.

**Comment by tghosth** [comment]
Please review the latest version of this file and let us know what you think:
https://github.com/OWASP/ASVS/blob/master/4.0/en/0x03-Using-ASVS.md

**Comment by dmeans82** [comment]
Josh -

The last version I see, when clicking the link, is from 2019.  I must be doing something wrong; can you help me here?

Thaks,

**Comment by tghosth** [comment]
Last version was from late December 2019 and I am pretty sure the "must stop" wording is gone hence asking you to take another look :)

**Comment by dmeans82** [comment]
Understood.  

Thanks,

**Comment by tghosth** [comment]
Did you have any other comments on the wording apart from that?

**Comment by dmeans82** [comment]
From that perspective, not at the moment.  I have some ideas about how the std. could communicate some ideas.  I'll put that together and submit for review... assuming I can figure out that process :-)

Thank you.
