### ISSUE TITLE
Certificate pining, V10.10 - level 2

### ISSUE THREAD

**Issue by raoul361** [OWASP/ASVS#75]
Suggest that certificate pining need not be all encompassing, but can gradually scaled up, from validating the cert matches domain, validating expiry dates, etc.. through to certificate hash/fingerprint verification. The last step can be extremely onerous, when considering the need for certificate reissue (requiring new app version).

Maybe a level 2 requirement on the cert=domain and cert < expiry date checks?

**Comment by vanderaj** [comment]
Fixed.
