### ISSUE TITLE
[Clarification/For Discussion] Simplifying language for 3.5.1

### ISSUE THREAD

**Issue by csfreak92** [OWASP/ASVS#758]
ASVS 4.0 - 3.5.1 verification requirement is:

`Verify the application does not treat OAuth and refresh tokens - on their own - as the presence of the subscriber and allows users to terminate trust relationships with linked applications.`

I suggest we could simplify the language for this verification requirement. The wording is a bit  confusing sometimes how it was presented. Basically, to simplify it would be `a user should be able to kill the token and its trust relationship with the linked service/applications. `

This is related to Pull Request #755.

**Comment by tghosth** [comment]
@jmanico what do you think about this?

**Comment by jmanico** [comment]
Fix https://github.com/OWASP/ASVS/commit/4c3437eaa4434765839d7c020e1e7fcaae1c58a2
