### ISSUE TITLE
Requirement: Verifying secrets aren't being commited

### ISSUE THREAD

**Issue by hazanasec** [OWASP/ASVS#759]
`V6.4 Secret Management` concentrates on how an application should use secrets, all important requirements, but what about inadvertently committing secrets, either as hard-coded or in a file/directory that shouldn't have been committed, e.g. pushing AWS keys in terraform or API tokens in `.bash_profile` to GitHub. There should be a requirement to verify secrets aren't ever being committed as it's very low effort but easily a huge win, i.e. pre-commit hooks with any of the number of excellent secret detecting SAST tools freely available.

**Comment by elarlang** [comment]
Isn't it addressed by V2.10.4?
> V2.10.4 Verify passwords, integrations with databases and third-party systems, seeds and internal secrets, and API keys are managed securely and not included in the source code or stored within source code repositories. Such storage SHOULD resist offline attacks. The use of a secure software key store (L1), hardware trusted platform module (TPM), or a hardware security module (L3) is recommended for password storage.
