### ISSUE TITLE
V19.8 - external components - hosting?

### ISSUE THREAD

**Issue by raoul361** [OWASP/ASVS#76]
Controversial! 

Suggest requirement for Level 3 to have any external library hosted locally to prevent any hijacking through third party server compromise?

E.g. calling javascript libraries such as jquery (probably bad example, but lesser known/supported ones certainly) should be hosted locally to avoid their compromise affecting your apps.

**Comment by vanderaj** [comment]
Hmm.  I think the problem is more about trustiness of the library than where it comes. This would impact CDN delivery of large scale web apps, and I don't think that is okay.

**Comment by vanderaj** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/5029993/16450605/36cb3e28-3dfe-11e6-9460-e0c186396481.png)
