### ISSUE TITLE
[Clarification/For Discussion] Unclear wording for 2.10.1

### ISSUE THREAD

**Issue by csfreak92** [OWASP/ASVS#763]
ASVS 4.0 - 2.10.1 verification requirement is:

`Verify that integration secrets do not rely on unchanging passwords, such as API keys or shared privileged accounts.`

The wording for this control is a unclear somehow. Don't integration secrets rely on unchanging passwords (API keys)? What is the rationale of this control? Maybe somebody could help me understand it more. Let's discuss about it. Thanks!

**Comment by tghosth** [comment]
@vanderaj see also this requirement. Similar questions to my questions on issue #764

**Comment by jmanico** [comment]
Attempt to fix this https://github.com/OWASP/ASVS/commit/9528e92b5e2f7d29d4d915b8d813c14711d446e0 please reopen if not satisfied
