### ISSUE TITLE
[Clarification/For Discussion] Default credentials mean in 2.10.2

### ISSUE THREAD

**Issue by csfreak92** [OWASP/ASVS#764]
ASVS 4.0 - 2.10.2 verification requirement is:

`Verify that if passwords are required, the credentials are not a default account.`

I would like to clarify from the community/maintainers of this project regarding the term `default credentials` mean on this control? Does `default credentials` stand for some applications that have default credentials after installation? The way I interpreted this is if an application is deployed/installed and there are default credentials it fails this verification requirement (e.g. phpmyadmin application has "root", "admin" or something similar default credentials that comes with the installation of the application).

If my assumption and thinking is correct, I'll create a Pull Request to link this issue, else please help me understand this control better. This confuses our team a lot of times.

**Comment by tghosth** [comment]
![](https://media.giphy.com/media/UVdiMrmmwTWDcN2dZ5/giphy.gif)

So I am not sure what this means and I am also struggling to trace it back to the relevant NIST requirement. 

@vanderaj it looks like requirement [2.10.2](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#v210-service-authentication-requirements) started life as part of 2.21 added in this commit: https://github.com/OWASP/ASVS/commit/e0aa0e60ee1a0a80fc762e1e5b377d6c6244489d

Any idea if that NIST link to 5.1.1.1 is accurate?

**Comment by csfreak92** [comment]
Hi @vanderaj, @tghosth, any updates on this issue? Is there anything needed from my end?

**Comment by danielcuthbert** [comment]
My bad, this was assigned to me and I've stalled. Originally it was just as you said, for example, admin/admin123, and in hindsight, I can now see how this is actually not helpful in the way it was written. I'd really like to see how you'd make it better, so yeah please submit a PR

**Comment by csfreak92** [comment]
If there are no more ideas, then alright will submit a PR later today. I think there's a way we could make this better.

**Comment by csfreak92** [comment]
@danielcuthbert, I analyzed it more about this requirement. It looks like this is about service authentication, though this ASVS requirement is still vague so I created a PR to make it better. Let me know your thoughts on it.

**Comment by danielcuthbert** [comment]
thank you @csfreak92 ill check it this weekend!

**Comment by tghosth** [comment]
Resolved by #848 and #859
