### ISSUE TITLE
[Clarification/For Discussion] Removing cookies for whitelisting in 5.1.3

### ISSUE THREAD

**Issue by csfreak92** [OWASP/ASVS#765]
ASVS 4.0 - 5.1.3 verification requirement is:

`Verify that all input (HTML form fields, REST requests, URL parameters, HTTP headers, cookies, batch files, RSS feeds, etc) is validated using positive validation (whitelisting).`

I propose removing "cookies" in this requirement because it does not make sense whitelisting cookies as they will always change in value every authenticated session. How to whitelist cookies for that case?

**Comment by elarlang** [comment]
I interpret that "cookies" exists in this requirement as one example of source of user input. For me it's ok that way.

> I propose removing "cookies" in this requirement because it does not make sense whitelisting cookies as they will always change in value every authenticated session

With this sentence - maybe you take one situation and watch it too general. I'm not agree with phrase "they will always change in value every authenticated session" for ALL cookies. It's really limited to session cookie.

**Comment by tghosth** [comment]
I agree that cookies may be a vector for malicious input and that not all cookies are session cookies. I also agree whitelisting may be a valid pattern and not just a valid value.

**Comment by csfreak92** [comment]
I do agree that cookies could be used as a vector for malicious input as well. If the control is talking about whitelisting of cookies through patterns and length, then this is our team's mistake for misunderstanding this control and `cookies` should still be there and leave this control as is. We can close this issue if that is the case then. Thank you for your
