### ISSUE TITLE
[Proposal/For Discussion] add link check GitHub workflow

### ISSUE THREAD

**Issue by efx** [OWASP/ASVS#767]
Hi all,
Longtime OWASP reader here. I'm glad to see y'all on GitHub; it makes contribution much easier.

I noticed #724. I propose we introduce a CI check that validates all links in the document are valid. Automating the check would remove the need for manual QA and hotfixing. 

## proposal

I propose we add a GitHub Workflow to check for valid links.
You can see a working example in the following project: https://github.com/exercism/v3/blob/master/.github/workflows/valid-links.yml

**Comment by tghosth** [comment]
Hi @efx. That sounds very cool.

My GitHub-fu is weak so could you set out in a little more detail what it would do and how it would manifest itself.

**Comment by efx** [comment]
I'm heads down on a deadline but will follow up in 2 or less weeks.

**Comment by efx** [comment]
I have not been able to allocate time here so will close.

**Comment by tghosth** [comment]
I will keep open in case anyone else can pick this up

**Comment by tghosth** [comment]
This isn't critical for 4.0.2 so I will remove it from the milestone for now

**Comment by tghosth** [comment]
hi @efx, I agree with the idea but we would need a PR which would do this for us. I will close the issue for now but would welcome a PR which did this.
