### ISSUE TITLE
Correction of Spelling

### ISSUE THREAD

**Issue by vermava** [OWASP/ASVS#768]
Hi Team,

Could you please correct the deployment spelling.

https://github.com/OWASP/ASVS
![ASVS](https://user-images.githubusercontent.com/18599968/82154553-50671e00-988c-11ea-864e-3ae9dcb38179.jpeg)

Thank you
Vandana

**Comment by tghosth** [comment]
hi @vermava, looks like the most recent version of that page is fixed, correct?
https://github.com/OWASP/ASVS/blob/master/README.md#introduction

**Comment by jmanico** [comment]
Its fixed
