### ISSUE TITLE
PCI DSS data element mapping

### ISSUE THREAD

**Issue by raoul361** [OWASP/ASVS#77]
Suggest including an appendix to provide mapping of level 2-3 for card data elements, such that "card holder data" requires level 2, "sensitive authentication data" requires level 3 (or 3+) - as an example.

This may even be included as a addendum V.PCI section??

**Comment by vanderaj** [comment]
Good idea.

**Comment by vanderaj** [comment]
Implemented as Appendix D by @jmanico
