### ISSUE TITLE
Wrong relationship between V5.3.7 and the CWE-943

### ISSUE THREAD

**Issue by elrond30** [OWASP/ASVS#774]
Hello,

I've seen that the ASVS V5.3.7 talks about LDAP Injection. The title of the associated CWE-943 is: "_Improper Neutralization of Special Elements in Data Query Logic._"

Searching more information I've seen that the CWE-90 says the following:
"_Improper Neutralization of Special Elements used in an LDAP Query ('LDAP Injection')_"

I think that it would be better to associate V5.3.7 with CWE-90 than associate with CWE-943

Can you confirm this pleas?

Thank you
Best regards

**Comment by jmanico** [comment]
I think this is a good idea for the 4.0.2 release, good call.

--
Jim Manico
@Manicode

**Comment by tghosth** [comment]
Agreed, resolved
