### ISSUE TITLE
We should run the CWE script as one of the last actions

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#777]
CWE script should hopefully be in issue #760

**Comment by lfservin** [comment]
as already mentioned in #760 here's the script:
`sed -Ei 's#(\| ?)([0-9]{1,4})( ?\|)#\1https://cwe.mitre.org/data/definitions/\2.html\3#' *.md`
the execution path needs to be adjusted, since I ran it directly in 4.0/en

**Comment by elarlang** [comment]
Do we actually need those links to *.md files (to data)? If links are required for pdf/docx/... output, generate it only for them. From my point of view it's another thing to clean up to use ASVS as data.

As previous discussion is in #760, but issue is closed, I link it here.

I have opened a bit related issues #809 and #810.

**Comment by tghosth** [comment]
Personally I like the idea from a convenience point of view but I admit I don't know the impact on the scripts which convert to differenf formats. What specific conversion to data format are you thinking of?

**Comment by elarlang** [comment]
The main question for all previously mentioned issue is - is this github repository more like some document or clear source of data. If it is document, then ok, we can have links. But all the tools which want to use this data later, need to parse text out from those links.

To create links to markdown here is the same like convert data to HTML specialcharacters before inserting data to database - it makes it convenient to display later back to HTML but it's done in wrong place - if you want to use this data somewhere else than HTML, it is in wrong format.

Like you can write one line to create this link to data, I can write one line to remove this link for me. Not a huge problem. But does it make sense?

**Comment by tghosth** [comment]
I think the aim is that the markdown should look good and have links and stuff so that people can refer to it directly

**Comment by lfservin** [comment]
The idea behind having the script run when "compiling" the documents is to not pollute the md files in the repository. So there should be no impact on tools parsing the existing md files.

**Comment by tghosth** [comment]
so I kinda wanted them in the MD as well but maybe we need to pursue a gitbook or something as well instead an apply the links on "compilation". I'll think more about this.

**Comment by lfservin** [comment]
You can look at my fork's branch for the status quo of the Makefile. I'm almost there. A word file can be generated, same for a pdf. it seems though as if the pdf is so far made by hand from the word file, since I couldn't fine where it is currently created. Here's the link to my WIP: https://github.com/lfservin/ASVS/blob/owasp-makefile/4.0/Makefile
it should be done before june 30th. 
other formats shouldn't be a problem

Not yet ready for a pull request, but maybe in a day or so

**Comment by lfservin** [comment]
the PDF is looking very nice. I think we can leave it like that now. Please comment on it:[OWASP Application Security Verification Standard 4.0.pdf](https://github.com/OWASP/ASVS/files/4832586/OWASP.Application.Security.Verification.Standard.4.0.pdf)

Word and odt files should look similar, but i'm having trouble with the reference document, as it produces broken docx files, that are fixed upon opening them.

**Comment by elarlang** [comment]
Few small things to consider:
- As ASVS contains already numbering, this extra numbering in documents does not seem necessary and I can smell that it actually may make some confusion - what is the correct number to point to same category or requirement - from "4.5 V1.4 Access Control Architectural Requirements" - is it 4.5 or 1.4? I know it's 1.4 but it can be confusing.
- owasp logo in footer should be lower, on the same line with "Application Security Verification Standard" and page number. Maybe it should be a bit smaller also
- Header part is a bit confusing, maybe to make it a bit transparent to keep it clearly separate from actual content.
- different color or style for links, can not detect them visually from text

**Comment by lfservin** [comment]
The first point had already been taken care of. It was just a flag in pandoc.

I'll tinker with the owasp logo tomorrow

I actually like the header, since it tells you the chapter and the section within your currently at. Can help orient yourself if printed out out when if reading on the screen. If too busy I can just take it out.

Links will be colored. Shouldn't be hard to achieve in latex. I was focused on getting the limits to cwe first working. Now I can change the style.

**Comment by lfservin** [comment]
i have now created a pdf natively from markdown with pandoc. I have two samples for which I require comments. the first one is produced straight with pandoc: 
[OWASP Application Security Verification Standard 4.0.pdf](https://github.com/OWASP/ASVS/files/4837708/OWASP.Application.Security.Verification.Standard.4.0.pdf)

the second one uses the eisvogel template from wandmalfarbe. it would require adding this template to the source tree. here's the sample: 
[OWASP Application Security Verification Standard 4.02.pdf](https://github.com/OWASP/ASVS/files/4837726/OWASP.Application.Security.Verification.Standard.4.02.pdf)

the comments from @elarlang should already be considered in the first sample. the second one presents nicer tables

**Comment by tghosth** [comment]
Assigning to @vanderaj as he is looking at the makefile.

**Comment by lfservin** [comment]
i consider the issue solved. we just need a decision towards the use of eisvogel as a latex template. the Makefile works as intended and creates all file formats with just calling make.

**Comment by tghosth** [comment]
Going to close this now to focus on the main makefile issues.
