### ISSUE TITLE
PCI-DSS section 6.x

### ISSUE THREAD

**Issue by raoul361** [OWASP/ASVS#78]
Suggest PCI-DSS 3.0 section 6.x could be referenced into ASVS, e.g.:

6.3 "Based on industry standards and/or best practices."
6.3.2 "Review custom code prior to release to production or customers in order to identify any potential coding vulnerability"

Furthermore, clear mapping should be provided for validating the 6.5.x requirements into specific ASVS requirements. This could be presented in an appendix, such that applying ASVS requirements Vx.y meets pci 6.5.z requirement. Langauge needs to be clear enough that this is guidance only.

Wording should include wording targetted at QSA's (qualified security assessor) to advise on how ASVS fits into the PCI-DSS (e.g. in terms of best practice standard)

**Comment by raoul361** [comment]
Also - PCI-DSS section 11.3 defines requirement for pen testing: "Defines application-layer penetration
tests to include, at a minimum, the vulnerabilities listed in Requirement 6.5" that could likewise be incorporated as a reference.

**Comment by vanderaj** [comment]
That's an excellent idea. Let me start the section.

**Comment by vanderaj** [comment]
Included as Appendix D by @jmanico
