### ISSUE TITLE
Various URL pointing to the old owasp site.

### ISSUE THREAD

**Issue by Marx314** [OWASP/ASVS#781]
Lots of URL are pointing to dead end.

**Comment by tghosth** [comment]
This looks great! By any chance, do you have an easy way of applying this to the https://github.com/OWASP/ASVS/tree/v4.0.2 branch as well?

**Comment by Marx314** [comment]
job's done :) I'm also in the process of translating in french, am I better to translate the v4.0.2 branch or the master branch?

**Comment by tghosth** [comment]
Please double check the links. e.g. I think "Formal-Numbering" for proactive conrols should be "div-numbering"

**Comment by Marx314** [comment]
fixed, I've also updated links to the cheatsheet that were referencing github instead of the https://cheatsheetseries.owasp.org/cheatsheets/

**Comment by tghosth** [comment]
Amazing, thanks!
