### ISSUE TITLE
[Clarification/For Discussion] Regarding 1.14.1 : 

### ISSUE THREAD

**Issue by Marx314** [OWASP/ASVS#785]
[1.14.1](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x10-V1-Architecture.md)
Verify the use of unique or special low-privilege operating system accounts for all application components, services, and servers. (C3)

What is the intent of 1.14.1?
Is is to make sure we don't have any suspicious activity for a service account or just to make sure we're align with the principle of less privileged?
Can it be summed as:
Verify that only needed account are enabled on the system.

**Comment by jmanico** [comment]
For the OS account where you’re running struts or Apache or similar you want to use the minimum priv account for the job as opposed to a su account.

--
Jim Manico
@Manicode

**Comment by Marx314** [comment]
thanks!
