### ISSUE TITLE
[Proposal] Avoid / minimize page breaks inside content tables in PDF version

### ISSUE THREAD

**Issue by scolytus** [OWASP/ASVS#786]
I would propose to try to avoid/minimize page breaks inside content tables.

This would increase the overall page count but in my humble opinion also increase readability.
I don't think it's printed too often but read on the screen. Not being interrupted by footer/header would increase readability for me.

Example:

![20200527-110405](https://user-images.githubusercontent.com/1374754/83000342-7c13a200-a00a-11ea-985f-433b14770067.png)

**Comment by tghosth** [comment]
I agree with this in principle. Maybe there is a way to configure the export to MS Word so that every Vx.y heading starts on a new page? Are you able to investigate?

**Comment by scolytus** [comment]
@tghosth Not sure if I'm _able_. I haven't looked into the build system /chain yet. I wasn't even aware that the PDF was generated via MS Word. I just noticed that this disturbs my reading flow while reading the PDF.

Is there some documentation of the build chain for newbies? Where would I start?

**Comment by tghosth** [comment]
Unfortunately not, I will take this on as an action.

**Comment by lfservin** [comment]
I've been working on issues #700 and #777. i have now create d a pdf natively from markdown with pandoc. I have two samples for which I require comments. the first one is produced straight with pandoc: 
[OWASP Application Security Verification Standard 4.0.pdf](https://github.com/OWASP/ASVS/files/4837708/OWASP.Application.Security.Verification.Standard.4.0.pdf)

the second one uses the eisvogel template from wandmalfarbe. it would require adding this template to the source tree. here's the sample: 
[OWASP Application Security Verification Standard 4.02.pdf](https://github.com/OWASP/ASVS/files/4837726/OWASP.Application.Security.Verification.Standard.4.02.pdf)

latex being latex, perhaps the tables that break unnecessarily are reduced or eliminated. please comment on the files

**Comment by tghosth** [comment]
assigning to @vanderaj as Andrew is looking at the makefile solution

**Comment by tghosth** [comment]
Going to close this now to focus on the main makefile issues.
