### ISSUE TITLE
Acronyms and case-changes

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#789]
Proposals based on https://www.e-education.psu.edu/styleforstudents/c2_p9.html

_Always write out the first in-text reference to an acronym, followed by the acronym itself written in capital letters and enclosed by parentheses. Subsequent references to the acronym can be made just by the capital letters alone. For example:_
> Geographic Information Systems (GIS) is a rapidly expanding field. GIS technology . . .

### V1.12.2

> V1.12.2 Verify that user-uploaded files - if required to be displayed or downloaded from the application - are served by either octet stream downloads, or from an unrelated domain, such as a cloud file storage bucket. Implement a suitable **content security policy (CSP)** to reduce the risk from XSS vectors or other attacks from the uploaded file.

V1.12.2 Verify that user-uploaded files - if required to be displayed or downloaded from the application - are served by either octet stream downloads, or from an unrelated domain, such as a cloud file storage bucket. Implement a suitable **Content Security Policy (CSP)** to reduce the risk from XSS vectors or other attacks from the uploaded file.

### V2.2.5

> V2.2.5 Verify that where a **credential service provider (CSP)** and the application verifying authentication are separated, mutually authenticated TLS is in place between the two endpoints.

V2.2.5 Verify that where a **Credential Service Provider (CSP)** and the application verifying authentication are separated, mutually authenticated TLS is in place between the two endpoints.

### V2.10.4

> V2.10.4 Verify passwords, integrations with databases and third-party systems, seeds and internal secrets, and API keys are managed securely and not included in the source code or stored within source code repositories. Such storage SHOULD resist offline attacks. The use of a secure software key store (L1), hardware **trusted platform module (TPM)**, or a hardware security module (L3) is recommended for password storage.

V2.10.4 Verify passwords, integrations with databases and third-party systems, seeds and internal secrets, and API keys are managed securely and not included in the source code or stored within source code repositories. Such storage SHOULD resist offline attacks. The use of a secure software key store (L1), hardware **Trusted Platform Module (TPM)**, or a hardware security module (L3) is recommended for password storage.

### V3.6.1

> V3.6.1 Verify that relying parties specify the maximum authentication time to **credential service providers (CSPs)** and that CSPs re-authenticate the subscriber if they haven't used a session within that period. 

V3.6.1 Verify that relying parties specify the maximum authentication time to **Credential Service Providers (CSPs)** and that CSPs re-authenticate the subscriber if they haven't used a session within that period. 

### V4.2.1

> V4.2.1 Verify that sensitive data and APIs are protected against **insecure direct object reference (IDOR)** attacks targeting creation, reading, updating and deletion of records, such as creating or updating someone else's record, viewing everyone's records, or deleting all records. 

V4.2.1 Verify that sensitive data and APIs are protected against **Insecure Direct Object Reference (IDOR)** attacks targeting creation, reading, updating and deletion of records, such as creating or updating someone else's record, viewing everyone's records, or deleting all records. 

### V5.3.1

> V5.3.1 Verify that output encoding is relevant for the interpreter and context required. For example, use encoders specifically for HTML values, HTML attributes, JavaScript, **URL Parameters**, HTTP headers, SMTP, and others as the context requires, especially from untrusted inputs (e.g. names with Unicode or apostrophes, such as ねこ or O'Hara). 

V5.3.1 Verify that output encoding is relevant for the interpreter and context required. For example, use encoders specifically for HTML values, HTML attributes, JavaScript, **URL parameters**, HTTP headers, SMTP, and others as the context requires, especially from untrusted inputs (e.g. names with Unicode or apostrophes, such as ねこ or O'Hara). 

### V5.3.6

> V5.3.6 Verify that the application protects against JavaScript or JSON injection attacks, including for eval attacks, remote JavaScript includes, **content security policy (CSP)** bypasses, DOM XSS, and JavaScript expression evaluation. 

V5.3.6 Verify that the application protects against JavaScript or JSON injection attacks, including for eval attacks, remote JavaScript includes, **Content Security Policy (CSP)** bypasses, DOM XSS, and JavaScript expression evaluation. 

### V5.3.7
> V5.3.7 Verify that the application protects against **LDAP Injection** vulnerabilities, or that specific security controls to prevent **LDAP Injection** have been implemented. 

V5.3.7 Verify that the application protects against **LDAP injection** vulnerabilities, or that specific security controls to prevent **LDAP injection** have been implemented. 

### V11.1.6
> V11.1.6 Verify the application does not suffer from "**time of check to time of use**" (TOCTOU) issues or other race conditions for sensitive operations. 

V11.1.6 Verify the application does not suffer from "**Time Of Check to Time Of Use**" (TOCTOU) issues or other race conditions for sensitive operations. 

### V14.2.3
> V14.2.3 Verify that if application assets, such as JavaScript libraries, CSS or web fonts, are hosted externally on a **content delivery network** (CDN) or external provider, **Subresource Integrity** (SRI) is used to validate the integrity of the asset.

V14.2.3 Verify that if application assets, such as JavaScript libraries, CSS or web fonts, are hosted externally on a **Content Delivery Network** (CDN) or external provider, **SubResource Integrity** (SRI) is used to validate the integrity of the asset.

### V14.4.3
> V14.4.3 Verify that a **content security policy** (CSP) is in place that helps mitigate impact for XSS attacks like HTML, DOM, JSON, and JavaScript injection vulnerabilities. 

V14.4.3 Verify that a **Content Security Policy** (CSP) is in place that helps mitigate impact for XSS attacks like HTML, DOM, JSON, and JavaScript injection vulnerabilities. 

### V3.6.2

> V3.6.2 Verify that **credential service providers (CSPs)** inform relying parties of the last authentication event, to allow **RPs** to determine if they need to re-authenticate the user. 

V3.6.2 Verify that **Credential Service Providers (CSPs)** inform relying parties of the last authentication event, to allow **relying party** to determine if they need to re-authenticate the user.

**Comment by tghosth** [comment]
@vanderaj any thoughts on this?

**Comment by elarlang** [comment]
@tghosth @vanderaj - any decision about this issue?

I pointed out here only noticed acronyms/initials from requirement descriptions. If to make things correctly, entire document needs some work.

**Comment by tghosth** [comment]
I agree with you @elarlang, can you open a PR with some fixes?

**Comment by tghosth** [comment]
This should be fixed now. There are a couple of irregular examples. For example, Multi-factor Authentication (MFA) or [Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) (SRI) but it should be reasonably consistent now.
