### ISSUE TITLE
Acronyms never explained in document

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#790]
Should those also be explained?

- TOTP "Time-based One Time Password"
  - better to use "time-based OTPs" like in V2.8.1 and V2.8.4
- FIDO "Fast IDentity Online"
- U2F "Universal Second Factor" or "Universal 2nd Factor"
- PBKDF2 "Password-Based Key Derivation Function 2"
- PSTN "Public Switched Telephone Network"
- RP "relying party"
- WYSIWYG "What You See Is What You Get"
- SSRF "Server-Side Request Forgery"
- HQL "Hibernate Query Language"
- ORM "Object-Relational Mapping"
- XXE "XML External Entity"

## OTP

One Time Password (OTP) is defined in V2.8 category description but used earlier

- V2.2.6
- V2.2.7
- V2.5.7

and "One Time Password (OTP)" is never explained inside a requirement

## TPM
- Used already in V2.9.1
- explained in V2.10.4 trusted platform module (TPM)

**Comment by tghosth** [comment]
Are any of these in the glossary?

**Comment by elarlang** [comment]
Can you please rephrase the questions, I'm not sure I can understand it correctly.

**Comment by csfreak92** [comment]
Don't we have subsections explaining some of those acronyms, no?

**Comment by elarlang** [comment]
@csfreak92  from your question I expected, that I have missed something and double checked. The answer is no.

- Now there is SSRF used (because of #798)
- RP is descibed in 3.6 section description.

Anyway, this was my question and take it as discussion - should we explain (write them out once) those or not? There is always some "expectation from reader", we don't need to explain what HTML means I guess.

**Comment by tghosth** [comment]
@elarlang I meant are these acronyms included in the glossary section of the ASVS: https://github.com/OWASP/ASVS/blob/master/4.0/en/0x90-Appendix-A_Glossary.md

**Comment by elarlang** [comment]
No, listed initials/acronyms does not exist in any latest .md file or generated v4.0.1 PDF file.

**Comment by tghosth** [comment]
So do you think they should be added to the glossary?

**Comment by elarlang** [comment]
Yes, all acronyms and initials should be to explained in the document.

**Comment by tghosth** [comment]
OK so please create PRs for 4.0.2 and 4.1 to add these to the glossary.

**Comment by jmanico** [comment]
I agree with Elar; thank you for this! 🙏 

--
Jim Manico
@Manicode

**Comment by elarlang** [comment]
I can put those acronyms there, but it requires some explanations also...

**Comment by tghosth** [comment]
Good point about the explanations. Open a PR against 4.1, add as many explanations as you feel you can and I will add the rest and then I will figure out how to drag the change back to 4.0.2 🙃

**Comment by tghosth** [comment]
Hi @elarlang, please could you open this PR against master :) I can then go in and update as necessary.

**Comment by elarlang** [comment]
This is something which I have started many times but never reached anywhere (additionally to just search and write out those acronyms). Reality is that no PR from me for this one...

**Comment by tghosth** [comment]
Hi @elarlang, please could you review PR #832 and let me know if you have any comments.

**Comment by elarlang** [comment]
Definitely it's a improvement.

Glossary itself does not follow only one rule or pattern how to describe acronyms, new ones:
```
**Fast IDentity Online** (FIDO) - A set of authentication ...
```

Some old ones:
```
**SAST** – Static application security testing (SAST) 
```

If to go through every item one-by-one, then we can have a lot of discussions how to write certain acronym or explanation (like `Server-side` vs `Server-Side`).

**Comment by tghosth** [comment]
Ok I have fixed the pattern thing but I don't want to get into discussions on every single one at this point.
Any other key points?

**Comment by elarlang** [comment]
> I don't want to get into discussions on every single one at this point.

Yes, I agree, that's why I said "If". I think it's a bit bigger topic and should be covered/synchronized over different OWASP projects.

Issue closed for me.
