### ISSUE TITLE
V7.2.1 session token vs session identifier

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#792]
[V7.2.1](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x15-V7-Error-Logging.md#v72-log-processing-requirements)

Current:
> V7.2.1 Verify that all authentication decisions are logged, without storing sensitive **session identifiers** or passwords. This should include requests with relevant metadata needed for security investigations.

Only requirement, where "session identifier" is used. Everywhere else is "session token".

Proposal:
> V7.2.1 Verify that all authentication decisions are logged, without storing sensitive **session tokens** or passwords. This should include requests with relevant metadata needed for security investigations.

**Comment by tghosth** [comment]
Good call
