### ISSUE TITLE
V4.3.2 - split to 2 different requirements

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#800]
[V4.3.2](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x12-V4-Access-Control.md#v43-other-access-control-considerations)

Current:
> V4.3.2 Verify that directory browsing is disabled unless deliberately desired. Additionally, applications should not allow discovery or disclosure of file or directory metadata, such as Thumbs.db, .DS_Store, .git or .svn folders. 

Problems:
- it contains 2 separate problems which requires separate defense methods
- if you disable directory browsing, mentioned files and folders are still readable
- if you disable reading mentioned files, it does not affect directory browsing

Proposal, split to 2 different requirements.

Second part of the requirement maybe should be merged with current V12.5.1?
> V12.5.1 Verify that the web tier is configured to serve only files with specific file extensions to prevent unintentional information and source code leakage. For example, backup files (e.g. .bak), temporary working files (e.g. .swp), compressed files (.zip, .tar.gz, etc) and other extensions commonly used by editors should be blocked unless required.

Milestone ASVS v4.1 (as it changes requirements numbers)

**Comment by tghosth** [comment]
I agree with the split and would be open to wording.

Regarding 12.5.1, I would rather keep the reuqirement separate as I think 12.5.1 might be difficult to implement practically.

**Comment by elarlang** [comment]
I try to move on with that.

Proposal - split current V4.3.2 to separate requirements (needs language correction):
* V4.3.2 Verify that directory browsing is disabled unless deliberately desired. 
* V4.3.NEW Verifify that applications do not allow discovery or disclosure of file or directory metadata, such as Thumbs.db, .DS_Store, .git or .svn folders.

**Comment by jmanico** [comment]
This is really I would dare say picky stuff can we please keep it in one requirement and handle both cases?  I would say get rid of directory browsing and just make sure that sensitive data can’t be exposed. Directory browsing itself is rarely a risk it’s the exposure of files on the web server that shouldn’t be exposed that’s the problem.

Or even better I would just remove this requirement altogether. This is already covered by the access control POLP rules that we talked about earlier....

--
Jim Manico
@Manicode

**Comment by elarlang** [comment]
## Directory browsing

Directory browsing is problem. Really small one separately, but in for crappy PHP world where _everything_ is in public folder and `.htaccess` or other protection is disabled by web server, it helps attackers to browse around. For me it still makes sense to keep it. If I compare it with "don't show application/server version number" (V14.3.3), then I would say, more important is to disable directory browsing.

## Thumbs.db, .DS_Store
There can be some kind of leakage.. I don't care too much about those (or probably I have not done enough research on this topic)

## .git, .svn, CVS
This is must-have, and actually it deserves separate requirement. See https://github.com/arthaud/git-dumper for example.

**Comment by jmanico** [comment]
My understanding is that figuring out what technology you’re using and what version you’re using of everything is easy via fingerprinting tools so I don’t think it’s a real risk to know what framework version you’re using; I can figure that out very easily. So again I assert that while directory browsing is not great I don’t think it’s a big enough of a problem to put into ASVS.

My conjecture is at the real problem is exposing files that should not be exposed and that simply an access control problem covered under POLP.

This is just my take on it love to get other people to chime in.

--
Jim Manico
@Manicode

**Comment by elarlang** [comment]
This is the reason, why I took parallel with "showing server version". If you hide it, you don't fix "problems with using old version of software", but you also don't advertise it.

The same with directory browsing - if you disable it, you don't fix "accessing file directly" problem, but you don't share list of files in folder and you don't make it easier for attackers or for search engines to index potentially sensitive content (yes, it's again another topic). Disable directory listing is way more needed in practice than a lot of other requirements in ASVS.

Probably you can not say that there is no difference for attackers is directory browsing enabled or not. Till there is difference for attackers, it make sense to keep this requirement in ASVS. Even it's 2nd, 3rd or n-th level "defense".

**Comment by jmanico** [comment]
I'm with you now. PR for this sounds good.

**Comment by elarlang** [comment]
If I reanalyze them - I think both requirements (after spliting current 4.3.2) fits better to 14.3 subcategory (V14.3 Unintended Security Disclosure Requirements) as those are not access control problems from application point of view.

**Comment by jmanico** [comment]
Agreed @elarlang

**Comment by elarlang** [comment]
When we will have requirement like: "Verifify that applications do not allow discovery or disclosure of file or directory metadata, such as Thumbs.db, .DS_Store, .git or .svn folders." in category V14.3 Configuration > "Unintended Security Disclosure"

and currently we have requirement "V12.5.1 Verify that the web tier is configured to serve only files with specific file extensions to prevent unintentional information and source code leakage. For example, backup files (e.g. .bak), temporary working files (e.g. .swp), compressed files (.zip, .tar.gz, etc) and other extensions commonly used by editors should be blocked unless required.
" in category V12.5 File and Resources > File Download

but for me it feels those should belong to same subcategory, and I could propose 14.3 here. 12.5.1 is not related application's file download functionality, but in case some "wrong files" are placed to public folder web application should disallow to access them.

**Comment by jmanico** [comment]
I agree these should be in different categories. One is essentially a configuration issue and another is a developer code issue.

**Comment by elarlang** [comment]
Jim, could you specify with what you agreed, there is space for interpret it in different ways.

**Comment by jmanico** [comment]
I agree with your post above. Both of these requirements should be in 14.3

**Comment by elarlang** [comment]
Current requirement:
* V4.3.2 Verify that directory browsing is disabled unless deliberately desired. Additionally, applications should not allow discovery or disclosure of file or directory metadata, such as Thumbs.db, .DS_Store, .git or .svn folders.

Split and move to category "V14.3 Configuration > Unintended Security Disclosure"

Proposal 1: `[ADDED, SPLIT FROM 4.3.2]`
* V14.3.4 Verify that directory browsing is disabled unless deliberately desired.
* [CWE-548](https://cwe.mitre.org/data/definitions/548.html)

Proposal 2: `[ADDED, SPLIT FROM 4.3.2]`
* V14.3.5 Verifify that applications do not allow discovery or disclosure of file or directory metadata, such as Thumbs.db, .DS_Store, .git or .svn folders.
* CWE ? <- need help here. From different CWE's for .git (source code leakage) and Thumbs.db (some thumbnail leakage) we may want to split it again.

I'll make separate issue for mentioned V12.5.1 if this issue is finished.

**Comment by jmanico** [comment]
I like this split, there is no good CWE for proposal 2 and suggest we keep it blank.
