### ISSUE TITLE
Use inclusive language

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#801]
Placeholder to organise us to continue the changes which @danielcuthbert began in https://github.com/OWASP/ASVS/commit/23c983b8d0e2f4720a8d28dd87dc722e826d047c to use language which is more inclusive.

**Comment by tghosth** [comment]
Should also check for use of master/slave

**Comment by tghosth** [comment]
Man, male, female

**Comment by danielcuthbert** [comment]
This is a *really* important aspect about the standard. Most standards today, in my opinion, make use of strong language that doesn't translate well to other languages, terms that are no longer welcoming or inclusive and it's our responsibility to help be the change. 

Appreciate any effort by the community to make this better, so thank you up front.

**Comment by jmanico** [comment]
I think the important thing is that the effort to do this is not so bad. A little effort goes a long way in making the world a better place.

Whomever started this? Thank you!

--
Jim Manico
@Manicode

**Comment by tghosth** [comment]
Our main branch is called master 🤦‍♂️

**Comment by jmanico** [comment]
Let’s change it to better words..

Replace master with say freedom or liberty or equality

Yea rename it equality 

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by elarlang** [comment]
> Let’s change it to better words.. Replace master with say freedom or liberty or equality Yea rename it equality

Maybe I just live in this part of the world then I don't realize or feel this problem.. but this a bit too much in my opinion.

What problems we solve with that change vs what problems we create with that change?

I think we don't hurt anyone's feelings when the branch name is like it is default and used in entire industry. It makes it clear, understandable and usable. If it's not default, it creates overhead - "hey, where is your master branch, where should I send my pull request?"

I don't want to open any political discussion here.

**Comment by jmanico** [comment]
It’s a small effort to acknowledge the institution racism from the US and world at large by changing this name. Slavery, US Jim Crowe laws, segregation, police brutality, etc.

Several terms in IT come from that era. Blacklisting as well as master-slave servers have a bad history.

So yea, be political. Change is in the air and we need to seize this moment.

Also please note, we are NOT asking for a call to action from anyone, we are simply changing a name to be a little better.

🤙🏼 

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by tghosth** [comment]
- Master only appears in a URL in 0x03-Using-ASVS.md which we would need to change if we change the branch name.
- Black/whitelist references have all been removed from 4.0.2 and master branches.
- male/man/men/female/him/his not in use.

Next task is to go through: https://developers.google.com/style/inclusive-documentation

**Comment by tghosth** [comment]
crazy, insane, blind, cripple, dumb

Replaced native with built-in https://github.com/OWASP/ASVS/commit/49d63c54537dc02c154a7ff99101cea2525c59b3

I think that is everything for now...
