### ISSUE TITLE
Does the ASVS cover desktop applications?

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#803]
We have previously discussed this in #663 and #773.

Does the ASVS cover desktop applications?

In, #663 I asked about adding [v9.1.4](https://github.com/OWASP/ASVS/blob/8d773b79ef33ffd2bbd22cfe216aaab29bfb49e0/4.0/en/0x17-V9-Communications.md#v91-client-communications-security-requirements) related to certificate pinning. At that time, @danielcuthbert approved and merged it.

In #773 we were discussing "deploying binaries" and @jmanico said:

> Respectfully, ASVS is for web and API apps only. Desktop threat model is
so very different than web, it's much closer to the mobile threat model
than a web app.
>
> I politely suggest we both remote and "desktop app only" requirements
and make it clear in the ASVS description that we're really the WASVS
for the Web.
>
> cc Daniel Cuthbert and Andrew V, am I right from your perspective?
>
> Respectfully,
>
> Jim Manico

@jmanico @danielcuthbert @vanderaj any consensus on this? :)

**Comment by danielcuthbert** [comment]
A hard and tricky subject. 

If we look at traditional desktop applications, compiled binaries that may, or may not, interact with additional services such as APIs or data stores etc then yes this ASVS isn't ideal but could prove some benefit. 

If we are talking about modern desktop applications that use frameworks like Electron, and other web-like frameworks, then the ASVS does apply a lot and can help. 

the worry about making it WASVS is that the nature of the web is changing so rapidly, do we not run the risk of alienating such initiatives?

**Comment by tghosth** [comment]
@vanderaj any further thoughts?

**Comment by jmanico** [comment]
I still think we need to drop desktop requirement and move those to MASVS where they are  more appropriate.

**Comment by danielcuthbert** [comment]
I agree with this stance. If we are talking about Electron-based apps (JavaScript) then we could support it but then it becomes a slippery slope. I can't see this working out the way many would like it to
