### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by Marx314** [OWASP/ASVS#805]
Title say it all, french translation.

**Comment by vanderaj** [comment]
Hi @Marx314 - I'd like to make sure the French translation hits the 4.0.2 branch. We'll get the list of changes sorted, and if you could make sure that the French translation picks those changes up, I'll happily merge a PR with the french translation for you.

**Comment by Marx314** [comment]
I've adjusted to the last change from Josh (the BLM commit). Charles gave his modification, Sebastien did review the V1 but not sure for the rest.

In short, ready when you are, do you want me to open another PR on the branch 4.0.2 or simply merge this in master than merge the commit back in 4.0.2?

**Comment by SPoint42** [comment]
Will do tomorrow a whole review and send PR

sent from mobile

Le 23 juin 2020 20:34, Marx314 <notifications@github.com> a écrit :

I've adjusted to the last change from Josh (the BLM commit). Charles gave his modification, Sebastien did review the V1 but not sure for the rest.

In short, ready when you are, do you want me to open another PR on the branch 4.0.2 or simply merge this in master than merge the commit back in 4.0.2?

**Comment by tghosth** [comment]
I think this was all merged in, please let me know if you think there is anything missing.
