### ISSUE TITLE
remove V5.3.3, it's is duplicate of V14.2.1 and not actionable

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#807]
"Spin-off" from discussion in #775 - conclusion by @jmanico:

[5.5.3](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x13-V5-Validation-Sanitization-Encoding.md#v55-deserialization-prevention-requirements)

Current V5.3.3 is duplicate of V14.2.1 and not actionable

> V5.5.3 Verify that deserialization of untrusted data is avoided or is protected in both custom code and third-party libraries (such as JSON, XML and YAML parsers).

> V14.2.1 Verify that all components are up to date, preferably using a dependency checker during build or compile time.

Milestone v4.1

**Comment by tghosth** [comment]
@elarlang can you think of a text for 5.5.3 which would be more actionable?

**Comment by elarlang** [comment]
Not really. I just took this info from another issue (#775) to keep things clear and separate. Content is solo-project for @jmanico.

**Comment by jmanico** [comment]
On it.

--
Jim Manico
@Manicode

**Comment by jmanico** [comment]
Issue solved with this commit to master https://github.com/OWASP/ASVS/commit/25783d0a725795e4f4d7b128c29cc713f3613d7f
