### ISSUE TITLE
Cleanup verification descriptions (V3.4.4 and V13.2.3) from references

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#809]
## References

[V3.4.4](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x12-V3-Session-management.md#v34-cookie-based-session-management)

> V3.4.4 | Verify that cookie-based session tokens use "__Host-" prefix **(see references)** to provide session cookie confidentiality.

[V13.2.3](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x21-V13-API.md#v132-restful-web-service-verification-requirements)

> V13.2.3 | Verify that RESTful web services that utilize cookies are protected from Cross-Site Request Forgery via the use of at least one or more of the following: triple or double submit cookie pattern **(see [references](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html))**, CSRF nonces, or Origin request header checks.

Only 2 requirements have "see references" as part of requirement text and only one of them is provided in markdown syntax link.

I think requirement description should have clean text without any extra references.

Problem - if to use data in JSON format or want to use description text, then you need to cleanup requirement texts manually. Description text is not usable like it should be.

**Comment by tghosth** [comment]
I agree with avoiding links within the requirement text. I will take this as there is another issue related to triple submit cookies.

**Comment by elarlang** [comment]
This related question can be based on my created issue there: https://github.com/OWASP/CheatSheetSeries/issues/195

Another question - V13.2.3 is a bit duplicate for V4.2.2 where there is no list of potential defense solutions. Isn't this list actually too complicated to maintain - to list all potential solutions?

**Comment by tghosth** [comment]
What is in 4.2.2?

**Comment by elarlang** [comment]
[V4.2.2](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x12-V4-Access-Control.md#v42-operation-level-access-control)

> V4.2.2 Verify that the application or framework enforces a strong anti-CSRF mechanism to protect authenticated functionality, and effective anti-automation or anti-CSRF protects unauthenticated functionality.

Another related issue to V4.2.2 - #795

**Comment by tghosth** [comment]
OK, taking your other question to #795.

Action on me to get the triple submit cookie thing resolved.

**Comment by tghosth** [comment]
Backported to v4.0.2 by #822
