### ISSUE TITLE
[Clarification needed] usage of "V" prefix

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#812]
For categories/titles we have "V" prefix, for requirements we don't have.

Questions:
- what is the argumentation for that?
- what is the correct way to reference to a requirement? `V1.1.1` vs `1.1.1`?
  - Related to issue #715 - with reference standard, should we use `v4.0.2-V1.1.1` or `v4.0.2-1.1.1`?
  - Question is also raised here: https://github.com/OWASP/ASVS/pull/804#issuecomment-639459411

**Comment by tghosth** [comment]
Have you noticed any pattern to when the v prefix is and is not used?

**Comment by elarlang** [comment]
Pattern:
> For categories/titles we have "V" prefix, for requirements we don't have.

**Comment by vanderaj** [comment]
Normalize the usage of "V". I think that 4.0.2 shouldn't remove the "V", so let's make it universal. Any breaking changes to naming scheme should affect the least number of items to improve attribution of element types.

**Comment by kingthorin** [comment]
What does it represent though? I'm all for standardization and consistency, but if it doesn't have a relevant function (other than "that's how it's always been") then the project should plan to drop it in v5. (Agreed 4.0.2 shouldn't have 'breaking' changes.)

**Comment by kingthorin** [comment]
It's been 3 weeks. Any feedback/answers?

**Comment by danielcuthbert** [comment]
I'd vote to make it all upper case, so V across the board. It shouldn't break at all, as @kingthorin said. adding this to my stack

**Comment by elarlang** [comment]
To be really clear with that...

.. what means "all upper case"? For (sub)categories and requirements?

Example:
- V1 title
  - V1.2 subtitle
    - V1.2.3 Verify that requirement...

And as reference with version number: `v4.0.2-V1.2.3`?
"all upper case" in this example is a bit alarming because of lower-case "v" for version.

**Comment by danielcuthbert** [comment]
yes for all. You should capitalise every sentence, and whilst it's generally accepted that one doesn't capitalise after a list, in this case, won't use them where this will be an impact. 

V1 category
V1.2 subcategory
V1.2.3 Verify that requirement...

Here, this looks clean over anything else, if that makes sense?

**Comment by kingthorin** [comment]
Hahahaha. As we can see this needs some sort of tie breaker. Or an actual answer as to what the `v` is meant to represent:

> What does it represent though? I'm all for standardization and consistency, but if it doesn't have a relevant function (other than "that's how it's always been")

Since it's already inconsistently applied is no more breaking to drop it than use it everywhere. We just need a majority (2/3, 3/5...whatever call on it.)

**Comment by elarlang** [comment]
@danielcuthbert  For me it makes sense.

@kingthorin My conclusion at the moment is:
- `V` (upper-case) - stands for "Verification" (just my interpretation, not sure is the "V" originated from the word) and will be before
  - category number (V1)
  - subcategory number (V1.2)
  - verification requirement (V1.2.3)
- `v` (lower-case) - stands for "version"
- reference standard will have format `v4.0.2-V1.2.3`

**Comment by kingthorin** [comment]
> how to point to "bleeding edge" number? Like most of the time when we talk/discuss about some requirements in github issues :)

Without including the version it should be assumed to refer to the latest available (released or not). If there is no match then it can either be assumed to refer to the last standard where it did match or that it's an error.

**Comment by kingthorin** [comment]
Since @elarlang and @danielcuthbert both seem to be on-board with the capital V, I'll update the reference standard PR and hopefully that can get merged. Then it can be tackled within the standard doc and www repo.

**Comment by vanderaj** [comment]
Thank you for the pull request. :) 100% support from me.

**Comment by elarlang** [comment]
Clarification done and reference standard is changed.

Do we put this capital "V" before every requirement number also? Or this is now too big change for v4.0.2 and need to wait some next version?

**Comment by vanderaj** [comment]
Elar, traditionally, ASVS 1.0 did have that, but it's too big a change for 4.0.2. 

I like that the differences in the way we do headings makes it clear that there is a difference between a section or sub-section rather than an individual requirement. 

For example, V2.2 is a sub-section, but 2.2.2 is an individual requirement. Plus, this is how it is now, and I've just checked to make sure all sections and sub-sections are V\d.\d[.\d]. This is also the least change to what we have today. 

Josh and I have discussed this, and we'd like to leave individual requirements without a V for the 4.x series.

**Comment by elarlang** [comment]
Well, then it's not clear at all. Discussion above made kind of conclusion that we'll have "V" also for requirements.

If we will not have "V" for requirements, then I would say we have conflict how identifiers are presented in ASVS document and how we recommend to use them in references (`2.2.2` vs `v4.0.2-V2.2.2`).

**Comment by tghosth** [comment]
I will clarify in a few days to finalise this.

**Comment by tghosth** [comment]
OK, the short version is this. The V in all of this stands for verifier. Historically, this was applied to the actual requirement identifiers but in version 4.x it only appeared to be applied to sections (V1) and sub-sections (V1.1).

Regardless of what is written above, we don't want to go and add it back to all requirements so we basically want to leave it as it is. That will mean a small change to the "reference standard" as the "reference standard" will generally refer to requirements and not sections and sub-sections.

Hope that is clearer to everyone now and apologies for the confusion :)

**Comment by elarlang** [comment]
Ok, question got answer.

For the future - personally I prefer V for requirement as well. 

> I like that the differences in the way we do headings makes it clear that there is a difference between a section or sub-section rather than an individual requirement.

This is something which I watch differently. I don't have any problem to understand what is requirement and what is section/sub-section title. If something needs capital "V" then actually the first one in my opinion should be "Verify that" requirement.

It's not only this document here - for pen-test reports it's way easier to understand that V1.2.3 points to ASVS requirement than 1.2.3 which can be whatever number.
