### ISSUE TITLE
Differences generating document from markdown

### ISSUE THREAD

**Issue by muralito** [OWASP/ASVS#816]
The document generated by the script it's not the same as the published docx.
Now i am using: pandoc --version
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.2, skylighting 0.8.4

This is with unmodified 4.0.2 branch.
The main problem is with pagination, as every section does not start in a new page, at least in Office 2013, Office online. And opening the docx in LibreOffice 6.4. or 7.0 beta ithe result is worse. 

My need to generate the document is because i have created a branch of 4.0.2 and added some new items "x.y.50+"  that are extensions needed by my organization.

I also tried to generate the pdf directly with pandoc and pdf-engine lualatex but the generated tables are bigger than the margins or the page, and they escape to the right.

**Comment by muralito** [comment]
The latex build using the makefile from lfservin fork https://github.com/lfservin/ASVS works ok for me. (found it in issue #787)

**Comment by lfservin** [comment]
if you need to start every section in a new page, we might need a filter to the script. I've seen one of the ASVS-derived works (SCVS) using a filter to create the correct code for newline for all formats. that could work.
