### ISSUE TITLE
Evaluate Use of OSCAL Standard

### ISSUE THREAD

**Issue by tohch4** [OWASP/ASVS#817]
Per discussion in [OWASP #project-asvs channel thread](https://owasp.slack.com/archives/C06MNF14M/p1593029302063200), I would like to assist and know further steps for evaluating the use of OSCAL to produce ASVS controls.

>NIST, in collaboration with industry, is developing the Open Security Controls Assessment Language (OSCAL). OSCAL is a set of formats expressed in XML, JSON, and YAML. These formats provide machine-readable representations of control catalogs, control baselines, system security plans, and assessment plans and results.
>
> From [NIST OSCAL site](https://pages.nist.gov/OSCAL/)

I am willing to work on assessing this, and would be very interested in building in the CI tooling once I communicate with the OSCAL developers about the efficacy after reviewing [Creating a Basic Control Catalog Tutorial](https://pages.nist.gov/OSCAL/tutorials/catalog/).

How do I proceed?

**Comment by danielcuthbert** [comment]
Ok this is interesting and I can see the benefit, easiest way to start is create an example and ping it back here to see how it might fit in

**Comment by danielcuthbert** [comment]
Closing this for now.
