### ISSUE TITLE
Semantic Versioning and the question of 4.1 vs 5.0

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#819]
@ThunderSon mentioned how we match ourselves to semantic versioning.

Adding this issue as a placeholder to decide this before 4.1.

We had some internal discussion between the leaders and I will add a summary at a later date.

**Comment by tghosth** [comment]
Useful comment from @ossie-git https://github.com/OWASP/ASVS/issues/750#issuecomment-650817817

**Comment by tghosth** [comment]
Now that 4.0.2 has been released, I think we are now in a position to discuss how we address this.

During a leaders discussion, we noted a couple of possible approaches for the next significant revision which would potentially comply with semantic versioning. We are also open to other suggestions. This new revision would come out mid-2021 at the earliest.

1) Make the next version 4.1.

In this case, we would add new requirements to the end of existing suggestions we would not remove or significantly change the meaning of existing requirements but if necessary we would retire certain requirements and add new ones. This would avoid breaking existing requirements but also provide additional or improved requirements making it easier for existing 4.0.x users. It would also potentially be a faster release.

2) Make the next version 5.0

This would be like the change from 3.x to 4.x where we make very significant changes, move requirements, remove requirments, change numbering etc. The end result would be cleaner but it would be harder to migrate.

Please let us know your thoughts below.

**Comment by elarlang** [comment]
Just some quick ideas which I have in mind for next release(s):
* split business-logic and anti-automation requirements to different subcategories
  * does match with idea of v4.1 or should it have v5.0?
* there will be some proper changes in V3 for sure
  * I think it's doable with v4.1
* review password requirements (https://github.com/OWASP/ASVS/issues/683)
  * doable with v4.1
* review topic "keeping component's permissions as low as possible"
  * doable with v4.1
* new "web sockets" (sub)cateogry?
  * probably smells like v5.0

Some related discussions on this topic has been in issues below and I think we are going to repeat all the arguments written in those:
* https://github.com/OWASP/ASVS/issues/666
* https://github.com/OWASP/ASVS/issues/750

And why there is "OR question" - v4.1 OR v5.0? Why not v4.1 AND v5.0?

We need to look again to calendar perspective - how often we actually have enough content and changes to send out? If I make change at the moment and it will be released in one year, then... I think community is not very enthusiastic to work with this project if there is no impact in near future.

So, personally I hope to have both - v4.1 with some new/deleted/moved requirements and later v5.0 with some new sections or reorganized categories.

**Comment by tghosth** [comment]
So for me the question is, will a 4.1 be useful to people or will it just be messy (with requirements just being added on to the end of sections regardless of level and requirements being retired) and not widely used.

**Comment by elarlang** [comment]
Can we have some direction or decision on that field? If I could start doing PRs, then it makes sense to follow some guidance do not cause some mess in category and requirement numbers.

**Comment by tghosth** [comment]
@kingthorin 
> If bleeding edge already contains breaking changes then plan for 5.0
https://owasp.slack.com/archives/C06MNF14M/p1612445051082700

**Comment by tghosth** [comment]
@elarlang 

>if you say, that 5.0 will not come before 2 years, I say that ok, let's go for 4.1
> if the question is, which version we can release in half-of-year, I say 5.0
> https://owasp.slack.com/archives/C06MNF14M/p1612446610106000

**Comment by kingthorin** [comment]
Also me on slack:

> Set the version based on changes vs setting the changes based on anticipated version.

From the outside looking in it seems like the project needs to embrace the community's (or a few individual's) willingness to contribute and implement change(s). Of course that assumes that there are leaders available to review PRs etc. 
Perhaps if that's not the case then a new plan/structure is necessary? Get a volunteer core of people familiar with ASVS to do reviews? [Note: that's not me.] Find some additional or different leaders? Ask the community to do initial reviews for grammar and simpler things then have sprints once a month or something when leaders can plan to review any "ready" PRs? 🤷  That's just off the top of my head, I'm sure there are many other options as well.

**Comment by tghosth** [comment]
Broadly speaking we agreed on trying to match semantic versioning where a patch does not change meaning, a minor change adds and removes requirements but does not change numbering to avoid compatibility and major change will change all sorts of things.
