### ISSUE TITLE
V2.12 (add below) (level 3) logging of metadata

### ISSUE THREAD

**Issue by raoul361** [OWASP/ASVS#82]
When logging authentication (particularly suspicious logons), ensure there is sufficient metadata available in logs to assist in any incident investigation; e.g. IP, user-agent, location, etc.

**Comment by athiasjerome** [comment]
More than that, the format of the logs should be compliant with policy (to be easily integrated within SIEM).
It is recommended using the same log format, and 1 library/component per app technology

**Comment by danielcuthbert** [comment]
We don't know what policy is required, so adding it in is hard. I feel as it stands currently, 2.12 is sufficient
