### ISSUE TITLE
Level 1 Verification Requirements

### ISSUE THREAD

**Issue by raoul361** [OWASP/ASVS#83]
Based on what has been provided for Levels 2 and 3, suggest that level 1 verification requirements could be largely tool based - automate scans with assertion/interview/validation (?) that  specific practices are in place to ensure code quality will be met (e.g. testing, architecture, etc).

Whilst level 3 clearly indicates a primarily manually tested application, I do not believe an automate scan should ever be sufficient in and of itself.

Another approach may be to borrow the PCI method of having Level 1 be a self attestation, Level 2 be a review and Level 3 be an in depth audit. That is likely to be commensurate with the risk of the application.

Level 0 could then be entirely tool based, allowing for vendors to give an initial rating without use of the term certified, verified, etc.

**Comment by danielcuthbert** [comment]
Hi

That's correct. Level 1 is indeed something a tool could do and we are in talks with both ZAP and Burp scanners to have a level 1 scan option in them. Level 3 is fully manual and this is where experience comes into play. 

I'm cautious about going down the PCI route as I personally feel PCI is a toothless checklist and doesn't offer any value at all. If a company wants a level 1 scan, there has to be someone checking the results to see if there is nothing untoward being reported back.
