### ISSUE TITLE
Add Appendix D: Blockchain Verification Requirements

### ISSUE THREAD

**Issue by GraoMelo** [OWASP/ASVS#833]
congratulations to all for the excellent work with ASVS. 4.0.1

I want to contribute some observations for the development I suggest using blockchain and derivatives.

# the general idea.

the idea is to replicate what was done in appendix C. but for general use blockchain, Cryptocurrency, Distributed ledger technology 
 
## Control Objective
Nodes, Wallets, call rpc, 

## reference and cases of use. 
the idea is to organize all the tools that may be related to blockchain within OWASP projects, thus creating a guide of good practices.
I will also bring an analysis of problems that occur most in each paradigm within blockchain projects.

**Comment by tghosth** [comment]
Sent you an email, let me know what you think :)

**Comment by GraoMelo** [comment]
@tghosth thank you, I answered your email.
