### ISSUE TITLE
Req # 2.2.5 - How would such a scenario look like?

### ISSUE THREAD

**Issue by dschwarz91** [OWASP/ASVS#837]
Referring to req # 2.2.5 (https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#v22-general-authenticator-requirements):
"Verify that where a Credential Service Provider (CSP) and the application verifying authentication are separated, mutually authenticated TLS is in place between the two endpoints."

How exactly would such a scenario look like?
What would be the task of the CSP if he doesn't verify the authentication?

Thanks in advance.

**Comment by jmanico** [comment]
I prefer to fully drop this requirement, its strange. Would you care to PR the removal of this requirement?

**Comment by cmlh** [comment]
> I prefer to fully drop this requirement, its strange. Would you care to PR the removal of this requirement?

@jmanico Can you or an admin create a label such as "Create PR" so we can track those needing a PR?

**Comment by danielcuthbert** [comment]
We are mapping to the NIST standard and will be leaving this as is.

**Comment by cmlh** [comment]
> We are mapping to the NIST standard and will be leaving this as is.

Based on the adverse outcome of https://www.parliament.nsw.gov.au/lcdocs/inquiries/2611/Report%20No%2052%20-%20PC1%20-%20Cyber%20Security.pdf against NIST CSP (quoted below), can NIST be removed from ASVS? 

![image](https://user-images.githubusercontent.com/136826/126416794-66fe7cc1-aa2c-4ecf-8719-37acc54619d6.png)
