### ISSUE TITLE
Add V5.22 - mass assignment

### ISSUE THREAD

**Issue by kravietz** [OWASP/ASVS#86]
Proposed text:

*Verify that structured data inputs (JSON, XML) consumed by ORM interfaces are mapped to whitelisted fields only and protected from mass assignment attacks.*

Reference: (CWE-915)[https://cwe.mitre.org/data/definitions/915.html]. These vulnerabilities are prevalent in Ruby on Rails, Play Framework and Dropwizard based applications, difficult to avoid with default configuration and not always come with sufficient warnings.

**Comment by kravietz** [comment]
Oh, just noticed this is already covered by 5.17 - but I think my proposed wording is a bit more clear and generic.

**Comment by vanderaj** [comment]
The one time I saw this, it wasn't against an ORM model, so I don't want to constrain it, because it was a problem for these guys using another technology. But I have included the reference, as I think that's super helpful!

Fixed! Thanks
