### ISSUE TITLE
V14.5.1 text improvement and (re)move log-related part to log category requirement

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#862]
Current requirement [14.5.1](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x22-V14-Config.md#v145-validate-http-request-header-requirements)

> V14.5.1 Verify that the application server only accepts the HTTP methods in use by the application/API, including pre-flight OPTIONS, and logs/alerts on any requests that are not valid for the application context.

### "content-type"

Every time I see `application/API` I have question - what kind of Content-Type is that? Maybe we can replace this with (or however it's correct to say it in English):

> V14.5.1 Verify that the application server only accepts the HTTP methods (including pre-flight OPTIONS) in use by the application or by the API.

This fix can be done for ASVS v4.0.2.

### logs

Second part of this requirement:

> and logs/alerts on any requests that are not valid for the application context.

This one is clear logging requirement and should belong separately to V7 category or it can be covered by current 7.1.3 if there will be something like "incorrect or unexpected HTTP request":

> 7.1.3 Verify that the application logs security relevant events including successful and failed authentication events, access control failures, deserialization failures and input validation failures.

**Comment by elarlang** [comment]
Any comments opinions on this?
(ping @jmanico @tghosth )

**Comment by jmanico** [comment]
We have another volunteer building several different CORS requirements that are very nuanced. So at the very least I suggest we drop the CORS requirements from this requirement.

I’d also recommend we remove the logging portion and just build a generic access control requirement that says to log any access control failures.

Then this requirement becomes very simple and atomic to just ensure developers only allow the right verbs for REST.

--
Jim Manico
@Manicode

**Comment by elarlang** [comment]
This requirement is general - accept only HTTP verbs you expect. It does not need to be an API.

**Comment by jmanico** [comment]
Agreed. It’s much more acute of a problem though in the world of REST, but your point is well taken.

--
Jim Manico
@Manicode

**Comment by jmanico** [comment]
I think we are ready for a PR here.

**Comment by elarlang** [comment]
Language checks needed:

Update proposal for 14.5.1 (additional change "pre-flight" > "preflight"):
> Verify that the application server only accepts the HTTP methods (including preflight OPTIONS) in use by the application or by the API.

Update proposal for 7.1.3:
> Verify that the application logs security relevant events including successful and failed authentication events, access control failures, deserialization failures, input validation failures and incorrect HTTP requests (including requests with unexpected HTTP verb).

Probably I will come back to "list of security events" in logging context in future.

**Comment by jmanico** [comment]
My suggestions for 14.51.1

_Verify that the application server only accepts HTTP methods (including OPTIONS during preflight requests) in use by the application or by the API._

Small change for 7.1.3

_Verify that the application logs security relevant events including successful and failed authentication events, access control failures, deserialization failures, input validation failures and incorrect HTTP requests (including requests with an unexpected HTTP verb)._
