### ISSUE TITLE
Better clarify the difference between ASVS and SAMM

### ISSUE THREAD

**Issue by omerlh** [OWASP/ASVS#868]
Context: [Twitter](https://twitter.com/omerlh/status/1320425822310772736?s=20)

It seems there is some overlapping between SAMM and ASVS (V1.1, V14, prefix). I think it could help further readers to add something around the relationship between SAMM and ASVS and how it is best to use them both.

**Comment by tghosth** [comment]
I think this is closed by #1213 and #1210, @omerlh please let me know if you think this is still lacking.
