### ISSUE TITLE
Requirement from v3.0.1 - user should be able to logout from every page

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#870]
In ASVS v3.0.1 there is/was requirement:

> 3.5 Verify that all pages that require authentication have easy and visible access to logout functionality.

I can not find clear requirement from ASVS v4.0.2 / or from latest to cover this requirement. Is there any good reason to remove this requirement (personally, I can not find any) or it's just a mistake and this requirement should be stored (to current V3.3 subcategory)?

**Comment by Racater** [comment]
Here is the history of the requirement:
- [The 29 Oct 2018](https://github.com/OWASP/ASVS/commit/64194cfc4e4b3229acb20e03812f626bc247ed43#diff-3fa18c0b028c040a1969231e957b99e5758b63ad69b3acb4e6a73715c35ccc59), @vanderaj rephrased the requirement to:

> Verify that logout functionality is easily found, and effective if used

- Then [the 15 Nov. 2018](https://github.com/OWASP/ASVS/commit/0f5ac563056132e650dbaa11cdf34d697c848bf1#diff-3fa18c0b028c040a1969231e957b99e5758b63ad69b3acb4e6a73715c35ccc59) @vanderaj removed the requirement.

**Comment by jmanico** [comment]
Logout is less important in modern architecures, perhaps? 

The issue is not having a login link doesn’t add an actual security vulnerability.

These are just my quick thoughts I love to hear what Andrew has to say.

Aloha,
--
Jim Manico
@Manicode

**Comment by elarlang** [comment]
For sure it's not the most critical problem, but say it's not a problem...

If user does not have possibility (or easy to access) to logout, he/she probably (in situation when need to leave fast for example) just closing a browser window/tab.

Which:

  * leaves session open on the server side - increases timewindow to take over session
  * if session hijacked, without logging out it leaves it usable for an attacker
  * leaves possibility if someone access same device/workstation, can continue using active session

To undestand, that logout functionality itself is important, we have other requirements like:

  * V3.3.3 Verify that the application gives the option to terminate all other active sessions after a successful password change (including change via password reset/recovery), and that this is effective across the application, federated login (if present), and any relying parties.
  * V3.3.4 Verify that users are able to view and (having re-entered login credentials) log out of any or all currently active sessions and devices.


To be clear with that: there is no question, should we have logout functionality - we need to have. The question is (reason for this issue), should we have separate requirement, that this logout link/button must be available on every page.

**Comment by jmanico** [comment]
I just do not agree that lack of a logout link is a vulnerability worthy of our standard. Especially when short idle timeout or short expiration tokens are present, in addition to non persiatant cookies, this risk here is very low to users.

•••• Keep in mind it’s not the lack of a logout link that causes session theft but some other vulnerability, and if you really have a session exposure issue then a per page logout link only reduces that risk a small amount ••••

I agree it’s an issue, I just think ASVS is big enough as is and leaving this out is best. 

But certainly if teams disagree they can fork.

- Jim

PS: Good comments from Elar as well on this issue, agree with them all.

**Comment by elarlang** [comment]
> I just do not agree that lack of a logout link is a vulnerability worthy of our standard. Especially when short idle timeout or short expiration tokens are present, in addition to non persiatant cookies, this risk here is very low to users.

I would like to see clear description, what is worth and what is not. If "missing logout link" is not an issue, I would kick out other requirements as well (like 2.1.8, 2.1.12).

"Missing logout link" is not first level vulnerability, but in practice, it makes attack surface smaller in situation, where there is some other problem. I would say, that session idle-timeout (on the server side) is not often implemented correctly and logout from user could help here. Yes, by requirements you can say that problem is on the server side, but at the same time, we should have next layer in place to catch lack of defense from first layer.

Anyway - my question and reason to open this issue was to understand - is requirement from v3.0.1 has been removed on purpose or it has happened accidentally.

**Comment by jmanico** [comment]
I changed my mind and would like to see this requirement back in.

**Comment by elarlang** [comment]
From @jmanico , ping @vanderaj 
> These are just my quick thoughts I love to hear what Andrew has to say.

Proposal copy-paste from v3.0.1-3.5:
3.3.5 Verify that all pages that require authentication have easy and visible access to logout functionality.

**Comment by elarlang** [comment]
Any change we ever will get comment from @vanderaj here or we just move on?

**Comment by jmanico** [comment]
Move on! Andrew is busy as executive director

**Comment by Sjord** [comment]
> Verify that all pages that require authentication have easy and visible access to logout functionality.

Authentication can be done using client certificates, and in that case it's not really possible to logout. Should this be limited to session-based authentication?

I couldn't find an applicable CWE. NIST has things to say about logout, but not in SP800-63b. It may be useful to link other NIST publications, but that's probably out of scope for this issue.

**Comment by jmanico** [comment]
Client side certs as a •single• factor for AuthN is not even AAL2 compliant per my understanding. I advise client side certs in addition to username/password.

**Comment by elarlang** [comment]
Should we go with empty NIST and CWE then?

**Comment by jmanico** [comment]
That seems reasonable for now.
