### ISSUE TITLE
move V7.3.4 to V7.1 subcategory 

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#879]
[7.3.4](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x15-V7-Error-Logging.md#v73-log-protection-requirements)

> V7.3.4 Verify that time sources are synchronized to the correct time and time zone. Strongly consider logging only in UTC if systems are global to assist with post-incident forensic analysis.

Subcategory V7.3 is "Log Protection" is for protecting logs (confidentiality + integrity), current requirement V7.3.4 is more log content requirement and should belong to subcategory V7.1 "Log Content" and it is part of 7.1.4 (_timeline_):

> V7.1.4 Verify that each log event includes necessary information that would allow for a detailed investigation of the timeline when an event happens.

**Comment by jmanico** [comment]
Correct time synchronization is important in areas of an application security beyond just logging. Things like cluster synchronization or time based access control rules still depend on a proper clock.

--
Jim Manico
@Manicode

**Comment by elarlang** [comment]
This _timeline_ connection I made more to point out, that mentioned requirement should belong also there. Proposal is only for moving current requirement V7.3.4 to category V7.1. I don't want to change requirement itself.

**Comment by jmanico** [comment]
👍🏼👍🏼 +1 PR away...

--
Jim Manico
@Manicode
