### ISSUE TITLE
merge V14.3.1 to V7.4.1

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#881]
[14.3.1](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x22-V14-Config.md#v143-unintended-security-disclosure-requirements)

> V14.3.1 Verify that web or application server and framework error messages are configured to deliver user actionable, customized responses to eliminate any unintended security disclosures. 

The requirement is duplicate with V7.4.1:

> V7.4.1 Verify that a generic message is shown when an unexpected or security sensitive error occurs, potentially with a unique ID which support personnel can use to investigate. 

I think wording should me merged that points and keys from both are covered and only V7.4.1 should stay. Category should be "Error handling", because even "to show errors or not" is question of configuration, then proper error handling must be also done with program code.

**Comment by jmanico** [comment]
+1 Good call Elar, very astute observation

--
Jim Manico
@Manicode

**Comment by elarlang** [comment]
Proposal:
* keep 7.4.1 as it is and remove 14.3.1 as it's duplicate.

**Comment by jmanico** [comment]
Good proposal. Would you care to do a PR for this? Let's do it.
