### ISSUE TITLE
Discussion/proposal: new requirement for "disable development tools in framework"

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#882]
I think we have need for new requirement.

Problem - some widespread frameworks (like Drupal and WordPress) have functionality to install/update/delete modules. It's ok for development environment it but should be disabled for production environment.

If to take requirement V14.3.2 as an example:

> V14.3.2 Verify that web or application server and application framework debug modes are disabled in production to eliminate debug features, developer consoles, and unintended security disclosures. 

Rough proposal idea is (please improve wording):

V14.1.X Verify that application framework development modes and functionalities are disabled to eliminate possibility to add, change or remove functionality.

Probably should belong to "V14.1 Build" category

**Comment by jmanico** [comment]
I’m not a fan of framework specific requirements I personally do not think this is a good idea for a general web security standard. But if we can build a few general administrative requirements I’d be more OK with this. 

This is a more generic problem for any framework on the web, maybe a little wordsmithing will help.

--
Jim Manico
@Manicode

**Comment by elarlang** [comment]
Framework names I mentioned only as an example - and from where I got the need to propose this.

I just shared direction/idea, with wordsmithing I need help here.

**Comment by jmanico** [comment]
> V14.3.X Verify that application framework development modes and functionalities are disabled to eliminate possibility to add, change or remove functionality.

I don’t think we want this kind of functionality disabled. We just want to make sure that typical users don’t have access to this but we might want to keep this enabled for administrators. So this is another access control requirement around framework adminstration I think…

--
Jim Manico
@Manicode

**Comment by elarlang** [comment]
... and then one tiny cute XSS against admin users escalates well to application take-over?

There is no need (or I just can not imagine where it is) for this kind of functionality like install/remove/change new modules **in production environment**. You should do it all in dev environment and move to production environment tested code.

It can be accessible via CLI for example.

**Comment by jmanico** [comment]
There are many many reasons why you want this enabled like if you a are PAAS provider or similar. Sure it’s a lot better to isolate or disable administrative functionality but for the way that some people run the software that’s not at all reasonable or practical. That’s why access control exists…

--
Jim Manico
@Manicode

**Comment by elarlang** [comment]
If you have cases, when someone need that their program have permission to overwrite itself, then we (well, you ;) ) need to wordsmith this into the requirement. If we only take mentioned Drupals and WordPress sites and amount of them in the Internet, then we just can not ignore this widespread misconfiguration just because "for someone it may be required".

**Comment by jmanico** [comment]
I agree this issue should be addressed in ASVS somehow. 

And by the way I need to administer my app if I’m doing wordpress or Drupal so you can turn those features off but if someone pops your admin account they can turn them back on.

So are you suggesting removing all administrative accounts from Drupal and wordpress? That’s not practical.

I’m a big fan of using strong authentication an origin isolation for the administrative part of my web app, maybe we should go in that direction as opposed to just saying no.

In general I want to help developers do risky thing securely as opposed to telling them no.

--
Jim Manico
@Manicode

**Comment by elarlang** [comment]
Removing administrator accounts entirely is not practical or realistic, and necessary.

My recommendation should be, that you can not modify program code from web interface.

You can have admin account access only via VPN for limited IP + strong authentication etc, but if there is just one XSS, you can automate authenticated administrator browser to do whatever there. With known software you can prepare them well without accessing target environment itself.

Actually, it may also stand for: "verify, that application can not / does not have permissions to modify own program code" or something like that. But this is also risky, because "what is program code?" (and what is "just a configuration") it's not clear.

**Comment by jmanico** [comment]
But with that described XSS if Itake over an admin account I can just do a couple forged requests to re-enable those features…

...my take on this is that access control origin isolation and other administration controls os what’s necessary and disabling the feature you’re describing is not gonna help if I compromise and admin account with XSS or similar.

--
Jim Manico
@Manicode

**Comment by jmanico** [comment]
> You can have admin account access only via VPN for limited IP + strong authentication etc, but if there is just one XSS, you can automate authenticated administrator browser to do whatever there

I agree and this includes re-enabling the ability to load dynamic code into these frameworks. The defense you suggest is just not gonna work unless you remove or disable all administrator accounts which like you said it’s not gonna help.

The real solution here is to do good access control, enable content security policy and isolate administrative functions and UI into their own origin.

Removing the ability is to load dynamic code from a web interface something that can be easily re-enabled by the admin and it’s not gonna help (at all) based on the risk of XSS you are describing.

--
Jim Manico
@Manicode

**Comment by elarlang** [comment]
If you don't have permissions on file-system level, it does not matter what permissions or functionality you have in user-interface. My point is - you should NOT be able to modify program code from user-interface.

**Comment by jmanico** [comment]
I strongly disagree - as a spring administrator for example I wanna dynamically load in library’s and other code all the time. And these features are highly protected as previously described. This is an extremely basic feature in cloud administration applications as well. I respectfully but strongly disagree with this requirement you’re describing.

I’d rather move in the direction of how to protect these features properly.

--
Jim Manico
@Manicode

**Comment by jmanico** [comment]
... And when we describe how to protect these admin features I’m not opposed to disabling them being >one< of many defense strategies, I’m just opposed to disabling specifically being required.

--
Jim Manico
@Manicode

**Comment by elarlang** [comment]
Till you have agenda to prove why you don't need this requirement in your chosen technologies I don't see point to continue to search solution, how to cover those technologies with requirement, where it's actually needed :)

So I keep this issue opened some time and close it later, when no-one else have not find it needed as well.

**Comment by jmanico** [comment]
Great! As long as this narrow requirement does not go live, I’m happy.

--
Jim Manico
@Manicode

**Comment by jmanico** [comment]
I politely disagree with this requirement and am closing it. If you want to bring this up again then please re-open.

**Comment by elarlang** [comment]
I would like to get someone else opinion in as well, so kind hilight to @danielcuthbert @kingthorin @ThunderSon

**Comment by ThunderSon** [comment]
I think it's going more towards having a vetted process where a developer or admin can't just modify an application through button clicks on production, and will require further approvals (2FA counts) to allow the change to go through, or to have a pre-approval for a certain change.
I see this in an other use case but on a different place: Don't have direct access to a production server to change code, where it should follow a build and deployment process that passes all checks (unit tests, regression, security, etc.) (change management process to say).

What I see from Elar is that application modification shouldn't be that easily accessible and to be accomplished through a simple XSS, and require multiple vectors to be able to hit such an attack.
If I misunderstood something, happy to give it a more focused look with some more guidance.

**Comment by elarlang** [comment]
> Don't have direct access to a production server to change code, where it should follow a build and deployment process that passes all checks (unit tests, regression, security, etc.) (change management process to say).

This is the thing which I want to address.

**Comment by jmanico** [comment]
I still am adamant that some PAAS and similar services require this like Salesforce,  HubSpot, ZoHo and many others. 

I still think this is an access control issue. At one point, an admin will NEED to do this. So I still say no to this requirement unless it's changed to include the process you are describing.

**Comment by kingthorin** [comment]
I don't see how dynamic loading (or unloading) of a module is any different that a solution configuration option that an admin would have access to or some sort of feature flag for something that's just ramping up as a new feature by percentage of users, etc.

This all seems like authorization and process stuff. While I don't think ASVS calls it out or names it exactly as you're mentioning, I do feel it's covered.

**Comment by elarlang** [comment]
Thank you all for feedback and discussion, I'll keep it closed and try to cover it for myself with some other requirements.

**Comment by ThunderSon** [comment]
This should have been covered in [Operational Access Controls](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x12-V4-Access-Control.md#v42-operation-level-access-control).
It is a part of the culture, having a **change process** implementation, which is not covered by ASVS. Not sure if this should be covered or not, but I did see cultural aspects here and there, so I do believe this is worth having a point. Might be a bit deviating from this issue, but they're to a sort related, with different implementations.

Let's say this admin you're talking about changed a setting on the SAAS application, where is the approval? Where is the log entry? etc.
Yes, people need to use the SAAS systems, of course. Are we ensuring that a process is in place to ensure no admin abuse happens? What if a rogue admin did something? Is it okay just because it's their task?
No, it is not.

**Comment by jmanico** [comment]
I am open to additional requirements that are more flexible. Some application truly require this functionality and I just cant endorse a flat out ban, but I'm totally open to more nuanced requirements about change control process.
