### ISSUE TITLE
Secure the postMessage interface

### ISSUE THREAD

**Issue by Sjord** [OWASP/ASVS#885]
Websites can communicate to other websites loaded in other windows or iframes using the [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) interface. This presents an attack surface, which can lead to XSS. I think the ASVS should have one or more requirements that verify whether the postMessage interface is secure. A good start would be the [recommendations on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#Security_concerns).

**Comment by jmanico** [comment]
+1

Esentially users of web messaging need to do at least 2 things.

1) Verify the origin of incoming messages
2) Treat incoming messages as untrusted data (a) verify their format (b) render those messages safely (like avoid innerHTML unless you DomPurify, use innerText, and all the other XSS defense advice) 

--
Jim Manico
@Manicode

**Comment by jmanico** [comment]
hey @Sjord can we get a PR on this one from you?

**Comment by Sjord** [comment]
I propose this:

> Verify that messages received by the `postMessage` interface are discarded if the origin of the message is not trusted, or if the syntax of the message is invalid.

DOM XSS through innerHTML is not particularly specific to messages, perhaps this already goes under [5.3.6](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x13-V5-Validation-Sanitization-Encoding.md#user-content-v53-output-encoding-and-injection-prevention-requirements:~:text=5.3.6). I think if the origin of the message is verified, it can be somewhat considered trusted data.

**Comment by jmanico** [comment]
This is perfect. Let's PR this! please add [ADDED] to the text of the new requirement please! :)

https://github.com/OWASP/ASVS/blob/master/CONTRIBUTING.md

**Comment by jmanico** [comment]
And if the label is confusing just ignore it and I'll take a standard PR and fix the label myself, whatever is easier for you.

**Comment by elarlang** [comment]
Formating note: please don't use markdown syntax in requirement text (`postMessage`)

I'm not too familiar with postMessage, can you please explain me the meaning of:
* the origin of the message is not trusted
* if the syntax of the message is invalid

**Comment by jmanico** [comment]
This is a well establish standard from the HTML5 era, it's old and well established.
See:  https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
And: https://caniuse.com/?search=postMessage

Can you give this a quick read first and ask questions if it's confusing?

**Comment by elarlang** [comment]
Yes, I can play with postMessage myself and I'll do it one day, but there are many reasons for my questions, like:
* is here maybe exists 2 different requirements in this proposal
* are they duplicates with requirements which already exists
* where to place them in the structure

**Comment by jmanico** [comment]
I think we can skip the handling of untrusted data in a UI because it's well handled elsewhere. So we  have only one requirement to process.

This can go with other CORS requirements since pastMessage is driven and secured by origin policy.

We're ready for a PR on this one.

**Comment by jmanico** [comment]
And @Sjord I can just commit the change to master on my own, but I can also wait for a PR so you are given proper credit, as you like. :)

**Comment by Sjord** [comment]
I am not clear on where this should go. Other CORS requirements are in V14, e.g. 14.5.3:

> Verify that the Origin header is validated against defined list of allowed domains to meet the Cross-Origin Resource Sharing (CORS) policy

This is pretty similar to checking the origin of messages. However, this section is named *Validate HTTP Request Header Requirements*, and that doesn't make sense for messages. Perhaps it's better to put it as 4.2.3, behind CSRF? Or somewhere in V5?

**Comment by elarlang** [comment]
I'm don't know where it should go, but 4.2.3 is not the way to go - it's not authorization requirement. CSRF requirement is in wrong category as well and it's addressed in other issue (#795 - no solution there yet as well).

**Comment by jmanico** [comment]
I agree with @elarlang I think we need a CORS section. And I want to add this in now, we do not want requirements that are good to stay in comment land, we just need to tag this as "added" and we can figure out what goes into each version later. 

So let's please add a new section 14.6 called "Origin Policy and Cross Origin Resource Sharing"

**Comment by jmanico** [comment]
Yea I do not like this going into 14.x, this is not a configuration issue. And it's not good for 4x.

How about 5.1 ?

**Comment by elarlang** [comment]
If you want to get requirement in fast, use 4.2.3 as proposed and lets open new issue for "where we should create this category". It's separate discussion from this issue.

**Comment by jmanico** [comment]
@Sjord if you give me a [ADDED] PR for 4.2.3 I'll accept it for now and we can revisit moving all CORS to a new section in a new comment per @elarlang - good call.
