### ISSUE TITLE
9.9 superfluous ")" and missing word

### ISSUE THREAD

**Issue by relaxnow** [OWASP/ASVS#89]
> Verify that data stored in client side storage - such as HTML5 local storage, session storage, IndexedDB, regular cookies or Flash cookies - does not contain sensitive or PII).

Should probably be:

>  Verify that data stored in client side storage (such as HTML5 local storage, session storage, IndexedDB, regular cookies or Flash cookies) does not contain sensitive data or PII.

**Comment by vanderaj** [comment]
Thank you, fixed.
