### ISSUE TITLE
Clarification needed 5.1.5 applies for usual links as well?

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#890]
[5.1.5](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x13-V5-Validation-Sanitization-Encoding.md#v51-input-validation-requirements)

> V5.1.5 Verify that URL redirects and forwards only allow destinations which appear on an allow list, or show a warning when redirecting to potentially untrusted content.

Does this requirement apply also for "usual links"? Like:
```
<a href="https://this-is-some-other-domain-com">visible text</a>
```

If it does, then maybe need to mention links in requirement as well. Or "usual links" may be dependent on ASVS level - this extra question for user "do you want to follow link to external site" on some forum seems overhead, but in some critical site it feels required. Any opinions?

**Comment by jmanico** [comment]
Opinions? Why yes!

Redirect problems are more prominent with Outh2 requiring redirects in several workflows...

...I’d like to suggest we keep open redirect/forward separate.  Validating dynamic url patterns, something needed in Outh2 redirects, can get quite tricky. I personally don’t think of redirect as a simple “allow list” issue only, sometimes dev’s need to implement a more complicated and dynamic URL validation plan.

The other user driven link issue I suggest we move to a new requirement so we do not dilute the redirect requirement.

--
Jim Manico
@Manicode

**Comment by jmanico** [comment]
Personally I like the requirement as is, I don't think 5.1.5 needs a change and I'm inclined to close this unless you have a specific suggestion, @elarlang

**Comment by elarlang** [comment]
We don't need changes to 5.1.5, the question is, do we need to have separate requirement for "do you want to follow link to external site".

If yes, we need wording and category, if no, then we can close this issue.

**Comment by jmanico** [comment]
I suggesting no and am closing this, if you disagree please reopen
