### ISSUE TITLE
Discussion/Proposal: new requirement - no test-code in production environment.

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#894]
Spin-off from #880

https://github.com/OWASP/ASVS/issues/880#issuecomment-754128067

New requirement like "Verify that production environment does not have test code.".
Language and grammar check and wordsmith needed.

**Comment by jmanico** [comment]
I think "Verify that production environment does not include test code" is ready for a PR.

**Comment by elarlang** [comment]
Category V14.1 "Configuration" > "Build"?

**Comment by jmanico** [comment]
I agree, good call! Let's do it!

**Comment by jmanico** [comment]
I'll keep an eye on this but would you care to drop the initial PR for this @elarlang ?

**Comment by elarlang** [comment]
What CWE I could use?

**Comment by elarlang** [comment]
Jim probably answered to another issue: https://github.com/OWASP/ASVS/issues/696#issuecomment-799026230

**Comment by jmanico** [comment]
Closing this out since it's resolved, please re-open if I did this in haste.

**Comment by elarlang** [comment]
How it's resolved?

**Comment by jmanico** [comment]
The PR I just merged?

**Comment by jmanico** [comment]
opening this back up for @elarlang

**Comment by jmanico** [comment]
@elarlang I deleted on of your comments on accident but this is indeed back open, my bad.

**Comment by jmanico** [comment]
> What CWE I could use?

I say 489

https://cwe.mitre.org/data/definitions/489.html (debug code in production)

or 

https://cwe.mitre.org/data/definitions/215.html (sensitive data in debug code)

**Comment by elarlang** [comment]
Proposal:
* [Label](https://github.com/OWASP/ASVS/blob/master/CONTRIBUTING.md): `[ADDED]` 
* Category: [V14.1 Configuration > Build](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x22-V14-Config.md#v141-build)
* Id: 14.1.7
* Requirement: Verify that production environment does not include test code.
* Levels: 2, 3
* [CWE-489](https://cwe.mitre.org/data/definitions/489.html)

**Comment by jmanico** [comment]
I like it.
