### ISSUE TITLE
[Proposal] Reference to OWASP-ASVS-4.0-testing-guide

### ISSUE THREAD

**Issue by BlazingWind** [OWASP/ASVS#898]
It was suggeseted in ASVS project's Slack that the [unoffical ASVS testing guide](https://github.com/BlazingWind/OWASP-ASVS-4.0-testing-guide) could be somehow referenced in ASVS. 

Adding this issue for consideration.

**Comment by danielcuthbert** [comment]
This looks great, we have added it in as a reference. Please watch the main repo and update yours accordingly as we release new versions.  https://github.com/OWASP/ASVS/commit/303bf3c6d842d630f501f82784d281f5d9145afa
