### ISSUE TITLE
11.4

### ISSUE THREAD

**Issue by relaxnow** [OWASP/ASVS#91]
> V11.4
Verify that the Content Security Policy V2 (CSP) is in use for sites where content should not be viewed in a 3rd-party X-Frame.

Should probably be

> V11.4
Verify that the X-Frame-Options (XFO) is in use for sites where content should not be viewed in a 3rd-party frame.

**Comment by vanderaj** [comment]
We have a few different X_FRAME_OPTIONS. We are trying to increase the uptake of CSP as it has a lot of other benefits other than just providing course grained access control of frame src and script src.

**Comment by vanderaj** [comment]
Let me ponder this one a while longer.

**Comment by vanderaj** [comment]
Fixed. Also updated v11.7 to be more clear about what we really want to achieve with a CSPv2 policy.
