### ISSUE TITLE
obvious but missing requirement on V1 section on software free from known vulnerabilities

### ISSUE THREAD

**Issue by boos** [OWASP/ASVS#92]
A discussed here: http://lists.owasp.org/pipermail/owasp-application-security-verification-standard/2015-November/000920.html

On V1 section we have requirements related to the needs to know internal and external components on which the application relies on (requirement v1.1 and v1.2.)

Although it might sounds obvious I believe we need a requirement that state something like: 
* Verify that all application components and all component, such as libraries, modules and external system that are not part of the application but that the application relies on are free of any known vulnerabilities. 

Or a better worded requirement that simply state that even if you have the full list of all used software that is not enough as as their version should be free of any known vulnerabilities. 

E.g. I have the list of all software components and as now I'm fine BUT they suffer for well known vulnerabilities as they are 10 years old.

**Comment by vanderaj** [comment]
![image](https://cloud.githubusercontent.com/assets/5029993/16450198/2839ec62-3dfc-11e6-8629-00143f787e33.png)

Fixed
