### ISSUE TITLE
Discussion: rename V14.1 subcategory "Build" > "Build and Deploy"

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#922]
Topic from issue https://github.com/OWASP/ASVS/issues/880#issuecomment-797121410

If agreed with change, then category rename may be breaking change, milestone 5.0

**Comment by jmanico** [comment]
Thank you for splitting this out. My wish is to push this to 4.1. What do you think @tghosth @vanderaj @danielcuthbert ?

**Comment by tghosth** [comment]
@jmanico given that everything we are doing on the master branch will either go into a theoretical 4.1 or into 5.0 then I think we are ready for this now, no?

**Comment by elarlang** [comment]
I'll cover it with #802

**Comment by jmanico** [comment]
Yes,  I agree. Let's do this!

**Comment by elarlang** [comment]
Done via https://github.com/OWASP/ASVS/commit/8ff57cf8fa061f7ebb203b58aaece88bf2aa1417
