### ISSUE TITLE
requirement v2.12 revise proposal: Verify that all authentication decisions are logged

### ISSUE THREAD

**Issue by boos** [OWASP/ASVS#93]
I suggest to revise requirement v2.12 from:
* Verify that all **suspicious** authentication decisions are logged. This should include requests with relevant metadata needed for security investigations.

to:

* Verify that all ~~suspicious~~ authentication decisions are logged. This should include requests with relevant metadata needed for security investigations.

In my opinion:
* the definition of suspicious is subjective and lack a common definition
* all authentication decisions must be logged

**Comment by rietta** [comment]
Logged and retained for an appropriate data retention period. Whenever space is an issue, the logs are the first to be deleted by system administrators, sometimes really quickly - as in after 10 or 15 days.

**Comment by boos** [comment]
Although I agree with your general security suggestion I don't believe that ASVS should cover log retention requirements. It's more a operational requirement than an application requirement. 

Furthermore the word **appropriate ** is subjective.

**Comment by vanderaj** [comment]
Fixed. 

![image](https://cloud.githubusercontent.com/assets/5029993/16450092/603c216c-3dfb-11e6-8213-3757b110414d.png)
