### ISSUE TITLE
13.2 Verify that a code review...

### ISSUE THREAD

**Issue by sjswoboda** [OWASP/ASVS#94]
Requirement 13.2: Verify that a code review looks for malicious code, back doors, Easter eggs, and logic flaws.

Because it says "a code review" does that mean that IF a code review is done, the requirement applies. If a code review is not done, the requirement is not applicable. Should this be updated to indicate that code reviews are done, and that "code reviews look for.."

Thanks

**Comment by vanderaj** [comment]
Fixed. I've also included some guidance to help folks do the right thing.

![image](https://cloud.githubusercontent.com/assets/5029993/16449722/5689e2d2-3df9-11e6-85fa-d8c92b9d9bfc.png)
