### ISSUE TITLE
Discussion/Proposal: split 2.1.10 to 2 separate requirements

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#940]
"Spin-Off" from https://github.com/OWASP/ASVS/issues/683#issuecomment-539387178 - "Recommendation 1"

Current:
  * Id: [2.1.10](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#v21-password-security-requirements)
  * Requirement: Verify that there are no periodic credential rotation or password history requirements.
  * Levels: 1, 2, 3
  * [CWE-263](https://cwe.mitre.org/data/definitions/263.html) Password Aging with Long Expiration

Covered in NIST [5.1.1.2](https://pages.nist.gov/800-63-3/sp800-63b.html#-5112-memorized-secret-verifiers):
  * _Verifiers SHOULD NOT require memorized secrets to be changed arbitrarily (e.g., periodically)._

Problems:

  * Requirement contains 2 different and separate requirements
    * "no periodic credential rotation" - password functionality requirement, may not be testable (blackbox)
    * "no password history requirement" - password content requirement, easy to test
  * CWE-263 is outdated / opposite of the requirement description
  * NIST says "SHOULD NOT" vs ASVS says "MUST NOT"

I prefer to keep CWE empty, as CWE descriptions are outdated and not lined with NIST:

  * [CWE-262](https://cwe.mitre.org/data/definitions/262.html) Not Using Password Aging
    * _If no mechanism is in place for managing password aging, users will have no incentive to update passwords in a timely manner._
  * [CWE-263](https://cwe.mitre.org/data/definitions/263.html) Password Aging with Long Expiration
    * _Allowing password aging to occur unchecked can result in the possibility of diminished password integrity._

Problem is also pointed out in:

  * https://github.com/OWASP/ASVS/issues/683#issuecomment-724307088 - NIST does not (clearly) disallow to use password history
    * _Accordingly, 800-63B doesn’t contain any requirements to maintain a history of past passwords used by subscribers. However, there is no prohibition on doing so_
  * https://github.com/OWASP/ASVS/issues/840 (different tactics and needs for testing, potentially different levels)
  * https://github.com/OWASP/ASVS/issues/871 (CWE-263 is outdated)

Current vision for proposal:

  * Split to 2 separate requirements
  * Keep CWE empty for both
  * ~~Level 1 for "no password history" requirement~~
  * Level 2 for "no password history" requirement
  * Level 2 for "no periodical change" requirement (as it's not testable in blackbox testing)

**Comment by Sjord** [comment]
> Level 1 for "no password history" requirement

I interpret password history as: when changing your password, your new password may not be the same as one of your last ten passwords.

I think the security impact of password history is pretty limited. There's some additional risk because the site stores old passwords, but if done correctly these are hashed and no longer valid. Should we also move this to L2, because the security impact is fairly small?

**Comment by jmanico** [comment]
I agree with you @Sjord I think we want to drop password history requirements but I asked Jim Fenton, the lead for SP800-63 to be sure. Keep an eye on this today...

https://twitter.com/manicode/status/1374331675715502082?s=21

**Comment by jmanico** [comment]
Jim Fenton (of SP800-63 fame) says not to do any kind of forced password expiration unless there is a breach, so I endorse fully dropping the password history requirement.

**Comment by elarlang** [comment]
Where is the logic here? If we drop this requirement, we going to allow password history.

**Comment by elarlang** [comment]
Where is the logic here? If we drop this requirement, we going to allow password history.

**Comment by jmanico** [comment]
So what? What’s the weakness? Unless there is a breach there is none.

**Comment by elarlang** [comment]
I don't mind to drop it, it's anyway "should".

So, current vision seems to be:
* Change 2.1.10 (instead of initial split proposal)
* Requirement: Verify that there are no periodic credential rotation requirement.
  * (changed, dropped password history part)
* Levels: 2, 3
  * (changed, as it's not testable with blackbox)
* CWE - empty / not set
  * (changed, as CWE description is deprecated / not lined with ASVS and NIST)

**Comment by elarlang** [comment]
> so I endorse fully dropping the password history requirement.

... or you meant to drop 2.1.10 completely, not only password history part?

**Comment by jmanico** [comment]
My mistake, the requirement looks good as is. We should not be forcing rotating passwords. I think 2.1.10 does not need to be split.

**Comment by jmanico** [comment]
Ok it makes sense to split this into two requirements.

**Comment by elarlang** [comment]
So then - split, drop, change levels? :)

**Comment by elarlang** [comment]
Valid proposal is the original one then (updated with level change): https://github.com/OWASP/ASVS/issues/940#issue-838494380

**Comment by jmanico** [comment]
I am sorry for the run around. I get it now and am ready for PR's when you are.

**Comment by elarlang** [comment]
Proposals as text:
* Verify that the application does not require periodic credential rotation.
* Verify that the application does not keep a password history.
