### ISSUE TITLE
V1.5.3 vs V5.1.3

### ISSUE THREAD

**Issue by roelstorms** [OWASP/ASVS#943]
[V1.5.3](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x10-V1-Architecture.md) describes the need for input validation enforced on a trusted service layer. It is a level 2 requirement.

[V5.1.3](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x13-V5-Validation-Sanitization-Encoding.md#v51-input-validation-requirements) requires all input is validated using positive validation. Other 5.1.X requirements also talk about input validation. All of them are ASVS level 1.

This implies that input validation is considered a level 1 requirement and input validation **on a trusted service layer** is considered a level 2 requirement. I believe that input validation NOT on a trusted service layer adds almost no security. Hense, if 5.1.x requirements are level 1 (I believe they should be), then V1.5.3 should also be level 1.

ASVS aims to make level 1 requirements blackbox-testable. I believe that a black-box test can determine if input validation occurs on a trusted service layer (aka NOT on the client-side). This does seem to invalidate the existing logic that architectural requirements are never ASVS level 1.

**Comment by elarlang** [comment]
My proposal is to move current V1.5.3 to category V5.1 and change level to 1.

(the same way like V4.1.1 belongs to "pentestable" category like V4.1 not to architecture category V1.4)

**Comment by jmanico** [comment]
This is a great idea and I appreciate the precision you are using in your review of these requirements. +1

**Comment by roelstorms** [comment]
Do I attempt a pull request?

**Comment by elarlang** [comment]
If you do, please follow https://github.com/OWASP/ASVS/blob/master/CONTRIBUTING.md

Otherwise I can do it myself.

**Comment by roelstorms** [comment]
Am I expected to close the issue now or what is the process here?

**Comment by jmanico** [comment]
It's now closed! Thanks for you PR!
