### ISSUE TITLE
Missing requirement trusted certificates V9.1

### ISSUE THREAD

**Issue by roelstorms** [OWASP/ASVS#947]
[9.2.1](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x17-V9-Communications.md#v92-server-communications-security-requirements) states the following

> Verify that connections to and from the server use trusted TLS certificates. Where internally generated or self-signed certificates are used, the server must be configured to only trust specific internal CAs and specific self-signed certificates. All others should be rejected.

For [9.1](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x17-V9-Communications.md#v91-client-communications-security-requirements) there is no requirement that requires to use trusted certificates. Propose to add 9.1.5: Verify that connections to and from the server use trusted TLS certificates. Where internally generated or self-signed certificates are used, **the client** must be configured to only trust specific internal CAs and specific self-signed certificates. All others should be rejected.

This section in bold implies you have control over the client and would typically apply for applications used by your employees only. In such a case you would have an SSL certificate which is signed by your companies internal PKI.

**Comment by jmanico** [comment]
Astute observation, I like it @roelstorms

**Comment by cmlh** [comment]
Can we extend the verification to Certificate Authorities similar to the process undertaken by https://www.dta.gov.au/our-projects/digital-identity/gatekeeper-public-key-infrastructure-framework and https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices#14-obtain-certificates-from-a-reliable-ca too?

**Comment by tghosth** [comment]
@roelstorms do you think the changes in #1221 make this clearer and cover what you were trying to achieve?

**Comment by tghosth** [comment]
@roelstorms any further feedback? I will probably close during mid-May if there is no further feedback.

**Comment by roelstorms** [comment]
No further remarks. Looks good.

**Comment by elarlang** [comment]
@tghosth - is it actually done and can be closed?

**Comment by tghosth** [comment]
@roelstorms said it did what he wanted so I am going to close, thanks
