### ISSUE TITLE
Typo V10.14 Online Certificate Status Protocol

### ISSUE THREAD

**Issue by shenril** [OWASP/ASVS#95]
I would like to forward a typo notified by Daniela Coman concerning on the ASVS 3.0 PDF version in English.

Page 44: V10.14 Verify that proper certification revocation, such as Online Certificate Status Protocol (OSCP) Stapling, is enabled and configured

If the acronym is correct, I believe it should be OCSP

**Comment by vanderaj** [comment]
Fixed.
