### ISSUE TITLE
rename V7: Cryptography at rest title to Cryptography and Randomness

### ISSUE THREAD

**Issue by boos** [OWASP/ASVS#96]
See http://lists.owasp.org/pipermail/owasp-application-security-verification-standard/2016-January/000936.html from Jeff Sergeant for relevant info.

**Comment by rietta** [comment]
I am not sure that I agree with this change without additional restructuring.  Encryption at rest uses many of the same algorithms and underlaying OS components as encryption in transit, but has a distinct attack surface area that is sufficiently different from TLS to deserve it's own section.

For example, most of the time TLS is a matter of use the latest SSL library from your OS or web server and use the strongest setting available as documented by https://www.ssllabs.com. 

But the attack surface area for short lived TLS keys in a FPS environment are very different then the long lived keys needed for protecting data at rest. Some areas that are vastly different include:

- How private keys are stored; are they for the whole server or per user?
- Is key escrow required by law or policy?
  - Password resets?
  - Two man rule for offline access?

Especially when we get into L3 systems, lumping it all into "use good crypto" is going to miss the point and for L2 and L1 systems, it's too easy to think that having TLS means that the app is encrypted!

Debate on!

**Comment by vanderaj** [comment]
Sorry, but no. 3.0.1 is a minor change, and I think unless we eventually create a section just for randomness, we'll let this go for now.
