### ISSUE TITLE
14.4.5 seems to have a weak length of time not appropriate for preloading

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#963]
> **14.4.5** | Verify that a Strict-Transport-Security header is included on all responses and for all subdomains, such as Strict-Transport-Security: max-age=15724800; includeSubdomains. | ✓ | ✓ | ✓ | 523 |

This seems pretty weak, lets bump this to a full year so preloading is possible

**Comment by elarlang** [comment]
From requirement I don't read that there should be max-age at least one year, I read it as syntax example.

If you want to have preload, then you may consider https://hstspreload.org/

**Comment by jmanico** [comment]
Yes I want to increase that syntax example since folks copy it and I opened a PR.

**Comment by tghosth** [comment]
Added the modified tag :)

Do you want to mention preload somewhere?

**Comment by elarlang** [comment]
[CWE-523](https://cwe.mitre.org/data/definitions/523.html) does not seem perfect match. If you make those changes already :)

**Comment by jmanico** [comment]
I moved this to https://github.com/OWASP/ASVS/issues/966 and am closing this up

**Comment by jmanico** [comment]
And good call on this one @tghosth thank you!
