### ISSUE TITLE
Adding a control to scrub exif tags (e.g GPS data) from media that is uploaded to a server

### ISSUE THREAD

**Issue by ismisepaul** [OWASP/ASVS#965]
This could be too specific but I think it's worth highlighting. 

Exif data like GPS data, ID of devices from media (photos, videos etc.) that is uploaded to a server should be scrubbed by the server - many sites do this, such as social networks, as standard but there are many examples where this has not been done and leads to the location of user's sensitive data being exposed.

I think this would be best suited for [8.3](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x16-V8-Data-Protection.md#v83-sensitive-private-data) as it deals with confidentiality - although it only mentions the use of encryption not the removal of metadata to protect the confidentiality of users.

**Comment by elarlang** [comment]
This is something from my todo list :)

Actually, photos are not the most problematic type of files here, classical office files contain way too much information which is not intended to be shared.

At the same time, some sites have intention to share metadata from files (like photo sharing sites, where exif information is ment to be shared), so requirement need to take this in account.

Agree with category proposal 8.3.

Alternatives:
  * [V14.3](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x22-V14-Config.md#v143-unintended-security-disclosure-requirements) Unintended Security Disclosure Requirements
  * V12.* Somewhere in fileupload/servince related categories - but as metadata information should be stripped out also from files which are generated by the application, then it's not maybe the best category

**Comment by elarlang** [comment]
One more point to cover/discuss - if application is going to strip all the meta-information from uploaded file, then for integrity there must be original file stored as well.

**Comment by jmanico** [comment]
> One more point to cover/discuss - if application is going to strip all the meta-information from uploaded file, then for integrity there must be original file stored as well.

For the sake of GDPR and other privacy requirements, I suggest in most cases **not** storing the original file if you plan to strip metadata. If you are going to stop a file with personal data you need to document why you are doing this and must have a good reason. Integrity alone is not one of them, in my opinion.

**Comment by elarlang** [comment]
For security investigations for example. Like you should not delete file when virus is detected from uploaded file, you should store it for investigations.

One option is to ask from user.

**Comment by ismisepaul** [comment]
You should also consider that the metadata is untrusted as anyone could forge it before upload. So maybe its not reliable for investigations?

**Comment by jmanico** [comment]
> For security investigations for example. Like you should not delete file when virus is detected from uploaded file, you should store it for investigations.
> 
> One option is to ask from user.

What you are suggesting is often a violation of GDPR and other privacy regulations. You may only store and process data per use consent.

**Comment by elarlang** [comment]
> You should also consider that the metadata is untrusted as anyone could forge it before upload. So maybe its not reliable for investigations?

metadata is like any other user-input, untrusted.

If you don't strip metadata, you'll store it anyway - and share with others as well. Anyway, you can skip this "storing original" and move on, but it is anyway something to think about.

**Comment by jsulinski** [comment]
I was just looking for this control in ASVS. Seems like a solid addition.

**Comment by jmanico** [comment]
Hey @ismisepaul would you care to submit a PR on this one?

**Comment by elarlang** [comment]
There is no clear proposal yet, let's start from this one before PR.

**Comment by jmanico** [comment]
Hey @ismisepaul would you care to kindly submit a proposed requirement for this one? :)

**Comment by ismisepaul** [comment]
@elarlang @jmanico The proposal for this is to have it within V8.3 Sensitive Private Data with the text

Verify that sensitive personal information stored within a user-submitted media file (photo, audio, video) or document file (.doc, .pdf etc.) in the form of metadata (GPS, IP address, names, device information etc.) is not automatically retained within the file without the consent of the user where the default is to scrub the metadata or have the user consent to keep the metadata before storage of the file.

**Comment by jsulinski** [comment]
Here are a pair of alternative wordings based on @ismisepaul's description:

Verify that sensitive information is removed from user-submitted file metadata unless storage is consented to by the user. 

or 

Verify that sensitive information is removed from the metadata of user-submitted files unless storage is consented to by the user.

**Comment by elarlang** [comment]
Long version by @ismisepaul describes well (with examples) why this requirement is needed, but as requirement I like more shorter version like proposed by @jsulinski .

> Verify that sensitive ~~personal~~ information stored within a ~~user-submitted media~~ file ~~(photo, audio, video) or document file (.doc, .pdf etc.)~~ in the form of metadata ~~(GPS, IP address, names, device information etc.)~~ is not automatically retained within the file without the consent of the user where the default is to scrub the metadata or have the user consent to keep the metadata before storage of the file.

Ideas:
* no need to limit only to "personal information"
* no need to limit only to media and document files
* (discussion) no need to limit user-submitted files? Files generated by the application may leak something as well, 

Goals for requirement
* by default sensitive meta-data should be removed
* IF not decided otherwise by user

Any proposals for CWE and ASVS Levels as well?

**Comment by jsulinski** [comment]
> Any proposals for CWE and ASVS Levels as well?

Maybe CWE-200: Exposure of Sensitive Information to an Unauthorized Actor. 

This is often verifiable externally and is likely applicable to nearly every company so I would put it in level 1.

**Comment by ismisepaul** [comment]
I'm inclined to go with @jsulinski version below as it's cleaner and to the point. 

```Verify that sensitive information is removed from the metadata of user-submitted files unless storage is consented to by the user.```

and I think ```CWE-212: Improper Removal of Sensitive Information Before Storage or Transfer``` is more applicable rather than ```CWE-200``` which seems too broad imo. 

I agree this should be at ASVS level 1.

I'm not sure about including files generated by an application where I think it makes more sense to keep "user-submitted file". This is because the original intention was to protect users sensitive information contained in files (photos, docs etc.) that is generated by an application on their local device (e.g. camera app, word processor, audio recorder) when the files are uploaded to an application (e.g. social media, cloud storage).

I think metadata generated by an application is probably a separate issue where it would be applicable to camera apps, word processors, audio recorder etc.

**Comment by elarlang** [comment]
Ok, agree with "generated by application" comment. Actually it's possible to use current 14.3.3 for situations where application reveals component versions in generated file metadata.

To conclude all mentioned pieces:

Proposal:
* [Label](https://github.com/OWASP/ASVS/blob/master/CONTRIBUTING.md): `ADDED`
* Category: [V8.3 Sensitive Private Data](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x16-V8-Data-Protection.md#v83-sensitive-private-data)
* Id: `8.3.10`
* Requirement: Verify that sensitive information is removed from the metadata of user-submitted files unless storage is consented to by the user.
* Levels: 1, 2, 3
* CWE: [CWE-212](https://cwe.mitre.org/data/definitions/212.html)

Now I think it's PR-ready :)

**Comment by jmanico** [comment]
I await your PR. :)

**Comment by jsulinski** [comment]
Perhaps @ismisepaul should submit the PR as it was his idea and first draft. Will also put him on the contributors list!

Just let me know if I can be helpful. Thanks for the hard work all!

**Comment by ismisepaul** [comment]
Pull request open, thanks everyone it was a pleasure. Let me know if I need to do anything else?

Love the project!

**Comment by elarlang** [comment]
merged long time ago
