### ISSUE TITLE
Extra title / empty paragraph "Security Verification Requirements" in V3 and V4 categories

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#968]
For category V3 and V4 there is extra title 'Security Verification Requirements' before actual requirements.

Problems:

  * it's "empty paragraph", just a title with the same level like next title after that
  * it's only for two categories - it should for all or for nowhere

[V3](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x12-V3-Session-management.md#security-verification-requirements):
```
## Security Verification Requirements

## V3.1 Fundamental Session Management Security
```

[V4](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x12-V4-Access-Control.md#security-verification-requirements):
```
## Security Verification Requirements

## V4.1 General Access Control Design
```

If there is no good explanation why those extra titles should be there, I propose to remove them.

**Comment by jmanico** [comment]
Can we add a paragraph here as opposed to removing the subtitles?

**Comment by elarlang** [comment]
What this paragraph should contain? And then it makes sense to add to all other categories as well.

**Comment by jmanico** [comment]
I agree to delete the extra titles that do not have a description. When we are willing to add descriptions in we can bring them back. You're welcome to PR this one @elarlang
