### ISSUE TITLE
ASVS L2 that should be L1 but isn't automatable

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/ASVS#969]
ASVS L1 is clear that it tries its best to contain all checks that _can_ be automated, and it sounds wonderful.

As I was going through [section 2.4](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#v24-credential-storage), it clearly mentions that L2 controls MUST be switched to L1 (and I definitely agree with that) if someone is doing a code/architecture review. I was not aware of that unless I read it in the repository, versus reading it from a checklist.

Is there anything that we can do to maybe flag L2s that should be L1s but aren't automatable? I don't know what other checks I might have to do while doing an architecture review for L1, and this might be tricky.

**Comment by elarlang** [comment]
Seems like duplicate to #840 (+ #956 )

**Comment by ThunderSon** [comment]
Definitely 840. I don't see a lot of meaning behind 956 (just from the description), it lacks a lot on the focus. Closing this in favor of 840. Thanks :)
