### ISSUE TITLE
Typos in Figure 1

### ISSUE THREAD

**Issue by jasonamorrow** [OWASP/ASVS#97]
Typo in Figure 1 on Page 8 "TOOL/SERVICE PROVDER"

Also Typo in the PROCUREMENT section, 3rd step "DESIGN-LaEVEL"

**Comment by vanderaj** [comment]
Wow. Thank you!

**Comment by vanderaj** [comment]
Actually reviewing this, this is the mid 2000's way of using the ASVS, where the verification performer is external to the organization being reviewed. We really REALLY want architects and developers to use the ASVS, so this diagram is not that helpful. 

I've deleted it completely.
