### ISSUE TITLE
3.4.4 requirement cleanup and improvement

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#986]
Requirement [3.4.4](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x12-V3-Session-management.md#v34-cookie-based-session-management)

> 3.4.4 Verify that cookie-based session tokens use "__Host-" prefix **(see references)** to provide session cookie confidentiality.

Proposal: cleanup, remove "(see references)", and change " to ' for `__Host-`, as other technical terms seems to use `'` as well.

3.4.4 Verify that cookie-based session tokens use '__Host-' prefix to provide session cookie confidentiality.

Phrase "to provide session cookie confidentiality" is confusing for me. `__Host-` prefix sets some limitation for setting a cookie, like cookie must be host-only (no Domain attribute set), Path with value `/` and `Secure` attribute used. How those limitations have the meaning "provide confidentiality"?

Using `__Host-` for a cookie means, that you can not write competitive cookie (many cookies with the same name) - from another subdomain or with another domain value or with different path value.

**Comment by jmanico** [comment]
I almost never use __Host- because of it's limits. I agree this is a problematic requirement. How about...

_3.4.4 Verify that cookie-based session tokens use '__Host-' prefix when the cookie should be limited to that one host only to provide session cookie confidentiality._

**Comment by elarlang** [comment]
Examples:
```
Set-Cookie: A=1; Path=/; Secure
Set-Cookie: __Host-B=1; Path=/; Secure
```

Cookie `__Host-B` does not have any extra benefit on confidentiality here over cookie `A`.

But it has extra benefits on integrity:

  * you can not override `__Host-B` from another subdomain, but you can create cookie with name `A`, which is matching for your domain
  * you can not create competitive for `__Host-B` using different value for `Path` attribute, but you can cause a lot of mess with setting cookie name `A` with more precise path, and cause client-side based DoS attack for example - browser sends usually cookies with more precise path first and server usually takes the first one. So you can block some functionality.

`__Host-` prefix improving integrity, but does not make it bullet-proof.

**Comment by jmanico** [comment]
I agree confidentiality is not the right word for this requirement. Something like:

_3.4.4 Verify that cookie-based session tokens use `'__Host-'` prefix when the cookie should be limited to sending host only so cookies do not span different subdomains or protocols._

**Comment by elarlang** [comment]
Just link to another cookie-related issue, as those need be looked together #978

**Comment by elarlang** [comment]
> _3.4.4 Verify that cookie-based session tokens use `'__Host-'` prefix when the cookie should be limited to sending host only so cookies do not span different subdomains or protocols._

Cookie can be "host-only" also without `__Host-` prefix.

To say it all out, it would be something like that (language improvement):
3.4.4 Verify that cookie-based session tokens use '__Host-' prefix to provide confidence for the application that cookie is written by the same host using secure connection and the cookie does not have any competitive cookies with the same name but with different Host or Domain and Path combinations.

I'm also ok with "3.4.4 Verify that cookie-based session tokens use '__Host-' prefix."

**Comment by elarlang** [comment]
Need wordsmithing help here as well to create valid and correct requirement text from my points in previous comment.

Or we can be happy with "3.4.4 Verify that cookie-based session tokens use '__Host-' prefix."?

**Comment by jmanico** [comment]
Finished. https://github.com/OWASP/ASVS/pull/1047
