### ISSUE TITLE
Out of band authenticators overlap

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/ASVS#987]
In [v2.7](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#v27-out-of-band-verifier), specifically 2.7.1  and 2.7.4, there is an overlap of requirements.
The first mentions not to have by default SMS for example, which is clear text, easily retrievable and logged.
In the second, it forces out of band verifiers to be over a secure channel.

Let's say an SMS based OOB was provided, by default or not, the other requirement fails as a direct cause of this.

I believe that having SMS is L1, versus having TOTP and other secure OOB implementations to be L2. A lot of companies can't provide anything but SMS because the people using them are non-technical, and we're saying implementing SMS is as bad as not having SMS since it doesn't even pass level 1 requirements.

**Comment by jmanico** [comment]
I think this is an astute observation.

I talked to Jim Fenton (the author of NIST SP800-63) about this recently. He said for AAL-1 MFA is not needed. For AAL-2 applications, SMS (and other NIST restricted authenticators) are only acceptable for AAL-2 if another stronger method is made available (and is default). 

So what we are missing for this entire section is that different types of authenticator requirements are necessary for different risk levels of applications.

Is there a way to acknowledge your concerns with all of this in mind?

**Comment by ThunderSon** [comment]
It depends on the direction of the section. If you want to be as close as possible to NIST, then the requirements I mentioned should be L2, and not L1.

Now if I want to be picky, if you look at 2.5.6, it mentions as well the communication of tokens, and having TOTPs is definitely not L1, and most probably an email or SMS OTP will be sent.

My advice would go to say "Have SMS or email as an OOB verifier" as a nice to have, as it's already implemented in other areas of the application and should be easily doable.

Open for deeper discussions on this, it's never straight forward around these topics.

**Comment by jmanico** [comment]
I like the direction you're going in. Would you care to provide what you think the PR should look like? I think your concern is very fair but I'm not sure how to word it.

**Comment by ThunderSon** [comment]
Looking at this, what is the feeling on moving 2.7.1 and 2.7.4 to L2?
I believe doing that opens up the door to having SMS (or clear text) OTPs would become fine since it's required in other L1 requirements, and that enforce that it should be short lived.

I was looking at 2.2.2; this is a different view as well on this specific topic, and I think a review of all authenticator requirements, their levels, etc. across V2 to be reviewed.

If this is something you agree with, I can take this on to detail some further thoughts by end of week and get some consensus on it.
Otherwise, let me know what you think about this.

**Comment by tghosth** [comment]
To me [2.7.1](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x11-V2-Authentication.md#v27-out-of-band-verifier) needs to be L1 but I would be open to [2.7.4](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x11-V2-Authentication.md#v27-out-of-band-verifier) becoming level 2.

I think 2.2.2 is talking about primary authentication and 2.7.x is talking about MFA.

@ThunderSon how do you want to proceed?

**Comment by tghosth** [comment]
@ThunderSon I will probably close during mid-May if there is no further comment.
