### ISSUE TITLE
discussion/proposal: new requirement - report-to HTTP response header

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#990]
I think we should have requirement for `Report-To` response header to have "collection" point(s) for messages from browser.

Browser support is not maybe there yet (https://caniuse.com/mdn-http_headers_report-to), opened for discussion and proposals.

**Comment by elarlang** [comment]
Not there yet.

**Comment by cmlh** [comment]
The link on _Can I use_ to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to was moved.

I believe this should be included as browser support is in progress so this issue should be deferred (added to a future milestone) rather than closed @elarlang?
