### ISSUE TITLE
Align PCI-DSS v3.2.1 Requirement 6.5 to CWE

### ISSUE THREAD

**Issue by cmlh** [OWASP/ASVS#991]
Child of Issue https://github.com/OWASP/ASVS/issues/317#issuecomment-829077114 specific to [PCI-DSS v3.2.1 Requirement 6.5](https://user-images.githubusercontent.com/136826/116528539-4b757000-a91f-11eb-8be3-189a1f01fe16.png)

The process will be to extract the CWE of ASVS 4.0.2 and the following to be forked into ASVS PCI-DSS:

The following "CERT Secure Coding Standard" cited by [MITRE](https://cwe.mitre.org/data/index.html) are:
- [Perl](https://cwe.mitre.org/data/definitions/1178.html) 
- [C](https://cwe.mitre.org/data/definitions/1154.html) 

The [OWASP Top Ten 2017](https://cwe.mitre.org/data/definitions/1026.html) cited by [MITRE](https://cwe.mitre.org/data/index.html).

Finally, the [MITIRE Top 25 (2020)](https://cwe.mitre.org/data/definitions/1350.html).

**Comment by elarlang** [comment]
Any clear proposal or it makes sense to close this issue?

**Comment by cmlh** [comment]
"... Extract the CWE of ASVS 4.0.2 and the following to be forked into ASVS PCI-DSS"

**Comment by danielcuthbert** [comment]
already discussed this over at 317 so no need to keep so many open on the same subject

**Comment by cmlh** [comment]
This is a child issue to https://github.com/OWASP/ASVS/issues/317#issuecomment-829077114

![image](https://user-images.githubusercontent.com/136826/126561781-071e7558-07b3-4b44-91ba-45cb70669d58.png)
