### ISSUE TITLE
Requirement: 9.1.2 - Insert Test Case Implementation(s)

### ISSUE THREAD

**Issue by cmlh** [OWASP/ASVS#992]
Proposal:
* _[Requirement: 9.1.2](https://github.com/cmlh/ASVS/blob/master/4.0/en/0x17-V9-Communications.md#v91-client-communications-security) [MODIFIED] Verify using online or up to date TLS testing tools that only strong cipher suites are enabled, with the strongest cipher suites set as preferred._ 
  * Insert _["EXAMPLE: TLS version detection using a packet capture"](https://aws.amazon.com/blogs/security/tls-1-2-required-for-aws-fips-endpoints/)_ and _["Is there more assistance available to help verify or update client applications?"](https://aws.amazon.com/blogs/security/tls-1-2-to-become-the-minimum-for-all-aws-fips-endpoints/)_ test cases from AWS.
  * Insert [NSA](https://github.com/nsacyber/Mitigating-Obsolete-TLS#scanning-tools) test case.

As there is crossover with the [OWASP Testing Guide](https://github.com/OWASP/wstg) please transfer this issue if preferred?

**Comment by elarlang** [comment]
Proposal for requirement is something what you can commit as requirement text for example. At the moment there is just a copy-paste from current requirement text and 2 links.

Can you please clarify, what is your expectation, what should happen next with this issue?

**Comment by cmlh** [comment]
To follow on from @tghosth https://github.com/OWASP/ASVS/issues/979#issuecomment-839434790

> Also, as a general note (which I am not sure is documented anywhere), we don't like to include links within requirements (the links to the proactive controls are an exception which we are planning to remove in the next major release).

I have opened https://github.com/OWASP/wstg/issues/747 and will close this [ASVS} Issue.
