### ISSUE TITLE
discussion/new requirement: inventory/documentation for "allow listed" sources and communications

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#993]
Over time there is need to configure every kind of allow lists, like *-src and frame-ancestors for Content-Security-Policy (current requirements 14.4.3 and 14.4.7), allowed Origin's (14.2.3, 13.5.2, 14.5.3), allow list of resources or systems to which the server can send requests or load data/files from (12.6.1).

Problem to solve - if it's not documented, then sooner or later it's not clear, why there is some item in allow list and those may stay there even if thay are not needed (anymore).

Idea - create new requirement which requires those whitelists to be documented. Category probably 1.14.

**Comment by jmanico** [comment]
Per Google research (weischelbalm/spagneullo) 94% of allow list policies are bypassable. It’s more secure to focus on a nonce or hash based CSP. Strict-dynamic makes this easier.

https://m.youtube.com/watch?v=5m7IPjC2v70

**Comment by elarlang** [comment]
Don't take this CSP out of context here. I have this proposal even if we remove CSP part and say that for CSP use nonces instead.

Think about requirement 14.2.5 (for me it seems V1 requirement btw):
> V14.2.5 Verify that an inventory catalog is maintained of all third party libraries in use.

Same with 12.6.1:
> V12.6.1 Verify that the web or application server is configured with an allow list of resources or systems to which the server can send requests or load data/files from.

If there is configured list of hosts, then there should be documentation which describes - why some host exists in this allow list.

**Comment by tghosth** [comment]
I like the concept of ensuring that these sorts of lists are explicitly documented and I agree that this sounds like a V1 control.

@jmanico I think the CSP point is a good question that needs to be looked at separately, do you want to open a specific issue for it

**Comment by jmanico** [comment]
Done here, @tghosth https://github.com/OWASP/ASVS/issues/1311

**Comment by tghosth** [comment]
@elarlang let me know if you are able to draft something :)

**Comment by tghosth** [comment]
@elarlang where are we with the original part of this issue, are you going to draft something?

**Comment by elarlang** [comment]
I try to get this one moving as well.

We have requirement like 12.6.1:
_V12.6.1 Verify that the web or application server is configured with an allow list of resources or systems to which the server can send requests or load data/files from._

Precondition here is - how you can test this if you don't have this "allow list of accepted resources" documented.

The goal for the requirement - we need to have the needs for the application documented, otherwise you can not write actual implementation for allow-list and also we can not test it.

I don't know how to build the requirement text, but it should say - all the needs for requests to external resources by the servers must be documented.

**Comment by tghosth** [comment]
How about:

> Verify that the allow-lists being used for security controls across the application are centrally documented and used for all implementations.

**Comment by elarlang** [comment]
Related requirements.

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.1.4** | Verify documentation and justification of all the application's trust boundaries, components, and significant data flows. | | ✓ | ✓ | 1059 |
| **1.1.5** | Verify definition and security analysis of the application's high-level architecture and all connected remote services. ([C1](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 1059 |

**Comment by tghosth** [comment]
> Verify that the allow-lists being used for security controls such as CSP and allowed outbound access across the application are centrally documented and used for all implementations.

12.6.1, 14.x?

Add somewhere to 1.x

**Comment by tghosth** [comment]
@set-reminder 5 weeks @tghosth to look at this

**Comment by elarlang** [comment]
Update, previous 12.6.1 is now moved to 14.7.1.

**V14.7 Web or Application Server Configuration**

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **14.7.1** | [MOVED FROM 12.6.1, GRAMMAR] Verify that the web or application server is configured with an allow list of resources or systems to which the server can send requests or load data or files from. | ✓ | ✓ | ✓ | 918 |

Pre-condition for implementing 14.7.1 is documented allow-list of resources - and this is the reason why we need the documentation requirement.

It feels that it is covered by:
| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.1.4** | Verify documentation and justification of all the application's trust boundaries, components, and significant data flows. | | ✓ | ✓ | 1059 |
| **1.1.5** | Verify definition and security analysis of the application's high-level architecture and all connected remote services. ([C1](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 1059 |

But those requirements will be potentially removed via #1541.

Also related: https://github.com/OWASP/ASVS/issues/1620#issuecomment-1750098336 (but I see it as separate requirement)

**Comment by tghosth** [comment]
Need to create documentation requirements for this. Potentially separate for CSP and for backend resource accesses.

**Comment by tghosth** [comment]
So do you think that 1.1.5 and 14.7.1 need to be merged/deduplicated @elarlang ?

**Comment by elarlang** [comment]
I consider 1.1.5 as a documentation requirement that is pre-condition for implementing and testing 14.6.1.

**Comment by tghosth** [comment]
Ok so we need updated wording for 1.1.5.

Based on [this comment](https://github.com/OWASP/ASVS/issues/1184#issuecomment-2414137390) and some further modifications, I would suggest:

"_Verify that architecture documentation defines the remote services upon which the application relies and how interactions with them are secured. This should also include cases where an end user might be able to provide an external location which the application will then connect to._"

What do you think @elarlang ?

**Comment by tghosth** [comment]
I think the key point here is services outside of the application though? No?

**Comment by elarlang** [comment]
The key point is whitelist of connections needed to be able to implement allowlisted connections via requirement:
> Verify that the web or application server is configured with an allowlist of resources or systems to which the server can send requests or load data or files from.

**Comment by tghosth** [comment]
So how about:

"_Verify that architecture documentation defines a list of the remote services which the application relies on and is permitted to access, and also how interactions with them are secured. This should also include cases where an end user might be able to provide an external location which the application will then connect to_."

**Comment by elarlang** [comment]
Attempt to rearrange the focus:
> Verify that all communication needs for the application are documented. It includes external services the application relies on and cases where an end user might be able to provide an external location to which the application will then connect.

**Comment by tghosth** [comment]
Ok so @elarlang the proposal here is to rewrite 1.1.5 as follows:


OLD - "_Verify definition and security analysis of the application's high-level architecture and all connected remote services._"

NEW - "_Verify that all communication needs for the application are documented. This should include external services which the application relies upon and cases where an end user might be able to provide an external location to which the application will then connect._"

**Comment by elarlang** [comment]
> Do I understand correctly?

yes

**Comment by jmanico** [comment]
Wordsmith suggestion:

_Verify that all application communication requirements are documented, including any external services the application depends on. This documentation should also cover scenarios where an end user can specify an external location for the application to connect to_

**Comment by elarlang** [comment]
From last proposals, I prefer https://github.com/OWASP/ASVS/issues/993#issuecomment-2439873161. Jim's version splits the requirement weird way.

**Comment by tghosth** [comment]
Opened #2198 @elarlang
