### ISSUE TITLE
2.4.2 Salt size recommendation

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/ASVS#994]
In [2.4.2](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#v24-credential-storage), it is mentioned to have a salt of 32 bits, which is barely 4 bytes.

I believe this should be raised to 128 bits, to ensure that it is random enough across the DB and across other used DBs.

The best thing would be to match the hash length and go beyond it, but that might be too much.

**Comment by Sjord** [comment]
See also #1002.

**Comment by jmanico** [comment]
https://github.com/OWASP/ASVS/issues/1000

**Comment by jmanico** [comment]
Salts have been removed from 2.4 making this issue moot.
