### ISSUE TITLE
wildcard TLS certificates

### ISSUE THREAD

**Issue by csfreak92** [OWASP/ASVS#995]
I think we should add a control in ASVS to ensure wildcard certificates are not being used across or a combination of either by production, staging and development environments. I believe it goes under `9.2 Server Communication Security` section. 

Whenever we do a security design review, we sometimes find this issue that wildcard TLS certificates are being used either on both production and staging environments, worse is across all environments. This is common among not yet mature software development organizations to use only a wildcard TLS certificate since it was at a cheaper cost and easier for them to renew and manage without looking at the security issues outlined in this article (https://www.packetlabs.net/wildcard-certificates/).  I was looking for anything related to this in ASVS but couldn't find any. I believe we need to add a requirement to ensure wildcard TLS certificates are not being used across production, staging and development environments. 

Suggested requirement is to prevent wildcard TLS certificates and only use a unique TLS certificate per environment/deployment. This would not be pentestable, but something a security review or hybrid pentest review would be able to flag as an issue.

**Comment by csfreak92** [comment]
I have been waiting for the community for any thoughts about this. How about you @jmanico, @elarlang?

**Comment by jmanico** [comment]
I think this would be a solid requirement. I am not a super expert in this area which is why I did not chime in yet. But I think a requirement here is a solid idea.

**Comment by elarlang** [comment]
I have pretty much the same feedback as Jim wrote. I asked from my coworker and he was 100% agree with your problem statement, @csfreak92 

Please write clear requirement proposal, then we can fine-tune details if needed.

**Comment by jmanico** [comment]
It's always a good day when Elar actually agrees with me! 😸

**Comment by mgargiullo** [comment]
I know I'm late to the party, but for clarification, are we talking about a complete elimination of the acceptability of wildcard certificates?
 
Could it be acceptable to use the wildcard in dev, test, and staging, but a unique cert in production?

I read the article and agree with its technical merrits, but it reads like an ad for Let's Encrypt. Not that I oppose what they do, I'm all for Let's Encrypt and use them in many places. 

This boils down to the _potential_ issue, _if_ a server that leverages a wildcard certificate is compromised. There is nothing inherently insecure about using wildcard certificates if managed appropriately.

**Comment by jmanico** [comment]
Fair point @mgargiullo can we consider this in the PR?

**Comment by mgargiullo** [comment]
@jmanico  I believe so. I'd like to see how @csfreak92 addresses it.

**Comment by csfreak92** [comment]
Not totally late to the party @mgargiullo, well I think you have a good point and it could be acceptable having the wildcard TLS cert in dev, test and staging, but never have the same thing in production. I do understand that some organizations prefer it this way for easy management of certificates. 

While you are correct, using wildcard TLS certificates are not inherently insecure, but the management of these certificates are mostly poor in non-mature organizations. They seldom rotate or revoke those and every deployment has the same certificate which is only a problem in the event of a compromised certificate (attack vectors here would either if someone who has former access to these certificates left the company and has a malicious intent or a server breach). Yes, the article sounds like it is pushing for Let's Encrypt (please ignore this ad part as I cannot find a good reference for this issue). 

@jmanico, @elarlang, I am no expert in TLS certificates either, but I think this is a good addition, so I will be drafting something for the PR. Let me think deeper if I miss something to consider all cases. I will be having the PR soon.

**Comment by jmanico** [comment]
Thanks, @csfreak92 we always appreciate your contributions!

**Comment by mgargiullo** [comment]
@csfreak92  I was thinking about this last night and again this morning, then I read your reply above (good stuff).

While I have not written any CA management software, I've been involved in a good deal of architecture of PKI solutions over the years. The thought process of the change is that if the cert and associated key of a wildcard cert is compromised on the dev, test, or staging servers, it could compromise the security posture of the production server, assuming it's using the same wildcard cert.

If that statement is accurate (regarding the risk of wildcard certificates), if the certificate's key is appropriately protected (requiring a password), how does an attacker's access to the key and certificate file (but not the key's password) make the wildcard cert weaker than a host-specific certificate?

You could also have two unique wildcard certificates for the same domain but created with different keys and CSRs. One deployed on dev, test, and staging, while the other deployed on www.domain.com and api.domain.com (both FQDNs servicing the same application).  This would separate production from non-production and ease management. If either certificate gets compromised, it's as simple as revoking one cert. 

I don't think wildcard certificates themselves add a high risk to an environment, but the mismanagement of certificates is a greater risk.

**Comment by csfreak92** [comment]
Hi @mgargiullo, I thought about it for a long time too. I definitely agree with you on compromise of any of the other environments' certificate (dev, test or staging servers) could lead to compromise of the production server's security posture assuming all of them are using the same wildcard certificate for the production server as well. 

Re: if the wildcard cert key is protected properly (with password or whatever means we could think of), then you are correct compromising a wildcard cert does not matter as much as compromising a host-specific cert. 

Re: two unique wildcard certificates (one for all non-production environments and I am assuming the one deployed on the domain is for production environment??) to separate environments and easier certificate management I think is one good solution.  Could you please clarify the point about CSRs? I am a bit lost there. 

I agree with you that using wildcard certificates adds a high risk to an environment had it been properly protected (proper management of certificates for addition, deletion, revocation and rotation). Although it seems like using wildcard certificates adds an inherent risk due to the way they are mismanaged. My question to you is, would you say we should just focus for a control about good TLS certificate management and add another control or a reminder about wildcard certs with an (*) asterisk regarding the points we talked about here in the thread? 


P.S. @jmanico, @elarlang, sorry it took me a while to get back to my outstanding issues for ASVS as life and career stuff got busy, but will soon draft a PR for this issue this weekend.

**Comment by mgargiullo** [comment]
> Could you please clarify the point about CSRs? I am a bit lost there.

In theory, you could create two distinct CSRs to have two certificates created using two distinct keys. 
Example:
`openssl req -new -newkey rsa:2048 -nodes -out nonprod_star_mydomain.com.csr -keyout nonprod_star_mydomain.com.key -subj "/C=US/ST=New York/L=New York/O=My Company, Inc./OU=NonProd/CN=*.mydomain.com"`

`openssl req -new -newkey rsa:2048 -nodes -out prod_star_mydomain.com.csr -keyout prod_star_mydomain.com.key -subj "/C=US/ST=New York/L=New York/O=My Company, Inc./OU=Prod/CN=*.mydomain.com"`

Regarding certificate management in general, we should focus on secure certificate management practices instead of stating a technology itself is insecure. If we want to expand the cryptography areas to include checks around certificate management, secure key management, etc., I'm all for it.

I think one of the biggest issues is that people choose to just hit enter when prompted for a password while generating the key. The second biggest is the reuse of keys when renewing certificates.

**Comment by csfreak92** [comment]
@mgargiullo, I agree we should have a requirement regarding certificate management in general and it will best go under cryptography section/requirements. Although, I would humbly suggest to still have one for avoiding the use of the same TLS wildcards on different environments (at least non-prod and prod envs) as a best practice. I can draft the one for TLS wildcards requirement and maybe you want to take on the cryptography requirement one regarding cert management? 

+1 on people just hitting password prompts whenever people generate keys, I noticed that a lot of people do that.

**Comment by tghosth** [comment]
@mgargiullo i will probably close this during mid-May if there are no further comments.
