### ISSUE TITLE
2.1.7 small fix

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#998]
SP800-63 says 50,000-150,000 common passwords, not 50,000-100,000 common passwords

**Comment by jmanico** [comment]
We should also split 2.1.7 into two requirements, one for common passwords and another for credential stuffing defense

**Comment by elarlang** [comment]
Just for mapping:
- spliting 2.1.7 is proposed in https://github.com/OWASP/ASVS/issues/683 (Recommendation 3)
- spliting 2.1.7 is proposed in https://github.com/OWASP/ASVS/issues/841#issuecomment-800976053, https://github.com/OWASP/ASVS/issues/841#issuecomment-800977763

**Comment by elarlang** [comment]
in #841 / https://github.com/OWASP/ASVS/commit/10b865f6a35bed828546472436fd5ca22bf38942 changed to:
```
Verify that passwords submitted during account registration or password change are checked against an available set of, at least, the top 3000 passwords.
```
